/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import Grid3.Four.Punct

/-!
# The per-colour bounds of a pair of colours, in region sizes and indicators

The per-colour bounds of `Grid3.Four.Bounds` for two distinct colours `y ≠ y'`, written in the
sizes of the regions of `(X, Z, T, M, B)` and the membership indicators of `y`, `y'`; and the
decomposition of every region into atoms. The right-hand sides are exactly the expressions of
`Grid3.Four.Arith.pair_all` (generated by the same script, `ai_research_notes/cx/eig/gen5.py`).
-/

open Finset

namespace Grid3
namespace Four

theorem pair_expand_C (X Z T M B : Finset ℕ) (hM : M.card = 4) (y y' : ℕ) :
    14 * betaH X Z T M B y + RC4 X Z T M B y + 2 * (14 * betaH X Z T M B y' + RC4 X Z T M B y')
      = (-6) * ((X ∩ Z).card : ℤ) + (-42) * (((X ∩ Z).filter (· ∉ M)).card : ℤ) + (12) * (((X ∩ Z).filter (· ∈ T ∩ B)).card : ℤ) + (-3) * (((X ∩ Z).filter (· ∈ T ∩ B ∩ M)).card : ℤ) + (171) * (X.card : ℤ) * (Z.card : ℤ) + (-288) * (X.card : ℤ) * ind (y' ∈ Z) + (-84) * (X.card : ℤ) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) + (336) * (X.card : ℤ) * ((Z.filter (· ∉ B)).card : ℤ) + (-84) * (X.card : ℤ) * ((Z.filter (· ∉ M)).card : ℤ) + (12) * (X.card : ℤ) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) + (-3) * (X.card : ℤ) * ((Z.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + (-144) * (X.card : ℤ) * ind (y ∈ Z) + (-288) * (Z.card : ℤ) * ind (y' ∈ X) + (-84) * (Z.card : ℤ) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) + (-84) * (Z.card : ℤ) * ((X.filter (· ∉ M)).card : ℤ) + (336) * (Z.card : ℤ) * ((X.filter (· ∉ T)).card : ℤ) + (12) * (Z.card : ℤ) * ((X.filter (· ∉ T ∩ B)).card : ℤ) + (-3) * (Z.card : ℤ) * ((X.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + (-144) * (Z.card : ℤ) * ind (y ∈ X) + (-2) * ind (y' ∈ M) * (((X ∩ Z).filter (· ∈ T ∩ B)).card : ℤ) + (494) * ind (y' ∈ X) * ind (y' ∈ Z) + (56) * ind (y' ∈ X) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) + (-224) * ind (y' ∈ X) * ((Z.filter (· ∉ B)).card : ℤ) + (56) * ind (y' ∈ X) * ((Z.filter (· ∉ M)).card : ℤ) + (-8) * ind (y' ∈ X) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) + (2) * ind (y' ∈ X) * ((Z.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + (56) * ind (y' ∈ Z) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) + (56) * ind (y' ∈ Z) * ((X.filter (· ∉ M)).card : ℤ) + (-224) * ind (y' ∈ Z) * ((X.filter (· ∉ T)).card : ℤ) + (-8) * ind (y' ∈ Z) * ((X.filter (· ∉ T ∩ B)).card : ℤ) + (2) * ind (y' ∈ Z) * ((X.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + (28) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) * ind (y ∈ Z) + (28) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) * ind (y ∈ X) + (28) * ((X.filter (· ∉ M)).card : ℤ) * ind (y ∈ Z) + (-112) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ Z) + (-4) * ((X.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ Z) + ((X.filter (· ∉ T ∩ B ∩ M)).card : ℤ) * ind (y ∈ Z) + (-1) * (((X ∩ Z).filter (· ∈ T ∩ B)).card : ℤ) * ind (y ∈ M) + (-112) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) + (28) * ((Z.filter (· ∉ M)).card : ℤ) * ind (y ∈ X) + (-4) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ X) + ((Z.filter (· ∉ T ∩ B ∩ M)).card : ℤ) * ind (y ∈ X) + (247) * ind (y ∈ X) * ind (y ∈ Z) + (-228) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) + (84) * (X.card : ℤ) * (Z.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) + (84) * (X.card : ℤ) * (Z.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) + (3) * (X.card : ℤ) * (Z.card : ℤ) * ((M.filter (· ∉ T ∩ B)).card : ℤ) + (-12) * (X.card : ℤ) * (Z.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) + (-114) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ M) + (224) * (X.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ Z) + (286) * (X.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ Z) + (-56) * (X.card : ℤ) * ind (y' ∈ M) * ((Z.filter (· ∉ B)).card : ℤ) + (-2) * (X.card : ℤ) * ind (y' ∈ M) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) + (8) * (X.card : ℤ) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ Z) + (-56) * (X.card : ℤ) * ind (y' ∈ Z) * ((M.filter (· ∉ B)).card : ℤ) + (-56) * (X.card : ℤ) * ind (y' ∈ Z) * ((M.filter (· ∉ T)).card : ℤ) + (-2) * (X.card : ℤ) * ind (y' ∈ Z) * ((M.filter (· ∉ T ∩ B)).card : ℤ) + (8) * (X.card : ℤ) * ind (y' ∈ Z) * ((T.filter (· ∉ B)).card : ℤ) + (-28) * (X.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ Z) + (-28) * (X.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ Z) + (-1) * (X.card : ℤ) * ((M.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ Z) + (4) * (X.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ Z) + (-28) * (X.card : ℤ) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) + (-1) * (X.card : ℤ) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ M) + (112) * (X.card : ℤ) * ind (y ∈ B) * ind (y ∈ Z) + (143) * (X.card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + (4) * (X.card : ℤ) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ Z) + (286) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ X) + (-56) * (Z.card : ℤ) * ind (y' ∈ M) * ((X.filter (· ∉ T)).card : ℤ) + (-2) * (Z.card : ℤ) * ind (y' ∈ M) * ((X.filter (· ∉ T ∩ B)).card : ℤ) + (224) * (Z.card : ℤ) * ind (y' ∈ T) * ind (y' ∈ X) + (8) * (Z.card : ℤ) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) + (-56) * (Z.card : ℤ) * ind (y' ∈ X) * ((M.filter (· ∉ B)).card : ℤ) + (-56) * (Z.card : ℤ) * ind (y' ∈ X) * ((M.filter (· ∉ T)).card : ℤ) + (-2) * (Z.card : ℤ) * ind (y' ∈ X) * ((M.filter (· ∉ T ∩ B)).card : ℤ) + (8) * (Z.card : ℤ) * ind (y' ∈ X) * ((T.filter (· ∉ B)).card : ℤ) + (-28) * (Z.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) + (-28) * (Z.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ X) + (-1) * (Z.card : ℤ) * ((M.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ X) + (4) * (Z.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) + (-28) * (Z.card : ℤ) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ M) + (-1) * (Z.card : ℤ) * ((X.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ M) + (143) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + (112) * (Z.card : ℤ) * ind (y ∈ T) * ind (y ∈ X) + (4) * (Z.card : ℤ) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) + (-224) * ind (y' ∈ B) * ind (y' ∈ X) * ind (y' ∈ Z) + (-372) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) + (56) * ind (y' ∈ M) * ind (y' ∈ X) * ((Z.filter (· ∉ B)).card : ℤ) + (2) * ind (y' ∈ M) * ind (y' ∈ X) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) + (56) * ind (y' ∈ M) * ind (y' ∈ Z) * ((X.filter (· ∉ T)).card : ℤ) + (2) * ind (y' ∈ M) * ind (y' ∈ Z) * ((X.filter (· ∉ T ∩ B)).card : ℤ) + (-224) * ind (y' ∈ T) * ind (y' ∈ X) * ind (y' ∈ Z) + (-24) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) * ind (y' ∈ Z) + (56) * ind (y' ∈ X) * ind (y' ∈ Z) * ((M.filter (· ∉ B)).card : ℤ) + (56) * ind (y' ∈ X) * ind (y' ∈ Z) * ((M.filter (· ∉ T)).card : ℤ) + (2) * ind (y' ∈ X) * ind (y' ∈ Z) * ((M.filter (· ∉ T ∩ B)).card : ℤ) + (-8) * ind (y' ∈ X) * ind (y' ∈ Z) * ((T.filter (· ∉ B)).card : ℤ) + (28) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + (28) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + ((M.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + (-4) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + (28) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + ((X.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + (28) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + ((Z.filter (· ∉ T ∩ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + (-112) * ind (y ∈ B) * ind (y ∈ X) * ind (y ∈ Z) + (-186) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) + (-112) * ind (y ∈ T) * ind (y ∈ X) * ind (y ∈ Z) + (-12) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) * ind (y ∈ Z) + (56) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) + (56) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) + (2) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) + (2) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) * ((T.filter (· ∉ B)).card : ℤ) + (X.card : ℤ) * (Z.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) + (28) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) + (28) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) + (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) + (-168) * (X.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ Z) + (-56) * (X.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ Z) + (-6) * (X.card : ℤ) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ Z) + (-2) * (X.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ Z) * ((T.filter (· ∉ B)).card : ℤ) + (-1) * (X.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + (-84) * (X.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ Z) + (-28) * (X.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ Z) + (-3) * (X.card : ℤ) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ Z) + (-56) * (Z.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ X) + (-168) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ X) + (-6) * (Z.card : ℤ) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) + (-2) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ X) * ((T.filter (· ∉ B)).card : ℤ) + (-1) * (Z.card : ℤ) * ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + (-28) * (Z.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ X) + (-84) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ X) + (-3) * (Z.card : ℤ) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) + (168) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) + (168) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ X) * ind (y' ∈ Z) + (14) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) * ind (y' ∈ Z) + (2) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) * ((T.filter (· ∉ B)).card : ℤ) + ((T.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) + (84) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) + (84) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ X) * ind (y ∈ Z) + (7) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) * ind (y ∈ Z) := by
  unfold betaH RC4 om
  simp only [pc_eq, out_eq, out2_eq, in2_eq, xz_eq, outIn_eq, Finset.mem_inter, ind_and, ind_not, hM, Nat.cast_ofNat]
  ring

theorem pair_expand_H (X Z T M B : Finset ℕ) (hM : M.card = 4) (y y' : ℕ) :
    betaH X Z T M B y + 2 * betaH X Z T M B y'
      = (-3) * (((X ∩ Z).filter (· ∉ M)).card : ℤ) + (12) * (X.card : ℤ) * (Z.card : ℤ) + (-20) * (X.card : ℤ) * ind (y' ∈ Z) + (-6) * (X.card : ℤ) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) + (24) * (X.card : ℤ) * ((Z.filter (· ∉ B)).card : ℤ) + (-6) * (X.card : ℤ) * ((Z.filter (· ∉ M)).card : ℤ) + (-10) * (X.card : ℤ) * ind (y ∈ Z) + (-20) * (Z.card : ℤ) * ind (y' ∈ X) + (-6) * (Z.card : ℤ) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) + (-6) * (Z.card : ℤ) * ((X.filter (· ∉ M)).card : ℤ) + (24) * (Z.card : ℤ) * ((X.filter (· ∉ T)).card : ℤ) + (-10) * (Z.card : ℤ) * ind (y ∈ X) + (34) * ind (y' ∈ X) * ind (y' ∈ Z) + (4) * ind (y' ∈ X) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) + (-16) * ind (y' ∈ X) * ((Z.filter (· ∉ B)).card : ℤ) + (4) * ind (y' ∈ X) * ((Z.filter (· ∉ M)).card : ℤ) + (4) * ind (y' ∈ Z) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) + (4) * ind (y' ∈ Z) * ((X.filter (· ∉ M)).card : ℤ) + (-16) * ind (y' ∈ Z) * ((X.filter (· ∉ T)).card : ℤ) + (2) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) * ind (y ∈ Z) + (2) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) * ind (y ∈ X) + (2) * ((X.filter (· ∉ M)).card : ℤ) * ind (y ∈ Z) + (-8) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ Z) + (-8) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) + (2) * ((Z.filter (· ∉ M)).card : ℤ) * ind (y ∈ X) + (17) * ind (y ∈ X) * ind (y ∈ Z) + (-16) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) + (6) * (X.card : ℤ) * (Z.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) + (6) * (X.card : ℤ) * (Z.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) + (-8) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ M) + (16) * (X.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ Z) + (20) * (X.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ Z) + (-4) * (X.card : ℤ) * ind (y' ∈ M) * ((Z.filter (· ∉ B)).card : ℤ) + (-4) * (X.card : ℤ) * ind (y' ∈ Z) * ((M.filter (· ∉ B)).card : ℤ) + (-4) * (X.card : ℤ) * ind (y' ∈ Z) * ((M.filter (· ∉ T)).card : ℤ) + (-2) * (X.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ Z) + (-2) * (X.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ Z) + (-2) * (X.card : ℤ) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) + (8) * (X.card : ℤ) * ind (y ∈ B) * ind (y ∈ Z) + (10) * (X.card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + (20) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ X) + (-4) * (Z.card : ℤ) * ind (y' ∈ M) * ((X.filter (· ∉ T)).card : ℤ) + (16) * (Z.card : ℤ) * ind (y' ∈ T) * ind (y' ∈ X) + (-4) * (Z.card : ℤ) * ind (y' ∈ X) * ((M.filter (· ∉ B)).card : ℤ) + (-4) * (Z.card : ℤ) * ind (y' ∈ X) * ((M.filter (· ∉ T)).card : ℤ) + (-2) * (Z.card : ℤ) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) + (-2) * (Z.card : ℤ) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ X) + (-2) * (Z.card : ℤ) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ M) + (10) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + (8) * (Z.card : ℤ) * ind (y ∈ T) * ind (y ∈ X) + (-16) * ind (y' ∈ B) * ind (y' ∈ X) * ind (y' ∈ Z) + (-26) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) + (4) * ind (y' ∈ M) * ind (y' ∈ X) * ((Z.filter (· ∉ B)).card : ℤ) + (4) * ind (y' ∈ M) * ind (y' ∈ Z) * ((X.filter (· ∉ T)).card : ℤ) + (-16) * ind (y' ∈ T) * ind (y' ∈ X) * ind (y' ∈ Z) + (4) * ind (y' ∈ X) * ind (y' ∈ Z) * ((M.filter (· ∉ B)).card : ℤ) + (4) * ind (y' ∈ X) * ind (y' ∈ Z) * ((M.filter (· ∉ T)).card : ℤ) + (2) * ((M.filter (· ∉ B)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + (2) * ((M.filter (· ∉ T)).card : ℤ) * ind (y ∈ X) * ind (y ∈ Z) + (2) * ((X.filter (· ∉ T)).card : ℤ) * ind (y ∈ M) * ind (y ∈ Z) + (2) * ((Z.filter (· ∉ B)).card : ℤ) * ind (y ∈ M) * ind (y ∈ X) + (-8) * ind (y ∈ B) * ind (y ∈ X) * ind (y ∈ Z) + (-13) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) + (-8) * ind (y ∈ T) * ind (y ∈ X) * ind (y ∈ Z) + (4) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) + (4) * (X.card : ℤ) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) + (2) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) + (2) * (X.card : ℤ) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) + (-12) * (X.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ Z) + (-4) * (X.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ Z) + (-6) * (X.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ Z) + (-2) * (X.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ Z) + (-4) * (Z.card : ℤ) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ X) + (-12) * (Z.card : ℤ) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ X) + (-2) * (Z.card : ℤ) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ X) + (-6) * (Z.card : ℤ) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ X) + (12) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) + (12) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ X) * ind (y' ∈ Z) + (6) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) + (6) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ X) * ind (y ∈ Z) := by
  unfold betaH
  simp only [pc_eq, out_eq, out2_eq, outIn_eq, Finset.mem_inter, ind_and, ind_not, hM, Nat.cast_ofNat]
  ring

theorem dec_xT (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 9 + ind (y' ∈ X) + (-1) * ((X.filter (· ∉ T)).card : ℤ) + ind (y ∈ X) + (-1) * ind (y' ∈ T) * ind (y' ∈ X) + (-1) * ind (y ∈ T) * ind (y ∈ X) = 0 := by
  have h := card_xT X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 21 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 7 + ind (y' ∈ X) + (-1) * ((X.filter (· ∉ M)).card : ℤ) + ind (y ∈ X) + (-1) * ind (y' ∈ M) * ind (y' ∈ X) + (-1) * ind (y ∈ M) * ind (y ∈ X) = 0 := by
  have h := card_xM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xW (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 7 + atom X Z T M B {y, y'} 9 + ind (y' ∈ X) + (-1) * ((X.filter (· ∉ T ∩ B)).card : ℤ) + ind (y ∈ X) + (-1) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) + (-1) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) = 0 := by
  have h := card_xW X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xWM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 21 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 7 + atom X Z T M B {y, y'} 9 + ind (y' ∈ X) + (-1) * ((X.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + ind (y ∈ X) + (-1) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) + (-1) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) = 0 := by
  have h := card_xWM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_zB (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ Z) + (-1) * ((Z.filter (· ∉ B)).card : ℤ) + ind (y ∈ Z) + (-1) * ind (y' ∈ B) * ind (y' ∈ Z) + (-1) * ind (y ∈ B) * ind (y ∈ Z) = 0 := by
  have h := card_zB X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_zM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 22 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ Z) + (-1) * ((Z.filter (· ∉ M)).card : ℤ) + ind (y ∈ Z) + (-1) * ind (y' ∈ M) * ind (y' ∈ Z) + (-1) * ind (y ∈ M) * ind (y ∈ Z) = 0 := by
  have h := card_zM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_zW (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ Z) + (-1) * ((Z.filter (· ∉ T ∩ B)).card : ℤ) + ind (y ∈ Z) + (-1) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ Z) + (-1) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ Z) = 0 := by
  have h := card_zW X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_zWM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 22 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ Z) + (-1) * ((Z.filter (· ∉ T ∩ B ∩ M)).card : ℤ) + ind (y ∈ Z) + (-1) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ Z) + (-1) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ Z) = 0 := by
  have h := card_zWM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_mT (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 24 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 8 + atom X Z T M B {y, y'} 9 + ind (y' ∈ M) + (-1) * ((M.filter (· ∉ T)).card : ℤ) + ind (y ∈ M) + (-1) * ind (y' ∈ M) * ind (y' ∈ T) + (-1) * ind (y ∈ M) * ind (y ∈ T) = 0 := by
  have h := card_mT X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_mB (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 12 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 8 + atom X Z T M B {y, y'} 9 + ind (y' ∈ M) + (-1) * ((M.filter (· ∉ B)).card : ℤ) + ind (y ∈ M) + (-1) * ind (y' ∈ B) * ind (y' ∈ M) + (-1) * ind (y ∈ B) * ind (y ∈ M) = 0 := by
  have h := card_mB X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_mW (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 12 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 24 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 8 + atom X Z T M B {y, y'} 9 + ind (y' ∈ M) + (-1) * ((M.filter (· ∉ T ∩ B)).card : ℤ) + ind (y ∈ M) + (-1) * ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) + (-1) * ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) = 0 := by
  have h := card_mW X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_mXT (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 9 + (-1) * (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) + ind (y' ∈ M) * ind (y' ∈ X) + ind (y ∈ M) * ind (y ∈ X) + (-1) * ind (y' ∈ M) * ind (y' ∈ T) * ind (y' ∈ X) + (-1) * ind (y ∈ M) * ind (y ∈ T) * ind (y ∈ X) = 0 := by
  have h := card_mXT X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_mZB (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + (-1) * (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) + ind (y' ∈ M) * ind (y' ∈ Z) + ind (y ∈ M) * ind (y ∈ Z) + (-1) * ind (y' ∈ B) * ind (y' ∈ M) * ind (y' ∈ Z) + (-1) * ind (y ∈ B) * ind (y ∈ M) * ind (y ∈ Z) = 0 := by
  have h := card_mZB X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xz (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 31 + atom X Z T M B {y, y'} 7 + (-1) * ((X ∩ Z).card : ℤ) + ind (y' ∈ X) * ind (y' ∈ Z) + ind (y ∈ X) * ind (y ∈ Z) = 0 := by
  have h := card_xz X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xzM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 7 + (-1) * (((X ∩ Z).filter (· ∉ M)).card : ℤ) + ind (y' ∈ X) * ind (y' ∈ Z) + ind (y ∈ X) * ind (y ∈ Z) + (-1) * ind (y' ∈ M) * ind (y' ∈ X) * ind (y' ∈ Z) + (-1) * ind (y ∈ M) * ind (y ∈ X) * ind (y ∈ Z) = 0 := by
  have h := card_xzM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xzW (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 31 + (-1) * (((X ∩ Z).filter (· ∈ T ∩ B)).card : ℤ) + (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) * ind (y' ∈ Z) + (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) * ind (y ∈ Z) = 0 := by
  have h := card_xzW X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xzWM (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 31 + (-1) * (((X ∩ Z).filter (· ∈ T ∩ B ∩ M)).card : ℤ) + ind (y' ∈ M) * (ind (y' ∈ T) * ind (y' ∈ B)) * ind (y' ∈ X) * ind (y' ∈ Z) + ind (y ∈ M) * (ind (y ∈ T) * ind (y ∈ B)) * ind (y ∈ X) * ind (y ∈ Z) = 0 := by
  have h := card_xzWM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_om (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 12 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 4 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ T) + (-1) * (ind (y' ∈ T) * ind (y' ∈ B)) + (-1) * ((T.filter (· ∉ B)).card : ℤ) + ind (y ∈ T) + (-1) * (ind (y ∈ T) * ind (y ∈ B)) = 0 := by
  have h := card_om X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_zT (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + ind (y' ∈ Z) + (-1) * ((Z.filter (· ∉ T)).card : ℤ) + ind (y ∈ Z) + (-1) * ind (y' ∈ T) * ind (y' ∈ Z) + (-1) * ind (y ∈ T) * ind (y ∈ Z) = 0 := by
  have h := card_zT X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem dec_xB (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 7 + atom X Z T M B {y, y'} 9 + ind (y' ∈ X) + (-1) * ((X.filter (· ∉ B)).card : ℤ) + ind (y ∈ X) + (-1) * ind (y' ∈ B) * ind (y' ∈ X) + (-1) * ind (y ∈ B) * ind (y ∈ X) = 0 := by
  have h := card_xB X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  simp only [ind_mem_filter, ind_mem_inter, ind_not] at h
  linear_combination (-1 : ℤ) * h

theorem size_X (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 1 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 21 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 29 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 31 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 7 + atom X Z T M B {y, y'} 9 + (-1) * (X.card : ℤ) + ind (y' ∈ X) + ind (y ∈ X) = 0 := by
  have h := card_nX X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  linear_combination (-1 : ℤ) * h

theorem size_Z (X Z T M B : Finset ℕ) {y y' : ℕ} (hne : y ≠ y') :
    atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 2 + atom X Z T M B {y, y'} 22 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 3 + atom X Z T M B {y, y'} 30 + atom X Z T M B {y, y'} 31 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + (-1) * (Z.card : ℤ) + ind (y' ∈ Z) + ind (y ∈ Z) = 0 := by
  have h := card_nZ X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  linear_combination (-1 : ℤ) * h

theorem size_T (X Z T M B : Finset ℕ) (hT : T.card = 4) {y y' : ℕ} (hne : y ≠ y') :
    (-4) + atom X Z T M B {y, y'} 12 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 20 + atom X Z T M B {y, y'} 21 + atom X Z T M B {y, y'} 22 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 28 + atom X Z T M B {y, y'} 29 + atom X Z T M B {y, y'} 30 + atom X Z T M B {y, y'} 31 + atom X Z T M B {y, y'} 4 + atom X Z T M B {y, y'} 5 + atom X Z T M B {y, y'} 6 + atom X Z T M B {y, y'} 7 + ind (y' ∈ T) + ind (y ∈ T) = 0 := by
  have h := card_nT X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  rw [hT] at h; push_cast at h
  linear_combination (-1 : ℤ) * h

theorem size_M (X Z T M B : Finset ℕ) (hM : M.card = 4) {y y' : ℕ} (hne : y ≠ y') :
    (-4) + atom X Z T M B {y, y'} 10 + atom X Z T M B {y, y'} 11 + atom X Z T M B {y, y'} 12 + atom X Z T M B {y, y'} 13 + atom X Z T M B {y, y'} 14 + atom X Z T M B {y, y'} 15 + atom X Z T M B {y, y'} 24 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 28 + atom X Z T M B {y, y'} 29 + atom X Z T M B {y, y'} 30 + atom X Z T M B {y, y'} 31 + atom X Z T M B {y, y'} 8 + atom X Z T M B {y, y'} 9 + ind (y' ∈ M) + ind (y ∈ M) = 0 := by
  have h := card_nM X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  rw [hM] at h; push_cast at h
  linear_combination (-1 : ℤ) * h

theorem size_B (X Z T M B : Finset ℕ) (hB : B.card = 4) {y y' : ℕ} (hne : y ≠ y') :
    (-4) + atom X Z T M B {y, y'} 16 + atom X Z T M B {y, y'} 17 + atom X Z T M B {y, y'} 18 + atom X Z T M B {y, y'} 19 + atom X Z T M B {y, y'} 20 + atom X Z T M B {y, y'} 21 + atom X Z T M B {y, y'} 22 + atom X Z T M B {y, y'} 23 + atom X Z T M B {y, y'} 24 + atom X Z T M B {y, y'} 25 + atom X Z T M B {y, y'} 26 + atom X Z T M B {y, y'} 27 + atom X Z T M B {y, y'} 28 + atom X Z T M B {y, y'} 29 + atom X Z T M B {y, y'} 30 + atom X Z T M B {y, y'} 31 + ind (y' ∈ B) + ind (y ∈ B) = 0 := by
  have h := card_nB X Z T M B {y, y'}
  rw [card_inter_pair _ hne] at h
  rw [hB] at h; push_cast at h
  linear_combination (-1 : ℤ) * h

end Four
end Grid3
