/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import Grid3.Four.Atoms

/-!
# The regions of the `k = 4` arithmetic, decomposed into atoms

Generated by `ai_research_notes/cx/eig/gen_regions.py`. One lemma per region: its size is the
sum of its atoms plus its marked colours.
-/

open Finset

set_option linter.unusedSimpArgs false

namespace Grid3
namespace Four

theorem card_nX (X Z T M B E : Finset ℕ) :
    ((X).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 5 + atom X Z T M B E 7 + atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 13 + atom X Z T M B E 15 + atom X Z T M B E 17 + atom X Z T M B E 19 + atom X Z T M B E 21 + atom X Z T M B E 23 + atom X Z T M B E 25 + atom X Z T M B E 27 + atom X Z T M B E 29 + atom X Z T M B E 31 + (((X) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0) (X) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_nZ (X Z T M B E : Finset ℕ) :
    ((Z).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 22 + atom X Z T M B E 23 + atom X Z T M B E 26 + atom X Z T M B E 27 + atom X Z T M B E 30 + atom X Z T M B E 31 + (((Z) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1) (Z) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_nT (X Z T M B E : Finset ℕ) :
    ((T).card : ℤ) = atom X Z T M B E 4 + atom X Z T M B E 5 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 12 + atom X Z T M B E 13 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 20 + atom X Z T M B E 21 + atom X Z T M B E 22 + atom X Z T M B E 23 + atom X Z T M B E 28 + atom X Z T M B E 29 + atom X Z T M B E 30 + atom X Z T M B E 31 + (((T) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 2) (T) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_T (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_nM (X Z T M B E : Finset ℕ) :
    ((M).card : ℤ) = atom X Z T M B E 8 + atom X Z T M B E 9 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 12 + atom X Z T M B E 13 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 24 + atom X Z T M B E 25 + atom X Z T M B E 26 + atom X Z T M B E 27 + atom X Z T M B E 28 + atom X Z T M B E 29 + atom X Z T M B E 30 + atom X Z T M B E 31 + (((M) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 3) (M) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_nB (X Z T M B E : Finset ℕ) :
    ((B).card : ℤ) = atom X Z T M B E 16 + atom X Z T M B E 17 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 20 + atom X Z T M B E 21 + atom X Z T M B E 22 + atom X Z T M B E 23 + atom X Z T M B E 24 + atom X Z T M B E 25 + atom X Z T M B E 26 + atom X Z T M B E 27 + atom X Z T M B E 28 + atom X Z T M B E 29 + atom X Z T M B E 30 + atom X Z T M B E 31 + (((B) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 4) (B) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_B (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xT (X Z T M B E : Finset ℕ) :
    ((X.filter (· ∉ T)).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 17 + atom X Z T M B E 19 + atom X Z T M B E 25 + atom X Z T M B E 27 + (((X.filter (· ∉ T)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ ¬ bit v 2) (X.filter (· ∉ T)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xM (X Z T M B E : Finset ℕ) :
    ((X.filter (· ∉ M)).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 5 + atom X Z T M B E 7 + atom X Z T M B E 17 + atom X Z T M B E 19 + atom X Z T M B E 21 + atom X Z T M B E 23 + (((X.filter (· ∉ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ ¬ bit v 3) (X.filter (· ∉ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xB (X Z T M B E : Finset ℕ) :
    ((X.filter (· ∉ B)).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 5 + atom X Z T M B E 7 + atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 13 + atom X Z T M B E 15 + (((X.filter (· ∉ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ ¬ bit v 4) (X.filter (· ∉ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xW (X Z T M B E : Finset ℕ) :
    ((X.filter (· ∉ T ∩ B)).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 5 + atom X Z T M B E 7 + atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 13 + atom X Z T M B E 15 + atom X Z T M B E 17 + atom X Z T M B E 19 + atom X Z T M B E 25 + atom X Z T M B E 27 + (((X.filter (· ∉ T ∩ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ ¬ (bit v 2 ∧ bit v 4)) (X.filter (· ∉ T ∩ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xWM (X Z T M B E : Finset ℕ) :
    ((X.filter (· ∉ T ∩ B ∩ M)).card : ℤ) = atom X Z T M B E 1 + atom X Z T M B E 3 + atom X Z T M B E 5 + atom X Z T M B E 7 + atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 13 + atom X Z T M B E 15 + atom X Z T M B E 17 + atom X Z T M B E 19 + atom X Z T M B E 21 + atom X Z T M B E 23 + atom X Z T M B E 25 + atom X Z T M B E 27 + (((X.filter (· ∉ T ∩ B ∩ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ ¬ (bit v 2 ∧ bit v 4 ∧ bit v 3)) (X.filter (· ∉ T ∩ B ∩ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_zB (X Z T M B E : Finset ℕ) :
    ((Z.filter (· ∉ B)).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 14 + atom X Z T M B E 15 + (((Z.filter (· ∉ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1 ∧ ¬ bit v 4) (Z.filter (· ∉ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_zM (X Z T M B E : Finset ℕ) :
    ((Z.filter (· ∉ M)).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 22 + atom X Z T M B E 23 + (((Z.filter (· ∉ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1 ∧ ¬ bit v 3) (Z.filter (· ∉ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_zT (X Z T M B E : Finset ℕ) :
    ((Z.filter (· ∉ T)).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 26 + atom X Z T M B E 27 + (((Z.filter (· ∉ T)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1 ∧ ¬ bit v 2) (Z.filter (· ∉ T)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_zW (X Z T M B E : Finset ℕ) :
    ((Z.filter (· ∉ T ∩ B)).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 26 + atom X Z T M B E 27 + (((Z.filter (· ∉ T ∩ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1 ∧ ¬ (bit v 2 ∧ bit v 4)) (Z.filter (· ∉ T ∩ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_zWM (X Z T M B E : Finset ℕ) :
    ((Z.filter (· ∉ T ∩ B ∩ M)).card : ℤ) = atom X Z T M B E 2 + atom X Z T M B E 3 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 18 + atom X Z T M B E 19 + atom X Z T M B E 22 + atom X Z T M B E 23 + atom X Z T M B E 26 + atom X Z T M B E 27 + (((Z.filter (· ∉ T ∩ B ∩ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 1 ∧ ¬ (bit v 2 ∧ bit v 4 ∧ bit v 3)) (Z.filter (· ∉ T ∩ B ∩ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_Z (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_mT (X Z T M B E : Finset ℕ) :
    ((M.filter (· ∉ T)).card : ℤ) = atom X Z T M B E 8 + atom X Z T M B E 9 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 24 + atom X Z T M B E 25 + atom X Z T M B E 26 + atom X Z T M B E 27 + (((M.filter (· ∉ T)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 3 ∧ ¬ bit v 2) (M.filter (· ∉ T)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_mB (X Z T M B E : Finset ℕ) :
    ((M.filter (· ∉ B)).card : ℤ) = atom X Z T M B E 8 + atom X Z T M B E 9 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 12 + atom X Z T M B E 13 + atom X Z T M B E 14 + atom X Z T M B E 15 + (((M.filter (· ∉ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 3 ∧ ¬ bit v 4) (M.filter (· ∉ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_mW (X Z T M B E : Finset ℕ) :
    ((M.filter (· ∉ T ∩ B)).card : ℤ) = atom X Z T M B E 8 + atom X Z T M B E 9 + atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 12 + atom X Z T M B E 13 + atom X Z T M B E 14 + atom X Z T M B E 15 + atom X Z T M B E 24 + atom X Z T M B E 25 + atom X Z T M B E 26 + atom X Z T M B E 27 + (((M.filter (· ∉ T ∩ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 3 ∧ ¬ (bit v 2 ∧ bit v 4)) (M.filter (· ∉ T ∩ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_mXT (X Z T M B E : Finset ℕ) :
    (((M.filter (· ∉ T)).filter (· ∈ X)).card : ℤ) = atom X Z T M B E 9 + atom X Z T M B E 11 + atom X Z T M B E 25 + atom X Z T M B E 27 + ((((M.filter (· ∉ T)).filter (· ∈ X)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => (bit v 3 ∧ ¬ bit v 2) ∧ bit v 0) ((M.filter (· ∉ T)).filter (· ∈ X)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_mZB (X Z T M B E : Finset ℕ) :
    (((M.filter (· ∉ B)).filter (· ∈ Z)).card : ℤ) = atom X Z T M B E 10 + atom X Z T M B E 11 + atom X Z T M B E 14 + atom X Z T M B E 15 + ((((M.filter (· ∉ B)).filter (· ∈ Z)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => (bit v 3 ∧ ¬ bit v 4) ∧ bit v 1) ((M.filter (· ∉ B)).filter (· ∈ Z)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_M (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xz (X Z T M B E : Finset ℕ) :
    ((X ∩ Z).card : ℤ) = atom X Z T M B E 3 + atom X Z T M B E 7 + atom X Z T M B E 11 + atom X Z T M B E 15 + atom X Z T M B E 19 + atom X Z T M B E 23 + atom X Z T M B E 27 + atom X Z T M B E 31 + (((X ∩ Z) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 0 ∧ bit v 1) (X ∩ Z) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xzM (X Z T M B E : Finset ℕ) :
    (((X ∩ Z).filter (· ∉ M)).card : ℤ) = atom X Z T M B E 3 + atom X Z T M B E 7 + atom X Z T M B E 19 + atom X Z T M B E 23 + ((((X ∩ Z).filter (· ∉ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => (bit v 0 ∧ bit v 1) ∧ ¬ bit v 3) ((X ∩ Z).filter (· ∉ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xzW (X Z T M B E : Finset ℕ) :
    (((X ∩ Z).filter (· ∈ T ∩ B)).card : ℤ) = atom X Z T M B E 23 + atom X Z T M B E 31 + ((((X ∩ Z).filter (· ∈ T ∩ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => (bit v 0 ∧ bit v 1) ∧ (bit v 2 ∧ bit v 4)) ((X ∩ Z).filter (· ∈ T ∩ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_xzWM (X Z T M B E : Finset ℕ) :
    (((X ∩ Z).filter (· ∈ T ∩ B ∩ M)).card : ℤ) = atom X Z T M B E 31 + ((((X ∩ Z).filter (· ∈ T ∩ B ∩ M)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => (bit v 0 ∧ bit v 1) ∧ (bit v 2 ∧ bit v 4 ∧ bit v 3)) ((X ∩ Z).filter (· ∈ T ∩ B ∩ M)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_X (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

theorem card_om (X Z T M B E : Finset ℕ) :
    ((T.filter (· ∉ B)).card : ℤ) = atom X Z T M B E 4 + atom X Z T M B E 5 + atom X Z T M B E 6 + atom X Z T M B E 7 + atom X Z T M B E 12 + atom X Z T M B E 13 + atom X Z T M B E 14 + atom X Z T M B E 15 + (((T.filter (· ∉ B)) ∩ E).card : ℤ) := by
  rw [card_region X Z T M B (fun v => bit v 2 ∧ ¬ bit v 4) (T.filter (· ∉ B)) E (fun c => by
    simp only [Finset.mem_filter, Finset.mem_inter, bit_typ_X, bit_typ_Z, bit_typ_T, bit_typ_M,
      bit_typ_B]
    constructor
    · intro h; exact ⟨mem_univ5_of_T (by tauto), by tauto⟩
    · intro h; tauto)]
  simp only [Finset.sum_filter, Finset.sum_range_succ, Finset.sum_range_zero]
  norm_num [bit]

end Four
end Grid3
