import Grid3.Three.Cert.Keys.K00
import Grid3.Three.Cert.Keys.K01
import Grid3.Three.Cert.Keys.K02
import Grid3.Three.Cert.Keys.K03
import Grid3.Three.Cert.Keys.K04
import Grid3.Three.Cert.Keys.K05
import Grid3.Three.Cert.Keys.K06
import Grid3.Three.Cert.Keys.K07
import Grid3.Three.Cert.Keys.K08
import Grid3.Three.Cert.Keys.K09
import Grid3.Three.Cert.Keys.K10
import Grid3.Three.Cert.Keys.K11
import Grid3.Three.Cert.Keys.K12
import Grid3.Three.Cert.Keys.K13
import Grid3.Three.Cert.Keys.K14
import Grid3.Three.Cert.Keys.K15
import Grid3.Three.Cert.Keys.K16
import Grid3.Three.Cert.Keys.K17
import Grid3.Three.Cert.Keys.K18
import Grid3.Three.Cert.Keys.K19
import Grid3.Three.Cert.Keys.K20
import Grid3.Three.Cert.Keys.K21
import Grid3.Three.Cert.Keys.K22
import Grid3.Three.Cert.Keys.K23
import Grid3.Three.Cert.Keys.K24
import Grid3.Three.Cert.Keys.K25
import Grid3.Three.Cert.Keys.K26
import Grid3.Three.Cert.Keys.K27
import Grid3.Three.Cert.Keys.K28
import Grid3.Three.Cert.Keys.K29
import Grid3.Three.Cert.Keys.K30
import Grid3.Three.Cert.Keys.K31
import Grid3.Three.Cert.Keys.K32
import Grid3.Three.Cert.Keys.K33
import Grid3.Three.Cert.Keys.K34
import Grid3.Three.Cert.Keys.K35
import Grid3.Three.Cert.Keys.K36
import Grid3.Three.Cert.Keys.K37
import Grid3.Three.Cert.Keys.K38

/-!
# Completeness of the `k = 3` seam certificate

`cert_complete`: every valid maximal seam key `(mL, mR, M)` is the symbolic `U → U` seam or has a
record in `Data/` that passes `checkRecord` (so that `Bridge.lean` yields its seam package).
The 39 per-type modules identify `enumKeys mL mR` with the stored keys by `decide +kernel`;
`enumKeys_complete` (`Keys.lean`) is the structural completeness of the enumeration.
Generated by `Grid3/Three/Cert/scripts/gen_keys.py`.
-/

namespace Grid3.Three.Cert

theorem cert_complete (mL mR M : Nat) (hLb : mL < 16384) (hRb : mR < 16384)
    (hL : validType mL = true) (hR : validType mR = true) (hM : M < 16384 ^ 7)
    (hv : validKey mL mR M = true) (hmax : keyMax mL mR M = true) :
    (mL = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt mL mR M ne blob = true := by
  have hmL := validType_mem_validTypes mL hLb hL
  have hmR := validType_mem_validTypes mR hRb hR
  have hM' := enumKeys_complete mL mR M hM hv hmax
  rw [validTypes_eq] at hmL
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmL
  rcases hmL with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact K38.cover mR hmR M hM'
  · exact K33.cover mR hmR M hM'
  · exact K21.cover mR hmR M hM'
  · exact K05.cover mR hmR M hM'
  · exact K34.cover mR hmR M hM'
  · exact K24.cover mR hmR M hM'
  · exact K09.cover mR hmR M hM'
  · exact K25.cover mR hmR M hM'
  · exact K11.cover mR hmR M hM'
  · exact K12.cover mR hmR M hM'
  · exact K37.cover mR hmR M hM'
  · exact K30.cover mR hmR M hM'
  · exact K16.cover mR hmR M hM'
  · exact K31.cover mR hmR M hM'
  · exact K19.cover mR hmR M hM'
  · exact K03.cover mR hmR M hM'
  · exact K22.cover mR hmR M hM'
  · exact K07.cover mR hmR M hM'
  · exact K36.cover mR hmR M hM'
  · exact K27.cover mR hmR M hM'
  · exact K28.cover mR hmR M hM'
  · exact K14.cover mR hmR M hM'
  · exact K35.cover mR hmR M hM'
  · exact K32.cover mR hmR M hM'
  · exact K20.cover mR hmR M hM'
  · exact K04.cover mR hmR M hM'
  · exact K23.cover mR hmR M hM'
  · exact K08.cover mR hmR M hM'
  · exact K10.cover mR hmR M hM'
  · exact K29.cover mR hmR M hM'
  · exact K15.cover mR hmR M hM'
  · exact K17.cover mR hmR M hM'
  · exact K01.cover mR hmR M hM'
  · exact K26.cover mR hmR M hM'
  · exact K18.cover mR hmR M hM'
  · exact K02.cover mR hmR M hM'
  · exact K06.cover mR hmR M hM'
  · exact K13.cover mR hmR M hM'
  · exact K00.cover mR hmR M hM'

end Grid3.Three.Cert
