import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0000
import Grid3.Three.Cert.Data.C0001
import Grid3.Three.Cert.Data.C0002
import Grid3.Three.Cert.Data.C0003
import Grid3.Three.Cert.Data.C0004
import Grid3.Three.Cert.Data.C0005

/-! Seam keys with left type `12288` (type index 0): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K00

theorem tL : rtype 12288 = 12288 := by decide

def s00 : List Nat := [237684487542793012780631851008]
theorem e00 : enumKeys 12288 12288 = s00 := by decide +kernel

def s01 : List Nat := [25068285795528950566707265536, 84489407681227203761865228288, 99344688152651767060654718976, 103986963299971943091526434816]
theorem e01 : enumKeys 12288 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 91, c0000_b0, by decide, c0000_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 83, c0000_b1, by decide, c0000_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 94, c0000_b2, by decide, c0000_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 83, c0000_b1, by decide, by rw [tL, t01, show rM 103986963299971943091526434816 = 84489407681227203761865228288 by decide]; exact c0000_ok1⟩, ?_⟩
  simp

def s02 : List Nat := [80775587563371062937167855616, 158765810038350020255812681728, 159694265067814055461987024896]
theorem e02 : enumKeys 12288 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 80, c0000_b3, by decide, c0000_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 72, c0000_b4, by decide, c0000_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 74, c0000_b5, by decide, c0000_ok5⟩, ?_⟩
  simp

def s03 : List Nat := [1856910058928070412348686336, 5570730176784211237046059008, 6499185206248246443220402176, 20426010648208774535835549696, 21354465677672809742009892864, 25068285795528950566707265536, 25996740824992985772881608704]
theorem e03 : enumKeys 12288 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 122, c0000_b6, by decide, c0000_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 106, c0000_b7, by decide, c0000_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 109, c0000_b8, by decide, c0000_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 116, c0000_b9, by decide, c0000_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 124, c0000_b10, by decide, c0000_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 107, c0000_b11, by decide, c0000_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 113, c0000_b12, by decide, c0000_ok12⟩, ?_⟩
  simp

def s04 : List Nat := [1856910058928070412348686336, 2785365088392105618523029504, 79847132533907027730993512448, 80775587563371062937167855616, 81704042592835098143342198784]
theorem e04 : enumKeys 12288 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 102, c0000_b13, by decide, c0000_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 112, c0000_b14, by decide, c0000_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 90, c0000_b15, by decide, c0000_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 96, c0000_b16, by decide, c0000_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 104, c0000_b17, by decide, c0000_ok17⟩, ?_⟩
  simp

def s05 : List Nat := [928455029464035206174343168, 1856910058928070412348686336, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e05 : enumKeys 12288 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 108, c0000_b18, by decide, c0000_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 118, c0000_b19, by decide, c0000_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 132, c0000_b20, by decide, c0000_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0000_b21, by decide, c0000_ok21⟩, ?_⟩
  simp

def s06 : List Nat := [84257293923861194960321642496, 158533696280984011454269095936, 163408085185670196286684397568]
theorem e06 : enumKeys 12288 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 97, c0000_b22, by decide, c0000_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 100, c0000_b23, by decide, c0000_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 84, c0000_b24, by decide, c0000_ok24⟩, ?_⟩
  simp

def s07 : List Nat := [5338616419418202435502473216, 9980891566738378466374189056, 10213005324104387267917774848, 20193896890842765734291963904, 24836172038162941765163679744, 25068285795528950566707265536, 29710560942849126597578981376]
theorem e07 : enumKeys 12288 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 141, c0000_b25, by decide, c0000_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 126, c0000_b26, by decide, c0000_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 118, c0000_b27, by decide, c0000_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 148, c0000_b28, by decide, c0000_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 141, c0000_b25, by decide, by rw [tL, t07, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0000_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 135, c0000_b29, by decide, c0000_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 118, c0000_b27, by decide, by rw [tL, t07, show rM 29710560942849126597578981376 = 10213005324104387267917774848 by decide]; exact c0000_ok27⟩, ?_⟩
  simp

def s08 : List Nat := [1624796301562061610805100544, 5338616419418202435502473216, 6267071448882237641676816384, 6499185206248246443220402176, 79615018776541018929449926656, 80543473806005054135624269824, 80775587563371062937167855616, 84257293923861194960321642496, 84489407681227203761865228288, 85417862710691238968039571456]
theorem e08 : enumKeys 12288 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0000_b30, by decide, c0000_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 121, c0000_b31, by decide, c0000_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 129, c0000_b32, by decide, c0000_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 121, c0000_b33, by decide, c0000_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 122, c0000_b34, by decide, c0000_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 130, c0000_b35, by decide, c0000_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 124, c0000_b36, by decide, c0000_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 113, c0000_b37, by decide, c0000_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 107, c0000_b38, by decide, c0000_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 109, c0000_b39, by decide, c0000_ok39⟩, ?_⟩
  simp

def s09 : List Nat := [696341272098026404630757376, 1624796301562061610805100544, 1856910058928070412348686336, 2553251331026096816979443712, 2785365088392105618523029504, 5338616419418202435502473216, 5570730176784211237046059008, 6267071448882237641676816384, 6499185206248246443220402176, 7427640235712281649394745344]
theorem e09 : enumKeys 12288 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0001_b0, by decide, c0001_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 157, c0001_b1, by decide, c0001_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 150, c0001_b2, by decide, c0001_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 172, c0001_b3, by decide, c0001_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 160, c0001_b4, by decide, c0001_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0001_b5, by decide, c0001_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 130, c0001_b6, by decide, c0001_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 149, c0001_b7, by decide, c0001_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0001_b8, by decide, c0001_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0001_b9, by decide, c0001_ok9⟩, ?_⟩
  simp

def s10 : List Nat := [5106502662052193633958887424, 9980891566738378466374189056, 79382905019175010127906340864, 84257293923861194960321642496, 89131682828547379792736944128]
theorem e10 : enumKeys 12288 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 156, c0001_b10, by decide, c0001_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 138, c0001_b11, by decide, c0001_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0001_b12, by decide, c0001_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 141, c0001_b13, by decide, c0001_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 114, c0001_b14, by decide, c0001_ok14⟩, ?_⟩
  simp

def s11 : List Nat := [464227514732017603087171584, 1392682544196052809261514752, 1624796301562061610805100544, 5106502662052193633958887424, 5338616419418202435502473216, 6267071448882237641676816384, 6499185206248246443220402176, 9980891566738378466374189056, 10213005324104387267917774848, 11141460353568422474092118016]
theorem e11 : enumKeys 12288 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0001_b15, by decide, c0001_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 196, c0001_b16, by decide, c0001_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 189, c0001_b17, by decide, c0001_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 176, c0001_b18, by decide, c0001_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 169, c0001_b19, by decide, c0001_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 177, c0001_b20, by decide, c0001_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 165, c0001_b21, by decide, c0001_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0001_b22, by decide, c0001_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 142, c0001_b23, by decide, c0001_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0001_b24, by decide, c0001_ok24⟩, ?_⟩
  simp

def s12 : List Nat := [232113757366008801543585792, 5106502662052193633958887424, 9980891566738378466374189056, 14855280471424563298789490688]
theorem e12 : enumKeys 12288 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0001_b25, by decide, c0001_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 208, c0001_b26, by decide, c0001_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 182, c0001_b27, by decide, c0001_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0001_b28, by decide, c0001_ok28⟩, ?_⟩
  simp

def s13 : List Nat := [99054545955944256058725236736, 158475667841642509253883199488, 178263365657094759585473888256]
theorem e13 : enumKeys 12288 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 80, c0000_b3, by decide, by rw [tL, t13, show rM 99054545955944256058725236736 = 80775587563371062937167855616 by decide]; exact c0000_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 74, c0000_b5, by decide, by rw [tL, t13, show rM 158475667841642509253883199488 = 159694265067814055461987024896 by decide]; exact c0000_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 72, c0000_b4, by decide, by rw [tL, t13, show rM 178263365657094759585473888256 = 158765810038350020255812681728 by decide]; exact c0000_ok4⟩, ?_⟩
  simp

def s14 : List Nat := [5280587980076700235116576768, 20135868451501263533906067456, 24778143598821439564777783296, 25068285795528950566707265536, 39633424070246002863567273984, 39923566266953513865496756224, 44565841414273689896368472064]
theorem e14 : enumKeys 12288 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 113, c0000_b12, by decide, by rw [tL, t14, show rM 5280587980076700235116576768 = 25996740824992985772881608704 by decide]; exact c0000_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 124, c0000_b10, by decide, by rw [tL, t14, show rM 20135868451501263533906067456 = 21354465677672809742009892864 by decide]; exact c0000_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 109, c0000_b8, by decide, by rw [tL, t14, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0000_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 107, c0000_b11, by decide, by rw [tL, t14, show rM 25068285795528950566707265536 = 25068285795528950566707265536 by decide]; exact c0000_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 122, c0000_b6, by decide, by rw [tL, t14, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0000_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 116, c0000_b9, by decide, by rw [tL, t14, show rM 39923566266953513865496756224 = 20426010648208774535835549696 by decide]; exact c0000_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 106, c0000_b7, by decide, by rw [tL, t14, show rM 44565841414273689896368472064 = 5570730176784211237046059008 by decide]; exact c0000_ok7⟩, ?_⟩
  simp

def s15 : List Nat := [1566767862220559410419204096, 20135868451501263533906067456, 21064323480965298740080410624, 21354465677672809742009892864, 79556990337199516729064030208, 80485445366663551935238373376, 80775587563371062937167855616, 99054545955944256058725236736, 99344688152651767060654718976, 100273143182115802266829062144]
theorem e15 : enumKeys 12288 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 110, c0001_b29, by decide, c0001_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 104, c0001_b30, by decide, c0001_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 110, c0001_b29, by decide, by rw [tL, t15, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0001_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 104, c0001_b30, by decide, by rw [tL, t15, show rM 21354465677672809742009892864 = 20135868451501263533906067456 by decide]; exact c0001_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 97, c0001_b31, by decide, c0001_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 98, c0001_b32, by decide, c0001_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 96, c0001_b33, by decide, c0001_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 96, c0001_b33, by decide, by rw [tL, t15, show rM 99054545955944256058725236736 = 80775587563371062937167855616 by decide]; exact c0001_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 94, c0001_b34, by decide, c0001_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 97, c0001_b31, by decide, by rw [tL, t15, show rM 100273143182115802266829062144 = 79556990337199516729064030208 by decide]; exact c0001_ok31⟩, ?_⟩
  simp

def s16 : List Nat := [638312832756524204244860928, 1566767862220559410419204096, 1856910058928070412348686336, 2495222891684594616593547264, 2785365088392105618523029504, 20135868451501263533906067456, 20426010648208774535835549696, 21064323480965298740080410624, 21354465677672809742009892864, 22282920707136844948184236032]
theorem e16 : enumKeys 12288 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 120, c0001_b35, by decide, c0001_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 126, c0001_b36, by decide, c0001_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 122, c0001_b37, by decide, c0001_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 134, c0001_b38, by decide, c0001_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 128, c0001_b39, by decide, c0001_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 120, c0002_b0, by decide, c0002_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 116, c0002_b1, by decide, c0002_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 130, c0002_b2, by decide, c0002_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 124, c0002_b3, by decide, c0002_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 132, c0002_b4, by decide, c0002_ok4⟩, ?_⟩
  simp

def s17 : List Nat := [5048474222710691433572990976, 19903754694135254732362481664, 24778143598821439564777783296, 24836172038162941765163679744, 79324876579833507927520444416, 84199265484519692759935746048, 84257293923861194960321642496, 99054545955944256058725236736, 99112574395285758259111133184, 103986963299971943091526434816]
theorem e17 : enumKeys 12288 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 129, c0000_b32, by decide, by rw [tL, t17, show rM 5048474222710691433572990976 = 6267071448882237641676816384 by decide]; exact c0000_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0000_b30, by decide, by rw [tL, t17, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0000_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 121, c0000_b33, by decide, by rw [tL, t17, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0000_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 121, c0000_b31, by decide, by rw [tL, t17, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0000_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 130, c0000_b35, by decide, by rw [tL, t17, show rM 79324876579833507927520444416 = 80543473806005054135624269824 by decide]; exact c0000_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 109, c0000_b39, by decide, by rw [tL, t17, show rM 84199265484519692759935746048 = 85417862710691238968039571456 by decide]; exact c0000_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 113, c0000_b37, by decide, by rw [tL, t17, show rM 84257293923861194960321642496 = 84257293923861194960321642496 by decide]; exact c0000_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 124, c0000_b36, by decide, by rw [tL, t17, show rM 99054545955944256058725236736 = 80775587563371062937167855616 by decide]; exact c0000_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 122, c0000_b34, by decide, by rw [tL, t17, show rM 99112574395285758259111133184 = 79615018776541018929449926656 by decide]; exact c0000_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 107, c0000_b38, by decide, by rw [tL, t17, show rM 103986963299971943091526434816 = 84489407681227203761865228288 by decide]; exact c0000_ok38⟩, ?_⟩
  simp

def s18 : List Nat := [1334654104854550608875618304, 79324876579833507927520444416, 80485445366663551935238373376, 80543473806005054135624269824, 158475667841642509253883199488, 158533696280984011454269095936, 159694265067814055461987024896]
theorem e18 : enumKeys 12288 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 126, c0002_b5, by decide, c0002_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 110, c0002_b6, by decide, c0002_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 110, c0002_b7, by decide, c0002_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 110, c0002_b6, by decide, by rw [tL, t18, show rM 80543473806005054135624269824 = 79324876579833507927520444416 by decide]; exact c0002_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 98, c0002_b8, by decide, c0002_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 100, c0002_b9, by decide, c0002_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 98, c0002_b8, by decide, by rw [tL, t18, show rM 159694265067814055461987024896 = 158475667841642509253883199488 by decide]; exact c0002_ok8⟩, ?_⟩
  simp

def s19 : List Nat := [406199075390515402701275136, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 5048474222710691433572990976, 5280587980076700235116576768, 5338616419418202435502473216, 6209043009540735441290919936, 6267071448882237641676816384, 6499185206248246443220402176, 19903754694135254732362481664, 20135868451501263533906067456, 20193896890842765734291963904, 21064323480965298740080410624, 21122351920306800940466307072, 21354465677672809742009892864, 24778143598821439564777783296, 24836172038162941765163679744, 25068285795528950566707265536, 25996740824992985772881608704]
theorem e19 : enumKeys 12288 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0002_b10, by decide, c0002_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 166, c0002_b11, by decide, c0002_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0002_b12, by decide, c0002_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 157, c0002_b13, by decide, c0002_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 145, c0002_b14, by decide, c0002_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0002_b15, by decide, c0002_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 141, c0002_b16, by decide, c0002_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 139, c0002_b17, by decide, c0002_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 145, c0002_b14, by decide, by rw [tL, t19, show rM 6267071448882237641676816384 = 5048474222710691433572990976 by decide]; exact c0002_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0002_b18, by decide, c0002_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 157, c0002_b13, by decide, by rw [tL, t19, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0002_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 152, c0002_b19, by decide, c0002_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 148, c0002_b20, by decide, c0002_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0002_b12, by decide, by rw [tL, t19, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0002_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0002_b10, by decide, by rw [tL, t19, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0002_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 152, c0002_b19, by decide, by rw [tL, t19, show rM 21354465677672809742009892864 = 20135868451501263533906067456 by decide]; exact c0002_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0002_b18, by decide, by rw [tL, t19, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0002_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 141, c0002_b16, by decide, by rw [tL, t19, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0002_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 135, c0002_b21, by decide, c0002_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0002_b15, by decide, by rw [tL, t19, show rM 25996740824992985772881608704 = 5280587980076700235116576768 by decide]; exact c0002_ok15⟩, ?_⟩
  simp

def s20 : List Nat := [406199075390515402701275136, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 79324876579833507927520444416, 79556990337199516729064030208, 79615018776541018929449926656, 80485445366663551935238373376, 80543473806005054135624269824, 80775587563371062937167855616, 81704042592835098143342198784]
theorem e20 : enumKeys 12288 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 134, c0002_b22, by decide, c0002_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 146, c0002_b23, by decide, c0002_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 138, c0002_b24, by decide, c0002_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 137, c0002_b25, by decide, c0002_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 146, c0002_b26, by decide, c0002_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 148, c0002_b27, by decide, c0002_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 140, c0002_b28, by decide, c0002_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 126, c0002_b29, by decide, c0002_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 121, c0002_b30, by decide, c0002_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 122, c0002_b31, by decide, c0002_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 126, c0002_b32, by decide, c0002_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 130, c0002_b33, by decide, c0002_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 124, c0002_b34, by decide, c0002_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 128, c0002_b35, by decide, c0002_ok35⟩, ?_⟩
  simp

def s21 : List Nat := [406199075390515402701275136, 638312832756524204244860928, 696341272098026404630757376, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 1856910058928070412348686336, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e21 : enumKeys 12288 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 150, c0002_b36, by decide, c0002_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0002_b37, by decide, c0002_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0002_b38, by decide, c0002_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 166, c0002_b39, by decide, c0002_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0003_b0, by decide, c0003_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 157, c0003_b1, by decide, c0003_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 150, c0003_b2, by decide, c0003_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 166, c0003_b3, by decide, c0003_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 172, c0003_b4, by decide, c0003_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 160, c0003_b5, by decide, c0003_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 168, c0003_b6, by decide, c0003_ok6⟩, ?_⟩
  simp

def s22 : List Nat := [174085318024506601157689344, 5048474222710691433572990976, 5106502662052193633958887424, 9922863127396876265988292608, 9980891566738378466374189056, 19903754694135254732362481664, 19961783133476756932748378112, 24778143598821439564777783296, 24836172038162941765163679744, 29710560942849126597578981376]
theorem e22 : enumKeys 12288 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 196, c0001_b16, by decide, by rw [tL, t22, show rM 174085318024506601157689344 = 1392682544196052809261514752 by decide]; exact c0001_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 177, c0001_b20, by decide, by rw [tL, t22, show rM 5048474222710691433572990976 = 6267071448882237641676816384 by decide]; exact c0001_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 176, c0001_b18, by decide, by rw [tL, t22, show rM 5106502662052193633958887424 = 5106502662052193633958887424 by decide]; exact c0001_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0001_b24, by decide, by rw [tL, t22, show rM 9922863127396876265988292608 = 11141460353568422474092118016 by decide]; exact c0001_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 154, c0001_b22, by decide, by rw [tL, t22, show rM 9980891566738378466374189056 = 9980891566738378466374189056 by decide]; exact c0001_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 189, c0001_b17, by decide, by rw [tL, t22, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0001_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 180, c0001_b15, by decide, by rw [tL, t22, show rM 19961783133476756932748378112 = 464227514732017603087171584 by decide]; exact c0001_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 165, c0001_b21, by decide, by rw [tL, t22, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0001_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 169, c0001_b19, by decide, by rw [tL, t22, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0001_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 142, c0001_b23, by decide, by rw [tL, t22, show rM 29710560942849126597578981376 = 10213005324104387267917774848 by decide]; exact c0001_ok23⟩, ?_⟩
  simp

def s23 : List Nat := [174085318024506601157689344, 1334654104854550608875618304, 1392682544196052809261514752, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 79324876579833507927520444416, 79382905019175010127906340864, 80485445366663551935238373376, 80543473806005054135624269824, 84199265484519692759935746048, 84257293923861194960321642496, 85417862710691238968039571456]
theorem e23 : enumKeys 12288 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 172, c0003_b7, by decide, c0003_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 178, c0003_b8, by decide, c0003_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 172, c0003_b7, by decide, by rw [tL, t23, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0003_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 157, c0003_b9, by decide, c0003_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 156, c0003_b10, by decide, c0003_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 151, c0003_b11, by decide, c0003_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 157, c0003_b9, by decide, by rw [tL, t23, show rM 6267071448882237641676816384 = 5048474222710691433572990976 by decide]; exact c0003_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0003_b12, by decide, c0003_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0003_b13, by decide, c0003_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0003_b14, by decide, c0003_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0003_b12, by decide, by rw [tL, t23, show rM 80543473806005054135624269824 = 79324876579833507927520444416 by decide]; exact c0003_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 133, c0003_b15, by decide, c0003_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 141, c0003_b16, by decide, c0003_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 133, c0003_b15, by decide, by rw [tL, t23, show rM 85417862710691238968039571456 = 84199265484519692759935746048 by decide]; exact c0003_ok15⟩, ?_⟩
  simp

def s24 : List Nat := [174085318024506601157689344, 406199075390515402701275136, 464227514732017603087171584, 1334654104854550608875618304, 1392682544196052809261514752, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 5048474222710691433572990976, 5106502662052193633958887424, 5280587980076700235116576768, 5338616419418202435502473216, 6209043009540735441290919936, 6267071448882237641676816384, 6499185206248246443220402176, 7427640235712281649394745344]
theorem e24 : enumKeys 12288 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0003_b17, by decide, c0003_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0003_b18, by decide, c0003_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0003_b19, by decide, c0003_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 198, c0003_b20, by decide, c0003_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 196, c0003_b21, by decide, c0003_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0003_b22, by decide, c0003_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 189, c0003_b23, by decide, c0003_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 194, c0003_b24, by decide, c0003_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 200, c0003_b25, by decide, c0003_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 188, c0003_b26, by decide, c0003_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 173, c0003_b27, by decide, c0003_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 176, c0003_b28, by decide, c0003_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 161, c0003_b29, by decide, c0003_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 169, c0003_b30, by decide, c0003_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 167, c0003_b31, by decide, c0003_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 177, c0003_b32, by decide, c0003_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 165, c0003_b33, by decide, c0003_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 168, c0003_b34, by decide, c0003_ok34⟩, ?_⟩
  simp

def s25 : List Nat := [174085318024506601157689344, 232113757366008801543585792, 1334654104854550608875618304, 1392682544196052809261514752, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 9922863127396876265988292608, 9980891566738378466374189056, 11141460353568422474092118016]
theorem e25 : enumKeys 12288 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0003_b35, by decide, c0003_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0003_b36, by decide, c0003_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 230, c0003_b37, by decide, c0003_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0003_b35, by decide, by rw [tL, t25, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0003_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 205, c0003_b38, by decide, c0003_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 208, c0003_b39, by decide, c0003_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 195, c0004_b0, by decide, c0004_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 205, c0003_b38, by decide, by rw [tL, t25, show rM 6267071448882237641676816384 = 5048474222710691433572990976 by decide]; exact c0003_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 168, c0004_b1, by decide, c0004_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 182, c0004_b2, by decide, c0004_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 168, c0004_b1, by decide, by rw [tL, t25, show rM 11141460353568422474092118016 = 9922863127396876265988292608 by decide]; exact c0004_ok1⟩, ?_⟩
  simp

def s26 : List Nat := [19845726254793752531976585216, 39633424070246002863567273984, 79266848140492005727134547968, 99054545955944256058725236736, 118842243771396506390315925504]
theorem e26 : enumKeys 12288 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 112, c0000_b14, by decide, by rw [tL, t26, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0000_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 102, c0000_b13, by decide, by rw [tL, t26, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0000_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 104, c0000_b17, by decide, by rw [tL, t26, show rM 79266848140492005727134547968 = 81704042592835098143342198784 by decide]; exact c0000_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 96, c0000_b16, by decide, by rw [tL, t26, show rM 99054545955944256058725236736 = 80775587563371062937167855616 by decide]; exact c0000_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 90, c0000_b15, by decide, by rw [tL, t26, show rM 118842243771396506390315925504 = 79847132533907027730993512448 by decide]; exact c0000_ok15⟩, ?_⟩
  simp

def s27 : List Nat := [348170636049013202315378688, 1276625665513048408489721856, 1566767862220559410419204096, 19845726254793752531976585216, 20135868451501263533906067456, 21064323480965298740080410624, 21354465677672809742009892864, 39633424070246002863567273984, 39923566266953513865496756224, 40852021296417549071671099392]
theorem e27 : enumKeys 12288 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 132, c0002_b4, by decide, by rw [tL, t27, show rM 348170636049013202315378688 = 22282920707136844948184236032 by decide]; exact c0002_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 134, c0001_b38, by decide, by rw [tL, t27, show rM 1276625665513048408489721856 = 2495222891684594616593547264 by decide]; exact c0001_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 130, c0002_b2, by decide, by rw [tL, t27, show rM 1566767862220559410419204096 = 21064323480965298740080410624 by decide]; exact c0002_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 128, c0001_b39, by decide, by rw [tL, t27, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0001_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 124, c0002_b3, by decide, by rw [tL, t27, show rM 20135868451501263533906067456 = 21354465677672809742009892864 by decide]; exact c0002_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 126, c0001_b36, by decide, by rw [tL, t27, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0001_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 120, c0002_b0, by decide, by rw [tL, t27, show rM 21354465677672809742009892864 = 20135868451501263533906067456 by decide]; exact c0002_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 122, c0001_b37, by decide, by rw [tL, t27, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0001_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 116, c0002_b1, by decide, by rw [tL, t27, show rM 39923566266953513865496756224 = 20426010648208774535835549696 by decide]; exact c0002_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 120, c0001_b35, by decide, by rw [tL, t27, show rM 40852021296417549071671099392 = 638312832756524204244860928 by decide]; exact c0001_ok35⟩, ?_⟩
  simp

def s28 : List Nat := [116056878683004400771792896, 4990445783369189233187094528, 5048474222710691433572990976, 19845726254793752531976585216, 19903754694135254732362481664, 24778143598821439564777783296, 24836172038162941765163679744, 39633424070246002863567273984, 39691452509587505063953170432, 44565841414273689896368472064]
theorem e28 : enumKeys 12288 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 172, c0001_b3, by decide, by rw [tL, t28, show rM 116056878683004400771792896 = 2553251331026096816979443712 by decide]; exact c0001_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0001_b9, by decide, by rw [tL, t28, show rM 4990445783369189233187094528 = 7427640235712281649394745344 by decide]; exact c0001_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 149, c0001_b7, by decide, by rw [tL, t28, show rM 5048474222710691433572990976 = 6267071448882237641676816384 by decide]; exact c0001_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 160, c0001_b4, by decide, by rw [tL, t28, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0001_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 157, c0001_b1, by decide, by rw [tL, t28, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0001_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0001_b8, by decide, by rw [tL, t28, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0001_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0001_b5, by decide, by rw [tL, t28, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0001_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 150, c0001_b2, by decide, by rw [tL, t28, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0001_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0001_b0, by decide, by rw [tL, t28, show rM 39691452509587505063953170432 = 696341272098026404630757376 by decide]; exact c0001_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 130, c0001_b6, by decide, by rw [tL, t28, show rM 44565841414273689896368472064 = 5570730176784211237046059008 by decide]; exact c0001_ok6⟩, ?_⟩
  simp

def s29 : List Nat := [116056878683004400771792896, 1276625665513048408489721856, 1334654104854550608875618304, 19845726254793752531976585216, 19903754694135254732362481664, 21064323480965298740080410624, 21122351920306800940466307072, 79266848140492005727134547968, 79324876579833507927520444416, 80485445366663551935238373376, 80543473806005054135624269824, 99054545955944256058725236736, 99112574395285758259111133184, 100273143182115802266829062144]
theorem e29 : enumKeys 12288 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 148, c0002_b27, by decide, by rw [tL, t29, show rM 116056878683004400771792896 = 2553251331026096816979443712 by decide]; exact c0002_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 146, c0002_b26, by decide, by rw [tL, t29, show rM 1276625665513048408489721856 = 2495222891684594616593547264 by decide]; exact c0002_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 146, c0002_b23, by decide, by rw [tL, t29, show rM 1334654104854550608875618304 = 1334654104854550608875618304 by decide]; exact c0002_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 140, c0002_b28, by decide, by rw [tL, t29, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0002_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 137, c0002_b25, by decide, by rw [tL, t29, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0002_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 138, c0002_b24, by decide, by rw [tL, t29, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0002_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 134, c0002_b22, by decide, by rw [tL, t29, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0002_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 128, c0002_b35, by decide, by rw [tL, t29, show rM 79266848140492005727134547968 = 81704042592835098143342198784 by decide]; exact c0002_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 130, c0002_b33, by decide, by rw [tL, t29, show rM 79324876579833507927520444416 = 80543473806005054135624269824 by decide]; exact c0002_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 126, c0002_b32, by decide, by rw [tL, t29, show rM 80485445366663551935238373376 = 80485445366663551935238373376 by decide]; exact c0002_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 126, c0002_b29, by decide, by rw [tL, t29, show rM 80543473806005054135624269824 = 79324876579833507927520444416 by decide]; exact c0002_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 124, c0002_b34, by decide, by rw [tL, t29, show rM 99054545955944256058725236736 = 80775587563371062937167855616 by decide]; exact c0002_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 122, c0002_b31, by decide, by rw [tL, t29, show rM 99112574395285758259111133184 = 79615018776541018929449926656 by decide]; exact c0002_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 121, c0002_b30, by decide, by rw [tL, t29, show rM 100273143182115802266829062144 = 79556990337199516729064030208 by decide]; exact c0002_ok30⟩, ?_⟩
  simp

def s30 : List Nat := [116056878683004400771792896, 348170636049013202315378688, 406199075390515402701275136, 1276625665513048408489721856, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 19845726254793752531976585216, 19903754694135254732362481664, 20135868451501263533906067456, 20193896890842765734291963904, 21064323480965298740080410624, 21122351920306800940466307072, 21354465677672809742009892864, 22282920707136844948184236032]
theorem e30 : enumKeys 12288 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 164, c0004_b3, by decide, c0004_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 156, c0004_b4, by decide, c0004_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0004_b5, by decide, c0004_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 162, c0004_b6, by decide, c0004_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 166, c0004_b7, by decide, c0004_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0004_b8, by decide, c0004_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 157, c0004_b9, by decide, c0004_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 162, c0004_b6, by decide, by rw [tL, t30, show rM 2495222891684594616593547264 = 1276625665513048408489721856 by decide]; exact c0004_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 164, c0004_b3, by decide, by rw [tL, t30, show rM 2553251331026096816979443712 = 116056878683004400771792896 by decide]; exact c0004_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 156, c0004_b10, by decide, c0004_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 156, c0004_b10, by decide, by rw [tL, t30, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0004_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 157, c0004_b9, by decide, by rw [tL, t30, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0004_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 152, c0004_b11, by decide, c0004_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 148, c0004_b12, by decide, c0004_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0004_b8, by decide, by rw [tL, t30, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0004_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0004_b5, by decide, by rw [tL, t30, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0004_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 152, c0004_b11, by decide, by rw [tL, t30, show rM 21354465677672809742009892864 = 20135868451501263533906067456 by decide]; exact c0004_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 156, c0004_b4, by decide, by rw [tL, t30, show rM 22282920707136844948184236032 = 348170636049013202315378688 by decide]; exact c0004_ok4⟩, ?_⟩
  simp

def s31 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 4990445783369189233187094528, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 19845726254793752531976585216, 19903754694135254732362481664, 19961783133476756932748378112, 21064323480965298740080410624, 21122351920306800940466307072, 24778143598821439564777783296, 24836172038162941765163679744, 25996740824992985772881608704]
theorem e31 : enumKeys 12288 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 200, c0003_b25, by decide, by rw [tL, t31, show rM 116056878683004400771792896 = 2553251331026096816979443712 by decide]; exact c0003_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 196, c0003_b21, by decide, by rw [tL, t31, show rM 174085318024506601157689344 = 1392682544196052809261514752 by decide]; exact c0003_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 194, c0003_b24, by decide, by rw [tL, t31, show rM 1276625665513048408489721856 = 2495222891684594616593547264 by decide]; exact c0003_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 198, c0003_b20, by decide, by rw [tL, t31, show rM 1334654104854550608875618304 = 1334654104854550608875618304 by decide]; exact c0003_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 192, c0003_b17, by decide, by rw [tL, t31, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0003_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 168, c0003_b34, by decide, by rw [tL, t31, show rM 4990445783369189233187094528 = 7427640235712281649394745344 by decide]; exact c0003_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 177, c0003_b32, by decide, by rw [tL, t31, show rM 5048474222710691433572990976 = 6267071448882237641676816384 by decide]; exact c0003_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 176, c0003_b28, by decide, by rw [tL, t31, show rM 5106502662052193633958887424 = 5106502662052193633958887424 by decide]; exact c0003_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 167, c0003_b31, by decide, by rw [tL, t31, show rM 6209043009540735441290919936 = 6209043009540735441290919936 by decide]; exact c0003_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 173, c0003_b27, by decide, by rw [tL, t31, show rM 6267071448882237641676816384 = 5048474222710691433572990976 by decide]; exact c0003_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 188, c0003_b26, by decide, by rw [tL, t31, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0003_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 189, c0003_b23, by decide, by rw [tL, t31, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0003_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 180, c0003_b19, by decide, by rw [tL, t31, show rM 19961783133476756932748378112 = 464227514732017603087171584 by decide]; exact c0003_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 186, c0003_b22, by decide, by rw [tL, t31, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0003_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 186, c0003_b18, by decide, by rw [tL, t31, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0003_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 165, c0003_b33, by decide, by rw [tL, t31, show rM 24778143598821439564777783296 = 6499185206248246443220402176 by decide]; exact c0003_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 169, c0003_b30, by decide, by rw [tL, t31, show rM 24836172038162941765163679744 = 5338616419418202435502473216 by decide]; exact c0003_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 161, c0003_b29, by decide, by rw [tL, t31, show rM 25996740824992985772881608704 = 5280587980076700235116576768 by decide]; exact c0003_ok29⟩, ?_⟩
  simp

def s32 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 79266848140492005727134547968, 79324876579833507927520444416, 79382905019175010127906340864, 80485445366663551935238373376, 80543473806005054135624269824, 81704042592835098143342198784]
theorem e32 : enumKeys 12288 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 176, c0004_b13, by decide, c0004_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 172, c0004_b14, by decide, c0004_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 174, c0004_b15, by decide, c0004_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 178, c0004_b16, by decide, c0004_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 172, c0004_b14, by decide, by rw [tL, t32, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0004_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 174, c0004_b15, by decide, by rw [tL, t32, show rM 2495222891684594616593547264 = 1276625665513048408489721856 by decide]; exact c0004_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 176, c0004_b13, by decide, by rw [tL, t32, show rM 2553251331026096816979443712 = 116056878683004400771792896 by decide]; exact c0004_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 152, c0004_b17, by decide, c0004_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 158, c0004_b18, by decide, c0004_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0004_b19, by decide, c0004_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 154, c0004_b20, by decide, c0004_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 158, c0004_b18, by decide, by rw [tL, t32, show rM 80543473806005054135624269824 = 79324876579833507927520444416 by decide]; exact c0004_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 152, c0004_b17, by decide, by rw [tL, t32, show rM 81704042592835098143342198784 = 79266848140492005727134547968 by decide]; exact c0004_ok17⟩, ?_⟩
  simp

def s33 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 348170636049013202315378688, 406199075390515402701275136, 464227514732017603087171584, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e33 : enumKeys 12288 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0004_b21, by decide, c0004_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0004_b22, by decide, c0004_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0004_b23, by decide, c0004_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0004_b24, by decide, c0004_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0004_b25, by decide, c0004_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 190, c0004_b26, by decide, c0004_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 198, c0004_b27, by decide, c0004_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 196, c0004_b28, by decide, c0004_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0004_b29, by decide, c0004_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 189, c0004_b30, by decide, c0004_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 194, c0004_b31, by decide, c0004_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 200, c0004_b32, by decide, c0004_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 188, c0004_b33, by decide, c0004_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0004_b34, by decide, c0004_ok34⟩, ?_⟩
  simp

def s34 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 232113757366008801543585792, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 4990445783369189233187094528, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 7427640235712281649394745344]
theorem e34 : enumKeys 12288 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0004_b35, by decide, c0004_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0004_b36, by decide, c0004_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0004_b37, by decide, c0004_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 222, c0004_b38, by decide, c0004_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 230, c0004_b39, by decide, c0004_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0004_b36, by decide, by rw [tL, t34, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0004_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 222, c0004_b38, by decide, by rw [tL, t34, show rM 2495222891684594616593547264 = 1276625665513048408489721856 by decide]; exact c0004_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0004_b35, by decide, by rw [tL, t34, show rM 2553251331026096816979443712 = 116056878683004400771792896 by decide]; exact c0004_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0005_b0, by decide, c0005_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 205, c0005_b1, by decide, c0005_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 208, c0005_b2, by decide, c0005_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 195, c0005_b3, by decide, c0005_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 205, c0005_b1, by decide, by rw [tL, t34, show rM 6267071448882237641676816384 = 5048474222710691433572990976 by decide]; exact c0005_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 192, c0005_b0, by decide, by rw [tL, t34, show rM 7427640235712281649394745344 = 4990445783369189233187094528 by decide]; exact c0005_ok0⟩, ?_⟩
  simp

def s35 : List Nat := [58028439341502200385896448, 19845726254793752531976585216, 39633424070246002863567273984, 59421121885698253195157962752]
theorem e35 : enumKeys 12288 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0000_b21, by decide, by rw [tL, t35, show rM 58028439341502200385896448 = 3713820117856140824697372672 by decide]; exact c0000_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 132, c0000_b20, by decide, by rw [tL, t35, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0000_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 118, c0000_b19, by decide, by rw [tL, t35, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0000_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 108, c0000_b18, by decide, by rw [tL, t35, show rM 59421121885698253195157962752 = 928455029464035206174343168 by decide]; exact c0000_ok18⟩, ?_⟩
  simp

def s36 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 1276625665513048408489721856, 1334654104854550608875618304, 19845726254793752531976585216, 19903754694135254732362481664, 21064323480965298740080410624, 21122351920306800940466307072, 39633424070246002863567273984, 39691452509587505063953170432, 40852021296417549071671099392]
theorem e36 : enumKeys 12288 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 168, c0003_b6, by decide, by rw [tL, t36, show rM 58028439341502200385896448 = 3713820117856140824697372672 by decide]; exact c0003_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 172, c0003_b4, by decide, by rw [tL, t36, show rM 116056878683004400771792896 = 2553251331026096816979443712 by decide]; exact c0003_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 166, c0003_b3, by decide, by rw [tL, t36, show rM 1276625665513048408489721856 = 2495222891684594616593547264 by decide]; exact c0003_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 166, c0002_b39, by decide, by rw [tL, t36, show rM 1334654104854550608875618304 = 1334654104854550608875618304 by decide]; exact c0002_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 160, c0003_b5, by decide, by rw [tL, t36, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0003_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 157, c0003_b1, by decide, by rw [tL, t36, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0003_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 154, c0003_b0, by decide, by rw [tL, t36, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0003_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 150, c0002_b36, by decide, by rw [tL, t36, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0002_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 150, c0003_b2, by decide, by rw [tL, t36, show rM 39633424070246002863567273984 = 1856910058928070412348686336 by decide]; exact c0003_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0002_b38, by decide, by rw [tL, t36, show rM 39691452509587505063953170432 = 696341272098026404630757376 by decide]; exact c0002_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0002_b37, by decide, by rw [tL, t36, show rM 40852021296417549071671099392 = 638312832756524204244860928 by decide]; exact c0002_ok37⟩, ?_⟩
  simp

def s37 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 19845726254793752531976585216, 19903754694135254732362481664, 19961783133476756932748378112, 21064323480965298740080410624, 21122351920306800940466307072, 22282920707136844948184236032]
theorem e37 : enumKeys 12288 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 192, c0004_b34, by decide, by rw [tL, t37, show rM 58028439341502200385896448 = 3713820117856140824697372672 by decide]; exact c0004_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 200, c0004_b32, by decide, by rw [tL, t37, show rM 116056878683004400771792896 = 2553251331026096816979443712 by decide]; exact c0004_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 196, c0004_b28, by decide, by rw [tL, t37, show rM 174085318024506601157689344 = 1392682544196052809261514752 by decide]; exact c0004_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 194, c0004_b31, by decide, by rw [tL, t37, show rM 1276625665513048408489721856 = 2495222891684594616593547264 by decide]; exact c0004_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 198, c0004_b27, by decide, by rw [tL, t37, show rM 1334654104854550608875618304 = 1334654104854550608875618304 by decide]; exact c0004_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 192, c0004_b22, by decide, by rw [tL, t37, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0004_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 190, c0004_b26, by decide, by rw [tL, t37, show rM 2495222891684594616593547264 = 1276625665513048408489721856 by decide]; exact c0004_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 192, c0004_b21, by decide, by rw [tL, t37, show rM 2553251331026096816979443712 = 116056878683004400771792896 by decide]; exact c0004_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 188, c0004_b33, by decide, by rw [tL, t37, show rM 19845726254793752531976585216 = 2785365088392105618523029504 by decide]; exact c0004_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 189, c0004_b30, by decide, by rw [tL, t37, show rM 19903754694135254732362481664 = 1624796301562061610805100544 by decide]; exact c0004_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 180, c0004_b25, by decide, by rw [tL, t37, show rM 19961783133476756932748378112 = 464227514732017603087171584 by decide]; exact c0004_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 186, c0004_b29, by decide, by rw [tL, t37, show rM 21064323480965298740080410624 = 1566767862220559410419204096 by decide]; exact c0004_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 186, c0004_b24, by decide, by rw [tL, t37, show rM 21122351920306800940466307072 = 406199075390515402701275136 by decide]; exact c0004_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 180, c0004_b23, by decide, by rw [tL, t37, show rM 22282920707136844948184236032 = 348170636049013202315378688 by decide]; exact c0004_ok23⟩, ?_⟩
  simp

def s38 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 174085318024506601157689344, 232113757366008801543585792, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 3713820117856140824697372672]
theorem e38 : enumKeys 12288 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0005_b4, by decide, c0005_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0005_b5, by decide, c0005_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0005_b6, by decide, c0005_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0005_b7, by decide, c0005_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 222, c0005_b8, by decide, c0005_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 230, c0005_b9, by decide, c0005_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0005_b6, by decide, by rw [tL, t38, show rM 1392682544196052809261514752 = 174085318024506601157689344 by decide]; exact c0005_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 222, c0005_b8, by decide, by rw [tL, t38, show rM 2495222891684594616593547264 = 1276625665513048408489721856 by decide]; exact c0005_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0005_b5, by decide, by rw [tL, t38, show rM 2553251331026096816979443712 = 116056878683004400771792896 by decide]; exact c0005_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 216, c0005_b4, by decide, by rw [tL, t38, show rM 3713820117856140824697372672 = 58028439341502200385896448 by decide]; exact c0005_ok4⟩, ?_⟩
  simp

/-- every enumerated key with left type `12288` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 12288 mR,
    (12288 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 12288) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · exact fun M _ => Or.inl ⟨rfl, rfl⟩

end K00
end Grid3.Three.Cert
