import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C0000
import Grid3.Three.Cert.Data.C0001
import Grid3.Three.Cert.Data.C0002
import Grid3.Three.Cert.Data.C0003
import Grid3.Three.Cert.Data.C0004
import Grid3.Three.Cert.Data.C0005
import Grid3.Three.Cert.Data.C0006
import Grid3.Three.Cert.Data.C0007
import Grid3.Three.Cert.Data.C0008
import Grid3.Three.Cert.Data.C0009
import Grid3.Three.Cert.Data.C0010
import Grid3.Three.Cert.Data.C0011
import Grid3.Three.Cert.Data.C0012
import Grid3.Three.Cert.Data.C0013
import Grid3.Three.Cert.Data.C0014
import Grid3.Three.Cert.Data.C0015
import Grid3.Three.Cert.Data.C0016
import Grid3.Three.Cert.Data.C0017
import Grid3.Three.Cert.Data.C0018
import Grid3.Three.Cert.Data.C0019
import Grid3.Three.Cert.Data.C0020
import Grid3.Three.Cert.Data.C0021
import Grid3.Three.Cert.Data.C0022
import Grid3.Three.Cert.Data.C0023
import Grid3.Three.Cert.Data.C0024
import Grid3.Three.Cert.Data.C0025
import Grid3.Three.Cert.Data.C0026
import Grid3.Three.Cert.Data.C0027
import Grid3.Three.Cert.Data.C0028
import Grid3.Three.Cert.Data.C0029
import Grid3.Three.Cert.Data.C0030
import Grid3.Three.Cert.Data.C0031
import Grid3.Three.Cert.Data.C0032
import Grid3.Three.Cert.Data.C0033
import Grid3.Three.Cert.Data.C0034
import Grid3.Three.Cert.Data.C0035
import Grid3.Three.Cert.Data.C0036
import Grid3.Three.Cert.Data.C0037

/-! Seam keys with left type `12288` (type index 0): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K00

def s00 : List Nat := [237684487542793012780631851008]
theorem e00 : enumKeys 12288 12288 = s00 := by decide +kernel

def s01 : List Nat := [25068285795528950566707265536, 84489407681227203761865228288, 99344688152651767060654718976, 103986963299971943091526434816]
theorem e01 : enumKeys 12288 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨1, 91, c0000_b3, by decide, c0000_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 83, c0000_b2, by decide, c0000_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 94, c0000_b1, by decide, c0000_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 83, c0000_b0, by decide, c0000_ok0⟩, ?_⟩
  simp

def s02 : List Nat := [80775587563371062937167855616, 158765810038350020255812681728, 159694265067814055461987024896]
theorem e02 : enumKeys 12288 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨1, 80, c0000_b6, by decide, c0000_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 72, c0000_b5, by decide, c0000_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 74, c0000_b4, by decide, c0000_ok4⟩, ?_⟩
  simp

def s03 : List Nat := [1856910058928070412348686336, 5570730176784211237046059008, 6499185206248246443220402176, 20426010648208774535835549696, 21354465677672809742009892864, 25068285795528950566707265536, 25996740824992985772881608704]
theorem e03 : enumKeys 12288 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0001_b3, by decide, c0001_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 106, c0001_b2, by decide, c0001_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 109, c0001_b0, by decide, c0001_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 116, c0001_b1, by decide, c0001_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0000_b9, by decide, c0000_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 107, c0000_b8, by decide, c0000_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 113, c0000_b7, by decide, c0000_ok7⟩, ?_⟩
  simp

def s04 : List Nat := [1856910058928070412348686336, 2785365088392105618523029504, 79847132533907027730993512448, 80775587563371062937167855616, 81704042592835098143342198784]
theorem e04 : enumKeys 12288 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨1, 102, c0001_b8, by decide, c0001_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 112, c0001_b6, by decide, c0001_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 90, c0001_b7, by decide, c0001_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c0001_b5, by decide, c0001_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c0001_b4, by decide, c0001_ok4⟩, ?_⟩
  simp

def s05 : List Nat := [928455029464035206174343168, 1856910058928070412348686336, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e05 : enumKeys 12288 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨1, 108, c0002_b2, by decide, c0002_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c0002_b1, by decide, c0002_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c0002_b0, by decide, c0002_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0001_b9, by decide, c0001_ok9⟩, ?_⟩
  simp

def s06 : List Nat := [84257293923861194960321642496, 158533696280984011454269095936, 163408085185670196286684397568]
theorem e06 : enumKeys 12288 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨1, 97, c0002_b5, by decide, c0002_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 100, c0002_b4, by decide, c0002_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 84, c0002_b3, by decide, c0002_ok3⟩, ?_⟩
  simp

def s07 : List Nat := [5338616419418202435502473216, 9980891566738378466374189056, 10213005324104387267917774848, 20193896890842765734291963904, 24836172038162941765163679744, 25068285795528950566707265536, 29710560942849126597578981376]
theorem e07 : enumKeys 12288 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0003_b2, by decide, c0003_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0003_b0, by decide, c0003_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c0002_b8, by decide, c0002_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 148, c0003_b1, by decide, c0003_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0002_b9, by decide, c0002_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 135, c0002_b7, by decide, c0002_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c0002_b6, by decide, c0002_ok6⟩, ?_⟩
  simp

def s08 : List Nat := [1624796301562061610805100544, 5338616419418202435502473216, 6267071448882237641676816384, 6499185206248246443220402176, 79615018776541018929449926656, 80543473806005054135624269824, 80775587563371062937167855616, 84257293923861194960321642496, 84489407681227203761865228288, 85417862710691238968039571456]
theorem e08 : enumKeys 12288 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0004_b2, by decide, c0004_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0004_b1, by decide, c0004_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 129, c0003_b9, by decide, c0003_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0003_b6, by decide, c0003_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0004_b0, by decide, c0004_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0003_b8, by decide, c0003_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0003_b5, by decide, c0003_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 113, c0003_b7, by decide, c0003_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 107, c0003_b4, by decide, c0003_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 109, c0003_b3, by decide, c0003_ok3⟩, ?_⟩
  simp

def s09 : List Nat := [696341272098026404630757376, 1624796301562061610805100544, 1856910058928070412348686336, 2553251331026096816979443712, 2785365088392105618523029504, 5338616419418202435502473216, 5570730176784211237046059008, 6267071448882237641676816384, 6499185206248246443220402176, 7427640235712281649394745344]
theorem e09 : enumKeys 12288 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0005_b2, by decide, c0005_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0005_b1, by decide, c0005_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0004_b7, by decide, c0004_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0004_b9, by decide, c0004_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c0004_b5, by decide, c0004_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0005_b0, by decide, c0005_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0004_b6, by decide, c0004_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 149, c0004_b8, by decide, c0004_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0004_b4, by decide, c0004_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0004_b3, by decide, c0004_ok3⟩, ?_⟩
  simp

def s10 : List Nat := [5106502662052193633958887424, 9980891566738378466374189056, 79382905019175010127906340864, 84257293923861194960321642496, 89131682828547379792736944128]
theorem e10 : enumKeys 12288 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0005_b7, by decide, c0005_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 138, c0005_b5, by decide, c0005_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0005_b6, by decide, c0005_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0005_b4, by decide, c0005_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 114, c0005_b3, by decide, c0005_ok3⟩, ?_⟩
  simp

def s11 : List Nat := [464227514732017603087171584, 1392682544196052809261514752, 1624796301562061610805100544, 5106502662052193633958887424, 5338616419418202435502473216, 6267071448882237641676816384, 6499185206248246443220402176, 9980891566738378466374189056, 10213005324104387267917774848, 11141460353568422474092118016]
theorem e11 : enumKeys 12288 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0006_b7, by decide, c0006_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0006_b6, by decide, c0006_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0006_b4, by decide, c0006_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0006_b5, by decide, c0006_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 169, c0006_b3, by decide, c0006_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 177, c0006_b2, by decide, c0006_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 165, c0006_b0, by decide, c0006_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0006_b1, by decide, c0006_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 142, c0005_b9, by decide, c0005_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0005_b8, by decide, c0005_ok8⟩, ?_⟩
  simp

def s12 : List Nat := [232113757366008801543585792, 5106502662052193633958887424, 9980891566738378466374189056, 14855280471424563298789490688]
theorem e12 : enumKeys 12288 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0007_b1, by decide, c0007_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c0007_b0, by decide, c0007_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 182, c0006_b9, by decide, c0006_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0006_b8, by decide, c0006_ok8⟩, ?_⟩
  simp

def s13 : List Nat := [99054545955944256058725236736, 158475667841642509253883199488, 178263365657094759585473888256]
theorem e13 : enumKeys 12288 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨1, 80, c0007_b4, by decide, c0007_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 74, c0007_b3, by decide, c0007_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 72, c0007_b2, by decide, c0007_ok2⟩, ?_⟩
  simp

def s14 : List Nat := [5280587980076700235116576768, 20135868451501263533906067456, 24778143598821439564777783296, 25068285795528950566707265536, 39633424070246002863567273984, 39923566266953513865496756224, 44565841414273689896368472064]
theorem e14 : enumKeys 12288 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨1, 113, c0008_b1, by decide, c0008_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0008_b0, by decide, c0008_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 109, c0007_b9, by decide, c0007_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 107, c0007_b7, by decide, c0007_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0007_b8, by decide, c0007_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 116, c0007_b6, by decide, c0007_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 106, c0007_b5, by decide, c0007_ok5⟩, ?_⟩
  simp

def s15 : List Nat := [1566767862220559410419204096, 20135868451501263533906067456, 21064323480965298740080410624, 21354465677672809742009892864, 79556990337199516729064030208, 80485445366663551935238373376, 80775587563371062937167855616, 99054545955944256058725236736, 99344688152651767060654718976, 100273143182115802266829062144]
theorem e15 : enumKeys 12288 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨1, 110, c0009_b1, by decide, c0009_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c0009_b0, by decide, c0009_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 110, c0008_b8, by decide, c0008_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c0008_b5, by decide, c0008_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 97, c0008_b9, by decide, c0008_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 98, c0008_b7, by decide, c0008_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c0008_b4, by decide, c0008_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c0008_b6, by decide, c0008_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 94, c0008_b3, by decide, c0008_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 97, c0008_b2, by decide, c0008_ok2⟩, ?_⟩
  simp

def s16 : List Nat := [638312832756524204244860928, 1566767862220559410419204096, 1856910058928070412348686336, 2495222891684594616593547264, 2785365088392105618523029504, 20135868451501263533906067456, 20426010648208774535835549696, 21064323480965298740080410624, 21354465677672809742009892864, 22282920707136844948184236032]
theorem e16 : enumKeys 12288 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨1, 120, c0010_b1, by decide, c0010_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0010_b0, by decide, c0010_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0009_b6, by decide, c0009_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 134, c0009_b8, by decide, c0009_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 128, c0009_b4, by decide, c0009_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 120, c0009_b9, by decide, c0009_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 116, c0009_b5, by decide, c0009_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0009_b7, by decide, c0009_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0009_b3, by decide, c0009_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c0009_b2, by decide, c0009_ok2⟩, ?_⟩
  simp

def s17 : List Nat := [5048474222710691433572990976, 19903754694135254732362481664, 24778143598821439564777783296, 24836172038162941765163679744, 79324876579833507927520444416, 84199265484519692759935746048, 84257293923861194960321642496, 99054545955944256058725236736, 99112574395285758259111133184, 103986963299971943091526434816]
theorem e17 : enumKeys 12288 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨1, 129, c0011_b1, by decide, c0011_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0011_b0, by decide, c0011_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0010_b8, by decide, c0010_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0010_b5, by decide, c0010_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0010_b9, by decide, c0010_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 109, c0010_b7, by decide, c0010_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 113, c0010_b4, by decide, c0010_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0010_b6, by decide, c0010_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0010_b3, by decide, c0010_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 107, c0010_b2, by decide, c0010_ok2⟩, ?_⟩
  simp

def s18 : List Nat := [1334654104854550608875618304, 79324876579833507927520444416, 80485445366663551935238373376, 80543473806005054135624269824, 158475667841642509253883199488, 158533696280984011454269095936, 159694265067814055461987024896]
theorem e18 : enumKeys 12288 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0011_b8, by decide, c0011_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 110, c0011_b7, by decide, c0011_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 110, c0011_b6, by decide, c0011_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 110, c0011_b4, by decide, c0011_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 98, c0011_b5, by decide, c0011_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 100, c0011_b3, by decide, c0011_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 98, c0011_b2, by decide, c0011_ok2⟩, ?_⟩
  simp

def s19 : List Nat := [406199075390515402701275136, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 5048474222710691433572990976, 5280587980076700235116576768, 5338616419418202435502473216, 6209043009540735441290919936, 6267071448882237641676816384, 6499185206248246443220402176, 19903754694135254732362481664, 20135868451501263533906067456, 20193896890842765734291963904, 21064323480965298740080410624, 21122351920306800940466307072, 21354465677672809742009892864, 24778143598821439564777783296, 24836172038162941765163679744, 25068285795528950566707265536, 25996740824992985772881608704]
theorem e19 : enumKeys 12288 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0013_b8, by decide, c0013_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0013_b7, by decide, c0013_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0013_b4, by decide, c0013_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0012_b8, by decide, c0012_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 145, c0013_b6, by decide, c0013_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0013_b3, by decide, c0013_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0012_b7, by decide, c0012_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 139, c0013_b1, by decide, c0013_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 145, c0012_b5, by decide, c0012_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0012_b2, by decide, c0012_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0013_b5, by decide, c0013_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0013_b2, by decide, c0013_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 148, c0012_b6, by decide, c0012_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0013_b0, by decide, c0013_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0012_b4, by decide, c0012_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0012_b1, by decide, c0012_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0012_b9, by decide, c0012_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0012_b3, by decide, c0012_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 135, c0012_b0, by decide, c0012_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0011_b9, by decide, c0011_ok9⟩, ?_⟩
  simp

def s20 : List Nat := [406199075390515402701275136, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 79324876579833507927520444416, 79556990337199516729064030208, 79615018776541018929449926656, 80485445366663551935238373376, 80543473806005054135624269824, 80775587563371062937167855616, 81704042592835098143342198784]
theorem e20 : enumKeys 12288 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨1, 134, c0015_b2, by decide, c0015_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 146, c0015_b1, by decide, c0015_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 138, c0014_b9, by decide, c0014_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0014_b5, by decide, c0014_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 146, c0014_b7, by decide, c0014_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 148, c0014_b3, by decide, c0014_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 140, c0014_b1, by decide, c0014_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0015_b0, by decide, c0015_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0014_b8, by decide, c0014_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0014_b4, by decide, c0014_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0014_b6, by decide, c0014_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0014_b2, by decide, c0014_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0014_b0, by decide, c0014_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 128, c0013_b9, by decide, c0013_ok9⟩, ?_⟩
  simp

def s21 : List Nat := [406199075390515402701275136, 638312832756524204244860928, 696341272098026404630757376, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 1856910058928070412348686336, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e21 : enumKeys 12288 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0016_b3, by decide, c0016_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0016_b1, by decide, c0016_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0015_b8, by decide, c0015_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0016_b2, by decide, c0016_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0016_b0, by decide, c0016_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0015_b7, by decide, c0015_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0015_b5, by decide, c0015_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0015_b9, by decide, c0015_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0015_b6, by decide, c0015_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c0015_b4, by decide, c0015_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0015_b3, by decide, c0015_ok3⟩, ?_⟩
  simp

def s22 : List Nat := [174085318024506601157689344, 5048474222710691433572990976, 5106502662052193633958887424, 9922863127396876265988292608, 9980891566738378466374189056, 19903754694135254732362481664, 19961783133476756932748378112, 24778143598821439564777783296, 24836172038162941765163679744, 29710560942849126597578981376]
theorem e22 : enumKeys 12288 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0017_b3, by decide, c0017_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 177, c0017_b2, by decide, c0017_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0016_b8, by decide, c0016_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0017_b0, by decide, c0017_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0016_b6, by decide, c0016_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0017_b1, by decide, c0017_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0016_b7, by decide, c0016_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 165, c0016_b9, by decide, c0016_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 169, c0016_b5, by decide, c0016_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 142, c0016_b4, by decide, c0016_ok4⟩, ?_⟩
  simp

def s23 : List Nat := [174085318024506601157689344, 1334654104854550608875618304, 1392682544196052809261514752, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 79324876579833507927520444416, 79382905019175010127906340864, 80485445366663551935238373376, 80543473806005054135624269824, 84199265484519692759935746048, 84257293923861194960321642496, 85417862710691238968039571456]
theorem e23 : enumKeys 12288 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0018_b7, by decide, c0018_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 178, c0018_b6, by decide, c0018_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0018_b0, by decide, c0018_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0018_b5, by decide, c0018_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0017_b9, by decide, c0017_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 151, c0018_b3, by decide, c0018_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0017_b7, by decide, c0017_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0018_b4, by decide, c0018_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0017_b8, by decide, c0017_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0018_b2, by decide, c0018_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0017_b6, by decide, c0017_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 133, c0018_b1, by decide, c0018_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 141, c0017_b5, by decide, c0017_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 133, c0017_b4, by decide, c0017_ok4⟩, ?_⟩
  simp

def s24 : List Nat := [174085318024506601157689344, 406199075390515402701275136, 464227514732017603087171584, 1334654104854550608875618304, 1392682544196052809261514752, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 5048474222710691433572990976, 5106502662052193633958887424, 5280587980076700235116576768, 5338616419418202435502473216, 6209043009540735441290919936, 6267071448882237641676816384, 6499185206248246443220402176, 7427640235712281649394745344]
theorem e24 : enumKeys 12288 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0020_b5, by decide, c0020_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0020_b4, by decide, c0020_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0019_b7, by decide, c0019_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c0020_b3, by decide, c0020_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0019_b6, by decide, c0019_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0020_b1, by decide, c0020_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0019_b4, by decide, c0019_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c0019_b9, by decide, c0019_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c0019_b2, by decide, c0019_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c0019_b0, by decide, c0019_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 173, c0020_b2, by decide, c0020_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0019_b5, by decide, c0019_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 161, c0020_b0, by decide, c0020_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 169, c0019_b3, by decide, c0019_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 167, c0019_b8, by decide, c0019_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 177, c0019_b1, by decide, c0019_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 165, c0018_b9, by decide, c0018_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0018_b8, by decide, c0018_ok8⟩, ?_⟩
  simp

def s25 : List Nat := [174085318024506601157689344, 232113757366008801543585792, 1334654104854550608875618304, 1392682544196052809261514752, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 9922863127396876265988292608, 9980891566738378466374189056, 11141460353568422474092118016]
theorem e25 : enumKeys 12288 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0021_b6, by decide, c0021_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0021_b1, by decide, c0021_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c0021_b5, by decide, c0021_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0021_b0, by decide, c0021_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c0021_b4, by decide, c0021_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c0020_b9, by decide, c0020_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 195, c0021_b3, by decide, c0021_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c0020_b8, by decide, c0020_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0021_b2, by decide, c0021_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 182, c0020_b7, by decide, c0020_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0020_b6, by decide, c0020_ok6⟩, ?_⟩
  simp

def s26 : List Nat := [19845726254793752531976585216, 39633424070246002863567273984, 79266848140492005727134547968, 99054545955944256058725236736, 118842243771396506390315925504]
theorem e26 : enumKeys 12288 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨1, 112, c0022_b1, by decide, c0022_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 102, c0021_b9, by decide, c0021_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c0022_b0, by decide, c0022_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c0021_b8, by decide, c0021_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 90, c0021_b7, by decide, c0021_ok7⟩, ?_⟩
  simp

def s27 : List Nat := [348170636049013202315378688, 1276625665513048408489721856, 1566767862220559410419204096, 19845726254793752531976585216, 20135868451501263533906067456, 21064323480965298740080410624, 21354465677672809742009892864, 39633424070246002863567273984, 39923566266953513865496756224, 40852021296417549071671099392]
theorem e27 : enumKeys 12288 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c0023_b1, by decide, c0023_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 134, c0023_b0, by decide, c0023_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0022_b8, by decide, c0022_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 128, c0022_b9, by decide, c0022_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0022_b7, by decide, c0022_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0022_b6, by decide, c0022_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 120, c0022_b4, by decide, c0022_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0022_b5, by decide, c0022_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 116, c0022_b3, by decide, c0022_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 120, c0022_b2, by decide, c0022_ok2⟩, ?_⟩
  simp

def s28 : List Nat := [116056878683004400771792896, 4990445783369189233187094528, 5048474222710691433572990976, 19845726254793752531976585216, 19903754694135254732362481664, 24778143598821439564777783296, 24836172038162941765163679744, 39633424070246002863567273984, 39691452509587505063953170432, 44565841414273689896368472064]
theorem e28 : enumKeys 12288 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0024_b1, by decide, c0024_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0024_b0, by decide, c0024_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 149, c0023_b8, by decide, c0023_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c0023_b9, by decide, c0023_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0023_b7, by decide, c0023_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0023_b6, by decide, c0023_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0023_b4, by decide, c0023_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0023_b5, by decide, c0023_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0023_b3, by decide, c0023_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0023_b2, by decide, c0023_ok2⟩, ?_⟩
  simp

def s29 : List Nat := [116056878683004400771792896, 1276625665513048408489721856, 1334654104854550608875618304, 19845726254793752531976585216, 19903754694135254732362481664, 21064323480965298740080410624, 21122351920306800940466307072, 79266848140492005727134547968, 79324876579833507927520444416, 80485445366663551935238373376, 80543473806005054135624269824, 99054545955944256058725236736, 99112574395285758259111133184, 100273143182115802266829062144]
theorem e29 : enumKeys 12288 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨1, 148, c0025_b5, by decide, c0025_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 146, c0025_b4, by decide, c0025_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 146, c0025_b1, by decide, c0025_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 140, c0025_b3, by decide, c0025_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 137, c0025_b0, by decide, c0025_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 138, c0024_b8, by decide, c0024_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 134, c0024_b5, by decide, c0024_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 128, c0025_b2, by decide, c0025_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 130, c0024_b9, by decide, c0024_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0024_b7, by decide, c0024_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 126, c0024_b4, by decide, c0024_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 124, c0024_b6, by decide, c0024_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 122, c0024_b3, by decide, c0024_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 121, c0024_b2, by decide, c0024_ok2⟩, ?_⟩
  simp

def s30 : List Nat := [116056878683004400771792896, 348170636049013202315378688, 406199075390515402701275136, 1276625665513048408489721856, 1334654104854550608875618304, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 19845726254793752531976585216, 19903754694135254732362481664, 20135868451501263533906067456, 20193896890842765734291963904, 21064323480965298740080410624, 21122351920306800940466307072, 21354465677672809742009892864, 22282920707136844948184236032]
theorem e30 : enumKeys 12288 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨1, 164, c0027_b3, by decide, c0027_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0027_b2, by decide, c0027_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0026_b9, by decide, c0026_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 162, c0027_b1, by decide, c0027_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0026_b8, by decide, c0026_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0026_b6, by decide, c0026_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0026_b2, by decide, c0026_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 162, c0026_b4, by decide, c0026_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 164, c0026_b0, by decide, c0026_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0025_b8, by decide, c0025_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0027_b0, by decide, c0027_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0026_b7, by decide, c0026_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0026_b5, by decide, c0026_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 148, c0026_b1, by decide, c0026_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0026_b3, by decide, c0026_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0025_b9, by decide, c0025_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0025_b7, by decide, c0025_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c0025_b6, by decide, c0025_ok6⟩, ?_⟩
  simp

def s31 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 4990445783369189233187094528, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 19845726254793752531976585216, 19903754694135254732362481664, 19961783133476756932748378112, 21064323480965298740080410624, 21122351920306800940466307072, 24778143598821439564777783296, 24836172038162941765163679744, 25996740824992985772881608704]
theorem e31 : enumKeys 12288 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c0029_b1, by decide, c0029_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0028_b7, by decide, c0028_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c0029_b0, by decide, c0029_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c0028_b6, by decide, c0028_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0028_b0, by decide, c0028_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0028_b9, by decide, c0028_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 177, c0028_b5, by decide, c0028_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0027_b9, by decide, c0027_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 167, c0028_b3, by decide, c0028_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 173, c0027_b7, by decide, c0027_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c0028_b8, by decide, c0028_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0028_b4, by decide, c0028_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0027_b8, by decide, c0027_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0028_b2, by decide, c0028_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0027_b6, by decide, c0027_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 165, c0028_b1, by decide, c0028_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 169, c0027_b5, by decide, c0027_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 161, c0027_b4, by decide, c0027_ok4⟩, ?_⟩
  simp

def s32 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 79266848140492005727134547968, 79324876579833507927520444416, 79382905019175010127906340864, 80485445366663551935238373376, 80543473806005054135624269824, 81704042592835098143342198784]
theorem e32 : enumKeys 12288 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0030_b4, by decide, c0030_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0030_b1, by decide, c0030_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 174, c0030_b3, by decide, c0030_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 178, c0030_b0, by decide, c0030_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0029_b6, by decide, c0029_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 174, c0029_b8, by decide, c0029_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 176, c0029_b4, by decide, c0029_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0030_b2, by decide, c0030_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0029_b9, by decide, c0029_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0029_b5, by decide, c0029_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0029_b7, by decide, c0029_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 158, c0029_b3, by decide, c0029_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 152, c0029_b2, by decide, c0029_ok2⟩, ?_⟩
  simp

def s33 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 348170636049013202315378688, 406199075390515402701275136, 464227514732017603087171584, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 1566767862220559410419204096, 1624796301562061610805100544, 2495222891684594616593547264, 2553251331026096816979443712, 2785365088392105618523029504, 3713820117856140824697372672]
theorem e33 : enumKeys 12288 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0031_b8, by decide, c0031_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0031_b5, by decide, c0031_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0031_b7, by decide, c0031_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0031_b4, by decide, c0031_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0031_b0, by decide, c0031_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 190, c0031_b6, by decide, c0031_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c0031_b3, by decide, c0031_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0030_b9, by decide, c0030_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0031_b2, by decide, c0031_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0030_b8, by decide, c0030_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c0031_b1, by decide, c0031_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c0030_b7, by decide, c0030_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c0030_b6, by decide, c0030_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0030_b5, by decide, c0030_ok5⟩, ?_⟩
  simp

def s34 : List Nat := [116056878683004400771792896, 174085318024506601157689344, 232113757366008801543585792, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 4990445783369189233187094528, 5048474222710691433572990976, 5106502662052193633958887424, 6209043009540735441290919936, 6267071448882237641676816384, 7427640235712281649394745344]
theorem e34 : enumKeys 12288 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0033_b2, by decide, c0033_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0032_b9, by decide, c0032_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0032_b4, by decide, c0032_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c0033_b1, by decide, c0033_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c0032_b8, by decide, c0032_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0032_b3, by decide, c0032_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c0032_b6, by decide, c0032_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0032_b1, by decide, c0032_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0033_b0, by decide, c0033_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c0032_b7, by decide, c0032_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c0032_b2, by decide, c0032_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 195, c0032_b5, by decide, c0032_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c0032_b0, by decide, c0032_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0031_b9, by decide, c0031_ok9⟩, ?_⟩
  simp

def s35 : List Nat := [58028439341502200385896448, 19845726254793752531976585216, 39633424070246002863567273984, 59421121885698253195157962752]
theorem e35 : enumKeys 12288 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0033_b6, by decide, c0033_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c0033_b5, by decide, c0033_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c0033_b4, by decide, c0033_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 108, c0033_b3, by decide, c0033_ok3⟩, ?_⟩
  simp

def s36 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 1276625665513048408489721856, 1334654104854550608875618304, 19845726254793752531976585216, 19903754694135254732362481664, 21064323480965298740080410624, 21122351920306800940466307072, 39633424070246002863567273984, 39691452509587505063953170432, 40852021296417549071671099392]
theorem e36 : enumKeys 12288 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c0034_b7, by decide, c0034_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c0034_b6, by decide, c0034_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0034_b5, by decide, c0034_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c0034_b3, by decide, c0034_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c0034_b4, by decide, c0034_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c0034_b2, by decide, c0034_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c0034_b1, by decide, c0034_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0033_b9, by decide, c0033_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c0034_b0, by decide, c0034_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0033_b8, by decide, c0033_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0033_b7, by decide, c0033_ok7⟩, ?_⟩
  simp

def s37 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 174085318024506601157689344, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 19845726254793752531976585216, 19903754694135254732362481664, 19961783133476756932748378112, 21064323480965298740080410624, 21122351920306800940466307072, 22282920707136844948184236032]
theorem e37 : enumKeys 12288 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0036_b1, by decide, c0036_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c0036_b0, by decide, c0036_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c0035_b7, by decide, c0035_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c0035_b9, by decide, c0035_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c0035_b6, by decide, c0035_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0035_b2, by decide, c0035_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 190, c0035_b4, by decide, c0035_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c0035_b0, by decide, c0035_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c0035_b8, by decide, c0035_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c0035_b5, by decide, c0035_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0035_b1, by decide, c0035_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0035_b3, by decide, c0035_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c0034_b9, by decide, c0034_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c0034_b8, by decide, c0034_ok8⟩, ?_⟩
  simp

def s38 : List Nat := [58028439341502200385896448, 116056878683004400771792896, 174085318024506601157689344, 232113757366008801543585792, 1276625665513048408489721856, 1334654104854550608875618304, 1392682544196052809261514752, 2495222891684594616593547264, 2553251331026096816979443712, 3713820117856140824697372672]
theorem e38 : enumKeys 12288 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0037_b1, by decide, c0037_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0037_b0, by decide, c0037_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0036_b8, by decide, c0036_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0036_b5, by decide, c0036_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c0036_b9, by decide, c0036_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c0036_b7, by decide, c0036_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0036_b4, by decide, c0036_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c0036_b6, by decide, c0036_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c0036_b3, by decide, c0036_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c0036_b2, by decide, c0036_ok2⟩, ?_⟩
  simp

/-- every enumerated key with left type `12288` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 12288 mR,
    (12288 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 12288 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · exact fun M _ => Or.inl ⟨rfl, rfl⟩

end K00
end Grid3.Three.Cert
