import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C0489
import Grid3.Three.Cert.Data.C0490
import Grid3.Three.Cert.Data.C0491
import Grid3.Three.Cert.Data.C0492
import Grid3.Three.Cert.Data.C0493
import Grid3.Three.Cert.Data.C0494
import Grid3.Three.Cert.Data.C0495
import Grid3.Three.Cert.Data.C0496
import Grid3.Three.Cert.Data.C0497
import Grid3.Three.Cert.Data.C0498
import Grid3.Three.Cert.Data.C0499
import Grid3.Three.Cert.Data.C0500
import Grid3.Three.Cert.Data.C0501
import Grid3.Three.Cert.Data.C0502
import Grid3.Three.Cert.Data.C0503
import Grid3.Three.Cert.Data.C0504
import Grid3.Three.Cert.Data.C0505
import Grid3.Three.Cert.Data.C0506
import Grid3.Three.Cert.Data.C0507
import Grid3.Three.Cert.Data.C0508
import Grid3.Three.Cert.Data.C0509
import Grid3.Three.Cert.Data.C0510
import Grid3.Three.Cert.Data.C0511
import Grid3.Three.Cert.Data.C0512
import Grid3.Three.Cert.Data.C0513
import Grid3.Three.Cert.Data.C0514
import Grid3.Three.Cert.Data.C0515
import Grid3.Three.Cert.Data.C0516
import Grid3.Three.Cert.Data.C0517
import Grid3.Three.Cert.Data.C0518
import Grid3.Three.Cert.Data.C0519
import Grid3.Three.Cert.Data.C0520
import Grid3.Three.Cert.Data.C0521
import Grid3.Three.Cert.Data.C0522
import Grid3.Three.Cert.Data.C0523
import Grid3.Three.Cert.Data.C0524
import Grid3.Three.Cert.Data.C0525
import Grid3.Three.Cert.Data.C0526
import Grid3.Three.Cert.Data.C0527
import Grid3.Three.Cert.Data.C0528
import Grid3.Three.Cert.Data.C0529
import Grid3.Three.Cert.Data.C0530
import Grid3.Three.Cert.Data.C0531
import Grid3.Three.Cert.Data.C0532
import Grid3.Three.Cert.Data.C0533
import Grid3.Three.Cert.Data.C0534
import Grid3.Three.Cert.Data.C0535
import Grid3.Three.Cert.Data.C0536
import Grid3.Three.Cert.Data.C0537
import Grid3.Three.Cert.Data.C0538
import Grid3.Three.Cert.Data.C0539
import Grid3.Three.Cert.Data.C0540
import Grid3.Three.Cert.Data.C0541
import Grid3.Three.Cert.Data.C0542
import Grid3.Three.Cert.Data.C0543
import Grid3.Three.Cert.Data.C0544
import Grid3.Three.Cert.Data.C0545
import Grid3.Three.Cert.Data.C0546
import Grid3.Three.Cert.Data.C0547
import Grid3.Three.Cert.Data.C0548
import Grid3.Three.Cert.Data.C0549
import Grid3.Three.Cert.Data.C0550
import Grid3.Three.Cert.Data.C0551
import Grid3.Three.Cert.Data.C0552
import Grid3.Three.Cert.Data.C0553
import Grid3.Three.Cert.Data.C0554
import Grid3.Three.Cert.Data.C0555
import Grid3.Three.Cert.Data.C0556
import Grid3.Three.Cert.Data.C0557
import Grid3.Three.Cert.Data.C0558
import Grid3.Three.Cert.Data.C0559
import Grid3.Three.Cert.Data.C0560
import Grid3.Three.Cert.Data.C0561

/-! Seam keys with left type `4256` (type index 4): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K04

def s00 : List Nat := [79228162514300366390562914304, 79228162514282353091565060096, 36029896530591744, 79228162514264339792567205888, 18016597532737536]
theorem e00 : enumKeys 4256 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c0489_b6, by decide, c0489_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c0489_b7, by decide, c0489_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 112, c0489_b8, by decide, c0489_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 90, c0489_b9, by decide, c0489_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 102, c0490_b0, by decide, c0490_ok0⟩, ?_⟩
  simp

def s01 : List Nat := [79228162514269967097373130752, 19807040628585224701097279488, 4951760157164039102028316672, 309485009843863135581110272, 79228162514268841266185764864, 19807040628584098869909913600, 22518071151296512, 309485009840485642019012608, 79228162514265463772623667200, 4951760157159535777278853120, 19140577589198848, 79228162514264337937141334016, 309485009839359810831646720, 309485009826975667770621952, 19807040628567211402099425280, 4951760157146025803030462464, 5630603340808192, 19807040628566085566617092096, 309485009825849836583256064, 4951760157141522473986031616, 309485009822472343021158400]
theorem e01 : enumKeys 4256 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0491_b2, by decide, c0491_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 121, c0491_b1, by decide, c0491_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c0491_b0, by decide, c0491_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0490_b5, by decide, c0490_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0492_b0, by decide, c0492_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c0491_b9, by decide, c0491_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0492_b1, by decide, c0492_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0490_b2, by decide, c0490_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 111, c0491_b7, by decide, c0491_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0491_b6, by decide, c0491_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0491_b8, by decide, c0491_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0490_b8, by decide, c0490_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0490_b9, by decide, c0490_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c0490_b1, by decide, c0490_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0491_b4, by decide, c0491_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0491_b3, by decide, c0491_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0491_b5, by decide, c0491_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0490_b6, by decide, c0490_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c0490_b7, by decide, c0490_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0490_b3, by decide, c0490_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c0490_b4, by decide, c0490_ok4⟩, ?_⟩
  simp

def s02 : List Nat := [309485009857373865743745024, 79228162514282633471325110272, 1237940039321409076213055488, 309485009839642041722601472, 79228162514264620172327256064, 1237940039303395777215201280, 18296977292787712, 1237940039285382473922379776, 309485009821628742724747264]
theorem e02 : enumKeys 4256 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0492_b2, by decide, c0492_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 91, c0492_b7, by decide, c0492_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c0492_b6, by decide, c0492_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 103, c0492_b3, by decide, c0492_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 87, c0492_b9, by decide, c0492_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c0492_b8, by decide, c0492_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 98, c0493_b0, by decide, c0493_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0492_b4, by decide, c0492_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 96, c0492_b5, by decide, c0492_ok5⟩, ?_⟩
  simp

def s03 : List Nat := [309485009826974572553961472, 19807040628567491781859475456, 4951760157146306182790512640, 1237940039291009783023271936, 19807040628566365946377142272, 1237940039289883947540938752, 309485009826130216343306240, 4951760157141802853746081792, 1237940039286506453978841088, 309485009822752722781208576, 1237940039285380618496507904, 309485009821626887298875392]
theorem e03 : enumKeys 4256 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0493_b3, by decide, c0493_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0494_b2, by decide, c0494_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 104, c0494_b1, by decide, c0494_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0494_b0, by decide, c0494_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0493_b8, by decide, c0493_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c0493_b7, by decide, c0493_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0493_b9, by decide, c0493_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0493_b5, by decide, c0493_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0493_b4, by decide, c0493_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c0493_b6, by decide, c0493_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0493_b1, by decide, c0493_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0493_b2, by decide, c0493_ok2⟩, ?_⟩
  simp

def s04 : List Nat := [309485009839640946505940992, 79228162514264900552087306240, 1237940039303676156975251456, 1237940039285662853682429952, 309485009821909122484797440]
theorem e04 : enumKeys 4256 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0494_b3, by decide, c0494_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 84, c0494_b7, by decide, c0494_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 102, c0494_b6, by decide, c0494_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0494_b4, by decide, c0494_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 93, c0494_b5, by decide, c0494_ok5⟩, ?_⟩
  simp

def s05 : List Nat := [309485009821908027268136960, 1237940039285943233442480128]
theorem e05 : enumKeys 4256 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c0494_b9, by decide, c0494_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c0494_b8, by decide, c0494_ok8⟩, ?_⟩
  simp

def s06 : List Nat := [79228162514283477893034016768, 4951760157177549897689202688, 77371252491365132919635968, 79228162514282352061846650880, 36028866812182528, 77371252474477665109147648, 79228162514265464594036162560, 4951760157159536598691348480, 19141399001694208, 79228162514264338761775054848, 77371252473351833921781760, 4951760157141523298619752448, 77371252456464366111293440]
theorem e06 : enumKeys 4256 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0495_b7, by decide, c0495_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0495_b6, by decide, c0495_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0495_b3, by decide, c0495_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0496_b1, by decide, c0496_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0496_b2, by decide, c0496_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0495_b0, by decide, c0495_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 119, c0495_b9, by decide, c0495_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 121, c0495_b8, by decide, c0495_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0496_b0, by decide, c0496_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0495_b4, by decide, c0495_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c0495_b5, by decide, c0495_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0495_b1, by decide, c0495_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0495_b2, by decide, c0495_ok2⟩, ?_⟩
  simp

def s07 : List Nat := [19807040628568336203568381952, 4951760157147150604499419136, 19807040628567210368086048768, 4951760157146024769017085952, 309485009826974638052212736, 19807040628567210371307274240, 4951760157146024772238311424, 77371252460965839729852416, 19807040628566084535824941056, 77371252459840004247519232, 309485009825848805791105024, 4951760157142647275454988288, 309485009823597144490115072, 4951760157142647278676213760, 77371252457588346167754752, 4951760157141521443193880576, 77371252456462510685421568, 309485009822471312229007360]
theorem e07 : enumKeys 4256 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0498_b0, by decide, c0498_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0497_b9, by decide, c0497_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0497_b7, by decide, c0497_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0497_b6, by decide, c0497_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0497_b8, by decide, c0497_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0497_b2, by decide, c0497_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0497_b1, by decide, c0497_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0497_b3, by decide, c0497_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0496_b6, by decide, c0496_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c0496_b8, by decide, c0496_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0496_b7, by decide, c0496_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0497_b4, by decide, c0497_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0497_b5, by decide, c0497_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0496_b9, by decide, c0496_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0497_b0, by decide, c0497_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c0496_b3, by decide, c0496_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0496_b5, by decide, c0496_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c0496_b4, by decide, c0496_ok4⟩, ?_⟩
  simp

def s08 : List Nat := [309485009840485368214847488, 77371252474476569892487168, 79228162514265744973796212736, 4951760157159816978451398656, 1237940039304520578684157952, 79228162514264619138313879552, 1237940039303394743201824768, 309485009839641012004192256, 79228162514264619141535105024, 1237940039303394746423050240, 77371252473632213681831936, 4951760157141803675158577152, 1237940039286507275391336448, 309485009822753544193703936, 4951760157141803678379802624, 1237940039286507278612561920, 77371252456744745871343616, 1237940039285381443130228736, 77371252455618910389010432, 309485009821627711932596224]
theorem e08 : enumKeys 4256 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c0499_b1, by decide, c0499_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0498_b4, by decide, c0498_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0500_b0, by decide, c0500_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0499_b9, by decide, c0499_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0499_b8, by decide, c0499_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0499_b6, by decide, c0499_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0499_b5, by decide, c0499_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0499_b7, by decide, c0499_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0498_b9, by decide, c0498_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c0498_b8, by decide, c0498_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0499_b0, by decide, c0499_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0499_b3, by decide, c0499_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0499_b2, by decide, c0499_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0499_b4, by decide, c0499_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0498_b6, by decide, c0498_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0498_b5, by decide, c0498_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0498_b7, by decide, c0498_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0498_b1, by decide, c0498_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c0498_b3, by decide, c0498_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c0498_b2, by decide, c0498_ok2⟩, ?_⟩
  simp

def s09 : List Nat := [309485009821908024046911488, 4951760157142084054918627328, 309485009822752448977043456, 1237940039286787655151386624, 77371252455899225724551168, 4951760157142084058139852800, 77371252456743650654683136, 1237940039286787658372612096, 1237940039285661819669053440, 309485009821908088471420928, 1237940039285661822890278912, 77371252455899290149060608, 309485009821908091692646400]
theorem e09 : enumKeys 4256 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0501_b3, by decide, c0501_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0501_b2, by decide, c0501_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0501_b1, by decide, c0501_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0501_b0, by decide, c0501_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0500_b7, by decide, c0500_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0500_b6, by decide, c0500_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0500_b5, by decide, c0500_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c0500_b4, by decide, c0500_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c0500_b8, by decide, c0500_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0500_b9, by decide, c0500_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0500_b1, by decide, c0500_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0500_b3, by decide, c0500_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0500_b2, by decide, c0500_ok2⟩, ?_⟩
  simp

def s10 : List Nat := [79228162514266589395505119232, 4951760157160661400160305152, 79228162514265463563244011520, 4951760157159535567899197440, 77371252474476635390738432, 79228162514264337730982903808, 77371252473350803129630720, 4951760157142648100088709120, 77371252457589167580250112, 4951760157141522267827601408, 77371252456463335319142400]
theorem e10 : enumKeys 4256 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0502_b4, by decide, c0502_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0502_b3, by decide, c0502_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0502_b1, by decide, c0502_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0502_b0, by decide, c0502_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0502_b2, by decide, c0502_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0501_b6, by decide, c0501_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0501_b7, by decide, c0501_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0501_b8, by decide, c0501_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c0501_b9, by decide, c0501_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c0501_b4, by decide, c0501_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0501_b5, by decide, c0501_ok5⟩, ?_⟩
  simp

def s11 : List Nat := [309485009822752445755817984, 4951760157142928476627533824, 309485009823596870685949952, 1237940039287632076860293120, 77371252456743647433457664, 4951760157142928479848759296, 77371252457588072363589632, 1237940039287632080081518592, 4951760157141802644366426112, 1237940039286506244599185408, 77371252456743711857967104, 309485009822752513401552896, 4951760157141802647587651584, 1237940039286506247820410880, 77371252456743715079192576, 1237940039285380412338077696, 77371252455617879596859392, 309485009821626681140445184]
theorem e11 : enumKeys 4256 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0504_b2, by decide, c0504_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0504_b1, by decide, c0504_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0504_b0, by decide, c0504_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0503_b9, by decide, c0503_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0503_b8, by decide, c0503_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0503_b7, by decide, c0503_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0503_b6, by decide, c0503_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0503_b5, by decide, c0503_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0503_b2, by decide, c0503_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c0503_b1, by decide, c0503_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0503_b4, by decide, c0503_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0503_b3, by decide, c0503_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c0502_b9, by decide, c0502_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c0502_b8, by decide, c0502_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0503_b0, by decide, c0503_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c0502_b5, by decide, c0502_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c0502_b7, by decide, c0502_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0502_b6, by decide, c0502_ok6⟩, ?_⟩
  simp

def s12 : List Nat := [77371252457588069142364160, 4951760157143772901557665792, 4951760157142647069296558080, 77371252457588136788099072, 4951760157141521237035450368, 77371252456462304526991360]
theorem e12 : enumKeys 4256 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0504_b8, by decide, c0504_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0504_b7, by decide, c0504_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0504_b5, by decide, c0504_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0504_b6, by decide, c0504_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c0504_b3, by decide, c0504_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c0504_b4, by decide, c0504_ok4⟩, ?_⟩
  simp

def s13 : List Nat := [79228162514286855591949238272, 19807040628602113195673387008, 19342813149863138692169728, 79228162514282352267199774720, 36029072165306368, 19342813136353164443779072, 79228162514268842292951384064, 19807040628584099896675532800, 22519097916915712, 79228162514264338967933485056, 19342813131849839694315520, 19807040628566086597409243136, 19342813118339865445924864]
theorem e13 : enumKeys 4256 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c0505_b6, by decide, c0505_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0505_b5, by decide, c0505_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c0505_b2, by decide, c0505_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c0506_b0, by decide, c0506_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0506_b1, by decide, c0506_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c0504_b9, by decide, c0504_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c0505_b8, by decide, c0505_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0505_b7, by decide, c0505_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0505_b9, by decide, c0505_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0505_b3, by decide, c0505_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 109, c0505_b4, by decide, c0505_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0505_b0, by decide, c0505_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0505_b1, by decide, c0505_ok1⟩, ?_⟩
  simp

def s14 : List Nat := [19807040628571713902483603456, 4951760157150528303414640640, 19807040628570588067001270272, 309485009830352336967434240, 19807040628570588071027802112, 19342813122841339064483840, 19807040628567210573439172608, 4951760157146024974370209792, 309485009826974843405336576, 19807040628567210577465704448, 4951760157146024978396741632, 19342813119463845502386176, 19807040628566084741983371264, 19342813118338010020052992, 309485009825849011949535232, 4951760157141521649352310784, 19342813114960516457955328, 309485009822471518387437568]
theorem e14 : enumKeys 4256 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c0507_b9, by decide, c0507_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0507_b8, by decide, c0507_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0507_b6, by decide, c0507_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0507_b7, by decide, c0507_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0507_b1, by decide, c0507_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c0507_b2, by decide, c0507_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0507_b4, by decide, c0507_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0507_b3, by decide, c0507_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c0507_b5, by decide, c0507_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0506_b9, by decide, c0506_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0506_b8, by decide, c0506_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0507_b0, by decide, c0507_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0506_b5, by decide, c0506_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0506_b7, by decide, c0506_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0506_b6, by decide, c0506_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0506_b2, by decide, c0506_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0506_b4, by decide, c0506_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0506_b3, by decide, c0506_ok3⟩, ?_⟩
  simp

def s15 : List Nat := [309485009843863067130068992, 19342813136352069227118592, 79228162514269122672711434240, 19807040628584380276435582976, 1237940039307898277599379456, 79228162514264619343667003392, 1237940039303394948554948608, 309485009839641217357316096, 79228162514264619347693535232, 1237940039303394952581480448, 19342813132130219454365696, 19807040628566366973142761472, 1237940039289884974306557952, 309485009826131243108925440, 19807040628566366977169293312, 1237940039289884978333089792, 19342813118620245205975040, 1237940039285381649288658944, 19342813114116916161544192, 309485009821627918091026432]
theorem e15 : enumKeys 4256 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0509_b0, by decide, c0509_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c0508_b3, by decide, c0508_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 98, c0509_b9, by decide, c0509_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c0509_b8, by decide, c0509_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0509_b7, by decide, c0509_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0509_b5, by decide, c0509_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0509_b4, by decide, c0509_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c0509_b6, by decide, c0509_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 111, c0508_b8, by decide, c0508_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0508_b7, by decide, c0508_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 101, c0508_b9, by decide, c0508_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0509_b2, by decide, c0509_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0509_b1, by decide, c0509_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0509_b3, by decide, c0509_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0508_b5, by decide, c0508_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0508_b4, by decide, c0508_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 103, c0508_b6, by decide, c0508_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0508_b0, by decide, c0508_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0508_b2, by decide, c0508_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c0508_b1, by decide, c0508_ok1⟩, ?_⟩
  simp

def s16 : List Nat := [309485009821908023241605120, 19807040628566647352902811648, 309485009826130147892264960, 1237940039290165354066608128, 19342813114397025338654720, 19807040628566647356929343488, 19342813118619149989314560, 1237940039290165358093139968, 1237940039285662025022177280, 309485009821908293824544768, 1237940039285662029048709120, 19342813114397295921594368, 309485009821908297851076608]
theorem e16 : enumKeys 4256 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 115, c0511_b2, by decide, c0511_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0511_b1, by decide, c0511_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0511_b0, by decide, c0511_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0510_b9, by decide, c0510_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c0510_b6, by decide, c0510_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0510_b5, by decide, c0510_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0510_b4, by decide, c0510_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0510_b3, by decide, c0510_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c0510_b7, by decide, c0510_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0510_b8, by decide, c0510_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0510_b0, by decide, c0510_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c0510_b2, by decide, c0510_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c0510_b1, by decide, c0510_ok1⟩, ?_⟩
  simp

def s17 : List Nat := [79228162514269967094420340736, 19807040628585224698144489472, 4951760157164039099075526656, 79228162514268841262159233024, 19807040628584098865883381760, 77371252477854334305959936, 79228162514268841262964539392, 19807040628584098866688688128, 19342813136352134725369856, 79228162514265463768597135360, 4951760157159535773252321280, 77371252474476840743862272, 79228162514265463769402441728, 4951760157159535774057627648, 19342813132974641163272192, 79228162514264337937141334016, 19342813131848808902164480, 77371252473351009288060928, 19807040628567211398072893440, 4951760157146025799003930624, 77371252460966866495471616, 19807040628567211398878199808, 4951760157146025799809236992, 19342813119464666914881536, 19807040628566085566617092096, 19342813118338834653773824, 77371252459841035039670272, 4951760157141522473986031616, 19342813114961341091676160, 77371252456463541477572608]
theorem e17 : enumKeys 4256 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c0514_b2, by decide, c0514_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c0514_b1, by decide, c0514_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0514_b0, by decide, c0514_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0513_b8, by decide, c0513_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0513_b7, by decide, c0513_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0513_b9, by decide, c0513_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0512_b9, by decide, c0512_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0512_b8, by decide, c0512_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0513_b0, by decide, c0513_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0513_b5, by decide, c0513_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0513_b4, by decide, c0513_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0513_b6, by decide, c0513_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0512_b6, by decide, c0512_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0512_b5, by decide, c0512_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0512_b7, by decide, c0512_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c0511_b9, by decide, c0511_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c0512_b1, by decide, c0512_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0512_b0, by decide, c0512_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0513_b2, by decide, c0513_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c0513_b1, by decide, c0513_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0513_b3, by decide, c0513_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0512_b3, by decide, c0512_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0512_b2, by decide, c0512_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0512_b4, by decide, c0512_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0511_b6, by decide, c0511_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0511_b8, by decide, c0511_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0511_b7, by decide, c0511_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0511_b3, by decide, c0511_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0511_b5, by decide, c0511_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0511_b4, by decide, c0511_ok4⟩, ?_⟩
  simp

def s18 : List Nat := [77371252491365064468594688, 19342813149862864888004608, 79228162514282633468372320256, 1237940039321409073260265472, 79228162514264620168300724224, 1237940039303395773188669440, 77371252473633240447451136, 79228162514264620169106030592, 1237940039303395773993975808, 19342813132131040866861056, 1237940039285382473922379776, 19342813114117740795265024, 77371252455619941181161472]
theorem e18 : enumKeys 4256 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0515_b0, by decide, c0515_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0514_b6, by decide, c0514_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c0515_b5, by decide, c0515_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0515_b4, by decide, c0515_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0515_b2, by decide, c0515_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c0515_b1, by decide, c0515_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c0515_b3, by decide, c0515_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 119, c0514_b8, by decide, c0514_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0514_b7, by decide, c0514_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 109, c0514_b9, by decide, c0514_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0514_b3, by decide, c0514_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0514_b5, by decide, c0514_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0514_b4, by decide, c0514_ok4⟩, ?_⟩
  simp

def s19 : List Nat := [309485009822752444950511616, 19807040628567491774611718144, 309485009826130144671039488, 4951760157146306175542755328, 309485009826974569601171456, 1237940039291009775775514624, 77371252456743646628151296, 19807040628567491777832943616, 77371252460121346348679168, 4951760157146306178763980800, 77371252460965771278811136, 1237940039291009778996740096, 19342813115241447047561216, 19807040628567491778638249984, 19342813118619146768089088, 4951760157146306179569287168, 19342813119463571698221056, 1237940039291009779802046464, 19807040628566365942350610432, 1237940039289883943514406912, 77371252460121410773188608, 309485009826130212316774400, 19807040628566365943155916800, 1237940039289883944319713280, 19342813118619211192598528, 309485009826130213122080768, 19807040628566365946377142272, 1237940039289883947540938752, 19342813118619214413824000, 77371252460121414799720448, 4951760157141802849719549952, 1237940039286506449952309248, 77371252456743917211090944, 309485009822752718754676736, 4951760157141802850524856320, 1237940039286506450757615616, 19342813115241717630500864, 309485009822752719559983104, 4951760157141802853746081792, 1237940039286506453978841088, 19342813115241720851726336, 77371252456743921237622784, 1237940039285380618496507904, 19342813114115885369393152, 77371252455618085755289600, 309485009821626887298875392]
theorem e19 : enumKeys 4256 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0520_b1, by decide, c0520_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0520_b0, by decide, c0520_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0519_b9, by decide, c0519_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0519_b8, by decide, c0519_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0519_b7, by decide, c0519_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0519_b6, by decide, c0519_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0519_b5, by decide, c0519_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0519_b4, by decide, c0519_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0519_b3, by decide, c0519_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0519_b2, by decide, c0519_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0519_b1, by decide, c0519_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0519_b0, by decide, c0519_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0518_b1, by decide, c0518_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0518_b0, by decide, c0518_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0517_b9, by decide, c0517_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0517_b8, by decide, c0517_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0517_b7, by decide, c0517_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0517_b6, by decide, c0517_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0518_b7, by decide, c0518_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0518_b6, by decide, c0518_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0518_b9, by decide, c0518_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0518_b8, by decide, c0518_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0517_b3, by decide, c0517_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c0517_b2, by decide, c0517_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0517_b5, by decide, c0517_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0517_b4, by decide, c0517_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0516_b5, by decide, c0516_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c0516_b4, by decide, c0516_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c0516_b7, by decide, c0516_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0516_b6, by decide, c0516_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0518_b3, by decide, c0518_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c0518_b2, by decide, c0518_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0518_b5, by decide, c0518_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0518_b4, by decide, c0518_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0516_b9, by decide, c0516_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0516_b8, by decide, c0516_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0517_b1, by decide, c0517_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0517_b0, by decide, c0517_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0516_b1, by decide, c0516_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c0516_b0, by decide, c0516_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0516_b3, by decide, c0516_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0516_b2, by decide, c0516_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0515_b6, by decide, c0515_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0515_b9, by decide, c0515_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0515_b8, by decide, c0515_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c0515_b7, by decide, c0515_ok7⟩, ?_⟩
  simp

def s20 : List Nat := [309485009821908020020379648, 79228162514264900544839548928, 309485009839640943553150976, 1237940039303676149727494144, 77371252455899221698019328, 79228162514264900548060774400, 77371252473632145230790656, 1237940039303676152948719616, 19342813114397022117429248, 79228162514264900548866080768, 19342813132129945650200576, 1237940039303676153754025984, 1237940039285662849655898112, 77371252455900316914679808, 309485009821909118458265600, 1237940039285662850461204480, 19342813114398117334089728, 309485009821909119263571968, 1237940039285662853682429952, 19342813114398120555315200, 77371252455900320941211648]
theorem e20 : enumKeys 4256 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0522_b2, by decide, c0522_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0522_b1, by decide, c0522_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0522_b0, by decide, c0522_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0521_b9, by decide, c0521_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0521_b8, by decide, c0521_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0521_b7, by decide, c0521_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0521_b6, by decide, c0521_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0521_b5, by decide, c0521_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c0521_b1, by decide, c0521_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0521_b0, by decide, c0521_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0520_b9, by decide, c0520_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0520_b8, by decide, c0520_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c0521_b2, by decide, c0521_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0521_b4, by decide, c0521_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0521_b3, by decide, c0521_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0520_b5, by decide, c0520_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0520_b7, by decide, c0520_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0520_b6, by decide, c0520_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0520_b2, by decide, c0520_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c0520_b4, by decide, c0520_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0520_b3, by decide, c0520_ok3⟩, ?_⟩
  simp

def s21 : List Nat := [309485009821908020020379648, 1237940039285943226194722816, 77371252455899221698019328, 309485009821908023241605120, 1237940039285943229415948288, 19342813114397022117429248, 309485009821908024046911488, 1237940039285943230221254656, 19342813114397025338654720, 77371252455899225724551168, 1237940039285943233442480128]
theorem e21 : enumKeys 4256 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c0523_b3, by decide, c0523_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0523_b2, by decide, c0523_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0523_b1, by decide, c0523_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0523_b0, by decide, c0523_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c0522_b9, by decide, c0522_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c0522_b8, by decide, c0522_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0522_b7, by decide, c0522_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0522_b6, by decide, c0522_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0522_b5, by decide, c0522_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0522_b4, by decide, c0522_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c0522_b3, by decide, c0522_ok3⟩, ?_⟩
  simp

def s22 : List Nat := [77371252457588068337057792, 19807040628568336199541850112, 77371252460965768057585664, 4951760157147150600472887296, 19342813116085868756467712, 19807040628568336200347156480, 19342813119463568476995584, 4951760157147150601278193664, 19807040628567210367280742400, 4951760157146024768211779584, 77371252460965835703320576, 19807040628567210368086048768, 4951760157146024769017085952, 19342813119463636122730496, 77371252460965836508626944, 19807040628566084535824941056, 19342813118337803861622784, 77371252459840004247519232, 4951760157142647274649681920, 77371252457588342141222912, 4951760157142647275454988288, 19342813116086142560632832, 77371252457588342946529280, 4951760157141521443193880576, 19342813114960310299525120, 77371252456462510685421568]
theorem e22 : enumKeys 4256 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c0525_b9, by decide, c0525_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0525_b8, by decide, c0525_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0525_b7, by decide, c0525_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0525_b6, by decide, c0525_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0525_b0, by decide, c0525_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0524_b9, by decide, c0524_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0524_b8, by decide, c0524_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0524_b7, by decide, c0524_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c0525_b4, by decide, c0525_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0525_b3, by decide, c0525_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0525_b5, by decide, c0525_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0524_b4, by decide, c0524_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c0524_b3, by decide, c0524_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0524_b6, by decide, c0524_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0524_b5, by decide, c0524_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c0523_b7, by decide, c0523_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c0523_b9, by decide, c0523_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c0523_b8, by decide, c0523_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c0525_b1, by decide, c0525_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0525_b2, by decide, c0525_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c0524_b0, by decide, c0524_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0524_b2, by decide, c0524_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0524_b1, by decide, c0524_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c0523_b4, by decide, c0523_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c0523_b6, by decide, c0523_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c0523_b5, by decide, c0523_ok5⟩, ?_⟩
  simp

def s23 : List Nat := [77371252456743643406925824, 79228162514265744969769680896, 77371252473632142009565184, 4951760157159816974424866816, 77371252474476566939697152, 1237940039304520574657626112, 19342813115241443826335744, 79228162514265744970574987264, 19342813132129942428975104, 4951760157159816975230173184, 19342813132974367359107072, 1237940039304520575462932480, 79228162514264619137508573184, 1237940039303394742396518400, 77371252473632209655300096, 79228162514264619138313879552, 1237940039303394743201824768, 19342813132130010074710016, 77371252473632210460606464, 4951760157141803674353270784, 1237940039286507274586030080, 77371252456744741844811776, 4951760157141803675158577152, 1237940039286507275391336448, 19342813115242542264221696, 77371252456744742650118144, 1237940039285381443130228736, 19342813114116710003113984, 77371252455618910389010432]
theorem e23 : enumKeys 4256 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0528_b8, by decide, c0528_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0528_b7, by decide, c0528_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0528_b6, by decide, c0528_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c0528_b5, by decide, c0528_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0528_b4, by decide, c0528_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c0528_b3, by decide, c0528_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0527_b6, by decide, c0527_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0527_b5, by decide, c0527_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0527_b4, by decide, c0527_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0527_b3, by decide, c0527_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0527_b2, by decide, c0527_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0527_b1, by decide, c0527_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0528_b1, by decide, c0528_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0528_b0, by decide, c0528_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0528_b2, by decide, c0528_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0526_b8, by decide, c0526_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0526_b7, by decide, c0526_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0527_b0, by decide, c0527_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0526_b9, by decide, c0526_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0527_b8, by decide, c0527_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c0527_b7, by decide, c0527_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0527_b9, by decide, c0527_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0526_b4, by decide, c0526_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c0526_b3, by decide, c0526_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0526_b6, by decide, c0526_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c0526_b5, by decide, c0526_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c0526_b0, by decide, c0526_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0526_b2, by decide, c0526_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0526_b1, by decide, c0526_ok1⟩, ?_⟩
  simp

def s24 : List Nat := [77371252455899218476793856, 309485009821908020020379648, 4951760157142084050892095488, 77371252456743643406925824, 309485009822752444950511616, 1237940039286787651124854784, 19342813114397018896203776, 309485009821908020825686016, 4951760157142084051697401856, 19342813115241443826335744, 309485009822752445755817984, 1237940039286787651930161152, 77371252455899221698019328, 4951760157142084054113320960, 77371252456743646628151296, 1237940039286787654346080256, 19342813114397022117429248, 77371252455899222503325696, 4951760157142084054918627328, 19342813115241447047561216, 77371252456743647433457664, 1237940039286787655151386624, 1237940039285661818863747072, 77371252455899286122528768, 309485009821908087666114560, 1237940039285661819669053440, 19342813114397086541938688, 77371252455899286927835136, 309485009821908088471420928, 1237940039285661822890278912, 19342813114397089763164160, 77371252455899290149060608]
theorem e24 : enumKeys 4256 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0532_b0, by decide, c0532_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0531_b9, by decide, c0531_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0531_b8, by decide, c0531_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0531_b7, by decide, c0531_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0531_b6, by decide, c0531_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0531_b5, by decide, c0531_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0530_b7, by decide, c0530_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0530_b6, by decide, c0530_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0530_b5, by decide, c0530_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0530_b4, by decide, c0530_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0530_b3, by decide, c0530_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0530_b2, by decide, c0530_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0531_b4, by decide, c0531_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0531_b3, by decide, c0531_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0531_b2, by decide, c0531_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c0531_b1, by decide, c0531_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0530_b1, by decide, c0530_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0530_b0, by decide, c0530_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0529_b9, by decide, c0529_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0529_b8, by decide, c0529_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0529_b7, by decide, c0529_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0529_b6, by decide, c0529_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c0530_b8, by decide, c0530_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c0531_b0, by decide, c0531_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0530_b9, by decide, c0530_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c0529_b2, by decide, c0529_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0529_b5, by decide, c0529_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0529_b4, by decide, c0529_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0529_b3, by decide, c0529_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c0528_b9, by decide, c0528_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0529_b1, by decide, c0529_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0529_b0, by decide, c0529_ok0⟩, ?_⟩
  simp

def s25 : List Nat := [77371252456743643406925824, 4951760157142928475822227456, 77371252457588068337057792, 1237940039287632076054986752, 19342813115241443826335744, 77371252456743644212232192, 4951760157142928476627533824, 19342813116085868756467712, 77371252457588069142364160, 1237940039287632076860293120, 4951760157141802643561119744, 1237940039286506243793879040, 77371252456743711052660736, 4951760157141802644366426112, 1237940039286506244599185408, 19342813115241511472070656, 77371252456743711857967104, 1237940039285380412338077696, 19342813114115679210962944, 77371252455617879596859392]
theorem e25 : enumKeys 4256 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0534_b0, by decide, c0534_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0533_b9, by decide, c0533_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0533_b8, by decide, c0533_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0533_b7, by decide, c0533_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0533_b3, by decide, c0533_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0533_b2, by decide, c0533_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0533_b1, by decide, c0533_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0533_b0, by decide, c0533_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0532_b9, by decide, c0532_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0532_b8, by decide, c0532_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0533_b5, by decide, c0533_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c0533_b4, by decide, c0533_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0533_b6, by decide, c0533_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0532_b5, by decide, c0532_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c0532_b4, by decide, c0532_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c0532_b7, by decide, c0532_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0532_b6, by decide, c0532_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c0532_b1, by decide, c0532_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c0532_b3, by decide, c0532_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c0532_b2, by decide, c0532_ok2⟩, ?_⟩
  simp

def s26 : List Nat := [79228162514273344793335562240, 19807040628588602397059710976, 79228162514268841468317663232, 19807040628584099072041811968, 19342813136352340078493696, 79228162514264338143299764224, 19342813131849015060594688, 19807040628570589097793421312, 19342813122842365830103040, 19807040628566085772775522304, 19342813118339040812204032]
theorem e26 : enumKeys 4256 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c0535_b1, by decide, c0535_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0535_b0, by decide, c0535_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0534_b8, by decide, c0534_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0534_b7, by decide, c0534_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c0534_b9, by decide, c0534_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0534_b3, by decide, c0534_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0534_b4, by decide, c0534_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0534_b5, by decide, c0534_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c0534_b6, by decide, c0534_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0534_b1, by decide, c0534_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0534_b2, by decide, c0534_ok2⟩, ?_⟩
  simp

def s27 : List Nat := [309485009826130143865733120, 19807040628570869473526939648, 309485009830352268516392960, 1237940039294387474690736128, 19342813118619145962782720, 19807040628570869477553471488, 19342813122841270613442560, 1237940039294387478717267968, 19807040628566366148509040640, 1237940039289884149672837120, 19342813118619416545722368, 309485009826130418475204608, 19807040628566366152535572480, 1237940039289884153699368960, 19342813118619420572254208, 1237940039285380824654938112, 19342813114116091527823360, 309485009821627093457305600]
theorem e27 : enumKeys 4256 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0536_b9, by decide, c0536_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c0536_b8, by decide, c0536_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0536_b7, by decide, c0536_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c0536_b6, by decide, c0536_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 125, c0536_b5, by decide, c0536_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c0536_b4, by decide, c0536_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c0536_b3, by decide, c0536_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0536_b2, by decide, c0536_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0535_b9, by decide, c0535_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0535_b8, by decide, c0535_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c0536_b1, by decide, c0536_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c0536_b0, by decide, c0536_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0535_b6, by decide, c0535_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0535_b5, by decide, c0535_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c0535_b7, by decide, c0535_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0535_b2, by decide, c0535_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0535_b4, by decide, c0535_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0535_b3, by decide, c0535_ok3⟩, ?_⟩
  simp

def s28 : List Nat := [77371252460965767252279296, 19807040628571713898457071616, 77371252464343466972807168, 4951760157150528299388108800, 19342813119463567671689216, 19807040628571713899262377984, 19342813122841267392217088, 4951760157150528300193415168, 19807040628570588067001270272, 19342813122841335037952000, 77371252464343535423848448, 19807040628570588067806576640, 19342813122841335843258368, 19807040628567210573439172608, 4951760157146024974370209792, 19342813119463841475854336, 77371252460966041861750784, 19807040628567210574244478976, 4951760157146024975175516160, 19342813119463842281160704, 19807040628566084741983371264, 19342813118338010020052992, 77371252459840210405949440, 4951760157141521649352310784, 19342813114960516457955328, 77371252456462716843851776]
theorem e28 : enumKeys 4256 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0539_b5, by decide, c0539_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0539_b4, by decide, c0539_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c0539_b3, by decide, c0539_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0539_b2, by decide, c0539_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c0539_b1, by decide, c0539_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0539_b0, by decide, c0539_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0538_b9, by decide, c0538_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0538_b8, by decide, c0538_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c0538_b5, by decide, c0538_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0538_b7, by decide, c0538_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c0538_b6, by decide, c0538_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c0537_b9, by decide, c0537_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0538_b0, by decide, c0538_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0538_b2, by decide, c0538_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c0538_b1, by decide, c0538_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0538_b4, by decide, c0538_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c0538_b3, by decide, c0538_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0537_b7, by decide, c0537_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0537_b6, by decide, c0537_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0537_b8, by decide, c0537_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c0537_b3, by decide, c0537_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c0537_b5, by decide, c0537_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c0537_b4, by decide, c0537_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c0537_b0, by decide, c0537_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0537_b2, by decide, c0537_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0537_b1, by decide, c0537_ok1⟩, ?_⟩
  simp

def s29 : List Nat := [77371252460121342322147328, 79228162514269122668684902400, 77371252473632141204258816, 19807040628584380272409051136, 77371252477854265854918656, 1237940039307898273572847616, 19342813118619142741557248, 79228162514269122669490208768, 19342813132129941623668736, 19807040628584380273214357504, 19342813136352066274328576, 1237940039307898274378153984, 79228162514264619343667003392, 1237940039303394948554948608, 19342813132130215427833856, 77371252473632415813730304, 79228162514264619344472309760, 1237940039303394949360254976, 19342813132130216233140224, 19807040628566366973142761472, 1237940039289884974306557952, 19342813118620241179443200, 77371252460122441565339648, 19807040628566366973948067840, 1237940039289884975111864320, 19342813118620241984749568, 1237940039285381649288658944, 19342813114116916161544192, 77371252455619116547440640]
theorem e29 : enumKeys 4256 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0542_b4, by decide, c0542_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0542_b3, by decide, c0542_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0542_b2, by decide, c0542_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0542_b1, by decide, c0542_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0542_b0, by decide, c0542_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0541_b9, by decide, c0541_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0541_b8, by decide, c0541_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c0541_b7, by decide, c0541_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0541_b6, by decide, c0541_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c0541_b5, by decide, c0541_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0541_b4, by decide, c0541_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0541_b3, by decide, c0541_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0541_b0, by decide, c0541_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c0540_b9, by decide, c0540_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0541_b2, by decide, c0541_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0541_b1, by decide, c0541_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c0540_b3, by decide, c0540_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0540_b2, by decide, c0540_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0540_b4, by decide, c0540_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0540_b6, by decide, c0540_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c0540_b5, by decide, c0540_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c0540_b8, by decide, c0540_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0540_b7, by decide, c0540_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0540_b0, by decide, c0540_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0539_b9, by decide, c0539_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c0540_b1, by decide, c0540_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0539_b6, by decide, c0539_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0539_b8, by decide, c0539_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c0539_b7, by decide, c0539_ok7⟩, ?_⟩
  simp

def s30 : List Nat := [77371252455899217671487488, 309485009821908019215073280, 19807040628566647348876279808, 77371252460121342322147328, 309485009826130143865733120, 1237940039290165350040076288, 19342813114397018090897408, 309485009821908020020379648, 19807040628566647349681586176, 19342813118619142741557248, 309485009826130144671039488, 1237940039290165350845382656, 19342813114397021312122880, 77371252455899221698019328, 19807040628566647352902811648, 19342813118619145962782720, 77371252460121346348679168, 1237940039290165354066608128, 19342813114397022117429248, 19807040628566647353708118016, 19342813118619146768089088, 1237940039290165354871914496, 1237940039285662025022177280, 19342813114397291895062528, 77371252455899492280958976, 309485009821908293824544768, 1237940039285662025827483648, 19342813114397292700368896, 309485009821908294629851136, 1237940039285662029048709120, 19342813114397295921594368, 77371252455899496307490816]
theorem e30 : enumKeys 4256 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0545_b6, by decide, c0545_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0545_b5, by decide, c0545_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0545_b4, by decide, c0545_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0545_b3, by decide, c0545_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0545_b2, by decide, c0545_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0545_b1, by decide, c0545_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c0545_b0, by decide, c0545_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0544_b9, by decide, c0544_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0544_b8, by decide, c0544_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0544_b7, by decide, c0544_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0544_b6, by decide, c0544_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0544_b5, by decide, c0544_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0544_b4, by decide, c0544_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0544_b3, by decide, c0544_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0544_b2, by decide, c0544_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c0544_b1, by decide, c0544_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0544_b0, by decide, c0544_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0543_b9, by decide, c0543_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0543_b4, by decide, c0543_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0543_b3, by decide, c0543_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0543_b2, by decide, c0543_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0543_b1, by decide, c0543_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c0543_b5, by decide, c0543_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0543_b8, by decide, c0543_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0543_b7, by decide, c0543_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0543_b6, by decide, c0543_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0542_b8, by decide, c0542_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0543_b0, by decide, c0543_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0542_b9, by decide, c0542_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c0542_b5, by decide, c0542_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0542_b7, by decide, c0542_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c0542_b6, by decide, c0542_ok6⟩, ?_⟩
  simp

def s31 : List Nat := [77371252456743642601619456, 19807040628567491773806411776, 77371252460121342322147328, 4951760157146306174737448960, 77371252460965767252279296, 1237940039291009774970208256, 19342813115241443021029376, 77371252456743643406925824, 19807040628567491774611718144, 19342813118619142741557248, 77371252460121343127453696, 4951760157146306175542755328, 19342813119463567671689216, 77371252460965768057585664, 1237940039291009775775514624, 19342813115241443826335744, 19807040628567491775417024512, 19342813118619143546863616, 4951760157146306176348061696, 19342813119463568476995584, 1237940039291009776580820992, 19807040628566365942350610432, 1237940039289883943514406912, 19342813118619210387292160, 77371252460121410773188608, 19807040628566365943155916800, 1237940039289883944319713280, 19342813118619211192598528, 77371252460121411578494976, 4951760157141802849719549952, 1237940039286506449952309248, 19342813115241716825194496, 77371252456743917211090944, 4951760157141802850524856320, 1237940039286506450757615616, 19342813115241717630500864, 77371252456743918016397312, 1237940039285380618496507904, 19342813114115885369393152, 77371252455618085755289600]
theorem e31 : enumKeys 4256 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0549_b6, by decide, c0549_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0549_b5, by decide, c0549_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0549_b4, by decide, c0549_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0549_b3, by decide, c0549_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0549_b2, by decide, c0549_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0549_b1, by decide, c0549_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0549_b0, by decide, c0549_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c0548_b9, by decide, c0548_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0548_b8, by decide, c0548_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0548_b7, by decide, c0548_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0548_b6, by decide, c0548_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0548_b5, by decide, c0548_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0548_b4, by decide, c0548_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0548_b3, by decide, c0548_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c0548_b2, by decide, c0548_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0547_b3, by decide, c0547_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0547_b2, by decide, c0547_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0547_b1, by decide, c0547_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0547_b0, by decide, c0547_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0546_b9, by decide, c0546_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0546_b8, by decide, c0546_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c0547_b9, by decide, c0547_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c0547_b8, by decide, c0547_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0548_b1, by decide, c0548_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0548_b0, by decide, c0548_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0546_b5, by decide, c0546_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c0546_b4, by decide, c0546_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0546_b7, by decide, c0546_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0546_b6, by decide, c0546_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c0547_b5, by decide, c0547_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c0547_b4, by decide, c0547_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0547_b7, by decide, c0547_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0547_b6, by decide, c0547_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c0546_b1, by decide, c0546_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0546_b0, by decide, c0546_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0546_b3, by decide, c0546_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0546_b2, by decide, c0546_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c0545_b7, by decide, c0545_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c0545_b9, by decide, c0545_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c0545_b8, by decide, c0545_ok8⟩, ?_⟩
  simp

def s32 : List Nat := [77371252455899217671487488, 79228162514264900544034242560, 77371252473632141204258816, 1237940039303676148922187776, 19342813114397018090897408, 77371252455899218476793856, 79228162514264900544839548928, 19342813132129941623668736, 77371252473632142009565184, 1237940039303676149727494144, 19342813114397018896203776, 79228162514264900545644855296, 19342813132129942428975104, 1237940039303676150532800512, 1237940039285662849655898112, 19342813114398116528783360, 77371252455900316914679808, 1237940039285662850461204480, 19342813114398117334089728, 77371252455900317719986176]
theorem e32 : enumKeys 4256 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0551_b6, by decide, c0551_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0551_b5, by decide, c0551_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0551_b4, by decide, c0551_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0551_b3, by decide, c0551_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0551_b2, by decide, c0551_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0551_b1, by decide, c0551_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0551_b0, by decide, c0551_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0550_b9, by decide, c0550_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0550_b8, by decide, c0550_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c0550_b7, by decide, c0550_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0550_b3, by decide, c0550_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0550_b2, by decide, c0550_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c0550_b1, by decide, c0550_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0550_b0, by decide, c0550_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c0550_b4, by decide, c0550_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0550_b6, by decide, c0550_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0550_b5, by decide, c0550_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c0549_b7, by decide, c0549_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0549_b9, by decide, c0549_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c0549_b8, by decide, c0549_ok8⟩, ?_⟩
  simp

def s33 : List Nat := [77371252455899217671487488, 309485009821908019215073280, 1237940039285943225389416448, 19342813114397018090897408, 77371252455899218476793856, 309485009821908020020379648, 1237940039285943226194722816, 19342813114397018896203776, 309485009821908020825686016, 1237940039285943227000029184, 19342813114397021312122880, 77371252455899221698019328, 1237940039285943229415948288, 19342813114397022117429248, 77371252455899222503325696, 1237940039285943230221254656]
theorem e33 : enumKeys 4256 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c0553_b2, by decide, c0553_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0553_b1, by decide, c0553_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0553_b0, by decide, c0553_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0552_b9, by decide, c0552_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0552_b8, by decide, c0552_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0552_b7, by decide, c0552_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0552_b6, by decide, c0552_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0552_b2, by decide, c0552_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0552_b1, by decide, c0552_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0552_b0, by decide, c0552_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0552_b5, by decide, c0552_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0552_b4, by decide, c0552_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c0552_b3, by decide, c0552_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0551_b9, by decide, c0551_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0551_b8, by decide, c0551_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c0551_b7, by decide, c0551_ok7⟩, ?_⟩
  simp

def s34 : List Nat := [77371252455899217671487488, 4951760157142084050086789120, 77371252456743642601619456, 1237940039286787650319548416, 19342813114397018090897408, 77371252455899218476793856, 4951760157142084050892095488, 19342813115241443021029376, 77371252456743643406925824, 1237940039286787651124854784, 19342813114397018896203776, 77371252455899219282100224, 4951760157142084051697401856, 19342813115241443826335744, 77371252456743644212232192, 1237940039286787651930161152, 1237940039285661818863747072, 19342813114397085736632320, 77371252455899286122528768, 1237940039285661819669053440, 19342813114397086541938688, 77371252455899286927835136]
theorem e34 : enumKeys 4256 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0555_b4, by decide, c0555_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0555_b3, by decide, c0555_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0555_b2, by decide, c0555_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0555_b1, by decide, c0555_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c0555_b0, by decide, c0555_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0554_b9, by decide, c0554_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0554_b8, by decide, c0554_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c0554_b7, by decide, c0554_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0554_b6, by decide, c0554_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0554_b5, by decide, c0554_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0554_b1, by decide, c0554_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0554_b0, by decide, c0554_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0553_b9, by decide, c0553_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0553_b8, by decide, c0553_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0553_b7, by decide, c0553_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0553_b6, by decide, c0553_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c0554_b2, by decide, c0554_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0554_b4, by decide, c0554_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0554_b3, by decide, c0554_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c0553_b3, by decide, c0553_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c0553_b5, by decide, c0553_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0553_b4, by decide, c0553_ok4⟩, ?_⟩
  simp

def s35 : List Nat := [19342813122841266586910720, 19807040628575091598177599488, 19807040628570588273159700480, 19342813122841541196382208, 19807040628566084948141801472, 19342813118338216178483200]
theorem e35 : enumKeys 4256 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0556_b0, by decide, c0556_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0555_b9, by decide, c0555_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0555_b7, by decide, c0555_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0555_b8, by decide, c0555_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0555_b5, by decide, c0555_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0555_b6, by decide, c0555_ok6⟩, ?_⟩
  simp

def s36 : List Nat := [19342813118619141936250880, 77371252460121342322147328, 19807040628570869473526939648, 19342813122841266586910720, 77371252464343466972807168, 1237940039294387474690736128, 19342813118619142741557248, 19807040628570869474332246016, 19342813122841267392217088, 1237940039294387475496042496, 19807040628566366148509040640, 1237940039289884149672837120, 19342813118619416545722368, 77371252460121616931618816, 19807040628566366149314347008, 1237940039289884150478143488, 19342813118619417351028736, 1237940039285380824654938112, 19342813114116091527823360, 77371252455618291913719808]
theorem e36 : enumKeys 4256 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0558_b0, by decide, c0558_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0557_b9, by decide, c0557_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0557_b8, by decide, c0557_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0557_b7, by decide, c0557_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c0557_b6, by decide, c0557_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0557_b5, by decide, c0557_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c0557_b4, by decide, c0557_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0557_b3, by decide, c0557_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0557_b2, by decide, c0557_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0557_b1, by decide, c0557_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0556_b8, by decide, c0556_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0556_b7, by decide, c0556_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c0557_b0, by decide, c0557_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c0556_b9, by decide, c0556_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0556_b5, by decide, c0556_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0556_b4, by decide, c0556_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0556_b6, by decide, c0556_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c0556_b1, by decide, c0556_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0556_b3, by decide, c0556_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0556_b2, by decide, c0556_ok2⟩, ?_⟩
  simp

def s37 : List Nat := [19342813114397017285591040, 77371252455899217671487488, 19807040628566647348876279808, 19342813118619141936250880, 77371252460121342322147328, 1237940039290165350040076288, 19342813114397018090897408, 77371252455899218476793856, 19807040628566647349681586176, 19342813118619142741557248, 77371252460121343127453696, 1237940039290165350845382656, 19342813114397018896203776, 19807040628566647350486892544, 19342813118619143546863616, 1237940039290165351650689024, 1237940039285662025022177280, 19342813114397291895062528, 77371252455899492280958976, 1237940039285662025827483648, 19342813114397292700368896, 77371252455899493086265344]
theorem e37 : enumKeys 4256 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0560_b2, by decide, c0560_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0560_b1, by decide, c0560_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0560_b0, by decide, c0560_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0559_b9, by decide, c0559_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0559_b8, by decide, c0559_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0559_b7, by decide, c0559_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c0559_b6, by decide, c0559_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c0559_b5, by decide, c0559_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0559_b4, by decide, c0559_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0559_b3, by decide, c0559_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c0559_b2, by decide, c0559_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c0559_b1, by decide, c0559_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0558_b7, by decide, c0558_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0558_b6, by decide, c0558_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0558_b5, by decide, c0558_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0558_b4, by decide, c0558_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c0558_b8, by decide, c0558_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0559_b0, by decide, c0559_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0558_b9, by decide, c0558_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0558_b1, by decide, c0558_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c0558_b3, by decide, c0558_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0558_b2, by decide, c0558_ok2⟩, ?_⟩
  simp

def s38 : List Nat := [19342813114397017285591040, 77371252455899217671487488, 1237940039285943225389416448, 19342813114397018090897408, 77371252455899218476793856, 1237940039285943226194722816, 19342813114397018896203776, 77371252455899219282100224, 1237940039285943227000029184]
theorem e38 : enumKeys 4256 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0561_b1, by decide, c0561_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c0561_b0, by decide, c0561_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0560_b9, by decide, c0560_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c0560_b8, by decide, c0560_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0560_b7, by decide, c0560_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0560_b6, by decide, c0560_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c0560_b5, by decide, c0560_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0560_b4, by decide, c0560_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0560_b3, by decide, c0560_ok3⟩, ?_⟩
  simp

/-- every enumerated key with left type `4256` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 4256 mR,
    (4256 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4256 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K04
end Grid3.Three.Cert
