import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C0561
import Grid3.Three.Cert.Data.C0562
import Grid3.Three.Cert.Data.C0563
import Grid3.Three.Cert.Data.C0564
import Grid3.Three.Cert.Data.C0565
import Grid3.Three.Cert.Data.C0566
import Grid3.Three.Cert.Data.C0567
import Grid3.Three.Cert.Data.C0568
import Grid3.Three.Cert.Data.C0569
import Grid3.Three.Cert.Data.C0570
import Grid3.Three.Cert.Data.C0571
import Grid3.Three.Cert.Data.C0572
import Grid3.Three.Cert.Data.C0573
import Grid3.Three.Cert.Data.C0574
import Grid3.Three.Cert.Data.C0575
import Grid3.Three.Cert.Data.C0576
import Grid3.Three.Cert.Data.C0577
import Grid3.Three.Cert.Data.C0578
import Grid3.Three.Cert.Data.C0579
import Grid3.Three.Cert.Data.C0580
import Grid3.Three.Cert.Data.C0581
import Grid3.Three.Cert.Data.C0582
import Grid3.Three.Cert.Data.C0583

/-! Seam keys with left type `240` (type index 5): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K05

def s00 : List Nat := [54043195528445952, 36029896530591744, 18016597532737536, 3298534883328]
theorem e00 : enumKeys 240 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c0561_b2, by decide, c0561_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c0561_b3, by decide, c0561_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c0561_b4, by decide, c0561_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 108, c0561_b5, by decide, c0561_ok5⟩, ?_⟩
  simp

def s01 : List Nat := [23643902338662400, 22518071151296512, 19140577589198848, 18014746401832960, 5630603340808192, 4504772153442304, 1127278591344640, 1443109011456]
theorem e01 : enumKeys 240 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c0561_b7, by decide, c0561_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0562_b1, by decide, c0562_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0561_b9, by decide, c0561_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0562_b3, by decide, c0562_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0561_b8, by decide, c0561_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0562_b2, by decide, c0562_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0562_b0, by decide, c0562_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0561_b6, by decide, c0561_ok6⟩, ?_⟩
  simp

def s02 : List Nat := [36310276290641920, 18296977292787712, 283678294933504]
theorem e02 : enumKeys 240 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c0562_b4, by decide, c0562_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 117, c0562_b5, by decide, c0562_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c0562_b6, by decide, c0562_ok6⟩, ?_⟩
  simp

def s03 : List Nat := [5910983100858368, 4785151913492480, 1407658351394816, 281822869061632]
theorem e03 : enumKeys 240 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c0562_b8, by decide, c0562_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0563_b0, by decide, c0563_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0562_b9, by decide, c0562_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0562_b7, by decide, c0562_ok7⟩, ?_⟩
  simp

def s04 : List Nat := [18577357052837888, 564058054983680]
theorem e04 : enumKeys 240 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c0563_b1, by decide, c0563_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c0563_b2, by decide, c0563_ok2⟩, ?_⟩
  simp

def s05 : List Nat := [844437815033856]
theorem e05 : enumKeys 240 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c0563_b3, by decide, c0563_ok3⟩, ?_⟩
  simp

def s06 : List Nat := [37154697999548416, 36028866812182528, 19141399001694208, 18015567814328320, 1128100003840000, 2267742732288]
theorem e06 : enumKeys 240 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0563_b5, by decide, c0563_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0563_b8, by decide, c0563_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0563_b6, by decide, c0563_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c0563_b9, by decide, c0563_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0563_b7, by decide, c0563_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0563_b4, by decide, c0563_ok4⟩, ?_⟩
  simp

def s07 : List Nat := [6755404809764864, 5629573622398976, 4503738140065792, 4503741361291264, 2252080060301312, 1126244577968128, 1126247799193600, 412316860416]
theorem e07 : enumKeys 240 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0564_b5, by decide, c0564_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c0564_b7, by decide, c0564_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0564_b4, by decide, c0564_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0564_b2, by decide, c0564_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0564_b6, by decide, c0564_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c0564_b3, by decide, c0564_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0564_b1, by decide, c0564_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c0564_b0, by decide, c0564_ok0⟩, ?_⟩
  simp

def s08 : List Nat := [19421778761744384, 18295947574378496, 1408479763890176, 282644281556992, 282647502782464]
theorem e08 : enumKeys 240 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0565_b0, by decide, c0565_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0565_b2, by decide, c0565_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0565_b1, by decide, c0565_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c0564_b9, by decide, c0564_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0564_b8, by decide, c0564_ok8⟩, ?_⟩
  simp

def s09 : List Nat := [1688859523940352, 563024041607168, 563027262832640]
theorem e09 : enumKeys 240 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0565_b5, by decide, c0565_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c0565_b4, by decide, c0565_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0565_b3, by decide, c0565_ok3⟩, ?_⟩
  simp

def s10 : List Nat := [20266200470650880, 19140369283284992, 18014537022177280, 2252901472796672, 1127069211688960, 1236950581248]
theorem e10 : enumKeys 240 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0565_b9, by decide, c0565_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0566_b1, by decide, c0566_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c0565_b8, by decide, c0565_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0566_b0, by decide, c0566_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c0565_b7, by decide, c0565_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c0565_b6, by decide, c0565_ok6⟩, ?_⟩
  simp

def s11 : List Nat := [2533281232846848, 1407445750513664, 1407448971739136, 281613489405952, 281616710631424]
theorem e11 : enumKeys 240 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0566_b6, by decide, c0566_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0566_b5, by decide, c0566_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c0566_b4, by decide, c0566_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c0566_b3, by decide, c0566_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c0566_b2, by decide, c0566_ok2⟩, ?_⟩
  simp

def s12 : List Nat := [3377702941753344, 2251870680645632, 1126038419537920, 206158430208]
theorem e12 : enumKeys 240 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0567_b0, by decide, c0567_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c0566_b9, by decide, c0566_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c0566_b8, by decide, c0566_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c0566_b7, by decide, c0566_ok7⟩, ?_⟩
  simp

def s13 : List Nat := [40532396914769920, 36029072165306368, 22519097916915712, 18015773167452160, 4505798919061504, 2473901162496]
theorem e13 : enumKeys 240 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0567_b2, by decide, c0567_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0567_b5, by decide, c0567_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0567_b3, by decide, c0567_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c0567_b6, by decide, c0567_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0567_b4, by decide, c0567_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0567_b1, by decide, c0567_ok1⟩, ?_⟩
  simp

def s14 : List Nat := [10133103724986368, 9007272537620480, 5629778975522816, 4503943493189632, 4503947519721472, 1126449931091968, 1126453957623808, 618475290624]
theorem e14 : enumKeys 240 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0568_b2, by decide, c0568_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c0568_b4, by decide, c0568_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0568_b3, by decide, c0568_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0568_b1, by decide, c0568_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0567_b9, by decide, c0567_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0568_b0, by decide, c0568_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0567_b8, by decide, c0567_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c0567_b7, by decide, c0567_ok7⟩, ?_⟩
  simp

def s15 : List Nat := [22799477676965888, 18296152927502336, 4786178679111680, 282849634680832, 282853661212672]
theorem e15 : enumKeys 240 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c0568_b7, by decide, c0568_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c0568_b9, by decide, c0568_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c0568_b8, by decide, c0568_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c0568_b6, by decide, c0568_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c0568_b5, by decide, c0568_ok5⟩, ?_⟩
  simp

def s16 : List Nat := [5066558439161856, 563229394731008, 563233421262848]
theorem e16 : enumKeys 240 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c0569_b2, by decide, c0569_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c0569_b1, by decide, c0569_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0569_b0, by decide, c0569_ok0⟩, ?_⟩
  simp

def s17 : List Nat := [23643899385872384, 22518068198506496, 19140574636408832, 18014742375301120, 18014743180607488, 5630600388018176, 4504768126910464, 4504768932216832, 1127274564812800, 1127275370119168, 1443109011456]
theorem e17 : enumKeys 240 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0570_b0, by decide, c0570_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0570_b3, by decide, c0570_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c0570_b2, by decide, c0570_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c0569_b9, by decide, c0569_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c0569_b6, by decide, c0569_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0570_b1, by decide, c0570_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c0569_b8, by decide, c0569_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c0569_b5, by decide, c0569_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c0569_b7, by decide, c0569_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0569_b4, by decide, c0569_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0569_b3, by decide, c0569_ok3⟩, ?_⟩
  simp

def s18 : List Nat := [36310273337851904, 18296974339997696, 283674268401664, 283675073708032]
theorem e18 : enumKeys 240 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c0570_b6, by decide, c0570_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c0570_b7, by decide, c0570_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c0570_b5, by decide, c0570_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0570_b4, by decide, c0570_ok4⟩, ?_⟩
  simp

def s19 : List Nat := [5910980148068352, 4785144665735168, 4785147886960640, 4785148692267008, 1407651103637504, 1407654324862976, 1407655130169344, 281818842529792, 281819647836160, 281822869061632]
theorem e19 : enumKeys 240 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0571_b7, by decide, c0571_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0571_b6, by decide, c0571_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0571_b4, by decide, c0571_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c0571_b1, by decide, c0571_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c0571_b5, by decide, c0571_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0571_b3, by decide, c0571_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0571_b0, by decide, c0571_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c0571_b2, by decide, c0571_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c0570_b9, by decide, c0570_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c0570_b8, by decide, c0570_ok8⟩, ?_⟩
  simp

def s20 : List Nat := [18577354100047872, 564050807226368, 564054028451840, 564054833758208]
theorem e20 : enumKeys 240 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c0572_b1, by decide, c0572_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c0572_b0, by decide, c0572_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0571_b9, by decide, c0571_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c0571_b8, by decide, c0571_ok8⟩, ?_⟩
  simp

def s21 : List Nat := [844430567276544, 844433788502016, 844434593808384]
theorem e21 : enumKeys 240 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0572_b4, by decide, c0572_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0572_b3, by decide, c0572_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0572_b2, by decide, c0572_ok2⟩, ?_⟩
  simp

def s22 : List Nat := [6755401856974848, 5629569595867136, 5629570401173504, 4503737334759424, 4503738140065792, 2252076033769472, 2252076839075840, 1126243772661760, 1126244577968128, 412316860416]
theorem e22 : enumKeys 240 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0573_b4, by decide, c0573_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c0573_b3, by decide, c0573_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c0572_b9, by decide, c0572_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c0573_b1, by decide, c0573_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c0572_b7, by decide, c0572_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c0573_b2, by decide, c0573_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0572_b8, by decide, c0572_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c0573_b0, by decide, c0573_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c0572_b6, by decide, c0572_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c0572_b5, by decide, c0572_ok5⟩, ?_⟩
  simp

def s23 : List Nat := [19421775808954368, 18295943547846656, 18295944353153024, 1408475737358336, 1408476542664704, 282643476250624, 282644281556992]
theorem e23 : enumKeys 240 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0574_b1, by decide, c0574_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0574_b0, by decide, c0574_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0573_b7, by decide, c0573_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0573_b9, by decide, c0573_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0573_b6, by decide, c0573_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c0573_b8, by decide, c0573_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c0573_b5, by decide, c0573_ok5⟩, ?_⟩
  simp

def s24 : List Nat := [1688852276183040, 1688855497408512, 1688856302714880, 563020015075328, 563020820381696, 563023236300800, 563024041607168]
theorem e24 : enumKeys 240 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0574_b8, by decide, c0574_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0574_b7, by decide, c0574_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0574_b4, by decide, c0574_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0574_b6, by decide, c0574_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c0574_b3, by decide, c0574_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c0574_b5, by decide, c0574_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c0574_b2, by decide, c0574_ok2⟩, ?_⟩
  simp

def s25 : List Nat := [2533277206315008, 2533278011621376, 1407444945207296, 1407445750513664, 281612684099584, 281613489405952]
theorem e25 : enumKeys 240 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0575_b4, by decide, c0575_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0575_b1, by decide, c0575_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c0575_b3, by decide, c0575_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c0575_b0, by decide, c0575_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c0575_b2, by decide, c0575_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c0574_b9, by decide, c0574_ok9⟩, ?_⟩
  simp

def s26 : List Nat := [27021598301093888, 22518273551630336, 18014948533731328, 9008299303239680, 4504974285340672, 1649267441664]
theorem e26 : enumKeys 240 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0575_b8, by decide, c0575_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c0576_b0, by decide, c0576_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c0575_b7, by decide, c0575_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0575_b9, by decide, c0575_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c0575_b6, by decide, c0575_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0575_b5, by decide, c0575_ok5⟩, ?_⟩
  simp

def s27 : List Nat := [9288679063289856, 4785350018859008, 4785354045390848, 282025000960000, 282029027491840]
theorem e27 : enumKeys 240 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c0576_b5, by decide, c0576_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c0576_b4, by decide, c0576_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c0576_b3, by decide, c0576_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c0576_b2, by decide, c0576_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c0576_b1, by decide, c0576_ok1⟩, ?_⟩
  simp

def s28 : List Nat := [10133100772196352, 9007268511088640, 9007269316395008, 5629774948990976, 5629775754297344, 4503943493189632, 4503944298496000, 1126449931091968, 1126450736398336, 618475290624]
theorem e28 : enumKeys 240 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0577_b5, by decide, c0577_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c0577_b4, by decide, c0577_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c0577_b2, by decide, c0577_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0577_b3, by decide, c0577_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c0577_b1, by decide, c0577_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c0577_b0, by decide, c0577_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c0576_b8, by decide, c0576_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c0576_b9, by decide, c0576_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0576_b7, by decide, c0576_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c0576_b6, by decide, c0576_ok6⟩, ?_⟩
  simp

def s29 : List Nat := [22799474724175872, 18296148900970496, 18296149706276864, 4786174652579840, 4786175457886208, 282849634680832, 282850439987200]
theorem e29 : enumKeys 240 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c0578_b2, by decide, c0578_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c0578_b1, by decide, c0578_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c0577_b9, by decide, c0577_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0578_b0, by decide, c0578_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0577_b8, by decide, c0577_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c0577_b7, by decide, c0577_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c0577_b6, by decide, c0577_ok6⟩, ?_⟩
  simp

def s30 : List Nat := [5066551191404544, 5066554412630016, 5066555217936384, 563225368199168, 563226173505536, 563229394731008, 563230200037376]
theorem e30 : enumKeys 240 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c0578_b9, by decide, c0578_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c0578_b8, by decide, c0578_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c0578_b6, by decide, c0578_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c0578_b7, by decide, c0578_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c0578_b5, by decide, c0578_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c0578_b4, by decide, c0578_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c0578_b3, by decide, c0578_ok3⟩, ?_⟩
  simp

def s31 : List Nat := [5910976121536512, 5910976926842880, 4785143860428800, 4785144665735168, 4785145471041536, 1407650298331136, 1407651103637504, 1407651908943872, 281818842529792, 281819647836160]
theorem e31 : enumKeys 240 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0579_b9, by decide, c0579_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0579_b6, by decide, c0579_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0579_b8, by decide, c0579_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c0579_b5, by decide, c0579_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c0579_b2, by decide, c0579_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0579_b7, by decide, c0579_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c0579_b4, by decide, c0579_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0579_b1, by decide, c0579_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c0579_b3, by decide, c0579_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c0579_b0, by decide, c0579_ok0⟩, ?_⟩
  simp

def s32 : List Nat := [18577350073516032, 18577350878822400, 564050001920000, 564050807226368, 564051612532736]
theorem e32 : enumKeys 240 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c0580_b4, by decide, c0580_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0580_b2, by decide, c0580_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0580_b3, by decide, c0580_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0580_b1, by decide, c0580_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0580_b0, by decide, c0580_ok0⟩, ?_⟩
  simp

def s33 : List Nat := [844426540744704, 844427346051072, 844429761970176, 844430567276544, 844431372582912]
theorem e33 : enumKeys 240 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0580_b9, by decide, c0580_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0580_b7, by decide, c0580_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0580_b8, by decide, c0580_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c0580_b6, by decide, c0580_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0580_b5, by decide, c0580_ok5⟩, ?_⟩
  simp

def s34 : List Nat := [1688851470876672, 1688852276183040, 1688853081489408, 563019209768960, 563020015075328, 563020820381696]
theorem e34 : enumKeys 240 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0581_b5, by decide, c0581_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0581_b3, by decide, c0581_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0581_b1, by decide, c0581_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c0581_b4, by decide, c0581_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c0581_b2, by decide, c0581_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c0581_b0, by decide, c0581_ok0⟩, ?_⟩
  simp

def s35 : List Nat := [13510799687417856, 9007474669518848, 4504149651619840, 824633720832]
theorem e35 : enumKeys 240 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c0581_b9, by decide, c0581_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c0581_b8, by decide, c0581_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c0581_b7, by decide, c0581_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0581_b6, by decide, c0581_ok6⟩, ?_⟩
  simp

def s36 : List Nat := [9288675036758016, 9288675842064384, 4785350018859008, 4785350824165376, 282025000960000, 282025806266368]
theorem e36 : enumKeys 240 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c0582_b5, by decide, c0582_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c0582_b4, by decide, c0582_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c0582_b3, by decide, c0582_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c0582_b2, by decide, c0582_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c0582_b1, by decide, c0582_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0582_b0, by decide, c0582_ok0⟩, ?_⟩
  simp

def s37 : List Nat := [5066550386098176, 5066551191404544, 5066551996710912, 563225368199168, 563226173505536, 563226978811904]
theorem e37 : enumKeys 240 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c0583_b1, by decide, c0583_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c0583_b0, by decide, c0583_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c0582_b8, by decide, c0582_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c0582_b9, by decide, c0582_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c0582_b7, by decide, c0582_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0582_b6, by decide, c0582_ok6⟩, ?_⟩
  simp

def s38 : List Nat := [844425735438336, 844426540744704, 844427346051072, 844428151357440]
theorem e38 : enumKeys 240 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0583_b5, by decide, c0583_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0583_b4, by decide, c0583_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c0583_b3, by decide, c0583_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c0583_b2, by decide, c0583_ok2⟩, ?_⟩
  simp

/-- every enumerated key with left type `240` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 240 mR,
    (240 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K05
end Grid3.Three.Cert
