import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0109
import Grid3.Three.Cert.Data.C0110
import Grid3.Three.Cert.Data.C0111
import Grid3.Three.Cert.Data.C0112
import Grid3.Three.Cert.Data.C0113
import Grid3.Three.Cert.Data.C0114

/-! Seam keys with left type `240` (type index 5): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K05

theorem tL : rtype 240 = 3075 := by decide

def s00 : List Nat := [54043195528445952, 36029896530591744, 18016597532737536, 3298534883328]
theorem e00 : enumKeys 240 12288 = s00 := by decide +kernel
theorem t00 : rtype 12288 = 12288 := by decide
theorem r00 : ∀ M ∈ s00, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 12288 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 12288) (rM M) ne blob = true) := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0109_b9, by decide, c0109_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 132, c0109_b8, by decide, c0109_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 118, c0109_b7, by decide, c0109_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 108, c0109_b6, by decide, c0109_ok6⟩, ?_⟩
  simp

def s01 : List Nat := [23643902338662400, 22518071151296512, 19140577589198848, 18014746401832960, 5630603340808192, 4504772153442304, 1127278591344640, 1443109011456]
theorem e01 : enumKeys 240 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 152, c0109_b17, by decide, c0109_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 159, c0109_b16, by decide, c0109_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0109_b15, by decide, c0109_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 154, c0109_b14, by decide, c0109_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 147, c0109_b13, by decide, c0109_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0109_b12, by decide, c0109_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 141, c0109_b11, by decide, c0109_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0109_b10, by decide, c0109_ok10⟩, ?_⟩
  simp

def s02 : List Nat := [36310276290641920, 18296977292787712, 283678294933504]
theorem e02 : enumKeys 240 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 128, c0109_b20, by decide, c0109_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 117, c0109_b19, by decide, c0109_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 108, c0109_b18, by decide, c0109_ok18⟩, ?_⟩
  simp

def s03 : List Nat := [5910983100858368, 4785151913492480, 1407658351394816, 281822869061632]
theorem e03 : enumKeys 240 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 140, c0109_b24, by decide, c0109_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0109_b23, by decide, c0109_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 138, c0109_b22, by decide, c0109_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0109_b21, by decide, c0109_ok21⟩, ?_⟩
  simp

def s04 : List Nat := [18577357052837888, 564058054983680]
theorem e04 : enumKeys 240 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 116, c0109_b26, by decide, c0109_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 108, c0109_b25, by decide, c0109_ok25⟩, ?_⟩
  simp

def s05 : List Nat := [844437815033856]
theorem e05 : enumKeys 240 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 108, c0109_b27, by decide, c0109_ok27⟩, ?_⟩
  simp

def s06 : List Nat := [37154697999548416, 36028866812182528, 19141399001694208, 18015567814328320, 1128100003840000, 2267742732288]
theorem e06 : enumKeys 240 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0109_b33, by decide, c0109_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0109_b32, by decide, c0109_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 159, c0109_b31, by decide, c0109_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 163, c0109_b30, by decide, c0109_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0109_b29, by decide, c0109_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0109_b28, by decide, c0109_ok28⟩, ?_⟩
  simp

def s07 : List Nat := [6755404809764864, 5629573622398976, 4503738140065792, 4503741361291264, 2252080060301312, 1126244577968128, 1126247799193600, 412316860416]
theorem e07 : enumKeys 240 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0110_b1, by decide, c0110_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0110_b0, by decide, c0110_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0109_b38, by decide, c0109_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0109_b39, by decide, c0109_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0109_b37, by decide, c0109_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0109_b35, by decide, c0109_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0109_b36, by decide, c0109_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0109_b34, by decide, c0109_ok34⟩, ?_⟩
  simp

def s08 : List Nat := [19421778761744384, 18295947574378496, 1408479763890176, 282644281556992, 282647502782464]
theorem e08 : enumKeys 240 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 154, c0110_b6, by decide, c0110_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 159, c0110_b5, by decide, c0110_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 147, c0110_b4, by decide, c0110_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 179, c0110_b2, by decide, c0110_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0110_b3, by decide, c0110_ok3⟩, ?_⟩
  simp

def s09 : List Nat := [1688859523940352, 563024041607168, 563027262832640]
theorem e09 : enumKeys 240 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0110_b9, by decide, c0110_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 175, c0110_b7, by decide, c0110_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0110_b8, by decide, c0110_ok8⟩, ?_⟩
  simp

def s10 : List Nat := [20266200470650880, 19140369283284992, 18014537022177280, 2252901472796672, 1127069211688960, 1236950581248]
theorem e10 : enumKeys 240 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0110_b15, by decide, c0110_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0110_b14, by decide, c0110_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0110_b13, by decide, c0110_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0110_b12, by decide, c0110_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0110_b11, by decide, c0110_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0110_b10, by decide, c0110_ok10⟩, ?_⟩
  simp

def s11 : List Nat := [2533281232846848, 1407445750513664, 1407448971739136, 281613489405952, 281616710631424]
theorem e11 : enumKeys 240 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0110_b20, by decide, c0110_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0110_b18, by decide, c0110_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0110_b19, by decide, c0110_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0110_b16, by decide, c0110_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0110_b17, by decide, c0110_ok17⟩, ?_⟩
  simp

def s12 : List Nat := [3377702941753344, 2251870680645632, 1126038419537920, 206158430208]
theorem e12 : enumKeys 240 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0110_b24, by decide, c0110_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0110_b23, by decide, c0110_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 304, c0110_b22, by decide, c0110_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0110_b21, by decide, c0110_ok21⟩, ?_⟩
  simp

def s13 : List Nat := [40532396914769920, 36029072165306368, 22519097916915712, 18015773167452160, 4505798919061504, 2473901162496]
theorem e13 : enumKeys 240 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0110_b30, by decide, c0110_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0110_b29, by decide, c0110_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 138, c0110_b28, by decide, c0110_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 133, c0110_b27, by decide, c0110_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 132, c0110_b26, by decide, c0110_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0110_b25, by decide, c0110_ok25⟩, ?_⟩
  simp

def s14 : List Nat := [10133103724986368, 9007272537620480, 5629778975522816, 4503943493189632, 4503947519721472, 1126449931091968, 1126453957623808, 618475290624]
theorem e14 : enumKeys 240 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 154, c0110_b38, by decide, c0110_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 162, c0110_b37, by decide, c0110_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 159, c0110_b36, by decide, c0110_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0110_b34, by decide, c0110_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0110_b35, by decide, c0110_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0110_b32, by decide, c0110_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0110_b33, by decide, c0110_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0110_b31, by decide, c0110_ok31⟩, ?_⟩
  simp

def s15 : List Nat := [22799477676965888, 18296152927502336, 4786178679111680, 282849634680832, 282853661212672]
theorem e15 : enumKeys 240 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 130, c0111_b3, by decide, c0111_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 129, c0111_b2, by decide, c0111_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 126, c0111_b1, by decide, c0111_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 149, c0110_b39, by decide, c0110_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 141, c0111_b0, by decide, c0111_ok0⟩, ?_⟩
  simp

def s16 : List Nat := [5066558439161856, 563229394731008, 563233421262848]
theorem e16 : enumKeys 240 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 120, c0111_b6, by decide, c0111_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 145, c0111_b4, by decide, c0111_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 138, c0111_b5, by decide, c0111_ok5⟩, ?_⟩
  simp

def s17 : List Nat := [23643899385872384, 22518068198506496, 19140574636408832, 18014742375301120, 18014743180607488, 5630600388018176, 4504768126910464, 4504768932216832, 1127274564812800, 1127275370119168, 1443109011456]
theorem e17 : enumKeys 240 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0111_b17, by decide, c0111_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0111_b16, by decide, c0111_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 171, c0111_b15, by decide, c0111_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0111_b13, by decide, c0111_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0111_b14, by decide, c0111_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0111_b12, by decide, c0111_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0111_b10, by decide, c0111_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0111_b11, by decide, c0111_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0111_b8, by decide, c0111_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0111_b9, by decide, c0111_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0111_b7, by decide, c0111_ok7⟩, ?_⟩
  simp

def s18 : List Nat := [36310273337851904, 18296974339997696, 283674268401664, 283675073708032]
theorem e18 : enumKeys 240 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 146, c0111_b21, by decide, c0111_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 138, c0111_b20, by decide, c0111_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 156, c0111_b18, by decide, c0111_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0111_b19, by decide, c0111_ok19⟩, ?_⟩
  simp

def s19 : List Nat := [5910980148068352, 4785144665735168, 4785147886960640, 4785148692267008, 1407651103637504, 1407654324862976, 1407655130169344, 281818842529792, 281819647836160, 281822869061632]
theorem e19 : enumKeys 240 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 158, c0111_b31, by decide, c0111_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0111_b28, by decide, c0111_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0111_b29, by decide, c0111_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0111_b30, by decide, c0111_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 191, c0111_b25, by decide, c0111_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0111_b26, by decide, c0111_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0111_b27, by decide, c0111_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0111_b22, by decide, c0111_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0111_b23, by decide, c0111_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0111_b24, by decide, c0111_ok24⟩, ?_⟩
  simp

def s20 : List Nat := [18577354100047872, 564050807226368, 564054028451840, 564054833758208]
theorem e20 : enumKeys 240 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 134, c0111_b35, by decide, c0111_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 154, c0111_b32, by decide, c0111_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0111_b33, by decide, c0111_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 147, c0111_b34, by decide, c0111_ok34⟩, ?_⟩
  simp

def s21 : List Nat := [844430567276544, 844433788502016, 844434593808384]
theorem e21 : enumKeys 240 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0111_b36, by decide, c0111_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0111_b37, by decide, c0111_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0111_b38, by decide, c0111_ok38⟩, ?_⟩
  simp

def s22 : List Nat := [6755401856974848, 5629569595867136, 5629570401173504, 4503737334759424, 4503738140065792, 2252076033769472, 2252076839075840, 1126243772661760, 1126244577968128, 412316860416]
theorem e22 : enumKeys 240 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0112_b8, by decide, c0112_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0112_b6, by decide, c0112_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0112_b7, by decide, c0112_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0112_b4, by decide, c0112_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 276, c0112_b5, by decide, c0112_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0112_b2, by decide, c0112_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0112_b3, by decide, c0112_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 274, c0112_b0, by decide, c0112_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0112_b1, by decide, c0112_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 312, c0111_b39, by decide, c0111_ok39⟩, ?_⟩
  simp

def s23 : List Nat := [19421775808954368, 18295943547846656, 18295944353153024, 1408475737358336, 1408476542664704, 282643476250624, 282644281556992]
theorem e23 : enumKeys 240 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0112_b15, by decide, c0112_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0112_b13, by decide, c0112_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0112_b14, by decide, c0112_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0112_b11, by decide, c0112_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0112_b12, by decide, c0112_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0112_b9, by decide, c0112_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0112_b10, by decide, c0112_ok10⟩, ?_⟩
  simp

def s24 : List Nat := [1688852276183040, 1688855497408512, 1688856302714880, 563020015075328, 563020820381696, 563023236300800, 563024041607168]
theorem e24 : enumKeys 240 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0112_b20, by decide, c0112_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0112_b21, by decide, c0112_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0112_b22, by decide, c0112_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0112_b16, by decide, c0112_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0112_b17, by decide, c0112_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0112_b18, by decide, c0112_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0112_b19, by decide, c0112_ok19⟩, ?_⟩
  simp

def s25 : List Nat := [2533277206315008, 2533278011621376, 1407444945207296, 1407445750513664, 281612684099584, 281613489405952]
theorem e25 : enumKeys 240 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0112_b27, by decide, c0112_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0112_b28, by decide, c0112_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0112_b25, by decide, c0112_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0112_b26, by decide, c0112_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0112_b23, by decide, c0112_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 304, c0112_b24, by decide, c0112_ok24⟩, ?_⟩
  simp

def s26 : List Nat := [27021598301093888, 22518273551630336, 18014948533731328, 9008299303239680, 4504974285340672, 1649267441664]
theorem e26 : enumKeys 240 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0112_b34, by decide, c0112_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 150, c0112_b33, by decide, c0112_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0112_b32, by decide, c0112_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0112_b31, by decide, c0112_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 169, c0112_b30, by decide, c0112_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0112_b29, by decide, c0112_ok29⟩, ?_⟩
  simp

def s27 : List Nat := [9288679063289856, 4785350018859008, 4785354045390848, 282025000960000, 282029027491840]
theorem e27 : enumKeys 240 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 132, c0112_b39, by decide, c0112_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 166, c0112_b37, by decide, c0112_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 159, c0112_b38, by decide, c0112_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0112_b35, by decide, c0112_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0112_b36, by decide, c0112_ok36⟩, ?_⟩
  simp

def s28 : List Nat := [10133100772196352, 9007268511088640, 9007269316395008, 5629774948990976, 5629775754297344, 4503943493189632, 4503944298496000, 1126449931091968, 1126450736398336, 618475290624]
theorem e28 : enumKeys 240 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0113_b9, by decide, c0113_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0113_b7, by decide, c0113_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0113_b8, by decide, c0113_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0113_b5, by decide, c0113_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0113_b6, by decide, c0113_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0113_b3, by decide, c0113_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0113_b4, by decide, c0113_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0113_b1, by decide, c0113_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0113_b2, by decide, c0113_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 276, c0113_b0, by decide, c0113_ok0⟩, ?_⟩
  simp

def s29 : List Nat := [22799474724175872, 18296148900970496, 18296149706276864, 4786174652579840, 4786175457886208, 282849634680832, 282850439987200]
theorem e29 : enumKeys 240 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 148, c0113_b16, by decide, c0113_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0113_b14, by decide, c0113_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 171, c0113_b15, by decide, c0113_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0113_b12, by decide, c0113_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0113_b13, by decide, c0113_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0113_b10, by decide, c0113_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0113_b11, by decide, c0113_ok11⟩, ?_⟩
  simp

def s30 : List Nat := [5066551191404544, 5066554412630016, 5066555217936384, 563225368199168, 563226173505536, 563229394731008, 563230200037376]
theorem e30 : enumKeys 240 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 164, c0113_b21, by decide, c0113_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 156, c0113_b22, by decide, c0113_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 158, c0113_b23, by decide, c0113_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0113_b17, by decide, c0113_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 191, c0113_b18, by decide, c0113_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0113_b19, by decide, c0113_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0113_b20, by decide, c0113_ok20⟩, ?_⟩
  simp

def s31 : List Nat := [5910976121536512, 5910976926842880, 4785143860428800, 4785144665735168, 4785145471041536, 1407650298331136, 1407651103637504, 1407651908943872, 281818842529792, 281819647836160]
theorem e31 : enumKeys 240 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0113_b32, by decide, c0113_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0113_b33, by decide, c0113_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0113_b29, by decide, c0113_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0113_b30, by decide, c0113_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0113_b31, by decide, c0113_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0113_b26, by decide, c0113_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0113_b27, by decide, c0113_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0113_b28, by decide, c0113_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 274, c0113_b24, by decide, c0113_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0113_b25, by decide, c0113_ok25⟩, ?_⟩
  simp

def s32 : List Nat := [18577350073516032, 18577350878822400, 564050001920000, 564050807226368, 564051612532736]
theorem e32 : enumKeys 240 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0113_b37, by decide, c0113_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0113_b38, by decide, c0113_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0113_b34, by decide, c0113_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0113_b35, by decide, c0113_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0113_b36, by decide, c0113_ok36⟩, ?_⟩
  simp

def s33 : List Nat := [844426540744704, 844427346051072, 844429761970176, 844430567276544, 844431372582912]
theorem e33 : enumKeys 240 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0113_b39, by decide, c0113_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0114_b0, by decide, c0114_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0114_b1, by decide, c0114_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0114_b2, by decide, c0114_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0114_b3, by decide, c0114_ok3⟩, ?_⟩
  simp

def s34 : List Nat := [1688851470876672, 1688852276183040, 1688853081489408, 563019209768960, 563020015075328, 563020820381696]
theorem e34 : enumKeys 240 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0114_b7, by decide, c0114_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0114_b8, by decide, c0114_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b9, by decide, c0114_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0114_b4, by decide, c0114_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0114_b5, by decide, c0114_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0114_b6, by decide, c0114_ok6⟩, ?_⟩
  simp

def s35 : List Nat := [13510799687417856, 9007474669518848, 4504149651619840, 824633720832]
theorem e35 : enumKeys 240 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 144, c0114_b13, by decide, c0114_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0114_b12, by decide, c0114_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0114_b11, by decide, c0114_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b10, by decide, c0114_ok10⟩, ?_⟩
  simp

def s36 : List Nat := [9288675036758016, 9288675842064384, 4785350018859008, 4785350824165376, 282025000960000, 282025806266368]
theorem e36 : enumKeys 240 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0114_b18, by decide, c0114_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0114_b19, by decide, c0114_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0114_b16, by decide, c0114_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0114_b17, by decide, c0114_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0114_b14, by decide, c0114_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b15, by decide, c0114_ok15⟩, ?_⟩
  simp

def s37 : List Nat := [5066550386098176, 5066551191404544, 5066551996710912, 563225368199168, 563226173505536, 563226978811904]
theorem e37 : enumKeys 240 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0114_b23, by decide, c0114_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0114_b24, by decide, c0114_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0114_b25, by decide, c0114_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0114_b20, by decide, c0114_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0114_b21, by decide, c0114_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b22, by decide, c0114_ok22⟩, ?_⟩
  simp

def s38 : List Nat := [844425735438336, 844426540744704, 844427346051072, 844428151357440]
theorem e38 : enumKeys 240 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b26, by decide, c0114_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0114_b27, by decide, c0114_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0114_b28, by decide, c0114_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0114_b29, by decide, c0114_ok29⟩, ?_⟩
  simp

/-- every enumerated key with left type `240` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 240 mR,
    (240 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 240 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 240) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K05
end Grid3.Three.Cert
