import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C1118
import Grid3.Three.Cert.Data.C1119
import Grid3.Three.Cert.Data.C1120
import Grid3.Three.Cert.Data.C1121
import Grid3.Three.Cert.Data.C1122
import Grid3.Three.Cert.Data.C1123
import Grid3.Three.Cert.Data.C1124
import Grid3.Three.Cert.Data.C1125
import Grid3.Three.Cert.Data.C1126
import Grid3.Three.Cert.Data.C1127
import Grid3.Three.Cert.Data.C1128
import Grid3.Three.Cert.Data.C1129
import Grid3.Three.Cert.Data.C1130
import Grid3.Three.Cert.Data.C1131
import Grid3.Three.Cert.Data.C1132
import Grid3.Three.Cert.Data.C1133
import Grid3.Three.Cert.Data.C1134
import Grid3.Three.Cert.Data.C1135
import Grid3.Three.Cert.Data.C1136
import Grid3.Three.Cert.Data.C1137
import Grid3.Three.Cert.Data.C1138
import Grid3.Three.Cert.Data.C1139
import Grid3.Three.Cert.Data.C1140
import Grid3.Three.Cert.Data.C1141
import Grid3.Three.Cert.Data.C1142
import Grid3.Three.Cert.Data.C1143
import Grid3.Three.Cert.Data.C1144
import Grid3.Three.Cert.Data.C1145
import Grid3.Three.Cert.Data.C1146
import Grid3.Three.Cert.Data.C1147
import Grid3.Three.Cert.Data.C1148
import Grid3.Three.Cert.Data.C1149
import Grid3.Three.Cert.Data.C1150
import Grid3.Three.Cert.Data.C1151
import Grid3.Three.Cert.Data.C1152
import Grid3.Three.Cert.Data.C1153
import Grid3.Three.Cert.Data.C1154
import Grid3.Three.Cert.Data.C1155
import Grid3.Three.Cert.Data.C1156
import Grid3.Three.Cert.Data.C1157
import Grid3.Three.Cert.Data.C1158
import Grid3.Three.Cert.Data.C1159
import Grid3.Three.Cert.Data.C1160
import Grid3.Three.Cert.Data.C1161
import Grid3.Three.Cert.Data.C1162
import Grid3.Three.Cert.Data.C1163
import Grid3.Three.Cert.Data.C1164
import Grid3.Three.Cert.Data.C1165
import Grid3.Three.Cert.Data.C1166
import Grid3.Three.Cert.Data.C1167
import Grid3.Three.Cert.Data.C1168
import Grid3.Three.Cert.Data.C1169
import Grid3.Three.Cert.Data.C1170
import Grid3.Three.Cert.Data.C1171
import Grid3.Three.Cert.Data.C1172
import Grid3.Three.Cert.Data.C1173
import Grid3.Three.Cert.Data.C1174
import Grid3.Three.Cert.Data.C1175
import Grid3.Three.Cert.Data.C1176
import Grid3.Three.Cert.Data.C1177
import Grid3.Three.Cert.Data.C1178
import Grid3.Three.Cert.Data.C1179
import Grid3.Three.Cert.Data.C1180
import Grid3.Three.Cert.Data.C1181
import Grid3.Three.Cert.Data.C1182
import Grid3.Three.Cert.Data.C1183
import Grid3.Three.Cert.Data.C1184
import Grid3.Three.Cert.Data.C1185
import Grid3.Three.Cert.Data.C1186
import Grid3.Three.Cert.Data.C1187
import Grid3.Three.Cert.Data.C1188
import Grid3.Three.Cert.Data.C1189

/-! Seam keys with left type `4616` (type index 10): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K10

def s00 : List Nat := [79228163104560147952249602048, 79228162809412242772963885056, 590295810358772760576, 79228162514264337593678168064, 295147905179487043584]
theorem e00 : enumKeys 4616 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 114, c1118_b3, by decide, c1118_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨3, 141, c1118_b4, by decide, c1118_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨3, 138, c1118_b5, by decide, c1118_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c1118_b6, by decide, c1118_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 156, c1118_b7, by decide, c1118_ok7⟩, ?_⟩
  simp

def s01 : List Nat := [79228162589204235392989003776, 19807040924866911082345660416, 309485378756226542915813376, 79228162606498057962091970560, 19807040942160733651448627200, 4951760526076402573787791360, 79228162533864003171877126144, 4951760453442347783572946944, 309485323415994321803935744, 79228162532711081667270541312, 4951760452289426278966362112, 313594649253079416832, 19807040648165749976769495040, 4951760232081418899108659200, 309485102055065437339648000, 19807040647012828472162910208, 4951760230928497394502074368, 92233720368615129088, 4951760158294442604287229952, 309485028268089142518218752, 19599665578400284672]
theorem e01 : enumKeys 4616 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1119_b0, by decide, c1119_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1118_b9, by decide, c1118_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1118_b8, by decide, c1118_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c1120_b2, by decide, c1120_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c1120_b1, by decide, c1120_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1120_b0, by decide, c1120_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c1119_b6, by decide, c1119_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1119_b5, by decide, c1119_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c1119_b4, by decide, c1119_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c1120_b7, by decide, c1120_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c1120_b6, by decide, c1120_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c1120_b8, by decide, c1120_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1119_b3, by decide, c1119_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c1119_b2, by decide, c1119_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1119_b1, by decide, c1119_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1120_b4, by decide, c1120_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c1120_b3, by decide, c1120_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c1120_b5, by decide, c1120_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c1119_b8, by decide, c1119_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1119_b7, by decide, c1119_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c1119_b9, by decide, c1119_ok9⟩, ?_⟩
  simp

def s02 : List Nat := [79228162810565164277503623168, 309485600117155427430432768, 79228162814023928791324426240, 1237940629581190633605038080, 79228162520028945116645294080, 1237940335586206958925905920, 309485309580936266572103680, 79228162518876023612038709248, 1237940334433285454319321088, 299759591197847584768, 1237940040438301779640188928, 309485014433031087286386688, 5764607523168452608]
theorem e02 : enumKeys 4616 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1121_b0, by decide, c1121_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1120_b9, by decide, c1120_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c1121_b8, by decide, c1121_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c1121_b7, by decide, c1121_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c1121_b3, by decide, c1121_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1121_b2, by decide, c1121_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1121_b1, by decide, c1121_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c1122_b0, by decide, c1122_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c1121_b9, by decide, c1121_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c1122_b1, by decide, c1122_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1121_b5, by decide, c1121_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1121_b4, by decide, c1121_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c1121_b6, by decide, c1121_ok6⟩, ?_⟩
  simp

def s03 : List Nat := [19807040630871927407599681536, 309485084761242868169834496, 19807040634330691921420484608, 19807040648165749976702648320, 1237940114225278074344439808, 4951760232081418899041812480, 309485088220007381990637568, 309485102055065437272801280, 19807040651624514490523451392, 4951760235540183412862615552, 1237940131519100643447406592, 1237940041591223284129595392, 4951760159447364108826968064, 309485015585952591775793152, 309485029421010647057956864, 4951760162906128622647771136, 1237940058885045853232562176, 309485032879775160878759936]
theorem e03 : enumKeys 4616 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1122_b3, by decide, c1122_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 284, c1122_b2, by decide, c1122_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1123_b3, by decide, c1123_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1123_b2, by decide, c1123_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1123_b1, by decide, c1123_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1123_b0, by decide, c1123_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1122_b9, by decide, c1122_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1122_b8, by decide, c1122_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c1123_b9, by decide, c1123_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c1123_b8, by decide, c1123_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1123_b7, by decide, c1123_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1122_b7, by decide, c1122_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1122_b6, by decide, c1122_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1122_b5, by decide, c1122_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1122_b4, by decide, c1122_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1123_b6, by decide, c1123_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1123_b5, by decide, c1123_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c1123_b4, by decide, c1123_ok4⟩, ?_⟩
  simp

def s04 : List Nat := [79228162516570180602757644288, 309485306122171752684453888, 79228162520028945116578447360, 1237940335586206958859059200, 309485309580936266505256960, 79228162523487709630399250432, 1237940339044971472679862272, 1237940041591223284179927040, 309485015585952591826124800, 1237940045049987798000730112, 309485019044717105646927872]
theorem e04 : enumKeys 4616 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1124_b1, by decide, c1124_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c1124_b0, by decide, c1124_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1124_b6, by decide, c1124_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1124_b5, by decide, c1124_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1124_b4, by decide, c1124_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c1125_b0, by decide, c1125_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c1124_b9, by decide, c1124_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1124_b3, by decide, c1124_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1124_b2, by decide, c1124_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1124_b8, by decide, c1124_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1124_b7, by decide, c1124_ok7⟩, ?_⟩
  simp

def s05 : List Nat := [309485012127188077938475008, 1237940041591223284113080320, 309485015585952591759278080, 1237940045049987797933883392, 309485019044717105580081152, 1237940048508752311754424320]
theorem e05 : enumKeys 4616 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1125_b1, by decide, c1125_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1125_b3, by decide, c1125_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c1125_b2, by decide, c1125_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1125_b6, by decide, c1125_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c1125_b5, by decide, c1125_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1125_b4, by decide, c1125_ok4⟩, ?_⟩
  simp

def s06 : List Nat := [77371842751146625886846976, 79228162827858986846606393344, 4951760747437331458302214144, 77371566049985520310681600, 79228162532711081667320676352, 4951760452289426279016497152, 313594649253129551872, 4951760157141521099730714624, 77371270902080341024964608]
theorem e06 : enumKeys 4616 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1125_b7, by decide, c1125_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 125, c1126_b2, by decide, c1126_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨2, 134, c1126_b1, by decide, c1126_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨2, 177, c1125_b8, by decide, c1125_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c1126_b4, by decide, c1126_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨2, 165, c1126_b3, by decide, c1126_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c1126_b5, by decide, c1126_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1125_b9, by decide, c1125_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1126_b0, by decide, c1126_ok0⟩, ?_⟩
  simp

def s07 : List Nat := [77371327395234066626248704, 19807040648165749976702451712, 4951760232081418899041615872, 309485102055065437272604672, 77371344689056635729215488, 19807040665459572545805418496, 4951760249375241468144582656, 77371272055001845514371072, 4951760176741186677929738240, 309485046714833216160727040, 4951760175588265173323087872, 77371289348824414617337856]
theorem e07 : enumKeys 4616 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 360, c1126_b6, by decide, c1126_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1127_b3, by decide, c1127_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1127_b2, by decide, c1127_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1127_b1, by decide, c1127_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1126_b8, by decide, c1126_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c1127_b7, by decide, c1127_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1127_b6, by decide, c1127_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1126_b7, by decide, c1126_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1127_b5, by decide, c1127_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c1127_b4, by decide, c1127_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1126_b9, by decide, c1126_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1127_b0, by decide, c1127_ok0⟩, ?_⟩
  simp

def s08 : List Nat := [77371548756162951140868096, 79228162520028945116578250752, 79228162533864003171860414464, 1237940335586206958858862592, 4951760453442347783556235264, 309485309580936266505060352, 309485323415994321787224064, 77371552214927464961671168, 77371566049985520243834880, 79228162537322767685681217536, 4951760456901112297377038336, 1237940352880029527961829376, 77371258219943790282539008, 77371272055001845564702720, 4951760162906128622697906176, 1237940058885045853282697216, 309485032879775160928894976, 4951760161753207118091255808, 1237940057732124348676046848, 77371275513766359385505792]
theorem e08 : enumKeys 4616 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c1127_b8, by decide, c1127_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1129_b1, by decide, c1129_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c1129_b0, by decide, c1129_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1128_b9, by decide, c1128_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1128_b8, by decide, c1128_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1128_b7, by decide, c1128_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1128_b6, by decide, c1128_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1128_b2, by decide, c1128_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1128_b1, by decide, c1128_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c1129_b7, by decide, c1129_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c1129_b6, by decide, c1129_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c1129_b5, by decide, c1129_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1128_b0, by decide, c1128_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1127_b9, by decide, c1127_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c1129_b4, by decide, c1129_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1129_b3, by decide, c1129_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c1129_b2, by decide, c1129_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1128_b4, by decide, c1128_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1128_b3, by decide, c1128_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1128_b5, by decide, c1128_ok5⟩, ?_⟩
  simp

def s09 : List Nat := [77371254761179276394889216, 1237940041591223284112883712, 4951760159447364108810256384, 309485015585952591759081472, 309485029421010647041245184, 77371258219943790215692288, 77371272055001845497856000, 1237940045049987797933686784, 4951760162906128622631059456, 309485019044717105579884544, 4951760166364893136451600384, 1237940058885045853215850496, 309485032879775160862048256, 1237940062343810367036391424, 77371261678708304036495360, 4951760166364893136451796992, 77371275513766359318659072, 1237940062343810367036588032]
theorem e09 : enumKeys 4616 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c1129_b8, by decide, c1129_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c1130_b8, by decide, c1130_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1130_b7, by decide, c1130_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1130_b6, by decide, c1130_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1130_b5, by decide, c1130_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1130_b0, by decide, c1130_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c1129_b9, by decide, c1129_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1131_b5, by decide, c1131_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1131_b4, by decide, c1131_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1131_b2, by decide, c1131_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1131_b1, by decide, c1131_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1131_b3, by decide, c1131_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1131_b0, by decide, c1131_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c1130_b9, by decide, c1130_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1130_b4, by decide, c1130_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1130_b3, by decide, c1130_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1130_b2, by decide, c1130_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1130_b1, by decide, c1130_ok1⟩, ?_⟩
  simp

def s10 : List Nat := [77371566049985520243638272, 79228162551157825740963184640, 4951760470736170352659005440, 4951760175588265173373222912, 77371289348824414667472896]
theorem e10 : enumKeys 4616 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1131_b6, by decide, c1131_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c1132_b0, by decide, c1132_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c1131_b9, by decide, c1131_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1131_b7, by decide, c1131_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1131_b8, by decide, c1131_ok8⟩, ?_⟩
  simp

def s11 : List Nat := [77371258219943790215495680, 77371272055001845497659392, 4951760162906128622630862848, 1237940058885045853215653888, 4951760176741186677913026560, 309485032879775160861851648, 4951760180199951191733567488, 309485046714833216144015360, 1237940076178868422318358528, 77371275513766359318462464, 4951760180199951191733764096, 77371289348824414600626176, 1237940076178868422318555136]
theorem e11 : enumKeys 4616 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1132_b2, by decide, c1132_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c1132_b1, by decide, c1132_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1133_b3, by decide, c1133_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1133_b2, by decide, c1133_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1133_b1, by decide, c1133_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1133_b0, by decide, c1133_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c1132_b9, by decide, c1132_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1132_b8, by decide, c1132_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1132_b7, by decide, c1132_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1132_b6, by decide, c1132_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1132_b5, by decide, c1132_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c1132_b4, by decide, c1132_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c1132_b3, by decide, c1132_ok3⟩, ?_⟩
  simp

def s12 : List Nat := [77371289348824414600429568, 4951760194035009247015731200]
theorem e12 : enumKeys 4616 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1133_b5, by decide, c1133_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1133_b4, by decide, c1133_ok4⟩, ?_⟩
  simp

def s13 : List Nat := [79228162883199219067734982656, 19807041218861894757091639296, 79228162809484300366951481344, 19343403409644425517727744, 79228162588123371482487193600, 19807040923786047171843850240, 19343182048715541053440000, 79228162514336395187665764352, 19343108261739246232010752, 295219962773474639872, 19807040628638141992558133248, 19342886900810361767723008, 73859033889010352128]
theorem e13 : enumKeys 4616 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1133_b7, by decide, c1133_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1133_b6, by decide, c1133_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c1134_b5, by decide, c1134_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c1134_b4, by decide, c1134_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c1134_b0, by decide, c1134_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1133_b9, by decide, c1133_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1133_b8, by decide, c1133_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c1134_b7, by decide, c1134_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c1134_b6, by decide, c1134_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c1134_b8, by decide, c1134_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1134_b2, by decide, c1134_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1134_b1, by decide, c1134_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c1134_b3, by decide, c1134_ok3⟩, ?_⟩
  simp

def s14 : List Nat := [19807040703505982197831041024, 309485157395297658401193984, 19807040702425118287262384128, 19807040720799804766934007808, 19342960687786656471973888, 4951760304715473689273171968, 19807040629791063497047539712, 19807040648165749976719163392, 309485083680378957617692672, 19342888053731866257129472, 4951760232081418899058327552, 309485102055065437289316352, 19807040647084886066150506496, 4951760231000554988489670656, 19342905347554435360096256, 4951760158366500198274826240, 309485028340146736505815040, 19342832713499645145251840]
theorem e14 : enumKeys 4616 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 284, c1135_b0, by decide, c1135_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1134_b9, by decide, c1134_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1136_b3, by decide, c1136_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1136_b2, by decide, c1136_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1136_b1, by decide, c1136_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1136_b0, by decide, c1136_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1135_b6, by decide, c1135_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1135_b4, by decide, c1135_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1135_b5, by decide, c1135_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1135_b3, by decide, c1135_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1135_b2, by decide, c1135_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1135_b1, by decide, c1135_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c1136_b6, by decide, c1136_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1136_b5, by decide, c1136_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1136_b4, by decide, c1136_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c1135_b9, by decide, c1135_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c1135_b8, by decide, c1135_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1135_b7, by decide, c1135_ok7⟩, ?_⟩
  simp

def s15 : List Nat := [79228162589204235392989003776, 19807040924866911082345660416, 309485378756226542915813376, 79228162588123371482420346880, 79228162592662999906809806848, 19807040923786047171777003520, 19807040928325675596166463488, 19343182048715540986593280, 1237940408220261749090418688, 79228162515489316692205502464, 79228162520028945116594962432, 309485305041307842132312064, 19343109414660750771748864, 1237940335586206958875574272, 309485309580936266521772032, 79228162518948081206026305536, 1237940334505343048306917376, 19343112873425264592551936, 19807040629791063497097871360, 19807040634330691921487331328, 309485083680378957668024320, 19342888053731866307461120, 1237940114225278074411286528, 309485088220007382057484288, 19807040633249828010918674432, 1237940113144414163842629632, 19342891512496380128264192, 1237940040510359373627785216, 309485014505088681273982976, 19342818878441589913419776]
theorem e15 : enumKeys 4616 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1136_b9, by decide, c1136_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1136_b8, by decide, c1136_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1136_b7, by decide, c1136_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1139_b0, by decide, c1139_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1138_b8, by decide, c1138_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1138_b9, by decide, c1138_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c1138_b7, by decide, c1138_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c1138_b6, by decide, c1138_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c1138_b5, by decide, c1138_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1138_b1, by decide, c1138_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1137_b9, by decide, c1137_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c1138_b0, by decide, c1138_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c1137_b8, by decide, c1137_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c1137_b7, by decide, c1137_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1137_b6, by decide, c1137_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c1139_b6, by decide, c1139_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c1139_b5, by decide, c1139_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c1139_b4, by decide, c1139_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1137_b5, by decide, c1137_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c1137_b3, by decide, c1137_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c1137_b4, by decide, c1137_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1137_b2, by decide, c1137_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1137_b1, by decide, c1137_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1137_b0, by decide, c1137_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1139_b3, by decide, c1139_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1139_b2, by decide, c1139_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1139_b1, by decide, c1139_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1138_b4, by decide, c1138_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c1138_b3, by decide, c1138_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1138_b2, by decide, c1138_ok2⟩, ?_⟩
  simp

def s16 : List Nat := [19807040630871927407599681536, 309485084761242868169834496, 19807040629791063497031024640, 19807040634330691921420484608, 309485083680378957601177600, 19342888053731866240614400, 1237940114225278074344439808, 309485088220007381990637568, 1237940043969123887364964352, 19807040633249828010851827712, 19342822337206103650598912, 19807040637789456435241287680, 1237940113144414163775782912, 19342891512496380061417472, 1237940117684042588165242880, 309485011046324167386333184, 19342815419677076025769984, 1237940041591223284129595392, 309485015585952591775793152, 1237940040510359373560938496, 309485014505088681207136256, 1237940043969123887381479424, 19342818878441589846573056, 1237940045049987797950398464, 19342822337206103667113984, 309485019044717105596596224]
theorem e16 : enumKeys 4616 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1139_b8, by decide, c1139_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 284, c1139_b7, by decide, c1139_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1140_b8, by decide, c1140_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1140_b6, by decide, c1140_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1140_b7, by decide, c1140_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c1140_b5, by decide, c1140_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1140_b4, by decide, c1140_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1140_b3, by decide, c1140_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1142_b2, by decide, c1142_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c1142_b1, by decide, c1142_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c1141_b9, by decide, c1141_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1141_b8, by decide, c1141_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1142_b0, by decide, c1142_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1141_b7, by decide, c1141_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1141_b6, by decide, c1141_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1140_b2, by decide, c1140_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1140_b1, by decide, c1140_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1140_b0, by decide, c1140_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1139_b9, by decide, c1139_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1141_b5, by decide, c1141_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1141_b4, by decide, c1141_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c1141_b3, by decide, c1141_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c1141_b2, by decide, c1141_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1141_b1, by decide, c1141_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c1141_b0, by decide, c1141_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1140_b9, by decide, c1140_ok9⟩, ?_⟩
  simp

def s17 : List Nat := [77371621390217741372227584, 79228162588123371482420150272, 79228162606498057962091773952, 19807040923786047171776806912, 19807040942160733651448430592, 19343182048715540986396672, 4951760526076402573787594752, 77371547675299040588726272, 77371566049985520260349952, 79228162532783139261308272640, 4951760452361483873004093440, 19343126708483319874519040, 77371326314370156124438528, 77371344689056635796062208, 19807040647084886066200641536, 4951760231000554988539805696, 19342905347554435410231296, 4951760157213578693718310912, 19342831560578140588736512, 77371270974137935012560896]
theorem e17 : enumKeys 4616 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c1142_b3, by decide, c1142_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1143_b6, by decide, c1143_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c1143_b4, by decide, c1143_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1143_b5, by decide, c1143_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1143_b3, by decide, c1143_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1143_b2, by decide, c1143_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1143_b1, by decide, c1143_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1142_b7, by decide, c1142_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1142_b6, by decide, c1142_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c1144_b2, by decide, c1144_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c1144_b1, by decide, c1144_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c1144_b0, by decide, c1144_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1142_b5, by decide, c1142_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1142_b4, by decide, c1142_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c1143_b9, by decide, c1143_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c1143_b8, by decide, c1143_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1143_b7, by decide, c1143_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1142_b9, by decide, c1142_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1142_b8, by decide, c1142_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1143_b0, by decide, c1143_ok0⟩, ?_⟩
  simp

def s18 : List Nat := [77371842751146625886846976, 79228162809484300366934769664, 79228162814023928791324229632, 19343403409644425501016064, 1237940629581190633604841472, 77371547675299040639057920, 77371552214927465028517888, 79228162518948081206076440576, 1237940334505343048357052416, 19343112873425264642686976, 1237940039357437869071269888, 19342817725520085356904448, 77371257139079879780728832]
theorem e18 : enumKeys 4616 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1144_b3, by decide, c1144_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1145_b2, by decide, c1145_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c1145_b1, by decide, c1145_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c1145_b0, by decide, c1145_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c1144_b9, by decide, c1144_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1144_b5, by decide, c1144_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1144_b4, by decide, c1144_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c1145_b5, by decide, c1145_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c1145_b4, by decide, c1145_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c1145_b3, by decide, c1145_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1144_b7, by decide, c1144_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1144_b6, by decide, c1144_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1144_b8, by decide, c1144_ok8⟩, ?_⟩
  simp

def s19 : List Nat := [77371327395234066626248704, 19807040629791063497030828032, 19807040634330691921420288000, 19807040648165749976702451712, 309485083680378957600980992, 19342888053731866240417792, 1237940114225278074344243200, 4951760232081418899041615872, 309485088220007381990440960, 309485102055065437272604672, 77371326314370156057591808, 77371330853998580447051776, 77371344689056635729215488, 4951760161825264712062140416, 19807040633249828010851631104, 1237940057804181942646931456, 19807040647084886066133794816, 19342836172264158932566016, 19807040651624514490523254784, 1237940113144414163775586304, 4951760231000554988472958976, 19342891512496380061220864, 4951760235540183412862418944, 19342905347554435343384576, 1237940131519100643447209984, 77371253680315365842747392, 77371258219943790232207360, 77371272055001845514371072, 1237940040510359373560741888, 4951760158366500198258114560, 309485014505088681206939648, 4951760161825264712078655488, 19342818878441589846376448, 4951760162906128622647574528, 309485028340146736489103360, 1237940057804181942663446528, 19342832713499645128540160, 1237940058885045853232365568, 19342836172264158949081088, 309485032879775160878563328, 77371257139079879663550464, 4951760161825264712078852096, 77371270974137934945714176, 1237940057804181942663643136, 19342836172264158949277696, 77371275513766359335174144]
theorem e19 : enumKeys 4616 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 360, c1145_b6, by decide, c1145_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1147_b7, by decide, c1147_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1147_b5, by decide, c1147_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1147_b4, by decide, c1147_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1147_b6, by decide, c1147_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1147_b3, by decide, c1147_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1147_b2, by decide, c1147_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1147_b1, by decide, c1147_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1147_b0, by decide, c1147_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1146_b9, by decide, c1146_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1146_b2, by decide, c1146_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 292, c1146_b1, by decide, c1146_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1146_b0, by decide, c1146_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c1150_b1, by decide, c1150_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1150_b0, by decide, c1150_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c1149_b9, by decide, c1149_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1149_b8, by decide, c1149_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c1149_b5, by decide, c1149_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c1149_b4, by decide, c1149_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1149_b7, by decide, c1149_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1149_b6, by decide, c1149_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1149_b3, by decide, c1149_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1149_b2, by decide, c1149_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1149_b1, by decide, c1149_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c1149_b0, by decide, c1149_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 292, c1145_b9, by decide, c1145_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1145_b8, by decide, c1145_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1145_b7, by decide, c1145_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1148_b9, by decide, c1148_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1148_b8, by decide, c1148_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1148_b7, by decide, c1148_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c1148_b6, by decide, c1148_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1148_b3, by decide, c1148_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1148_b2, by decide, c1148_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c1148_b5, by decide, c1148_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c1148_b4, by decide, c1148_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c1148_b1, by decide, c1148_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1148_b0, by decide, c1148_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c1147_b9, by decide, c1147_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1147_b8, by decide, c1147_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1146_b8, by decide, c1146_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1146_b7, by decide, c1146_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1146_b6, by decide, c1146_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1146_b5, by decide, c1146_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1146_b4, by decide, c1146_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1146_b3, by decide, c1146_ok3⟩, ?_⟩
  simp

def s20 : List Nat := [77371548756162951140868096, 79228162515489316692188790784, 79228162520028945116578250752, 309485305041307842115600384, 19343109414660750755037184, 1237940335586206958858862592, 309485309580936266505060352, 77371547675299040572211200, 77371552214927464961671168, 1237940043969123887364767744, 79228162518948081206009593856, 19342822337206103650402304, 79228162523487709630399053824, 1237940334505343048290205696, 19343112873425264575840256, 1237940339044971472679665664, 77371253680315365893079040, 77371258219943790282539008, 1237940040510359373611073536, 309485014505088681257271296, 1237940043969123887431614464, 19342818878441589896708096, 1237940045049987798000533504, 19342822337206103717249024, 309485019044717105646731264, 77371257139079879713882112, 1237940043969123887431811072, 19342822337206103717445632, 77371261678708304103342080]
theorem e20 : enumKeys 4616 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c1150_b2, by decide, c1150_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1151_b6, by decide, c1151_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1151_b4, by decide, c1151_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1151_b5, by decide, c1151_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1151_b3, by decide, c1151_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1151_b2, by decide, c1151_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1151_b1, by decide, c1151_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1150_b6, by decide, c1150_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1150_b5, by decide, c1150_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c1153_b0, by decide, c1153_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c1152_b9, by decide, c1152_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1152_b7, by decide, c1152_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c1152_b6, by decide, c1152_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1152_b8, by decide, c1152_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c1152_b5, by decide, c1152_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1152_b4, by decide, c1152_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1150_b4, by decide, c1150_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1150_b3, by decide, c1150_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1152_b3, by decide, c1152_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c1152_b2, by decide, c1152_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1152_b1, by decide, c1152_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1152_b0, by decide, c1152_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1151_b9, by decide, c1151_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1151_b8, by decide, c1151_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1151_b7, by decide, c1151_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1151_b0, by decide, c1151_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1150_b9, by decide, c1150_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1150_b8, by decide, c1150_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1150_b7, by decide, c1150_ok7⟩, ?_⟩
  simp

def s21 : List Nat := [77371254761179276394889216, 309485011046324167369621504, 19342815419677076009058304, 1237940041591223284112883712, 309485015585952591759081472, 77371253680315365826232320, 77371258219943790215692288, 1237940040510359373544226816, 309485014505088681190424576, 1237940043969123887364767744, 19342818878441589829861376, 1237940045049987797933686784, 19342822337206103650402304, 309485019044717105579884544, 1237940048508752311754227712, 77371257139079879647035392, 1237940043969123887364964352, 19342822337206103650598912, 77371261678708304036495360, 1237940048508752311754424320]
theorem e21 : enumKeys 4616 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c1153_b1, by decide, c1153_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1154_b2, by decide, c1154_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1154_b1, by decide, c1154_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c1154_b0, by decide, c1154_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1153_b9, by decide, c1153_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c1153_b3, by decide, c1153_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1153_b2, by decide, c1153_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1155_b0, by decide, c1155_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1154_b9, by decide, c1154_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1154_b8, by decide, c1154_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1154_b7, by decide, c1154_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1154_b6, by decide, c1154_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1154_b5, by decide, c1154_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1154_b4, by decide, c1154_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c1154_b3, by decide, c1154_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1153_b8, by decide, c1153_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c1153_b7, by decide, c1153_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1153_b6, by decide, c1153_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1153_b5, by decide, c1153_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1153_b4, by decide, c1153_ok4⟩, ?_⟩
  simp

def s22 : List Nat := [77371326314370156057395200, 77371344689056635729018880, 4951760175660322767344107520, 19807040647084886066133598208, 19342850007322214214533120, 19807040665459572545805221888, 4951760231000554988472762368, 19342905347554435343187968, 4951760249375241468144386048, 77371270974137934945517568, 4951760175660322767360819200, 19342850007322214231244800, 77371289348824414617141248]
theorem e22 : enumKeys 4616 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1155_b2, by decide, c1155_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c1155_b1, by decide, c1155_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c1156_b3, by decide, c1156_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1156_b2, by decide, c1156_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1156_b0, by decide, c1156_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1155_b9, by decide, c1155_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1156_b1, by decide, c1156_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1155_b8, by decide, c1155_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1155_b7, by decide, c1155_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1155_b6, by decide, c1155_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1155_b5, by decide, c1155_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c1155_b4, by decide, c1155_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c1155_b3, by decide, c1155_ok3⟩, ?_⟩
  simp

def s23 : List Nat := [77371547675299040572014592, 77371552214927464961474560, 77371566049985520243638272, 4951760161825264712061943808, 79228162518948081206009397248, 1237940057804181942646734848, 79228162532783139261291560960, 19342836172264158932369408, 79228162537322767685681020928, 1237940334505343048290009088, 4951760452361483872987381760, 19343112873425264575643648, 4951760456901112297376841728, 19343126708483319857807360, 1237940352880029527961632768, 77371257139079879713685504, 4951760161825264712128987136, 77371270974137934995849216, 1237940057804181942713778176, 19342836172264158999412736, 77371275513766359385309184]
theorem e23 : enumKeys 4616 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1156_b6, by decide, c1156_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1156_b5, by decide, c1156_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1156_b4, by decide, c1156_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c1158_b4, by decide, c1158_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c1158_b3, by decide, c1158_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1158_b2, by decide, c1158_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c1158_b1, by decide, c1158_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1157_b8, by decide, c1157_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c1157_b7, by decide, c1157_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1158_b0, by decide, c1158_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1157_b9, by decide, c1157_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1157_b6, by decide, c1157_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1157_b5, by decide, c1157_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c1157_b4, by decide, c1157_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c1157_b3, by decide, c1157_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c1157_b2, by decide, c1157_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1157_b1, by decide, c1157_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1157_b0, by decide, c1157_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1156_b9, by decide, c1156_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1156_b8, by decide, c1156_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1156_b7, by decide, c1156_ok7⟩, ?_⟩
  simp

def s24 : List Nat := [77371253680315365826035712, 77371258219943790215495680, 77371272055001845497659392, 1237940040510359373544030208, 4951760158366500198241402880, 309485014505088681190227968, 1237940043969123887364571136, 4951760161825264712061943808, 19342818878441589829664768, 1237940045049987797933490176, 4951760162906128622630862848, 19342822337206103650205696, 309485019044717105579687936, 4951760166364893136451403776, 309485028340146736472391680, 1237940057804181942646734848, 19342832713499645111828480, 1237940058885045853215653888, 19342836172264158932369408, 309485032879775160861851648, 1237940062343810367036194816, 77371257139079879646838784, 1237940043969123887364767744, 4951760161825264712062140416, 19342822337206103650402304, 77371261678708304036298752, 4951760166364893136451600384, 77371270974137934929002496, 1237940057804181942646931456, 19342836172264158932566016, 77371275513766359318462464, 1237940062343810367036391424]
theorem e24 : enumKeys 4616 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c1158_b7, by decide, c1158_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1158_b6, by decide, c1158_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c1158_b5, by decide, c1158_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1161_b6, by decide, c1161_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1161_b5, by decide, c1161_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1161_b4, by decide, c1161_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1161_b3, by decide, c1161_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c1161_b2, by decide, c1161_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1160_b9, by decide, c1160_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1160_b8, by decide, c1160_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1160_b7, by decide, c1160_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1160_b4, by decide, c1160_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1160_b3, by decide, c1160_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c1160_b2, by decide, c1160_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1161_b1, by decide, c1161_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1161_b0, by decide, c1161_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1160_b6, by decide, c1160_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1160_b5, by decide, c1160_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1160_b1, by decide, c1160_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1160_b0, by decide, c1160_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1159_b9, by decide, c1159_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1159_b8, by decide, c1159_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c1159_b7, by decide, c1159_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1159_b6, by decide, c1159_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c1159_b3, by decide, c1159_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1159_b2, by decide, c1159_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1159_b1, by decide, c1159_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1159_b5, by decide, c1159_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c1159_b4, by decide, c1159_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c1159_b0, by decide, c1159_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1158_b9, by decide, c1158_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1158_b8, by decide, c1158_ok8⟩, ?_⟩
  simp

def s25 : List Nat := [77371257139079879646642176, 4951760161825264712061943808, 77371270974137934928805888, 1237940057804181942646734848, 4951760175660322767344107520, 19342836172264158932369408, 77371275513766359318265856, 4951760180199951191733567488, 19342850007322214214533120, 77371289348824414600429568, 1237940076178868422318358528]
theorem e25 : enumKeys 4616 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c1162_b7, by decide, c1162_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1162_b6, by decide, c1162_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1162_b5, by decide, c1162_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c1162_b4, by decide, c1162_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1162_b3, by decide, c1162_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c1162_b2, by decide, c1162_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1162_b1, by decide, c1162_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1162_b0, by decide, c1162_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1161_b9, by decide, c1161_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1161_b8, by decide, c1161_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1161_b7, by decide, c1161_ok7⟩, ?_⟩
  simp

def s26 : List Nat := [79228162661838290183220363264, 19807040997500965872577019904, 79228162588123371482436861952, 19807040923786047171793518592, 19343182048715541003108352, 79228162514408452781653360640, 19343108333796840219607040, 19807040702425118287329230848, 19342960687786656538820608, 19807040628710199586545729536, 19342886972867955755319296]
theorem e26 : enumKeys 4616 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1162_b9, by decide, c1162_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c1162_b8, by decide, c1162_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1163_b4, by decide, c1163_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c1163_b3, by decide, c1163_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c1163_b2, by decide, c1163_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c1163_b8, by decide, c1163_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c1163_b7, by decide, c1163_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c1163_b1, by decide, c1163_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c1163_b0, by decide, c1163_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c1163_b6, by decide, c1163_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c1163_b5, by decide, c1163_ok5⟩, ?_⟩
  simp

def s27 : List Nat := [19807040703505982197831041024, 309485157395297658401193984, 19807040702425118287262384128, 19807040706964746711651844096, 19342960687786656471973888, 1237940186859332864575799296, 19807040629791063497047539712, 19807040634330691921436999680, 309485083680378957617692672, 19342888053731866257129472, 1237940114225278074360954880, 309485088220007382007152640, 1237940039429495462992019456, 19807040628710199586478882816, 19342817797577679277654016, 19807040633249828010868342784, 19342886972867955688472576, 1237940113144414163792297984, 19342891512496380077932544, 309485009965460256834191360, 1237940039429495463008534528, 19342814338813165473628160, 1237940040510359373577453568, 19342817797577679294169088, 309485014505088681223651328, 19342818878441589863088128]
theorem e27 : enumKeys 4616 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 284, c1164_b0, by decide, c1164_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1163_b9, by decide, c1163_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1165_b7, by decide, c1165_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1165_b6, by decide, c1165_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1165_b5, by decide, c1165_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1165_b4, by decide, c1165_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c1164_b6, by decide, c1164_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1164_b4, by decide, c1164_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1164_b5, by decide, c1164_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1164_b3, by decide, c1164_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c1164_b2, by decide, c1164_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1164_b1, by decide, c1164_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c1166_b4, by decide, c1166_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1166_b3, by decide, c1166_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c1166_b2, by decide, c1166_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c1166_b1, by decide, c1166_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1166_b0, by decide, c1166_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c1165_b9, by decide, c1165_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c1165_b8, by decide, c1165_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c1165_b3, by decide, c1165_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c1165_b2, by decide, c1165_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1165_b1, by decide, c1165_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1165_b0, by decide, c1165_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1164_b9, by decide, c1164_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c1164_b8, by decide, c1164_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1164_b7, by decide, c1164_ok7⟩, ?_⟩
  simp

def s28 : List Nat := [77371400029288856857608192, 19807040702425118287262187520, 19807040720799804766933811200, 19342960687786656471777280, 4951760304715473689272975360, 77371326314370156074106880, 77371344689056635745730560, 4951760157285636287689195520, 19807040628710199586478686208, 19342831632635734559621120, 19807040647084886066150309888, 19342886972867955688275968, 4951760231000554988489474048, 19342905347554435359899648, 77371252599451455290605568, 4951760157285636287705907200, 19342831632635734576332800, 77371270974137934962229248]
theorem e28 : enumKeys 4616 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c1166_b5, by decide, c1166_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1167_b5, by decide, c1167_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1167_b4, by decide, c1167_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c1167_b3, by decide, c1167_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1167_b2, by decide, c1167_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1166_b7, by decide, c1166_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c1166_b6, by decide, c1166_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1168_b2, by decide, c1168_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1168_b1, by decide, c1168_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c1168_b0, by decide, c1168_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1167_b9, by decide, c1167_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1167_b8, by decide, c1167_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1167_b7, by decide, c1167_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1167_b6, by decide, c1167_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1167_b1, by decide, c1167_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1167_b0, by decide, c1167_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1166_b9, by decide, c1166_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1166_b8, by decide, c1166_ok8⟩, ?_⟩
  simp

def s29 : List Nat := [77371621390217741372227584, 79228162588123371482420150272, 79228162592662999906809610240, 19807040923786047171776806912, 19807040928325675596166266880, 19343182048715540986396672, 1237940408220261749090222080, 77371547675299040588726272, 77371552214927464978186240, 1237940039429495462991822848, 79228162514408452781636648960, 19342817797577679277457408, 79228162518948081206026108928, 19343108333796840202895360, 1237940334505343048306720768, 19343112873425264592355328, 77371326314370156124438528, 77371330853998580513898496, 1237940039429495463042154496, 19807040628710199586529017856, 19342817797577679327789056, 19807040633249828010918477824, 19342886972867955738607616, 1237940113144414163842433024, 19342891512496380128067584, 77371252599451455340937216, 1237940039429495463058866176, 19342817797577679344500736, 77371257139079879730397184]
theorem e29 : enumKeys 4616 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c1168_b3, by decide, c1168_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1169_b7, by decide, c1169_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1169_b5, by decide, c1169_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c1169_b6, by decide, c1169_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1169_b4, by decide, c1169_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1169_b3, by decide, c1169_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1169_b2, by decide, c1169_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1168_b7, by decide, c1168_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1168_b6, by decide, c1168_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c1171_b1, by decide, c1171_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c1171_b0, by decide, c1171_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c1170_b9, by decide, c1170_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c1170_b8, by decide, c1170_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c1170_b7, by decide, c1170_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c1170_b6, by decide, c1170_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c1170_b5, by decide, c1170_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1168_b5, by decide, c1168_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1168_b4, by decide, c1168_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c1170_b4, by decide, c1170_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1170_b3, by decide, c1170_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c1170_b2, by decide, c1170_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c1170_b1, by decide, c1170_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c1170_b0, by decide, c1170_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1169_b9, by decide, c1169_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1169_b8, by decide, c1169_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1169_b1, by decide, c1169_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1169_b0, by decide, c1169_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1168_b9, by decide, c1168_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1168_b8, by decide, c1168_ok8⟩, ?_⟩
  simp

def s30 : List Nat := [77371327395234066626248704, 19807040629791063497030828032, 19807040634330691921420288000, 309485083680378957600980992, 19342888053731866240417792, 1237940114225278074344243200, 309485088220007381990440960, 77371326314370156057591808, 77371330853998580447051776, 1237940039429495462975307776, 19807040628710199586462171136, 19342817797577679260942336, 1237940043969123887364767744, 19807040633249828010851631104, 19342822337206103650402304, 19807040637789456435241091072, 19342886972867955671760896, 1237940113144414163775586304, 19342891512496380061220864, 1237940117684042588165046272, 77371253680315365842747392, 77371258219943790232207360, 309485009965460256817479680, 1237940039429495462991822848, 19342814338813165456916480, 1237940040510359373560741888, 19342817797577679277457408, 309485014505088681206939648, 1237940043969123887381282816, 19342818878441589846376448, 1237940045049987797950201856, 19342822337206103666917376, 309485019044717105596399616, 77371252599451455274090496, 1237940039429495462992019456, 19342817797577679277654016, 77371257139079879663550464, 1237940043969123887381479424, 19342822337206103667113984, 77371261678708304053010432]
theorem e30 : enumKeys 4616 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 360, c1171_b2, by decide, c1171_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1172_b9, by decide, c1172_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1172_b7, by decide, c1172_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1172_b8, by decide, c1172_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1172_b6, by decide, c1172_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1172_b5, by decide, c1172_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1172_b4, by decide, c1172_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1171_b6, by decide, c1171_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 292, c1171_b5, by decide, c1171_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1175_b1, by decide, c1175_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1175_b0, by decide, c1175_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c1174_b9, by decide, c1174_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1174_b8, by decide, c1174_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1174_b7, by decide, c1174_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1174_b4, by decide, c1174_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1174_b3, by decide, c1174_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1174_b6, by decide, c1174_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1174_b5, by decide, c1174_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1174_b2, by decide, c1174_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c1174_b1, by decide, c1174_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 292, c1171_b4, by decide, c1171_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1171_b3, by decide, c1171_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c1174_b0, by decide, c1174_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c1173_b9, by decide, c1173_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c1173_b8, by decide, c1173_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1173_b7, by decide, c1173_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1173_b6, by decide, c1173_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1173_b5, by decide, c1173_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c1173_b4, by decide, c1173_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1173_b3, by decide, c1173_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1173_b2, by decide, c1173_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1173_b1, by decide, c1173_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1173_b0, by decide, c1173_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1172_b3, by decide, c1172_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1172_b2, by decide, c1172_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1172_b1, by decide, c1172_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1172_b0, by decide, c1172_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c1171_b9, by decide, c1171_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c1171_b8, by decide, c1171_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c1171_b7, by decide, c1171_ok7⟩, ?_⟩
  simp

def s31 : List Nat := [77371326314370156057395200, 77371330853998580446855168, 77371344689056635729018880, 1237940039429495462975111168, 4951760157285636287672483840, 19807040628710199586461974528, 19342817797577679260745728, 4951760161825264712061943808, 19807040633249828010851434496, 19342831632635734542909440, 1237940057804181942646734848, 19807040647084886066133598208, 19342836172264158932369408, 19807040651624514490523058176, 19342886972867955671564288, 1237940113144414163775389696, 4951760231000554988472762368, 19342891512496380061024256, 4951760235540183412862222336, 19342905347554435343187968, 1237940131519100643447013376, 77371252599451455273893888, 1237940039429495462991822848, 4951760157285636287689195520, 19342817797577679277457408, 77371257139079879663353856, 4951760161825264712078655488, 19342831632635734559621120, 77371270974137934945517568, 1237940057804181942663446528, 19342836172264158949081088, 77371275513766359334977536]
theorem e31 : enumKeys 4616 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1175_b4, by decide, c1175_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c1175_b3, by decide, c1175_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c1175_b2, by decide, c1175_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1178_b3, by decide, c1178_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c1178_b2, by decide, c1178_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1178_b1, by decide, c1178_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1178_b0, by decide, c1178_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c1177_b9, by decide, c1177_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1177_b8, by decide, c1177_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1177_b7, by decide, c1177_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c1177_b6, by decide, c1177_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1177_b5, by decide, c1177_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1177_b1, by decide, c1177_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1177_b0, by decide, c1177_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1177_b4, by decide, c1177_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1177_b3, by decide, c1177_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1177_b2, by decide, c1177_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1176_b9, by decide, c1176_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1176_b8, by decide, c1176_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c1176_b7, by decide, c1176_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1176_b6, by decide, c1176_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1176_b5, by decide, c1176_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c1176_b4, by decide, c1176_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1176_b3, by decide, c1176_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c1176_b2, by decide, c1176_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1176_b1, by decide, c1176_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1176_b0, by decide, c1176_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c1175_b9, by decide, c1175_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1175_b8, by decide, c1175_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c1175_b7, by decide, c1175_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c1175_b6, by decide, c1175_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1175_b5, by decide, c1175_ok5⟩, ?_⟩
  simp

def s32 : List Nat := [77371547675299040572014592, 77371552214927464961474560, 1237940039429495462975111168, 79228162514408452781619937280, 19342817797577679260745728, 1237940043969123887364571136, 79228162518948081206009397248, 19342822337206103650205696, 79228162523487709630398857216, 19343108333796840186183680, 1237940334505343048290009088, 19343112873425264575643648, 1237940339044971472679469056, 77371252599451455324225536, 1237940039429495463042154496, 19342817797577679327789056, 77371257139079879713685504, 1237940043969123887431614464, 19342822337206103717249024, 77371261678708304103145472]
theorem e32 : enumKeys 4616 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1178_b5, by decide, c1178_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1178_b4, by decide, c1178_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1180_b3, by decide, c1180_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1180_b2, by decide, c1180_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1180_b1, by decide, c1180_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c1180_b0, by decide, c1180_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c1179_b9, by decide, c1179_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1179_b6, by decide, c1179_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1179_b5, by decide, c1179_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1179_b8, by decide, c1179_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1179_b7, by decide, c1179_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1179_b4, by decide, c1179_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c1179_b3, by decide, c1179_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c1179_b2, by decide, c1179_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1179_b1, by decide, c1179_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1179_b0, by decide, c1179_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c1178_b9, by decide, c1178_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1178_b8, by decide, c1178_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1178_b7, by decide, c1178_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c1178_b6, by decide, c1178_ok6⟩, ?_⟩
  simp

def s33 : List Nat := [77371253680315365826035712, 77371258219943790215495680, 309485009965460256800768000, 1237940039429495462975111168, 19342814338813165440204800, 1237940040510359373544030208, 19342817797577679260745728, 309485014505088681190227968, 1237940043969123887364571136, 19342818878441589829664768, 1237940045049987797933490176, 19342822337206103650205696, 309485019044717105579687936, 1237940048508752311754031104, 77371252599451455257378816, 1237940039429495462975307776, 19342817797577679260942336, 77371257139079879646838784, 1237940043969123887364767744, 19342822337206103650402304, 77371261678708304036298752, 1237940048508752311754227712]
theorem e33 : enumKeys 4616 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c1180_b5, by decide, c1180_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1180_b4, by decide, c1180_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1182_b5, by decide, c1182_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1182_b4, by decide, c1182_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1182_b3, by decide, c1182_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1182_b2, by decide, c1182_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c1182_b1, by decide, c1182_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1182_b0, by decide, c1182_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1181_b9, by decide, c1181_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1181_b8, by decide, c1181_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1181_b7, by decide, c1181_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1181_b6, by decide, c1181_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1181_b5, by decide, c1181_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1181_b4, by decide, c1181_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1181_b3, by decide, c1181_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1181_b2, by decide, c1181_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1181_b1, by decide, c1181_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1181_b0, by decide, c1181_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c1180_b9, by decide, c1180_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c1180_b8, by decide, c1180_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1180_b7, by decide, c1180_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1180_b6, by decide, c1180_ok6⟩, ?_⟩
  simp

def s34 : List Nat := [77371252599451455257182208, 1237940039429495462975111168, 4951760157285636287672483840, 19342817797577679260745728, 77371257139079879646642176, 1237940043969123887364571136, 4951760161825264712061943808, 19342822337206103650205696, 77371261678708304036102144, 4951760166364893136451403776, 19342831632635734542909440, 77371270974137934928805888, 1237940057804181942646734848, 19342836172264158932369408, 77371275513766359318265856, 1237940062343810367036194816]
theorem e34 : enumKeys 4616 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c1184_b1, by decide, c1184_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1184_b0, by decide, c1184_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1183_b9, by decide, c1183_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1183_b8, by decide, c1183_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c1183_b7, by decide, c1183_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1183_b6, by decide, c1183_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1183_b5, by decide, c1183_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1183_b1, by decide, c1183_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c1183_b0, by decide, c1183_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1182_b9, by decide, c1182_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1183_b4, by decide, c1183_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1183_b3, by decide, c1183_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c1183_b2, by decide, c1183_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c1182_b8, by decide, c1182_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1182_b7, by decide, c1182_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1182_b6, by decide, c1182_ok6⟩, ?_⟩
  simp

def s35 : List Nat := [19807040776140036988062400512, 19807040702425118287278899200, 19342960687786656488488960, 19342813257949254904709120, 19807040628710199586495397888, 19342886972867955704987648]
theorem e35 : enumKeys 4616 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1184_b2, by decide, c1184_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c1184_b4, by decide, c1184_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1184_b3, by decide, c1184_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1184_b7, by decide, c1184_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c1184_b6, by decide, c1184_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1184_b5, by decide, c1184_ok5⟩, ?_⟩
  simp

def s36 : List Nat := [77371400029288856857608192, 19807040702425118287262187520, 19807040706964746711651647488, 19342960687786656471777280, 1237940186859332864575602688, 77371326314370156074106880, 77371330853998580463566848, 19342813257949254887997440, 1237940039429495462991822848, 19807040628710199586478686208, 19342817797577679277457408, 19807040633249828010868146176, 19342886972867955688275968, 1237940113144414163792101376, 19342891512496380077735936, 19342813257949254904709120, 77371252599451455290605568, 1237940039429495463008534528, 19342817797577679294169088, 77371257139079879680065536]
theorem e36 : enumKeys 4616 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c1184_b8, by decide, c1184_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1185_b9, by decide, c1185_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c1185_b8, by decide, c1185_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c1185_b7, by decide, c1185_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1185_b6, by decide, c1185_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1185_b0, by decide, c1185_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c1184_b9, by decide, c1184_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c1186_b7, by decide, c1186_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1186_b6, by decide, c1186_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c1186_b5, by decide, c1186_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1186_b4, by decide, c1186_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c1186_b3, by decide, c1186_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1186_b2, by decide, c1186_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1186_b1, by decide, c1186_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1186_b0, by decide, c1186_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1185_b5, by decide, c1185_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1185_b4, by decide, c1185_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1185_b3, by decide, c1185_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c1185_b2, by decide, c1185_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c1185_b1, by decide, c1185_ok1⟩, ?_⟩
  simp

def s37 : List Nat := [77371326314370156057395200, 77371330853998580446855168, 19342813257949254871285760, 1237940039429495462975111168, 19807040628710199586461974528, 19342817797577679260745728, 1237940043969123887364571136, 19807040633249828010851434496, 19342822337206103650205696, 19807040637789456435240894464, 19342886972867955671564288, 1237940113144414163775389696, 19342891512496380061024256, 1237940117684042588164849664, 19342813257949254887997440, 77371252599451455273893888, 1237940039429495462991822848, 19342817797577679277457408, 77371257139079879663353856, 1237940043969123887381282816, 19342822337206103666917376, 77371261678708304052813824]
theorem e37 : enumKeys 4616 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c1186_b9, by decide, c1186_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c1186_b8, by decide, c1186_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1188_b9, by decide, c1188_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1188_b8, by decide, c1188_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1188_b7, by decide, c1188_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c1188_b6, by decide, c1188_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c1188_b5, by decide, c1188_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1188_b4, by decide, c1188_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1188_b1, by decide, c1188_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1188_b0, by decide, c1188_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1188_b3, by decide, c1188_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1188_b2, by decide, c1188_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c1187_b9, by decide, c1187_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1187_b8, by decide, c1187_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c1187_b7, by decide, c1187_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1187_b6, by decide, c1187_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c1187_b5, by decide, c1187_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c1187_b4, by decide, c1187_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1187_b3, by decide, c1187_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c1187_b2, by decide, c1187_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1187_b1, by decide, c1187_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c1187_b0, by decide, c1187_ok0⟩, ?_⟩
  simp

def s38 : List Nat := [19342813257949254871285760, 77371252599451455257182208, 1237940039429495462975111168, 19342817797577679260745728, 77371257139079879646642176, 1237940043969123887364571136, 19342822337206103650205696, 77371261678708304036102144, 1237940048508752311754031104]
theorem e38 : enumKeys 4616 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1189_b8, by decide, c1189_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c1189_b7, by decide, c1189_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1189_b6, by decide, c1189_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1189_b5, by decide, c1189_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c1189_b4, by decide, c1189_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c1189_b3, by decide, c1189_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1189_b2, by decide, c1189_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c1189_b1, by decide, c1189_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1189_b0, by decide, c1189_ok0⟩, ?_⟩
  simp

/-- every enumerated key with left type `4616` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 4616 mR,
    (4616 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 4616 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K10
end Grid3.Three.Cert
