import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C1292
import Grid3.Three.Cert.Data.C1293
import Grid3.Three.Cert.Data.C1294
import Grid3.Three.Cert.Data.C1295
import Grid3.Three.Cert.Data.C1296
import Grid3.Three.Cert.Data.C1297
import Grid3.Three.Cert.Data.C1298
import Grid3.Three.Cert.Data.C1299
import Grid3.Three.Cert.Data.C1300
import Grid3.Three.Cert.Data.C1301
import Grid3.Three.Cert.Data.C1302
import Grid3.Three.Cert.Data.C1303
import Grid3.Three.Cert.Data.C1304
import Grid3.Three.Cert.Data.C1305
import Grid3.Three.Cert.Data.C1306
import Grid3.Three.Cert.Data.C1307
import Grid3.Three.Cert.Data.C1308
import Grid3.Three.Cert.Data.C1309
import Grid3.Three.Cert.Data.C1310
import Grid3.Three.Cert.Data.C1311
import Grid3.Three.Cert.Data.C1312
import Grid3.Three.Cert.Data.C1313
import Grid3.Three.Cert.Data.C1314

/-! Seam keys with left type `780` (type index 12): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `ai_research_notes/cx/k3rev/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K12

def s00 : List Nat := [885443715538058477568, 590295810358772760576, 295147905179487043584, 201326592]
theorem e00 : enumKeys 780 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c1292_b5, by decide, c1292_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 182, c1292_b6, by decide, c1292_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c1292_b7, by decide, c1292_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c1292_b8, by decide, c1292_ok8⟩, ?_⟩
  simp

def s01 : List Nat := [370087802978797879296, 387381625547900846080, 314747570757686001664, 313594649253079416832, 93386641873221713920, 92233720368615129088, 19599665578400284672, 18446744073793699840]
theorem e01 : enumKeys 780 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1292_b9, by decide, c1292_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1293_b3, by decide, c1293_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1293_b1, by decide, c1293_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c1293_b5, by decide, c1293_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c1293_b0, by decide, c1293_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1293_b4, by decide, c1293_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1293_b2, by decide, c1293_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1293_b6, by decide, c1293_ok6⟩, ?_⟩
  simp

def s02 : List Nat := [591448731863312498688, 594907496377133301760, 300912512702454169600, 299759591197847584768, 5764607523168452608, 4611686018561867776]
theorem e02 : enumKeys 780 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1293_b7, by decide, c1293_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c1294_b0, by decide, c1294_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1293_b8, by decide, c1293_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1294_b1, by decide, c1294_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1293_b9, by decide, c1293_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1294_b2, by decide, c1294_ok2⟩, ?_⟩
  simp

def s03 : List Nat := [76092819304051900416, 79551583817872703488, 93386641873154867200, 96845406386975670272, 6917529027657859072, 20752587082940022784, 24211351596760825856, 23058430092154241024]
theorem e03 : enumKeys 780 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 366, c1294_b3, by decide, c1294_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c1294_b7, by decide, c1294_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1294_b6, by decide, c1294_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1294_b9, by decide, c1294_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1294_b5, by decide, c1294_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1294_b4, by decide, c1294_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1294_b8, by decide, c1294_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1295_b0, by decide, c1295_ok0⟩, ?_⟩
  simp

def s04 : List Nat := [297453748188566519808, 300912512702387322880, 304371277216208125952, 6917529027708190720, 10376293541528993792, 9223372036922408960]
theorem e04 : enumKeys 780 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1295_b1, by decide, c1295_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1295_b3, by decide, c1295_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1295_b5, by decide, c1295_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1295_b2, by decide, c1295_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1295_b4, by decide, c1295_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1295_b6, by decide, c1295_ok6⟩, ?_⟩
  simp

def s05 : List Nat := [3458764513820540928, 6917529027641344000, 10376293541462147072, 13835058055282950144]
theorem e05 : enumKeys 780 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1295_b7, by decide, c1295_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c1295_b8, by decide, c1295_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1295_b9, by decide, c1295_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1296_b0, by decide, c1296_ok0⟩, ?_⟩
  simp

def s06 : List Nat := [608742554432415268864, 313594649253129551872, 18446744073843834880]
theorem e06 : enumKeys 780 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c1296_b1, by decide, c1296_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c1296_b2, by decide, c1296_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1296_b3, by decide, c1296_ok3⟩, ?_⟩
  simp

def s07 : List Nat := [93386641873154670592, 110680464442257637376, 38046409652042792960, 36893488147436208128]
theorem e07 : enumKeys 780 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1296_b4, by decide, c1296_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1296_b6, by decide, c1296_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1296_b5, by decide, c1296_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1296_b7, by decide, c1296_ok7⟩, ?_⟩
  simp

def s08 : List Nat := [300912512702387126272, 314747570757669289984, 318206335271490093056, 24211351596810960896, 23058430092204376064]
theorem e08 : enumKeys 780 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1296_b9, by decide, c1296_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1296_b8, by decide, c1296_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1297_b1, by decide, c1297_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1297_b0, by decide, c1297_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1297_b2, by decide, c1297_ok2⟩, ?_⟩
  simp

def s09 : List Nat := [6917529027641147392, 20752587082923311104, 10376293541461950464, 24211351596744114176, 27670116110564917248]
theorem e09 : enumKeys 780 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c1297_b4, by decide, c1297_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1297_b3, by decide, c1297_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1297_b6, by decide, c1297_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c1297_b5, by decide, c1297_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1297_b7, by decide, c1297_ok7⟩, ?_⟩
  simp

def s10 : List Nat := [332041393326772060160, 36893488147486343168]
theorem e10 : enumKeys 780 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1297_b8, by decide, c1297_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1297_b9, by decide, c1297_ok9⟩, ?_⟩
  simp

def s11 : List Nat := [24211351596743917568, 38046409652026081280, 41505174165846884352]
theorem e11 : enumKeys 780 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c1298_b1, by decide, c1298_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1298_b0, by decide, c1298_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1298_b2, by decide, c1298_ok2⟩, ?_⟩
  simp

def s12 : List Nat := [55340232221128851456]
theorem e12 : enumKeys 780 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1298_b3, by decide, c1298_ok3⟩, ?_⟩
  simp

def s13 : List Nat := [664082786653543858176, 590367867952760356864, 369006939068296069120, 295219962773474639872, 73859033889010352128, 72057594188922880]
theorem e13 : enumKeys 780 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1298_b4, by decide, c1298_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c1298_b7, by decide, c1298_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c1298_b5, by decide, c1298_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c1298_b8, by decide, c1298_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c1298_b6, by decide, c1298_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1298_b9, by decide, c1298_ok9⟩, ?_⟩
  simp

def s14 : List Nat := [148726874094283259904, 147646010183714603008, 166020696663386226688, 75011955393499758592, 93386641873171382272, 92305777962602725376, 19671723172387880960, 18518801667781296128]
theorem e14 : enumKeys 780 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 366, c1299_b0, by decide, c1299_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1299_b5, by decide, c1299_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1299_b4, by decide, c1299_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c1299_b2, by decide, c1299_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1299_b1, by decide, c1299_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c1299_b6, by decide, c1299_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1299_b3, by decide, c1299_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1299_b7, by decide, c1299_ok7⟩, ?_⟩
  simp

def s15 : List Nat := [370087802978797879296, 369006939068229222400, 373546567492618682368, 296372884278014377984, 300912512702403837952, 299831648791835181056, 75011955393550090240, 79551583817939550208, 78470719907370893312, 5836665117156048896, 4683743612549464064]
theorem e15 : enumKeys 780 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c1299_b8, by decide, c1299_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1300_b5, by decide, c1300_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1300_b4, by decide, c1300_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1300_b2, by decide, c1300_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1300_b1, by decide, c1300_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c1300_b7, by decide, c1300_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c1300_b0, by decide, c1300_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c1299_b9, by decide, c1299_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1300_b6, by decide, c1300_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c1300_b3, by decide, c1300_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1300_b8, by decide, c1300_ok8⟩, ?_⟩
  simp

def s16 : List Nat := [76092819304051900416, 75011955393483243520, 79551583817872703488, 78470719907304046592, 83010348331693506560, 2377900603268399104, 6917529027657859072, 5836665117089202176, 10376293541478662144, 9295429630910005248]
theorem e16 : enumKeys 780 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 366, c1300_b9, by decide, c1300_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1301_b3, by decide, c1301_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c1301_b2, by decide, c1301_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1301_b7, by decide, c1301_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1301_b6, by decide, c1301_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1301_b1, by decide, c1301_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1301_b0, by decide, c1301_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1301_b5, by decide, c1301_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1301_b4, by decide, c1301_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1301_b8, by decide, c1301_ok8⟩, ?_⟩
  simp

def s17 : List Nat := [369006939068229025792, 387381625547900649472, 313666706847117148160, 92305777962652860416, 18518801667831431168]
theorem e17 : enumKeys 780 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1302_b0, by decide, c1302_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1301_b9, by decide, c1301_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1302_b2, by decide, c1302_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c1302_b1, by decide, c1302_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1302_b3, by decide, c1302_ok3⟩, ?_⟩
  simp

def s18 : List Nat := [590367867952743645184, 594907496377133105152, 299831648791885316096, 4683743612599599104]
theorem e18 : enumKeys 780 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1302_b5, by decide, c1302_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1302_b4, by decide, c1302_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c1302_b6, by decide, c1302_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1302_b7, by decide, c1302_ok7⟩, ?_⟩
  simp

def s19 : List Nat := [75011955393483046912, 79551583817872506880, 93386641873154670592, 78470719907303849984, 92305777962586013696, 96845406386975473664, 5836665117089005568, 19671723172371169280, 24211351596760629248, 23130487686191972352]
theorem e19 : enumKeys 780 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 358, c1303_b0, by decide, c1303_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 358, c1302_b9, by decide, c1302_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1302_b8, by decide, c1302_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1303_b6, by decide, c1303_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c1303_b5, by decide, c1303_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1303_b4, by decide, c1303_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1303_b3, by decide, c1303_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1303_b2, by decide, c1303_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c1303_b1, by decide, c1303_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c1303_b7, by decide, c1303_ok7⟩, ?_⟩
  simp

def s20 : List Nat := [296372884277997666304, 300912512702387126272, 299831648791818469376, 304371277216207929344, 5836665117139337216, 10376293541528797184, 9295429630960140288]
theorem e20 : enumKeys 780 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1303_b9, by decide, c1303_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1303_b8, by decide, c1303_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1304_b3, by decide, c1304_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1304_b2, by decide, c1304_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1304_b1, by decide, c1304_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1304_b0, by decide, c1304_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1304_b4, by decide, c1304_ok4⟩, ?_⟩
  simp

def s21 : List Nat := [2377900603251687424, 6917529027641147392, 5836665117072490496, 10376293541461950464, 9295429630893293568, 13835058055282753536]
theorem e21 : enumKeys 780 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1304_b6, by decide, c1304_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c1304_b5, by decide, c1304_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1304_b8, by decide, c1304_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1304_b7, by decide, c1304_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1305_b0, by decide, c1305_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1304_b9, by decide, c1304_ok9⟩, ?_⟩
  simp

def s22 : List Nat := [92305777962585817088, 110680464442257440768, 36965545741473939456]
theorem e22 : enumKeys 780 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c1305_b2, by decide, c1305_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1305_b1, by decide, c1305_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1305_b3, by decide, c1305_ok3⟩, ?_⟩
  simp

def s23 : List Nat := [299831648791818272768, 313666706847100436480, 318206335271489896448, 23130487686242107392]
theorem e23 : enumKeys 780 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1305_b6, by decide, c1305_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1305_b5, by decide, c1305_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1305_b4, by decide, c1305_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1305_b7, by decide, c1305_ok7⟩, ?_⟩
  simp

def s24 : List Nat := [5836665117072293888, 10376293541461753856, 19671723172354457600, 24211351596743917568, 9295429630893096960, 23130487686175260672, 27670116110564720640]
theorem e24 : enumKeys 780 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c1306_b1, by decide, c1306_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c1305_b9, by decide, c1305_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1306_b0, by decide, c1306_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c1305_b8, by decide, c1305_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1306_b4, by decide, c1306_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1306_b3, by decide, c1306_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1306_b2, by decide, c1306_ok2⟩, ?_⟩
  simp

def s25 : List Nat := [23130487686175064064, 36965545741457227776, 41505174165846687744]
theorem e25 : enumKeys 780 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1306_b7, by decide, c1306_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1306_b6, by decide, c1306_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1306_b5, by decide, c1306_ok5⟩, ?_⟩
  simp

def s26 : List Nat := [442721857769029238784, 369006939068245737472, 295292020367462236160, 147646010183781449728, 73931091482997948416, 144115188176519168]
theorem e26 : enumKeys 780 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1306_b8, by decide, c1306_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1307_b0, by decide, c1307_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c1307_b2, by decide, c1307_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c1306_b9, by decide, c1306_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c1307_b1, by decide, c1307_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1307_b3, by decide, c1307_ok3⟩, ?_⟩
  simp

def s27 : List Nat := [148726874094283259904, 147646010183714603008, 152185638608104062976, 75011955393499758592, 79551583817889218560, 73931091482931101696, 78470719907320561664, 1297036692716257280, 5836665117105717248, 4755801206537060352]
theorem e27 : enumKeys 780 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 366, c1307_b4, by decide, c1307_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1308_b0, by decide, c1308_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1307_b9, by decide, c1307_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c1307_b6, by decide, c1307_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c1307_b5, by decide, c1307_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1308_b2, by decide, c1308_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c1308_b1, by decide, c1308_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1307_b8, by decide, c1307_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c1307_b7, by decide, c1307_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c1308_b3, by decide, c1308_ok3⟩, ?_⟩
  simp

def s28 : List Nat := [147646010183714406400, 166020696663386030080, 73931091482930905088, 92305777962602528768, 18590859261819027456]
theorem e28 : enumKeys 780 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c1308_b5, by decide, c1308_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1308_b4, by decide, c1308_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1308_b7, by decide, c1308_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c1308_b6, by decide, c1308_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1308_b8, by decide, c1308_ok8⟩, ?_⟩
  simp

def s29 : List Nat := [369006939068229025792, 373546567492618485760, 295292020367445524480, 299831648791834984448, 73931091482981236736, 78470719907370696704, 4755801206587195392]
theorem e29 : enumKeys 780 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1309_b0, by decide, c1309_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1308_b9, by decide, c1308_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c1309_b4, by decide, c1309_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c1309_b3, by decide, c1309_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c1309_b2, by decide, c1309_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c1309_b1, by decide, c1309_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c1309_b5, by decide, c1309_ok5⟩, ?_⟩
  simp

def s30 : List Nat := [75011955393483046912, 79551583817872506880, 73931091482914390016, 78470719907303849984, 83010348331693309952, 1297036692699545600, 5836665117089005568, 10376293541478465536, 4755801206520348672, 9295429630909808640]
theorem e30 : enumKeys 780 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 358, c1309_b7, by decide, c1309_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 358, c1309_b6, by decide, c1309_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1310_b3, by decide, c1310_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1310_b2, by decide, c1310_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1310_b1, by decide, c1310_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1310_b0, by decide, c1310_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1309_b9, by decide, c1309_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c1309_b8, by decide, c1309_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1310_b5, by decide, c1310_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c1310_b4, by decide, c1310_ok4⟩, ?_⟩
  simp

def s31 : List Nat := [73931091482914193408, 78470719907303653376, 92305777962585817088, 96845406386975277056, 4755801206520152064, 18590859261802315776, 23130487686191775744]
theorem e31 : enumKeys 780 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c1310_b9, by decide, c1310_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c1310_b8, by decide, c1310_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c1310_b7, by decide, c1310_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1310_b6, by decide, c1310_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1311_b2, by decide, c1311_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1311_b1, by decide, c1311_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1311_b0, by decide, c1311_ok0⟩, ?_⟩
  simp

def s32 : List Nat := [295292020367428812800, 299831648791818272768, 304371277216207732736, 4755801206570483712, 9295429630959943680]
theorem e32 : enumKeys 780 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1311_b5, by decide, c1311_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c1311_b4, by decide, c1311_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1311_b3, by decide, c1311_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1311_b7, by decide, c1311_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c1311_b6, by decide, c1311_ok6⟩, ?_⟩
  simp

def s33 : List Nat := [1297036692682833920, 5836665117072293888, 10376293541461753856, 4755801206503636992, 9295429630893096960, 13835058055282556928]
theorem e33 : enumKeys 780 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1312_b0, by decide, c1312_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c1311_b9, by decide, c1311_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c1311_b8, by decide, c1311_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1312_b3, by decide, c1312_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1312_b2, by decide, c1312_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1312_b1, by decide, c1312_ok1⟩, ?_⟩
  simp

def s34 : List Nat := [4755801206503440384, 9295429630892900352, 18590859261785604096, 23130487686175064064, 27670116110564524032]
theorem e34 : enumKeys 780 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c1312_b8, by decide, c1312_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c1312_b6, by decide, c1312_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1312_b7, by decide, c1312_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1312_b5, by decide, c1312_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1312_b4, by decide, c1312_ok4⟩, ?_⟩
  simp

def s35 : List Nat := [221360928884514619392, 147646010183731118080, 73931091482947616768, 216172782164115456]
theorem e35 : enumKeys 780 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1312_b9, by decide, c1312_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c1313_b0, by decide, c1313_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c1313_b1, by decide, c1313_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c1313_b2, by decide, c1313_ok2⟩, ?_⟩
  simp

def s36 : List Nat := [147646010183714406400, 152185638608103866368, 73931091482930905088, 78470719907320365056, 216172782147403776, 4755801206536863744]
theorem e36 : enumKeys 780 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c1313_b4, by decide, c1313_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1313_b3, by decide, c1313_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c1313_b6, by decide, c1313_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c1313_b5, by decide, c1313_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1313_b8, by decide, c1313_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c1313_b7, by decide, c1313_ok7⟩, ?_⟩
  simp

def s37 : List Nat := [73931091482914193408, 78470719907303653376, 83010348331693113344, 216172782130692096, 4755801206520152064, 9295429630909612032]
theorem e37 : enumKeys 780 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c1314_b1, by decide, c1314_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c1314_b0, by decide, c1314_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1313_b9, by decide, c1313_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1314_b4, by decide, c1314_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c1314_b3, by decide, c1314_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c1314_b2, by decide, c1314_ok2⟩, ?_⟩
  simp

def s38 : List Nat := [216172782113980416, 4755801206503440384, 9295429630892900352, 13835058055282360320]
theorem e38 : enumKeys 780 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1314_b8, by decide, c1314_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c1314_b7, by decide, c1314_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c1314_b6, by decide, c1314_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c1314_b5, by decide, c1314_ok5⟩, ?_⟩
  simp

/-- every enumerated key with left type `780` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 780 mR,
    (780 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K12
end Grid3.Three.Cert
