import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0255
import Grid3.Three.Cert.Data.C0256
import Grid3.Three.Cert.Data.C0257
import Grid3.Three.Cert.Data.C0258

/-! Seam keys with left type `780` (type index 12): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K12

theorem tL : rtype 780 = 780 := by decide

def s00 : List Nat := [885443715538058477568, 590295810358772760576, 295147905179487043584, 201326592]
theorem e00 : enumKeys 780 12288 = s00 := by decide +kernel
theorem t00 : rtype 12288 = 12288 := by decide
theorem r00 : ∀ M ∈ s00, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 12288 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 12288) (rM M) ne blob = true) := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 144, c0255_b37, by decide, c0255_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 182, c0255_b36, by decide, c0255_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 208, c0255_b35, by decide, c0255_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0255_b34, by decide, c0255_ok34⟩, ?_⟩
  simp

def s01 : List Nat := [370087802978797879296, 387381625547900846080, 314747570757686001664, 313594649253079416832, 93386641873221713920, 92233720368615129088, 19599665578400284672, 18446744073793699840]
theorem e01 : enumKeys 780 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 285, c0256_b3, by decide, c0256_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0256_b2, by decide, by rw [tL, t01, show rM 387381625547900846080 = 314747570757686001664 by decide]; exact c0256_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0256_b2, by decide, c0256_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0256_b1, by decide, c0256_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0256_b0, by decide, c0256_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 230, c0255_b39, by decide, by rw [tL, t01, show rM 92233720368615129088 = 19599665578400284672 by decide]; exact c0255_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0255_b39, by decide, c0255_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0255_b38, by decide, c0255_ok38⟩, ?_⟩
  simp

def s02 : List Nat := [591448731863312498688, 594907496377133301760, 300912512702454169600, 299759591197847584768, 5764607523168452608, 4611686018561867776]
theorem e02 : enumKeys 780 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0256_b8, by decide, c0256_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0256_b9, by decide, c0256_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0256_b7, by decide, c0256_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0256_b6, by decide, c0256_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0256_b5, by decide, c0256_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0256_b4, by decide, c0256_ok4⟩, ?_⟩
  simp

def s03 : List Nat := [76092819304051900416, 79551583817872703488, 93386641873154867200, 96845406386975670272, 6917529027657859072, 20752587082940022784, 24211351596760825856, 23058430092154241024]
theorem e03 : enumKeys 780 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 366, c0256_b14, by decide, c0256_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 316, c0256_b15, by decide, c0256_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0256_b16, by decide, c0256_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0256_b17, by decide, c0256_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 310, c0256_b10, by decide, c0256_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0256_b11, by decide, c0256_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0256_b13, by decide, c0256_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0256_b12, by decide, c0256_ok12⟩, ?_⟩
  simp

def s04 : List Nat := [297453748188566519808, 300912512702387322880, 304371277216208125952, 6917529027708190720, 10376293541528993792, 9223372036922408960]
theorem e04 : enumKeys 780 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0256_b21, by decide, c0256_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0256_b22, by decide, c0256_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0256_b23, by decide, c0256_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 280, c0256_b18, by decide, c0256_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0256_b20, by decide, c0256_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0256_b19, by decide, c0256_ok19⟩, ?_⟩
  simp

def s05 : List Nat := [3458764513820540928, 6917529027641344000, 10376293541462147072, 13835058055282950144]
theorem e05 : enumKeys 780 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0256_b24, by decide, c0256_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 304, c0256_b25, by decide, c0256_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0256_b26, by decide, c0256_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0256_b27, by decide, c0256_ok27⟩, ?_⟩
  simp

def s06 : List Nat := [608742554432415268864, 313594649253129551872, 18446744073843834880]
theorem e06 : enumKeys 780 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0256_b30, by decide, c0256_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 205, c0256_b29, by decide, c0256_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0256_b28, by decide, c0256_ok28⟩, ?_⟩
  simp

def s07 : List Nat := [93386641873154670592, 110680464442257637376, 38046409652042792960, 36893488147436208128]
theorem e07 : enumKeys 780 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0256_b33, by decide, c0256_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0256_b32, by decide, by rw [tL, t07, show rM 110680464442257637376 = 38046409652042792960 by decide]; exact c0256_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0256_b32, by decide, c0256_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0256_b31, by decide, c0256_ok31⟩, ?_⟩
  simp

def s08 : List Nat := [300912512702387126272, 314747570757669289984, 318206335271490093056, 24211351596810960896, 23058430092204376064]
theorem e08 : enumKeys 780 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 278, c0256_b36, by decide, c0256_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0256_b37, by decide, c0256_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0256_b38, by decide, c0256_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0256_b35, by decide, c0256_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0256_b34, by decide, c0256_ok34⟩, ?_⟩
  simp

def s09 : List Nat := [6917529027641147392, 20752587082923311104, 10376293541461950464, 24211351596744114176, 27670116110564917248]
theorem e09 : enumKeys 780 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 352, c0256_b39, by decide, c0256_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0257_b1, by decide, c0257_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0257_b0, by decide, c0257_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0257_b2, by decide, c0257_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0257_b3, by decide, c0257_ok3⟩, ?_⟩
  simp

def s10 : List Nat := [332041393326772060160, 36893488147486343168]
theorem e10 : enumKeys 780 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0257_b5, by decide, c0257_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0257_b4, by decide, c0257_ok4⟩, ?_⟩
  simp

def s11 : List Nat := [24211351596743917568, 38046409652026081280, 41505174165846884352]
theorem e11 : enumKeys 780 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 301, c0257_b6, by decide, c0257_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0257_b7, by decide, c0257_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0257_b8, by decide, c0257_ok8⟩, ?_⟩
  simp

def s12 : List Nat := [55340232221128851456]
theorem e12 : enumKeys 780 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0257_b9, by decide, c0257_ok9⟩, ?_⟩
  simp

def s13 : List Nat := [664082786653543858176, 590367867952760356864, 369006939068296069120, 295219962773474639872, 73859033889010352128, 72057594188922880]
theorem e13 : enumKeys 780 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0256_b8, by decide, by rw [tL, t13, show rM 664082786653543858176 = 591448731863312498688 by decide]; exact c0256_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0256_b9, by decide, by rw [tL, t13, show rM 590367867952760356864 = 594907496377133301760 by decide]; exact c0256_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 212, c0256_b7, by decide, by rw [tL, t13, show rM 369006939068296069120 = 300912512702454169600 by decide]; exact c0256_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 200, c0256_b6, by decide, by rw [tL, t13, show rM 295219962773474639872 = 299759591197847584768 by decide]; exact c0256_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 244, c0256_b5, by decide, by rw [tL, t13, show rM 73859033889010352128 = 5764607523168452608 by decide]; exact c0256_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0256_b4, by decide, by rw [tL, t13, show rM 72057594188922880 = 4611686018561867776 by decide]; exact c0256_ok4⟩, ?_⟩
  simp

def s14 : List Nat := [148726874094283259904, 147646010183714603008, 166020696663386226688, 75011955393499758592, 93386641873171382272, 92305777962602725376, 19671723172387880960, 18518801667781296128]
theorem e14 : enumKeys 780 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 366, c0256_b14, by decide, by rw [tL, t14, show rM 148726874094283259904 = 76092819304051900416 by decide]; exact c0256_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 310, c0256_b10, by decide, by rw [tL, t14, show rM 147646010183714603008 = 6917529027657859072 by decide]; exact c0256_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0256_b11, by decide, by rw [tL, t14, show rM 166020696663386226688 = 20752587082940022784 by decide]; exact c0256_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 316, c0256_b15, by decide, by rw [tL, t14, show rM 75011955393499758592 = 79551583817872703488 by decide]; exact c0256_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0256_b16, by decide, by rw [tL, t14, show rM 93386641873171382272 = 93386641873154867200 by decide]; exact c0256_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 217, c0256_b13, by decide, by rw [tL, t14, show rM 92305777962602725376 = 24211351596760825856 by decide]; exact c0256_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0256_b17, by decide, by rw [tL, t14, show rM 19671723172387880960 = 96845406386975670272 by decide]; exact c0256_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0256_b12, by decide, by rw [tL, t14, show rM 18518801667781296128 = 23058430092154241024 by decide]; exact c0256_ok12⟩, ?_⟩
  simp

def s15 : List Nat := [370087802978797879296, 369006939068229222400, 373546567492618682368, 296372884278014377984, 300912512702403837952, 299831648791835181056, 75011955393550090240, 79551583817939550208, 78470719907370893312, 5836665117156048896, 4683743612549464064]
theorem e15 : enumKeys 780 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 285, c0257_b16, by decide, c0257_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0257_b15, by decide, by rw [tL, t15, show rM 369006939068229222400 = 300912512702403837952 by decide]; exact c0257_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0257_b13, by decide, by rw [tL, t15, show rM 373546567492618682368 = 296372884278014377984 by decide]; exact c0257_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0257_b13, by decide, c0257_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0257_b15, by decide, c0257_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0257_b14, by decide, c0257_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 286, c0257_b12, by decide, c0257_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 286, c0257_b12, by decide, by rw [tL, t15, show rM 79551583817939550208 = 75011955393550090240 by decide]; exact c0257_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 230, c0257_b11, by decide, by rw [tL, t15, show rM 78470719907370893312 = 5836665117156048896 by decide]; exact c0257_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0257_b11, by decide, c0257_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0257_b10, by decide, c0257_ok10⟩, ?_⟩
  simp

def s16 : List Nat := [76092819304051900416, 75011955393483243520, 79551583817872703488, 78470719907304046592, 83010348331693506560, 2377900603268399104, 6917529027657859072, 5836665117089202176, 10376293541478662144, 9295429630910005248]
theorem e16 : enumKeys 780 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 366, c0257_b23, by decide, c0257_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 310, c0257_b22, by decide, c0257_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 316, c0257_b25, by decide, c0257_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 260, c0257_b24, by decide, c0257_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0257_b26, by decide, c0257_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0257_b17, by decide, c0257_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 310, c0257_b19, by decide, c0257_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 254, c0257_b18, by decide, c0257_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 260, c0257_b21, by decide, c0257_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0257_b20, by decide, c0257_ok20⟩, ?_⟩
  simp

def s17 : List Nat := [369006939068229025792, 387381625547900649472, 313666706847117148160, 92305777962652860416, 18518801667831431168]
theorem e17 : enumKeys 780 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 278, c0256_b36, by decide, by rw [tL, t17, show rM 369006939068229025792 = 300912512702387126272 by decide]; exact c0256_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0256_b37, by decide, by rw [tL, t17, show rM 387381625547900649472 = 314747570757669289984 by decide]; exact c0256_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0256_b38, by decide, by rw [tL, t17, show rM 313666706847117148160 = 318206335271490093056 by decide]; exact c0256_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 235, c0256_b35, by decide, by rw [tL, t17, show rM 92305777962652860416 = 24211351596810960896 by decide]; exact c0256_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0256_b34, by decide, by rw [tL, t17, show rM 18518801667831431168 = 23058430092204376064 by decide]; exact c0256_ok34⟩, ?_⟩
  simp

def s18 : List Nat := [590367867952743645184, 594907496377133105152, 299831648791885316096, 4683743612599599104]
theorem e18 : enumKeys 780 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0257_b29, by decide, c0257_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0257_b29, by decide, by rw [tL, t18, show rM 594907496377133105152 = 590367867952743645184 by decide]; exact c0257_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 205, c0257_b28, by decide, c0257_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0257_b27, by decide, c0257_ok27⟩, ?_⟩
  simp

def s19 : List Nat := [75011955393483046912, 79551583817872506880, 93386641873154670592, 78470719907303849984, 92305777962586013696, 96845406386975473664, 5836665117089005568, 19671723172371169280, 24211351596760629248, 23130487686191972352]
theorem e19 : enumKeys 780 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 358, c0257_b34, by decide, c0257_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 358, c0257_b34, by decide, by rw [tL, t19, show rM 79551583817872506880 = 75011955393483046912 by decide]; exact c0257_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0257_b35, by decide, c0257_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 302, c0257_b30, by decide, by rw [tL, t19, show rM 78470719907303849984 = 5836665117089005568 by decide]; exact c0257_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 259, c0257_b33, by decide, by rw [tL, t19, show rM 92305777962586013696 = 24211351596760629248 by decide]; exact c0257_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0257_b31, by decide, by rw [tL, t19, show rM 96845406386975473664 = 19671723172371169280 by decide]; exact c0257_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 302, c0257_b30, by decide, c0257_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0257_b31, by decide, c0257_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0257_b33, by decide, c0257_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0257_b32, by decide, c0257_ok32⟩, ?_⟩
  simp

def s20 : List Nat := [296372884277997666304, 300912512702387126272, 299831648791818469376, 304371277216207929344, 5836665117139337216, 10376293541528797184, 9295429630960140288]
theorem e20 : enumKeys 780 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0257_b39, by decide, c0257_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 278, c0258_b1, by decide, c0258_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0258_b0, by decide, c0258_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0258_b2, by decide, c0258_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 272, c0257_b36, by decide, c0257_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 278, c0257_b38, by decide, c0257_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0257_b37, by decide, c0257_ok37⟩, ?_⟩
  simp

def s21 : List Nat := [2377900603251687424, 6917529027641147392, 5836665117072490496, 10376293541461950464, 9295429630893293568, 13835058055282753536]
theorem e21 : enumKeys 780 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0258_b3, by decide, c0258_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 352, c0258_b5, by decide, c0258_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 296, c0258_b4, by decide, c0258_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0258_b7, by decide, c0258_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0258_b6, by decide, c0258_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0258_b8, by decide, c0258_ok8⟩, ?_⟩
  simp

def s22 : List Nat := [92305777962585817088, 110680464442257440768, 36965545741473939456]
theorem e22 : enumKeys 780 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 301, c0257_b6, by decide, by rw [tL, t22, show rM 92305777962585817088 = 24211351596743917568 by decide]; exact c0257_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0257_b7, by decide, by rw [tL, t22, show rM 110680464442257440768 = 38046409652026081280 by decide]; exact c0257_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0257_b8, by decide, by rw [tL, t22, show rM 36965545741473939456 = 41505174165846884352 by decide]; exact c0257_ok8⟩, ?_⟩
  simp

def s23 : List Nat := [299831648791818272768, 313666706847100436480, 318206335271489896448, 23130487686242107392]
theorem e23 : enumKeys 780 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0258_b10, by decide, c0258_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0258_b11, by decide, c0258_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0258_b11, by decide, by rw [tL, t23, show rM 318206335271489896448 = 313666706847100436480 by decide]; exact c0258_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0258_b9, by decide, c0258_ok9⟩, ?_⟩
  simp

def s24 : List Nat := [5836665117072293888, 10376293541461753856, 19671723172354457600, 24211351596743917568, 9295429630893096960, 23130487686175260672, 27670116110564720640]
theorem e24 : enumKeys 780 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 344, c0258_b12, by decide, c0258_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 350, c0258_b14, by decide, c0258_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0258_b15, by decide, c0258_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 301, c0258_b17, by decide, c0258_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0258_b13, by decide, c0258_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0258_b16, by decide, c0258_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0258_b18, by decide, c0258_ok18⟩, ?_⟩
  simp

def s25 : List Nat := [23130487686175064064, 36965545741457227776, 41505174165846687744]
theorem e25 : enumKeys 780 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0258_b19, by decide, c0258_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0258_b20, by decide, c0258_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0258_b20, by decide, by rw [tL, t25, show rM 41505174165846687744 = 36965545741457227776 by decide]; exact c0258_ok20⟩, ?_⟩
  simp

def s26 : List Nat := [442721857769029238784, 369006939068245737472, 295292020367462236160, 147646010183781449728, 73931091482997948416, 144115188176519168]
theorem e26 : enumKeys 780 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0256_b21, by decide, by rw [tL, t26, show rM 442721857769029238784 = 297453748188566519808 by decide]; exact c0256_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0256_b22, by decide, by rw [tL, t26, show rM 369006939068245737472 = 300912512702387322880 by decide]; exact c0256_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0256_b23, by decide, by rw [tL, t26, show rM 295292020367462236160 = 304371277216208125952 by decide]; exact c0256_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 280, c0256_b18, by decide, by rw [tL, t26, show rM 147646010183781449728 = 6917529027708190720 by decide]; exact c0256_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0256_b20, by decide, by rw [tL, t26, show rM 73931091482997948416 = 10376293541528993792 by decide]; exact c0256_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0256_b19, by decide, by rw [tL, t26, show rM 144115188176519168 = 9223372036922408960 by decide]; exact c0256_ok19⟩, ?_⟩
  simp

def s27 : List Nat := [148726874094283259904, 147646010183714603008, 152185638608104062976, 75011955393499758592, 79551583817889218560, 73931091482931101696, 78470719907320561664, 1297036692716257280, 5836665117105717248, 4755801206537060352]
theorem e27 : enumKeys 780 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 366, c0257_b23, by decide, by rw [tL, t27, show rM 148726874094283259904 = 76092819304051900416 by decide]; exact c0257_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 310, c0257_b19, by decide, by rw [tL, t27, show rM 147646010183714603008 = 6917529027657859072 by decide]; exact c0257_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0257_b17, by decide, by rw [tL, t27, show rM 152185638608104062976 = 2377900603268399104 by decide]; exact c0257_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 316, c0257_b25, by decide, by rw [tL, t27, show rM 75011955393499758592 = 79551583817872703488 by decide]; exact c0257_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 310, c0257_b22, by decide, by rw [tL, t27, show rM 79551583817889218560 = 75011955393483243520 by decide]; exact c0257_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 260, c0257_b21, by decide, by rw [tL, t27, show rM 73931091482931101696 = 10376293541478662144 by decide]; exact c0257_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 254, c0257_b18, by decide, by rw [tL, t27, show rM 78470719907320561664 = 5836665117089202176 by decide]; exact c0257_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0257_b26, by decide, by rw [tL, t27, show rM 1297036692716257280 = 83010348331693506560 by decide]; exact c0257_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 260, c0257_b24, by decide, by rw [tL, t27, show rM 5836665117105717248 = 78470719907304046592 by decide]; exact c0257_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0257_b20, by decide, by rw [tL, t27, show rM 4755801206537060352 = 9295429630910005248 by decide]; exact c0257_ok20⟩, ?_⟩
  simp

def s28 : List Nat := [147646010183714406400, 166020696663386030080, 73931091482930905088, 92305777962602528768, 18590859261819027456]
theorem e28 : enumKeys 780 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 352, c0256_b39, by decide, by rw [tL, t28, show rM 147646010183714406400 = 6917529027641147392 by decide]; exact c0256_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0257_b1, by decide, by rw [tL, t28, show rM 166020696663386030080 = 20752587082923311104 by decide]; exact c0257_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 308, c0257_b0, by decide, by rw [tL, t28, show rM 73931091482930905088 = 10376293541461950464 by decide]; exact c0257_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 259, c0257_b2, by decide, by rw [tL, t28, show rM 92305777962602528768 = 24211351596744114176 by decide]; exact c0257_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0257_b3, by decide, by rw [tL, t28, show rM 18590859261819027456 = 27670116110564917248 by decide]; exact c0257_ok3⟩, ?_⟩
  simp

def s29 : List Nat := [369006939068229025792, 373546567492618485760, 295292020367445524480, 299831648791834984448, 73931091482981236736, 78470719907370696704, 4755801206587195392]
theorem e29 : enumKeys 780 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 278, c0258_b1, by decide, by rw [tL, t29, show rM 369006939068229025792 = 300912512702387126272 by decide]; exact c0258_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0257_b39, by decide, by rw [tL, t29, show rM 373546567492618485760 = 296372884277997666304 by decide]; exact c0257_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0258_b2, by decide, by rw [tL, t29, show rM 295292020367445524480 = 304371277216207929344 by decide]; exact c0258_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 229, c0258_b0, by decide, by rw [tL, t29, show rM 299831648791834984448 = 299831648791818469376 by decide]; exact c0258_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 278, c0257_b38, by decide, by rw [tL, t29, show rM 73931091482981236736 = 10376293541528797184 by decide]; exact c0257_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 272, c0257_b36, by decide, by rw [tL, t29, show rM 78470719907370696704 = 5836665117139337216 by decide]; exact c0257_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0257_b37, by decide, by rw [tL, t29, show rM 4755801206587195392 = 9295429630960140288 by decide]; exact c0257_ok37⟩, ?_⟩
  simp

def s30 : List Nat := [75011955393483046912, 79551583817872506880, 73931091482914390016, 78470719907303849984, 83010348331693309952, 1297036692699545600, 5836665117089005568, 10376293541478465536, 4755801206520348672, 9295429630909808640]
theorem e30 : enumKeys 780 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 358, c0258_b25, by decide, c0258_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 358, c0258_b25, by decide, by rw [tL, t30, show rM 79551583817872506880 = 75011955393483046912 by decide]; exact c0258_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 302, c0258_b24, by decide, by rw [tL, t30, show rM 73931091482914390016 = 10376293541478465536 by decide]; exact c0258_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 302, c0258_b23, by decide, by rw [tL, t30, show rM 78470719907303849984 = 5836665117089005568 by decide]; exact c0258_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0258_b21, by decide, by rw [tL, t30, show rM 83010348331693309952 = 1297036692699545600 by decide]; exact c0258_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0258_b21, by decide, c0258_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 302, c0258_b23, by decide, c0258_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 302, c0258_b24, by decide, c0258_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0258_b22, by decide, c0258_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 246, c0258_b22, by decide, by rw [tL, t30, show rM 9295429630909808640 = 4755801206520348672 by decide]; exact c0258_ok22⟩, ?_⟩
  simp

def s31 : List Nat := [73931091482914193408, 78470719907303653376, 92305777962585817088, 96845406386975277056, 4755801206520152064, 18590859261802315776, 23130487686191775744]
theorem e31 : enumKeys 780 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 350, c0258_b14, by decide, by rw [tL, t31, show rM 73931091482914193408 = 10376293541461753856 by decide]; exact c0258_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 344, c0258_b12, by decide, by rw [tL, t31, show rM 78470719907303653376 = 5836665117072293888 by decide]; exact c0258_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 301, c0258_b17, by decide, by rw [tL, t31, show rM 92305777962585817088 = 24211351596743917568 by decide]; exact c0258_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0258_b15, by decide, by rw [tL, t31, show rM 96845406386975277056 = 19671723172354457600 by decide]; exact c0258_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 294, c0258_b13, by decide, by rw [tL, t31, show rM 4755801206520152064 = 9295429630893096960 by decide]; exact c0258_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0258_b18, by decide, by rw [tL, t31, show rM 18590859261802315776 = 27670116110564720640 by decide]; exact c0258_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0258_b16, by decide, by rw [tL, t31, show rM 23130487686191775744 = 23130487686175260672 by decide]; exact c0258_ok16⟩, ?_⟩
  simp

def s32 : List Nat := [295292020367428812800, 299831648791818272768, 304371277216207732736, 4755801206570483712, 9295429630959943680]
theorem e32 : enumKeys 780 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0258_b27, by decide, c0258_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0258_b28, by decide, c0258_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0258_b27, by decide, by rw [tL, t32, show rM 304371277216207732736 = 295292020367428812800 by decide]; exact c0258_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0258_b26, by decide, c0258_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0258_b26, by decide, by rw [tL, t32, show rM 9295429630959943680 = 4755801206570483712 by decide]; exact c0258_ok26⟩, ?_⟩
  simp

def s33 : List Nat := [1297036692682833920, 5836665117072293888, 10376293541461753856, 4755801206503636992, 9295429630893096960, 13835058055282556928]
theorem e33 : enumKeys 780 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0258_b29, by decide, c0258_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 344, c0258_b31, by decide, c0258_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 350, c0258_b33, by decide, c0258_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0258_b30, by decide, c0258_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0258_b32, by decide, c0258_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0258_b34, by decide, c0258_ok34⟩, ?_⟩
  simp

def s34 : List Nat := [4755801206503440384, 9295429630892900352, 18590859261785604096, 23130487686175064064, 27670116110564524032]
theorem e34 : enumKeys 780 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 336, c0258_b35, by decide, c0258_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 336, c0258_b35, by decide, by rw [tL, t34, show rM 9295429630892900352 = 4755801206503440384 by decide]; exact c0258_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0258_b36, by decide, c0258_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0258_b37, by decide, c0258_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0258_b36, by decide, by rw [tL, t34, show rM 27670116110564524032 = 18590859261785604096 by decide]; exact c0258_ok36⟩, ?_⟩
  simp

def s35 : List Nat := [221360928884514619392, 147646010183731118080, 73931091482947616768, 216172782164115456]
theorem e35 : enumKeys 780 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0256_b24, by decide, by rw [tL, t35, show rM 221360928884514619392 = 3458764513820540928 by decide]; exact c0256_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 304, c0256_b25, by decide, by rw [tL, t35, show rM 147646010183731118080 = 6917529027641344000 by decide]; exact c0256_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0256_b26, by decide, by rw [tL, t35, show rM 73931091482947616768 = 10376293541462147072 by decide]; exact c0256_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0256_b27, by decide, by rw [tL, t35, show rM 216172782164115456 = 13835058055282950144 by decide]; exact c0256_ok27⟩, ?_⟩
  simp

def s36 : List Nat := [147646010183714406400, 152185638608103866368, 73931091482930905088, 78470719907320365056, 216172782147403776, 4755801206536863744]
theorem e36 : enumKeys 780 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 352, c0258_b5, by decide, by rw [tL, t36, show rM 147646010183714406400 = 6917529027641147392 by decide]; exact c0258_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0258_b3, by decide, by rw [tL, t36, show rM 152185638608103866368 = 2377900603251687424 by decide]; exact c0258_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 308, c0258_b7, by decide, by rw [tL, t36, show rM 73931091482930905088 = 10376293541461950464 by decide]; exact c0258_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 296, c0258_b4, by decide, by rw [tL, t36, show rM 78470719907320365056 = 5836665117072490496 by decide]; exact c0258_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0258_b8, by decide, by rw [tL, t36, show rM 216172782147403776 = 13835058055282753536 by decide]; exact c0258_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0258_b6, by decide, by rw [tL, t36, show rM 4755801206536863744 = 9295429630893293568 by decide]; exact c0258_ok6⟩, ?_⟩
  simp

def s37 : List Nat := [73931091482914193408, 78470719907303653376, 83010348331693113344, 216172782130692096, 4755801206520152064, 9295429630909612032]
theorem e37 : enumKeys 780 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 350, c0258_b33, by decide, by rw [tL, t37, show rM 73931091482914193408 = 10376293541461753856 by decide]; exact c0258_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 344, c0258_b31, by decide, by rw [tL, t37, show rM 78470719907303653376 = 5836665117072293888 by decide]; exact c0258_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0258_b29, by decide, by rw [tL, t37, show rM 83010348331693113344 = 1297036692682833920 by decide]; exact c0258_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0258_b34, by decide, by rw [tL, t37, show rM 216172782130692096 = 13835058055282556928 by decide]; exact c0258_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 294, c0258_b32, by decide, by rw [tL, t37, show rM 4755801206520152064 = 9295429630893096960 by decide]; exact c0258_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0258_b30, by decide, by rw [tL, t37, show rM 9295429630909612032 = 4755801206503636992 by decide]; exact c0258_ok30⟩, ?_⟩
  simp

def s38 : List Nat := [216172782113980416, 4755801206503440384, 9295429630892900352, 13835058055282360320]
theorem e38 : enumKeys 780 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0258_b38, by decide, c0258_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 336, c0258_b39, by decide, c0258_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 336, c0258_b39, by decide, by rw [tL, t38, show rM 9295429630892900352 = 4755801206503440384 by decide]; exact c0258_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0258_b38, by decide, by rw [tL, t38, show rM 13835058055282360320 = 216172782113980416 by decide]; exact c0258_ok38⟩, ?_⟩
  simp

/-- every enumerated key with left type `780` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 780 mR,
    (780 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 780 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 780) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K12
end Grid3.Three.Cert
