import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C2602
import Grid3.Three.Cert.Data.C2603
import Grid3.Three.Cert.Data.C2604
import Grid3.Three.Cert.Data.C2605
import Grid3.Three.Cert.Data.C2606
import Grid3.Three.Cert.Data.C2607
import Grid3.Three.Cert.Data.C2608
import Grid3.Three.Cert.Data.C2609
import Grid3.Three.Cert.Data.C2610
import Grid3.Three.Cert.Data.C2611
import Grid3.Three.Cert.Data.C2612
import Grid3.Three.Cert.Data.C2613
import Grid3.Three.Cert.Data.C2614
import Grid3.Three.Cert.Data.C2615
import Grid3.Three.Cert.Data.C2616
import Grid3.Three.Cert.Data.C2617
import Grid3.Three.Cert.Data.C2618
import Grid3.Three.Cert.Data.C2619
import Grid3.Three.Cert.Data.C2620
import Grid3.Three.Cert.Data.C2621
import Grid3.Three.Cert.Data.C2622
import Grid3.Three.Cert.Data.C2623
import Grid3.Three.Cert.Data.C2624
import Grid3.Three.Cert.Data.C2625
import Grid3.Three.Cert.Data.C2626
import Grid3.Three.Cert.Data.C2627
import Grid3.Three.Cert.Data.C2628
import Grid3.Three.Cert.Data.C2629
import Grid3.Three.Cert.Data.C2630
import Grid3.Three.Cert.Data.C2631
import Grid3.Three.Cert.Data.C2632
import Grid3.Three.Cert.Data.C2633
import Grid3.Three.Cert.Data.C2634
import Grid3.Three.Cert.Data.C2635
import Grid3.Three.Cert.Data.C2636
import Grid3.Three.Cert.Data.C2637
import Grid3.Three.Cert.Data.C2638
import Grid3.Three.Cert.Data.C2639
import Grid3.Three.Cert.Data.C2640
import Grid3.Three.Cert.Data.C2641
import Grid3.Three.Cert.Data.C2642
import Grid3.Three.Cert.Data.C2643
import Grid3.Three.Cert.Data.C2644
import Grid3.Three.Cert.Data.C2645
import Grid3.Three.Cert.Data.C2646
import Grid3.Three.Cert.Data.C2647
import Grid3.Three.Cert.Data.C2648
import Grid3.Three.Cert.Data.C2649
import Grid3.Three.Cert.Data.C2650
import Grid3.Three.Cert.Data.C2651
import Grid3.Three.Cert.Data.C2652
import Grid3.Three.Cert.Data.C2653
import Grid3.Three.Cert.Data.C2654
import Grid3.Three.Cert.Data.C2655
import Grid3.Three.Cert.Data.C2656
import Grid3.Three.Cert.Data.C2657
import Grid3.Three.Cert.Data.C2658
import Grid3.Three.Cert.Data.C2659
import Grid3.Three.Cert.Data.C2660
import Grid3.Three.Cert.Data.C2661
import Grid3.Three.Cert.Data.C2662
import Grid3.Three.Cert.Data.C2663
import Grid3.Three.Cert.Data.C2664
import Grid3.Three.Cert.Data.C2665
import Grid3.Three.Cert.Data.C2666
import Grid3.Three.Cert.Data.C2667
import Grid3.Three.Cert.Data.C2668
import Grid3.Three.Cert.Data.C2669
import Grid3.Three.Cert.Data.C2670
import Grid3.Three.Cert.Data.C2671
import Grid3.Three.Cert.Data.C2672
import Grid3.Three.Cert.Data.C2673
import Grid3.Three.Cert.Data.C2674
import Grid3.Three.Cert.Data.C2675

/-! Seam keys with left type `229` (type index 21): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K21

def s00 : List Nat := [54043195528445952, 36029896530591744, 18016597532737536, 36028797086072832, 18015498088218624, 2199090364416, 36028797018968064, 18015498021113856, 2199023259648, 18014398576594944, 1099578740736]
theorem e00 : enumKeys 229 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c2602_b6, by decide, c2602_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c2602_b7, by decide, c2602_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c2602_b8, by decide, c2602_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c2602_b9, by decide, c2602_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c2603_b0, by decide, c2603_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c2603_b1, by decide, c2603_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c2603_b2, by decide, c2603_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c2603_b3, by decide, c2603_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c2603_b4, by decide, c2603_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c2603_b5, by decide, c2603_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c2603_b6, by decide, c2603_ok6⟩, ?_⟩
  simp

def s01 : List Nat := [23643902338662400, 22518071151296512, 19140577589198848, 5630603340808192, 23643898043957248, 22518066856591360, 19140573294493696, 18014742107127808, 5630599046103040, 4504767858737152, 1127274296639488, 19140302728069120, 18014471540703232, 1127003730214912, 5629503896289280, 4503672708923392, 1126179146825728, 23643898043695120, 22518066856329232, 19140573294231568, 18014742106865680, 5630599045840912, 4504767858475024, 1127274296377360, 19140298433101840, 18014467245735952, 1126999435247632, 1168247881744, 5629499601322000, 4503668413956112, 1126174851858448, 343664492560, 22518002431820032, 18014677682356480, 4504703433965824, 22517998137114880, 18014673387651328, 4504699139260672, 1374389797120, 18014402821226752, 1103823372544, 4503603989446912, 279239983360, 5629503829184512, 4503672641818624, 1126179079720960, 5629499534479360, 4503668347113472, 1126174785015808, 343597649920, 1125904218591232, 73031225344]
theorem e01 : enumKeys 229 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2603_b7, by decide, c2603_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2604_b0, by decide, c2604_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2603_b9, by decide, c2603_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2603_b8, by decide, c2603_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2604_b7, by decide, c2604_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2605_b1, by decide, c2605_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2604_b9, by decide, c2604_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2605_b3, by decide, c2605_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2604_b8, by decide, c2604_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2605_b2, by decide, c2605_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2605_b0, by decide, c2605_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2604_b4, by decide, c2604_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c2604_b6, by decide, c2604_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2604_b5, by decide, c2604_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c2604_b1, by decide, c2604_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2604_b3, by decide, c2604_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2604_b2, by decide, c2604_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2607_b4, by decide, c2607_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c2607_b8, by decide, c2607_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c2607_b6, by decide, c2607_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2608_b0, by decide, c2608_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2607_b5, by decide, c2607_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2607_b9, by decide, c2607_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2607_b7, by decide, c2607_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c2608_b5, by decide, c2608_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2608_b7, by decide, c2608_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2608_b6, by decide, c2608_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2608_b8, by decide, c2608_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2608_b1, by decide, c2608_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2608_b3, by decide, c2608_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c2608_b2, by decide, c2608_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2608_b4, by decide, c2608_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2606_b3, by decide, c2606_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c2606_b5, by decide, c2606_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2606_b4, by decide, c2606_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c2607_b0, by decide, c2607_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2607_b2, by decide, c2607_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2607_b1, by decide, c2607_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c2607_b3, by decide, c2607_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c2606_b8, by decide, c2606_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c2606_b9, by decide, c2606_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2606_b6, by decide, c2606_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2606_b7, by decide, c2606_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2605_b4, by decide, c2605_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2605_b6, by decide, c2605_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2605_b5, by decide, c2605_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2605_b9, by decide, c2605_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2606_b1, by decide, c2606_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2606_b0, by decide, c2606_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c2606_b2, by decide, c2606_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2605_b7, by decide, c2605_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c2605_b8, by decide, c2605_ok8⟩, ?_⟩
  simp

def s02 : List Nat := [36310276290641920, 18296977292787712, 36310271995936768, 18296972998082560, 283674000228352, 18295877848268800, 282578850414592, 36310271995674640, 18296972997820432, 283673999966224, 18295873553301520, 282574555447312, 18295877781164032, 282578783309824, 18295873486458880, 282574488604672, 281479338790912]
theorem e02 : enumKeys 229 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2608_b9, by decide, c2608_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2609_b0, by decide, c2609_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2609_b3, by decide, c2609_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2609_b4, by decide, c2609_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c2609_b5, by decide, c2609_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c2609_b1, by decide, c2609_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c2609_b2, by decide, c2609_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2610_b1, by decide, c2610_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2610_b2, by decide, c2610_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2610_b3, by decide, c2610_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2610_b4, by decide, c2610_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2610_b5, by decide, c2610_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2609_b6, by decide, c2609_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c2609_b7, by decide, c2609_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c2609_b9, by decide, c2609_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c2610_b0, by decide, c2610_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2609_b8, by decide, c2609_ok8⟩, ?_⟩
  simp

def s03 : List Nat := [5910983100858368, 5910978806153216, 4785147618787328, 1407654056689664, 1407383490265088, 5910978805891088, 4785147618525200, 1407654056427536, 5910974511185936, 4785143323820048, 1407649761722384, 281818574356496, 1407379195297808, 281548007931920, 4785083194016000, 4785078899310848, 281754149847296, 281483583422720]
theorem e03 : enumKeys 229 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2610_b6, by decide, c2610_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c2610_b8, by decide, c2610_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2611_b0, by decide, c2611_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2610_b9, by decide, c2610_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2610_b7, by decide, c2610_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2611_b5, by decide, c2611_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c2611_b7, by decide, c2611_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2611_b6, by decide, c2611_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2612_b0, by decide, c2612_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2612_b2, by decide, c2612_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2612_b1, by decide, c2612_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2612_b3, by decide, c2612_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2611_b8, by decide, c2611_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2611_b9, by decide, c2611_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2611_b1, by decide, c2611_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c2611_b3, by decide, c2611_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2611_b4, by decide, c2611_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c2611_b2, by decide, c2611_ok2⟩, ?_⟩
  simp

def s04 : List Nat := [18577357052837888, 18577352758132736, 564053760278528, 562958610464768, 18577352757870608, 564053760016400, 18577348463165456, 564049465311248, 562954315497488, 562958543360000, 562954248654848]
theorem e04 : enumKeys 229 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c2612_b4, by decide, c2612_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2612_b6, by decide, c2612_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c2612_b7, by decide, c2612_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2612_b5, by decide, c2612_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2613_b0, by decide, c2613_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c2613_b1, by decide, c2613_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2613_b3, by decide, c2613_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c2613_b4, by decide, c2613_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2613_b2, by decide, c2613_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c2612_b8, by decide, c2612_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c2612_b9, by decide, c2612_ok9⟩, ?_⟩
  simp

def s05 : List Nat := [844433520328704, 844433520066576, 844429225361424]
theorem e05 : enumKeys 229 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c2613_b5, by decide, c2613_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c2613_b6, by decide, c2613_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2613_b7, by decide, c2613_ok7⟩, ?_⟩
  simp

def s06 : List Nat := [37154697999548416, 36028866812182528, 19141399001694208, 37154696925872128, 36028865738506240, 19141397928017920, 18015566740652032, 1128098930163712, 19140299557175296, 18014468369809408, 1127000559321088, 1168298213376, 36028798092706048, 18015499094851840, 36028797019029760, 18015498021175552, 2199023321344, 18014399650332928, 1100652478720, 19140299490070528, 18014468302704640, 1127000492216320, 19140298416394240, 18014467229028352, 1126999418540032, 1168231174144, 1125901047697408, 69860331520]
theorem e06 : enumKeys 229 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2613_b8, by decide, c2613_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c2614_b0, by decide, c2614_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2613_b9, by decide, c2613_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2614_b5, by decide, c2614_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c2614_b8, by decide, c2614_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2614_b6, by decide, c2614_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2614_b9, by decide, c2614_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c2614_b7, by decide, c2614_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c2614_b2, by decide, c2614_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c2614_b4, by decide, c2614_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c2614_b3, by decide, c2614_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c2614_b1, by decide, c2614_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2615_b9, by decide, c2615_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2616_b0, by decide, c2616_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2616_b3, by decide, c2616_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2616_b4, by decide, c2616_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2616_b5, by decide, c2616_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2616_b1, by decide, c2616_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2616_b2, by decide, c2616_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2615_b0, by decide, c2615_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2615_b2, by decide, c2615_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2615_b1, by decide, c2615_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2615_b5, by decide, c2615_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2615_b7, by decide, c2615_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2615_b6, by decide, c2615_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2615_b8, by decide, c2615_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2615_b3, by decide, c2615_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2615_b4, by decide, c2615_ok4⟩, ?_⟩
  simp

def s07 : List Nat := [6755404809764864, 6755403736088576, 5629572548722688, 2252078986625024, 6755400515059712, 5629569327693824, 4503737066586112, 2252075765596160, 1126243504488448, 2251805199171584, 1125972938063872, 6755400514797584, 5629569327431696, 2252075765334032, 6755399441121296, 5629568253755408, 4503737066389520, 2252074691657744, 1126243504291856, 2251800904204304, 1125969716838416, 137455730704, 5629504902922496, 5629503829246208, 4503672641880320, 1126179079782656, 343597449472, 5629500608217344, 4503669420851456, 1126175858753792, 343597646080, 1125905292329216, 69809996032, 73031221504]
theorem e07 : enumKeys 229 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c2616_b6, by decide, c2616_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2617_b4, by decide, c2617_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c2617_b6, by decide, c2617_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2617_b5, by decide, c2617_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2617_b1, by decide, c2617_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c2617_b3, by decide, c2617_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c2617_b0, by decide, c2617_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c2617_b2, by decide, c2617_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c2616_b9, by decide, c2616_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2616_b8, by decide, c2616_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c2616_b7, by decide, c2616_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c2618_b9, by decide, c2618_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c2619_b1, by decide, c2619_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c2619_b0, by decide, c2619_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2619_b5, by decide, c2619_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c2619_b7, by decide, c2619_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2619_b9, by decide, c2619_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c2619_b6, by decide, c2619_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2619_b8, by decide, c2619_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c2619_b3, by decide, c2619_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2619_b4, by decide, c2619_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2619_b2, by decide, c2619_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c2617_b7, by decide, c2617_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2618_b6, by decide, c2618_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2618_b8, by decide, c2618_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2618_b7, by decide, c2618_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c2618_b5, by decide, c2618_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c2618_b2, by decide, c2618_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2618_b4, by decide, c2618_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2618_b3, by decide, c2618_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c2618_b1, by decide, c2618_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c2618_b0, by decide, c2618_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c2617_b9, by decide, c2617_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2617_b8, by decide, c2617_ok8⟩, ?_⟩
  simp

def s08 : List Nat := [19421778761744384, 19421777688068096, 18295946500702208, 1408478690213888, 19421774467039232, 18295943279673344, 1408475469185024, 282643208077312, 1407380319371264, 281548058263552, 19421774466777104, 18295943279411216, 1408475468922896, 19421773393100816, 18295942205734928, 1408474395246608, 282643207880720, 1407376024403984, 281544837038096, 18295878854902016, 18295877781225728, 282578783371520, 18295874560196864, 282575562342656, 281480412528896, 1407380252266496, 1407379178590208, 281547991224320, 1407375957561344, 281544770195456]
theorem e08 : enumKeys 229 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2620_b0, by decide, c2620_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2620_b7, by decide, c2620_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2620_b9, by decide, c2620_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2620_b8, by decide, c2620_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c2620_b4, by decide, c2620_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c2620_b6, by decide, c2620_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c2620_b5, by decide, c2620_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c2620_b3, by decide, c2620_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2620_b2, by decide, c2620_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2620_b1, by decide, c2620_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c2622_b1, by decide, c2622_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2622_b3, by decide, c2622_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2622_b2, by decide, c2622_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2622_b6, by decide, c2622_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2622_b8, by decide, c2622_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2622_b7, by decide, c2622_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2622_b9, by decide, c2622_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2622_b4, by decide, c2622_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2622_b5, by decide, c2622_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2621_b5, by decide, c2621_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2621_b9, by decide, c2621_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c2622_b0, by decide, c2622_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2621_b7, by decide, c2621_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2621_b8, by decide, c2621_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2621_b6, by decide, c2621_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2621_b0, by decide, c2621_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2621_b3, by decide, c2621_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c2621_b4, by decide, c2621_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c2621_b1, by decide, c2621_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2621_b2, by decide, c2621_ok2⟩, ?_⟩
  simp

def s09 : List Nat := [1688858450264064, 1688855229235200, 563022968127488, 1688855228973072, 1688854155296784, 563022967930896, 1688850934267920, 563019746902032, 562958543421696, 562955322392832]
theorem e09 : enumKeys 229 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2623_b2, by decide, c2623_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2623_b1, by decide, c2623_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2623_b0, by decide, c2623_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2623_b5, by decide, c2623_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2623_b8, by decide, c2623_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2623_b9, by decide, c2623_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2623_b6, by decide, c2623_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2623_b7, by decide, c2623_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2623_b4, by decide, c2623_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2623_b3, by decide, c2623_ok3⟩, ?_⟩
  simp

def s10 : List Nat := [20266200470650880, 20266199396974592, 19140368209608704, 18014535948500992, 2252900399120384, 1127068138012672, 2251802028277760, 1125969767170048, 137506062336, 19140300563808512, 19140299490132224, 18014468302766336, 1127000492278016, 1168231170304, 1125902121435392, 69860327680, 2251801961172992, 2251800887496704, 1125969700130816, 137439023104]
theorem e10 : enumKeys 229 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c2624_b0, by decide, c2624_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c2624_b6, by decide, c2624_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c2624_b8, by decide, c2624_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c2624_b5, by decide, c2624_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c2624_b7, by decide, c2624_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c2624_b4, by decide, c2624_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c2624_b3, by decide, c2624_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c2624_b2, by decide, c2624_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c2624_b1, by decide, c2624_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2625_b3, by decide, c2625_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2625_b7, by decide, c2625_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2625_b9, by decide, c2625_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2625_b8, by decide, c2625_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2625_b6, by decide, c2625_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2625_b5, by decide, c2625_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c2625_b4, by decide, c2625_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2624_b9, by decide, c2624_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2625_b1, by decide, c2625_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2625_b2, by decide, c2625_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c2625_b0, by decide, c2625_ok0⟩, ?_⟩
  simp

def s11 : List Nat := [2533280159170560, 1407447898062848, 2533276938141696, 1407444677033984, 281612415926272, 2533276937879568, 2533275864203280, 1407444676837392, 281612415729680, 1407380252328192, 281544769995008, 281547991220480, 1407377031299328, 281544770191616]
theorem e11 : enumKeys 229 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2626_b4, by decide, c2626_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2626_b3, by decide, c2626_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2626_b2, by decide, c2626_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c2626_b1, by decide, c2626_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 320, c2626_b0, by decide, c2626_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2627_b0, by decide, c2627_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2627_b2, by decide, c2627_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2627_b3, by decide, c2627_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c2627_b1, by decide, c2627_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2626_b9, by decide, c2626_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2626_b8, by decide, c2626_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2626_b7, by decide, c2626_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2626_b6, by decide, c2626_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2626_b5, by decide, c2626_ok5⟩, ?_⟩
  simp

def s12 : List Nat := [3377701868077056, 2251869606969344, 1126037345861632, 2251801961234688, 1125969700126976, 137439019264]
theorem e12 : enumKeys 229 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2627_b6, by decide, c2627_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c2627_b5, by decide, c2627_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c2627_b4, by decide, c2627_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2627_b9, by decide, c2627_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c2627_b8, by decide, c2627_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c2627_b7, by decide, c2627_ok7⟩, ?_⟩
  simp

def s13 : List Nat := [40532396914769920, 36029072165306368, 22519097916915712, 36028797304176640, 18015498306322432, 22517998472396800, 18014673722933248, 4504699474542592, 40532396646334465, 36029071896870913, 22519097648480257, 18015772899016705, 4505798650626049, 36028797035741185, 18015498037886977, 2199040032769, 22517998203961345, 18014673454497793, 4504699206107137, 1374456643585, 22517998405292032, 18014673655828480, 4504699407437824, 1374389538816, 18014398794698752, 1099796844544, 4503599962918912, 275213455360]
theorem e13 : enumKeys 229 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2628_b0, by decide, c2628_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2628_b2, by decide, c2628_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c2628_b1, by decide, c2628_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2628_b6, by decide, c2628_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c2628_b7, by decide, c2628_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2628_b3, by decide, c2628_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2628_b5, by decide, c2628_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2628_b4, by decide, c2628_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2629_b6, by decide, c2629_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c2629_b9, by decide, c2629_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c2629_b7, by decide, c2629_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2630_b0, by decide, c2630_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2629_b8, by decide, c2629_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2630_b5, by decide, c2630_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c2630_b6, by decide, c2630_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c2630_b7, by decide, c2630_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2630_b1, by decide, c2630_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2630_b3, by decide, c2630_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2630_b2, by decide, c2630_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2630_b4, by decide, c2630_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c2628_b9, by decide, c2628_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2629_b1, by decide, c2629_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2629_b0, by decide, c2629_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2628_b8, by decide, c2628_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c2629_b4, by decide, c2629_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2629_b5, by decide, c2629_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2629_b2, by decide, c2629_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2629_b3, by decide, c2629_ok3⟩, ?_⟩
  simp

def s14 : List Nat := [10133103724986368, 10133099430281216, 9007268242915328, 5629774680817664, 5629504114393088, 10133103456550913, 9007272269185025, 5629778707087361, 10133099161845761, 9007267974479873, 5629774412382209, 4503943225016321, 1126449662918657, 5629503845957633, 4503672658591745, 1126179096494081, 343614160897, 10133099430019088, 9007268242653200, 5629774680555536, 4503943224754192, 1126449662656528, 5629499819425808, 4503668632059920, 1126175069962256, 343614160912, 9007203818144000, 4503878800244992, 9007199523438848, 4503874773975296, 549756076288, 4503604207550720, 275163119872, 279189651712]
theorem e14 : enumKeys 229 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2630_b8, by decide, c2630_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c2631_b0, by decide, c2631_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2631_b2, by decide, c2631_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2631_b1, by decide, c2631_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2630_b9, by decide, c2630_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2633_b0, by decide, c2633_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c2633_b2, by decide, c2633_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2633_b1, by decide, c2633_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2633_b7, by decide, c2633_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2634_b0, by decide, c2634_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2633_b8, by decide, c2633_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2634_b1, by decide, c2634_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c2633_b9, by decide, c2633_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2633_b4, by decide, c2633_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2633_b6, by decide, c2633_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2633_b5, by decide, c2633_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c2633_b3, by decide, c2633_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2632_b3, by decide, c2632_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2632_b5, by decide, c2632_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2632_b4, by decide, c2632_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2632_b2, by decide, c2632_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c2632_b1, by decide, c2632_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2632_b7, by decide, c2632_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2632_b9, by decide, c2632_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2632_b8, by decide, c2632_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c2632_b6, by decide, c2632_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c2631_b4, by decide, c2631_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c2631_b3, by decide, c2631_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2631_b9, by decide, c2631_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2632_b0, by decide, c2632_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2631_b8, by decide, c2631_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2631_b7, by decide, c2631_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c2631_b6, by decide, c2631_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2631_b5, by decide, c2631_ok5⟩, ?_⟩
  simp

def s15 : List Nat := [22799477676965888, 22799473382260736, 18296148632797184, 4786174384406528, 18295878066372608, 4785079234592768, 22799477408530433, 18296152659066881, 4786178410676225, 22799473113825281, 18296148364361729, 4786174115971073, 282849366507521, 18295877797937153, 282578800082945, 4785078966157313, 281754216693761, 22799473381998608, 18296148632535056, 4786174384144400, 282849366245392, 18295873771405328, 282574773551120, 4785074939625488, 281750190161936, 4785079167488000, 281754149588992, 4785074872782848, 281750123319296, 281479556894720]
theorem e15 : enumKeys 229 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c2634_b2, by decide, c2634_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2634_b5, by decide, c2634_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c2634_b7, by decide, c2634_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c2634_b6, by decide, c2634_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c2634_b4, by decide, c2634_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2634_b3, by decide, c2634_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c2636_b1, by decide, c2636_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2636_b3, by decide, c2636_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c2636_b2, by decide, c2636_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c2636_b8, by decide, c2636_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2637_b0, by decide, c2637_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c2636_b9, by decide, c2636_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c2637_b1, by decide, c2637_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c2636_b6, by decide, c2636_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c2636_b7, by decide, c2636_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2636_b4, by decide, c2636_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2636_b5, by decide, c2636_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2635_b4, by decide, c2635_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2635_b6, by decide, c2635_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2635_b5, by decide, c2635_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2635_b3, by decide, c2635_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c2635_b9, by decide, c2635_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c2636_b0, by decide, c2636_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2635_b7, by decide, c2635_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2635_b8, by decide, c2635_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c2634_b9, by decide, c2634_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2634_b8, by decide, c2634_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c2635_b1, by decide, c2635_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2635_b2, by decide, c2635_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c2635_b0, by decide, c2635_ok0⟩, ?_⟩
  simp

def s16 : List Nat := [5066554144456704, 5066558170726401, 5066553876021249, 563229126557697, 562958560133121, 5066554144194576, 563229126295568, 5066549849489424, 563225100025872, 562954533601296]
theorem e16 : enumKeys 229 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c2637_b2, by decide, c2637_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c2637_b8, by decide, c2637_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c2638_b0, by decide, c2638_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c2638_b1, by decide, c2638_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c2637_b9, by decide, c2637_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c2637_b4, by decide, c2637_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2637_b3, by decide, c2637_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2637_b6, by decide, c2637_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2637_b7, by decide, c2637_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c2637_b5, by decide, c2637_ok5⟩, ?_⟩
  simp

def s17 : List Nat := [23643899385872384, 23643898312196096, 22518067124830208, 19140573562732544, 5630599314341888, 19140299775279104, 18014467514171392, 1126999703683072, 5629500943499264, 4503668682391552, 1126175120293888, 23643899117436929, 22518067930071041, 19140574367973377, 5630600119582721, 23643898043760641, 22518066856394753, 19140573294297089, 18014742106931201, 5630599045906433, 4504767858540545, 1127274296442881, 19140299506843649, 18014468319477761, 1127000508989441, 1168247881729, 5629500675063809, 4503669487697921, 1126175925600257, 343664492545, 22517999479030016, 18014674461131008, 4504700212740352, 22517998405353728, 18014673655890176, 4504699407499520, 1374389600512, 18014399868436736, 1099796840704, 1100602147072, 4503601036656896, 275213451520, 276018757888, 5629500876394496, 4503669420593152, 1126175858495488, 5629499802718208, 4503668615352320, 1126175053254656, 343597453312, 1125901265801216, 69004693504, 69809999872]
theorem e17 : enumKeys 229 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2638_b2, by decide, c2638_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2638_b9, by decide, c2638_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c2639_b2, by decide, c2639_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c2639_b1, by decide, c2639_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c2639_b0, by decide, c2639_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2638_b8, by decide, c2638_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c2638_b7, by decide, c2638_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2638_b6, by decide, c2638_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c2638_b5, by decide, c2638_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c2638_b4, by decide, c2638_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c2638_b3, by decide, c2638_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c2641_b6, by decide, c2641_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c2641_b9, by decide, c2641_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2641_b8, by decide, c2641_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2641_b7, by decide, c2641_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2642_b8, by decide, c2642_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2643_b2, by decide, c2643_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2643_b0, by decide, c2643_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2643_b4, by decide, c2643_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2642_b9, by decide, c2642_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2643_b3, by decide, c2643_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2643_b1, by decide, c2643_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2642_b5, by decide, c2642_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2642_b7, by decide, c2642_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2642_b6, by decide, c2642_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2642_b4, by decide, c2642_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c2642_b1, by decide, c2642_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2642_b3, by decide, c2642_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2642_b2, by decide, c2642_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c2642_b0, by decide, c2642_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c2640_b5, by decide, c2640_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c2640_b4, by decide, c2640_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2640_b3, by decide, c2640_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2641_b3, by decide, c2641_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2641_b5, by decide, c2641_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2641_b4, by decide, c2641_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2641_b2, by decide, c2641_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2641_b1, by decide, c2641_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2641_b0, by decide, c2641_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2640_b9, by decide, c2640_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2640_b8, by decide, c2640_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c2640_b7, by decide, c2640_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2640_b6, by decide, c2640_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2639_b5, by decide, c2639_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2639_b4, by decide, c2639_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c2639_b3, by decide, c2639_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c2640_b0, by decide, c2640_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2640_b2, by decide, c2640_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2640_b1, by decide, c2640_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c2639_b9, by decide, c2639_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2639_b8, by decide, c2639_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c2639_b7, by decide, c2639_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c2639_b6, by decide, c2639_ok6⟩, ?_⟩
  simp

def s18 : List Nat := [36310273337851904, 36310272264175616, 18296973266321408, 18295874895478784, 282574823882752, 36310273069416449, 18296974071562241, 36310271995740161, 18296972997885953, 283674000031745, 18295874627043329, 282575629189121, 18295874828374016, 282575562084352, 18295873754697728, 282574756843520, 281476386000896]
theorem e18 : enumKeys 229 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2643_b5, by decide, c2643_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c2643_b8, by decide, c2643_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2643_b9, by decide, c2643_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2643_b7, by decide, c2643_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c2643_b6, by decide, c2643_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2644_b5, by decide, c2644_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2644_b6, by decide, c2644_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c2644_b9, by decide, c2644_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c2645_b0, by decide, c2645_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c2645_b1, by decide, c2645_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c2644_b7, by decide, c2644_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2644_b8, by decide, c2644_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2644_b1, by decide, c2644_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2644_b0, by decide, c2644_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2644_b3, by decide, c2644_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c2644_b4, by decide, c2644_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2644_b2, by decide, c2644_ok2⟩, ?_⟩
  simp

def s19 : List Nat := [5910979074392064, 5910975853363200, 4785143592255488, 1407650030157824, 1407379463733248, 5910979879632897, 5910978805956609, 4785147618590721, 1407654056493057, 281818574159873, 5910975584927745, 4785144397561857, 1407650835464193, 281818574356481, 1407380269039617, 281544786706433, 281548007931905, 5910975853101072, 4785144397299728, 1407650835202064, 5910974779424784, 4785143592058896, 1407650029961232, 281818574159888, 1407376242507792, 281543981400080, 281544786706448, 4785079972790528, 4785079167549696, 281750123118848, 281754149650688, 4785075946520832, 281750123315456, 281750928621824, 281476335665408, 281479556890880, 281480362197248]
theorem e19 : enumKeys 229 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c2645_b6, by decide, c2645_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2645_b5, by decide, c2645_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c2645_b4, by decide, c2645_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2645_b3, by decide, c2645_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2645_b2, by decide, c2645_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2647_b7, by decide, c2647_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2648_b6, by decide, c2648_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2648_b8, by decide, c2648_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2648_b7, by decide, c2648_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2648_b5, by decide, c2648_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c2648_b2, by decide, c2648_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2648_b4, by decide, c2648_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2648_b3, by decide, c2648_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2648_b1, by decide, c2648_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2648_b0, by decide, c2648_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2647_b9, by decide, c2647_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2647_b8, by decide, c2647_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2646_b9, by decide, c2646_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c2646_b8, by decide, c2646_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c2646_b7, by decide, c2646_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2647_b4, by decide, c2647_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2647_b6, by decide, c2647_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2647_b5, by decide, c2647_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2647_b3, by decide, c2647_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2647_b2, by decide, c2647_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2647_b1, by decide, c2647_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2647_b0, by decide, c2647_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c2645_b7, by decide, c2645_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2646_b6, by decide, c2646_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2646_b5, by decide, c2646_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2646_b4, by decide, c2646_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2646_b3, by decide, c2646_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2646_b2, by decide, c2646_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c2646_b1, by decide, c2646_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2646_b0, by decide, c2646_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2645_b9, by decide, c2645_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c2645_b8, by decide, c2645_ok8⟩, ?_⟩
  simp

def s20 : List Nat := [18577353026371584, 18577349805342720, 564049733746688, 562954583932928, 18577353831612417, 18577352757936129, 564053760081921, 18577349536907265, 564050539053057, 562955389239297, 18577349805080592, 564050538790928, 18577348731404304, 564049733550096, 562951362707472, 562955322134528, 562954516893696, 562951295864832]
theorem e20 : enumKeys 229 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2649_b2, by decide, c2649_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2649_b1, by decide, c2649_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c2649_b0, by decide, c2649_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c2648_b9, by decide, c2648_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2650_b1, by decide, c2650_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c2650_b5, by decide, c2650_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c2650_b6, by decide, c2650_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c2650_b3, by decide, c2650_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c2650_b4, by decide, c2650_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2650_b2, by decide, c2650_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2649_b7, by decide, c2649_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2649_b6, by decide, c2649_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c2649_b9, by decide, c2649_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2650_b0, by decide, c2650_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2649_b8, by decide, c2649_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2649_b3, by decide, c2649_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c2649_b5, by decide, c2649_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2649_b4, by decide, c2649_ok4⟩, ?_⟩
  simp

def s21 : List Nat := [844429493796864, 844433520132097, 844430299103233, 844430298841104, 844429493600272, 844426272571408]
theorem e21 : enumKeys 229 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2650_b7, by decide, c2650_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c2651_b2, by decide, c2651_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2651_b1, by decide, c2651_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2650_b8, by decide, c2650_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c2651_b0, by decide, c2651_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2650_b9, by decide, c2650_ok9⟩, ?_⟩
  simp

def s22 : List Nat := [6755400783298560, 5629568522190848, 2252074960093184, 2251801172639744, 1125968911532032, 6755401588539393, 6755400514863105, 5629569327497217, 4503737066389505, 2252075765399553, 1126243504291841, 2251801977946113, 1125969716838401, 137455730689, 5629501681697024, 5629500876456192, 4503668615348480, 4503669420654848, 1126175053250816, 1126175858557184, 343597449472, 1125901265797376, 1125902071103744, 69004689664, 69809996032]
theorem e22 : enumKeys 229 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c2651_b7, by decide, c2651_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c2651_b6, by decide, c2651_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c2651_b5, by decide, c2651_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 275, c2651_b4, by decide, c2651_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 322, c2651_b3, by decide, c2651_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2652_b9, by decide, c2652_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2653_b5, by decide, c2653_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c2653_b7, by decide, c2653_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2653_b4, by decide, c2653_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2653_b6, by decide, c2653_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2653_b3, by decide, c2653_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2653_b2, by decide, c2653_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c2653_b1, by decide, c2653_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c2653_b0, by decide, c2653_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c2651_b8, by decide, c2651_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c2652_b8, by decide, c2652_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2652_b7, by decide, c2652_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2652_b5, by decide, c2652_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2652_b6, by decide, c2652_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c2652_b4, by decide, c2652_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 297, c2652_b3, by decide, c2652_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c2652_b2, by decide, c2652_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c2652_b0, by decide, c2652_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c2652_b1, by decide, c2652_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c2651_b9, by decide, c2651_ok9⟩, ?_⟩
  simp

def s23 : List Nat := [19421774735278080, 18295942474170368, 1408474663682048, 1407376292839424, 281544031731712, 19421775540518913, 19421774466842625, 18295943279476737, 1408475468988417, 282643207880705, 1407377098145793, 281544837038081, 18295875633676544, 18295874828435712, 282574756839680, 282575562146048, 281476385997056, 281477191303424, 1407377031041024, 1407376225800192, 281543964692480, 281544769998848]
theorem e23 : enumKeys 229 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2654_b2, by decide, c2654_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c2654_b1, by decide, c2654_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c2654_b0, by decide, c2654_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c2653_b9, by decide, c2653_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c2653_b8, by decide, c2653_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2655_b3, by decide, c2655_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c2655_b7, by decide, c2655_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2655_b9, by decide, c2655_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2655_b8, by decide, c2655_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c2655_b6, by decide, c2655_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c2655_b5, by decide, c2655_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c2655_b4, by decide, c2655_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2654_b7, by decide, c2654_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2655_b2, by decide, c2655_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c2655_b1, by decide, c2655_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2655_b0, by decide, c2655_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c2654_b9, by decide, c2654_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2654_b8, by decide, c2654_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2654_b3, by decide, c2654_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2654_b6, by decide, c2654_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c2654_b5, by decide, c2654_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2654_b4, by decide, c2654_ok4⟩, ?_⟩
  simp

def s24 : List Nat := [1688854423732224, 1688851202703360, 563018941595648, 1688855229038593, 563019746705409, 563022967930881, 1688852008009729, 563019746902017, 1688852007747600, 1688851202506768, 563018941399056, 563019746705424, 562951295664384, 562954516889856, 562955322196224, 562951295860992, 562952101167360]
theorem e24 : enumKeys 229 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2656_b2, by decide, c2656_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2656_b1, by decide, c2656_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c2656_b0, by decide, c2656_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2657_b6, by decide, c2657_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2657_b5, by decide, c2657_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2657_b4, by decide, c2657_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2657_b3, by decide, c2657_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2657_b2, by decide, c2657_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2656_b8, by decide, c2656_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2657_b1, by decide, c2657_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2657_b0, by decide, c2657_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2656_b9, by decide, c2656_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2656_b7, by decide, c2656_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2656_b6, by decide, c2656_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c2656_b5, by decide, c2656_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c2656_b4, by decide, c2656_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2656_b3, by decide, c2656_ok3⟩, ?_⟩
  simp

def s25 : List Nat := [2533276132638720, 1407443871531008, 2533276937945089, 1407444676837377, 281612415729665, 1407376225796352, 1407377031102720, 281543964688640, 281544769995008]
theorem e25 : enumKeys 229 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2657_b8, by decide, c2657_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c2657_b7, by decide, c2657_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2658_b5, by decide, c2658_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c2658_b4, by decide, c2658_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c2658_b3, by decide, c2658_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c2658_b2, by decide, c2658_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2658_b0, by decide, c2658_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c2658_b1, by decide, c2658_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c2657_b9, by decide, c2657_ok9⟩, ?_⟩
  simp

def s26 : List Nat := [27021598301093888, 22517998690500608, 9007199858720768, 27021598032658433, 22518273283194881, 18014948265295873, 9008299034804225, 4504974016905217, 22517998422065153, 18014673672601601, 4504699424210945, 1374406311937, 9007199590285313, 4503874840821761, 549822922753, 9007199791616000, 4503874773716992, 549755817984, 4503600181022720, 275163123712]
theorem e26 : enumKeys 229 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2658_b6, by decide, c2658_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c2658_b8, by decide, c2658_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c2658_b7, by decide, c2658_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2659_b6, by decide, c2659_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c2659_b8, by decide, c2659_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2659_b5, by decide, c2659_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2659_b7, by decide, c2659_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2659_b4, by decide, c2659_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c2660_b3, by decide, c2660_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c2660_b5, by decide, c2660_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c2660_b4, by decide, c2660_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2660_b2, by decide, c2660_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2660_b0, by decide, c2660_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2660_b1, by decide, c2660_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2659_b9, by decide, c2659_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2659_b1, by decide, c2659_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2659_b0, by decide, c2659_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2658_b9, by decide, c2658_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2659_b3, by decide, c2659_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2659_b2, by decide, c2659_ok2⟩, ?_⟩
  simp

def s27 : List Nat := [9288674768584704, 9288678794854401, 4785353776955393, 9288674500149249, 4785349750685697, 282024732786689, 4785079184261121, 281750139830273, 281754166362113, 9288674768322576, 4785349750423568, 282024732524560, 4785075157729296, 281750139830288]
theorem e27 : enumKeys 229 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2660_b6, by decide, c2660_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2661_b3, by decide, c2661_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2661_b2, by decide, c2661_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c2661_b8, by decide, c2661_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c2661_b9, by decide, c2661_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c2661_b7, by decide, c2661_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c2661_b6, by decide, c2661_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c2661_b5, by decide, c2661_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c2661_b4, by decide, c2661_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2660_b9, by decide, c2660_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2660_b8, by decide, c2660_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c2660_b7, by decide, c2660_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2661_b1, by decide, c2661_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2661_b0, by decide, c2661_ok0⟩, ?_⟩
  simp

def s28 : List Nat := [10133099698520064, 5629500087861248, 10133100503760897, 9007269047959553, 5629775485861889, 10133099430084609, 9007268242718721, 5629774680621057, 4503943224819713, 1126449662722049, 5629500893167617, 4503668632059905, 4503669437366273, 1126175069962241, 1126175875268609, 343614160897, 9007200596918528, 4503875579019520, 9007199791677696, 4503874773778688, 549755879680, 4503600181018880, 4503600986325248, 275163119872, 275968426240]
theorem e28 : enumKeys 229 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2662_b1, by decide, c2662_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c2662_b0, by decide, c2662_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2663_b3, by decide, c2663_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c2663_b2, by decide, c2663_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c2663_b1, by decide, c2663_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c2664_b2, by decide, c2664_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2664_b4, by decide, c2664_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c2664_b3, by decide, c2664_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2664_b1, by decide, c2664_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2664_b0, by decide, c2664_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2663_b9, by decide, c2663_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c2663_b8, by decide, c2663_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2663_b6, by decide, c2663_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c2663_b7, by decide, c2663_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c2663_b5, by decide, c2663_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c2663_b4, by decide, c2663_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c2662_b3, by decide, c2662_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 277, c2662_b2, by decide, c2662_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2663_b0, by decide, c2663_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2662_b9, by decide, c2662_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c2662_b8, by decide, c2662_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c2662_b7, by decide, c2662_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c2662_b6, by decide, c2662_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c2662_b5, by decide, c2662_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c2662_b4, by decide, c2662_ok4⟩, ?_⟩
  simp

def s29 : List Nat := [22799473650499584, 18295874039840768, 4785075208060928, 22799474455740417, 18296149437841409, 4786175189450753, 22799473382064129, 18296148632600577, 4786174384209921, 282849366310913, 18295874845147137, 282574773551105, 282575578857473, 4785076013367297, 281750190161921, 281750995468289, 4785075946262528, 281750928363520, 4785075141021696, 281750123122688, 281475530362880, 281476335669248]
theorem e29 : enumKeys 229 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2664_b7, by decide, c2664_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c2664_b6, by decide, c2664_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2664_b5, by decide, c2664_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2665_b6, by decide, c2665_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2665_b5, by decide, c2665_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c2665_b4, by decide, c2665_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2666_b4, by decide, c2666_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c2666_b6, by decide, c2666_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c2666_b5, by decide, c2666_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2666_b3, by decide, c2666_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c2666_b2, by decide, c2666_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c2666_b1, by decide, c2666_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c2666_b0, by decide, c2666_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2665_b9, by decide, c2665_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2665_b8, by decide, c2665_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c2665_b7, by decide, c2665_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c2664_b9, by decide, c2664_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c2664_b8, by decide, c2664_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2665_b3, by decide, c2665_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2665_b2, by decide, c2665_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2665_b1, by decide, c2665_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2665_b0, by decide, c2665_ok0⟩, ?_⟩
  simp

def s30 : List Nat := [5066550117924864, 5066554949500929, 5066554144260097, 563225099829249, 563229126361089, 5066550923231233, 563225100025857, 563225905332225, 562951312375809, 562954533601281, 562955338907649, 5066550922969104, 563225905070096, 5066550117728272, 563225099829264, 562950507069456, 562951312375824]
theorem e30 : enumKeys 229 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c2666_b7, by decide, c2666_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c2667_b4, by decide, c2667_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c2668_b3, by decide, c2668_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2668_b2, by decide, c2668_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c2668_b1, by decide, c2668_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c2668_b0, by decide, c2668_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2667_b9, by decide, c2667_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c2667_b8, by decide, c2667_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c2667_b7, by decide, c2667_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2667_b6, by decide, c2667_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c2667_b5, by decide, c2667_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2666_b9, by decide, c2666_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c2666_b8, by decide, c2666_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c2667_b3, by decide, c2667_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2667_b2, by decide, c2667_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2667_b1, by decide, c2667_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c2667_b0, by decide, c2667_ok0⟩, ?_⟩
  simp

def s31 : List Nat := [5910975047860224, 1407375437201408, 5910976658407425, 5910975853166593, 4785143592058881, 4785144397365249, 1407650029961217, 1407650835267585, 281818574159873, 1407376242507777, 1407377047814145, 281543981400065, 281544786706433, 4785076751565056, 4785075141017856, 4785075946324224, 281750123118848, 281750928425216, 281475530359040, 281476335665408, 281477140971776]
theorem e31 : enumKeys 229 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c2668_b5, by decide, c2668_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c2668_b4, by decide, c2668_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2669_b4, by decide, c2669_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2670_b4, by decide, c2670_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2670_b3, by decide, c2670_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c2670_b1, by decide, c2670_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c2670_b2, by decide, c2670_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2670_b0, by decide, c2670_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2669_b9, by decide, c2669_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2669_b8, by decide, c2669_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2669_b6, by decide, c2669_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2669_b7, by decide, c2669_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c2669_b5, by decide, c2669_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c2668_b6, by decide, c2668_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c2669_b3, by decide, c2669_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c2669_b2, by decide, c2669_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c2669_b1, by decide, c2669_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c2669_b0, by decide, c2669_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2668_b9, by decide, c2668_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c2668_b8, by decide, c2668_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c2668_b7, by decide, c2668_ok7⟩, ?_⟩
  simp

def s32 : List Nat := [18577348999839744, 562950557401088, 18577350610386945, 18577349805146113, 564049733550081, 564050538856449, 562951362707457, 562952168013825, 562952100909056, 562950490361856, 562951295668224]
theorem e32 : enumKeys 229 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c2670_b6, by decide, c2670_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c2670_b5, by decide, c2670_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2671_b0, by decide, c2671_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c2671_b5, by decide, c2671_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c2671_b4, by decide, c2671_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c2671_b3, by decide, c2671_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2671_b2, by decide, c2671_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c2671_b1, by decide, c2671_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2670_b7, by decide, c2670_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c2670_b9, by decide, c2670_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c2670_b8, by decide, c2670_ok8⟩, ?_⟩
  simp

def s33 : List Nat := [844425467265024, 844426272374785, 844429493600257, 844430298906625, 844426272571393, 844427077877761, 844427077615632, 844425467068432, 844426272374800]
theorem e33 : enumKeys 229 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2671_b6, by decide, c2671_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c2672_b4, by decide, c2672_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2672_b3, by decide, c2672_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c2672_b2, by decide, c2672_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2672_b1, by decide, c2672_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2672_b0, by decide, c2672_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c2671_b7, by decide, c2671_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c2671_b9, by decide, c2671_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c2671_b8, by decide, c2671_ok8⟩, ?_⟩
  simp

def s34 : List Nat := [1688850397200384, 1688851202506753, 1688852007813121, 563018941399041, 563019746705409, 562950490358016, 562951295664384, 562952100970752]
theorem e34 : enumKeys 229 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c2672_b5, by decide, c2672_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2673_b2, by decide, c2673_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2673_b0, by decide, c2673_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2673_b1, by decide, c2673_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c2672_b9, by decide, c2672_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2672_b8, by decide, c2672_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c2672_b7, by decide, c2672_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c2672_b6, by decide, c2672_ok6⟩, ?_⟩
  simp

def s35 : List Nat := [13510799418982401, 9007474401083393, 4504149383184385, 9007199808389121, 4503874790490113, 549772591105]
theorem e35 : enumKeys 229 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c2673_b5, by decide, c2673_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c2673_b4, by decide, c2673_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c2673_b3, by decide, c2673_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c2673_b8, by decide, c2673_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c2673_b7, by decide, c2673_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2673_b6, by decide, c2673_ok6⟩, ?_⟩
  simp

def s36 : List Nat := [9288675573628929, 4785350555729921, 9288674768388097, 4785349750489089, 282024732590081, 4785075157729281, 4785075963035649, 281750139830273, 281750945136641]
theorem e36 : enumKeys 229 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2674_b0, by decide, c2674_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c2673_b9, by decide, c2673_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c2674_b7, by decide, c2674_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c2674_b6, by decide, c2674_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c2674_b5, by decide, c2674_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2674_b4, by decide, c2674_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c2674_b3, by decide, c2674_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c2674_b2, by decide, c2674_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c2674_b1, by decide, c2674_ok1⟩, ?_⟩
  simp

def s37 : List Nat := [5066551728275457, 5066550117728257, 5066550923034625, 563225099829249, 563225905135617, 562950507069441, 562951312375809, 562952117682177]
theorem e37 : enumKeys 229 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2674_b8, by decide, c2674_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c2675_b5, by decide, c2675_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c2675_b4, by decide, c2675_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c2675_b3, by decide, c2675_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c2675_b2, by decide, c2675_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c2675_b1, by decide, c2675_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c2675_b0, by decide, c2675_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2674_b9, by decide, c2674_ok9⟩, ?_⟩
  simp

def s38 : List Nat := [844425467068417, 844426272374785, 844427077681153]
theorem e38 : enumKeys 229 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2675_b8, by decide, c2675_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c2675_b7, by decide, c2675_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c2675_b6, by decide, c2675_ok6⟩, ?_⟩
  simp

/-- every enumerated key with left type `229` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 229 mR,
    (229 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 229 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K21
end Grid3.Three.Cert
