import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C3100
import Grid3.Three.Cert.Data.C3101
import Grid3.Three.Cert.Data.C3102
import Grid3.Three.Cert.Data.C3103
import Grid3.Three.Cert.Data.C3104
import Grid3.Three.Cert.Data.C3105
import Grid3.Three.Cert.Data.C3106
import Grid3.Three.Cert.Data.C3107
import Grid3.Three.Cert.Data.C3108
import Grid3.Three.Cert.Data.C3109
import Grid3.Three.Cert.Data.C3110
import Grid3.Three.Cert.Data.C3111
import Grid3.Three.Cert.Data.C3112
import Grid3.Three.Cert.Data.C3113
import Grid3.Three.Cert.Data.C3114
import Grid3.Three.Cert.Data.C3115
import Grid3.Three.Cert.Data.C3116
import Grid3.Three.Cert.Data.C3117
import Grid3.Three.Cert.Data.C3118
import Grid3.Three.Cert.Data.C3119
import Grid3.Three.Cert.Data.C3120
import Grid3.Three.Cert.Data.C3121
import Grid3.Three.Cert.Data.C3122
import Grid3.Three.Cert.Data.C3123
import Grid3.Three.Cert.Data.C3124
import Grid3.Three.Cert.Data.C3125
import Grid3.Three.Cert.Data.C3126
import Grid3.Three.Cert.Data.C3127
import Grid3.Three.Cert.Data.C3128
import Grid3.Three.Cert.Data.C3129
import Grid3.Three.Cert.Data.C3130
import Grid3.Three.Cert.Data.C3131
import Grid3.Three.Cert.Data.C3132
import Grid3.Three.Cert.Data.C3133
import Grid3.Three.Cert.Data.C3134
import Grid3.Three.Cert.Data.C3135
import Grid3.Three.Cert.Data.C3136
import Grid3.Three.Cert.Data.C3137
import Grid3.Three.Cert.Data.C3138
import Grid3.Three.Cert.Data.C3139
import Grid3.Three.Cert.Data.C3140
import Grid3.Three.Cert.Data.C3141
import Grid3.Three.Cert.Data.C3142
import Grid3.Three.Cert.Data.C3143
import Grid3.Three.Cert.Data.C3144
import Grid3.Three.Cert.Data.C3145
import Grid3.Three.Cert.Data.C3146
import Grid3.Three.Cert.Data.C3147
import Grid3.Three.Cert.Data.C3148
import Grid3.Three.Cert.Data.C3149
import Grid3.Three.Cert.Data.C3150
import Grid3.Three.Cert.Data.C3151
import Grid3.Three.Cert.Data.C3152
import Grid3.Three.Cert.Data.C3153
import Grid3.Three.Cert.Data.C3154
import Grid3.Three.Cert.Data.C3155
import Grid3.Three.Cert.Data.C3156
import Grid3.Three.Cert.Data.C3157
import Grid3.Three.Cert.Data.C3158
import Grid3.Three.Cert.Data.C3159
import Grid3.Three.Cert.Data.C3160
import Grid3.Three.Cert.Data.C3161
import Grid3.Three.Cert.Data.C3162
import Grid3.Three.Cert.Data.C3163
import Grid3.Three.Cert.Data.C3164
import Grid3.Three.Cert.Data.C3165
import Grid3.Three.Cert.Data.C3166
import Grid3.Three.Cert.Data.C3167
import Grid3.Three.Cert.Data.C3168
import Grid3.Three.Cert.Data.C3169
import Grid3.Three.Cert.Data.C3170
import Grid3.Three.Cert.Data.C3171
import Grid3.Three.Cert.Data.C3172
import Grid3.Three.Cert.Data.C3173

/-! Seam keys with left type `589` (type index 25): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `ai_research_notes/cx/k3rev/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K25

def s00 : List Nat := [590313824757215133696, 590295810358772760576, 295165919577929416704, 295147905179487043584, 18014398643699712, 201326592, 590295810358705655808, 295165919577862311936, 295147905179419938816, 18014398576594944, 134221824]
theorem e00 : enumKeys 589 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c3100_b0, by decide, c3100_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨3, 182, c3100_b1, by decide, c3100_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c3100_b2, by decide, c3100_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c3100_b3, by decide, c3100_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c3100_b4, by decide, c3100_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c3100_b5, by decide, c3100_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c3100_b6, by decide, c3100_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 195, c3100_b7, by decide, c3100_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c3100_b8, by decide, c3100_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c3100_b9, by decide, c3100_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c3101_b0, by decide, c3101_ok0⟩, ?_⟩
  simp

def s01 : List Nat := [368936007374098137088, 313599152852690010112, 92251734767057502208, 296301952583883292672, 19617679976842657792, 313594649253079416832, 295149031079276707840, 18464758472236072960, 74941023699419004928, 19604169178010877952, 92233720368615129088, 73788102194812420096, 18451247673404293120, 19599665578400284672, 1154047404597575680, 18446744073793699840, 1125899990990848, 368936007374097874960, 313599152852689747984, 92251734767057240080, 313594649253079154704, 295149031079276445712, 18464758472235810832, 92233720368614866960, 73788102194812157968, 18451247673404030992, 18446744073793437712, 1125899990728720, 296305330283587043584, 74957912197954535680, 368934881474191294720, 295152408778980458752, 73804990693347950848, 296300826683976450304, 1170935903133106432, 295147905179369865472, 18014398526521600, 74939897799512162560, 1157425104301326592, 73786976294905577728, 4503599694741760, 1152921504690733312, 84148480, 74941023699351900160, 19604169177943773184, 92233720368548024320, 73788102194745315328, 18451247673337188352, 19599665578333179904, 1154047404530470912, 18446744073726595072, 1125899923886080]
theorem e01 : enumKeys 589 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3101_b9, by decide, c3101_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3101_b8, by decide, c3101_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3101_b7, by decide, c3101_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3101_b4, by decide, c3101_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3101_b3, by decide, c3101_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3102_b3, by decide, c3102_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3102_b5, by decide, c3102_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3102_b4, by decide, c3102_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3101_b2, by decide, c3101_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3101_b1, by decide, c3101_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3102_b0, by decide, c3102_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c3102_b2, by decide, c3102_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3102_b1, by decide, c3102_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3101_b5, by decide, c3101_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c3101_b6, by decide, c3101_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3102_b6, by decide, c3102_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3102_b7, by decide, c3102_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3105_b4, by decide, c3105_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3105_b3, by decide, c3105_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3105_b2, by decide, c3105_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3105_b8, by decide, c3105_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3106_b0, by decide, c3106_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3105_b9, by decide, c3105_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3105_b5, by decide, c3105_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3105_b7, by decide, c3105_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3105_b6, by decide, c3105_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3106_b1, by decide, c3106_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c3106_b2, by decide, c3106_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3103_b8, by decide, c3103_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3103_b7, by decide, c3103_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3104_b4, by decide, c3104_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3104_b6, by decide, c3104_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c3104_b5, by decide, c3104_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3104_b1, by decide, c3104_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c3104_b2, by decide, c3104_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3104_b9, by decide, c3104_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c3105_b0, by decide, c3105_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3103_b9, by decide, c3103_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3104_b0, by decide, c3104_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c3104_b7, by decide, c3104_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c3104_b8, by decide, c3104_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c3104_b3, by decide, c3104_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3105_b1, by decide, c3105_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3102_b9, by decide, c3102_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3102_b8, by decide, c3102_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3103_b2, by decide, c3103_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c3103_b4, by decide, c3103_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3103_b3, by decide, c3103_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3103_b0, by decide, c3103_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c3103_b1, by decide, c3103_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3103_b5, by decide, c3103_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c3103_b6, by decide, c3103_ok6⟩, ?_⟩
  simp

def s02 : List Nat := [296318841082469154816, 590296091833682624512, 299777605596289957888, 296301108159003492352, 5782621921610825728, 299759591197847584768, 295148186654396907520, 4629700417004240896, 5764607523168452608, 1153202979717775360, 4611686018561867776, 281475111190528, 590296091833682362384, 299777605596289695760, 299759591197847322640, 295148186654396645392, 4629700417003978768, 4611686018561605648, 281475110928400, 296301108158936387584, 5782621921543720960, 299759591197780480000, 295148186654329802752, 4629700416937136128, 5764607523101347840, 1153202979650670592, 4611686018494763008, 281475044085760]
theorem e02 : enumKeys 589 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3106_b3, by decide, c3106_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3106_b9, by decide, c3106_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3106_b8, by decide, c3106_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3106_b5, by decide, c3106_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c3106_b4, by decide, c3106_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3107_b0, by decide, c3107_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3107_b2, by decide, c3107_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3107_b1, by decide, c3107_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3106_b6, by decide, c3106_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3106_b7, by decide, c3106_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3107_b3, by decide, c3107_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3107_b4, by decide, c3107_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3108_b5, by decide, c3108_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3108_b4, by decide, c3108_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3108_b6, by decide, c3108_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3108_b8, by decide, c3108_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c3108_b7, by decide, c3108_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3108_b9, by decide, c3108_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3109_b0, by decide, c3109_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3107_b6, by decide, c3107_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c3107_b5, by decide, c3107_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c3107_b9, by decide, c3107_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c3108_b1, by decide, c3108_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3108_b0, by decide, c3108_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3107_b7, by decide, c3107_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3107_b8, by decide, c3107_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c3108_b2, by decide, c3108_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c3108_b3, by decide, c3108_ok3⟩, ?_⟩
  simp

def s03 : List Nat := [74941023699352158208, 19604169177944031232, 92234001843524993024, 78399788213172961280, 23062933691764834304, 2306968909137313792, 19599947053310148608, 5765733422958116864, 23058430092154241024, 18447025548703563776, 4612811918351532032, 74940179274421764112, 74941023699351896080, 5769111122661605392, 19604169177943769104, 92234001843524730896, 78399788213172699152, 23062933691764572176, 19599947053309886480, 5765733422957854736, 23058430092153978896, 18447025548703301648, 4612811918351269904, 2310346608841064704, 74940179274422026496, 5769111122661867776, 78398662313266118912, 73787257769815441664, 4616189618055282944, 2306124484207182080, 5764607523051274496, 1153202979600597248, 4611686018444689664, 281474994012416]
theorem e03 : enumKeys 589 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c3109_b3, by decide, c3109_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3109_b2, by decide, c3109_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3109_b8, by decide, c3109_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3109_b7, by decide, c3109_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3109_b6, by decide, c3109_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c3109_b1, by decide, c3109_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3109_b5, by decide, c3109_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3109_b4, by decide, c3109_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3109_b9, by decide, c3109_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3110_b1, by decide, c3110_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3110_b0, by decide, c3110_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3111_b6, by decide, c3111_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3111_b5, by decide, c3111_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3111_b4, by decide, c3111_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3111_b3, by decide, c3111_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3112_b1, by decide, c3112_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3112_b0, by decide, c3112_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3111_b9, by decide, c3111_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3111_b8, by decide, c3111_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3111_b7, by decide, c3111_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3112_b2, by decide, c3112_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3112_b4, by decide, c3112_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3112_b3, by decide, c3112_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3110_b2, by decide, c3110_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3110_b5, by decide, c3110_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3110_b4, by decide, c3110_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3110_b8, by decide, c3110_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3111_b0, by decide, c3111_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3110_b9, by decide, c3110_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3110_b3, by decide, c3110_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3110_b6, by decide, c3110_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3110_b7, by decide, c3110_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3111_b1, by decide, c3111_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3111_b2, by decide, c3111_ok2⟩, ?_⟩
  simp

def s04 : List Nat := [2323857407723175936, 296301108158936645632, 5782621921543979008, 299759872672757448704, 9241386435364782080, 2306124484257513472, 5764888998078316544, 9223372036922408960, 4611967493471731712, 296301108158936383504, 5782621921543716880, 299759872672757186576, 9241386435364519952, 5764888998078054416, 9223372036922146832, 4611967493471469584, 2306124484190408704, 5764888998011211776, 9223372036855304192, 4611967493404626944]
theorem e04 : enumKeys 589 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c3112_b5, by decide, c3112_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3112_b8, by decide, c3112_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3112_b7, by decide, c3112_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3113_b1, by decide, c3113_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3113_b0, by decide, c3113_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c3112_b6, by decide, c3112_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3112_b9, by decide, c3112_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3113_b2, by decide, c3113_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3113_b3, by decide, c3113_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3113_b9, by decide, c3113_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3113_b8, by decide, c3113_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3114_b2, by decide, c3114_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3114_b1, by decide, c3114_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3114_b0, by decide, c3114_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3114_b3, by decide, c3114_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3114_b4, by decide, c3114_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3113_b4, by decide, c3113_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3113_b5, by decide, c3113_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3113_b6, by decide, c3113_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3113_b7, by decide, c3113_ok7⟩, ?_⟩
  simp

def s05 : List Nat := [2306124484190666752, 5764888998011469824, 9223653511832272896, 2306124484190404624, 5764888998011207696, 9223653511832010768]
theorem e05 : enumKeys 589 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c3114_b5, by decide, c3114_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3114_b6, by decide, c3114_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3114_b7, by decide, c3114_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3114_b8, by decide, c3114_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3114_b9, by decide, c3114_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3115_b0, by decide, c3115_ok0⟩, ?_⟩
  simp

def s06 : List Nat := [590296936258612559872, 313612663651571924992, 313594649253129551872, 295149031079326842880, 18464758472286208000, 18446744073843834880, 1125900041125888, 590295810358705717504, 295165919577862373632, 295147905179420000512, 18014398576656640, 134283520, 313594649253062447104, 295149031079259738112, 18464758472219103232, 18446744073776730112, 1125899974021120]
theorem e06 : enumKeys 589 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3115_b2, by decide, c3115_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3115_b1, by decide, c3115_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3115_b3, by decide, c3115_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3115_b5, by decide, c3115_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3115_b4, by decide, c3115_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3115_b6, by decide, c3115_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3115_b7, by decide, c3115_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3116_b3, by decide, c3116_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3116_b4, by decide, c3116_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3116_b5, by decide, c3116_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c3116_b6, by decide, c3116_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3116_b7, by decide, c3116_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3115_b8, by decide, c3115_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3116_b0, by decide, c3116_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3115_b9, by decide, c3115_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3116_b1, by decide, c3116_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c3116_b2, by decide, c3116_ok2⟩, ?_⟩
  simp

def s07 : List Nat := [92234846268454928384, 36897991747046801408, 19600791478240083968, 36893488147436208128, 18447869973633499136, 92234846268454666256, 36897991747046539280, 36893488147435946000, 18447869973633237008, 74941023699351961856, 19604169177943834880, 92233720368548086016, 73788102194745377024, 18451247673337250048, 19599665578333241600, 1154047404530532608, 18446744073726656768, 1125899923947776]
theorem e07 : enumKeys 589 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3117_b0, by decide, c3117_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3116_b9, by decide, c3116_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3116_b8, by decide, c3116_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3117_b1, by decide, c3117_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3117_b2, by decide, c3117_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3118_b3, by decide, c3118_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3118_b2, by decide, c3118_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3118_b4, by decide, c3118_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3118_b5, by decide, c3118_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3117_b4, by decide, c3117_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3117_b3, by decide, c3117_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3117_b7, by decide, c3117_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3117_b9, by decide, c3117_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3117_b8, by decide, c3117_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3117_b5, by decide, c3117_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3117_b6, by decide, c3117_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3118_b0, by decide, c3118_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3118_b1, by decide, c3118_ok1⟩, ?_⟩
  simp

def s08 : List Nat := [296301952583866580992, 19617679976825946112, 313594930728039415808, 299760717097687384064, 23076444490646749184, 19599947053360283648, 5765733423008251904, 23058430092204376064, 18447025548753698816, 4612811918401667072, 313594930728039153680, 299760717097687121936, 23076444490646487056, 23058430092204113936, 18447025548753436688, 4612811918401404944, 296301108158936449280, 5782621921543782656, 299759591197780541696, 295148186654329864448, 4629700416937197824, 5764607523101409536, 1153202979650732288, 4611686018494824704, 281475044147456, 19599947053293178880, 5765733422941147136, 23058430092137271296, 18447025548686594048, 4612811918334562304]
theorem e08 : enumKeys 589 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3118_b7, by decide, c3118_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3118_b6, by decide, c3118_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3119_b2, by decide, c3119_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3119_b1, by decide, c3119_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3119_b0, by decide, c3119_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3118_b9, by decide, c3118_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3118_b8, by decide, c3118_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3119_b3, by decide, c3119_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3119_b5, by decide, c3119_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3119_b4, by decide, c3119_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3121_b2, by decide, c3121_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3121_b1, by decide, c3121_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3121_b0, by decide, c3121_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3121_b3, by decide, c3121_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3121_b5, by decide, c3121_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3121_b4, by decide, c3121_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3120_b2, by decide, c3120_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3120_b1, by decide, c3120_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3120_b5, by decide, c3120_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3120_b7, by decide, c3120_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c3120_b6, by decide, c3120_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3120_b3, by decide, c3120_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3120_b4, by decide, c3120_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3120_b8, by decide, c3120_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3120_b9, by decide, c3120_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3119_b7, by decide, c3119_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3119_b6, by decide, c3119_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3119_b8, by decide, c3119_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3120_b0, by decide, c3120_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3119_b9, by decide, c3119_ok9⟩, ?_⟩
  simp

def s09 : List Nat := [2306968909120602112, 19599947053293436928, 5765733422941405184, 23058711567114240000, 9224497936762208256, 5764888998011011088, 19599947053293174800, 5765733422941143056, 23058711567113977872, 9224497936761946128, 2306124484190470400, 5764888998011273472, 9223372036855365888, 4611967493404688640]
theorem e09 : enumKeys 589 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c3121_b6, by decide, c3121_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3121_b8, by decide, c3121_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3121_b7, by decide, c3121_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3122_b0, by decide, c3122_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3121_b9, by decide, c3121_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3122_b7, by decide, c3122_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3122_b6, by decide, c3122_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3122_b5, by decide, c3122_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3122_b9, by decide, c3122_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3122_b8, by decide, c3122_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3122_b1, by decide, c3122_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3122_b2, by decide, c3122_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3122_b3, by decide, c3122_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3122_b4, by decide, c3122_ok4⟩, ?_⟩
  simp

def s10 : List Nat := [313595775152969351168, 36911502545928716288, 36893488147486343168, 18447869973683634176, 313594649253062508800, 295149031079259799808, 18464758472219164928, 18446744073776791808, 1125899974082816, 36893488147419238400, 18447869973616529408]
theorem e10 : enumKeys 589 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3123_b1, by decide, c3123_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3123_b0, by decide, c3123_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3123_b2, by decide, c3123_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3123_b3, by decide, c3123_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3123_b6, by decide, c3123_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3123_b8, by decide, c3123_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3123_b7, by decide, c3123_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3123_b9, by decide, c3123_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c3124_b0, by decide, c3124_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3123_b4, by decide, c3123_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3123_b5, by decide, c3123_ok5⟩, ?_⟩
  simp

def s11 : List Nat := [19600791478223372288, 36893769622396207104, 23059555992044175360, 36893769622395944976, 23059555992043913232, 19599947053293240576, 5765733422941208832, 23058430092137332992, 18447025548686655744, 4612811918334624000]
theorem e11 : enumKeys 589 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3124_b1, by decide, c3124_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3124_b3, by decide, c3124_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3124_b2, by decide, c3124_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3125_b0, by decide, c3125_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3124_b9, by decide, c3124_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3124_b5, by decide, c3124_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3124_b4, by decide, c3124_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3124_b6, by decide, c3124_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3124_b8, by decide, c3124_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3124_b7, by decide, c3124_ok7⟩, ?_⟩
  simp

def s12 : List Nat := [36894614047326142464, 36893488147419300096, 18447869973616591104]
theorem e12 : enumKeys 589 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3125_b1, by decide, c3125_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3125_b2, by decide, c3125_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3125_b3, by decide, c3125_ok3⟩, ?_⟩
  simp

def s13 : List Nat := [295237977171917012992, 295224466373085233152, 73877048287452725248, 295219962773474639872, 90071992631296000, 73859033889010352128, 76561193799516160, 72057594188922880, 590300313958333022209, 368952895872700514305, 590295810358722428929, 295165919577879085057, 368934881474258141185, 295152408779047305217, 73804990693414797313, 295147905179436711937, 18014398593368065, 73786976294972424193, 4503599761588225, 150994945, 368934881474191036416, 295224466373018128384, 73877048287385620480, 295219962773407535104, 90071992564191232, 73859033888943247360, 76561193732411392, 72057594121818112]
theorem e13 : enumKeys 589 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c3125_b8, by decide, c3125_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3125_b5, by decide, c3125_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3125_b4, by decide, c3125_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3125_b9, by decide, c3125_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c3126_b0, by decide, c3126_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3125_b6, by decide, c3125_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3125_b7, by decide, c3125_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3126_b1, by decide, c3126_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3127_b1, by decide, c3127_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3127_b0, by decide, c3127_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3127_b7, by decide, c3127_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c3127_b8, by decide, c3127_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3127_b2, by decide, c3127_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3127_b4, by decide, c3127_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3127_b3, by decide, c3127_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3127_b9, by decide, c3127_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c3128_b0, by decide, c3128_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3127_b5, by decide, c3127_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3127_b6, by decide, c3127_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3128_b1, by decide, c3128_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3126_b2, by decide, c3126_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3126_b4, by decide, c3126_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c3126_b3, by decide, c3126_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3126_b7, by decide, c3126_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3126_b8, by decide, c3126_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c3126_b5, by decide, c3126_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c3126_b6, by decide, c3126_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3126_b9, by decide, c3126_ok9⟩, ?_⟩
  simp

def s14 : List Nat := [73860159788800016384, 18523305267391889408, 1226104998585171968, 18518801667781296128, 73183493978587136, 74944401399072423937, 147575078489583517697, 92238223968175390721, 74941023699368673281, 19604169177960546305, 92233720368564797441, 73788102194762088449, 18451247673353961473, 19599665578349953025, 1154047404547244033, 18446744073743368193, 1125899940659201, 147575078489583255568, 73863537488503504912, 92238223968175128592, 92233720368564535312, 73860159788799754256, 18523305267391627280, 18518801667781034000, 73183493978325008, 74944401399072424192, 147573952589676675328, 73863537488503767296, 74939897799461830912, 1229482698288922880, 73859033888893174016, 76561193682338048, 1224979098678329600, 72057594071744768]
theorem e14 : enumKeys 589 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3128_b4, by decide, c3128_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3128_b3, by decide, c3128_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3128_b2, by decide, c3128_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3128_b5, by decide, c3128_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3128_b6, by decide, c3128_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3130_b4, by decide, c3130_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3131_b0, by decide, c3131_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3130_b9, by decide, c3130_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3130_b6, by decide, c3130_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3130_b5, by decide, c3130_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3131_b1, by decide, c3131_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3131_b3, by decide, c3131_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3131_b2, by decide, c3131_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3130_b7, by decide, c3130_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3130_b8, by decide, c3130_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3131_b4, by decide, c3131_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3131_b5, by decide, c3131_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3129_b8, by decide, c3129_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3129_b7, by decide, c3129_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3129_b6, by decide, c3129_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3129_b9, by decide, c3129_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3130_b1, by decide, c3130_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3130_b0, by decide, c3130_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3130_b2, by decide, c3130_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3130_b3, by decide, c3130_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3128_b7, by decide, c3128_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c3129_b1, by decide, c3129_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3129_b2, by decide, c3129_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c3128_b8, by decide, c3128_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3128_b9, by decide, c3128_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3129_b3, by decide, c3129_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3129_b4, by decide, c3129_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3129_b0, by decide, c3129_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3129_b5, by decide, c3129_ok5⟩, ?_⟩
  simp

def s15 : List Nat := [295224466373018386432, 73877048287385878528, 1242993497171034112, 295220244248384503808, 4701758010991837184, 1229482698339254272, 73859315363920216064, 4688247212160057344, 1225260573705371648, 4683743612549464064, 72339069098786816, 296305330283587043329, 74957912197954535425, 368935162949168005121, 299764094797407846401, 78416676711775338497, 296301108158953160705, 5782621921560494081, 299759591197797253121, 295148186654346575873, 4629700416953909249, 74940179274488872961, 5769111122728714241, 78398662313332965377, 73787257769882288129, 4616189618122129409, 5764607523118120961, 1153202979667443713, 4611686018511536129, 281475060858881, 368935162949167742992, 295224466373018124304, 299764094797407584272, 73877048287385616400, 78416676711775076368, 299759591197796990992, 295220244248384241680, 4701758010991575056, 78398662313332703248, 73859315363919953936, 4688247212159795216, 4683743612549201936, 72339069098524688, 74940179274421768192, 1229482698272149504, 5769111122661609472, 78398662313265860608, 73859315363853111296, 4688247212092952576, 5764607523051016192, 1225260573638266880, 4683743612482359296, 72339069031682048]
theorem e15 : enumKeys 589 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3132_b0, by decide, c3132_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c3131_b9, by decide, c3131_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c3131_b7, by decide, c3131_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3132_b4, by decide, c3132_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3132_b3, by decide, c3132_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3131_b6, by decide, c3131_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3132_b2, by decide, c3132_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3132_b1, by decide, c3132_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3131_b8, by decide, c3131_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3132_b5, by decide, c3132_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3132_b6, by decide, c3132_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3135_b1, by decide, c3135_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3135_b0, by decide, c3135_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3136_b0, by decide, c3136_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3135_b9, by decide, c3135_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3135_b8, by decide, c3135_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3135_b5, by decide, c3135_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3135_b4, by decide, c3135_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3136_b4, by decide, c3136_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3136_b6, by decide, c3136_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3136_b5, by decide, c3136_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3135_b3, by decide, c3135_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3135_b2, by decide, c3135_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3136_b1, by decide, c3136_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3136_b3, by decide, c3136_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3136_b2, by decide, c3136_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3135_b6, by decide, c3135_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3135_b7, by decide, c3135_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3136_b7, by decide, c3136_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3136_b8, by decide, c3136_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3134_b1, by decide, c3134_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3134_b0, by decide, c3134_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3133_b9, by decide, c3133_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3133_b8, by decide, c3133_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3133_b7, by decide, c3133_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3134_b5, by decide, c3134_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3134_b7, by decide, c3134_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3134_b6, by decide, c3134_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3134_b2, by decide, c3134_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3134_b4, by decide, c3134_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3134_b3, by decide, c3134_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3134_b8, by decide, c3134_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3134_b9, by decide, c3134_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3132_b9, by decide, c3132_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3132_b8, by decide, c3132_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3132_b7, by decide, c3132_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c3133_b2, by decide, c3133_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3133_b4, by decide, c3133_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3133_b3, by decide, c3133_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c3133_b0, by decide, c3133_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3133_b1, by decide, c3133_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3133_b5, by decide, c3133_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3133_b6, by decide, c3133_ok6⟩, ?_⟩
  simp

def s16 : List Nat := [1229482698272407552, 73859315363853369344, 4688247212093210624, 1225260573638524928, 4684025087459328000, 2310346608841064449, 74940179274422026241, 5769111122661867521, 78398943788242829313, 9227875636482670593, 2306124484207181825, 5764888998027984897, 9223372036872077313, 4611967493421400065, 74940179274421764112, 1229482698272145424, 5769111122661605392, 73859315363853107216, 78398943788242567184, 4688247212092948496, 9227875636482408464, 1225260573638262800, 5764888998027722768, 9223372036871815184, 4684025087459065872]
theorem e16 : enumKeys 589 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c3136_b9, by decide, c3136_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3137_b2, by decide, c3137_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3137_b1, by decide, c3137_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3137_b0, by decide, c3137_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3137_b3, by decide, c3137_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3138_b5, by decide, c3138_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3138_b8, by decide, c3138_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3138_b7, by decide, c3138_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3139_b1, by decide, c3139_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3139_b0, by decide, c3139_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3138_b6, by decide, c3138_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3138_b9, by decide, c3138_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3139_b2, by decide, c3139_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3139_b3, by decide, c3139_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3137_b6, by decide, c3137_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3137_b5, by decide, c3137_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3137_b4, by decide, c3137_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3138_b2, by decide, c3138_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3138_b1, by decide, c3138_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3138_b0, by decide, c3138_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3137_b9, by decide, c3137_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3137_b8, by decide, c3137_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3137_b7, by decide, c3137_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3138_b3, by decide, c3138_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3138_b4, by decide, c3138_ok4⟩, ?_⟩
  simp

def s17 : List Nat := [295221088673314439168, 18536816066273804288, 73860159788850151424, 18523305267442024448, 18518801667831431168, 73183494028722176, 368936007374097940481, 313599152852689813505, 92251734767057305601, 313594649253079220225, 295149031079276511233, 18464758472235876353, 92233720368614932481, 73788102194812223489, 18451247673404096513, 18446744073793503233, 1125899990794241, 368934881474191098112, 295224466373018190080, 73877048287385682176, 295219962773407596800, 90071992564252928, 73859033888943309056, 76561193732473088, 72057594121879808, 92233720368547827712, 73860159788783046656, 18523305267374919680, 18518801667764326400, 73183493961617408]
theorem e17 : enumKeys 589 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3139_b7, by decide, c3139_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3139_b6, by decide, c3139_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3139_b5, by decide, c3139_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3139_b4, by decide, c3139_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3139_b8, by decide, c3139_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3139_b9, by decide, c3139_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3141_b5, by decide, c3141_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3141_b4, by decide, c3141_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3141_b3, by decide, c3141_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3141_b9, by decide, c3141_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3142_b1, by decide, c3142_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3142_b0, by decide, c3142_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3141_b6, by decide, c3141_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3141_b8, by decide, c3141_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3141_b7, by decide, c3141_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3142_b2, by decide, c3142_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3142_b3, by decide, c3142_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3140_b5, by decide, c3140_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3140_b7, by decide, c3140_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3140_b6, by decide, c3140_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3141_b0, by decide, c3141_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3141_b1, by decide, c3141_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3140_b8, by decide, c3140_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3140_b9, by decide, c3140_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3141_b2, by decide, c3141_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3140_b0, by decide, c3140_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3140_b2, by decide, c3140_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3140_b1, by decide, c3140_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3140_b3, by decide, c3140_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c3140_b4, by decide, c3140_ok4⟩, ?_⟩
  simp

def s18 : List Nat := [295237977171900301312, 295220244248434638848, 4701758011041972224, 4683743612599599104, 72339069148921856, 590296091833682427905, 299777605596289761281, 299759591197847388161, 295148186654396710913, 4629700417004044289, 4611686018561671169, 281475110993921, 299759591197780283392, 295220244248367534080, 4701758010974867456, 4683743612532494336, 72339069081817088]
theorem e18 : enumKeys 589 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3142_b4, by decide, c3142_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3142_b6, by decide, c3142_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3142_b5, by decide, c3142_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3142_b7, by decide, c3142_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3142_b8, by decide, c3142_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3143_b5, by decide, c3143_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3143_b4, by decide, c3143_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3143_b6, by decide, c3143_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3143_b8, by decide, c3143_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3143_b7, by decide, c3143_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3143_b9, by decide, c3143_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3144_b0, by decide, c3144_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3142_b9, by decide, c3142_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3143_b1, by decide, c3143_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3143_b0, by decide, c3143_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3143_b2, by decide, c3143_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c3143_b3, by decide, c3143_ok3⟩, ?_⟩
  simp

def s19 : List Nat := [73860159788783304704, 18523305267375177728, 1226104998568460288, 18519083142741295104, 4684869512389263360, 74940179274421829633, 74941023699351961601, 5769111122661670913, 19604169177943834625, 92234001843524796417, 78399788213172764673, 23062933691764637697, 19599947053309952001, 5765733422957920257, 23058430092154044417, 18447025548703367169, 4612811918351335425, 73859315363852910608, 92234001843524534288, 73860159788783042576, 78399788213172502544, 4688247212092751888, 18523305267374915600, 23062933691764375568, 23058430092153782288, 18519083142741032976, 4684869512389001232, 74940179274421829888, 1229482698272211200, 5769111122661671168, 78398662313265922304, 73859315363853172992, 4688247212093014272, 5764607523051077888, 1225260573638328576, 4683743612482420992, 72339069031743744]
theorem e19 : enumKeys 589 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3144_b3, by decide, c3144_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3144_b2, by decide, c3144_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3144_b1, by decide, c3144_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3144_b5, by decide, c3144_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3144_b4, by decide, c3144_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3146_b9, by decide, c3146_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3146_b8, by decide, c3146_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3146_b7, by decide, c3146_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3146_b6, by decide, c3146_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3147_b4, by decide, c3147_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3147_b3, by decide, c3147_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3147_b2, by decide, c3147_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3147_b1, by decide, c3147_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3147_b0, by decide, c3147_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3147_b5, by decide, c3147_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3147_b7, by decide, c3147_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3147_b6, by decide, c3147_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3146_b2, by decide, c3146_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3146_b1, by decide, c3146_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3146_b0, by decide, c3146_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3145_b9, by decide, c3145_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3145_b8, by decide, c3145_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3145_b7, by decide, c3145_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3145_b6, by decide, c3145_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3146_b3, by decide, c3146_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3146_b5, by decide, c3146_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3146_b4, by decide, c3146_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3144_b8, by decide, c3144_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3144_b7, by decide, c3144_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3144_b6, by decide, c3144_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3145_b1, by decide, c3145_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3145_b3, by decide, c3145_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3145_b2, by decide, c3145_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3144_b9, by decide, c3144_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3145_b0, by decide, c3145_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3145_b4, by decide, c3145_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3145_b5, by decide, c3145_ok5⟩, ?_⟩
  simp

def s20 : List Nat := [1242993497154322432, 295220244248367792128, 4701758010975125504, 1225260573688659968, 4684025087509463040, 296301108158936449025, 5782621921543782401, 299759872672757252097, 9241386435364585473, 5764888998078119937, 9223372036922212353, 4611967493471535105, 295220244248367530000, 299759872672756989968, 4701758010974863376, 9241386435364323344, 9223372036921950224, 4684025087509200912, 1225260573621555200, 5764888998011015168, 9223372036855107584, 4684025087442358272]
theorem e20 : enumKeys 589 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c3147_b8, by decide, c3147_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3148_b1, by decide, c3148_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c3148_b0, by decide, c3148_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3147_b9, by decide, c3147_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3148_b2, by decide, c3148_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3149_b4, by decide, c3149_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3149_b3, by decide, c3149_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3149_b7, by decide, c3149_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3149_b6, by decide, c3149_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3149_b5, by decide, c3149_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3149_b8, by decide, c3149_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3149_b9, by decide, c3149_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3149_b0, by decide, c3149_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3148_b9, by decide, c3148_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3148_b8, by decide, c3148_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3148_b7, by decide, c3148_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3149_b1, by decide, c3149_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3149_b2, by decide, c3149_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3148_b4, by decide, c3148_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3148_b3, by decide, c3148_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3148_b5, by decide, c3148_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3148_b6, by decide, c3148_ok6⟩, ?_⟩
  simp

def s21 : List Nat := [1225260573621813248, 4684025087442616320, 2306124484190470145, 5764888998011273217, 9223653511832076289, 1225260573621551120, 5764888998011011088, 4684025087442354192, 9223653511831814160]
theorem e21 : enumKeys 589 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c3150_b0, by decide, c3150_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3150_b1, by decide, c3150_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3150_b6, by decide, c3150_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3150_b7, by decide, c3150_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3150_b8, by decide, c3150_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3150_b3, by decide, c3150_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3150_b2, by decide, c3150_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3150_b5, by decide, c3150_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3150_b4, by decide, c3150_ok4⟩, ?_⟩
  simp

def s22 : List Nat := [18519927567671230464, 92234846268454731777, 36897991747046604801, 36893488147436011521, 18447869973633302529, 92233720368547889408, 73860159788783108352, 18523305267374981376, 18518801667764388096, 73183493961679104]
theorem e22 : enumKeys 589 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3150_b9, by decide, c3150_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3151_b6, by decide, c3151_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3151_b5, by decide, c3151_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3151_b7, by decide, c3151_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3151_b8, by decide, c3151_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3151_b0, by decide, c3151_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3151_b2, by decide, c3151_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3151_b1, by decide, c3151_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3151_b3, by decide, c3151_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3151_b4, by decide, c3151_ok4⟩, ?_⟩
  simp

def s23 : List Nat := [295221088673297727488, 18536816066257092608, 18519083142791430144, 4684869512439398400, 313594930728039219201, 299760717097687187457, 23076444490646552577, 23058430092204179457, 18447025548753502209, 4612811918401470465, 299759591197780345088, 295220244248367595776, 4701758010974929152, 4683743612532556032, 72339069081878784, 23058430092137074688, 18519083142724325376, 4684869512372293632]
theorem e23 : enumKeys 589 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3152_b0, by decide, c3152_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3151_b9, by decide, c3151_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3152_b2, by decide, c3152_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3152_b1, by decide, c3152_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3153_b3, by decide, c3153_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3153_b2, by decide, c3153_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3153_b1, by decide, c3153_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3153_b4, by decide, c3153_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3153_b6, by decide, c3153_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3153_b5, by decide, c3153_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3152_b6, by decide, c3152_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3152_b8, by decide, c3152_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3152_b7, by decide, c3152_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3152_b9, by decide, c3152_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3153_b0, by decide, c3153_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3152_b3, by decide, c3152_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3152_b5, by decide, c3152_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3152_b4, by decide, c3152_ok4⟩, ?_⟩
  simp

def s24 : List Nat := [1226104998551748608, 18519083142724583424, 4684869512372551680, 5764888998011076609, 19599947053293240321, 5765733422941208577, 23058711567114043393, 9224497936762011649, 4684025087442157584, 18519083142724321296, 23058711567113781264, 4684869512372289552, 9224497936761749520, 1225260573621616896, 5764888998011076864, 9223372036855169280, 4684025087442419968]
theorem e24 : enumKeys 589 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c3153_b7, by decide, c3153_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3153_b9, by decide, c3153_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3153_b8, by decide, c3153_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3155_b1, by decide, c3155_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3155_b0, by decide, c3155_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3154_b9, by decide, c3154_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3155_b3, by decide, c3155_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3155_b2, by decide, c3155_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3154_b8, by decide, c3154_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3154_b7, by decide, c3154_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3154_b6, by decide, c3154_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3154_b5, by decide, c3154_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3154_b4, by decide, c3154_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3154_b1, by decide, c3154_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3154_b0, by decide, c3154_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3154_b2, by decide, c3154_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3154_b3, by decide, c3154_ok3⟩, ?_⟩
  simp

def s25 : List Nat := [18519927567654518784, 36893769622396010497, 23059555992043978753, 23058430092137136384, 18519083142724387072, 4684869512372355328]
theorem e25 : enumKeys 589 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3155_b4, by decide, c3155_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3155_b9, by decide, c3155_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3155_b8, by decide, c3155_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3155_b5, by decide, c3155_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3155_b7, by decide, c3155_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3155_b6, by decide, c3155_ok6⟩, ?_⟩
  simp

def s26 : List Nat := [162129586618892288, 148618787787112448, 144115188176519168, 368939385073818402817, 147591966988185894913, 368934881474207809537, 295224466373034901505, 73877048287402393601, 295219962773424308225, 90071992580964353, 147573952589743521793, 73863537488570613761, 73859033888960020481, 76561193749184513, 72057594138591233, 147573952589676417024, 73863537488503508992, 73859033888892915712, 148618787720007680, 144115188109414400]
theorem e26 : enumKeys 589 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3156_b1, by decide, c3156_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3156_b0, by decide, c3156_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3156_b2, by decide, c3156_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3156_b9, by decide, c3156_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3156_b8, by decide, c3156_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3157_b2, by decide, c3157_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3157_b4, by decide, c3157_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3157_b3, by decide, c3157_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3157_b7, by decide, c3157_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3157_b8, by decide, c3157_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c3157_b0, by decide, c3157_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3157_b1, by decide, c3157_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3157_b5, by decide, c3157_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3157_b6, by decide, c3157_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3157_b9, by decide, c3157_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c3156_b3, by decide, c3156_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3156_b4, by decide, c3156_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3156_b5, by decide, c3156_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3156_b6, by decide, c3156_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3156_b7, by decide, c3156_ok7⟩, ?_⟩
  simp

def s27 : List Nat := [148618787720265728, 144396663086383104, 74944401399072423937, 147574234064653385729, 73863537488503767041, 78403165912893227009, 74940179274438541313, 1229482698288922625, 5769111122678382593, 78398662313282633729, 73859315363869884417, 4688247212109725697, 5764607523067789313, 1225260573655040001, 4683743612499132417, 72339069048455169, 147574234064653123600, 73863537488503504912, 78403165912892964880, 78398662313282371600, 73859315363869622288, 148618787720003600, 4688247212109463568, 4683743612498870288, 144396663086120976]
theorem e27 : enumKeys 589 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3158_b0, by decide, c3158_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3158_b1, by decide, c3158_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3159_b1, by decide, c3159_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3159_b9, by decide, c3159_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3159_b8, by decide, c3159_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3159_b7, by decide, c3159_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3159_b4, by decide, c3159_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3159_b3, by decide, c3159_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3159_b2, by decide, c3159_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3160_b0, by decide, c3160_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3160_b2, by decide, c3160_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c3160_b1, by decide, c3160_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3159_b5, by decide, c3159_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3159_b6, by decide, c3159_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3160_b3, by decide, c3160_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3160_b4, by decide, c3160_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3158_b4, by decide, c3158_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c3158_b3, by decide, c3158_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3158_b2, by decide, c3158_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 310, c3158_b5, by decide, c3158_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3158_b8, by decide, c3158_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3158_b7, by decide, c3158_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3158_b6, by decide, c3158_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c3158_b9, by decide, c3158_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3159_b0, by decide, c3159_ok0⟩, ?_⟩
  simp

def s28 : List Nat := [145241088016318464, 147575078489583321089, 73863537488503570433, 92238223968175194113, 92233720368564600833, 73860159788799819777, 18523305267391692801, 18518801667781099521, 73183493978390529, 147573952589676478720, 73863537488503570688, 73859033888892977408, 148618787720069376, 144115188109476096]
theorem e28 : enumKeys 589 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3160_b5, by decide, c3160_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3161_b3, by decide, c3161_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3161_b2, by decide, c3161_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3161_b1, by decide, c3161_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3161_b4, by decide, c3161_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3161_b6, by decide, c3161_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3161_b5, by decide, c3161_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3161_b7, by decide, c3161_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3161_b8, by decide, c3161_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c3160_b6, by decide, c3160_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3160_b7, by decide, c3160_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3160_b8, by decide, c3160_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3160_b9, by decide, c3160_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3161_b0, by decide, c3161_ok0⟩, ?_⟩
  simp

def s29 : List Nat := [162129586602180608, 148618787770400768, 144396663136518144, 368935162949167808513, 295224466373018189825, 299764094797407649793, 73877048287385681921, 78416676711775141889, 299759591197797056513, 295220244248384307201, 4701758010991640577, 78398662313332768769, 73859315363920019457, 4688247212159860737, 4683743612549267457, 72339069098590209, 78398662313265664000, 73859315363852914688, 148618787703296000, 4688247212092755968, 4683743612482162688, 144396663069413376]
theorem e29 : enumKeys 589 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c3162_b0, by decide, c3162_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c3161_b9, by decide, c3161_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3162_b1, by decide, c3162_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3163_b2, by decide, c3163_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3163_b1, by decide, c3163_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3163_b0, by decide, c3163_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3162_b9, by decide, c3162_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3162_b8, by decide, c3162_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c3163_b6, by decide, c3163_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3163_b8, by decide, c3163_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3163_b7, by decide, c3163_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c3163_b3, by decide, c3163_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3163_b5, by decide, c3163_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c3163_b4, by decide, c3163_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3163_b9, by decide, c3163_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c3164_b0, by decide, c3164_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c3162_b2, by decide, c3162_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3162_b5, by decide, c3162_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3162_b4, by decide, c3162_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c3162_b3, by decide, c3162_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c3162_b6, by decide, c3162_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3162_b7, by decide, c3162_ok7⟩, ?_⟩
  simp

def s30 : List Nat := [148618787703554048, 144396663069671424, 74940179274421829633, 1229482698272210945, 5769111122661670913, 73859315363853172737, 78398943788242632705, 4688247212093014017, 9227875636482473985, 1225260573638328321, 5764888998027788289, 9223372036871880705, 4684025087459131393, 73859315363852910608, 78398943788242370576, 148618787703291920, 4688247212092751888, 9227875636482211856, 9223372036871618576, 144396663069409296, 4684025087458869264]
theorem e30 : enumKeys 589 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3164_b1, by decide, c3164_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3164_b2, by decide, c3164_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3165_b3, by decide, c3165_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3165_b2, by decide, c3165_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3165_b1, by decide, c3165_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3165_b9, by decide, c3165_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3165_b8, by decide, c3165_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3165_b7, by decide, c3165_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3165_b6, by decide, c3165_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3165_b5, by decide, c3165_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3165_b4, by decide, c3165_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3166_b0, by decide, c3166_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c3166_b1, by decide, c3166_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3164_b7, by decide, c3164_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3164_b6, by decide, c3164_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3164_b5, by decide, c3164_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3164_b4, by decide, c3164_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3164_b3, by decide, c3164_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c3164_b8, by decide, c3164_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3165_b0, by decide, c3165_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3164_b9, by decide, c3164_ok9⟩, ?_⟩
  simp

def s31 : List Nat := [145241087999606784, 73859315363852976129, 92234001843524599809, 73860159788783108097, 78399788213172568065, 4688247212092817409, 18523305267374981121, 23062933691764441089, 23058430092153847809, 18519083142741098497, 4684869512389066753, 78398662313265725696, 73859315363852976384, 148618787703357696, 4688247212092817664, 4683743612482224384, 144396663069475072]
theorem e31 : enumKeys 589 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3166_b2, by decide, c3166_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3167_b5, by decide, c3167_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3167_b4, by decide, c3167_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3167_b3, by decide, c3167_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3167_b2, by decide, c3167_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3167_b1, by decide, c3167_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c3167_b0, by decide, c3167_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3166_b9, by decide, c3166_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3167_b6, by decide, c3167_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3167_b8, by decide, c3167_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3167_b7, by decide, c3167_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c3166_b3, by decide, c3166_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3166_b6, by decide, c3166_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3166_b5, by decide, c3166_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3166_b4, by decide, c3166_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3166_b7, by decide, c3166_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3166_b8, by decide, c3166_ok8⟩, ?_⟩
  simp

def s32 : List Nat := [162129586585468928, 144396663119806464, 295220244248367595521, 299759872672757055489, 4701758010974928897, 9241386435364388865, 9223372036922015745, 4684025087509266433, 9223372036854910976, 144396663052701696, 4684025087442161664]
theorem e32 : enumKeys 589 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c3167_b9, by decide, c3167_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3168_b0, by decide, c3168_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3168_b7, by decide, c3168_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3168_b6, by decide, c3168_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3168_b5, by decide, c3168_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3168_b4, by decide, c3168_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3168_b8, by decide, c3168_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3168_b9, by decide, c3168_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c3168_b1, by decide, c3168_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3168_b3, by decide, c3168_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3168_b2, by decide, c3168_ok2⟩, ?_⟩
  simp

def s33 : List Nat := [144396663052959744, 1225260573621616641, 5764888998011076609, 4684025087442419713, 9223653511831879681, 144396663052697616, 4684025087442157584, 9223653511831617552]
theorem e33 : enumKeys 589 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3169_b0, by decide, c3169_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3169_b5, by decide, c3169_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3169_b4, by decide, c3169_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3169_b7, by decide, c3169_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3169_b6, by decide, c3169_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3169_b3, by decide, c3169_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3169_b2, by decide, c3169_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3169_b1, by decide, c3169_ok1⟩, ?_⟩
  simp

def s34 : List Nat := [145241087982895104, 4684025087442223105, 18519083142724386817, 23058711567113846785, 4684869512372355073, 9224497936761815041, 9223372036854972672, 144396663052763392, 4684025087442223360]
theorem e34 : enumKeys 589 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c3169_b8, by decide, c3169_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3170_b6, by decide, c3170_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3170_b5, by decide, c3170_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3170_b4, by decide, c3170_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3170_b3, by decide, c3170_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3170_b2, by decide, c3170_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c3169_b9, by decide, c3169_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3170_b1, by decide, c3170_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3170_b0, by decide, c3170_ok0⟩, ?_⟩
  simp

def s35 : List Nat := [147578456189303783425, 147573952589693190145, 73863537488520282113, 73859033888909688833, 148618787736780801, 144115188126187521]
theorem e35 : enumKeys 589 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3170_b7, by decide, c3170_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c3170_b8, by decide, c3170_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3170_b9, by decide, c3170_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c3171_b0, by decide, c3171_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3171_b1, by decide, c3171_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3171_b2, by decide, c3171_ok2⟩, ?_⟩
  simp

def s36 : List Nat := [147574234064653189121, 73863537488503570433, 78403165912893030401, 78398662313282437121, 73859315363869687809, 148618787720069121, 4688247212109529089, 4683743612498935809, 144396663086186497]
theorem e36 : enumKeys 589 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3171_b5, by decide, c3171_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c3171_b4, by decide, c3171_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3171_b3, by decide, c3171_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c3171_b6, by decide, c3171_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3171_b9, by decide, c3171_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3171_b8, by decide, c3171_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c3171_b7, by decide, c3171_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3172_b0, by decide, c3172_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3172_b1, by decide, c3172_ok1⟩, ?_⟩
  simp

def s37 : List Nat := [73859315363852976129, 78398943788242436097, 148618787703357441, 4688247212092817409, 9227875636482277377, 9223372036871684097, 144396663069474817, 4684025087458934785]
theorem e37 : enumKeys 589 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3172_b6, by decide, c3172_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3172_b5, by decide, c3172_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c3172_b4, by decide, c3172_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c3172_b3, by decide, c3172_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3172_b2, by decide, c3172_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3172_b7, by decide, c3172_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3172_b9, by decide, c3172_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3172_b8, by decide, c3172_ok8⟩, ?_⟩
  simp

def s38 : List Nat := [144396663052763137, 4684025087442223105, 9223653511831683073]
theorem e38 : enumKeys 589 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3173_b2, by decide, c3173_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c3173_b1, by decide, c3173_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c3173_b0, by decide, c3173_ok0⟩, ?_⟩
  simp

/-- every enumerated key with left type `589` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 589 mR,
    (589 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 589 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K25
end Grid3.Three.Cert
