import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C3173
import Grid3.Three.Cert.Data.C3174
import Grid3.Three.Cert.Data.C3175
import Grid3.Three.Cert.Data.C3176
import Grid3.Three.Cert.Data.C3177
import Grid3.Three.Cert.Data.C3178
import Grid3.Three.Cert.Data.C3179
import Grid3.Three.Cert.Data.C3180
import Grid3.Three.Cert.Data.C3181
import Grid3.Three.Cert.Data.C3182
import Grid3.Three.Cert.Data.C3183
import Grid3.Three.Cert.Data.C3184
import Grid3.Three.Cert.Data.C3185
import Grid3.Three.Cert.Data.C3186
import Grid3.Three.Cert.Data.C3187
import Grid3.Three.Cert.Data.C3188
import Grid3.Three.Cert.Data.C3189
import Grid3.Three.Cert.Data.C3190
import Grid3.Three.Cert.Data.C3191
import Grid3.Three.Cert.Data.C3192
import Grid3.Three.Cert.Data.C3193
import Grid3.Three.Cert.Data.C3194
import Grid3.Three.Cert.Data.C3195
import Grid3.Three.Cert.Data.C3196
import Grid3.Three.Cert.Data.C3197
import Grid3.Three.Cert.Data.C3198
import Grid3.Three.Cert.Data.C3199
import Grid3.Three.Cert.Data.C3200
import Grid3.Three.Cert.Data.C3201
import Grid3.Three.Cert.Data.C3202
import Grid3.Three.Cert.Data.C3203
import Grid3.Three.Cert.Data.C3204
import Grid3.Three.Cert.Data.C3205
import Grid3.Three.Cert.Data.C3206
import Grid3.Three.Cert.Data.C3207
import Grid3.Three.Cert.Data.C3208
import Grid3.Three.Cert.Data.C3209
import Grid3.Three.Cert.Data.C3210
import Grid3.Three.Cert.Data.C3211
import Grid3.Three.Cert.Data.C3212
import Grid3.Three.Cert.Data.C3213
import Grid3.Three.Cert.Data.C3214
import Grid3.Three.Cert.Data.C3215
import Grid3.Three.Cert.Data.C3216
import Grid3.Three.Cert.Data.C3217
import Grid3.Three.Cert.Data.C3218
import Grid3.Three.Cert.Data.C3219
import Grid3.Three.Cert.Data.C3220
import Grid3.Three.Cert.Data.C3221
import Grid3.Three.Cert.Data.C3222
import Grid3.Three.Cert.Data.C3223
import Grid3.Three.Cert.Data.C3224
import Grid3.Three.Cert.Data.C3225
import Grid3.Three.Cert.Data.C3226
import Grid3.Three.Cert.Data.C3227
import Grid3.Three.Cert.Data.C3228
import Grid3.Three.Cert.Data.C3229
import Grid3.Three.Cert.Data.C3230
import Grid3.Three.Cert.Data.C3231
import Grid3.Three.Cert.Data.C3232
import Grid3.Three.Cert.Data.C3233
import Grid3.Three.Cert.Data.C3234
import Grid3.Three.Cert.Data.C3235
import Grid3.Three.Cert.Data.C3236
import Grid3.Three.Cert.Data.C3237
import Grid3.Three.Cert.Data.C3238
import Grid3.Three.Cert.Data.C3239
import Grid3.Three.Cert.Data.C3240
import Grid3.Three.Cert.Data.C3241
import Grid3.Three.Cert.Data.C3242
import Grid3.Three.Cert.Data.C3243
import Grid3.Three.Cert.Data.C3244

/-! Seam keys with left type `6146` (type index 26): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K26

def s00 : List Nat := [79237833920821254626941599744, 79232998217542796110242779136, 9671406556917033397653504, 79228162514264337593543958528, 4835703278458516698832896]
theorem e00 : enumKeys 6146 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 90, c3173_b3, by decide, c3173_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 96, c3173_b4, by decide, c3173_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 102, c3173_b5, by decide, c3173_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 104, c3173_b6, by decide, c3173_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 112, c3173_b7, by decide, c3173_ok7⟩, ?_⟩
  simp

def s01 : List Nat := [79228483635185172729418481664, 4956614749885911094876176384, 314622944554707242717282304, 79229673671538855880012333072, 19812178563299446572378488848, 4957804786239594245470027792, 79229390329549883701299511552, 19811895221310474393665667328, 315529638919418214598312192, 79229371440083952222718656784, 19811876331844542915084812560, 6044629098073145873531152, 19807361749486919534260523008, 4952987972427067207352061952, 310996167095863355193167872, 19807342860020988055679668240, 4952969082961135728771207184, 1511157274518286468386832, 19807059518032015876966846720, 310693935640959697899491584, 1227815285546107755565312]
theorem e01 : enumKeys 6146 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c3174_b0, by decide, c3174_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c3173_b9, by decide, c3173_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3173_b8, by decide, c3173_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3175_b2, by decide, c3175_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c3175_b1, by decide, c3175_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3175_b0, by decide, c3175_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 111, c3174_b6, by decide, c3174_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c3174_b5, by decide, c3174_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3174_b4, by decide, c3174_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3175_b7, by decide, c3175_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c3175_b6, by decide, c3175_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3175_b8, by decide, c3175_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3174_b3, by decide, c3174_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3174_b2, by decide, c3174_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c3174_b1, by decide, c3174_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3175_b4, by decide, c3175_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c3175_b3, by decide, c3175_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3175_b5, by decide, c3175_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c3174_b8, by decide, c3174_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 121, c3174_b7, by decide, c3174_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3174_b9, by decide, c3174_ok9⟩, ?_⟩
  simp

def s02 : List Nat := [79233017107008727588823629824, 319156416378262102122430464, 79233073775406522024566194192, 1247611445842297308296773648, 79228256961593994986448228352, 1242794632029770270178807808, 314396270963529499747028992, 79228238072128063507867373584, 1242775742563838791597953040, 4911261142184431022247952, 1237958928751311753479987200, 309560567685070983048208384, 94447329657392904282112]
theorem e02 : enumKeys 6146 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3176_b0, by decide, c3176_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3175_b9, by decide, c3175_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c3176_b8, by decide, c3176_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3176_b7, by decide, c3176_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c3176_b3, by decide, c3176_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 109, c3176_b2, by decide, c3176_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3176_b1, by decide, c3176_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c3177_b0, by decide, c3177_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c3176_b9, by decide, c3176_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3177_b1, by decide, c3177_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c3176_b5, by decide, c3176_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3176_b4, by decide, c3176_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3176_b6, by decide, c3176_ok6⟩, ?_⟩
  simp

def s03 : List Nat := [4951797936073384056758206464, 309806130742180204599312384, 4951854604471178492500770832, 1238261160206215410773655568, 19807361749486919534260518928, 309862799139974640341876752, 4952987972427067207352057872, 310996167095863355193163792, 19807418417884713970003083296, 4953044640824861643094622240, 1239451196559898561367506976, 1237977818217243232060834048, 19807078407497947355547697408, 309579457151002461629055232, 310712825106891176480342272, 19807135075895741791290261776, 1239167854570926382654685456, 310769493504685612222906640]
theorem e03 : enumKeys 6146 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3177_b3, by decide, c3177_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c3177_b2, by decide, c3177_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3178_b3, by decide, c3178_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c3178_b2, by decide, c3178_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3178_b1, by decide, c3178_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3177_b9, by decide, c3177_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3178_b0, by decide, c3178_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3177_b8, by decide, c3177_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3178_b9, by decide, c3178_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3178_b8, by decide, c3178_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c3178_b7, by decide, c3178_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3177_b7, by decide, c3177_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3177_b6, by decide, c3177_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3177_b5, by decide, c3177_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3177_b4, by decide, c3177_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c3178_b6, by decide, c3178_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3178_b5, by decide, c3178_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c3178_b4, by decide, c3178_ok4⟩, ?_⟩
  simp

def s04 : List Nat := [79228200293196200550705659904, 314339602565735064004460544, 79228256961593994986448224272, 1242794632029770270178803728, 314396270963529499747024912, 79228313629991789422190788640, 1242851300427564705921368096, 1237977818217243232060837888, 309579457151002461629059072, 1238034486615037667803402256, 309636125548796897371623440]
theorem e04 : enumKeys 6146 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3179_b1, by decide, c3179_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3179_b0, by decide, c3179_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3179_b6, by decide, c3179_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3179_b5, by decide, c3179_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3179_b4, by decide, c3179_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3180_b0, by decide, c3180_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3179_b9, by decide, c3179_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3179_b3, by decide, c3179_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3179_b2, by decide, c3179_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3179_b8, by decide, c3179_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3179_b7, by decide, c3179_ok7⟩, ?_⟩
  simp

def s05 : List Nat := [309522788753208025886490624, 1237977818217243232060833808, 309579457151002461629054992, 1238034486615037667803398176, 309636125548796897371619360, 1238091155012832103545962528]
theorem e05 : enumKeys 6146 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c3180_b1, by decide, c3180_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3180_b3, by decide, c3180_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c3180_b2, by decide, c3180_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3180_b6, by decide, c3180_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c3180_b5, by decide, c3180_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c3180_b4, by decide, c3180_ok4⟩, ?_⟩
  simp

def s06 : List Nat := [79233300448997699767536451584, 4961431563698438132994146304, 79233002939909278979887988992, 87042659012253300578844928, 79228469468085724120482844672, 4956600582786462485940539392, 82509187188698441173700608, 79228167236630820463189168384, 82206955733794783880024320, 4840425644941386344042752, 4951764879508003969241718784, 77673483910239924474880000, 306953821386526938898432]
theorem e06 : enumKeys 6146 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3180_b8, by decide, c3180_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3180_b7, by decide, c3180_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 119, c3181_b6, by decide, c3181_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3181_b5, by decide, c3181_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3181_b1, by decide, c3181_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 121, c3181_b0, by decide, c3181_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c3180_b9, by decide, c3180_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3181_b8, by decide, c3181_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c3181_b7, by decide, c3181_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c3181_b9, by decide, c3181_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c3181_b3, by decide, c3181_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3181_b2, by decide, c3181_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3181_b4, by decide, c3181_ok4⟩, ?_⟩
  simp

def s07 : List Nat := [4952081278062356235471028224, 310089472731152383312134144, 4952067110962907626535387152, 77975715365143581768548368, 19807645091475891712973340688, 4953271314416039386064879632, 4951783768973935447822565632, 309791963642731595663671552, 77692373376171403055726848, 19807361749486919534260519168, 4952987972427067207352058112, 310996167095863355193164032, 19807347582387470925324878096, 4952973805327618598416417040, 78882409729854553649578256, 19807064240398498746612056576, 310698658007442567544701440, 78599067740882374936756736]
theorem e07 : enumKeys 6146 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3182_b1, by decide, c3182_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3182_b0, by decide, c3182_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3183_b4, by decide, c3183_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3183_b3, by decide, c3183_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3183_b2, by decide, c3183_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3183_b1, by decide, c3183_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3182_b7, by decide, c3182_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3182_b6, by decide, c3182_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3182_b5, by decide, c3182_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c3182_b4, by decide, c3182_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3182_b3, by decide, c3182_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3182_b2, by decide, c3182_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3183_b7, by decide, c3183_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3183_b6, by decide, c3183_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3183_b5, by decide, c3183_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3183_b0, by decide, c3183_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3182_b9, by decide, c3182_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3182_b8, by decide, c3182_ok8⟩, ?_⟩
  simp

def s08 : List Nat := [79228483635185172729418481664, 4956614749885911094876176384, 314622944554707242717282304, 79228469468085724120482840592, 79228540303582967165161046032, 4956600582786462485940535312, 4956671418283705530618740752, 82509187188698441173696528, 1243077974018742448891625488, 79228186126096751941770019072, 79228256961593994986448224512, 314325435466286455068819712, 82225845199726262460875008, 1242794632029770270178803968, 314396270963529499747025152, 79228242794494546377512583440, 1242780464930321661243162896, 82282513597520698203439376, 4951783768973935447822569472, 4951854604471178492500774912, 309791963642731595663675392, 77692373376171403055730688, 1238261160206215410773659648, 309862799139974640341880832, 4951840437371729883565133840, 1238246993106766801838018576, 77749041773965838798295056, 1237963651117794623125197056, 309565290051553852693418240, 77465699784993660085473536]
theorem e08 : enumKeys 6146 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c3184_b0, by decide, c3184_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3183_b9, by decide, c3183_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3183_b8, by decide, c3183_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3186_b1, by decide, c3186_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3185_b9, by decide, c3185_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3186_b0, by decide, c3186_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c3185_b8, by decide, c3185_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3185_b7, by decide, c3185_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3185_b6, by decide, c3185_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3185_b2, by decide, c3185_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3185_b0, by decide, c3185_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3185_b1, by decide, c3185_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3184_b9, by decide, c3184_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3184_b8, by decide, c3184_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3184_b7, by decide, c3184_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c3186_b7, by decide, c3186_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3186_b6, by decide, c3186_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3186_b5, by decide, c3186_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3184_b6, by decide, c3184_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3184_b4, by decide, c3184_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c3184_b5, by decide, c3184_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3184_b3, by decide, c3184_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c3184_b2, by decide, c3184_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3184_b1, by decide, c3184_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c3186_b4, by decide, c3186_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3186_b3, by decide, c3186_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3186_b2, by decide, c3186_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c3185_b5, by decide, c3185_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c3185_b4, by decide, c3185_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3185_b3, by decide, c3185_ok3⟩, ?_⟩
  simp

def s09 : List Nat := [4951797936073384056758206464, 309806130742180204599312384, 4951783768973935447822565392, 4951854604471178492500770832, 309791963642731595663671312, 77692373376171403055726608, 1238261160206215410773655568, 309862799139974640341876752, 1238020319515589058867757088, 4951840437371729883565129760, 77522368182788095828033568, 4951911272868972928243335200, 1238246993106766801838014496, 77749041773965838798290976, 1238317828604009846516219936, 309508621653759416950849792, 77409031387199224342905088, 1237977818217243232060834048, 309579457151002461629055232, 1237963651117794623125192976, 309565290051553852693414160, 1238020319515589058867757328, 77465699784993660085469456, 1238034486615037667803398416, 77522368182788095828033808, 309636125548796897371619600]
theorem e09 : enumKeys 6146 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c3186_b9, by decide, c3186_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3186_b8, by decide, c3186_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c3187_b9, by decide, c3187_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c3187_b7, by decide, c3187_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c3187_b8, by decide, c3187_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c3187_b6, by decide, c3187_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c3187_b5, by decide, c3187_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c3187_b4, by decide, c3187_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3189_b3, by decide, c3189_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3189_b2, by decide, c3189_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c3189_b0, by decide, c3189_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3188_b9, by decide, c3188_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3189_b1, by decide, c3189_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c3188_b8, by decide, c3188_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c3188_b7, by decide, c3188_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3187_b3, by decide, c3187_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3187_b2, by decide, c3187_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3187_b1, by decide, c3187_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3187_b0, by decide, c3187_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3188_b6, by decide, c3188_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3188_b5, by decide, c3188_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c3188_b4, by decide, c3188_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c3188_b3, by decide, c3188_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3188_b2, by decide, c3188_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c3188_b1, by decide, c3188_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3188_b0, by decide, c3188_ok0⟩, ?_⟩
  simp

def s10 : List Nat := [79228766977174144908131303424, 4956898091874883273588998144, 79228469468085724120482840832, 4956600582786462485940535552, 82509187188698441173696768, 79228171958997303332834378240, 82211678100277653525234176, 4952067110962907626535391232, 77975715365143581768552448, 4951769601874486838886928640, 77678206276722794120089856]
theorem e10 : enumKeys 6146 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3189_b5, by decide, c3189_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c3189_b4, by decide, c3189_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3190_b0, by decide, c3190_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3189_b9, by decide, c3189_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3189_b8, by decide, c3189_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3190_b4, by decide, c3190_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c3190_b3, by decide, c3190_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3189_b7, by decide, c3189_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3189_b6, by decide, c3189_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c3190_b2, by decide, c3190_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3190_b1, by decide, c3190_ok1⟩, ?_⟩
  simp

def s11 : List Nat := [4952081278062356235471028224, 310089472731152383312134144, 4952067110962907626535387152, 4952137946460150671213592592, 77975715365143581768548368, 1238544502195187589486477328, 4951783768973935447822565632, 4951854604471178492500771072, 309791963642731595663671552, 77692373376171403055726848, 1238261160206215410773655808, 309862799139974640341876992, 1237949484018346014189551888, 4951769601874486838886924560, 77451532685545051149828368, 4951840437371729883565130000, 77678206276722794120085776, 1238246993106766801838014736, 77749041773965838798291216, 309494454554310808015208960, 1237949484018346014189552128, 77394864287750615407264256, 1237963651117794623125193216, 77451532685545051149828608, 309565290051553852693414400, 77465699784993660085469696]
theorem e11 : enumKeys 6146 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c3190_b6, by decide, c3190_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c3190_b5, by decide, c3190_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c3192_b3, by decide, c3192_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c3192_b2, by decide, c3192_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c3192_b1, by decide, c3192_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c3192_b0, by decide, c3192_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c3191_b2, by decide, c3191_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c3191_b0, by decide, c3191_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3191_b1, by decide, c3191_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3190_b9, by decide, c3190_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3190_b8, by decide, c3190_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3190_b7, by decide, c3190_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3193_b0, by decide, c3193_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c3192_b9, by decide, c3192_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3192_b8, by decide, c3192_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3192_b7, by decide, c3192_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3192_b6, by decide, c3192_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3192_b5, by decide, c3192_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3192_b4, by decide, c3192_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3191_b9, by decide, c3191_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3191_b8, by decide, c3191_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3191_b7, by decide, c3191_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3191_b6, by decide, c3191_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c3191_b5, by decide, c3191_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3191_b4, by decide, c3191_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c3191_b3, by decide, c3191_ok3⟩, ?_⟩
  simp

def s12 : List Nat := [4952364620051328414183849984, 4952067110962907626535387392, 77975715365143581768548608, 77380697188302006471623168, 4951769601874486838886924800, 77678206276722794120086016]
theorem e12 : enumKeys 6146 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c3193_b1, by decide, c3193_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3193_b3, by decide, c3193_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c3193_b2, by decide, c3193_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3193_b6, by decide, c3193_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3193_b5, by decide, c3193_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3193_b4, by decide, c3193_ok4⟩, ?_⟩
  simp

def s13 : List Nat := [29014219670751100192948224, 79234207143362410739417481217, 19816712035123001431783636993, 25387442211907212668833792, 79229371440083952222718660609, 19811876331844542915084816385, 6044629098073145873534977, 19807040628566084398385995776, 20551738933448695970013184]
theorem e13 : enumKeys 6146 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3193_b7, by decide, c3193_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 87, c3194_b2, by decide, c3194_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 96, c3194_b1, by decide, c3194_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c3193_b8, by decide, c3193_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 91, c3194_b4, by decide, c3194_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 103, c3194_b3, by decide, c3194_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 98, c3194_b5, by decide, c3194_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3193_b9, by decide, c3193_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c3194_b0, by decide, c3194_ok0⟩, ?_⟩
  simp

def s14 : List Nat := [19663934034669202669830144, 19807361749486919534260518913, 4952987972427067207352057857, 310996167095863355193163777, 20853970388352353263681552, 19808551785840602684854370321, 4954178008780750357945909265, 20570628399380174550860032, 19808268443851630506141548801, 311902861460574327074193665, 19808249554385699027560694032, 21760664753063325144711440]
theorem e14 : enumKeys 6146 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3194_b6, by decide, c3194_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3195_b3, by decide, c3195_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c3195_b2, by decide, c3195_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c3195_b1, by decide, c3195_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c3194_b8, by decide, c3194_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3195_b7, by decide, c3195_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 104, c3195_b6, by decide, c3195_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3194_b7, by decide, c3194_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c3195_b5, by decide, c3195_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3195_b4, by decide, c3195_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3194_b9, by decide, c3194_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3195_b0, by decide, c3195_ok0⟩, ?_⟩
  simp

def s15 : List Nat := [24197405858224062074978304, 79228256961593994986448224257, 79229390329549883701299511297, 1242794632029770270178803713, 19811895221310474393665667073, 314396270963529499747024897, 315529638919418214598311937, 24254074256018497817542672, 25387442211907212668829712, 79229446997947678137042075665, 19811951889708268829408231441, 1243984668383453420772655121, 19437260443491459699576832, 20570628399380174550863872, 19807135075895741791290265601, 1239167854570926382654689281, 310769493504685612222910465, 19807116186429810312709410832, 1239148965104994904073834512, 20627296797174610293428240]
theorem e15 : enumKeys 6146 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3195_b8, by decide, c3195_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3197_b1, by decide, c3197_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 111, c3197_b0, by decide, c3197_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3196_b9, by decide, c3196_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c3196_b8, by decide, c3196_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3196_b7, by decide, c3196_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3196_b6, by decide, c3196_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3196_b2, by decide, c3196_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c3196_b1, by decide, c3196_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 98, c3197_b7, by decide, c3197_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3197_b6, by decide, c3197_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 103, c3197_b5, by decide, c3197_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3196_b0, by decide, c3196_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c3195_b9, by decide, c3195_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3197_b4, by decide, c3197_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 101, c3197_b3, by decide, c3197_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c3197_b2, by decide, c3197_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3196_b4, by decide, c3196_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c3196_b3, by decide, c3196_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3196_b5, by decide, c3196_ok5⟩, ?_⟩
  simp

def s16 : List Nat := [19380592045697023957008384, 1237977818217243232060833793, 19807078407497947355547697153, 309579457151002461629054977, 310712825106891176480342017, 19437260443491459699572752, 20570628399380174550859792, 1238034486615037667803398161, 19807135075895741791290261521, 309636125548796897371619345, 19807191744293536227032825873, 1239167854570926382654685201, 310769493504685612222906385, 1239224522968720818397249553, 19493928841285895442137120, 19807191744293536227032825888, 20627296797174610293424160, 1239224522968720818397249568]
theorem e16 : enumKeys 6146 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3197_b8, by decide, c3197_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3198_b8, by decide, c3198_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3198_b7, by decide, c3198_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3198_b6, by decide, c3198_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3198_b5, by decide, c3198_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3198_b0, by decide, c3198_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3197_b9, by decide, c3197_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c3199_b5, by decide, c3199_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c3199_b4, by decide, c3199_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 136, c3199_b2, by decide, c3199_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c3199_b1, by decide, c3199_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3199_b3, by decide, c3199_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c3199_b0, by decide, c3199_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 125, c3198_b9, by decide, c3198_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c3198_b4, by decide, c3198_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3198_b3, by decide, c3198_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3198_b2, by decide, c3198_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c3198_b1, by decide, c3198_ok1⟩, ?_⟩
  simp

def s17 : List Nat := [24480747847196240787800064, 79228469468085724120482840577, 79229673671538855880012333057, 4956600582786462485940535297, 82509187188698441173696513, 19812178563299446572378488833, 4957804786239594245470027777, 24183238758775453139337472, 25387442211907212668829952, 79229376162450435092363870465, 19811881054211025784730026241, 83415881553409413054726401, 19649766935220593734193152, 20853970388352353263685632, 19807347582387470925324881921, 4952973805327618598416420865, 78882409729854553649582081, 19807045350932567268031205632, 78580178274950896355905792, 20556461299931565615223040]
theorem e17 : enumKeys 6146 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3199_b6, by decide, c3199_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c3200_b9, by decide, c3200_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3200_b7, by decide, c3200_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c3200_b8, by decide, c3200_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c3200_b6, by decide, c3200_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c3200_b5, by decide, c3200_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c3200_b4, by decide, c3200_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3200_b0, by decide, c3200_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3199_b9, by decide, c3199_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3201_b5, by decide, c3201_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3201_b4, by decide, c3201_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3201_b3, by decide, c3201_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3199_b8, by decide, c3199_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c3199_b7, by decide, c3199_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3201_b2, by decide, c3201_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 113, c3201_b1, by decide, c3201_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3201_b0, by decide, c3201_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c3200_b2, by decide, c3200_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3200_b1, by decide, c3200_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c3200_b3, by decide, c3200_ok3⟩, ?_⟩
  simp

def s18 : List Nat := [29014219670751100192948224, 79233002939909278979887988737, 79233073775406522024566194177, 87042659012253300578844673, 1247611445842297308296773633, 24183238758775453139341312, 24254074256018497817546752, 79228242794494546377512587265, 1242780464930321661243166721, 82282513597520698203443201, 1237944761651863144544346112, 77446810319062181504622592, 19423093344042850763939840]
theorem e18 : enumKeys 6146 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3201_b6, by decide, c3201_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 119, c3202_b5, by decide, c3202_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3202_b4, by decide, c3202_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3202_b3, by decide, c3202_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3202_b2, by decide, c3202_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3201_b8, by decide, c3201_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c3201_b7, by decide, c3201_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 107, c3202_b8, by decide, c3202_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 109, c3202_b7, by decide, c3202_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c3202_b6, by decide, c3202_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3202_b0, by decide, c3202_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3201_b9, by decide, c3201_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c3202_b1, by decide, c3202_ok1⟩, ?_⟩
  simp

def s19 : List Nat := [19663934034669202669830144, 4951783768973935447822565377, 4951854604471178492500770817, 309791963642731595663671297, 77692373376171403055726593, 1238261160206215410773655553, 19807361749486919534260518913, 309862799139974640341876737, 4952987972427067207352057857, 310996167095863355193163777, 19649766935220593734189072, 19720602432463638412394512, 20853970388352353263681552, 4951840437371729883565129745, 19807120908796293182354620433, 1238246993106766801838014481, 19807347582387470925324877841, 77749041773965838798290961, 19807418417884713970003083281, 1239153687471477773719044113, 4952973805327618598416416785, 78655736138676810679320593, 4953044640824861643094622225, 78882409729854553649578001, 1239451196559898561367506961, 19366424946248415021367552, 19437260443491459699572992, 20570628399380174550860032, 1237963651117794623125192961, 19807064240398498746612056321, 309565290051553852693414145, 19807120908796293182354620673, 77465699784993660085469441, 19807135075895741791290261761, 310698658007442567544701185, 1239153687471477773719044353, 78599067740882374936756481, 1239167854570926382654685441, 78655736138676810679320833, 310769493504685612222906625, 19423093344042850763931920, 19807120908796293182354620688, 20556461299931565615218960, 1239153687471477773719044368, 20627296797174610293424400, 78655736138676810679320848]
theorem e19 : enumKeys 6146 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3202_b9, by decide, c3202_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3205_b0, by decide, c3205_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3204_b8, by decide, c3204_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3204_b9, by decide, c3204_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3204_b7, by decide, c3204_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3204_b6, by decide, c3204_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c3204_b5, by decide, c3204_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3204_b3, by decide, c3204_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3204_b4, by decide, c3204_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3204_b2, by decide, c3204_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c3203_b5, by decide, c3203_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c3203_b4, by decide, c3203_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c3203_b3, by decide, c3203_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3207_b4, by decide, c3207_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3207_b3, by decide, c3207_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3207_b2, by decide, c3207_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3207_b1, by decide, c3207_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3206_b8, by decide, c3206_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c3206_b7, by decide, c3206_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3207_b0, by decide, c3207_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3206_b9, by decide, c3206_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3206_b6, by decide, c3206_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3206_b5, by decide, c3206_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3206_b4, by decide, c3206_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c3206_b3, by decide, c3206_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c3203_b2, by decide, c3203_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3203_b1, by decide, c3203_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c3203_b0, by decide, c3203_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3206_b2, by decide, c3206_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3206_b1, by decide, c3206_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3206_b0, by decide, c3206_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3205_b9, by decide, c3205_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3205_b6, by decide, c3205_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3205_b5, by decide, c3205_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3205_b8, by decide, c3205_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3205_b7, by decide, c3205_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3205_b4, by decide, c3205_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3205_b3, by decide, c3205_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3205_b2, by decide, c3205_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3205_b1, by decide, c3205_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c3204_b1, by decide, c3204_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3204_b0, by decide, c3204_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3203_b9, by decide, c3203_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3203_b8, by decide, c3203_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3203_b7, by decide, c3203_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3203_b6, by decide, c3203_ok6⟩, ?_⟩
  simp

def s20 : List Nat := [24197405858224062074978304, 79228186126096751941770018817, 79228256961593994986448224257, 314325435466286455068819457, 82225845199726262460874753, 1242794632029770270178803713, 314396270963529499747024897, 24183238758775453139337232, 24254074256018497817542672, 1238020319515589058867757073, 79228242794494546377512583185, 77522368182788095828033553, 79228313629991789422190788625, 1242780464930321661243162641, 82282513597520698203439121, 1242851300427564705921368081, 19366424946248415021371392, 19437260443491459699576832, 1237963651117794623125196801, 309565290051553852693417985, 1238020319515589058867761153, 77465699784993660085473281, 1238034486615037667803402241, 77522368182788095828037633, 309636125548796897371623425, 19423093344042850763935760, 1238020319515589058867761168, 19493928841285895442141200, 77522368182788095828037648]
theorem e20 : enumKeys 6146 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3207_b5, by decide, c3207_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 143, c3208_b9, by decide, c3208_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3208_b7, by decide, c3208_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3208_b8, by decide, c3208_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3208_b6, by decide, c3208_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3208_b5, by decide, c3208_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c3208_b4, by decide, c3208_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3207_b9, by decide, c3207_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c3207_b8, by decide, c3207_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3210_b3, by decide, c3210_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c3210_b2, by decide, c3210_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3210_b0, by decide, c3210_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3209_b9, by decide, c3209_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3210_b1, by decide, c3210_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3209_b8, by decide, c3209_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3209_b7, by decide, c3209_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3207_b7, by decide, c3207_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c3207_b6, by decide, c3207_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c3209_b6, by decide, c3209_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c3209_b5, by decide, c3209_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 135, c3209_b4, by decide, c3209_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3209_b3, by decide, c3209_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3209_b2, by decide, c3209_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3209_b1, by decide, c3209_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3209_b0, by decide, c3209_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3208_b3, by decide, c3208_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3208_b2, by decide, c3208_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3208_b1, by decide, c3208_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3208_b0, by decide, c3208_ok0⟩, ?_⟩
  simp

def s21 : List Nat := [19380592045697023957008384, 309508621653759416950849537, 77409031387199224342904833, 1237977818217243232060833793, 309579457151002461629054977, 19366424946248415021367312, 19437260443491459699572752, 1237963651117794623125192721, 309565290051553852693413905, 1238020319515589058867757073, 77465699784993660085469201, 1238034486615037667803398161, 77522368182788095828033553, 309636125548796897371619345, 1238091155012832103545962513, 19423093344042850763931680, 1238020319515589058867757088, 19493928841285895442137120, 77522368182788095828033568, 1238091155012832103545962528]
theorem e21 : enumKeys 6146 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3210_b4, by decide, c3210_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3211_b5, by decide, c3211_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3211_b4, by decide, c3211_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3211_b3, by decide, c3211_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3211_b2, by decide, c3211_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3210_b6, by decide, c3210_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3210_b5, by decide, c3210_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3212_b3, by decide, c3212_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3212_b2, by decide, c3212_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c3212_b1, by decide, c3212_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c3212_b0, by decide, c3212_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3211_b9, by decide, c3211_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c3211_b8, by decide, c3211_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3211_b7, by decide, c3211_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3211_b6, by decide, c3211_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3211_b1, by decide, c3211_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3211_b0, by decide, c3211_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c3210_b9, by decide, c3210_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c3210_b8, by decide, c3210_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c3210_b7, by decide, c3210_ok7⟩, ?_⟩
  simp

def s22 : List Nat := [19947276023641381382651904, 4952067110962907626535387137, 77975715365143581768548353, 19807645091475891712973340673, 4953271314416039386064879617, 19649766935220593734189312, 20853970388352353263681792, 4951769601874486838886924545, 19807050073299050137676415233, 77678206276722794120085761, 19807347582387470925324878081, 78584900641433766001115393, 4952973805327618598416417025, 78882409729854553649578241, 19352257846799806085726720, 19807050073299050137676415488, 20556461299931565615219200, 78584900641433766001115648]
theorem e22 : enumKeys 6146 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c3212_b4, by decide, c3212_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3213_b4, by decide, c3213_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c3213_b3, by decide, c3213_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3213_b2, by decide, c3213_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c3213_b1, by decide, c3213_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3212_b6, by decide, c3212_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c3212_b5, by decide, c3212_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3214_b1, by decide, c3214_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3214_b0, by decide, c3214_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3213_b9, by decide, c3213_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3213_b8, by decide, c3213_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3213_b7, by decide, c3213_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3213_b6, by decide, c3213_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3213_b5, by decide, c3213_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3213_b0, by decide, c3213_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3212_b9, by decide, c3212_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3212_b8, by decide, c3212_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3212_b7, by decide, c3212_ok7⟩, ?_⟩
  simp

def s23 : List Nat := [24480747847196240787800064, 79228469468085724120482840577, 79228540303582967165161046017, 4956600582786462485940535297, 4956671418283705530618740737, 82509187188698441173696513, 1243077974018742448891625473, 24183238758775453139337472, 24254074256018497817542912, 1237949484018346014189551873, 79228171958997303332834377985, 77451532685545051149828353, 79228242794494546377512583425, 82211678100277653525233921, 1242780464930321661243162881, 82282513597520698203439361, 19649766935220593734193152, 19720602432463638412398592, 1237949484018346014189555713, 4951769601874486838886928385, 77451532685545051149832193, 4951840437371729883565133825, 77678206276722794120089601, 1238246993106766801838018561, 77749041773965838798295041, 19352257846799806085730560, 1237949484018346014189555968, 19423093344042850763936000, 77451532685545051149832448]
theorem e23 : enumKeys 6146 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c3214_b2, by decide, c3214_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3215_b6, by decide, c3215_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3215_b4, by decide, c3215_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3215_b5, by decide, c3215_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3215_b3, by decide, c3215_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3215_b2, by decide, c3215_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3215_b1, by decide, c3215_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c3214_b6, by decide, c3214_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3214_b5, by decide, c3214_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3217_b0, by decide, c3217_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3216_b9, by decide, c3216_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3216_b8, by decide, c3216_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3216_b7, by decide, c3216_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c3216_b6, by decide, c3216_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3216_b5, by decide, c3216_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3216_b4, by decide, c3216_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3214_b4, by decide, c3214_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3214_b3, by decide, c3214_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3216_b3, by decide, c3216_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c3216_b2, by decide, c3216_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3216_b1, by decide, c3216_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c3216_b0, by decide, c3216_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3215_b9, by decide, c3215_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3215_b8, by decide, c3215_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3215_b7, by decide, c3215_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3215_b0, by decide, c3215_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3214_b9, by decide, c3214_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c3214_b8, by decide, c3214_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3214_b7, by decide, c3214_ok7⟩, ?_⟩
  simp

def s24 : List Nat := [19663934034669202669830144, 4951783768973935447822565377, 4951854604471178492500770817, 309791963642731595663671297, 77692373376171403055726593, 1238261160206215410773655553, 309862799139974640341876737, 19649766935220593734189072, 19720602432463638412394512, 1237949484018346014189551633, 4951769601874486838886924305, 77451532685545051149828113, 1238020319515589058867757073, 4951840437371729883565129745, 77522368182788095828033553, 4951911272868972928243335185, 77678206276722794120085521, 1238246993106766801838014481, 77749041773965838798290961, 1238317828604009846516219921, 19366424946248415021367552, 19437260443491459699572992, 309494454554310808015208705, 1237949484018346014189551873, 77394864287750615407264001, 1237963651117794623125192961, 77451532685545051149828353, 309565290051553852693414145, 1238020319515589058867757313, 77465699784993660085469441, 1238034486615037667803398401, 77522368182788095828033793, 309636125548796897371619585, 19352257846799806085726480, 1237949484018346014189551888, 19423093344042850763931920, 77451532685545051149828368, 1238020319515589058867757328, 19493928841285895442137360, 77522368182788095828033808]
theorem e24 : enumKeys 6146 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c3217_b1, by decide, c3217_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c3218_b8, by decide, c3218_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c3218_b6, by decide, c3218_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c3218_b7, by decide, c3218_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3218_b5, by decide, c3218_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c3218_b4, by decide, c3218_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c3218_b3, by decide, c3218_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c3217_b5, by decide, c3217_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c3217_b4, by decide, c3217_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3221_b0, by decide, c3221_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c3220_b9, by decide, c3220_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3220_b8, by decide, c3220_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3220_b7, by decide, c3220_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3220_b6, by decide, c3220_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3220_b3, by decide, c3220_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3220_b2, by decide, c3220_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3220_b5, by decide, c3220_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3220_b4, by decide, c3220_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3220_b1, by decide, c3220_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3220_b0, by decide, c3220_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3217_b3, by decide, c3217_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c3217_b2, by decide, c3217_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3219_b9, by decide, c3219_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3219_b8, by decide, c3219_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3219_b7, by decide, c3219_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3219_b6, by decide, c3219_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c3219_b5, by decide, c3219_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3219_b4, by decide, c3219_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3219_b3, by decide, c3219_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c3219_b2, by decide, c3219_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3219_b1, by decide, c3219_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3219_b0, by decide, c3219_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3218_b9, by decide, c3218_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3218_b2, by decide, c3218_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3218_b1, by decide, c3218_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c3218_b0, by decide, c3218_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3217_b9, by decide, c3217_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3217_b8, by decide, c3217_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3217_b7, by decide, c3217_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3217_b6, by decide, c3217_ok6⟩, ?_⟩
  simp

def s25 : List Nat := [19947276023641381382651904, 4952067110962907626535387137, 4952137946460150671213592577, 77975715365143581768548353, 1238544502195187589486477313, 19649766935220593734189312, 19720602432463638412394752, 77380697188302006471622913, 1237949484018346014189551873, 4951769601874486838886924545, 77451532685545051149828353, 4951840437371729883565129985, 77678206276722794120085761, 1238246993106766801838014721, 77749041773965838798291201, 19352257846799806085726720, 77380697188302006471623168, 1237949484018346014189552128, 19423093344042850763932160, 77451532685545051149828608]
theorem e25 : enumKeys 6146 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c3221_b1, by decide, c3221_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3222_b2, by decide, c3222_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3222_b1, by decide, c3222_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c3222_b0, by decide, c3222_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c3221_b9, by decide, c3221_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3221_b3, by decide, c3221_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3221_b2, by decide, c3221_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3223_b0, by decide, c3223_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3222_b9, by decide, c3222_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3222_b8, by decide, c3222_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3222_b7, by decide, c3222_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3222_b6, by decide, c3222_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3222_b5, by decide, c3222_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3222_b4, by decide, c3222_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3222_b3, by decide, c3222_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3221_b8, by decide, c3221_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3221_b7, by decide, c3221_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3221_b6, by decide, c3221_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3221_b5, by decide, c3221_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3221_b4, by decide, c3221_ok4⟩, ?_⟩
  simp

def s26 : List Nat := [25387442211907212668829697, 79230580365903566851893362690, 19813085257664157544259518466, 19808249554385699027560697857, 21760664753063325144715265]
theorem e26 : enumKeys 6146 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3223_b1, by decide, c3223_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 84, c3223_b5, by decide, c3223_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 93, c3223_b4, by decide, c3223_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3223_b2, by decide, c3223_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 102, c3223_b3, by decide, c3223_ok3⟩, ?_⟩
  simp

def s27 : List Nat := [19437260443491459699572737, 20570628399380174550859777, 19807135075895741791290261506, 1239167854570926382654685186, 19808268443851630506141548546, 310769493504685612222906370, 19808325112249424941884112898, 311902861460574327074193410, 1240357890924609533248536578, 20627296797174610293424145, 19808325112249424941884112913, 21760664753063325144711185, 1240357890924609533248536593]
theorem e27 : enumKeys 6146 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c3223_b7, by decide, c3223_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3223_b6, by decide, c3223_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c3224_b8, by decide, c3224_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 114, c3224_b7, by decide, c3224_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c3224_b6, by decide, c3224_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3224_b5, by decide, c3224_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 115, c3224_b4, by decide, c3224_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3224_b3, by decide, c3224_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 106, c3224_b2, by decide, c3224_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3224_b1, by decide, c3224_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 127, c3224_b0, by decide, c3224_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3223_b9, by decide, c3223_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3223_b8, by decide, c3223_ok8⟩, ?_⟩
  simp

def s28 : List Nat := [19649766935220593734189057, 20853970388352353263681537, 19807347582387470925324877826, 4952973805327618598416416770, 19808254276752181897205907458, 78882409729854553649577986, 19808551785840602684854370306, 79789104094565525530607618, 4954178008780750357945909250, 20556461299931565615218945, 19808254276752181897205907713, 21760664753063325144711425, 79789104094565525530607873]
theorem e28 : enumKeys 6146 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c3225_b0, by decide, c3225_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3224_b9, by decide, c3224_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3226_b1, by decide, c3226_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c3226_b0, by decide, c3226_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3225_b9, by decide, c3225_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3225_b8, by decide, c3225_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3225_b7, by decide, c3225_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3225_b6, by decide, c3225_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3225_b5, by decide, c3225_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3225_b4, by decide, c3225_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3225_b3, by decide, c3225_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c3225_b2, by decide, c3225_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3225_b1, by decide, c3225_ok1⟩, ?_⟩
  simp

def s29 : List Nat := [24183238758775453139337217, 24254074256018497817542657, 25387442211907212668829697, 19807120908796293182354620418, 79228242794494546377512583170, 1239153687471477773719044098, 79229376162450435092363870210, 78655736138676810679320578, 79229446997947678137042075650, 1242780464930321661243162626, 19811881054211025784730025986, 82282513597520698203439106, 19811951889708268829408231426, 83415881553409413054726146, 1243984668383453420772655106, 19423093344042850763935745, 19807120908796293182354624513, 20556461299931565615222785, 1239153687471477773719048193, 20627296797174610293428225, 78655736138676810679324673]
theorem e29 : enumKeys 6146 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c3226_b4, by decide, c3226_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c3226_b3, by decide, c3226_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3226_b2, by decide, c3226_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c3228_b2, by decide, c3228_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c3228_b1, by decide, c3228_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3228_b0, by decide, c3228_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 112, c3227_b9, by decide, c3227_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3227_b6, by decide, c3227_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 118, c3227_b5, by decide, c3227_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 122, c3227_b8, by decide, c3227_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 124, c3227_b7, by decide, c3227_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3227_b4, by decide, c3227_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3227_b3, by decide, c3227_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c3227_b2, by decide, c3227_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 123, c3227_b1, by decide, c3227_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3227_b0, by decide, c3227_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3226_b9, by decide, c3226_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c3226_b8, by decide, c3226_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c3226_b7, by decide, c3226_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c3226_b6, by decide, c3226_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c3226_b5, by decide, c3226_ok5⟩, ?_⟩
  simp

def s30 : List Nat := [19366424946248415021367297, 19437260443491459699572737, 20570628399380174550859777, 1237963651117794623125192706, 19807064240398498746612056066, 309565290051553852693413890, 1238020319515589058867757058, 19807120908796293182354620418, 77465699784993660085469186, 1238034486615037667803398146, 19807135075895741791290261506, 77522368182788095828033538, 309636125548796897371619330, 19807191744293536227032825858, 310698658007442567544700930, 1239153687471477773719044098, 78599067740882374936756226, 1239167854570926382654685186, 78655736138676810679320578, 310769493504685612222906370, 1239224522968720818397249538, 19423093344042850763931665, 1238020319515589058867757073, 19807120908796293182354620433, 19493928841285895442137105, 77522368182788095828033553, 19807191744293536227032825873, 20556461299931565615218705, 1239153687471477773719044113, 20627296797174610293424145, 78655736138676810679320593, 1239224522968720818397249553]
theorem e30 : enumKeys 6146 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c3228_b5, by decide, c3228_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3228_b4, by decide, c3228_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c3228_b3, by decide, c3228_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c3231_b4, by decide, c3231_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3231_b3, by decide, c3231_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3231_b2, by decide, c3231_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c3231_b1, by decide, c3231_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3231_b0, by decide, c3231_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3230_b7, by decide, c3230_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3230_b6, by decide, c3230_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3230_b5, by decide, c3230_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3230_b2, by decide, c3230_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3230_b1, by decide, c3230_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c3230_b0, by decide, c3230_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3230_b9, by decide, c3230_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3230_b8, by decide, c3230_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3230_b4, by decide, c3230_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3230_b3, by decide, c3230_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3229_b9, by decide, c3229_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3229_b8, by decide, c3229_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c3229_b7, by decide, c3229_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c3229_b6, by decide, c3229_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3229_b5, by decide, c3229_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3229_b4, by decide, c3229_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3229_b1, by decide, c3229_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3229_b0, by decide, c3229_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c3228_b9, by decide, c3228_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c3229_b3, by decide, c3229_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3229_b2, by decide, c3229_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3228_b8, by decide, c3228_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3228_b7, by decide, c3228_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c3228_b6, by decide, c3228_ok6⟩, ?_⟩
  simp

def s31 : List Nat := [19649766935220593734189057, 19720602432463638412394497, 20853970388352353263681537, 1237949484018346014189551618, 4951769601874486838886924290, 19807050073299050137676414978, 77451532685545051149828098, 4951840437371729883565129730, 19807120908796293182354620418, 77678206276722794120085506, 1238246993106766801838014466, 19807347582387470925324877826, 77749041773965838798290946, 19807418417884713970003083266, 78584900641433766001115138, 1239153687471477773719044098, 4952973805327618598416416770, 78655736138676810679320578, 4953044640824861643094622210, 78882409729854553649577986, 1239451196559898561367506946, 19352257846799806085726465, 1237949484018346014189551873, 19807050073299050137676415233, 19423093344042850763931905, 77451532685545051149828353, 19807120908796293182354620673, 20556461299931565615218945, 78584900641433766001115393, 1239153687471477773719044353, 20627296797174610293424385, 78655736138676810679320833]
theorem e31 : enumKeys 6146 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c3231_b7, by decide, c3231_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c3231_b6, by decide, c3231_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c3231_b5, by decide, c3231_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c3234_b6, by decide, c3234_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3234_b5, by decide, c3234_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3234_b4, by decide, c3234_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3234_b3, by decide, c3234_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c3234_b2, by decide, c3234_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3234_b1, by decide, c3234_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3234_b0, by decide, c3234_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3233_b9, by decide, c3233_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3233_b8, by decide, c3233_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c3233_b4, by decide, c3233_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3233_b3, by decide, c3233_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3233_b7, by decide, c3233_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3233_b6, by decide, c3233_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3233_b5, by decide, c3233_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3233_b2, by decide, c3233_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3233_b1, by decide, c3233_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3233_b0, by decide, c3233_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c3232_b9, by decide, c3232_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3232_b8, by decide, c3232_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c3232_b7, by decide, c3232_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3232_b6, by decide, c3232_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3232_b5, by decide, c3232_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3232_b4, by decide, c3232_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3232_b3, by decide, c3232_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3232_b2, by decide, c3232_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3232_b1, by decide, c3232_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3232_b0, by decide, c3232_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c3231_b9, by decide, c3231_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3231_b8, by decide, c3231_ok8⟩, ?_⟩
  simp

def s32 : List Nat := [24183238758775453139337217, 24254074256018497817542657, 1237949484018346014189551618, 79228171958997303332834377730, 77451532685545051149828098, 1238020319515589058867757058, 79228242794494546377512583170, 77522368182788095828033538, 79228313629991789422190788610, 82211678100277653525233666, 1242780464930321661243162626, 82282513597520698203439106, 1242851300427564705921368066, 19352257846799806085730305, 1237949484018346014189555713, 19423093344042850763935745, 77451532685545051149832193, 1238020319515589058867761153, 19493928841285895442141185, 77522368182788095828037633]
theorem e32 : enumKeys 6146 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c3234_b8, by decide, c3234_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c3234_b7, by decide, c3234_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3236_b6, by decide, c3236_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c3236_b5, by decide, c3236_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c3236_b4, by decide, c3236_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3236_b3, by decide, c3236_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3236_b2, by decide, c3236_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3235_b9, by decide, c3235_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c3235_b8, by decide, c3235_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c3236_b1, by decide, c3236_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c3236_b0, by decide, c3236_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c3235_b7, by decide, c3235_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c3235_b6, by decide, c3235_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3235_b5, by decide, c3235_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3235_b4, by decide, c3235_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c3235_b3, by decide, c3235_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3235_b2, by decide, c3235_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c3235_b1, by decide, c3235_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3235_b0, by decide, c3235_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3234_b9, by decide, c3234_ok9⟩, ?_⟩
  simp

def s33 : List Nat := [19366424946248415021367297, 19437260443491459699572737, 309494454554310808015208450, 1237949484018346014189551618, 77394864287750615407263746, 1237963651117794623125192706, 77451532685545051149828098, 309565290051553852693413890, 1238020319515589058867757058, 77465699784993660085469186, 1238034486615037667803398146, 77522368182788095828033538, 309636125548796897371619330, 1238091155012832103545962498, 19352257846799806085726225, 1237949484018346014189551633, 19423093344042850763931665, 77451532685545051149828113, 1238020319515589058867757073, 19493928841285895442137105, 77522368182788095828033553, 1238091155012832103545962513]
theorem e33 : enumKeys 6146 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3236_b8, by decide, c3236_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c3236_b7, by decide, c3236_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c3238_b8, by decide, c3238_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c3238_b7, by decide, c3238_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3238_b6, by decide, c3238_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3238_b5, by decide, c3238_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c3238_b4, by decide, c3238_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3238_b3, by decide, c3238_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3238_b2, by decide, c3238_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c3238_b1, by decide, c3238_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3238_b0, by decide, c3238_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3237_b9, by decide, c3237_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3237_b8, by decide, c3237_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3237_b7, by decide, c3237_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3237_b6, by decide, c3237_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3237_b5, by decide, c3237_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c3237_b4, by decide, c3237_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c3237_b3, by decide, c3237_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3237_b2, by decide, c3237_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c3237_b1, by decide, c3237_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c3237_b0, by decide, c3237_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3236_b9, by decide, c3236_ok9⟩, ?_⟩
  simp

def s34 : List Nat := [19649766935220593734189057, 19720602432463638412394497, 77380697188302006471622658, 1237949484018346014189551618, 4951769601874486838886924290, 77451532685545051149828098, 1238020319515589058867757058, 4951840437371729883565129730, 77522368182788095828033538, 4951911272868972928243335170, 77678206276722794120085506, 1238246993106766801838014466, 77749041773965838798290946, 1238317828604009846516219906, 19352257846799806085726465, 77380697188302006471622913, 1237949484018346014189551873, 19423093344042850763931905, 77451532685545051149828353, 1238020319515589058867757313, 19493928841285895442137345, 77522368182788095828033793]
theorem e34 : enumKeys 6146 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c3239_b0, by decide, c3239_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c3238_b9, by decide, c3238_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3241_b0, by decide, c3241_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3240_b9, by decide, c3240_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3240_b8, by decide, c3240_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3240_b7, by decide, c3240_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3240_b6, by decide, c3240_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c3240_b5, by decide, c3240_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3240_b2, by decide, c3240_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c3240_b1, by decide, c3240_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3240_b4, by decide, c3240_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3240_b3, by decide, c3240_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3240_b0, by decide, c3240_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3239_b9, by decide, c3239_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3239_b8, by decide, c3239_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3239_b7, by decide, c3239_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3239_b6, by decide, c3239_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3239_b5, by decide, c3239_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3239_b4, by decide, c3239_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3239_b3, by decide, c3239_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3239_b2, by decide, c3239_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3239_b1, by decide, c3239_ok1⟩, ?_⟩
  simp

def s35 : List Nat := [21760664753063325144711170, 19809458480205313656735399938]
theorem e35 : enumKeys 6146 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c3241_b2, by decide, c3241_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c3241_b1, by decide, c3241_ok1⟩, ?_⟩
  simp

def s36 : List Nat := [19423093344042850763931650, 19807120908796293182354620418, 20556461299931565615218690, 1239153687471477773719044098, 19808254276752181897205907458, 20627296797174610293424130, 78655736138676810679320578, 19808325112249424941884112898, 21760664753063325144711170, 79789104094565525530607618, 1240357890924609533248536578]
theorem e36 : enumKeys 6146 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c3242_b3, by decide, c3242_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c3242_b2, by decide, c3242_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3242_b1, by decide, c3242_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c3242_b0, by decide, c3242_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c3241_b9, by decide, c3241_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c3241_b8, by decide, c3241_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c3241_b7, by decide, c3241_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c3241_b6, by decide, c3241_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c3241_b5, by decide, c3241_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c3241_b4, by decide, c3241_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c3241_b3, by decide, c3241_ok3⟩, ?_⟩
  simp

def s37 : List Nat := [19352257846799806085726210, 1237949484018346014189551618, 19807050073299050137676414978, 19423093344042850763931650, 77451532685545051149828098, 1238020319515589058867757058, 19807120908796293182354620418, 19493928841285895442137090, 77522368182788095828033538, 19807191744293536227032825858, 20556461299931565615218690, 78584900641433766001115138, 1239153687471477773719044098, 20627296797174610293424130, 78655736138676810679320578, 1239224522968720818397249538]
theorem e37 : enumKeys 6146 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c3243_b9, by decide, c3243_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c3243_b8, by decide, c3243_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c3243_b7, by decide, c3243_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3243_b6, by decide, c3243_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c3243_b5, by decide, c3243_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c3243_b4, by decide, c3243_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c3243_b3, by decide, c3243_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3242_b9, by decide, c3242_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c3242_b8, by decide, c3242_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c3242_b7, by decide, c3242_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c3243_b2, by decide, c3243_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c3243_b1, by decide, c3243_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c3243_b0, by decide, c3243_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c3242_b6, by decide, c3242_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c3242_b5, by decide, c3242_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c3242_b4, by decide, c3242_ok4⟩, ?_⟩
  simp

def s38 : List Nat := [19352257846799806085726210, 77380697188302006471622658, 1237949484018346014189551618, 19423093344042850763931650, 77451532685545051149828098, 1238020319515589058867757058, 19493928841285895442137090, 77522368182788095828033538, 1238091155012832103545962498]
theorem e38 : enumKeys 6146 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3244_b8, by decide, c3244_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3244_b7, by decide, c3244_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c3244_b6, by decide, c3244_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3244_b5, by decide, c3244_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c3244_b4, by decide, c3244_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c3244_b3, by decide, c3244_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c3244_b2, by decide, c3244_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c3244_b1, by decide, c3244_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c3244_b0, by decide, c3244_ok0⟩, ?_⟩
  simp

/-- every enumerated key with left type `6146` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 6146 mR,
    (6146 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 6146 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K26
end Grid3.Three.Cert
