import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0521
import Grid3.Three.Cert.Data.C0522
import Grid3.Three.Cert.Data.C0523
import Grid3.Three.Cert.Data.C0524
import Grid3.Three.Cert.Data.C0525
import Grid3.Three.Cert.Data.C0526
import Grid3.Three.Cert.Data.C0527
import Grid3.Three.Cert.Data.C0528
import Grid3.Three.Cert.Data.C0529
import Grid3.Three.Cert.Data.C0530
import Grid3.Three.Cert.Data.C0531
import Grid3.Three.Cert.Data.C0532
import Grid3.Three.Cert.Data.C0533
import Grid3.Three.Cert.Data.C0534
import Grid3.Three.Cert.Data.C0535
import Grid3.Three.Cert.Data.C0536
import Grid3.Three.Cert.Data.C0537
import Grid3.Three.Cert.Data.C0538
import Grid3.Three.Cert.Data.C0539
import Grid3.Three.Cert.Data.C0540

/-! Seam keys with left type `218` (type index 33): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K33

theorem tL : rtype 218 = 1163 := by decide

def s00 : List Nat := [54043195528445952, 36029896530591744, 36028797086072832, 18015498088218624, 18014398643699712, 1099645845504, 36028797018968064, 18015498021113856, 18014398576594944, 1099578740736, 134221824, 18014398509490176, 1099511635968, 67117056]
theorem e00 : enumKeys 218 12288 = s00 := by decide +kernel
theorem t00 : rtype 12288 = 12288 := by decide
theorem r00 : ∀ M ∈ s00, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 12288 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 12288) (rM M) ne blob = true) := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0521_b32, by decide, c0521_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 188, c0521_b31, by decide, c0521_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 200, c0521_b30, by decide, c0521_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 189, c0521_b28, by decide, c0521_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 196, c0521_b26, by decide, c0521_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0521_b23, by decide, c0521_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 194, c0521_b29, by decide, c0521_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0521_b27, by decide, c0521_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 198, c0521_b25, by decide, c0521_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 186, c0521_b22, by decide, c0521_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0521_b20, by decide, c0521_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 190, c0521_b24, by decide, c0521_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 180, c0521_b21, by decide, c0521_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 192, c0521_b19, by decide, c0521_ok19⟩, ?_⟩
  simp

def s01 : List Nat := [23643902338662400, 23643898043957248, 22518066856591360, 19140573294493696, 5630599046103040, 19140302728069120, 19140298433363968, 18014467245998080, 1126999435509760, 5629503896289280, 5629499601584128, 4503668414218240, 1126174852120576, 1125904285696000, 23643898043695120, 22518066856329232, 19140573294231568, 5630599045840912, 19140298433101840, 18014467245735952, 1126999435247632, 5629499601322000, 4503668413956112, 1126174851858448, 1125899990728720, 68803362832, 22518002431820032, 22517998137114880, 18014673387651328, 4504699139260672, 18014402821226752, 18014398526521600, 1099528667392, 4503603989446912, 4503599694741760, 274945278208, 4378853632, 22517998136852752, 18014673387389200, 4504699138998544, 18014398526259472, 1099528405264, 4503599694479632, 274945016080, 83886352, 5629503829184512, 5629499534479360, 4503668347113472, 1126174785015808, 1125904218591232, 1125899923886080, 68736520192, 5629499534217232, 4503668346851344, 1126174784753680, 1125899923623952, 68736258064, 4503603922342144, 4503599627636992, 274878173440, 4311748864, 17043712]
theorem e01 : enumKeys 218 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0523_b14, by decide, c0523_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0523_b13, by decide, c0523_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 243, c0523_b11, by decide, c0523_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0523_b6, by decide, c0523_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0522_b34, by decide, c0522_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0523_b4, by decide, c0523_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0523_b3, by decide, c0523_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0522_b39, by decide, c0522_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0522_b15, by decide, c0522_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0522_b32, by decide, c0522_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0522_b30, by decide, c0522_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0522_b24, by decide, c0522_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0522_b13, by decide, c0522_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0522_b9, by decide, c0522_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0523_b12, by decide, c0523_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0523_b10, by decide, c0523_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0523_b5, by decide, c0523_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0522_b33, by decide, c0522_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0523_b2, by decide, c0523_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0522_b38, by decide, c0522_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0522_b14, by decide, c0522_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0522_b29, by decide, c0522_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 261, c0522_b23, by decide, c0522_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0522_b12, by decide, c0522_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0522_b7, by decide, c0522_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0521_b39, by decide, c0521_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0523_b9, by decide, c0523_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0523_b8, by decide, c0523_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0523_b1, by decide, c0523_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0522_b26, by decide, c0522_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0522_b37, by decide, c0522_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0522_b36, by decide, c0522_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 195, c0522_b4, by decide, c0522_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0522_b20, by decide, c0522_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0522_b18, by decide, c0522_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0522_b2, by decide, c0522_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0521_b36, by decide, c0521_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0523_b7, by decide, c0523_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0523_b0, by decide, c0523_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0522_b25, by decide, c0522_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0522_b35, by decide, c0522_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0522_b3, by decide, c0522_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0522_b17, by decide, c0522_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0522_b1, by decide, c0522_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0521_b34, by decide, c0521_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0522_b31, by decide, c0522_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0522_b28, by decide, c0522_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0522_b22, by decide, c0522_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0522_b11, by decide, c0522_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0522_b8, by decide, c0522_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0522_b6, by decide, c0522_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0521_b38, by decide, c0521_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0522_b27, by decide, c0522_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0522_b21, by decide, c0522_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0522_b10, by decide, c0522_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0522_b5, by decide, c0522_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0521_b37, by decide, c0521_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 215, c0522_b19, by decide, c0522_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0522_b16, by decide, c0522_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0522_b0, by decide, c0522_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0521_b35, by decide, c0521_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0521_b33, by decide, c0521_ok33⟩, ?_⟩
  simp

def s02 : List Nat := [36310276290641920, 36310271995936768, 18296972998082560, 18295877848268800, 18295873553563648, 282574555709440, 281479405895680, 36310271995674640, 18296972997820432, 18295873553301520, 282574555447312, 281475110928400, 18295877781164032, 18295873486458880, 282574488604672, 281479338790912, 281475044085760, 18295873486196752, 282574488342544, 281475043823632, 281479271686144, 281474976980992]
theorem e02 : enumKeys 218 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0523_b36, by decide, c0523_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0523_b35, by decide, c0523_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 181, c0523_b33, by decide, c0523_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0523_b31, by decide, c0523_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0523_b29, by decide, c0523_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0523_b25, by decide, c0523_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0523_b21, by decide, c0523_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0523_b34, by decide, c0523_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0523_b32, by decide, c0523_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0523_b28, by decide, c0523_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0523_b24, by decide, c0523_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0523_b18, by decide, c0523_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 181, c0523_b30, by decide, c0523_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0523_b27, by decide, c0523_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0523_b23, by decide, c0523_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0523_b20, by decide, c0523_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0523_b17, by decide, c0523_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0523_b26, by decide, c0523_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0523_b22, by decide, c0523_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0523_b16, by decide, c0523_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0523_b19, by decide, c0523_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0523_b15, by decide, c0523_ok15⟩, ?_⟩
  simp

def s03 : List Nat := [5910978806153216, 5910974511448064, 4785143324082176, 1407649761984512, 1407379195559936, 5910978805891088, 5910974511185936, 4785143323820048, 1407649761722384, 1407379195297808, 1407374900592656, 281543713226768, 5910974510923808, 4785143323557920, 1407649761460256, 1407374900330528, 281543712964640, 4785078899310848, 4785074604605696, 281749855142144, 281479288717568, 4785078899048720, 4785074604343568, 281749854880016, 281479288455440, 281474993750288]
theorem e03 : enumKeys 218 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0524_b22, by decide, c0524_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0524_b20, by decide, c0524_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0524_b17, by decide, c0524_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0524_b10, by decide, c0524_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0524_b7, by decide, c0524_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0524_b21, by decide, c0524_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0524_b19, by decide, c0524_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0524_b16, by decide, c0524_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0524_b9, by decide, c0524_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0524_b6, by decide, c0524_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0524_b5, by decide, c0524_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0524_b1, by decide, c0524_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0524_b18, by decide, c0524_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0524_b15, by decide, c0524_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0524_b8, by decide, c0524_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0524_b4, by decide, c0524_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0524_b0, by decide, c0524_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0524_b14, by decide, c0524_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0524_b12, by decide, c0524_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0524_b3, by decide, c0524_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0523_b39, by decide, c0523_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0524_b13, by decide, c0524_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0524_b11, by decide, c0524_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0524_b2, by decide, c0524_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0523_b38, by decide, c0523_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0523_b37, by decide, c0523_ok37⟩, ?_⟩
  simp

def s04 : List Nat := [18577352758132736, 18577348463427584, 564049465573376, 562954315759616, 18577352757870608, 18577348463165456, 564049465311248, 562954315497488, 562950020792336, 18577348462903328, 564049465049120, 562950020530208, 562954248654848, 562949953949696, 562954248392720, 562949953687568]
theorem e04 : enumKeys 218 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 182, c0524_b38, by decide, c0524_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0524_b36, by decide, c0524_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0524_b33, by decide, c0524_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0524_b30, by decide, c0524_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0524_b37, by decide, c0524_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0524_b35, by decide, c0524_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0524_b32, by decide, c0524_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0524_b29, by decide, c0524_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0524_b26, by decide, c0524_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0524_b34, by decide, c0524_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0524_b31, by decide, c0524_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0524_b25, by decide, c0524_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 175, c0524_b28, by decide, c0524_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0524_b24, by decide, c0524_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0524_b27, by decide, c0524_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0524_b23, by decide, c0524_ok23⟩, ?_⟩
  simp

def s05 : List Nat := [844429225623552, 844429225361424, 844424930656272, 844429225099296, 844424930394144]
theorem e05 : enumKeys 218 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0525_b3, by decide, c0525_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0525_b2, by decide, c0525_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0525_b0, by decide, c0525_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0525_b1, by decide, c0525_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0524_b39, by decide, c0524_ok39⟩, ?_⟩
  simp

def s06 : List Nat := [37154697999548416, 37154696925872128, 36028865738506240, 19141397928017920, 19140299557175296, 19140298483499008, 18014467296133120, 1126999485644800, 1125901114802176, 68853694464, 36028798092706048, 36028797019029760, 18015498021175552, 18014399650332928, 18014398576656640, 1099578802432, 1207959808, 19140299490070528, 19140298416394240, 18014467229028352, 1126999418540032, 1125901047697408, 1125899974021120, 68786655232, 18014399583228160, 18014398509551872, 1099511697664, 1140855040, 67178752, 1125900980592640, 1125899906916352, 68719550464]
theorem e06 : enumKeys 218 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0525_b35, by decide, c0525_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0525_b34, by decide, c0525_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0525_b33, by decide, c0525_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0525_b30, by decide, c0525_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0525_b29, by decide, c0525_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0525_b27, by decide, c0525_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0525_b24, by decide, c0525_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0525_b18, by decide, c0525_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0525_b16, by decide, c0525_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 306, c0525_b9, by decide, c0525_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0525_b32, by decide, c0525_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0525_b31, by decide, c0525_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0525_b25, by decide, c0525_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0525_b22, by decide, c0525_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0525_b20, by decide, c0525_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0525_b11, by decide, c0525_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0525_b6, by decide, c0525_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0525_b28, by decide, c0525_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0525_b26, by decide, c0525_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0525_b23, by decide, c0525_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0525_b17, by decide, c0525_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0525_b15, by decide, c0525_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0525_b13, by decide, c0525_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0525_b8, by decide, c0525_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0525_b21, by decide, c0525_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0525_b19, by decide, c0525_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0525_b10, by decide, c0525_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0525_b5, by decide, c0525_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0525_b4, by decide, c0525_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0525_b14, by decide, c0525_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0525_b12, by decide, c0525_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0525_b7, by decide, c0525_ok7⟩, ?_⟩
  simp

def s07 : List Nat := [6755403736088576, 6755400515059712, 6755399441383424, 5629568254017536, 2252074691919872, 2251804125495296, 2251800904466432, 1125968643358720, 6755400514797584, 6755399441121296, 5629568253755408, 2252074691657744, 2251800904204304, 2251799830528016, 1125968643162128, 5629503829246208, 5629500608217344, 5629499534541056, 4503668347175168, 1126174785077504, 1125904218652928, 1125900997624064, 68736516352, 5629500607955216, 5629499534278928, 4503668346913040, 1126174784815376, 1125900997361936, 1125899923685648, 68736319760, 4503603922403840, 4503600701374976, 4503599627698688, 274878235136, 4311810560, 1090781696]
theorem e07 : enumKeys 218 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0526_b31, by decide, c0526_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0526_b30, by decide, c0526_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0526_b28, by decide, c0526_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0526_b26, by decide, c0526_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 247, c0526_b14, by decide, c0526_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0526_b12, by decide, c0526_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0526_b11, by decide, c0526_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 318, c0526_b6, by decide, c0526_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 276, c0526_b29, by decide, c0526_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0526_b27, by decide, c0526_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 277, c0526_b25, by decide, c0526_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 267, c0526_b13, by decide, c0526_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 276, c0526_b10, by decide, c0526_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 255, c0526_b9, by decide, c0526_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0526_b5, by decide, c0526_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0526_b24, by decide, c0526_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 273, c0526_b23, by decide, c0526_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0526_b21, by decide, c0526_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0526_b19, by decide, c0526_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0526_b8, by decide, c0526_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0526_b4, by decide, c0526_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 257, c0526_b3, by decide, c0526_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 306, c0525_b39, by decide, c0525_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 279, c0526_b22, by decide, c0526_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0526_b20, by decide, c0526_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0526_b18, by decide, c0526_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0526_b7, by decide, c0526_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0526_b2, by decide, c0526_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 247, c0526_b1, by decide, c0526_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0525_b38, by decide, c0525_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0526_b17, by decide, c0526_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0526_b16, by decide, c0526_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0526_b15, by decide, c0526_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0526_b0, by decide, c0526_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0525_b37, by decide, c0525_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0525_b36, by decide, c0525_ok36⟩, ?_⟩
  simp

def s08 : List Nat := [19421777688068096, 19421774467039232, 19421773393362944, 18295942205997056, 1408474395508736, 1407379245694976, 1407376024666112, 281543763558400, 19421774466777104, 19421773393100816, 18295942205734928, 1408474395246608, 1407376024403984, 1407374950727696, 281543763361808, 18295877781225728, 18295874560196864, 18295873486520576, 282574488666368, 281479338852608, 281476117823744, 18295874559934736, 18295873486258448, 282574488404240, 281476117561616, 281475043885328, 1407379178590208, 1407375957561344, 1407374883885056, 281543696519168, 1407375957299216, 1407374883622928, 281543696257040, 281479271747840, 281476050718976, 281474977042688]
theorem e08 : enumKeys 218 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0527_b27, by decide, c0527_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0527_b26, by decide, c0527_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0527_b24, by decide, c0527_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0527_b22, by decide, c0527_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0527_b15, by decide, c0527_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0527_b13, by decide, c0527_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0527_b11, by decide, c0527_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 293, c0527_b2, by decide, c0527_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0527_b25, by decide, c0527_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0527_b23, by decide, c0527_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0527_b21, by decide, c0527_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0527_b14, by decide, c0527_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0527_b10, by decide, c0527_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0527_b7, by decide, c0527_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 243, c0527_b1, by decide, c0527_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0527_b20, by decide, c0527_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0527_b19, by decide, c0527_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0527_b17, by decide, c0527_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0527_b4, by decide, c0527_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0526_b38, by decide, c0526_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0526_b36, by decide, c0526_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0527_b18, by decide, c0527_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0527_b16, by decide, c0527_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0527_b3, by decide, c0527_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0526_b35, by decide, c0526_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0526_b33, by decide, c0526_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0527_b12, by decide, c0527_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0527_b9, by decide, c0527_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0527_b6, by decide, c0527_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0527_b0, by decide, c0527_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0527_b8, by decide, c0527_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0527_b5, by decide, c0527_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0526_b39, by decide, c0526_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0526_b37, by decide, c0526_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0526_b34, by decide, c0526_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0526_b32, by decide, c0526_ok32⟩, ?_⟩
  simp

def s09 : List Nat := [1688854155558912, 1688850934530048, 563018673422336, 1688854155296784, 1688850934267920, 1688849860591632, 563018673225744, 1688850934005792, 1688849860329504, 563018672963616, 562954248716544, 562951027687680, 562954248454416, 562951027425552, 562949953749264]
theorem e09 : enumKeys 218 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0528_b2, by decide, c0528_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0528_b0, by decide, c0528_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 280, c0527_b35, by decide, c0527_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0528_b1, by decide, c0528_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0527_b39, by decide, c0527_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0527_b37, by decide, c0527_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0527_b34, by decide, c0527_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0527_b38, by decide, c0527_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0527_b36, by decide, c0527_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0527_b33, by decide, c0527_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0527_b32, by decide, c0527_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0527_b30, by decide, c0527_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0527_b31, by decide, c0527_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0527_b29, by decide, c0527_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0527_b28, by decide, c0527_ok28⟩, ?_⟩
  simp

def s10 : List Nat := [20266199396974592, 20266198323298304, 19140367135932416, 2252899325444096, 2251800954601472, 1125968693493760, 19140299490132224, 19140298416455936, 18014467229090048, 1126999418601728, 1125901047759104, 68786651392, 18014399583289856, 18014398509613568, 1099511759360, 1140916736, 2251800887496704, 2251799813820416, 1125968626454528, 1125900980654336, 1125899906978048, 68719612160]
theorem e10 : enumKeys 218 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0528_b24, by decide, c0528_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0528_b23, by decide, c0528_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0528_b22, by decide, c0528_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0528_b16, by decide, c0528_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0528_b15, by decide, c0528_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 333, c0528_b11, by decide, c0528_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0528_b21, by decide, c0528_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 247, c0528_b20, by decide, c0528_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0528_b19, by decide, c0528_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0528_b12, by decide, c0528_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 272, c0528_b9, by decide, c0528_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 321, c0528_b5, by decide, c0528_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 260, c0528_b18, by decide, c0528_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0528_b17, by decide, c0528_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0528_b6, by decide, c0528_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 261, c0528_b3, by decide, c0528_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 267, c0528_b14, by decide, c0528_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0528_b13, by decide, c0528_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0528_b10, by decide, c0528_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0528_b8, by decide, c0528_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0528_b7, by decide, c0528_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0528_b4, by decide, c0528_ok4⟩, ?_⟩
  simp

def s11 : List Nat := [2533279085494272, 2533275864465408, 1407443603357696, 2533275864203280, 2533274790526992, 1407443603161104, 1407379178651904, 1407375957623040, 281543696515328, 1407375957360912, 1407374883684624, 281543696318736, 281479271809536, 281476050780672]
theorem e11 : enumKeys 218 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0528_b38, by decide, c0528_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0528_b37, by decide, c0528_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 315, c0528_b34, by decide, c0528_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 270, c0528_b36, by decide, c0528_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0528_b35, by decide, c0528_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0528_b33, by decide, c0528_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0528_b32, by decide, c0528_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0528_b31, by decide, c0528_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 304, c0528_b28, by decide, c0528_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0528_b30, by decide, c0528_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 245, c0528_b29, by decide, c0528_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0528_b27, by decide, c0528_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0528_b26, by decide, c0528_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 248, c0528_b25, by decide, c0528_ok25⟩, ?_⟩
  simp

def s12 : List Nat := [3377700794400768, 2251868533293056, 2251800887558400, 1125968626450688, 1125900980716032, 68719608320]
theorem e12 : enumKeys 218 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0529_b4, by decide, c0529_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 350, c0529_b3, by decide, c0529_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0529_b2, by decide, c0529_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 344, c0529_b1, by decide, c0529_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0529_b0, by decide, c0529_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0528_b39, by decide, c0528_ok39⟩, ?_⟩
  simp

def s13 : List Nat := [40532396914769920, 36028797304176640, 22517998472396800, 18014398861803520, 4503600030023680, 40532396646334465, 36029071896870913, 22519097648480257, 36028797035741185, 18015498037886977, 22517998203961345, 18014673454497793, 4504699206107137, 18014398593368065, 1099595513857, 4503599761588225, 275012124673, 22517998405292032, 18014398794698752, 4503599962918912, 352325632, 22517998136856577, 18014673387393025, 4504699139002369, 18014398526263297, 1099528409089, 4503599694483457, 274945019905, 83890177, 4503599895814144, 274877915136, 285220864]
theorem e13 : enumKeys 218 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0529_b36, by decide, c0529_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0529_b33, by decide, c0529_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0529_b30, by decide, c0529_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0529_b23, by decide, c0529_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0529_b17, by decide, c0529_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0529_b35, by decide, c0529_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0529_b34, by decide, c0529_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0529_b31, by decide, c0529_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 182, c0529_b32, by decide, c0529_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0529_b26, by decide, c0529_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0529_b28, by decide, c0529_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0529_b25, by decide, c0529_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0529_b19, by decide, c0529_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0529_b21, by decide, c0529_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0529_b12, by decide, c0529_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0529_b14, by decide, c0529_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0529_b10, by decide, c0529_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0529_b29, by decide, c0529_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0529_b22, by decide, c0529_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0529_b16, by decide, c0529_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0529_b7, by decide, c0529_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0529_b27, by decide, c0529_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 195, c0529_b24, by decide, c0529_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 191, c0529_b18, by decide, c0529_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0529_b20, by decide, c0529_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0529_b11, by decide, c0529_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0529_b13, by decide, c0529_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0529_b9, by decide, c0529_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0529_b5, by decide, c0529_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0529_b15, by decide, c0529_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0529_b8, by decide, c0529_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0529_b6, by decide, c0529_ok6⟩, ?_⟩
  simp

def s14 : List Nat := [10133099430281216, 5629499819687936, 10133103456550913, 10133099161845761, 9007267974479873, 5629774412382209, 5629503845957633, 5629499551252481, 4503668363886593, 1126174801788929, 1125904235364353, 10133099430019088, 5629499819425808, 1125900208832528, 10133099161583633, 9007267974217745, 5629774412120081, 5629499550990353, 4503668363624465, 1126174801526801, 1125899940397073, 68753031185, 9007199523438848, 4503599912845568, 9007203549708545, 9007199255003393, 4503874505539841, 4503603939115265, 4503599644410113, 274894946561, 4328521985, 9007199523176720, 4503874505277712, 4503599912583440, 274894684432, 301990160]
theorem e14 : enumKeys 218 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0530_b31, by decide, c0530_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0530_b18, by decide, c0530_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0530_b32, by decide, c0530_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0530_b29, by decide, c0530_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0530_b27, by decide, c0530_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0530_b21, by decide, c0530_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0530_b19, by decide, c0530_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0530_b16, by decide, c0530_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0530_b12, by decide, c0530_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0530_b6, by decide, c0530_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0530_b4, by decide, c0530_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0530_b30, by decide, c0530_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0530_b17, by decide, c0530_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0530_b3, by decide, c0530_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0530_b28, by decide, c0530_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0530_b26, by decide, c0530_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0530_b20, by decide, c0530_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0530_b15, by decide, c0530_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0530_b11, by decide, c0530_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0530_b5, by decide, c0530_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0530_b2, by decide, c0530_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0529_b39, by decide, c0529_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0530_b24, by decide, c0530_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0530_b9, by decide, c0530_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0530_b25, by decide, c0530_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0530_b22, by decide, c0530_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0530_b14, by decide, c0530_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0530_b10, by decide, c0530_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0530_b7, by decide, c0530_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0530_b1, by decide, c0530_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0529_b38, by decide, c0529_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0530_b23, by decide, c0530_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 282, c0530_b13, by decide, c0530_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0530_b8, by decide, c0530_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 267, c0530_b0, by decide, c0530_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0529_b37, by decide, c0529_ok37⟩, ?_⟩
  simp

def s15 : List Nat := [22799473382260736, 18295873771667456, 4785074939887616, 22799477408530433, 22799473113825281, 18296148364361729, 4786174115971073, 18295877797937153, 18295873503232001, 282574505377793, 4785078966157313, 4785074671452161, 281749921988609, 281479355564033, 22799473381998608, 18295873771405328, 4785074939625488, 281475329032208, 22799473113563153, 18296148364099601, 4786174115708945, 18295873502969873, 282574505115665, 4785074671190033, 281749921726481, 281475060596753, 4785074872782848, 281475262189568, 4785078899052545, 4785074604347393, 281749854883841, 281479288459265, 281474993754113, 4785074872520720, 281749854621712, 281475261927440]
theorem e15 : enumKeys 218 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0531_b27, by decide, c0531_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0531_b20, by decide, c0531_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0531_b12, by decide, c0531_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0531_b28, by decide, c0531_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0531_b25, by decide, c0531_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0531_b23, by decide, c0531_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0531_b16, by decide, c0531_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 173, c0531_b21, by decide, c0531_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 173, c0531_b18, by decide, c0531_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 166, c0531_b5, by decide, c0531_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0531_b14, by decide, c0531_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0531_b8, by decide, c0531_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0531_b3, by decide, c0531_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 175, c0530_b39, by decide, c0530_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0531_b26, by decide, c0531_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0531_b19, by decide, c0531_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0531_b11, by decide, c0531_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0530_b37, by decide, c0530_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0531_b24, by decide, c0531_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0531_b22, by decide, c0531_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0531_b15, by decide, c0531_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0531_b17, by decide, c0531_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0531_b4, by decide, c0531_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 195, c0531_b7, by decide, c0531_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0531_b2, by decide, c0531_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0530_b34, by decide, c0530_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0531_b10, by decide, c0531_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0530_b36, by decide, c0530_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0531_b13, by decide, c0531_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0531_b6, by decide, c0531_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0531_b1, by decide, c0531_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 169, c0530_b38, by decide, c0530_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0530_b33, by decide, c0530_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0531_b9, by decide, c0531_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 239, c0531_b0, by decide, c0531_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0530_b35, by decide, c0530_ok35⟩, ?_⟩
  simp

def s16 : List Nat := [5066549849751552, 5066553876021249, 5066549581316097, 563224831852545, 562954265427969, 5066549849489424, 562950238896144, 5066553875759121, 5066549581053969, 563224831590417, 562954265165841, 562949970460689, 5066549849227296, 563224831328288, 562950238634016]
theorem e16 : enumKeys 218 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0532_b1, by decide, c0532_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0532_b3, by decide, c0532_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0531_b38, by decide, c0531_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0531_b36, by decide, c0531_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 167, c0531_b33, by decide, c0531_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0532_b0, by decide, c0532_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 195, c0531_b31, by decide, c0531_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0532_b2, by decide, c0532_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0531_b37, by decide, c0531_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0531_b35, by decide, c0531_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 173, c0531_b32, by decide, c0531_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 177, c0531_b29, by decide, c0531_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0531_b39, by decide, c0531_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0531_b34, by decide, c0531_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0531_b30, by decide, c0531_ok30⟩, ?_⟩
  simp

def s17 : List Nat := [23643898312196096, 19140298701602816, 5629499869822976, 1125900259164160, 23643899117436929, 23643898043760641, 22518066856394753, 19140573294297089, 5630599045906433, 19140299506843649, 19140298433167361, 18014467245801473, 1126999435313153, 5629500675063809, 5629499601387521, 4503668414021633, 1126174851923969, 1125901064470529, 68803362817, 22517998405353728, 18014398794760448, 4503599962980608, 352321792, 22517999210594561, 22517998136918273, 18014673387454721, 4504699139064065, 18014399600001281, 18014398526324993, 1099528470785, 4503600768221441, 4503599694545153, 274945081601, 1157628161, 5629499802718208, 1125900192124928, 5629500607959041, 5629499534282753, 4503668346916865, 1126174784819201, 1125900997365761, 1125899923689473, 68736323585, 4503600701116672, 4503599895875840, 274877976832, 1090523392, 285282560]
theorem e17 : enumKeys 218 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0533_b10, by decide, c0533_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0533_b2, by decide, c0533_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0532_b32, by decide, c0532_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 291, c0532_b15, by decide, c0532_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0533_b11, by decide, c0533_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0533_b9, by decide, c0533_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0533_b8, by decide, c0533_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0533_b4, by decide, c0533_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0532_b35, by decide, c0532_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0533_b3, by decide, c0533_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0533_b1, by decide, c0533_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0532_b39, by decide, c0532_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0532_b20, by decide, c0532_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0532_b34, by decide, c0532_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0532_b30, by decide, c0532_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 245, c0532_b27, by decide, c0532_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0532_b19, by decide, c0532_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0532_b17, by decide, c0532_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 285, c0532_b9, by decide, c0532_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0533_b6, by decide, c0533_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0532_b37, by decide, c0532_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 245, c0532_b23, by decide, c0532_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 285, c0532_b5, by decide, c0532_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 238, c0533_b7, by decide, c0533_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0533_b5, by decide, c0533_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0533_b0, by decide, c0533_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0532_b28, by decide, c0532_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0532_b38, by decide, c0532_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 203, c0532_b36, by decide, c0532_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0532_b12, by decide, c0532_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 250, c0532_b25, by decide, c0532_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0532_b21, by decide, c0532_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0532_b11, by decide, c0532_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0532_b7, by decide, c0532_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0532_b31, by decide, c0532_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0532_b14, by decide, c0532_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0532_b33, by decide, c0532_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0532_b29, by decide, c0532_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0532_b26, by decide, c0532_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0532_b18, by decide, c0532_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0532_b16, by decide, c0532_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0532_b13, by decide, c0532_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0532_b8, by decide, c0532_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 285, c0532_b24, by decide, c0532_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 231, c0532_b22, by decide, c0532_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 261, c0532_b10, by decide, c0532_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 270, c0532_b6, by decide, c0532_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0532_b4, by decide, c0532_ok4⟩, ?_⟩
  simp

def s18 : List Nat := [36310272264175616, 18295873821802496, 281475379363840, 36310273069416449, 36310271995740161, 18296972997885953, 18295874627043329, 18295873553367041, 282574555512833, 281476184670209, 18295873754697728, 281475312324608, 18295874559938561, 18295873486262273, 282574488408065, 281476117565441, 281475043889153, 281476050460672, 281475245219840]
theorem e18 : enumKeys 218 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0533_b29, by decide, c0533_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0533_b24, by decide, c0533_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0533_b15, by decide, c0533_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0533_b30, by decide, c0533_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 182, c0533_b28, by decide, c0533_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 179, c0533_b27, by decide, c0533_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0533_b26, by decide, c0533_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0533_b22, by decide, c0533_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 181, c0533_b20, by decide, c0533_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0533_b18, by decide, c0533_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 195, c0533_b23, by decide, c0533_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0533_b14, by decide, c0533_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0533_b25, by decide, c0533_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 179, c0533_b21, by decide, c0533_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 175, c0533_b19, by decide, c0533_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0533_b17, by decide, c0533_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0533_b12, by decide, c0533_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0533_b16, by decide, c0533_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0533_b13, by decide, c0533_ok13⟩, ?_⟩
  simp

def s19 : List Nat := [5910974779686912, 1407375169028096, 5910978805956609, 5910975584927745, 5910974511251457, 4785143323885569, 1407649761787905, 1407379195363329, 1407375974334465, 281543713226753, 5910974779424784, 1407375168831504, 5910975584665617, 5910974510989329, 4785143323623441, 1407649761525777, 1407375974072337, 1407374900396049, 281543713030161, 4785074872844544, 281475262185728, 4785078899114241, 4785075678085377, 4785074604409089, 281749854945537, 281479288520961, 281476067492097, 4785075677823248, 4785074872582416, 281749854683408, 281476067229968, 281475261989136]
theorem e19 : enumKeys 218 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0534_b19, by decide, c0534_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 273, c0534_b2, by decide, c0534_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0534_b22, by decide, c0534_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0534_b21, by decide, c0534_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0534_b17, by decide, c0534_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0534_b15, by decide, c0534_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0534_b7, by decide, c0534_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0534_b5, by decide, c0534_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0534_b4, by decide, c0534_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0533_b37, by decide, c0533_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0534_b18, by decide, c0534_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0534_b1, by decide, c0534_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0534_b20, by decide, c0534_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0534_b16, by decide, c0534_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0534_b14, by decide, c0534_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0534_b6, by decide, c0534_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0534_b3, by decide, c0534_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0534_b0, by decide, c0534_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0533_b36, by decide, c0533_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0534_b10, by decide, c0534_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0533_b32, by decide, c0533_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0534_b13, by decide, c0534_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0534_b12, by decide, c0534_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0534_b8, by decide, c0534_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0533_b39, by decide, c0533_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0533_b35, by decide, c0533_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 215, c0533_b34, by decide, c0533_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 279, c0534_b11, by decide, c0534_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0534_b9, by decide, c0534_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0533_b38, by decide, c0533_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 271, c0533_b33, by decide, c0533_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0533_b31, by decide, c0533_ok31⟩, ?_⟩
  simp

def s20 : List Nat := [18577348731666432, 562950289227776, 18577352757936129, 18577349536907265, 18577348463230977, 564049465376769, 562954315563009, 562951094534145, 18577348731404304, 562950289031184, 18577349536645137, 18577348462968849, 564049465114641, 562951094272017, 562950020595729, 562950222188544, 562954248458241, 562951027429377, 562949953753089, 562951027167248, 562950221926416]
theorem e20 : enumKeys 218 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0535_b0, by decide, c0535_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 253, c0534_b28, by decide, c0534_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0535_b3, by decide, c0535_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0535_b2, by decide, c0535_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0534_b38, by decide, c0534_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 173, c0534_b36, by decide, c0534_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 182, c0534_b34, by decide, c0534_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0534_b32, by decide, c0534_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0534_b39, by decide, c0534_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0534_b27, by decide, c0534_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 202, c0535_b1, by decide, c0535_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0534_b37, by decide, c0534_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 179, c0534_b35, by decide, c0534_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0534_b31, by decide, c0534_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0534_b24, by decide, c0534_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 189, c0534_b26, by decide, c0534_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0534_b33, by decide, c0534_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0534_b30, by decide, c0534_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 171, c0534_b23, by decide, c0534_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0534_b29, by decide, c0534_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 191, c0534_b25, by decide, c0534_ok25⟩, ?_⟩
  simp

def s21 : List Nat := [844425199091712, 844429225426945, 844426004398081, 844425198895120, 844429225164817, 844426004135953, 844424930459665, 844426003873824, 844425198632992]
theorem e21 : enumKeys 218 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0535_b7, by decide, c0535_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0535_b12, by decide, c0535_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0535_b10, by decide, c0535_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0535_b6, by decide, c0535_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0535_b11, by decide, c0535_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0535_b9, by decide, c0535_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0535_b4, by decide, c0535_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0535_b8, by decide, c0535_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0535_b5, by decide, c0535_ok5⟩, ?_⟩
  simp

def s22 : List Nat := [6755399709622272, 2251800098963456, 6755400514863105, 6755399441186817, 5629568253820929, 2252074691723265, 2251800904269825, 1125968643162113, 5629499802779904, 1125900192121088, 5629500608020737, 5629499534344449, 4503668346978561, 1126174784880897, 1125900997427457, 68736319745, 4503600701178368, 4503599895937536, 274878038528, 285278720, 1090585088]
theorem e22 : enumKeys 218 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0535_b32, by decide, c0535_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0535_b21, by decide, c0535_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0535_b33, by decide, c0535_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0535_b31, by decide, c0535_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 263, c0535_b30, by decide, c0535_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0535_b23, by decide, c0535_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 255, c0535_b22, by decide, c0535_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0535_b19, by decide, c0535_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 263, c0535_b28, by decide, c0535_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0535_b17, by decide, c0535_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0535_b29, by decide, c0535_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0535_b27, by decide, c0535_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0535_b26, by decide, c0535_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0535_b20, by decide, c0535_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 255, c0535_b18, by decide, c0535_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0535_b15, by decide, c0535_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0535_b25, by decide, c0535_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0535_b24, by decide, c0535_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 282, c0535_b16, by decide, c0535_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0535_b13, by decide, c0535_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 291, c0535_b14, by decide, c0535_ok14⟩, ?_⟩
  simp

def s23 : List Nat := [19421773661601792, 1407375219163136, 19421774466842625, 19421773393166337, 18295942205800449, 1408474395312129, 1407376024469505, 281543763361793, 18295873754759424, 281475312320768, 18295874560000257, 18295873486323969, 282574488469761, 281476117627137, 1407375152123904, 1407375957364737, 1407374883688449, 281543696322561, 281476050522368, 281475245281536]
theorem e23 : enumKeys 218 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0536_b12, by decide, c0536_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0536_b3, by decide, c0536_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0536_b13, by decide, c0536_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0536_b11, by decide, c0536_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0536_b10, by decide, c0536_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0536_b6, by decide, c0536_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0536_b5, by decide, c0536_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 283, c0535_b39, by decide, c0535_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0536_b8, by decide, c0536_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 283, c0535_b35, by decide, c0535_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0536_b9, by decide, c0536_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0536_b7, by decide, c0536_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0536_b0, by decide, c0536_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0535_b37, by decide, c0535_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0536_b2, by decide, c0536_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0536_b4, by decide, c0536_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 206, c0536_b1, by decide, c0536_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 215, c0535_b38, by decide, c0535_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0535_b36, by decide, c0535_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 215, c0535_b34, by decide, c0535_ok34⟩, ?_⟩
  simp

def s24 : List Nat := [1688850129027072, 1688854155362305, 1688850934333441, 563018673225729, 1688850128830480, 1688850934071313, 1688849860395025, 563018673029137, 562950222184704, 562954248519937, 562951027491073, 562951027228944, 562950221988112]
theorem e24 : enumKeys 218 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 270, c0536_b23, by decide, c0536_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0536_b26, by decide, c0536_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0536_b25, by decide, c0536_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0536_b20, by decide, c0536_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0536_b22, by decide, c0536_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0536_b24, by decide, c0536_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0536_b21, by decide, c0536_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0536_b19, by decide, c0536_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0536_b15, by decide, c0536_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0536_b18, by decide, c0536_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0536_b17, by decide, c0536_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0536_b16, by decide, c0536_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0536_b14, by decide, c0536_ok14⟩, ?_⟩
  simp

def s25 : List Nat := [2533275058962432, 2533275864268801, 1407443603161089, 1407375152120064, 1407375957426433, 281543696318721, 281475245277696, 281476050584064]
theorem e25 : enumKeys 218 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 300, c0536_b33, by decide, c0536_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0536_b34, by decide, c0536_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 301, c0536_b32, by decide, c0536_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 301, c0536_b30, by decide, c0536_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0536_b31, by decide, c0536_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0536_b29, by decide, c0536_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0536_b27, by decide, c0536_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0536_b28, by decide, c0536_ok28⟩, ?_⟩
  simp

def s26 : List Nat := [27021598032658433, 22517998422065153, 18014398811471873, 9007199590285313, 4503599979692033, 27021597764222978, 22518273014759426, 9008298766368770, 22517998153629698, 18014673404166146, 4504699155775490, 18014398543036418, 1099545182210, 9007199321849858, 4503874572386306, 4503599711256578, 274961793026, 9007199523180545, 4503874505281537, 4503599912587265, 274894688257, 301993985]
theorem e26 : enumKeys 218 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0537_b16, by decide, c0537_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 198, c0537_b13, by decide, c0537_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0537_b10, by decide, c0537_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0537_b7, by decide, c0537_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0537_b1, by decide, c0537_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0537_b15, by decide, c0537_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0537_b14, by decide, c0537_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0537_b8, by decide, c0537_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0537_b12, by decide, c0537_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0537_b11, by decide, c0537_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0537_b4, by decide, c0537_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0537_b9, by decide, c0537_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0536_b38, by decide, c0536_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0537_b5, by decide, c0537_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 208, c0537_b3, by decide, c0537_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 193, c0536_b39, by decide, c0536_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0536_b37, by decide, c0536_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0537_b6, by decide, c0537_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 243, c0537_b2, by decide, c0537_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 201, c0537_b0, by decide, c0537_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0536_b36, by decide, c0536_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0536_b35, by decide, c0536_ok35⟩, ?_⟩
  simp

def s27 : List Nat := [9288674500149249, 4785074889555969, 9288678526418946, 9288674231713794, 4785349482250242, 4785078915825666, 4785074621120514, 281749871656962, 281479305232386, 9288674499887121, 4785349481988113, 4785074889293841, 281749871394833, 281475278700561]
theorem e27 : enumKeys 218 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0537_b29, by decide, c0537_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0537_b23, by decide, c0537_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0537_b30, by decide, c0537_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 180, c0537_b27, by decide, c0537_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0537_b26, by decide, c0537_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0537_b24, by decide, c0537_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 176, c0537_b21, by decide, c0537_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 173, c0537_b20, by decide, c0537_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 164, c0537_b18, by decide, c0537_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0537_b28, by decide, c0537_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 237, c0537_b25, by decide, c0537_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0537_b22, by decide, c0537_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 229, c0537_b19, by decide, c0537_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0537_b17, by decide, c0537_ok17⟩, ?_⟩
  simp

def s28 : List Nat := [10133099430084609, 5629499819491329, 1125900208832513, 10133100235325442, 10133099161649154, 9007267974283266, 5629774412185602, 5629500624732162, 5629499551055874, 4503668363689986, 1126174801592322, 1125901014138882, 68753031170, 9007200328483073, 9007199523242241, 4503874505343233, 4503600717889793, 4503599912648961, 274894749953, 301990145, 1107296513]
theorem e28 : enumKeys 218 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0538_b10, by decide, c0538_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0538_b3, by decide, c0538_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 272, c0537_b35, by decide, c0537_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0538_b11, by decide, c0538_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0538_b9, by decide, c0538_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0538_b8, by decide, c0538_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0538_b5, by decide, c0538_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0538_b4, by decide, c0538_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 211, c0538_b2, by decide, c0538_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0538_b0, by decide, c0538_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0537_b37, by decide, c0537_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0537_b36, by decide, c0537_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0537_b33, by decide, c0537_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 278, c0538_b7, by decide, c0538_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0538_b6, by decide, c0538_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0538_b1, by decide, c0538_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 275, c0537_b39, by decide, c0537_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 226, c0537_b38, by decide, c0537_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 249, c0537_b34, by decide, c0537_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0537_b31, by decide, c0537_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0537_b32, by decide, c0537_ok32⟩, ?_⟩
  simp

def s29 : List Nat := [22799473382064129, 18295873771470849, 4785074939691009, 281475329032193, 22799474187304962, 22799473113628674, 18296148364165122, 4786174115774466, 18295874576711682, 18295873503035394, 282574505181186, 4785075744931842, 4785074671255554, 281749921792002, 281476134338562, 4785075677827073, 4785074872586241, 281749854687233, 281476067233793, 281475261992961]
theorem e29 : enumKeys 218 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0538_b30, by decide, c0538_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0538_b26, by decide, c0538_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 207, c0538_b21, by decide, c0538_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 247, c0538_b13, by decide, c0538_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0538_b31, by decide, c0538_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 178, c0538_b29, by decide, c0538_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 183, c0538_b28, by decide, c0538_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 182, c0538_b24, by decide, c0538_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0538_b27, by decide, c0538_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 171, c0538_b25, by decide, c0538_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 170, c0538_b18, by decide, c0538_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0538_b23, by decide, c0538_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 191, c0538_b19, by decide, c0538_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0538_b17, by decide, c0538_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 197, c0538_b15, by decide, c0538_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0538_b22, by decide, c0538_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 194, c0538_b20, by decide, c0538_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0538_b16, by decide, c0538_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0538_b14, by decide, c0538_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 185, c0538_b12, by decide, c0538_ok12⟩, ?_⟩
  simp

def s30 : List Nat := [5066549849554945, 562950238896129, 5066553875824642, 5066550654795778, 5066549581119490, 563224831655938, 562954265231362, 562951044202498, 5066550654533649, 5066549849292817, 563224831393809, 562951043940369, 562950238699537]
theorem e30 : enumKeys 218 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0539_b1, by decide, c0539_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0538_b33, by decide, c0538_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0539_b4, by decide, c0539_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0539_b3, by decide, c0539_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 174, c0538_b39, by decide, c0538_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 175, c0538_b38, by decide, c0538_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 166, c0538_b36, by decide, c0538_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0538_b35, by decide, c0538_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 234, c0539_b2, by decide, c0539_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0539_b0, by decide, c0539_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 224, c0538_b37, by decide, c0538_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0538_b34, by decide, c0538_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 187, c0538_b32, by decide, c0538_ok32⟩, ?_⟩
  simp

def s31 : List Nat := [5910974779490305, 1407375168831489, 5910975584731138, 5910974511054850, 4785143323688962, 1407649761591298, 1407375974137858, 281543713030146, 4785075677888769, 4785074872647937, 281749854748929, 281475261989121, 281476067295489]
theorem e31 : enumKeys 218 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0539_b16, by decide, c0539_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0539_b9, by decide, c0539_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0539_b17, by decide, c0539_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0539_b15, by decide, c0539_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0539_b14, by decide, c0539_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0539_b11, by decide, c0539_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0539_b10, by decide, c0539_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0539_b7, by decide, c0539_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0539_b13, by decide, c0539_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0539_b12, by decide, c0539_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0539_b8, by decide, c0539_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0539_b5, by decide, c0539_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 255, c0539_b6, by decide, c0539_ok6⟩, ?_⟩
  simp

def s32 : List Nat := [18577348731469825, 562950289031169, 18577349536710658, 18577348463034370, 564049465180162, 562951094337538, 562951027232769, 562950221991937]
theorem e32 : enumKeys 218 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0539_b24, by decide, c0539_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 245, c0539_b19, by decide, c0539_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0539_b25, by decide, c0539_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0539_b23, by decide, c0539_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 172, c0539_b22, by decide, c0539_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 199, c0539_b21, by decide, c0539_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0539_b20, by decide, c0539_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0539_b18, by decide, c0539_ok18⟩, ?_⟩
  simp

def s33 : List Nat := [844425198895105, 844429225230338, 844426004201474, 844426003939345, 844425198698513]
theorem e33 : enumKeys 218 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0539_b27, by decide, c0539_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 168, c0539_b30, by decide, c0539_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0539_b29, by decide, c0539_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0539_b28, by decide, c0539_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 186, c0539_b26, by decide, c0539_ok26⟩, ?_⟩
  simp

def s34 : List Nat := [1688850128830465, 1688850934136834, 563018673029122, 562950221988097, 562951027294465]
theorem e34 : enumKeys 218 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0539_b34, by decide, c0539_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0539_b35, by decide, c0539_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0539_b33, by decide, c0539_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0539_b31, by decide, c0539_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0539_b32, by decide, c0539_ok32⟩, ?_⟩
  simp

def s35 : List Nat := [13510799150546946, 9007474132647938, 9007199539953666, 4503874522054658, 4503599929360386, 274911461378]
theorem e35 : enumKeys 218 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 192, c0540_b1, by decide, c0540_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0540_b0, by decide, c0540_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 200, c0539_b39, by decide, c0539_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 233, c0539_b38, by decide, c0539_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 196, c0539_b37, by decide, c0539_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0539_b36, by decide, c0539_ok36⟩, ?_⟩
  simp

def s36 : List Nat := [9288675305193474, 9288674499952642, 4785349482053634, 4785075694600194, 4785074889359362, 281749871460354, 281475278700546, 281476084006914]
theorem e36 : enumKeys 218 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0540_b9, by decide, c0540_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 188, c0540_b8, by decide, c0540_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 223, c0540_b7, by decide, c0540_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 232, c0540_b6, by decide, c0540_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 190, c0540_b5, by decide, c0540_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 213, c0540_b4, by decide, c0540_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0540_b2, by decide, c0540_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0540_b3, by decide, c0540_ok3⟩, ?_⟩
  simp

def s37 : List Nat := [5066550654599170, 5066549849358338, 563224831459330, 562950238699522, 562951044005890]
theorem e37 : enumKeys 218 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0540_b14, by decide, c0540_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 184, c0540_b13, by decide, c0540_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0540_b12, by decide, c0540_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0540_b10, by decide, c0540_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 219, c0540_b11, by decide, c0540_ok11⟩, ?_⟩
  simp

def s38 : List Nat := [844425198698498, 844426004004866]
theorem e38 : enumKeys 218 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0540_b15, by decide, c0540_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0540_b16, by decide, c0540_ok16⟩, ?_⟩
  simp

/-- every enumerated key with left type `218` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 218 mR,
    (218 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 218) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K33
end Grid3.Three.Cert
