import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4022
import Grid3.Three.Cert.Data.C4023
import Grid3.Three.Cert.Data.C4024
import Grid3.Three.Cert.Data.C4025
import Grid3.Three.Cert.Data.C4026
import Grid3.Three.Cert.Data.C4027
import Grid3.Three.Cert.Data.C4028
import Grid3.Three.Cert.Data.C4029
import Grid3.Three.Cert.Data.C4030
import Grid3.Three.Cert.Data.C4031
import Grid3.Three.Cert.Data.C4032
import Grid3.Three.Cert.Data.C4033
import Grid3.Three.Cert.Data.C4034
import Grid3.Three.Cert.Data.C4035
import Grid3.Three.Cert.Data.C4036
import Grid3.Three.Cert.Data.C4037
import Grid3.Three.Cert.Data.C4038
import Grid3.Three.Cert.Data.C4039
import Grid3.Three.Cert.Data.C4040
import Grid3.Three.Cert.Data.C4041
import Grid3.Three.Cert.Data.C4042
import Grid3.Three.Cert.Data.C4043
import Grid3.Three.Cert.Data.C4044
import Grid3.Three.Cert.Data.C4045
import Grid3.Three.Cert.Data.C4046
import Grid3.Three.Cert.Data.C4047
import Grid3.Three.Cert.Data.C4048
import Grid3.Three.Cert.Data.C4049
import Grid3.Three.Cert.Data.C4050
import Grid3.Three.Cert.Data.C4051
import Grid3.Three.Cert.Data.C4052
import Grid3.Three.Cert.Data.C4053
import Grid3.Three.Cert.Data.C4054
import Grid3.Three.Cert.Data.C4055
import Grid3.Three.Cert.Data.C4056
import Grid3.Three.Cert.Data.C4057
import Grid3.Three.Cert.Data.C4058
import Grid3.Three.Cert.Data.C4059
import Grid3.Three.Cert.Data.C4060
import Grid3.Three.Cert.Data.C4061
import Grid3.Three.Cert.Data.C4062
import Grid3.Three.Cert.Data.C4063
import Grid3.Three.Cert.Data.C4064
import Grid3.Three.Cert.Data.C4065
import Grid3.Three.Cert.Data.C4066
import Grid3.Three.Cert.Data.C4067
import Grid3.Three.Cert.Data.C4068
import Grid3.Three.Cert.Data.C4069
import Grid3.Three.Cert.Data.C4070
import Grid3.Three.Cert.Data.C4071
import Grid3.Three.Cert.Data.C4072
import Grid3.Three.Cert.Data.C4073
import Grid3.Three.Cert.Data.C4074
import Grid3.Three.Cert.Data.C4075
import Grid3.Three.Cert.Data.C4076
import Grid3.Three.Cert.Data.C4077
import Grid3.Three.Cert.Data.C4078
import Grid3.Three.Cert.Data.C4079
import Grid3.Three.Cert.Data.C4080
import Grid3.Three.Cert.Data.C4081
import Grid3.Three.Cert.Data.C4082
import Grid3.Three.Cert.Data.C4083
import Grid3.Three.Cert.Data.C4084
import Grid3.Three.Cert.Data.C4085
import Grid3.Three.Cert.Data.C4086
import Grid3.Three.Cert.Data.C4087
import Grid3.Three.Cert.Data.C4088
import Grid3.Three.Cert.Data.C4089
import Grid3.Three.Cert.Data.C4090
import Grid3.Three.Cert.Data.C4091
import Grid3.Three.Cert.Data.C4092
import Grid3.Three.Cert.Data.C4093
import Grid3.Three.Cert.Data.C4094
import Grid3.Three.Cert.Data.C4095
import Grid3.Three.Cert.Data.C4096
import Grid3.Three.Cert.Data.C4097
import Grid3.Three.Cert.Data.C4098

/-! Seam keys with left type `218` (type index 33): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K33

def s00 : List Nat := [54043195528445952, 36029896530591744, 36028797086072832, 18015498088218624, 18014398643699712, 1099645845504, 36028797018968064, 18015498021113856, 18014398576594944, 1099578740736, 134221824, 18014398509490176, 1099511635968, 67117056]
theorem e00 : enumKeys 218 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4022_b5, by decide, c4022_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c4022_b6, by decide, c4022_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c4022_b7, by decide, c4022_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c4022_b8, by decide, c4022_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c4022_b9, by decide, c4022_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c4023_b0, by decide, c4023_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c4023_b1, by decide, c4023_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c4023_b2, by decide, c4023_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c4023_b3, by decide, c4023_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c4023_b4, by decide, c4023_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4023_b5, by decide, c4023_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 190, c4023_b6, by decide, c4023_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c4023_b7, by decide, c4023_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4023_b8, by decide, c4023_ok8⟩, ?_⟩
  simp

def s01 : List Nat := [23643902338662400, 23643898043957248, 22518066856591360, 19140573294493696, 5630599046103040, 19140302728069120, 19140298433363968, 18014467245998080, 1126999435509760, 5629503896289280, 5629499601584128, 4503668414218240, 1126174852120576, 1125904285696000, 23643898043695120, 22518066856329232, 19140573294231568, 5630599045840912, 19140298433101840, 18014467245735952, 1126999435247632, 5629499601322000, 4503668413956112, 1126174851858448, 1125899990728720, 68803362832, 22518002431820032, 22517998137114880, 18014673387651328, 4504699139260672, 18014402821226752, 18014398526521600, 1099528667392, 4503603989446912, 4503599694741760, 274945278208, 4378853632, 22517998136852752, 18014673387389200, 4504699138998544, 18014398526259472, 1099528405264, 4503599694479632, 274945016080, 83886352, 5629503829184512, 5629499534479360, 4503668347113472, 1126174785015808, 1125904218591232, 1125899923886080, 68736520192, 5629499534217232, 4503668346851344, 1126174784753680, 1125899923623952, 68736258064, 4503603922342144, 4503599627636992, 274878173440, 4311748864, 17043712]
theorem e01 : enumKeys 218 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4023_b9, by decide, c4023_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4024_b3, by decide, c4024_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4024_b6, by decide, c4024_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4024_b5, by decide, c4024_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4024_b4, by decide, c4024_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4024_b1, by decide, c4024_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4025_b0, by decide, c4025_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4025_b2, by decide, c4025_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4025_b1, by decide, c4025_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4024_b0, by decide, c4024_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4024_b7, by decide, c4024_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4024_b9, by decide, c4024_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4024_b8, by decide, c4024_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4024_b2, by decide, c4024_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4027_b6, by decide, c4027_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4027_b9, by decide, c4027_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4027_b8, by decide, c4027_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4027_b7, by decide, c4027_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4028_b3, by decide, c4028_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4028_b5, by decide, c4028_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4028_b4, by decide, c4028_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4028_b0, by decide, c4028_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4028_b2, by decide, c4028_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4028_b1, by decide, c4028_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4028_b6, by decide, c4028_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4028_b7, by decide, c4028_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4026_b0, by decide, c4026_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4026_b4, by decide, c4026_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4026_b6, by decide, c4026_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4026_b5, by decide, c4026_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4026_b2, by decide, c4026_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4026_b9, by decide, c4026_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4027_b0, by decide, c4027_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4026_b1, by decide, c4026_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4026_b7, by decide, c4026_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4026_b8, by decide, c4026_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4026_b3, by decide, c4026_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4029_b3, by decide, c4029_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4029_b5, by decide, c4029_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4029_b4, by decide, c4029_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4029_b8, by decide, c4029_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4029_b9, by decide, c4029_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4029_b6, by decide, c4029_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4029_b7, by decide, c4029_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4030_b0, by decide, c4030_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4025_b3, by decide, c4025_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4025_b5, by decide, c4025_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4025_b7, by decide, c4025_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4025_b6, by decide, c4025_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4025_b4, by decide, c4025_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4025_b8, by decide, c4025_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4025_b9, by decide, c4025_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4028_b8, by decide, c4028_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4029_b0, by decide, c4029_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4028_b9, by decide, c4028_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4029_b1, by decide, c4029_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4029_b2, by decide, c4029_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4027_b1, by decide, c4027_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4027_b3, by decide, c4027_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4027_b4, by decide, c4027_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4027_b2, by decide, c4027_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4027_b5, by decide, c4027_ok5⟩, ?_⟩
  simp

def s02 : List Nat := [36310276290641920, 36310271995936768, 18296972998082560, 18295877848268800, 18295873553563648, 282574555709440, 281479405895680, 36310271995674640, 18296972997820432, 18295873553301520, 282574555447312, 281475110928400, 18295877781164032, 18295873486458880, 282574488604672, 281479338790912, 281475044085760, 18295873486196752, 282574488342544, 281475043823632, 281479271686144, 281474976980992]
theorem e02 : enumKeys 218 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4030_b1, by decide, c4030_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4030_b4, by decide, c4030_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4030_b5, by decide, c4030_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4030_b2, by decide, c4030_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4030_b6, by decide, c4030_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4030_b7, by decide, c4030_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4030_b3, by decide, c4030_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4031_b5, by decide, c4031_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4031_b6, by decide, c4031_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4031_b7, by decide, c4031_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4031_b8, by decide, c4031_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4031_b9, by decide, c4031_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4030_b8, by decide, c4030_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4031_b0, by decide, c4031_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4031_b1, by decide, c4031_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4030_b9, by decide, c4030_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4031_b2, by decide, c4031_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4032_b0, by decide, c4032_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4032_b1, by decide, c4032_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4032_b2, by decide, c4032_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4031_b3, by decide, c4031_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4031_b4, by decide, c4031_ok4⟩, ?_⟩
  simp

def s03 : List Nat := [5910978806153216, 5910974511448064, 4785143324082176, 1407649761984512, 1407379195559936, 5910978805891088, 5910974511185936, 4785143323820048, 1407649761722384, 1407379195297808, 1407374900592656, 281543713226768, 5910974510923808, 4785143323557920, 1407649761460256, 1407374900330528, 281543712964640, 4785078899310848, 4785074604605696, 281749855142144, 281479288717568, 4785078899048720, 4785074604343568, 281749854880016, 281479288455440, 281474993750288]
theorem e03 : enumKeys 218 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4032_b3, by decide, c4032_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4032_b5, by decide, c4032_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4032_b7, by decide, c4032_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4032_b6, by decide, c4032_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4032_b4, by decide, c4032_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4033_b2, by decide, c4033_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4033_b4, by decide, c4033_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4033_b6, by decide, c4033_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4033_b5, by decide, c4033_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4033_b3, by decide, c4033_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4033_b7, by decide, c4033_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4033_b8, by decide, c4033_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4034_b4, by decide, c4034_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4034_b6, by decide, c4034_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4034_b5, by decide, c4034_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4034_b7, by decide, c4034_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4034_b8, by decide, c4034_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4032_b8, by decide, c4032_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4033_b0, by decide, c4033_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4033_b1, by decide, c4033_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4032_b9, by decide, c4032_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4033_b9, by decide, c4033_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4034_b1, by decide, c4034_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4034_b2, by decide, c4034_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4034_b0, by decide, c4034_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4034_b3, by decide, c4034_ok3⟩, ?_⟩
  simp

def s04 : List Nat := [18577352758132736, 18577348463427584, 564049465573376, 562954315759616, 18577352757870608, 18577348463165456, 564049465311248, 562954315497488, 562950020792336, 18577348462903328, 564049465049120, 562950020530208, 562954248654848, 562949953949696, 562954248392720, 562949953687568]
theorem e04 : enumKeys 218 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4034_b9, by decide, c4034_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4035_b1, by decide, c4035_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4035_b2, by decide, c4035_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4035_b0, by decide, c4035_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4035_b5, by decide, c4035_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4035_b7, by decide, c4035_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4035_b8, by decide, c4035_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4035_b6, by decide, c4035_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4035_b9, by decide, c4035_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4036_b2, by decide, c4036_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4036_b3, by decide, c4036_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4036_b4, by decide, c4036_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4035_b3, by decide, c4035_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4035_b4, by decide, c4035_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4036_b0, by decide, c4036_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4036_b1, by decide, c4036_ok1⟩, ?_⟩
  simp

def s05 : List Nat := [844429225623552, 844429225361424, 844424930656272, 844429225099296, 844424930394144]
theorem e05 : enumKeys 218 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4036_b5, by decide, c4036_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4036_b6, by decide, c4036_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4036_b7, by decide, c4036_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4036_b8, by decide, c4036_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4036_b9, by decide, c4036_ok9⟩, ?_⟩
  simp

def s06 : List Nat := [37154697999548416, 37154696925872128, 36028865738506240, 19141397928017920, 19140299557175296, 19140298483499008, 18014467296133120, 1126999485644800, 1125901114802176, 68853694464, 36028798092706048, 36028797019029760, 18015498021175552, 18014399650332928, 18014398576656640, 1099578802432, 1207959808, 19140299490070528, 19140298416394240, 18014467229028352, 1126999418540032, 1125901047697408, 1125899974021120, 68786655232, 18014399583228160, 18014398509551872, 1099511697664, 1140855040, 67178752, 1125900980592640, 1125899906916352, 68719550464]
theorem e06 : enumKeys 218 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4037_b0, by decide, c4037_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4037_b4, by decide, c4037_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4037_b6, by decide, c4037_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4037_b5, by decide, c4037_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4037_b1, by decide, c4037_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4037_b7, by decide, c4037_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4037_b9, by decide, c4037_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4037_b8, by decide, c4037_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4037_b3, by decide, c4037_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4037_b2, by decide, c4037_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4039_b0, by decide, c4039_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4039_b3, by decide, c4039_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4039_b4, by decide, c4039_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4039_b1, by decide, c4039_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4039_b5, by decide, c4039_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4039_b6, by decide, c4039_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4039_b2, by decide, c4039_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4038_b0, by decide, c4038_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4038_b2, by decide, c4038_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4038_b4, by decide, c4038_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4038_b3, by decide, c4038_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4038_b1, by decide, c4038_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4038_b5, by decide, c4038_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4038_b6, by decide, c4038_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4039_b7, by decide, c4039_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4039_b9, by decide, c4039_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4040_b0, by decide, c4040_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4039_b8, by decide, c4039_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4040_b1, by decide, c4040_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4038_b7, by decide, c4038_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4038_b8, by decide, c4038_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4038_b9, by decide, c4038_ok9⟩, ?_⟩
  simp

def s07 : List Nat := [6755403736088576, 6755400515059712, 6755399441383424, 5629568254017536, 2252074691919872, 2251804125495296, 2251800904466432, 1125968643358720, 6755400514797584, 6755399441121296, 5629568253755408, 2252074691657744, 2251800904204304, 2251799830528016, 1125968643162128, 5629503829246208, 5629500608217344, 5629499534541056, 4503668347175168, 1126174785077504, 1125904218652928, 1125900997624064, 68736516352, 5629500607955216, 5629499534278928, 4503668346913040, 1126174784815376, 1125900997361936, 1125899923685648, 68736319760, 4503603922403840, 4503600701374976, 4503599627698688, 274878235136, 4311810560, 1090781696]
theorem e07 : enumKeys 218 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4040_b5, by decide, c4040_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4040_b2, by decide, c4040_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4040_b7, by decide, c4040_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4040_b9, by decide, c4040_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4040_b8, by decide, c4040_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4040_b6, by decide, c4040_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4040_b4, by decide, c4040_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 318, c4040_b3, by decide, c4040_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4042_b4, by decide, c4042_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4042_b6, by decide, c4042_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 277, c4042_b8, by decide, c4042_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4042_b7, by decide, c4042_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4042_b5, by decide, c4042_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4042_b9, by decide, c4042_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4043_b0, by decide, c4043_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4041_b3, by decide, c4041_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 273, c4041_b0, by decide, c4041_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4041_b5, by decide, c4041_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4041_b7, by decide, c4041_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4041_b6, by decide, c4041_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4041_b4, by decide, c4041_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4041_b2, by decide, c4041_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4041_b1, by decide, c4041_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c4043_b1, by decide, c4043_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4043_b3, by decide, c4043_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4043_b5, by decide, c4043_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4043_b4, by decide, c4043_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4043_b2, by decide, c4043_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4043_b6, by decide, c4043_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4043_b7, by decide, c4043_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4042_b0, by decide, c4042_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4041_b8, by decide, c4041_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4042_b2, by decide, c4042_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4042_b3, by decide, c4042_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4042_b1, by decide, c4042_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4041_b9, by decide, c4041_ok9⟩, ?_⟩
  simp

def s08 : List Nat := [19421777688068096, 19421774467039232, 19421773393362944, 18295942205997056, 1408474395508736, 1407379245694976, 1407376024666112, 281543763558400, 19421774466777104, 19421773393100816, 18295942205734928, 1408474395246608, 1407376024403984, 1407374950727696, 281543763361808, 18295877781225728, 18295874560196864, 18295873486520576, 282574488666368, 281479338852608, 281476117823744, 18295874559934736, 18295873486258448, 282574488404240, 281476117561616, 281475043885328, 1407379178590208, 1407375957561344, 1407374883885056, 281543696519168, 1407375957299216, 1407374883622928, 281543696257040, 281479271747840, 281476050718976, 281474977042688]
theorem e08 : enumKeys 218 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4044_b1, by decide, c4044_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4043_b8, by decide, c4043_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4044_b3, by decide, c4044_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4044_b5, by decide, c4044_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4044_b4, by decide, c4044_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4044_b2, by decide, c4044_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4044_b0, by decide, c4044_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 293, c4043_b9, by decide, c4043_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4045_b9, by decide, c4045_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4046_b1, by decide, c4046_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4046_b3, by decide, c4046_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4046_b2, by decide, c4046_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4046_b0, by decide, c4046_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4046_b4, by decide, c4046_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4046_b5, by decide, c4046_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4045_b2, by decide, c4045_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4045_b0, by decide, c4045_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4045_b4, by decide, c4045_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4045_b5, by decide, c4045_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4045_b3, by decide, c4045_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4045_b1, by decide, c4045_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4046_b9, by decide, c4046_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4047_b1, by decide, c4047_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4047_b2, by decide, c4047_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4047_b0, by decide, c4047_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4047_b3, by decide, c4047_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4044_b7, by decide, c4044_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4044_b6, by decide, c4044_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4044_b8, by decide, c4044_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4044_b9, by decide, c4044_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4046_b6, by decide, c4046_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4046_b7, by decide, c4046_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4046_b8, by decide, c4046_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4045_b7, by decide, c4045_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4045_b6, by decide, c4045_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4045_b8, by decide, c4045_ok8⟩, ?_⟩
  simp

def s09 : List Nat := [1688854155558912, 1688850934530048, 563018673422336, 1688854155296784, 1688850934267920, 1688849860591632, 563018673225744, 1688850934005792, 1688849860329504, 563018672963616, 562954248716544, 562951027687680, 562954248454416, 562951027425552, 562949953749264]
theorem e09 : enumKeys 218 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4047_b6, by decide, c4047_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4047_b5, by decide, c4047_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c4047_b4, by decide, c4047_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4048_b0, by decide, c4048_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4047_b9, by decide, c4047_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4048_b1, by decide, c4048_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4048_b2, by decide, c4048_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4048_b6, by decide, c4048_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4048_b7, by decide, c4048_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4048_b8, by decide, c4048_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4047_b8, by decide, c4047_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4047_b7, by decide, c4047_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4048_b4, by decide, c4048_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4048_b3, by decide, c4048_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4048_b5, by decide, c4048_ok5⟩, ?_⟩
  simp

def s10 : List Nat := [20266199396974592, 20266198323298304, 19140367135932416, 2252899325444096, 2251800954601472, 1125968693493760, 19140299490132224, 19140298416455936, 18014467229090048, 1126999418601728, 1125901047759104, 68786651392, 18014399583289856, 18014398509613568, 1099511759360, 1140916736, 2251800887496704, 2251799813820416, 1125968626454528, 1125900980654336, 1125899906978048, 68719612160]
theorem e10 : enumKeys 218 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4048_b9, by decide, c4048_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4049_b2, by decide, c4049_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4049_b4, by decide, c4049_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4049_b3, by decide, c4049_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4049_b1, by decide, c4049_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c4049_b0, by decide, c4049_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4049_b8, by decide, c4049_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4050_b1, by decide, c4050_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4050_b3, by decide, c4050_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4050_b2, by decide, c4050_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4050_b0, by decide, c4050_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c4049_b9, by decide, c4049_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4050_b7, by decide, c4050_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4050_b9, by decide, c4050_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4051_b0, by decide, c4051_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4050_b8, by decide, c4050_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4049_b5, by decide, c4049_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4049_b6, by decide, c4049_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4049_b7, by decide, c4049_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4050_b4, by decide, c4050_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4050_b5, by decide, c4050_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4050_b6, by decide, c4050_ok6⟩, ?_⟩
  simp

def s11 : List Nat := [2533279085494272, 2533275864465408, 1407443603357696, 2533275864203280, 2533274790526992, 1407443603161104, 1407379178651904, 1407375957623040, 281543696515328, 1407375957360912, 1407374883684624, 281543696318736, 281479271809536, 281476050780672]
theorem e11 : enumKeys 218 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4051_b3, by decide, c4051_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4051_b2, by decide, c4051_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c4051_b1, by decide, c4051_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4051_b9, by decide, c4051_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4052_b0, by decide, c4052_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4052_b1, by decide, c4052_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4051_b6, by decide, c4051_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4051_b5, by decide, c4051_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c4051_b4, by decide, c4051_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4052_b2, by decide, c4052_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4052_b3, by decide, c4052_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4052_b4, by decide, c4052_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4051_b8, by decide, c4051_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4051_b7, by decide, c4051_ok7⟩, ?_⟩
  simp

def s12 : List Nat := [3377700794400768, 2251868533293056, 2251800887558400, 1125968626450688, 1125900980716032, 68719608320]
theorem e12 : enumKeys 218 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4052_b6, by decide, c4052_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c4052_b5, by decide, c4052_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4052_b8, by decide, c4052_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c4052_b7, by decide, c4052_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4053_b0, by decide, c4053_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4052_b9, by decide, c4052_ok9⟩, ?_⟩
  simp

def s13 : List Nat := [40532396914769920, 36028797304176640, 22517998472396800, 18014398861803520, 4503600030023680, 40532396646334465, 36029071896870913, 22519097648480257, 36028797035741185, 18015498037886977, 22517998203961345, 18014673454497793, 4504699206107137, 18014398593368065, 1099595513857, 4503599761588225, 275012124673, 22517998405292032, 18014398794698752, 4503599962918912, 352325632, 22517998136856577, 18014673387393025, 4504699139002369, 18014398526263297, 1099528409089, 4503599694483457, 274945019905, 83890177, 4503599895814144, 274877915136, 285220864]
theorem e13 : enumKeys 218 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4053_b1, by decide, c4053_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4053_b4, by decide, c4053_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4053_b2, by decide, c4053_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4053_b5, by decide, c4053_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4053_b3, by decide, c4053_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4054_b3, by decide, c4054_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4054_b5, by decide, c4054_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4054_b4, by decide, c4054_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4055_b1, by decide, c4055_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4055_b2, by decide, c4055_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4054_b6, by decide, c4054_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4054_b8, by decide, c4054_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4054_b7, by decide, c4054_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4055_b3, by decide, c4055_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4055_b4, by decide, c4055_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4054_b9, by decide, c4054_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4055_b0, by decide, c4055_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4053_b6, by decide, c4053_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4053_b8, by decide, c4053_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4053_b7, by decide, c4053_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4053_b9, by decide, c4053_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4055_b5, by decide, c4055_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4055_b7, by decide, c4055_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4055_b6, by decide, c4055_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4056_b0, by decide, c4056_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4056_b1, by decide, c4056_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4055_b8, by decide, c4055_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4055_b9, by decide, c4055_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4056_b2, by decide, c4056_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4054_b1, by decide, c4054_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4054_b0, by decide, c4054_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4054_b2, by decide, c4054_ok2⟩, ?_⟩
  simp

def s14 : List Nat := [10133099430281216, 5629499819687936, 10133103456550913, 10133099161845761, 9007267974479873, 5629774412382209, 5629503845957633, 5629499551252481, 4503668363886593, 1126174801788929, 1125904235364353, 10133099430019088, 5629499819425808, 1125900208832528, 10133099161583633, 9007267974217745, 5629774412120081, 5629499550990353, 4503668363624465, 1126174801526801, 1125899940397073, 68753031185, 9007199523438848, 4503599912845568, 9007203549708545, 9007199255003393, 4503874505539841, 4503603939115265, 4503599644410113, 274894946561, 4328521985, 9007199523176720, 4503874505277712, 4503599912583440, 274894684432, 301990160]
theorem e14 : enumKeys 218 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4056_b3, by decide, c4056_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4056_b4, by decide, c4056_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4057_b5, by decide, c4057_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4057_b8, by decide, c4057_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4058_b0, by decide, c4058_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4057_b9, by decide, c4057_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4057_b6, by decide, c4057_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4058_b1, by decide, c4058_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4058_b3, by decide, c4058_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4058_b2, by decide, c4058_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4057_b7, by decide, c4057_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4056_b7, by decide, c4056_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4056_b8, by decide, c4056_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4056_b9, by decide, c4056_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4059_b1, by decide, c4059_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4059_b3, by decide, c4059_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4059_b2, by decide, c4059_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4059_b4, by decide, c4059_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4059_b6, by decide, c4059_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4059_b5, by decide, c4059_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4059_b7, by decide, c4059_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4059_b8, by decide, c4059_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4056_b5, by decide, c4056_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4056_b6, by decide, c4056_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4058_b4, by decide, c4058_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4058_b7, by decide, c4058_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4058_b8, by decide, c4058_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4058_b5, by decide, c4058_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4058_b9, by decide, c4058_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4059_b0, by decide, c4059_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4058_b6, by decide, c4058_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4057_b1, by decide, c4057_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4057_b0, by decide, c4057_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4057_b3, by decide, c4057_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4057_b2, by decide, c4057_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4057_b4, by decide, c4057_ok4⟩, ?_⟩
  simp

def s15 : List Nat := [22799473382260736, 18295873771667456, 4785074939887616, 22799477408530433, 22799473113825281, 18296148364361729, 4786174115971073, 18295877797937153, 18295873503232001, 282574505377793, 4785078966157313, 4785074671452161, 281749921988609, 281479355564033, 22799473381998608, 18295873771405328, 4785074939625488, 281475329032208, 22799473113563153, 18296148364099601, 4786174115708945, 18295873502969873, 282574505115665, 4785074671190033, 281749921726481, 281475060596753, 4785074872782848, 281475262189568, 4785078899052545, 4785074604347393, 281749854883841, 281479288459265, 281474993754113, 4785074872520720, 281749854621712, 281475261927440]
theorem e15 : enumKeys 218 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4059_b9, by decide, c4059_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4060_b1, by decide, c4060_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4060_b0, by decide, c4060_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4061_b1, by decide, c4061_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4061_b5, by decide, c4061_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4061_b7, by decide, c4061_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4061_b6, by decide, c4061_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4061_b3, by decide, c4061_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4062_b0, by decide, c4062_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4062_b1, by decide, c4062_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4061_b2, by decide, c4061_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4061_b8, by decide, c4061_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4061_b9, by decide, c4061_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4061_b4, by decide, c4061_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4060_b4, by decide, c4060_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4060_b6, by decide, c4060_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4060_b5, by decide, c4060_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4060_b7, by decide, c4060_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4062_b7, by decide, c4062_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4062_b9, by decide, c4062_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4062_b8, by decide, c4062_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4063_b2, by decide, c4063_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4063_b3, by decide, c4063_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4063_b0, by decide, c4063_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4063_b1, by decide, c4063_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4063_b4, by decide, c4063_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4060_b2, by decide, c4060_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4060_b3, by decide, c4060_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4062_b2, by decide, c4062_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4062_b4, by decide, c4062_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4062_b5, by decide, c4062_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4062_b3, by decide, c4062_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4062_b6, by decide, c4062_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4060_b9, by decide, c4060_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4060_b8, by decide, c4060_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4061_b0, by decide, c4061_ok0⟩, ?_⟩
  simp

def s16 : List Nat := [5066549849751552, 5066553876021249, 5066549581316097, 563224831852545, 562954265427969, 5066549849489424, 562950238896144, 5066553875759121, 5066549581053969, 563224831590417, 562954265165841, 562949970460689, 5066549849227296, 563224831328288, 562950238634016]
theorem e16 : enumKeys 218 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4063_b5, by decide, c4063_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4064_b1, by decide, c4064_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4064_b3, by decide, c4064_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4064_b4, by decide, c4064_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4064_b2, by decide, c4064_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4063_b6, by decide, c4063_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4063_b7, by decide, c4063_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4064_b5, by decide, c4064_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4064_b7, by decide, c4064_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4064_b8, by decide, c4064_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4064_b6, by decide, c4064_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4064_b9, by decide, c4064_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4063_b9, by decide, c4063_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4063_b8, by decide, c4063_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4064_b0, by decide, c4064_ok0⟩, ?_⟩
  simp

def s17 : List Nat := [23643898312196096, 19140298701602816, 5629499869822976, 1125900259164160, 23643899117436929, 23643898043760641, 22518066856394753, 19140573294297089, 5630599045906433, 19140299506843649, 19140298433167361, 18014467245801473, 1126999435313153, 5629500675063809, 5629499601387521, 4503668414021633, 1126174851923969, 1125901064470529, 68803362817, 22517998405353728, 18014398794760448, 4503599962980608, 352321792, 22517999210594561, 22517998136918273, 18014673387454721, 4504699139064065, 18014399600001281, 18014398526324993, 1099528470785, 4503600768221441, 4503599694545153, 274945081601, 1157628161, 5629499802718208, 1125900192124928, 5629500607959041, 5629499534282753, 4503668346916865, 1126174784819201, 1125900997365761, 1125899923689473, 68736323585, 4503600701116672, 4503599895875840, 274877976832, 1090523392, 285282560]
theorem e17 : enumKeys 218 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4065_b1, by decide, c4065_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4065_b3, by decide, c4065_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4065_b2, by decide, c4065_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 291, c4065_b0, by decide, c4065_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4066_b5, by decide, c4066_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4067_b0, by decide, c4067_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4067_b3, by decide, c4067_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4067_b2, by decide, c4067_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4067_b1, by decide, c4067_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4066_b7, by decide, c4066_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4067_b7, by decide, c4067_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4067_b9, by decide, c4067_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4067_b8, by decide, c4067_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4066_b6, by decide, c4066_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4067_b4, by decide, c4067_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4067_b6, by decide, c4067_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4067_b5, by decide, c4067_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4066_b9, by decide, c4066_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4066_b8, by decide, c4066_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4065_b7, by decide, c4065_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4065_b9, by decide, c4065_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4065_b8, by decide, c4065_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4065_b6, by decide, c4065_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4068_b7, by decide, c4068_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4069_b1, by decide, c4069_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4069_b3, by decide, c4069_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4069_b2, by decide, c4069_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4068_b9, by decide, c4068_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4069_b6, by decide, c4069_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4069_b7, by decide, c4069_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4068_b8, by decide, c4068_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4069_b4, by decide, c4069_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4069_b5, by decide, c4069_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4069_b0, by decide, c4069_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4065_b4, by decide, c4065_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4065_b5, by decide, c4065_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4068_b0, by decide, c4068_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4068_b2, by decide, c4068_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4068_b4, by decide, c4068_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4068_b3, by decide, c4068_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4068_b1, by decide, c4068_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4068_b5, by decide, c4068_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4068_b6, by decide, c4068_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4066_b0, by decide, c4066_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4066_b3, by decide, c4066_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4066_b2, by decide, c4066_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4066_b1, by decide, c4066_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4066_b4, by decide, c4066_ok4⟩, ?_⟩
  simp

def s18 : List Nat := [36310272264175616, 18295873821802496, 281475379363840, 36310273069416449, 36310271995740161, 18296972997885953, 18295874627043329, 18295873553367041, 282574555512833, 281476184670209, 18295873754697728, 281475312324608, 18295874559938561, 18295873486262273, 282574488408065, 281476117565441, 281475043889153, 281476050460672, 281475245219840]
theorem e18 : enumKeys 218 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4069_b9, by decide, c4069_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4070_b0, by decide, c4070_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4069_b8, by decide, c4069_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4070_b5, by decide, c4070_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4070_b8, by decide, c4070_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4070_b9, by decide, c4070_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4070_b6, by decide, c4070_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4071_b0, by decide, c4071_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4071_b1, by decide, c4071_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4070_b7, by decide, c4070_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4070_b1, by decide, c4070_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4070_b2, by decide, c4070_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4071_b2, by decide, c4071_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4071_b4, by decide, c4071_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4071_b5, by decide, c4071_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4071_b3, by decide, c4071_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4071_b6, by decide, c4071_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4070_b3, by decide, c4070_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4070_b4, by decide, c4070_ok4⟩, ?_⟩
  simp

def s19 : List Nat := [5910974779686912, 1407375169028096, 5910978805956609, 5910975584927745, 5910974511251457, 4785143323885569, 1407649761787905, 1407379195363329, 1407375974334465, 281543713226753, 5910974779424784, 1407375168831504, 5910975584665617, 5910974510989329, 4785143323623441, 1407649761525777, 1407375974072337, 1407374900396049, 281543713030161, 4785074872844544, 281475262185728, 4785078899114241, 4785075678085377, 4785074604409089, 281749854945537, 281479288520961, 281476067492097, 4785075677823248, 4785074872582416, 281749854683408, 281476067229968, 281475261989136]
theorem e19 : enumKeys 218 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4071_b8, by decide, c4071_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 273, c4071_b7, by decide, c4071_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4073_b1, by decide, c4073_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4072_b8, by decide, c4072_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4073_b3, by decide, c4073_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4073_b5, by decide, c4073_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4073_b4, by decide, c4073_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4073_b2, by decide, c4073_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4073_b0, by decide, c4073_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4072_b9, by decide, c4072_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4072_b1, by decide, c4072_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4072_b2, by decide, c4072_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4074_b2, by decide, c4074_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4074_b4, by decide, c4074_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4074_b6, by decide, c4074_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4074_b5, by decide, c4074_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4074_b3, by decide, c4074_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4074_b7, by decide, c4074_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4074_b8, by decide, c4074_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4072_b0, by decide, c4072_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4071_b9, by decide, c4071_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4073_b8, by decide, c4073_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4073_b6, by decide, c4073_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4074_b0, by decide, c4074_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4074_b1, by decide, c4074_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4073_b9, by decide, c4073_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4073_b7, by decide, c4073_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c4072_b3, by decide, c4072_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4072_b6, by decide, c4072_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4072_b5, by decide, c4072_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4072_b4, by decide, c4072_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4072_b7, by decide, c4072_ok7⟩, ?_⟩
  simp

def s20 : List Nat := [18577348731666432, 562950289227776, 18577352757936129, 18577349536907265, 18577348463230977, 564049465376769, 562954315563009, 562951094534145, 18577348731404304, 562950289031184, 18577349536645137, 18577348462968849, 564049465114641, 562951094272017, 562950020595729, 562950222188544, 562954248458241, 562951027429377, 562949953753089, 562951027167248, 562950221926416]
theorem e20 : enumKeys 218 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4075_b0, by decide, c4075_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 253, c4074_b9, by decide, c4074_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4075_b8, by decide, c4075_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4075_b6, by decide, c4075_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4076_b0, by decide, c4076_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4076_b1, by decide, c4076_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4075_b9, by decide, c4075_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4075_b7, by decide, c4075_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4075_b2, by decide, c4075_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4075_b3, by decide, c4075_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4076_b5, by decide, c4076_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4076_b7, by decide, c4076_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4076_b8, by decide, c4076_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4076_b6, by decide, c4076_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4076_b9, by decide, c4076_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4075_b1, by decide, c4075_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4076_b3, by decide, c4076_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4076_b2, by decide, c4076_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4076_b4, by decide, c4076_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4075_b4, by decide, c4075_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4075_b5, by decide, c4075_ok5⟩, ?_⟩
  simp

def s21 : List Nat := [844425199091712, 844429225426945, 844426004398081, 844425198895120, 844429225164817, 844426004135953, 844424930459665, 844426003873824, 844425198632992]
theorem e21 : enumKeys 218 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4077_b0, by decide, c4077_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4077_b5, by decide, c4077_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4077_b4, by decide, c4077_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4077_b1, by decide, c4077_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4077_b7, by decide, c4077_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4077_b6, by decide, c4077_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4077_b8, by decide, c4077_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4077_b2, by decide, c4077_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4077_b3, by decide, c4077_ok3⟩, ?_⟩
  simp

def s22 : List Nat := [6755399709622272, 2251800098963456, 6755400514863105, 6755399441186817, 5629568253820929, 2252074691723265, 2251800904269825, 1125968643162113, 5629499802779904, 1125900192121088, 5629500608020737, 5629499534344449, 4503668346978561, 1126174784880897, 1125900997427457, 68736319745, 4503600701178368, 4503599895937536, 274878038528, 285278720, 1090585088]
theorem e22 : enumKeys 218 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4078_b0, by decide, c4078_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4077_b9, by decide, c4077_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4078_b8, by decide, c4078_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4079_b1, by decide, c4079_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4079_b3, by decide, c4079_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4079_b2, by decide, c4079_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4079_b0, by decide, c4079_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4078_b9, by decide, c4078_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4078_b2, by decide, c4078_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4078_b1, by decide, c4078_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4079_b4, by decide, c4079_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4079_b7, by decide, c4079_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4079_b9, by decide, c4079_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4079_b8, by decide, c4079_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4079_b6, by decide, c4079_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4079_b5, by decide, c4079_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4078_b3, by decide, c4078_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4078_b7, by decide, c4078_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4078_b6, by decide, c4078_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4078_b5, by decide, c4078_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 291, c4078_b4, by decide, c4078_ok4⟩, ?_⟩
  simp

def s23 : List Nat := [19421773661601792, 1407375219163136, 19421774466842625, 19421773393166337, 18295942205800449, 1408474395312129, 1407376024469505, 281543763361793, 18295873754759424, 281475312320768, 18295874560000257, 18295873486323969, 282574488469761, 281476117627137, 1407375152123904, 1407375957364737, 1407374883688449, 281543696322561, 281476050522368, 281475245281536]
theorem e23 : enumKeys 218 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4080_b1, by decide, c4080_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4080_b0, by decide, c4080_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4080_b7, by decide, c4080_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4081_b0, by decide, c4081_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4081_b2, by decide, c4081_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4081_b1, by decide, c4081_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4080_b9, by decide, c4080_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c4080_b8, by decide, c4080_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4080_b4, by decide, c4080_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c4080_b3, by decide, c4080_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4081_b6, by decide, c4081_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4081_b8, by decide, c4081_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4081_b9, by decide, c4081_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4081_b7, by decide, c4081_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4080_b2, by decide, c4080_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4081_b3, by decide, c4081_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4081_b4, by decide, c4081_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4081_b5, by decide, c4081_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4080_b5, by decide, c4080_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4080_b6, by decide, c4080_ok6⟩, ?_⟩
  simp

def s24 : List Nat := [1688850129027072, 1688854155362305, 1688850934333441, 563018673225729, 1688850128830480, 1688850934071313, 1688849860395025, 563018673029137, 562950222184704, 562954248519937, 562951027491073, 562951027228944, 562950221988112]
theorem e24 : enumKeys 218 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4082_b0, by decide, c4082_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4082_b7, by decide, c4082_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4082_b6, by decide, c4082_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4082_b5, by decide, c4082_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4082_b2, by decide, c4082_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4083_b0, by decide, c4083_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4083_b1, by decide, c4083_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4083_b2, by decide, c4083_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4082_b1, by decide, c4082_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4082_b9, by decide, c4082_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4082_b8, by decide, c4082_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4082_b3, by decide, c4082_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4082_b4, by decide, c4082_ok4⟩, ?_⟩
  simp

def s25 : List Nat := [2533275058962432, 2533275864268801, 1407443603161089, 1407375152120064, 1407375957426433, 281543696318721, 281475245277696, 281476050584064]
theorem e25 : enumKeys 218 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4083_b3, by decide, c4083_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4083_b8, by decide, c4083_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4083_b7, by decide, c4083_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4083_b4, by decide, c4083_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4084_b0, by decide, c4084_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4083_b9, by decide, c4083_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4083_b6, by decide, c4083_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4083_b5, by decide, c4083_ok5⟩, ?_⟩
  simp

def s26 : List Nat := [27021598032658433, 22517998422065153, 18014398811471873, 9007199590285313, 4503599979692033, 27021597764222978, 22518273014759426, 9008298766368770, 22517998153629698, 18014673404166146, 4504699155775490, 18014398543036418, 1099545182210, 9007199321849858, 4503874572386306, 4503599711256578, 274961793026, 9007199523180545, 4503874505281537, 4503599912587265, 274894688257, 301993985]
theorem e26 : enumKeys 218 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4084_b1, by decide, c4084_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4084_b3, by decide, c4084_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4084_b5, by decide, c4084_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4084_b2, by decide, c4084_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4084_b4, by decide, c4084_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4085_b1, by decide, c4085_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4085_b3, by decide, c4085_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4085_b2, by decide, c4085_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4085_b6, by decide, c4085_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4085_b8, by decide, c4085_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4085_b7, by decide, c4085_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4086_b1, by decide, c4086_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4086_b2, by decide, c4086_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4085_b4, by decide, c4085_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4085_b5, by decide, c4085_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4085_b9, by decide, c4085_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4086_b0, by decide, c4086_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4084_b7, by decide, c4084_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4084_b6, by decide, c4084_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4084_b9, by decide, c4084_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4084_b8, by decide, c4084_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4085_b0, by decide, c4085_ok0⟩, ?_⟩
  simp

def s27 : List Nat := [9288674500149249, 4785074889555969, 9288678526418946, 9288674231713794, 4785349482250242, 4785078915825666, 4785074621120514, 281749871656962, 281479305232386, 9288674499887121, 4785349481988113, 4785074889293841, 281749871394833, 281475278700561]
theorem e27 : enumKeys 218 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4086_b3, by decide, c4086_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4086_b4, by decide, c4086_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4087_b0, by decide, c4087_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4087_b3, by decide, c4087_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4087_b4, by decide, c4087_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4087_b1, by decide, c4087_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4087_b5, by decide, c4087_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4087_b6, by decide, c4087_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4087_b2, by decide, c4087_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4086_b6, by decide, c4086_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4086_b5, by decide, c4086_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4086_b8, by decide, c4086_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4086_b7, by decide, c4086_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4086_b9, by decide, c4086_ok9⟩, ?_⟩
  simp

def s28 : List Nat := [10133099430084609, 5629499819491329, 1125900208832513, 10133100235325442, 10133099161649154, 9007267974283266, 5629774412185602, 5629500624732162, 5629499551055874, 4503668363689986, 1126174801592322, 1125901014138882, 68753031170, 9007200328483073, 9007199523242241, 4503874505343233, 4503600717889793, 4503599912648961, 274894749953, 301990145, 1107296513]
theorem e28 : enumKeys 218 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4087_b8, by decide, c4087_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4087_b9, by decide, c4087_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4087_b7, by decide, c4087_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4088_b8, by decide, c4088_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4089_b2, by decide, c4089_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4089_b4, by decide, c4089_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4089_b3, by decide, c4089_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4088_b9, by decide, c4088_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4089_b5, by decide, c4089_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4089_b7, by decide, c4089_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4089_b6, by decide, c4089_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4089_b1, by decide, c4089_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4089_b0, by decide, c4089_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4088_b0, by decide, c4088_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4088_b5, by decide, c4088_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4088_b4, by decide, c4088_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 275, c4088_b1, by decide, c4088_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4088_b7, by decide, c4088_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4088_b6, by decide, c4088_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4088_b3, by decide, c4088_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4088_b2, by decide, c4088_ok2⟩, ?_⟩
  simp

def s29 : List Nat := [22799473382064129, 18295873771470849, 4785074939691009, 281475329032193, 22799474187304962, 22799473113628674, 18296148364165122, 4786174115774466, 18295874576711682, 18295873503035394, 282574505181186, 4785075744931842, 4785074671255554, 281749921792002, 281476134338562, 4785075677827073, 4785074872586241, 281749854687233, 281476067233793, 281475261992961]
theorem e29 : enumKeys 218 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4089_b9, by decide, c4089_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4090_b1, by decide, c4090_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4090_b0, by decide, c4090_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4089_b8, by decide, c4089_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4090_b7, by decide, c4090_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4091_b1, by decide, c4091_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4091_b3, by decide, c4091_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4091_b2, by decide, c4091_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4090_b9, by decide, c4090_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4091_b6, by decide, c4091_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4091_b7, by decide, c4091_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4090_b8, by decide, c4090_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4091_b4, by decide, c4091_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4091_b5, by decide, c4091_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4091_b0, by decide, c4091_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4090_b2, by decide, c4090_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4090_b5, by decide, c4090_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4090_b4, by decide, c4090_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4090_b3, by decide, c4090_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4090_b6, by decide, c4090_ok6⟩, ?_⟩
  simp

def s30 : List Nat := [5066549849554945, 562950238896129, 5066553875824642, 5066550654795778, 5066549581119490, 563224831655938, 562954265231362, 562951044202498, 5066550654533649, 5066549849292817, 563224831393809, 562951043940369, 562950238699537]
theorem e30 : enumKeys 218 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4091_b9, by decide, c4091_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4091_b8, by decide, c4091_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4092_b7, by decide, c4092_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4092_b5, by decide, c4092_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4092_b9, by decide, c4092_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4093_b0, by decide, c4093_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4092_b8, by decide, c4092_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4092_b6, by decide, c4092_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4092_b0, by decide, c4092_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4092_b3, by decide, c4092_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4092_b2, by decide, c4092_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4092_b1, by decide, c4092_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4092_b4, by decide, c4092_ok4⟩, ?_⟩
  simp

def s31 : List Nat := [5910974779490305, 1407375168831489, 5910975584731138, 5910974511054850, 4785143323688962, 1407649761591298, 1407375974137858, 281543713030146, 4785075677888769, 4785074872647937, 281749854748929, 281475261989121, 281476067295489]
theorem e31 : enumKeys 218 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4093_b2, by decide, c4093_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4093_b1, by decide, c4093_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4093_b8, by decide, c4093_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4094_b1, by decide, c4094_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4094_b3, by decide, c4094_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4094_b2, by decide, c4094_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4094_b0, by decide, c4094_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4093_b9, by decide, c4093_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4093_b3, by decide, c4093_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4093_b7, by decide, c4093_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4093_b6, by decide, c4093_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4093_b5, by decide, c4093_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4093_b4, by decide, c4093_ok4⟩, ?_⟩
  simp

def s32 : List Nat := [18577348731469825, 562950289031169, 18577349536710658, 18577348463034370, 564049465180162, 562951094337538, 562951027232769, 562950221991937]
theorem e32 : enumKeys 218 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4094_b5, by decide, c4094_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4094_b4, by decide, c4094_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4094_b8, by decide, c4094_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4095_b0, by decide, c4095_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4095_b1, by decide, c4095_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4094_b9, by decide, c4094_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4094_b6, by decide, c4094_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4094_b7, by decide, c4094_ok7⟩, ?_⟩
  simp

def s33 : List Nat := [844425198895105, 844429225230338, 844426004201474, 844426003939345, 844425198698513]
theorem e33 : enumKeys 218 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4095_b2, by decide, c4095_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4095_b6, by decide, c4095_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4095_b5, by decide, c4095_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4095_b3, by decide, c4095_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4095_b4, by decide, c4095_ok4⟩, ?_⟩
  simp

def s34 : List Nat := [1688850128830465, 1688850934136834, 563018673029122, 562950221988097, 562951027294465]
theorem e34 : enumKeys 218 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4095_b7, by decide, c4095_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4096_b1, by decide, c4096_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4096_b0, by decide, c4096_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4095_b9, by decide, c4095_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4095_b8, by decide, c4095_ok8⟩, ?_⟩
  simp

def s35 : List Nat := [13510799150546946, 9007474132647938, 9007199539953666, 4503874522054658, 4503599929360386, 274911461378]
theorem e35 : enumKeys 218 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4096_b3, by decide, c4096_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4096_b2, by decide, c4096_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4096_b5, by decide, c4096_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4096_b4, by decide, c4096_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4096_b7, by decide, c4096_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4096_b6, by decide, c4096_ok6⟩, ?_⟩
  simp

def s36 : List Nat := [9288675305193474, 9288674499952642, 4785349482053634, 4785075694600194, 4785074889359362, 281749871460354, 281475278700546, 281476084006914]
theorem e36 : enumKeys 218 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4096_b8, by decide, c4096_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4097_b3, by decide, c4097_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4097_b2, by decide, c4097_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4096_b9, by decide, c4096_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4097_b5, by decide, c4097_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4097_b4, by decide, c4097_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4097_b1, by decide, c4097_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4097_b0, by decide, c4097_ok0⟩, ?_⟩
  simp

def s37 : List Nat := [5066550654599170, 5066549849358338, 563224831459330, 562950238699522, 562951044005890]
theorem e37 : enumKeys 218 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4097_b6, by decide, c4097_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4098_b0, by decide, c4098_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4097_b9, by decide, c4097_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4097_b8, by decide, c4097_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4097_b7, by decide, c4097_ok7⟩, ?_⟩
  simp

def s38 : List Nat := [844425198698498, 844426004004866]
theorem e38 : enumKeys 218 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4098_b2, by decide, c4098_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4098_b1, by decide, c4098_ok1⟩, ?_⟩
  simp

/-- every enumerated key with left type `218` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 218 mR,
    (218 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 218 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K33
end Grid3.Three.Cert
