import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4098
import Grid3.Three.Cert.Data.C4099
import Grid3.Three.Cert.Data.C4100
import Grid3.Three.Cert.Data.C4101
import Grid3.Three.Cert.Data.C4102
import Grid3.Three.Cert.Data.C4103
import Grid3.Three.Cert.Data.C4104
import Grid3.Three.Cert.Data.C4105
import Grid3.Three.Cert.Data.C4106
import Grid3.Three.Cert.Data.C4107
import Grid3.Three.Cert.Data.C4108
import Grid3.Three.Cert.Data.C4109
import Grid3.Three.Cert.Data.C4110
import Grid3.Three.Cert.Data.C4111
import Grid3.Three.Cert.Data.C4112
import Grid3.Three.Cert.Data.C4113
import Grid3.Three.Cert.Data.C4114
import Grid3.Three.Cert.Data.C4115
import Grid3.Three.Cert.Data.C4116
import Grid3.Three.Cert.Data.C4117
import Grid3.Three.Cert.Data.C4118
import Grid3.Three.Cert.Data.C4119
import Grid3.Three.Cert.Data.C4120
import Grid3.Three.Cert.Data.C4121
import Grid3.Three.Cert.Data.C4122
import Grid3.Three.Cert.Data.C4123
import Grid3.Three.Cert.Data.C4124
import Grid3.Three.Cert.Data.C4125
import Grid3.Three.Cert.Data.C4126
import Grid3.Three.Cert.Data.C4127
import Grid3.Three.Cert.Data.C4128
import Grid3.Three.Cert.Data.C4129
import Grid3.Three.Cert.Data.C4130
import Grid3.Three.Cert.Data.C4131
import Grid3.Three.Cert.Data.C4132
import Grid3.Three.Cert.Data.C4133
import Grid3.Three.Cert.Data.C4134
import Grid3.Three.Cert.Data.C4135
import Grid3.Three.Cert.Data.C4136
import Grid3.Three.Cert.Data.C4137
import Grid3.Three.Cert.Data.C4138
import Grid3.Three.Cert.Data.C4139
import Grid3.Three.Cert.Data.C4140
import Grid3.Three.Cert.Data.C4141
import Grid3.Three.Cert.Data.C4142
import Grid3.Three.Cert.Data.C4143
import Grid3.Three.Cert.Data.C4144
import Grid3.Three.Cert.Data.C4145
import Grid3.Three.Cert.Data.C4146
import Grid3.Three.Cert.Data.C4147
import Grid3.Three.Cert.Data.C4148
import Grid3.Three.Cert.Data.C4149
import Grid3.Three.Cert.Data.C4150
import Grid3.Three.Cert.Data.C4151
import Grid3.Three.Cert.Data.C4152
import Grid3.Three.Cert.Data.C4153
import Grid3.Three.Cert.Data.C4154
import Grid3.Three.Cert.Data.C4155
import Grid3.Three.Cert.Data.C4156
import Grid3.Three.Cert.Data.C4157
import Grid3.Three.Cert.Data.C4158
import Grid3.Three.Cert.Data.C4159
import Grid3.Three.Cert.Data.C4160
import Grid3.Three.Cert.Data.C4161
import Grid3.Three.Cert.Data.C4162
import Grid3.Three.Cert.Data.C4163
import Grid3.Three.Cert.Data.C4164
import Grid3.Three.Cert.Data.C4165
import Grid3.Three.Cert.Data.C4166
import Grid3.Three.Cert.Data.C4167
import Grid3.Three.Cert.Data.C4168
import Grid3.Three.Cert.Data.C4169
import Grid3.Three.Cert.Data.C4170
import Grid3.Three.Cert.Data.C4171
import Grid3.Three.Cert.Data.C4172
import Grid3.Three.Cert.Data.C4173
import Grid3.Three.Cert.Data.C4174

/-! Seam keys with left type `398` (type index 34): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K34

def s00 : List Nat := [295183933976371789824, 295165919577929416704, 36028797086072832, 295147905179487043584, 18014398643699712, 201326592, 295165919577862311936, 36028797018968064, 295147905179419938816, 18014398576594944, 134221824, 295147905179352834048, 18014398509490176, 67117056]
theorem e00 : enumKeys 398 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4098_b3, by decide, c4098_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c4098_b4, by decide, c4098_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4098_b5, by decide, c4098_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 208, c4098_b6, by decide, c4098_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4098_b7, by decide, c4098_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c4098_b8, by decide, c4098_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 195, c4098_b9, by decide, c4098_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c4099_b0, by decide, c4099_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 205, c4099_b1, by decide, c4099_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c4099_b2, by decide, c4099_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4099_b3, by decide, c4099_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4099_b4, by decide, c4099_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c4099_b5, by decide, c4099_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4099_b6, by decide, c4099_ok6⟩, ?_⟩
  simp

def s01 : List Nat := [295153534678887301120, 73806116593254793216, 18469262071846666240, 1172061803039948800, 295149031079276707840, 18464758472236072960, 19140298433363968, 1158551004208168960, 73788102194812420096, 18451247673404293120, 5629499601584128, 1154047404597575680, 18446744073793699840, 1125899990990848, 295153534678887038992, 73806116593254531088, 18469262071846404112, 295149031079276445712, 18464758472235810832, 19140298433101840, 73788102194812157968, 18451247673404030992, 5629499601322000, 18446744073793437712, 1125899990728720, 1175439502743699712, 295152408778980458752, 73804990693347950848, 22517998137114880, 1170935903133106432, 295147905179369865472, 18014398526521600, 1157425104301326592, 73786976294905577728, 4503599694741760, 1152921504690733312, 84148480, 295152408778980196624, 73804990693347688720, 22517998136852752, 295147905179369603344, 18014398526259472, 73786976294905315600, 4503599694479632, 83886352, 1158551004141064192, 73788102194745315328, 18451247673337188352, 5629499534479360, 1154047404530470912, 18446744073726595072, 1125899923886080, 73788102194745053200, 18451247673336926224, 5629499534217232, 18446744073726332944, 1125899923623952, 1157425104234221824, 73786976294838472960, 4503599627636992, 1152921504623628544, 17043712]
theorem e01 : enumKeys 398 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4100_b2, by decide, c4100_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4100_b1, by decide, c4100_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4100_b0, by decide, c4100_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4099_b8, by decide, c4099_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4100_b7, by decide, c4100_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4100_b6, by decide, c4100_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4100_b8, by decide, c4100_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4099_b7, by decide, c4099_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4100_b4, by decide, c4100_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4100_b3, by decide, c4100_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4100_b5, by decide, c4100_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4099_b9, by decide, c4099_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4100_b9, by decide, c4100_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4101_b0, by decide, c4101_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4103_b7, by decide, c4103_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4103_b6, by decide, c4103_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4103_b5, by decide, c4103_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4104_b2, by decide, c4104_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4104_b1, by decide, c4104_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4104_b3, by decide, c4104_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4103_b9, by decide, c4103_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4103_b8, by decide, c4103_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4104_b0, by decide, c4104_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4104_b4, by decide, c4104_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4104_b5, by decide, c4104_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4101_b8, by decide, c4101_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4102_b3, by decide, c4102_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4102_b2, by decide, c4102_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4102_b4, by decide, c4102_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4102_b0, by decide, c4102_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4102_b7, by decide, c4102_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4102_b8, by decide, c4102_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4101_b9, by decide, c4101_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4102_b5, by decide, c4102_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4102_b6, by decide, c4102_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4102_b1, by decide, c4102_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4102_b9, by decide, c4102_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4105_b2, by decide, c4105_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4105_b1, by decide, c4105_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4105_b3, by decide, c4105_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4105_b6, by decide, c4105_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4105_b7, by decide, c4105_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4105_b4, by decide, c4105_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4105_b5, by decide, c4105_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4105_b8, by decide, c4105_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4101_b1, by decide, c4101_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4101_b4, by decide, c4101_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4101_b3, by decide, c4101_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4101_b5, by decide, c4101_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4101_b2, by decide, c4101_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4101_b6, by decide, c4101_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4101_b7, by decide, c4101_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4104_b7, by decide, c4104_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4104_b6, by decide, c4104_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4104_b8, by decide, c4104_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4104_b9, by decide, c4104_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4105_b0, by decide, c4105_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4103_b0, by decide, c4103_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4103_b2, by decide, c4103_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4103_b3, by decide, c4103_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4103_b1, by decide, c4103_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4103_b4, by decide, c4103_ok4⟩, ?_⟩
  simp

def s02 : List Nat := [1188950301625810944, 295166201052839280640, 4647714815446614016, 1171217378160148480, 295148186654396907520, 4629700417004240896, 18295873553563648, 1153202979717775360, 4611686018561867776, 281475111190528, 295166201052839018512, 4647714815446351888, 295148186654396645392, 4629700417003978768, 18295873553301520, 4611686018561605648, 281475110928400, 1171217378093043712, 295148186654329802752, 4629700416937136128, 18295873486458880, 1153202979650670592, 4611686018494763008, 281475044085760, 295148186654329540624, 4629700416936874000, 18295873486196752, 4611686018494500880, 281475043823632, 1153202979583565824, 4611686018427658240, 281474976980992]
theorem e02 : enumKeys 398 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4105_b9, by decide, c4105_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4106_b3, by decide, c4106_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4106_b2, by decide, c4106_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4106_b0, by decide, c4106_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4106_b5, by decide, c4106_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4106_b4, by decide, c4106_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4106_b6, by decide, c4106_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4106_b1, by decide, c4106_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4106_b7, by decide, c4106_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4106_b8, by decide, c4106_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4108_b0, by decide, c4108_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4107_b9, by decide, c4107_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4108_b2, by decide, c4108_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4108_b1, by decide, c4108_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4108_b3, by decide, c4108_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4108_b4, by decide, c4108_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4108_b5, by decide, c4108_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4106_b9, by decide, c4106_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4107_b2, by decide, c4107_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4107_b1, by decide, c4107_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4107_b3, by decide, c4107_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4107_b0, by decide, c4107_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4107_b4, by decide, c4107_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4107_b5, by decide, c4107_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4108_b7, by decide, c4108_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4108_b6, by decide, c4108_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4108_b8, by decide, c4108_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4108_b9, by decide, c4108_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4109_b0, by decide, c4109_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4107_b6, by decide, c4107_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4107_b7, by decide, c4107_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4107_b8, by decide, c4107_ok8⟩, ?_⟩
  simp

def s03 : List Nat := [1158551004141322240, 73788383669722284032, 18451529148314157056, 4617315517962125312, 1154328879507439616, 18447025548703563776, 4612811918351532032, 1407374900854784, 1158551004141060112, 73788383669722021904, 18451529148313894928, 4617315517961863184, 1154328879507177488, 18447025548703301648, 4612811918351269904, 1407374900592656, 73788383669721759776, 18451529148313632800, 4617315517961601056, 18447025548703039520, 4612811918351007776, 1407374900330528, 1157706579211190528, 73787257769815441664, 4616189618055282944, 4785074604605696, 1153202979600597248, 4611686018444689664, 281474994012416, 1157706579210928400, 73787257769815179536, 4616189618055020816, 4785074604343568, 1153202979600335120, 4611686018444427536, 281474993750288]
theorem e03 : enumKeys 398 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c4109_b1, by decide, c4109_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4109_b5, by decide, c4109_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4109_b4, by decide, c4109_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4109_b3, by decide, c4109_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4109_b2, by decide, c4109_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4109_b7, by decide, c4109_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4109_b6, by decide, c4109_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4109_b8, by decide, c4109_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c4110_b6, by decide, c4110_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4111_b0, by decide, c4111_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4110_b9, by decide, c4110_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4110_b8, by decide, c4110_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4110_b7, by decide, c4110_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4111_b2, by decide, c4111_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4111_b1, by decide, c4111_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4111_b3, by decide, c4111_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4112_b3, by decide, c4112_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4112_b2, by decide, c4112_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4112_b1, by decide, c4112_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4112_b5, by decide, c4112_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4112_b4, by decide, c4112_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4112_b6, by decide, c4112_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4109_b9, by decide, c4109_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4110_b2, by decide, c4110_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4110_b1, by decide, c4110_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4110_b3, by decide, c4110_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4110_b0, by decide, c4110_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4110_b4, by decide, c4110_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4110_b5, by decide, c4110_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4111_b4, by decide, c4111_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4111_b7, by decide, c4111_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4111_b6, by decide, c4111_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4111_b8, by decide, c4111_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4111_b5, by decide, c4111_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4111_b9, by decide, c4111_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4112_b0, by decide, c4112_ok0⟩, ?_⟩
  simp

def s04 : List Nat := [1171217378093301760, 295148468129306771456, 4629981891914104832, 1153484454627639296, 4611967493471731712, 562950021054464, 1171217378093039632, 295148468129306509328, 4629981891913842704, 1153484454627377168, 4611967493471469584, 562950020792336, 295148468129306247200, 4629981891913580576, 4611967493471207456, 562950020530208, 1153484454560534528, 4611967493404626944, 562949953949696, 1153484454560272400, 4611967493404364816, 562949953687568]
theorem e04 : enumKeys 398 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4112_b7, by decide, c4112_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4113_b0, by decide, c4113_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4112_b9, by decide, c4112_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4112_b8, by decide, c4112_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4113_b1, by decide, c4113_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4113_b2, by decide, c4113_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4113_b6, by decide, c4113_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4113_b9, by decide, c4113_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4113_b8, by decide, c4113_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4113_b7, by decide, c4113_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4114_b0, by decide, c4114_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4114_b1, by decide, c4114_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4114_b6, by decide, c4114_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4114_b5, by decide, c4114_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4114_b7, by decide, c4114_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4114_b8, by decide, c4114_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4113_b3, by decide, c4113_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4113_b4, by decide, c4113_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4113_b5, by decide, c4113_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4114_b2, by decide, c4114_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4114_b3, by decide, c4114_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4114_b4, by decide, c4114_ok4⟩, ?_⟩
  simp

def s05 : List Nat := [1153484454560792576, 4612248968381595648, 1153484454560530448, 4612248968381333520, 1153484454560268320, 4612248968381071392]
theorem e05 : enumKeys 398 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4114_b9, by decide, c4114_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4115_b0, by decide, c4115_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4115_b1, by decide, c4115_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4115_b2, by decide, c4115_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4115_b3, by decide, c4115_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4115_b4, by decide, c4115_ok4⟩, ?_⟩
  simp

def s06 : List Nat := [295167045477769216000, 18482772870728581120, 295149031079326842880, 18464758472286208000, 19140298483499008, 18446744073843834880, 1125900041125888, 295165919577862373632, 36028797019029760, 295147905179420000512, 18014398576656640, 134283520, 295149031079259738112, 18464758472219103232, 19140298416394240, 18446744073776730112, 1125899974021120, 295147905179352895744, 18014398509551872, 67178752, 18446744073709625344, 1125899906916352]
theorem e06 : enumKeys 398 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4115_b6, by decide, c4115_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4115_b5, by decide, c4115_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4115_b8, by decide, c4115_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4115_b7, by decide, c4115_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4115_b9, by decide, c4115_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4116_b0, by decide, c4116_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4116_b1, by decide, c4116_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4116_b9, by decide, c4116_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4117_b0, by decide, c4117_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4117_b1, by decide, c4117_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4117_b2, by decide, c4117_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4117_b3, by decide, c4117_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4116_b3, by decide, c4116_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4116_b2, by decide, c4116_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4116_b4, by decide, c4116_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4116_b5, by decide, c4116_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4116_b6, by decide, c4116_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4117_b4, by decide, c4117_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4117_b5, by decide, c4117_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4117_b6, by decide, c4117_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4116_b7, by decide, c4116_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4116_b8, by decide, c4116_ok8⟩, ?_⟩
  simp

def s07 : List Nat := [73789228094652219392, 18452373573244092416, 1155173304437374976, 18447869973633499136, 2251799830790144, 73789228094651957264, 18452373573243830288, 18447869973633237008, 2251799830528016, 1158551004141125888, 73788102194745377024, 18451247673337250048, 5629499534541056, 1154047404530532608, 18446744073726656768, 1125899923947776, 73788102194745114896, 18451247673336987920, 5629499534278928, 18446744073726394640, 1125899923685648, 1157425104234283520, 73786976294838534656, 4503599627698688, 1152921504623690240, 17105408]
theorem e07 : enumKeys 398 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4117_b9, by decide, c4117_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4117_b8, by decide, c4117_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4117_b7, by decide, c4117_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4118_b0, by decide, c4118_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4118_b1, by decide, c4118_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4119_b5, by decide, c4119_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4119_b4, by decide, c4119_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4119_b6, by decide, c4119_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4119_b7, by decide, c4119_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4118_b2, by decide, c4118_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4118_b5, by decide, c4118_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4118_b4, by decide, c4118_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4118_b6, by decide, c4118_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4118_b3, by decide, c4118_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4118_b7, by decide, c4118_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4118_b8, by decide, c4118_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4119_b9, by decide, c4119_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4119_b8, by decide, c4119_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4120_b0, by decide, c4120_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4120_b1, by decide, c4120_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4120_b2, by decide, c4120_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4118_b9, by decide, c4118_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4119_b1, by decide, c4119_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4119_b2, by decide, c4119_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4119_b0, by decide, c4119_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4119_b3, by decide, c4119_ok3⟩, ?_⟩
  simp

def s08 : List Nat := [1172061803023237120, 295149312554236706816, 18465039947196071936, 4630826316844040192, 1154328879557574656, 18447025548753698816, 4612811918401667072, 1407374950989824, 295149312554236444688, 18465039947195809808, 4630826316843778064, 18447025548753436688, 4612811918401404944, 1407374950727696, 1171217378093105408, 295148186654329864448, 4629700416937197824, 18295873486520576, 1153202979650732288, 4611686018494824704, 281475044147456, 295148186654329602320, 4629700416936935696, 18295873486258448, 4611686018494562576, 281475043885328, 1154328879490469888, 18447025548686594048, 4612811918334562304, 1407374883885056, 18447025548686331920, 4612811918334300176, 1407374883622928, 1153202979583627520, 4611686018427719936, 281474977042688]
theorem e08 : enumKeys 398 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 313, c4120_b3, by decide, c4120_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4120_b7, by decide, c4120_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4120_b6, by decide, c4120_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4120_b5, by decide, c4120_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4120_b4, by decide, c4120_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4120_b9, by decide, c4120_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4120_b8, by decide, c4120_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4121_b0, by decide, c4121_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4122_b7, by decide, c4122_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4122_b6, by decide, c4122_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4122_b5, by decide, c4122_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4122_b9, by decide, c4122_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4122_b8, by decide, c4122_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4123_b0, by decide, c4123_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4121_b5, by decide, c4121_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4121_b8, by decide, c4121_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4121_b7, by decide, c4121_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4121_b9, by decide, c4121_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4121_b6, by decide, c4121_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4122_b0, by decide, c4122_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4122_b1, by decide, c4122_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4123_b5, by decide, c4123_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4123_b4, by decide, c4123_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4123_b6, by decide, c4123_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4123_b7, by decide, c4123_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4123_b8, by decide, c4123_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4121_b1, by decide, c4121_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4121_b3, by decide, c4121_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4121_b2, by decide, c4121_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4121_b4, by decide, c4121_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4123_b2, by decide, c4123_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4123_b1, by decide, c4123_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4123_b3, by decide, c4123_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4122_b2, by decide, c4122_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4122_b3, by decide, c4122_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4122_b4, by decide, c4122_ok4⟩, ?_⟩
  simp

def s09 : List Nat := [1154328879490727936, 18447307023663562752, 4613093393311531008, 1154328879490465808, 18447307023663300624, 4613093393311268880, 18447307023663038496, 4613093393311006752, 1153484454560596224, 4611967493404688640, 562949954011392, 1153484454560334096, 4611967493404426512, 562949953749264]
theorem e09 : enumKeys 398 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4123_b9, by decide, c4123_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4124_b1, by decide, c4124_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4124_b0, by decide, c4124_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4124_b5, by decide, c4124_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4124_b7, by decide, c4124_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4124_b6, by decide, c4124_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4125_b2, by decide, c4125_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4125_b1, by decide, c4125_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4124_b2, by decide, c4124_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4124_b3, by decide, c4124_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4124_b4, by decide, c4124_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4124_b8, by decide, c4124_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4124_b9, by decide, c4124_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4125_b0, by decide, c4125_ok0⟩, ?_⟩
  simp

def s10 : List Nat := [295150156979166642176, 18465884372126007296, 18447869973683634176, 2251799880925184, 295149031079259799808, 18464758472219164928, 19140298416455936, 18446744073776791808, 1125899974082816, 295147905179352957440, 18014398509613568, 67240448, 18447869973616529408, 2251799813820416, 18446744073709687040, 1125899906978048]
theorem e10 : enumKeys 398 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4125_b4, by decide, c4125_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4125_b3, by decide, c4125_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4125_b5, by decide, c4125_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4125_b6, by decide, c4125_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4126_b0, by decide, c4126_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4125_b9, by decide, c4125_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4126_b1, by decide, c4126_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4126_b2, by decide, c4126_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4126_b3, by decide, c4126_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4126_b6, by decide, c4126_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4126_b7, by decide, c4126_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4126_b8, by decide, c4126_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4125_b7, by decide, c4125_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4125_b8, by decide, c4125_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4126_b4, by decide, c4126_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4126_b5, by decide, c4126_ok5⟩, ?_⟩
  simp

def s11 : List Nat := [1155173304420663296, 18448151448593498112, 4613937818241466368, 18448151448593235984, 4613937818241204240, 1154328879490531584, 18447025548686655744, 4612811918334624000, 1407374883946752, 18447025548686393616, 4612811918334361872, 1407374883684624, 1153202979583689216, 4611686018427781632, 281474977104384]
theorem e11 : enumKeys 398 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c4126_b9, by decide, c4126_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4127_b1, by decide, c4127_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4127_b0, by decide, c4127_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4128_b0, by decide, c4128_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4127_b9, by decide, c4127_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4127_b2, by decide, c4127_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4127_b4, by decide, c4127_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4127_b3, by decide, c4127_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4127_b5, by decide, c4127_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4128_b2, by decide, c4128_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4128_b1, by decide, c4128_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4128_b3, by decide, c4128_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4127_b6, by decide, c4127_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4127_b7, by decide, c4127_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4127_b8, by decide, c4127_ok8⟩, ?_⟩
  simp

def s12 : List Nat := [18448995873523433472, 18447869973616591104, 2251799813882112, 18446744073709748736, 1125899907039744]
theorem e12 : enumKeys 398 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4128_b4, by decide, c4128_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4128_b5, by decide, c4128_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4128_b6, by decide, c4128_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4128_b7, by decide, c4128_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4128_b8, by decide, c4128_ok8⟩, ?_⟩
  simp

def s13 : List Nat := [108086391073669120, 94575592241889280, 90071992631296000, 76561193799516160, 72057594188922880, 295170423177489678337, 73823005091857170433, 295165919577879085057, 36028797035741185, 295152408779047305217, 73804990693414797313, 22517998203961345, 295147905179436711937, 18014398593368065, 73786976294972424193, 4503599761588225, 150994945, 94575592174784512, 90071992564191232, 76561193732411392, 72057594121818112, 295152408778980200449, 73804990693347692545, 22517998136856577, 295147905179369607169, 18014398526263297, 73786976294905319425, 4503599694483457, 83890177, 73786976294838214656, 76561193665306624, 72057594054713344]
theorem e13 : enumKeys 398 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4129_b1, by decide, c4129_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4128_b9, by decide, c4128_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4129_b2, by decide, c4129_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4129_b0, by decide, c4129_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4129_b3, by decide, c4129_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4130_b2, by decide, c4130_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4130_b1, by decide, c4130_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4130_b8, by decide, c4130_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4130_b9, by decide, c4130_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4130_b4, by decide, c4130_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4130_b3, by decide, c4130_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4130_b5, by decide, c4130_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4131_b0, by decide, c4131_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4131_b1, by decide, c4131_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4130_b6, by decide, c4130_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4130_b7, by decide, c4130_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4131_b2, by decide, c4131_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4129_b4, by decide, c4129_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4129_b6, by decide, c4129_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4129_b5, by decide, c4129_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4129_b7, by decide, c4129_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4131_b4, by decide, c4131_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4131_b3, by decide, c4131_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4131_b5, by decide, c4131_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4131_b8, by decide, c4131_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4131_b9, by decide, c4131_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4131_b6, by decide, c4131_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4131_b7, by decide, c4131_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4132_b0, by decide, c4132_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4129_b8, by decide, c4129_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4129_b9, by decide, c4129_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4130_b0, by decide, c4130_ok0⟩, ?_⟩
  simp

def s14 : List Nat := [77687093589180416, 73183493978587136, 73792605794372681729, 18455751272964554753, 1158551004157837313, 73788102194762088449, 18451247673353961473, 5629499551252481, 1154047404547244033, 18446744073743368193, 1125899940659201, 77687093588918288, 73183493978325008, 73792605794372419601, 18455751272964292625, 73788102194761826321, 18451247673353699345, 5629499550990353, 18446744073743106065, 1125899940397073, 81064793292931328, 76561193682338048, 72057594071744768, 1161928703861588225, 73791479894465839361, 9007199255003393, 1157425104250994945, 73786976294855246081, 4503599644410113, 1152921504640401665, 33816833, 73791479894465577232, 81064793292669200, 73786976294854983952, 76561193682075920, 72057594071482640]
theorem e14 : enumKeys 398 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4132_b1, by decide, c4132_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4132_b2, by decide, c4132_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4133_b6, by decide, c4133_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4133_b5, by decide, c4133_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4133_b3, by decide, c4133_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4133_b8, by decide, c4133_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4133_b7, by decide, c4133_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4133_b9, by decide, c4133_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4133_b4, by decide, c4133_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4134_b0, by decide, c4134_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4134_b1, by decide, c4134_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4132_b6, by decide, c4132_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4132_b7, by decide, c4132_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4135_b1, by decide, c4135_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4135_b0, by decide, c4135_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4135_b3, by decide, c4135_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4135_b2, by decide, c4135_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4135_b4, by decide, c4135_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4135_b5, by decide, c4135_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4135_b6, by decide, c4135_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4132_b3, by decide, c4132_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4132_b4, by decide, c4132_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4132_b5, by decide, c4132_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4134_b2, by decide, c4134_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4134_b5, by decide, c4134_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4134_b6, by decide, c4134_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4134_b3, by decide, c4134_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4134_b7, by decide, c4134_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4134_b8, by decide, c4134_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4134_b4, by decide, c4134_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4134_b9, by decide, c4134_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c4132_b8, by decide, c4132_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4132_b9, by decide, c4132_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 316, c4133_b0, by decide, c4133_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4133_b1, by decide, c4133_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4133_b2, by decide, c4133_ok2⟩, ?_⟩
  simp

def s15 : List Nat := [94575592175042560, 90353467541159936, 76842668709380096, 72339069098786816, 1175439502743699457, 295152690253957169153, 73805272168324661249, 4634204016564502529, 1171217378109816833, 295148186654346575873, 4629700416953909249, 18295873503232001, 1157706579278036993, 73787257769882288129, 4616189618122129409, 4785074671452161, 1153202979667443713, 4611686018511536129, 281475060858881, 94575592174780432, 90353467540897808, 76842668709117968, 72339069098524688, 295152690253956907025, 73805272168324399121, 4634204016564240401, 295148186654346313745, 4629700416953647121, 18295873502969873, 73787257769882026001, 4616189618121867281, 4785074671190033, 4611686018511274001, 281475060596753, 76842668642275328, 72339069031682048, 1157706579210932225, 73787257769815183361, 4616189618055024641, 4785074604347393, 1153202979600338945, 4611686018444431361, 281474993754113, 73787257769814921232, 4616189618054762512, 76842668642013200, 4611686018444169232, 72339069031419920]
theorem e15 : enumKeys 398 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4135_b7, by decide, c4135_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4135_b9, by decide, c4135_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4135_b8, by decide, c4135_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4136_b0, by decide, c4136_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4137_b2, by decide, c4137_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4137_b8, by decide, c4137_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4137_b7, by decide, c4137_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4137_b6, by decide, c4137_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4137_b4, by decide, c4137_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4138_b3, by decide, c4138_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4138_b2, by decide, c4138_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4138_b4, by decide, c4138_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4137_b3, by decide, c4137_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4138_b0, by decide, c4138_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4137_b9, by decide, c4137_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4138_b1, by decide, c4138_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4137_b5, by decide, c4137_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4138_b5, by decide, c4138_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4138_b6, by decide, c4138_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4136_b3, by decide, c4136_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4136_b5, by decide, c4136_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4136_b4, by decide, c4136_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4136_b6, by decide, c4136_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4139_b6, by decide, c4139_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4139_b5, by decide, c4139_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4139_b4, by decide, c4139_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4140_b1, by decide, c4140_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4140_b0, by decide, c4140_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4140_b2, by decide, c4140_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4139_b8, by decide, c4139_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4139_b7, by decide, c4139_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4139_b9, by decide, c4139_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4140_b3, by decide, c4140_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4140_b4, by decide, c4140_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4136_b1, by decide, c4136_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4136_b2, by decide, c4136_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4138_b7, by decide, c4138_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4139_b0, by decide, c4139_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4138_b9, by decide, c4138_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4139_b1, by decide, c4139_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4138_b8, by decide, c4138_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4139_b2, by decide, c4139_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4139_b3, by decide, c4139_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4136_b8, by decide, c4136_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4136_b7, by decide, c4136_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4136_b9, by decide, c4136_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4137_b0, by decide, c4137_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4137_b1, by decide, c4137_ok1⟩, ?_⟩
  simp

def s16 : List Nat := [76842668642533376, 72620544008650752, 1157706579211190273, 73787539244792152065, 4616471093031993345, 1153484454577307649, 4611967493421400065, 562949970722817, 76842668642271248, 72620544008388624, 1157706579210928145, 73787539244791889937, 4616471093031731217, 1153484454577045521, 4611967493421137937, 562949970460689, 73787539244791627808, 76842668642009120, 4616471093031469088, 4611967493420875808, 72620544008126496]
theorem e16 : enumKeys 398 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4140_b5, by decide, c4140_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4140_b6, by decide, c4140_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4141_b4, by decide, c4141_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4141_b7, by decide, c4141_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4141_b6, by decide, c4141_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4141_b5, by decide, c4141_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4141_b8, by decide, c4141_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4141_b9, by decide, c4141_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4140_b7, by decide, c4140_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4140_b8, by decide, c4140_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4142_b0, by decide, c4142_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4142_b3, by decide, c4142_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4142_b2, by decide, c4142_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4142_b1, by decide, c4142_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4142_b4, by decide, c4142_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4142_b5, by decide, c4142_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4141_b1, by decide, c4141_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4141_b0, by decide, c4141_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4140_b9, by decide, c4140_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4141_b2, by decide, c4141_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4141_b3, by decide, c4141_ok3⟩, ?_⟩
  simp

def s17 : List Nat := [91197892471095296, 77687093639315456, 73183494028722176, 295153534678887104513, 73806116593254596609, 18469262071846469633, 295149031079276511233, 18464758472235876353, 19140298433167361, 73788102194812223489, 18451247673404096513, 5629499601387521, 18446744073793503233, 1125899990794241, 94575592174846208, 90071992564252928, 76561193732473088, 72057594121879808, 295152408778980262145, 73804990693347754241, 22517998136918273, 295147905179369668865, 18014398526324993, 73786976294905381121, 4503599694545153, 83951873, 77687093572210688, 73183493961617408, 73788102194745118721, 18451247673336991745, 5629499534282753, 18446744073726398465, 1125899923689473, 73786976294838276352, 76561193665368320, 72057594054775040]
theorem e17 : enumKeys 398 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4142_b7, by decide, c4142_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4142_b6, by decide, c4142_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4142_b8, by decide, c4142_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4144_b0, by decide, c4144_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4143_b9, by decide, c4143_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4143_b8, by decide, c4143_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4144_b5, by decide, c4144_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4144_b4, by decide, c4144_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4144_b6, by decide, c4144_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4144_b2, by decide, c4144_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4144_b1, by decide, c4144_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4144_b3, by decide, c4144_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4144_b7, by decide, c4144_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4144_b8, by decide, c4144_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4143_b1, by decide, c4143_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4143_b3, by decide, c4143_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4143_b2, by decide, c4143_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4143_b4, by decide, c4143_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4145_b5, by decide, c4145_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4145_b4, by decide, c4145_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4145_b6, by decide, c4145_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4145_b9, by decide, c4145_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4146_b0, by decide, c4146_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4145_b7, by decide, c4145_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4145_b8, by decide, c4145_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4146_b1, by decide, c4146_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4142_b9, by decide, c4142_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4143_b0, by decide, c4143_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4145_b0, by decide, c4145_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4144_b9, by decide, c4144_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4145_b1, by decide, c4145_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4145_b2, by decide, c4145_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4145_b3, by decide, c4145_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 313, c4143_b5, by decide, c4143_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4143_b6, by decide, c4143_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4143_b7, by decide, c4143_ok7⟩, ?_⟩
  simp

def s18 : List Nat := [108086391056957440, 90353467591294976, 72339069148921856, 295166201052839084033, 4647714815446417409, 295148186654396710913, 4629700417004044289, 18295873553367041, 4611686018561671169, 281475110993921, 90353467524190208, 72339069081817088, 295148186654329606145, 4629700416936939521, 18295873486262273, 4611686018494566401, 281475043889153, 4611686018427461632, 72339069014712320]
theorem e18 : enumKeys 398 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4146_b2, by decide, c4146_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4146_b3, by decide, c4146_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4146_b4, by decide, c4146_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4147_b0, by decide, c4147_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4146_b9, by decide, c4146_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4147_b2, by decide, c4147_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4147_b1, by decide, c4147_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4147_b3, by decide, c4147_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4147_b4, by decide, c4147_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4147_b5, by decide, c4147_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4146_b5, by decide, c4146_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4146_b6, by decide, c4146_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4147_b7, by decide, c4147_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4147_b6, by decide, c4147_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4147_b8, by decide, c4147_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4147_b9, by decide, c4147_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4148_b0, by decide, c4148_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4146_b7, by decide, c4146_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4146_b8, by decide, c4146_ok8⟩, ?_⟩
  simp

def s19 : List Nat := [77687093572468736, 73464968938586112, 1158551004141125633, 73788383669722087425, 18451529148313960449, 4617315517961928705, 1154328879507243009, 18447025548703367169, 4612811918351335425, 1407374900658177, 77687093572206608, 73464968938323984, 73788383669721825297, 18451529148313698321, 4617315517961666577, 18447025548703105041, 4612811918351073297, 1407374900396049, 76842668642337024, 72339069031743744, 1157706579210993921, 73787257769815245057, 4616189618055086337, 4785074604409089, 1153202979600400641, 4611686018444493057, 281474993815809, 73787257769814982928, 4616189618054824208, 76842668642074896, 4611686018444230928, 72339069031481616]
theorem e19 : enumKeys 398 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4148_b1, by decide, c4148_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4148_b2, by decide, c4148_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4149_b2, by decide, c4149_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4149_b6, by decide, c4149_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4149_b5, by decide, c4149_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4149_b4, by decide, c4149_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4149_b3, by decide, c4149_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4149_b8, by decide, c4149_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4149_b7, by decide, c4149_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4149_b9, by decide, c4149_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4148_b5, by decide, c4148_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4148_b6, by decide, c4148_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4150_b9, by decide, c4150_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4150_b8, by decide, c4150_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4150_b7, by decide, c4150_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4151_b1, by decide, c4151_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4151_b0, by decide, c4151_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4151_b2, by decide, c4151_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4148_b3, by decide, c4148_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4148_b4, by decide, c4148_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4150_b0, by decide, c4150_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4150_b3, by decide, c4150_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4150_b2, by decide, c4150_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4150_b4, by decide, c4150_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4150_b1, by decide, c4150_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4150_b5, by decide, c4150_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4150_b6, by decide, c4150_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4148_b8, by decide, c4148_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4148_b7, by decide, c4148_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4148_b9, by decide, c4148_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4149_b0, by decide, c4149_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4149_b1, by decide, c4149_ok1⟩, ?_⟩
  simp

def s20 : List Nat := [90353467524448256, 72620544058785792, 1171217378093105153, 295148468129306574849, 4629981891913908225, 1153484454627442689, 4611967493471535105, 562950020857857, 90353467524186128, 72620544058523664, 295148468129306312721, 4629981891913646097, 4611967493471272977, 562950020595729, 72620543991681024, 1153484454560337921, 4611967493404430337, 562949953753089, 4611967493404168208, 72620543991418896]
theorem e20 : enumKeys 398 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4151_b3, by decide, c4151_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4151_b4, by decide, c4151_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4152_b0, by decide, c4152_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4152_b3, by decide, c4152_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4152_b2, by decide, c4152_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4152_b1, by decide, c4152_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4152_b4, by decide, c4152_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4152_b5, by decide, c4152_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4151_b6, by decide, c4151_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4151_b7, by decide, c4151_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4153_b0, by decide, c4153_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4152_b9, by decide, c4152_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4153_b1, by decide, c4153_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4153_b2, by decide, c4153_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4151_b5, by decide, c4151_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4152_b6, by decide, c4152_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4152_b7, by decide, c4152_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4152_b8, by decide, c4152_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4151_b8, by decide, c4151_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4151_b9, by decide, c4151_ok9⟩, ?_⟩
  simp

def s21 : List Nat := [72620543991939072, 1153484454560595969, 4612248968381399041, 72620543991676944, 1153484454560333841, 4612248968381136913, 72620543991414816, 4612248968380874784]
theorem e21 : enumKeys 398 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4153_b3, by decide, c4153_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4153_b7, by decide, c4153_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4153_b8, by decide, c4153_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4153_b4, by decide, c4153_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4153_b9, by decide, c4153_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4154_b0, by decide, c4154_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4153_b6, by decide, c4153_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4153_b5, by decide, c4153_ok5⟩, ?_⟩
  simp

def s22 : List Nat := [74309393868521472, 73789228094652022785, 18452373573243895809, 18447869973633302529, 2251799830593537, 77687093572272384, 73183493961679104, 73788102194745180417, 18451247673337053441, 5629499534344449, 18446744073726460161, 1125899923751169, 73786976294838338048, 76561193665430016, 72057594054836736]
theorem e22 : enumKeys 398 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4154_b1, by decide, c4154_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4154_b8, by decide, c4154_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4154_b7, by decide, c4154_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4154_b9, by decide, c4154_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4155_b0, by decide, c4155_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4154_b2, by decide, c4154_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4154_b3, by decide, c4154_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4155_b2, by decide, c4155_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4155_b1, by decide, c4155_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4155_b3, by decide, c4155_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4155_b4, by decide, c4155_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4155_b5, by decide, c4155_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c4154_b4, by decide, c4154_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4154_b5, by decide, c4154_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4154_b6, by decide, c4154_ok6⟩, ?_⟩
  simp

def s23 : List Nat := [91197892454383616, 73464968988721152, 295149312554236510209, 18465039947195875329, 4630826316843843585, 18447025548753502209, 4612811918401470465, 1407374950793217, 90353467524251904, 72339069081878784, 295148186654329667841, 4629700416937001217, 18295873486323969, 4611686018494628097, 281475043950849, 73464968921616384, 18447025548686397441, 4612811918334365697, 1407374883688449, 4611686018427523328, 72339069014774016]
theorem e23 : enumKeys 398 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4155_b6, by decide, c4155_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4155_b7, by decide, c4155_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4156_b5, by decide, c4156_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4156_b4, by decide, c4156_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4156_b3, by decide, c4156_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4156_b7, by decide, c4156_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4156_b6, by decide, c4156_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4156_b8, by decide, c4156_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4155_b9, by decide, c4155_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4156_b0, by decide, c4156_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4157_b3, by decide, c4157_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4157_b2, by decide, c4157_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4157_b4, by decide, c4157_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4157_b5, by decide, c4157_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4157_b6, by decide, c4157_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4155_b8, by decide, c4155_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4157_b0, by decide, c4157_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4156_b9, by decide, c4156_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4157_b1, by decide, c4157_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4156_b1, by decide, c4156_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4156_b2, by decide, c4156_ok2⟩, ?_⟩
  simp

def s24 : List Nat := [73464968921874432, 1154328879490531329, 18447307023663366145, 4613093393311334401, 73464968921612304, 18447307023663104017, 4613093393311072273, 72620543991742720, 1153484454560399617, 4611967493404492033, 562949953814785, 4611967493404229904, 72620543991480592]
theorem e24 : enumKeys 398 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4157_b7, by decide, c4157_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4158_b2, by decide, c4158_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4158_b4, by decide, c4158_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4158_b3, by decide, c4158_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4157_b9, by decide, c4157_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4158_b9, by decide, c4158_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4158_b8, by decide, c4158_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4157_b8, by decide, c4157_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4158_b5, by decide, c4158_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4158_b6, by decide, c4158_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4158_b7, by decide, c4158_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4158_b0, by decide, c4158_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4158_b1, by decide, c4158_ok1⟩, ?_⟩
  simp

def s25 : List Nat := [74309393851809792, 18448151448593301505, 4613937818241269761, 73464968921678080, 18447025548686459137, 4612811918334427393, 1407374883750145, 4611686018427585024, 72339069014835712]
theorem e25 : enumKeys 398 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4159_b0, by decide, c4159_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4159_b5, by decide, c4159_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4159_b4, by decide, c4159_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4159_b1, by decide, c4159_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4159_b7, by decide, c4159_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4159_b6, by decide, c4159_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4159_b8, by decide, c4159_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4159_b2, by decide, c4159_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4159_b3, by decide, c4159_ok3⟩, ?_⟩
  simp

def s26 : List Nat := [94575592191557633, 90071992580964353, 81064793359777793, 76561193749184513, 72057594138591233, 295156912378607566850, 73809494292975058946, 295152408778996973570, 73804990693364465666, 22517998153629698, 295147905179386380290, 18014398543036418, 73791479894532685826, 9007199321849858, 73786976294922092546, 4503599711256578, 100663298, 73791479894465581057, 81064793292673025, 73786976294854987777, 76561193682079745, 72057594071486465]
theorem e26 : enumKeys 398 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4160_b0, by decide, c4160_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4160_b2, by decide, c4160_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4159_b9, by decide, c4159_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4160_b1, by decide, c4160_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4160_b3, by decide, c4160_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4161_b0, by decide, c4161_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4160_b9, by decide, c4160_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4161_b4, by decide, c4161_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4161_b3, by decide, c4161_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4161_b5, by decide, c4161_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4161_b8, by decide, c4161_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4161_b9, by decide, c4161_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4161_b1, by decide, c4161_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4161_b2, by decide, c4161_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4161_b6, by decide, c4161_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4161_b7, by decide, c4161_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4162_b0, by decide, c4162_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4160_b4, by decide, c4160_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4160_b5, by decide, c4160_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4160_b6, by decide, c4160_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4160_b7, by decide, c4160_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4160_b8, by decide, c4160_ok8⟩, ?_⟩
  simp

def s27 : List Nat := [81064793292931073, 76842668659048449, 72339069048455169, 1161928703861587970, 73791761369442549762, 4620693217682391042, 1157706579227705346, 73787257769831956482, 4616189618071797762, 4785074621120514, 1153202979617112066, 4611686018461204482, 281475010527234, 73791761369442287633, 81064793292668945, 4620693217682128913, 73787257769831694353, 4616189618071535633, 76842668658786321, 4611686018460942353, 72339069048193041]
theorem e27 : enumKeys 398 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4162_b1, by decide, c4162_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4162_b2, by decide, c4162_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4162_b3, by decide, c4162_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4163_b2, by decide, c4163_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4163_b6, by decide, c4163_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4163_b5, by decide, c4163_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4163_b3, by decide, c4163_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4163_b8, by decide, c4163_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4163_b7, by decide, c4163_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4163_b9, by decide, c4163_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4163_b4, by decide, c4163_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4164_b0, by decide, c4164_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4164_b1, by decide, c4164_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4162_b6, by decide, c4162_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4162_b5, by decide, c4162_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4162_b4, by decide, c4162_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4162_b8, by decide, c4162_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4162_b7, by decide, c4162_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4162_b9, by decide, c4162_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4163_b0, by decide, c4163_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4163_b1, by decide, c4163_ok1⟩, ?_⟩
  simp

def s28 : List Nat := [77687093588983809, 73183493978390529, 73792605794372485122, 18455751272964358146, 73788102194761891842, 18451247673353764866, 5629499551055874, 18446744073743171586, 1125899940462594, 73791479894465642753, 81064793292734721, 73786976294855049473, 76561193682141441, 72057594071548161]
theorem e28 : enumKeys 398 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4164_b2, by decide, c4164_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4164_b3, by decide, c4164_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4165_b0, by decide, c4165_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4164_b9, by decide, c4164_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4165_b2, by decide, c4165_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4165_b1, by decide, c4165_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4165_b3, by decide, c4165_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4165_b4, by decide, c4165_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4165_b5, by decide, c4165_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4164_b4, by decide, c4164_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4164_b5, by decide, c4164_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4164_b6, by decide, c4164_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4164_b7, by decide, c4164_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4164_b8, by decide, c4164_ok8⟩, ?_⟩
  simp

def s29 : List Nat := [94575592174845953, 90353467540963329, 76842668709183489, 72339069098590209, 295152690253956972546, 73805272168324464642, 4634204016564305922, 295148186654346379266, 4629700416953712642, 18295873503035394, 73787257769882091522, 4616189618121932802, 4785074671255554, 4611686018511339522, 281475060662274, 73787257769814986753, 4616189618054828033, 76842668642078721, 4611686018444234753, 72339069031485441]
theorem e29 : enumKeys 398 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4165_b6, by decide, c4165_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4165_b8, by decide, c4165_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4165_b7, by decide, c4165_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4165_b9, by decide, c4165_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4166_b7, by decide, c4166_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4166_b6, by decide, c4166_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4166_b5, by decide, c4166_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4167_b2, by decide, c4167_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4167_b1, by decide, c4167_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4167_b3, by decide, c4167_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4166_b9, by decide, c4166_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4166_b8, by decide, c4166_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4167_b0, by decide, c4167_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4167_b4, by decide, c4167_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4167_b5, by decide, c4167_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4166_b1, by decide, c4166_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4166_b0, by decide, c4166_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4166_b2, by decide, c4166_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4166_b3, by decide, c4166_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4166_b4, by decide, c4166_ok4⟩, ?_⟩
  simp

def s30 : List Nat := [76842668642336769, 72620544008454145, 1157706579210993666, 73787539244791955458, 4616471093031796738, 1153484454577111042, 4611967493421203458, 562949970526210, 73787539244791693329, 76842668642074641, 4616471093031534609, 4611967493420941329, 72620544008192017]
theorem e30 : enumKeys 398 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4167_b6, by decide, c4167_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4167_b7, by decide, c4167_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4168_b3, by decide, c4168_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4168_b6, by decide, c4168_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4168_b5, by decide, c4168_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4168_b4, by decide, c4168_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4168_b7, by decide, c4168_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4168_b8, by decide, c4168_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4168_b0, by decide, c4168_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4167_b9, by decide, c4167_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4167_b8, by decide, c4167_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4168_b1, by decide, c4168_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4168_b2, by decide, c4168_ok2⟩, ?_⟩
  simp

def s31 : List Nat := [77687093572272129, 73464968938389505, 73788383669721890818, 18451529148313763842, 4617315517961732098, 18447025548703170562, 4612811918351138818, 1407374900461570, 73787257769815048449, 4616189618054889729, 76842668642140417, 4611686018444296449, 72339069031547137]
theorem e31 : enumKeys 398 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4168_b9, by decide, c4168_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4169_b0, by decide, c4169_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4169_b8, by decide, c4169_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4169_b7, by decide, c4169_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4169_b6, by decide, c4169_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4170_b0, by decide, c4170_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4169_b9, by decide, c4169_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4170_b1, by decide, c4170_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4169_b2, by decide, c4169_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4169_b1, by decide, c4169_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4169_b3, by decide, c4169_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4169_b4, by decide, c4169_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4169_b5, by decide, c4169_ok5⟩, ?_⟩
  simp

def s32 : List Nat := [90353467524251649, 72620544058589185, 295148468129306378242, 4629981891913711618, 4611967493471338498, 562950020661250, 4611967493404233729, 72620543991484417]
theorem e32 : enumKeys 398 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4170_b2, by decide, c4170_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4170_b3, by decide, c4170_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4170_b7, by decide, c4170_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4170_b6, by decide, c4170_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4170_b8, by decide, c4170_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4170_b9, by decide, c4170_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4170_b4, by decide, c4170_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4170_b5, by decide, c4170_ok5⟩, ?_⟩
  simp

def s33 : List Nat := [72620543991742465, 1153484454560399362, 4612248968381202434, 72620543991480337, 4612248968380940305]
theorem e33 : enumKeys 398 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4171_b0, by decide, c4171_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4171_b3, by decide, c4171_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4171_b4, by decide, c4171_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4171_b2, by decide, c4171_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4171_b1, by decide, c4171_ok1⟩, ?_⟩
  simp

def s34 : List Nat := [73464968921677825, 18447307023663169538, 4613093393311137794, 4611967493404295425, 72620543991546113]
theorem e34 : enumKeys 398 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4171_b5, by decide, c4171_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4171_b9, by decide, c4171_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4171_b8, by decide, c4171_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4171_b6, by decide, c4171_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4171_b7, by decide, c4171_ok7⟩, ?_⟩
  simp

def s35 : List Nat := [73795983494092947458, 73791479894482354178, 81064793309446146, 73786976294871760898, 76561193698852866, 72057594088259586]
theorem e35 : enumKeys 398 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4172_b0, by decide, c4172_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4172_b1, by decide, c4172_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4172_b2, by decide, c4172_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4172_b3, by decide, c4172_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4172_b4, by decide, c4172_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4172_b5, by decide, c4172_ok5⟩, ?_⟩
  simp

def s36 : List Nat := [73791761369442353154, 81064793292734466, 4620693217682194434, 73787257769831759874, 4616189618071601154, 76842668658851842, 4611686018461007874, 72339069048258562]
theorem e36 : enumKeys 398 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4172_b8, by decide, c4172_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4172_b7, by decide, c4172_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4172_b6, by decide, c4172_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4173_b0, by decide, c4173_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4172_b9, by decide, c4172_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4173_b1, by decide, c4173_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4173_b2, by decide, c4173_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4173_b3, by decide, c4173_ok3⟩, ?_⟩
  simp

def s37 : List Nat := [73787539244791758850, 76842668642140162, 4616471093031600130, 4611967493421006850, 72620544008257538]
theorem e37 : enumKeys 398 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4173_b6, by decide, c4173_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4173_b5, by decide, c4173_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4173_b4, by decide, c4173_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4173_b7, by decide, c4173_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4173_b8, by decide, c4173_ok8⟩, ?_⟩
  simp

def s38 : List Nat := [72620543991545858, 4612248968381005826]
theorem e38 : enumKeys 398 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4174_b0, by decide, c4174_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4173_b9, by decide, c4173_ok9⟩, ?_⟩
  simp

/-- every enumerated key with left type `398` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 398 mR,
    (398 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 398 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K34
end Grid3.Three.Cert
