import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4174
import Grid3.Three.Cert.Data.C4175
import Grid3.Three.Cert.Data.C4176
import Grid3.Three.Cert.Data.C4177
import Grid3.Three.Cert.Data.C4178
import Grid3.Three.Cert.Data.C4179
import Grid3.Three.Cert.Data.C4180
import Grid3.Three.Cert.Data.C4181
import Grid3.Three.Cert.Data.C4182
import Grid3.Three.Cert.Data.C4183
import Grid3.Three.Cert.Data.C4184
import Grid3.Three.Cert.Data.C4185
import Grid3.Three.Cert.Data.C4186
import Grid3.Three.Cert.Data.C4187
import Grid3.Three.Cert.Data.C4188
import Grid3.Three.Cert.Data.C4189
import Grid3.Three.Cert.Data.C4190
import Grid3.Three.Cert.Data.C4191
import Grid3.Three.Cert.Data.C4192
import Grid3.Three.Cert.Data.C4193
import Grid3.Three.Cert.Data.C4194
import Grid3.Three.Cert.Data.C4195
import Grid3.Three.Cert.Data.C4196

/-! Seam keys with left type `3075` (type index 35): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `ai_research_notes/cx/k3rev/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K35

def s00 : List Nat := [14507109835375550096474112, 9671406556917033397653504, 4835703278458516698832896, 12288]
theorem e00 : enumKeys 3075 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 108, c4174_b1, by decide, c4174_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 118, c4174_b2, by decide, c4174_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 132, c4174_b3, by decide, c4174_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c4174_b4, by decide, c4174_ok4⟩, ?_⟩
  simp

def s01 : List Nat := [5156824199293652573356032, 6346860552976803167207440, 6063518564004624454385920, 6044629098073145873531152, 1530046740449765049241600, 1511157274518286468386832, 1227815285546107755565312, 1208925819614629174710544]
theorem e01 : enumKeys 3075 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4174_b5, by decide, c4174_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4174_b9, by decide, c4174_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c4174_b7, by decide, c4174_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4175_b1, by decide, c4175_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4174_b6, by decide, c4174_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4175_b0, by decide, c4175_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4174_b8, by decide, c4174_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c4175_b2, by decide, c4175_ok2⟩, ?_⟩
  simp

def s02 : List Nat := [9690296022848511978504192, 9746964420642947721068560, 4930150608115909603102720, 4911261142184431022247952, 94447329657392904282112, 75557863725914323427344]
theorem e02 : enumKeys 3075 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4175_b3, by decide, c4175_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c4175_b6, by decide, c4175_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c4175_b4, by decide, c4175_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4175_b7, by decide, c4175_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4175_b5, by decide, c4175_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4175_b8, by decide, c4175_ok8⟩, ?_⟩
  simp

def s03 : List Nat := [340010386766614455386112, 396678784561050197950480, 1530046740449765049237520, 1586715138244200791801888, 113336795588871485128960, 1246704751477586336416000, 1303373149272022078980368, 1284483683340543498125600]
theorem e03 : enumKeys 3075 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4175_b9, by decide, c4175_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4176_b3, by decide, c4176_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4176_b2, by decide, c4176_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4176_b5, by decide, c4176_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4176_b1, by decide, c4176_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4176_b0, by decide, c4176_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4176_b4, by decide, c4176_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4176_b6, by decide, c4176_ok6⟩, ?_⟩
  simp

def s04 : List Nat := [4873482210321473860534272, 4930150608115909603098640, 4986819005910345345663008, 113336795588871485132800, 170005193383307227697168, 151115727451828646842400]
theorem e04 : enumKeys 3075 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4176_b7, by decide, c4176_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4176_b9, by decide, c4176_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4177_b1, by decide, c4177_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4176_b8, by decide, c4176_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4177_b0, by decide, c4177_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4177_b2, by decide, c4177_ok2⟩, ?_⟩
  simp

def s05 : List Nat := [56668397794435742564352, 113336795588871485128720, 170005193383307227693088, 226673591177742970257456]
theorem e05 : enumKeys 3075 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4177_b3, by decide, c4177_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4177_b4, by decide, c4177_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4177_b5, by decide, c4177_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4177_b6, by decide, c4177_ok6⟩, ?_⟩
  simp

def s06 : List Nat := [9973638011820690691325952, 9676128923399903042863360, 5142657099845043637719040, 4840425644941386344042752, 306953821386526938898432, 4722366482869645222144]
theorem e06 : enumKeys 3075 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4177_b7, by decide, c4177_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4178_b0, by decide, c4178_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c4177_b8, by decide, c4177_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4178_b1, by decide, c4178_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4177_b9, by decide, c4177_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4178_b2, by decide, c4178_ok2⟩, ?_⟩
  simp

def s07 : List Nat := [623352375738793168207872, 609185276290184232566800, 1813388729421943762059280, 325843287318005519745280, 1530046740449765049237760, 1515879641001156113596688, 1232537652028977400775168, 1213648186097498819920400]
theorem e07 : enumKeys 3075 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4178_b3, by decide, c4178_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4178_b8, by decide, c4178_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4178_b7, by decide, c4178_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4178_b5, by decide, c4178_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4178_b4, by decide, c4178_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4178_b9, by decide, c4178_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4178_b6, by decide, c4178_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4179_b0, by decide, c4179_ok0⟩, ?_⟩
  simp

def s08 : List Nat := [5156824199293652573356032, 5142657099845043637714960, 5213492597088088315920400, 4859315110872864924893440, 4930150608115909603098880, 4915983508667300667457808, 325843287318005519749120, 396678784561050197954560, 382511685112441262313488, 99169696140262549491968, 80280230208783968637200]
theorem e08 : enumKeys 3075 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4179_b1, by decide, c4179_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4179_b8, by decide, c4179_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4179_b7, by decide, c4179_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4179_b5, by decide, c4179_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4179_b4, by decide, c4179_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4180_b0, by decide, c4180_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4179_b3, by decide, c4179_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4179_b2, by decide, c4179_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4179_b9, by decide, c4179_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4179_b6, by decide, c4179_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4180_b1, by decide, c4180_ok1⟩, ?_⟩
  simp

def s09 : List Nat := [340010386766614455386112, 325843287318005519745040, 396678784561050197950480, 382511685112441262309408, 453347182355485940514848, 42501298345826806923520, 113336795588871485128960, 99169696140262549487888, 170005193383307227693328, 155838093934698292052256]
theorem e09 : enumKeys 3075 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4180_b2, by decide, c4180_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4180_b6, by decide, c4180_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4180_b5, by decide, c4180_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4181_b0, by decide, c4181_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4180_b9, by decide, c4180_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4180_b4, by decide, c4180_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4180_b3, by decide, c4180_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4180_b8, by decide, c4180_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4180_b7, by decide, c4180_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4181_b1, by decide, c4181_ok1⟩, ?_⟩
  simp

def s10 : List Nat := [5440166188265831286177792, 5142657099845043637715200, 4845148011424255989252608, 609185276290184232570880, 311676187869396584108288, 9444732965739290432000]
theorem e10 : enumKeys 3075 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4181_b2, by decide, c4181_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4181_b4, by decide, c4181_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4181_b6, by decide, c4181_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4181_b3, by decide, c4181_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4181_b5, by decide, c4181_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4181_b7, by decide, c4181_ok7⟩, ?_⟩
  simp

def s11 : List Nat := [623352375738793168207872, 609185276290184232566800, 680020773533228910772240, 325843287318005519745280, 396678784561050197950720, 311676187869396584104208, 382511685112441262309648, 28334198897217871282688, 99169696140262549488128, 85002596691653613847056]
theorem e11 : enumKeys 3075 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 312, c4181_b8, by decide, c4181_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4182_b4, by decide, c4182_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4182_b3, by decide, c4182_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4182_b0, by decide, c4182_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4181_b9, by decide, c4181_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4182_b6, by decide, c4182_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4182_b5, by decide, c4182_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4182_b2, by decide, c4182_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4182_b1, by decide, c4182_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4182_b7, by decide, c4182_ok7⟩, ?_⟩
  simp

def s12 : List Nat := [906694364710971881029632, 609185276290184232567040, 311676187869396584104448, 14167099448608935641856]
theorem e12 : enumKeys 3075 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4182_b8, by decide, c4182_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c4182_b9, by decide, c4182_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4183_b0, by decide, c4183_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4183_b1, by decide, c4183_ok1⟩, ?_⟩
  simp

def s13 : List Nat := [10880332376531662572355585, 6044629098073145873534977, 1208925819614629174714369]
theorem e13 : enumKeys 3075 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c4183_b2, by decide, c4183_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 117, c4183_b3, by decide, c4183_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 128, c4183_b4, by decide, c4183_ok4⟩, ?_⟩
  simp

def s14 : List Nat := [1530046740449765049237505, 2720083094132915643088913, 2436741105160736930267393, 2417851639229258349412625]
theorem e14 : enumKeys 3075 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4183_b5, by decide, c4183_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4183_b7, by decide, c4183_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4183_b6, by decide, c4183_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c4183_b8, by decide, c4183_ok8⟩, ?_⟩
  simp

def s15 : List Nat := [4930150608115909603098625, 6063518564004624454385665, 6120186961799060196950033, 1303373149272022078984193, 1284483683340543498129425]
theorem e15 : enumKeys 3075 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4184_b0, by decide, c4184_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c4183_b9, by decide, c4183_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 126, c4184_b2, by decide, c4184_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 129, c4184_b1, by decide, c4184_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c4184_b3, by decide, c4184_ok3⟩, ?_⟩
  simp

def s16 : List Nat := [113336795588871485128705, 1246704751477586336415745, 170005193383307227693073, 1303373149272022078980113, 1360041547066457821544481]
theorem e16 : enumKeys 3075 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4184_b5, by decide, c4184_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4184_b4, by decide, c4184_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4184_b7, by decide, c4184_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4184_b6, by decide, c4184_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c4184_b8, by decide, c4184_ok8⟩, ?_⟩
  simp

def s17 : List Nat := [5142657099845043637714945, 6346860552976803167207425, 6049351464556015518744833, 1515879641001156113600513, 1213648186097498819924225]
theorem e17 : enumKeys 3075 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4185_b0, by decide, c4185_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4184_b9, by decide, c4184_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4185_b2, by decide, c4185_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4185_b1, by decide, c4185_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4185_b3, by decide, c4185_ok3⟩, ?_⟩
  simp

def s18 : List Nat := [9676128923399903042863105, 9746964420642947721068545, 4915983508667300667461633, 80280230208783968641025]
theorem e18 : enumKeys 3075 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4185_b5, by decide, c4185_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4185_b4, by decide, c4185_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4185_b6, by decide, c4185_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c4185_b7, by decide, c4185_ok7⟩, ?_⟩
  simp

def s19 : List Nat := [325843287318005519745025, 396678784561050197950465, 1530046740449765049237505, 382511685112441262309393, 1515879641001156113596433, 1586715138244200791801873, 99169696140262549487873, 1232537652028977400774913, 1303373149272022078980353, 1289206049823413143339281]
theorem e19 : enumKeys 3075 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4186_b0, by decide, c4186_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4185_b9, by decide, c4185_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4185_b8, by decide, c4185_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4186_b6, by decide, c4186_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4186_b5, by decide, c4186_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4186_b4, by decide, c4186_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4186_b3, by decide, c4186_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4186_b2, by decide, c4186_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4186_b1, by decide, c4186_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4186_b7, by decide, c4186_ok7⟩, ?_⟩
  simp

def s20 : List Nat := [4859315110872864924893185, 4930150608115909603098625, 4915983508667300667457553, 4986819005910345345662993, 99169696140262549491713, 170005193383307227697153, 155838093934698292056081]
theorem e20 : enumKeys 3075 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4186_b9, by decide, c4186_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4186_b8, by decide, c4186_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4187_b3, by decide, c4187_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4187_b2, by decide, c4187_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4187_b1, by decide, c4187_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4187_b0, by decide, c4187_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c4187_b4, by decide, c4187_ok4⟩, ?_⟩
  simp

def s21 : List Nat := [42501298345826806923265, 113336795588871485128705, 99169696140262549487633, 170005193383307227693073, 155838093934698292052001, 226673591177742970257441]
theorem e21 : enumKeys 3075 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4187_b6, by decide, c4187_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4187_b5, by decide, c4187_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4187_b8, by decide, c4187_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4187_b7, by decide, c4187_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4188_b0, by decide, c4188_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4187_b9, by decide, c4187_ok9⟩, ?_⟩
  simp

def s22 : List Nat := [609185276290184232566785, 1813388729421943762059265, 311676187869396584104193, 1515879641001156113596673, 1218370552580368465134081]
theorem e22 : enumKeys 3075 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4188_b2, by decide, c4188_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4188_b1, by decide, c4188_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4188_b4, by decide, c4188_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4188_b3, by decide, c4188_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4188_b5, by decide, c4188_ok5⟩, ?_⟩
  simp

def s23 : List Nat := [5142657099845043637714945, 5213492597088088315920385, 4845148011424255989252353, 4915983508667300667457793, 311676187869396584108033, 382511685112441262313473, 85002596691653613850881]
theorem e23 : enumKeys 3075 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4188_b7, by decide, c4188_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4188_b6, by decide, c4188_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4189_b1, by decide, c4189_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4189_b0, by decide, c4189_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4188_b9, by decide, c4188_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4188_b8, by decide, c4188_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4189_b2, by decide, c4189_ok2⟩, ?_⟩
  simp

def s24 : List Nat := [325843287318005519745025, 396678784561050197950465, 311676187869396584103953, 382511685112441262309393, 453347182355485940514833, 28334198897217871282433, 99169696140262549487873, 170005193383307227693313, 85002596691653613846801, 155838093934698292052241]
theorem e24 : enumKeys 3075 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4189_b4, by decide, c4189_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4189_b3, by decide, c4189_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4190_b0, by decide, c4190_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4189_b9, by decide, c4189_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4189_b8, by decide, c4189_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4189_b7, by decide, c4189_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4189_b6, by decide, c4189_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4189_b5, by decide, c4189_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4190_b2, by decide, c4190_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4190_b1, by decide, c4190_ok1⟩, ?_⟩
  simp

def s25 : List Nat := [609185276290184232566785, 680020773533228910772225, 311676187869396584104193, 382511685112441262309633, 14167099448608935641601, 85002596691653613847041]
theorem e25 : enumKeys 3075 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c4190_b4, by decide, c4190_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4190_b3, by decide, c4190_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4190_b6, by decide, c4190_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4190_b5, by decide, c4190_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4190_b8, by decide, c4190_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4190_b7, by decide, c4190_ok7⟩, ?_⟩
  simp

def s26 : List Nat := [7253554917687775048237058, 2417851639229258349416450]
theorem e26 : enumKeys 3075 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c4190_b9, by decide, c4190_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 116, c4191_b0, by decide, c4191_ok0⟩, ?_⟩
  simp

def s27 : List Nat := [1303373149272022078980098, 2436741105160736930267138, 2493409502955172672831506]
theorem e27 : enumKeys 3075 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c4191_b2, by decide, c4191_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4191_b1, by decide, c4191_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 120, c4191_b3, by decide, c4191_ok3⟩, ?_⟩
  simp

def s28 : List Nat := [1515879641001156113596418, 2720083094132915643088898, 2422574005712127994626306]
theorem e28 : enumKeys 3075 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4191_b5, by decide, c4191_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4191_b4, by decide, c4191_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4191_b6, by decide, c4191_ok6⟩, ?_⟩
  simp

def s29 : List Nat := [4915983508667300667457538, 6049351464556015518744578, 6120186961799060196950018, 1289206049823413143343106]
theorem e29 : enumKeys 3075 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4191_b9, by decide, c4191_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4191_b8, by decide, c4191_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4191_b7, by decide, c4191_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c4192_b0, by decide, c4192_ok0⟩, ?_⟩
  simp

def s30 : List Nat := [99169696140262549487618, 170005193383307227693058, 1232537652028977400774658, 1303373149272022078980098, 155838093934698292051986, 1289206049823413143339026, 1360041547066457821544466]
theorem e30 : enumKeys 3075 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4192_b4, by decide, c4192_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4192_b2, by decide, c4192_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4192_b3, by decide, c4192_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4192_b1, by decide, c4192_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4192_b7, by decide, c4192_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4192_b6, by decide, c4192_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4192_b5, by decide, c4192_ok5⟩, ?_⟩
  simp

def s31 : List Nat := [311676187869396584103938, 382511685112441262309378, 1515879641001156113596418, 1586715138244200791801858, 85002596691653613846786, 1218370552580368465133826, 1289206049823413143339266]
theorem e31 : enumKeys 3075 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4193_b1, by decide, c4193_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4193_b0, by decide, c4193_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4192_b9, by decide, c4192_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4192_b8, by decide, c4192_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4193_b4, by decide, c4193_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4193_b3, by decide, c4193_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4193_b2, by decide, c4193_ok2⟩, ?_⟩
  simp

def s32 : List Nat := [4845148011424255989252098, 4915983508667300667457538, 4986819005910345345662978, 85002596691653613850626, 155838093934698292056066]
theorem e32 : enumKeys 3075 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4193_b7, by decide, c4193_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4193_b6, by decide, c4193_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4193_b5, by decide, c4193_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4193_b9, by decide, c4193_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4193_b8, by decide, c4193_ok8⟩, ?_⟩
  simp

def s33 : List Nat := [28334198897217871282178, 99169696140262549487618, 170005193383307227693058, 85002596691653613846546, 155838093934698292051986, 226673591177742970257426]
theorem e33 : enumKeys 3075 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4194_b2, by decide, c4194_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4194_b1, by decide, c4194_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4194_b0, by decide, c4194_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4194_b5, by decide, c4194_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4194_b4, by decide, c4194_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4194_b3, by decide, c4194_ok3⟩, ?_⟩
  simp

def s34 : List Nat := [311676187869396584103938, 382511685112441262309378, 453347182355485940514818, 14167099448608935641346, 85002596691653613846786, 155838093934698292052226]
theorem e34 : enumKeys 3075 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4194_b8, by decide, c4194_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4194_b7, by decide, c4194_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4194_b6, by decide, c4194_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4195_b1, by decide, c4195_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4195_b0, by decide, c4195_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4194_b9, by decide, c4194_ok9⟩, ?_⟩
  simp

def s35 : List Nat := [3626777458843887524118531]
theorem e35 : enumKeys 3075 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 108, c4195_b2, by decide, c4195_ok2⟩, ?_⟩
  simp

def s36 : List Nat := [1289206049823413143339011, 2422574005712127994626051, 2493409502955172672831491]
theorem e36 : enumKeys 3075 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4195_b5, by decide, c4195_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4195_b4, by decide, c4195_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4195_b3, by decide, c4195_ok3⟩, ?_⟩
  simp

def s37 : List Nat := [85002596691653613846531, 155838093934698292051971, 1218370552580368465133571, 1289206049823413143339011, 1360041547066457821544451]
theorem e37 : enumKeys 3075 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4196_b0, by decide, c4196_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4195_b8, by decide, c4195_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4195_b9, by decide, c4195_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4195_b7, by decide, c4195_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4195_b6, by decide, c4195_ok6⟩, ?_⟩
  simp

def s38 : List Nat := [14167099448608935641091, 85002596691653613846531, 155838093934698292051971, 226673591177742970257411]
theorem e38 : enumKeys 3075 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4196_b4, by decide, c4196_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4196_b3, by decide, c4196_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4196_b2, by decide, c4196_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4196_b1, by decide, c4196_ok1⟩, ?_⟩
  simp

/-- every enumerated key with left type `3075` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 3075 mR,
    (3075 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K35
end Grid3.Three.Cert
