import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0109
import Grid3.Three.Cert.Data.C0110
import Grid3.Three.Cert.Data.C0111
import Grid3.Three.Cert.Data.C0112
import Grid3.Three.Cert.Data.C0113
import Grid3.Three.Cert.Data.C0114

/-! Seam keys with left type `3075` (type index 35): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K35

theorem tL : rtype 3075 = 240 := by decide

def s00 : List Nat := [14507109835375550096474112, 9671406556917033397653504, 4835703278458516698832896, 12288]
theorem e00 : enumKeys 3075 12288 = s00 := by decide +kernel
theorem t00 : rtype 12288 = 12288 := by decide
theorem r00 : ∀ M ∈ s00, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 12288 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 12288) (rM M) ne blob = true) := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 108, c0109_b6, by decide, by rw [tL, t00, show rM 14507109835375550096474112 = 3298534883328 by decide]; exact c0109_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 118, c0109_b7, by decide, by rw [tL, t00, show rM 9671406556917033397653504 = 18016597532737536 by decide]; exact c0109_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 132, c0109_b8, by decide, by rw [tL, t00, show rM 4835703278458516698832896 = 36029896530591744 by decide]; exact c0109_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 144, c0109_b9, by decide, by rw [tL, t00, show rM 12288 = 54043195528445952 by decide]; exact c0109_ok9⟩, ?_⟩
  simp

def s01 : List Nat := [5156824199293652573356032, 6346860552976803167207440, 6063518564004624454385920, 6044629098073145873531152, 1530046740449765049241600, 1511157274518286468386832, 1227815285546107755565312, 1208925819614629174710544]
theorem e01 : enumKeys 3075 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 174, c0109_b10, by decide, by rw [tL, t01, show rM 5156824199293652573356032 = 1443109011456 by decide]; exact c0109_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0109_b12, by decide, by rw [tL, t01, show rM 6346860552976803167207440 = 4504772153442304 by decide]; exact c0109_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 141, c0109_b11, by decide, by rw [tL, t01, show rM 6063518564004624454385920 = 1127278591344640 by decide]; exact c0109_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 147, c0109_b13, by decide, by rw [tL, t01, show rM 6044629098073145873531152 = 5630603340808192 by decide]; exact c0109_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 154, c0109_b14, by decide, by rw [tL, t01, show rM 1530046740449765049241600 = 18014746401832960 by decide]; exact c0109_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 159, c0109_b16, by decide, by rw [tL, t01, show rM 1511157274518286468386832 = 22518071151296512 by decide]; exact c0109_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0109_b15, by decide, by rw [tL, t01, show rM 1227815285546107755565312 = 19140577589198848 by decide]; exact c0109_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 152, c0109_b17, by decide, by rw [tL, t01, show rM 1208925819614629174710544 = 23643902338662400 by decide]; exact c0109_ok17⟩, ?_⟩
  simp

def s02 : List Nat := [9690296022848511978504192, 9746964420642947721068560, 4930150608115909603102720, 4911261142184431022247952, 94447329657392904282112, 75557863725914323427344]
theorem e02 : enumKeys 3075 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0110_b25, by decide, by rw [tL, t02, show rM 9690296022848511978504192 = 2473901162496 by decide]; exact c0110_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 132, c0110_b26, by decide, by rw [tL, t02, show rM 9746964420642947721068560 = 4505798919061504 by decide]; exact c0110_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 133, c0110_b27, by decide, by rw [tL, t02, show rM 4930150608115909603102720 = 18015773167452160 by decide]; exact c0110_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 138, c0110_b28, by decide, by rw [tL, t02, show rM 4911261142184431022247952 = 22519097916915712 by decide]; exact c0110_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0110_b29, by decide, by rw [tL, t02, show rM 94447329657392904282112 = 36029072165306368 by decide]; exact c0110_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0110_b30, by decide, by rw [tL, t02, show rM 75557863725914323427344 = 40532396914769920 by decide]; exact c0110_ok30⟩, ?_⟩
  simp

def s03 : List Nat := [340010386766614455386112, 396678784561050197950480, 1530046740449765049237520, 1586715138244200791801888, 113336795588871485128960, 1246704751477586336416000, 1303373149272022078980368, 1284483683340543498125600]
theorem e03 : enumKeys 3075 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0110_b31, by decide, by rw [tL, t03, show rM 340010386766614455386112 = 618475290624 by decide]; exact c0110_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 198, c0110_b34, by decide, by rw [tL, t03, show rM 396678784561050197950480 = 4503943493189632 by decide]; exact c0110_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 190, c0110_b35, by decide, by rw [tL, t03, show rM 1530046740449765049237520 = 4503947519721472 by decide]; exact c0110_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 162, c0110_b37, by decide, by rw [tL, t03, show rM 1586715138244200791801888 = 9007272537620480 by decide]; exact c0110_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 190, c0110_b32, by decide, by rw [tL, t03, show rM 113336795588871485128960 = 1126449931091968 by decide]; exact c0110_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 174, c0110_b33, by decide, by rw [tL, t03, show rM 1246704751477586336416000 = 1126453957623808 by decide]; exact c0110_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 159, c0110_b36, by decide, by rw [tL, t03, show rM 1303373149272022078980368 = 5629778975522816 by decide]; exact c0110_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 154, c0110_b38, by decide, by rw [tL, t03, show rM 1284483683340543498125600 = 10133103724986368 by decide]; exact c0110_ok38⟩, ?_⟩
  simp

def s04 : List Nat := [4873482210321473860534272, 4930150608115909603098640, 4986819005910345345663008, 113336795588871485132800, 170005193383307227697168, 151115727451828646842400]
theorem e04 : enumKeys 3075 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0112_b29, by decide, by rw [tL, t04, show rM 4873482210321473860534272 = 1649267441664 by decide]; exact c0112_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 169, c0112_b30, by decide, by rw [tL, t04, show rM 4930150608115909603098640 = 4504974285340672 by decide]; exact c0112_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0112_b31, by decide, by rw [tL, t04, show rM 4986819005910345345663008 = 9008299303239680 by decide]; exact c0112_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 170, c0112_b32, by decide, by rw [tL, t04, show rM 113336795588871485132800 = 18014948533731328 by decide]; exact c0112_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0112_b33, by decide, by rw [tL, t04, show rM 170005193383307227697168 = 22518273551630336 by decide]; exact c0112_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0112_b34, by decide, by rw [tL, t04, show rM 151115727451828646842400 = 27021598301093888 by decide]; exact c0112_ok34⟩, ?_⟩
  simp

def s05 : List Nat := [56668397794435742564352, 113336795588871485128720, 170005193383307227693088, 226673591177742970257456]
theorem e05 : enumKeys 3075 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b10, by decide, by rw [tL, t05, show rM 56668397794435742564352 = 824633720832 by decide]; exact c0114_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 206, c0114_b11, by decide, by rw [tL, t05, show rM 113336795588871485128720 = 4504149651619840 by decide]; exact c0114_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0114_b12, by decide, by rw [tL, t05, show rM 170005193383307227693088 = 9007474669518848 by decide]; exact c0114_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0114_b13, by decide, by rw [tL, t05, show rM 226673591177742970257456 = 13510799687417856 by decide]; exact c0114_ok13⟩, ?_⟩
  simp

def s06 : List Nat := [9973638011820690691325952, 9676128923399903042863360, 5142657099845043637719040, 4840425644941386344042752, 306953821386526938898432, 4722366482869645222144]
theorem e06 : enumKeys 3075 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0109_b28, by decide, by rw [tL, t06, show rM 9973638011820690691325952 = 2267742732288 by decide]; exact c0109_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0109_b29, by decide, by rw [tL, t06, show rM 9676128923399903042863360 = 1128100003840000 by decide]; exact c0109_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 163, c0109_b30, by decide, by rw [tL, t06, show rM 5142657099845043637719040 = 18015567814328320 by decide]; exact c0109_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 159, c0109_b31, by decide, by rw [tL, t06, show rM 4840425644941386344042752 = 19141399001694208 by decide]; exact c0109_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 177, c0109_b32, by decide, by rw [tL, t06, show rM 306953821386526938898432 = 36028866812182528 by decide]; exact c0109_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0109_b33, by decide, by rw [tL, t06, show rM 4722366482869645222144 = 37154697999548416 by decide]; exact c0109_ok33⟩, ?_⟩
  simp

def s07 : List Nat := [623352375738793168207872, 609185276290184232566800, 1813388729421943762059280, 325843287318005519745280, 1530046740449765049237760, 1515879641001156113596688, 1232537652028977400775168, 1213648186097498819920400]
theorem e07 : enumKeys 3075 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0109_b34, by decide, by rw [tL, t07, show rM 623352375738793168207872 = 412316860416 by decide]; exact c0109_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0109_b38, by decide, by rw [tL, t07, show rM 609185276290184232566800 = 4503738140065792 by decide]; exact c0109_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0109_b39, by decide, by rw [tL, t07, show rM 1813388729421943762059280 = 4503741361291264 by decide]; exact c0109_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 223, c0109_b35, by decide, by rw [tL, t07, show rM 325843287318005519745280 = 1126244577968128 by decide]; exact c0109_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 218, c0109_b36, by decide, by rw [tL, t07, show rM 1530046740449765049237760 = 1126247799193600 by decide]; exact c0109_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 189, c0110_b0, by decide, by rw [tL, t07, show rM 1515879641001156113596688 = 5629573622398976 by decide]; exact c0110_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 177, c0109_b37, by decide, by rw [tL, t07, show rM 1232537652028977400775168 = 2252080060301312 by decide]; exact c0109_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 178, c0110_b1, by decide, by rw [tL, t07, show rM 1213648186097498819920400 = 6755404809764864 by decide]; exact c0110_ok1⟩, ?_⟩
  simp

def s08 : List Nat := [5156824199293652573356032, 5142657099845043637714960, 5213492597088088315920400, 4859315110872864924893440, 4930150608115909603098880, 4915983508667300667457808, 325843287318005519749120, 396678784561050197954560, 382511685112441262313488, 99169696140262549491968, 80280230208783968637200]
theorem e08 : enumKeys 3075 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0111_b7, by decide, by rw [tL, t08, show rM 5156824199293652573356032 = 1443109011456 by decide]; exact c0111_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 199, c0111_b11, by decide, by rw [tL, t08, show rM 5142657099845043637714960 = 4504768932216832 by decide]; exact c0111_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 198, c0111_b10, by decide, by rw [tL, t08, show rM 5213492597088088315920400 = 4504768126910464 by decide]; exact c0111_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 183, c0111_b9, by decide, by rw [tL, t08, show rM 4859315110872864924893440 = 1127275370119168 by decide]; exact c0111_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 197, c0111_b8, by decide, by rw [tL, t08, show rM 4930150608115909603098880 = 1127274564812800 by decide]; exact c0111_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0111_b12, by decide, by rw [tL, t08, show rM 4915983508667300667457808 = 5630600388018176 by decide]; exact c0111_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 203, c0111_b14, by decide, by rw [tL, t08, show rM 325843287318005519749120 = 18014743180607488 by decide]; exact c0111_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 210, c0111_b13, by decide, by rw [tL, t08, show rM 396678784561050197954560 = 18014742375301120 by decide]; exact c0111_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0111_b16, by decide, by rw [tL, t08, show rM 382511685112441262313488 = 22518068198506496 by decide]; exact c0111_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 171, c0111_b15, by decide, by rw [tL, t08, show rM 99169696140262549491968 = 19140574636408832 by decide]; exact c0111_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 170, c0111_b17, by decide, by rw [tL, t08, show rM 80280230208783968637200 = 23643899385872384 by decide]; exact c0111_ok17⟩, ?_⟩
  simp

def s09 : List Nat := [340010386766614455386112, 325843287318005519745040, 396678784561050197950480, 382511685112441262309408, 453347182355485940514848, 42501298345826806923520, 113336795588871485128960, 99169696140262549487888, 170005193383307227693328, 155838093934698292052256]
theorem e09 : enumKeys 3075 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 276, c0113_b0, by decide, by rw [tL, t09, show rM 340010386766614455386112 = 618475290624 by decide]; exact c0113_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 239, c0113_b4, by decide, by rw [tL, t09, show rM 325843287318005519745040 = 4503944298496000 by decide]; exact c0113_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 246, c0113_b3, by decide, by rw [tL, t09, show rM 396678784561050197950480 = 4503943493189632 by decide]; exact c0113_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 210, c0113_b8, by decide, by rw [tL, t09, show rM 382511685112441262309408 = 9007269316395008 by decide]; exact c0113_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0113_b7, by decide, by rw [tL, t09, show rM 453347182355485940514848 = 9007268511088640 by decide]; exact c0113_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0113_b2, by decide, by rw [tL, t09, show rM 42501298345826806923520 = 1126450736398336 by decide]; exact c0113_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 238, c0113_b1, by decide, by rw [tL, t09, show rM 113336795588871485128960 = 1126449931091968 by decide]; exact c0113_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 201, c0113_b6, by decide, by rw [tL, t09, show rM 99169696140262549487888 = 5629775754297344 by decide]; exact c0113_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 208, c0113_b5, by decide, by rw [tL, t09, show rM 170005193383307227693328 = 5629774948990976 by decide]; exact c0113_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 172, c0113_b9, by decide, by rw [tL, t09, show rM 155838093934698292052256 = 10133100772196352 by decide]; exact c0113_ok9⟩, ?_⟩
  simp

def s10 : List Nat := [5440166188265831286177792, 5142657099845043637715200, 4845148011424255989252608, 609185276290184232570880, 311676187869396584108288, 9444732965739290432000]
theorem e10 : enumKeys 3075 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0110_b10, by decide, by rw [tL, t10, show rM 5440166188265831286177792 = 1236950581248 by decide]; exact c0110_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 227, c0110_b11, by decide, by rw [tL, t10, show rM 5142657099845043637715200 = 1127069211688960 by decide]; exact c0110_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0110_b12, by decide, by rw [tL, t10, show rM 4845148011424255989252608 = 2252901472796672 by decide]; exact c0110_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 240, c0110_b13, by decide, by rw [tL, t10, show rM 609185276290184232570880 = 18014537022177280 by decide]; exact c0110_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0110_b14, by decide, by rw [tL, t10, show rM 311676187869396584108288 = 19140369283284992 by decide]; exact c0110_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0110_b15, by decide, by rw [tL, t10, show rM 9444732965739290432000 = 20266200470650880 by decide]; exact c0110_ok15⟩, ?_⟩
  simp

def s11 : List Nat := [623352375738793168207872, 609185276290184232566800, 680020773533228910772240, 325843287318005519745280, 396678784561050197950720, 311676187869396584104208, 382511685112441262309648, 28334198897217871282688, 99169696140262549488128, 85002596691653613847056]
theorem e11 : enumKeys 3075 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 312, c0111_b39, by decide, by rw [tL, t11, show rM 623352375738793168207872 = 412316860416 by decide]; exact c0111_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 276, c0112_b5, by decide, by rw [tL, t11, show rM 609185276290184232566800 = 4503738140065792 by decide]; exact c0112_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0112_b4, by decide, by rw [tL, t11, show rM 680020773533228910772240 = 4503737334759424 by decide]; exact c0112_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 271, c0112_b1, by decide, by rw [tL, t11, show rM 325843287318005519745280 = 1126244577968128 by decide]; exact c0112_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 274, c0112_b0, by decide, by rw [tL, t11, show rM 396678784561050197950720 = 1126243772661760 by decide]; exact c0112_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 234, c0112_b7, by decide, by rw [tL, t11, show rM 311676187869396584104208 = 5629570401173504 by decide]; exact c0112_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 238, c0112_b6, by decide, by rw [tL, t11, show rM 382511685112441262309648 = 5629569595867136 by decide]; exact c0112_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0112_b3, by decide, by rw [tL, t11, show rM 28334198897217871282688 = 2252076839075840 by decide]; exact c0112_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 233, c0112_b2, by decide, by rw [tL, t11, show rM 99169696140262549488128 = 2252076033769472 by decide]; exact c0112_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0112_b8, by decide, by rw [tL, t11, show rM 85002596691653613847056 = 6755401856974848 by decide]; exact c0112_ok8⟩, ?_⟩
  simp

def s12 : List Nat := [906694364710971881029632, 609185276290184232567040, 311676187869396584104448, 14167099448608935641856]
theorem e12 : enumKeys 3075 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0110_b21, by decide, by rw [tL, t12, show rM 906694364710971881029632 = 206158430208 by decide]; exact c0110_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 304, c0110_b22, by decide, by rw [tL, t12, show rM 609185276290184232567040 = 1126038419537920 by decide]; exact c0110_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0110_b23, by decide, by rw [tL, t12, show rM 311676187869396584104448 = 2251870680645632 by decide]; exact c0110_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0110_b24, by decide, by rw [tL, t12, show rM 14167099448608935641856 = 3377702941753344 by decide]; exact c0110_ok24⟩, ?_⟩
  simp

def s13 : List Nat := [10880332376531662572355585, 6044629098073145873534977, 1208925819614629174714369]
theorem e13 : enumKeys 3075 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 108, c0109_b18, by decide, by rw [tL, t13, show rM 10880332376531662572355585 = 283678294933504 by decide]; exact c0109_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 117, c0109_b19, by decide, by rw [tL, t13, show rM 6044629098073145873534977 = 18296977292787712 by decide]; exact c0109_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 128, c0109_b20, by decide, by rw [tL, t13, show rM 1208925819614629174714369 = 36310276290641920 by decide]; exact c0109_ok20⟩, ?_⟩
  simp

def s14 : List Nat := [1530046740449765049237505, 2720083094132915643088913, 2436741105160736930267393, 2417851639229258349412625]
theorem e14 : enumKeys 3075 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 170, c0109_b21, by decide, by rw [tL, t14, show rM 1530046740449765049237505 = 281822869061632 by decide]; exact c0109_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0109_b23, by decide, by rw [tL, t14, show rM 2720083094132915643088913 = 4785151913492480 by decide]; exact c0109_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 138, c0109_b22, by decide, by rw [tL, t14, show rM 2436741105160736930267393 = 1407658351394816 by decide]; exact c0109_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 140, c0109_b24, by decide, by rw [tL, t14, show rM 2417851639229258349412625 = 5910983100858368 by decide]; exact c0109_ok24⟩, ?_⟩
  simp

def s15 : List Nat := [4930150608115909603098625, 6063518564004624454385665, 6120186961799060196950033, 1303373149272022078984193, 1284483683340543498129425]
theorem e15 : enumKeys 3075 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 149, c0110_b39, by decide, by rw [tL, t15, show rM 4930150608115909603098625 = 282849634680832 by decide]; exact c0110_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 141, c0111_b0, by decide, by rw [tL, t15, show rM 6063518564004624454385665 = 282853661212672 by decide]; exact c0111_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 126, c0111_b1, by decide, by rw [tL, t15, show rM 6120186961799060196950033 = 4786178679111680 by decide]; exact c0111_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 129, c0111_b2, by decide, by rw [tL, t15, show rM 1303373149272022078984193 = 18296152927502336 by decide]; exact c0111_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 130, c0111_b3, by decide, by rw [tL, t15, show rM 1284483683340543498129425 = 22799477676965888 by decide]; exact c0111_ok3⟩, ?_⟩
  simp

def s16 : List Nat := [113336795588871485128705, 1246704751477586336415745, 170005193383307227693073, 1303373149272022078980113, 1360041547066457821544481]
theorem e16 : enumKeys 3075 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 190, c0112_b35, by decide, by rw [tL, t16, show rM 113336795588871485128705 = 282025000960000 by decide]; exact c0112_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 174, c0112_b36, by decide, by rw [tL, t16, show rM 1246704751477586336415745 = 282029027491840 by decide]; exact c0112_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 166, c0112_b37, by decide, by rw [tL, t16, show rM 170005193383307227693073 = 4785350018859008 by decide]; exact c0112_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 159, c0112_b38, by decide, by rw [tL, t16, show rM 1303373149272022078980113 = 4785354045390848 by decide]; exact c0112_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 132, c0112_b39, by decide, by rw [tL, t16, show rM 1360041547066457821544481 = 9288679063289856 by decide]; exact c0112_ok39⟩, ?_⟩
  simp

def s17 : List Nat := [5142657099845043637714945, 6346860552976803167207425, 6049351464556015518744833, 1515879641001156113600513, 1213648186097498819924225]
theorem e17 : enumKeys 3075 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 179, c0110_b2, by decide, by rw [tL, t17, show rM 5142657099845043637714945 = 282644281556992 by decide]; exact c0110_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 174, c0110_b3, by decide, by rw [tL, t17, show rM 6346860552976803167207425 = 282647502782464 by decide]; exact c0110_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 147, c0110_b4, by decide, by rw [tL, t17, show rM 6049351464556015518744833 = 1408479763890176 by decide]; exact c0110_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 159, c0110_b5, by decide, by rw [tL, t17, show rM 1515879641001156113600513 = 18295947574378496 by decide]; exact c0110_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 154, c0110_b6, by decide, by rw [tL, t17, show rM 1213648186097498819924225 = 19421778761744384 by decide]; exact c0110_ok6⟩, ?_⟩
  simp

def s18 : List Nat := [9676128923399903042863105, 9746964420642947721068545, 4915983508667300667461633, 80280230208783968641025]
theorem e18 : enumKeys 3075 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0111_b19, by decide, by rw [tL, t18, show rM 9676128923399903042863105 = 283675073708032 by decide]; exact c0111_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 156, c0111_b18, by decide, by rw [tL, t18, show rM 9746964420642947721068545 = 283674268401664 by decide]; exact c0111_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 138, c0111_b20, by decide, by rw [tL, t18, show rM 4915983508667300667461633 = 18296974339997696 by decide]; exact c0111_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 146, c0111_b21, by decide, by rw [tL, t18, show rM 80280230208783968641025 = 36310273337851904 by decide]; exact c0111_ok21⟩, ?_⟩
  simp

def s19 : List Nat := [325843287318005519745025, 396678784561050197950465, 1530046740449765049237505, 382511685112441262309393, 1515879641001156113596433, 1586715138244200791801873, 99169696140262549487873, 1232537652028977400774913, 1303373149272022078980353, 1289206049823413143339281]
theorem e19 : enumKeys 3075 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 223, c0111_b23, by decide, by rw [tL, t19, show rM 325843287318005519745025 = 281819647836160 by decide]; exact c0111_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 226, c0111_b22, by decide, by rw [tL, t19, show rM 396678784561050197950465 = 281818842529792 by decide]; exact c0111_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 218, c0111_b24, by decide, by rw [tL, t19, show rM 1530046740449765049237505 = 281822869061632 by decide]; exact c0111_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0111_b28, by decide, by rw [tL, t19, show rM 382511685112441262309393 = 4785144665735168 by decide]; exact c0111_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 189, c0111_b30, by decide, by rw [tL, t19, show rM 1515879641001156113596433 = 4785148692267008 by decide]; exact c0111_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0111_b29, by decide, by rw [tL, t19, show rM 1586715138244200791801873 = 4785147886960640 by decide]; exact c0111_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 191, c0111_b25, by decide, by rw [tL, t19, show rM 99169696140262549487873 = 1407651103637504 by decide]; exact c0111_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 177, c0111_b27, by decide, by rw [tL, t19, show rM 1232537652028977400774913 = 1407655130169344 by decide]; exact c0111_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 187, c0111_b26, by decide, by rw [tL, t19, show rM 1303373149272022078980353 = 1407654324862976 by decide]; exact c0111_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 158, c0111_b31, by decide, by rw [tL, t19, show rM 1289206049823413143339281 = 5910980148068352 by decide]; exact c0111_ok31⟩, ?_⟩
  simp

def s20 : List Nat := [4859315110872864924893185, 4930150608115909603098625, 4915983508667300667457553, 4986819005910345345662993, 99169696140262549491713, 170005193383307227697153, 155838093934698292056081]
theorem e20 : enumKeys 3075 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 183, c0113_b11, by decide, by rw [tL, t20, show rM 4859315110872864924893185 = 282850439987200 by decide]; exact c0113_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 197, c0113_b10, by decide, by rw [tL, t20, show rM 4930150608115909603098625 = 282849634680832 by decide]; exact c0113_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0113_b13, by decide, by rw [tL, t20, show rM 4915983508667300667457553 = 4786175457886208 by decide]; exact c0113_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0113_b12, by decide, by rw [tL, t20, show rM 4986819005910345345662993 = 4786174652579840 by decide]; exact c0113_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 171, c0113_b15, by decide, by rw [tL, t20, show rM 99169696140262549491713 = 18296149706276864 by decide]; exact c0113_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 178, c0113_b14, by decide, by rw [tL, t20, show rM 170005193383307227697153 = 18296148900970496 by decide]; exact c0113_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 148, c0113_b16, by decide, by rw [tL, t20, show rM 155838093934698292056081 = 22799474724175872 by decide]; exact c0113_ok16⟩, ?_⟩
  simp

def s21 : List Nat := [42501298345826806923265, 113336795588871485128705, 99169696140262549487633, 170005193383307227693073, 155838093934698292052001, 226673591177742970257441]
theorem e21 : enumKeys 3075 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b15, by decide, by rw [tL, t21, show rM 42501298345826806923265 = 282025806266368 by decide]; exact c0114_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 238, c0114_b14, by decide, by rw [tL, t21, show rM 113336795588871485128705 = 282025000960000 by decide]; exact c0114_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 201, c0114_b17, by decide, by rw [tL, t21, show rM 99169696140262549487633 = 4785350824165376 by decide]; exact c0114_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 208, c0114_b16, by decide, by rw [tL, t21, show rM 170005193383307227693073 = 4785350018859008 by decide]; exact c0114_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 172, c0114_b19, by decide, by rw [tL, t21, show rM 155838093934698292052001 = 9288675842064384 by decide]; exact c0114_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0114_b18, by decide, by rw [tL, t21, show rM 226673591177742970257441 = 9288675036758016 by decide]; exact c0114_ok18⟩, ?_⟩
  simp

def s22 : List Nat := [609185276290184232566785, 1813388729421943762059265, 311676187869396584104193, 1515879641001156113596673, 1218370552580368465134081]
theorem e22 : enumKeys 3075 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 256, c0110_b16, by decide, by rw [tL, t22, show rM 609185276290184232566785 = 281613489405952 by decide]; exact c0110_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 240, c0110_b17, by decide, by rw [tL, t22, show rM 1813388729421943762059265 = 281616710631424 by decide]; exact c0110_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 224, c0110_b18, by decide, by rw [tL, t22, show rM 311676187869396584104193 = 1407445750513664 by decide]; exact c0110_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 217, c0110_b19, by decide, by rw [tL, t22, show rM 1515879641001156113596673 = 1407448971739136 by decide]; exact c0110_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0110_b20, by decide, by rw [tL, t22, show rM 1218370552580368465134081 = 2533281232846848 by decide]; exact c0110_ok20⟩, ?_⟩
  simp

def s23 : List Nat := [5142657099845043637714945, 5213492597088088315920385, 4845148011424255989252353, 4915983508667300667457793, 311676187869396584108033, 382511685112441262313473, 85002596691653613850881]
theorem e23 : enumKeys 3075 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 227, c0112_b10, by decide, by rw [tL, t23, show rM 5142657099845043637714945 = 282644281556992 by decide]; exact c0112_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0112_b9, by decide, by rw [tL, t23, show rM 5213492597088088315920385 = 282643476250624 by decide]; exact c0112_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0112_b12, by decide, by rw [tL, t23, show rM 4845148011424255989252353 = 1408476542664704 by decide]; exact c0112_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0112_b11, by decide, by rw [tL, t23, show rM 4915983508667300667457793 = 1408475737358336 by decide]; exact c0112_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0112_b14, by decide, by rw [tL, t23, show rM 311676187869396584108033 = 18295944353153024 by decide]; exact c0112_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 208, c0112_b13, by decide, by rw [tL, t23, show rM 382511685112441262313473 = 18295943547846656 by decide]; exact c0112_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 172, c0112_b15, by decide, by rw [tL, t23, show rM 85002596691653613850881 = 19421775808954368 by decide]; exact c0112_ok15⟩, ?_⟩
  simp

def s24 : List Nat := [325843287318005519745025, 396678784561050197950465, 311676187869396584103953, 382511685112441262309393, 453347182355485940514833, 28334198897217871282433, 99169696140262549487873, 170005193383307227693313, 85002596691653613846801, 155838093934698292052241]
theorem e24 : enumKeys 3075 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 271, c0113_b25, by decide, by rw [tL, t24, show rM 325843287318005519745025 = 281819647836160 by decide]; exact c0113_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 274, c0113_b24, by decide, by rw [tL, t24, show rM 396678784561050197950465 = 281818842529792 by decide]; exact c0113_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 234, c0113_b31, by decide, by rw [tL, t24, show rM 311676187869396584103953 = 4785145471041536 by decide]; exact c0113_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 238, c0113_b30, by decide, by rw [tL, t24, show rM 382511685112441262309393 = 4785144665735168 by decide]; exact c0113_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0113_b29, by decide, by rw [tL, t24, show rM 453347182355485940514833 = 4785143860428800 by decide]; exact c0113_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0113_b28, by decide, by rw [tL, t24, show rM 28334198897217871282433 = 1407651908943872 by decide]; exact c0113_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 233, c0113_b27, by decide, by rw [tL, t24, show rM 99169696140262549487873 = 1407651103637504 by decide]; exact c0113_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0113_b26, by decide, by rw [tL, t24, show rM 170005193383307227693313 = 1407650298331136 by decide]; exact c0113_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0113_b33, by decide, by rw [tL, t24, show rM 85002596691653613846801 = 5910976926842880 by decide]; exact c0113_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 200, c0113_b32, by decide, by rw [tL, t24, show rM 155838093934698292052241 = 5910976121536512 by decide]; exact c0113_ok32⟩, ?_⟩
  simp

def s25 : List Nat := [609185276290184232566785, 680020773533228910772225, 311676187869396584104193, 382511685112441262309633, 14167099448608935641601, 85002596691653613847041]
theorem e25 : enumKeys 3075 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 304, c0112_b24, by decide, by rw [tL, t25, show rM 609185276290184232566785 = 281613489405952 by decide]; exact c0112_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0112_b23, by decide, by rw [tL, t25, show rM 680020773533228910772225 = 281612684099584 by decide]; exact c0112_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0112_b26, by decide, by rw [tL, t25, show rM 311676187869396584104193 = 1407445750513664 by decide]; exact c0112_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0112_b25, by decide, by rw [tL, t25, show rM 382511685112441262309633 = 1407444945207296 by decide]; exact c0112_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0112_b28, by decide, by rw [tL, t25, show rM 14167099448608935641601 = 2533278011621376 by decide]; exact c0112_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0112_b27, by decide, by rw [tL, t25, show rM 85002596691653613847041 = 2533277206315008 by decide]; exact c0112_ok27⟩, ?_⟩
  simp

def s26 : List Nat := [7253554917687775048237058, 2417851639229258349416450]
theorem e26 : enumKeys 3075 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 108, c0109_b25, by decide, by rw [tL, t26, show rM 7253554917687775048237058 = 564058054983680 by decide]; exact c0109_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 116, c0109_b26, by decide, by rw [tL, t26, show rM 2417851639229258349416450 = 18577357052837888 by decide]; exact c0109_ok26⟩, ?_⟩
  simp

def s27 : List Nat := [1303373149272022078980098, 2436741105160736930267138, 2493409502955172672831506]
theorem e27 : enumKeys 3075 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 145, c0111_b4, by decide, by rw [tL, t27, show rM 1303373149272022078980098 = 563229394731008 by decide]; exact c0111_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 138, c0111_b5, by decide, by rw [tL, t27, show rM 2436741105160736930267138 = 563233421262848 by decide]; exact c0111_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 120, c0111_b6, by decide, by rw [tL, t27, show rM 2493409502955172672831506 = 5066558439161856 by decide]; exact c0111_ok6⟩, ?_⟩
  simp

def s28 : List Nat := [1515879641001156113596418, 2720083094132915643088898, 2422574005712127994626306]
theorem e28 : enumKeys 3075 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 175, c0110_b7, by decide, by rw [tL, t28, show rM 1515879641001156113596418 = 563024041607168 by decide]; exact c0110_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 168, c0110_b8, by decide, by rw [tL, t28, show rM 2720083094132915643088898 = 563027262832640 by decide]; exact c0110_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0110_b9, by decide, by rw [tL, t28, show rM 2422574005712127994626306 = 1688859523940352 by decide]; exact c0110_ok9⟩, ?_⟩
  simp

def s29 : List Nat := [4915983508667300667457538, 6049351464556015518744578, 6120186961799060196950018, 1289206049823413143343106]
theorem e29 : enumKeys 3075 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 154, c0111_b32, by decide, by rw [tL, t29, show rM 4915983508667300667457538 = 564050807226368 by decide]; exact c0111_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 147, c0111_b34, by decide, by rw [tL, t29, show rM 6049351464556015518744578 = 564054833758208 by decide]; exact c0111_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0111_b33, by decide, by rw [tL, t29, show rM 6120186961799060196950018 = 564054028451840 by decide]; exact c0111_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 134, c0111_b35, by decide, by rw [tL, t29, show rM 1289206049823413143343106 = 18577354100047872 by decide]; exact c0111_ok35⟩, ?_⟩
  simp

def s30 : List Nat := [99169696140262549487618, 170005193383307227693058, 1232537652028977400774658, 1303373149272022078980098, 155838093934698292051986, 1289206049823413143339026, 1360041547066457821544466]
theorem e30 : enumKeys 3075 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 191, c0113_b18, by decide, by rw [tL, t30, show rM 99169696140262549487618 = 563226173505536 by decide]; exact c0113_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 194, c0113_b17, by decide, by rw [tL, t30, show rM 170005193383307227693058 = 563225368199168 by decide]; exact c0113_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 177, c0113_b20, by decide, by rw [tL, t30, show rM 1232537652028977400774658 = 563230200037376 by decide]; exact c0113_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 187, c0113_b19, by decide, by rw [tL, t30, show rM 1303373149272022078980098 = 563229394731008 by decide]; exact c0113_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 164, c0113_b21, by decide, by rw [tL, t30, show rM 155838093934698292051986 = 5066551191404544 by decide]; exact c0113_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 158, c0113_b23, by decide, by rw [tL, t30, show rM 1289206049823413143339026 = 5066555217936384 by decide]; exact c0113_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 156, c0113_b22, by decide, by rw [tL, t30, show rM 1360041547066457821544466 = 5066554412630016 by decide]; exact c0113_ok22⟩, ?_⟩
  simp

def s31 : List Nat := [311676187869396584103938, 382511685112441262309378, 1515879641001156113596418, 1586715138244200791801858, 85002596691653613846786, 1218370552580368465133826, 1289206049823413143339266]
theorem e31 : enumKeys 3075 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 224, c0112_b17, by decide, by rw [tL, t31, show rM 311676187869396584103938 = 563020820381696 by decide]; exact c0112_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 224, c0112_b16, by decide, by rw [tL, t31, show rM 382511685112441262309378 = 563020015075328 by decide]; exact c0112_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 217, c0112_b19, by decide, by rw [tL, t31, show rM 1515879641001156113596418 = 563024041607168 by decide]; exact c0112_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 210, c0112_b18, by decide, by rw [tL, t31, show rM 1586715138244200791801858 = 563023236300800 by decide]; exact c0112_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0112_b20, by decide, by rw [tL, t31, show rM 85002596691653613846786 = 1688852276183040 by decide]; exact c0112_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0112_b22, by decide, by rw [tL, t31, show rM 1218370552580368465133826 = 1688856302714880 by decide]; exact c0112_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0112_b21, by decide, by rw [tL, t31, show rM 1289206049823413143339266 = 1688855497408512 by decide]; exact c0112_ok21⟩, ?_⟩
  simp

def s32 : List Nat := [4845148011424255989252098, 4915983508667300667457538, 4986819005910345345662978, 85002596691653613850626, 155838093934698292056066]
theorem e32 : enumKeys 3075 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0113_b36, by decide, by rw [tL, t32, show rM 4845148011424255989252098 = 564051612532736 by decide]; exact c0113_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0113_b35, by decide, by rw [tL, t32, show rM 4915983508667300667457538 = 564050807226368 by decide]; exact c0113_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0113_b34, by decide, by rw [tL, t32, show rM 4986819005910345345662978 = 564050001920000 by decide]; exact c0113_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 172, c0113_b38, by decide, by rw [tL, t32, show rM 85002596691653613850626 = 18577350878822400 by decide]; exact c0113_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 176, c0113_b37, by decide, by rw [tL, t32, show rM 155838093934698292056066 = 18577350073516032 by decide]; exact c0113_ok37⟩, ?_⟩
  simp

def s33 : List Nat := [28334198897217871282178, 99169696140262549487618, 170005193383307227693058, 85002596691653613846546, 155838093934698292051986, 226673591177742970257426]
theorem e33 : enumKeys 3075 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b22, by decide, by rw [tL, t33, show rM 28334198897217871282178 = 563226978811904 by decide]; exact c0114_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 233, c0114_b21, by decide, by rw [tL, t33, show rM 99169696140262549487618 = 563226173505536 by decide]; exact c0114_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0114_b20, by decide, by rw [tL, t33, show rM 170005193383307227693058 = 563225368199168 by decide]; exact c0114_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 196, c0114_b25, by decide, by rw [tL, t33, show rM 85002596691653613846546 = 5066551996710912 by decide]; exact c0114_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 200, c0114_b24, by decide, by rw [tL, t33, show rM 155838093934698292051986 = 5066551191404544 by decide]; exact c0114_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0114_b23, by decide, by rw [tL, t33, show rM 226673591177742970257426 = 5066550386098176 by decide]; exact c0114_ok23⟩, ?_⟩
  simp

def s34 : List Nat := [311676187869396584103938, 382511685112441262309378, 453347182355485940514818, 14167099448608935641346, 85002596691653613846786, 155838093934698292052226]
theorem e34 : enumKeys 3075 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0114_b6, by decide, by rw [tL, t34, show rM 311676187869396584103938 = 563020820381696 by decide]; exact c0114_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0114_b5, by decide, by rw [tL, t34, show rM 382511685112441262309378 = 563020015075328 by decide]; exact c0114_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0114_b4, by decide, by rw [tL, t34, show rM 453347182355485940514818 = 563019209768960 by decide]; exact c0114_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b9, by decide, by rw [tL, t34, show rM 14167099448608935641346 = 1688853081489408 by decide]; exact c0114_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0114_b8, by decide, by rw [tL, t34, show rM 85002596691653613846786 = 1688852276183040 by decide]; exact c0114_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0114_b7, by decide, by rw [tL, t34, show rM 155838093934698292052226 = 1688851470876672 by decide]; exact c0114_ok7⟩, ?_⟩
  simp

def s35 : List Nat := [3626777458843887524118531]
theorem e35 : enumKeys 3075 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 108, c0109_b27, by decide, by rw [tL, show rM 3626777458843887524118531 = 844437815033856 by decide]; exact c0109_ok27⟩, ?_⟩
  simp

def s36 : List Nat := [1289206049823413143339011, 2422574005712127994626051, 2493409502955172672831491]
theorem e36 : enumKeys 3075 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 150, c0111_b36, by decide, by rw [tL, t36, show rM 1289206049823413143339011 = 844430567276544 by decide]; exact c0111_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0111_b38, by decide, by rw [tL, t36, show rM 2422574005712127994626051 = 844434593808384 by decide]; exact c0111_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 144, c0111_b37, by decide, by rw [tL, t36, show rM 2493409502955172672831491 = 844433788502016 by decide]; exact c0111_ok37⟩, ?_⟩
  simp

def s37 : List Nat := [85002596691653613846531, 155838093934698292051971, 1218370552580368465133571, 1289206049823413143339011, 1360041547066457821544451]
theorem e37 : enumKeys 3075 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0114_b0, by decide, by rw [tL, t37, show rM 85002596691653613846531 = 844427346051072 by decide]; exact c0114_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 192, c0113_b39, by decide, by rw [tL, t37, show rM 155838093934698292051971 = 844426540744704 by decide]; exact c0113_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0114_b3, by decide, by rw [tL, t37, show rM 1218370552580368465133571 = 844431372582912 by decide]; exact c0114_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 186, c0114_b2, by decide, by rw [tL, t37, show rM 1289206049823413143339011 = 844430567276544 by decide]; exact c0114_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 180, c0114_b1, by decide, by rw [tL, t37, show rM 1360041547066457821544451 = 844429761970176 by decide]; exact c0114_ok1⟩, ?_⟩
  simp

def s38 : List Nat := [14167099448608935641091, 85002596691653613846531, 155838093934698292051971, 226673591177742970257411]
theorem e38 : enumKeys 3075 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b29, by decide, by rw [tL, t38, show rM 14167099448608935641091 = 844428151357440 by decide]; exact c0114_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0114_b28, by decide, by rw [tL, t38, show rM 85002596691653613846531 = 844427346051072 by decide]; exact c0114_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0114_b27, by decide, by rw [tL, t38, show rM 155838093934698292051971 = 844426540744704 by decide]; exact c0114_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0114_b26, by decide, by rw [tL, t38, show rM 226673591177742970257411 = 844425735438336 by decide]; exact c0114_ok26⟩, ?_⟩
  simp

/-- every enumerated key with left type `3075` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 3075 mR,
    (3075 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 3075 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 3075) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K35
end Grid3.Three.Cert
