import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4196
import Grid3.Three.Cert.Data.C4197
import Grid3.Three.Cert.Data.C4198
import Grid3.Three.Cert.Data.C4199
import Grid3.Three.Cert.Data.C4200
import Grid3.Three.Cert.Data.C4201
import Grid3.Three.Cert.Data.C4202
import Grid3.Three.Cert.Data.C4203
import Grid3.Three.Cert.Data.C4204
import Grid3.Three.Cert.Data.C4205
import Grid3.Three.Cert.Data.C4206
import Grid3.Three.Cert.Data.C4207
import Grid3.Three.Cert.Data.C4208
import Grid3.Three.Cert.Data.C4209
import Grid3.Three.Cert.Data.C4210
import Grid3.Three.Cert.Data.C4211
import Grid3.Three.Cert.Data.C4212
import Grid3.Three.Cert.Data.C4213
import Grid3.Three.Cert.Data.C4214
import Grid3.Three.Cert.Data.C4215
import Grid3.Three.Cert.Data.C4216
import Grid3.Three.Cert.Data.C4217
import Grid3.Three.Cert.Data.C4218
import Grid3.Three.Cert.Data.C4219
import Grid3.Three.Cert.Data.C4220
import Grid3.Three.Cert.Data.C4221
import Grid3.Three.Cert.Data.C4222
import Grid3.Three.Cert.Data.C4223
import Grid3.Three.Cert.Data.C4224
import Grid3.Three.Cert.Data.C4225
import Grid3.Three.Cert.Data.C4226
import Grid3.Three.Cert.Data.C4227
import Grid3.Three.Cert.Data.C4228
import Grid3.Three.Cert.Data.C4229
import Grid3.Three.Cert.Data.C4230
import Grid3.Three.Cert.Data.C4231
import Grid3.Three.Cert.Data.C4232
import Grid3.Three.Cert.Data.C4233
import Grid3.Three.Cert.Data.C4234
import Grid3.Three.Cert.Data.C4235
import Grid3.Three.Cert.Data.C4236
import Grid3.Three.Cert.Data.C4237
import Grid3.Three.Cert.Data.C4238
import Grid3.Three.Cert.Data.C4239
import Grid3.Three.Cert.Data.C4240
import Grid3.Three.Cert.Data.C4241
import Grid3.Three.Cert.Data.C4242
import Grid3.Three.Cert.Data.C4243
import Grid3.Three.Cert.Data.C4244
import Grid3.Three.Cert.Data.C4245
import Grid3.Three.Cert.Data.C4246
import Grid3.Three.Cert.Data.C4247
import Grid3.Three.Cert.Data.C4248
import Grid3.Three.Cert.Data.C4249
import Grid3.Three.Cert.Data.C4250
import Grid3.Three.Cert.Data.C4251
import Grid3.Three.Cert.Data.C4252
import Grid3.Three.Cert.Data.C4253
import Grid3.Three.Cert.Data.C4254
import Grid3.Three.Cert.Data.C4255
import Grid3.Three.Cert.Data.C4256
import Grid3.Three.Cert.Data.C4257
import Grid3.Three.Cert.Data.C4258
import Grid3.Three.Cert.Data.C4259
import Grid3.Three.Cert.Data.C4260
import Grid3.Three.Cert.Data.C4261
import Grid3.Three.Cert.Data.C4262
import Grid3.Three.Cert.Data.C4263
import Grid3.Three.Cert.Data.C4264
import Grid3.Three.Cert.Data.C4265
import Grid3.Three.Cert.Data.C4266
import Grid3.Three.Cert.Data.C4267
import Grid3.Three.Cert.Data.C4268
import Grid3.Three.Cert.Data.C4269

/-! Seam keys with left type `2119` (type index 36): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K36

def s00 : List Nat := [9671406574931431907131392, 9671406556917033464758272, 4835703296472915275415552, 9671406556917033397653504, 4835703296472915208310784, 4835703278458516765937664, 18014398576594944, 4835703278458516698832896, 18014398509490176, 67117056, 12288]
theorem e00 : enumKeys 2119 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c4196_b5, by decide, c4196_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 144, c4196_b6, by decide, c4196_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c4196_b7, by decide, c4196_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 150, c4196_b8, by decide, c4196_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 154, c4196_b9, by decide, c4196_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 157, c4197_b0, by decide, c4197_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c4197_b1, by decide, c4197_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 160, c4197_b2, by decide, c4197_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 166, c4197_b3, by decide, c4197_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 172, c4197_b4, by decide, c4197_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 168, c4197_b5, by decide, c4197_ok5⟩, ?_⟩
  simp

def s01 : List Nat := [6044629099199045780635648, 5137934737865773620133888, 1511157292532684978126848, 4854592745515895203299328, 321120938849534400790528, 1227815286672007729512448, 321120925338735569010688, 6044629099199045780373520, 5137934737865773619871760, 1511157292532684977864720, 5137934733362174009278480, 4835703279584416622444560, 302231472918055819935760, 1511157274518286535491600, 1208925820740529148657680, 302231459407256988155920, 4854592748893594907050240, 1227815303560506265043200, 6044629098073145873793280, 4835703282962116326457600, 1208925837629027684450560, 4854592744389995296456960, 18889483945877107114240, 1227815285546107822670080, 18889470435078275334400, 6044629098073145873531152, 4835703282962116326195472, 1208925837629027684188432, 4835703278458516715602192, 18014398526259472, 1208925819614629241815312, 4503599694479632, 1227815286672007662407680, 321120925338735501905920, 1511157274518286468648960, 1208925820740529081815040, 302231459407256921313280, 321120920835135891312640, 18889467057378504478720, 1511157274518286468386832, 1208925820740529081552912, 302231459407256921051152, 302231454903657310457872, 1125899923623952, 1227815285546107755565312, 18889470435078208229632, 1208925819614629174972672, 4503599627636992, 18889465931478597636352, 1208925819614629174710544, 4503599627374864, 16781584]
theorem e01 : enumKeys 2119 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c4198_b2, by decide, c4198_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4198_b1, by decide, c4198_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4198_b0, by decide, c4198_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c4197_b9, by decide, c4197_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4197_b8, by decide, c4197_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4197_b7, by decide, c4197_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4197_b6, by decide, c4197_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4200_b6, by decide, c4200_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4200_b5, by decide, c4200_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4200_b4, by decide, c4200_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4201_b0, by decide, c4201_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4201_b2, by decide, c4201_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4201_b1, by decide, c4201_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4200_b7, by decide, c4200_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4200_b9, by decide, c4200_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4200_b8, by decide, c4200_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4199_b1, by decide, c4199_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4199_b0, by decide, c4199_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4199_b6, by decide, c4199_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4199_b8, by decide, c4199_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4199_b7, by decide, c4199_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4199_b4, by decide, c4199_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4199_b5, by decide, c4199_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4199_b2, by decide, c4199_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4199_b3, by decide, c4199_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4201_b8, by decide, c4201_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4202_b0, by decide, c4202_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4201_b9, by decide, c4201_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4202_b3, by decide, c4202_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4202_b4, by decide, c4202_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4202_b1, by decide, c4202_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4202_b2, by decide, c4202_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4198_b4, by decide, c4198_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4198_b3, by decide, c4198_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4198_b7, by decide, c4198_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c4198_b9, by decide, c4198_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4198_b8, by decide, c4198_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4198_b5, by decide, c4198_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4198_b6, by decide, c4198_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4201_b3, by decide, c4201_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4201_b5, by decide, c4201_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4201_b4, by decide, c4201_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4201_b6, by decide, c4201_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4201_b7, by decide, c4201_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4199_b9, by decide, c4199_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4200_b0, by decide, c4200_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4200_b2, by decide, c4200_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4200_b3, by decide, c4200_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4200_b1, by decide, c4200_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4202_b5, by decide, c4202_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4202_b6, by decide, c4202_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4202_b7, by decide, c4202_ok7⟩, ?_⟩
  simp

def s02 : List Nat := [4854592762404393789161472, 9671406557198508374622208, 4911261160198829531987968, 4854592744671470323499008, 94447347671791480864768, 9671406557198508374360080, 4911261160198829531725840, 4911261142184431089352720, 4835703278739991742644240, 75557881740312900010000, 4854592744671470256394240, 94447347671791413760000, 4911261142184431022510080, 4835703278739991675801600, 75557881740312833167360, 94447329657392971386880, 18889466212953624678400, 4911261142184431022247952, 4835703278739991675539472, 75557881740312832905232, 75557863725914390532112, 281475043823632, 94447329657392904282112, 18889466212953557573632, 75557863725914323689472, 281474976980992, 75557863725914323427344, 281474976718864]
theorem e02 : enumKeys 2119 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4202_b8, by decide, c4202_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c4203_b2, by decide, c4203_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4203_b1, by decide, c4203_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4203_b0, by decide, c4203_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4202_b9, by decide, c4202_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4204_b5, by decide, c4204_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4204_b4, by decide, c4204_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4204_b6, by decide, c4204_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4204_b8, by decide, c4204_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4204_b7, by decide, c4204_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4203_b4, by decide, c4203_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4203_b3, by decide, c4203_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c4203_b7, by decide, c4203_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c4203_b9, by decide, c4203_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4203_b8, by decide, c4203_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4203_b5, by decide, c4203_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4203_b6, by decide, c4203_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4204_b9, by decide, c4204_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 157, c4205_b1, by decide, c4205_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4205_b0, by decide, c4205_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4205_b2, by decide, c4205_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4205_b3, by decide, c4205_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4204_b0, by decide, c4204_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4204_b1, by decide, c4204_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4204_b2, by decide, c4204_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4204_b3, by decide, c4204_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4205_b4, by decide, c4205_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4205_b5, by decide, c4205_ok5⟩, ?_⟩
  simp

def s03 : List Nat := [321120921116610851504128, 94447330783292811378688, 1227815286672007662665728, 321120925338735502163968, 37778932988857085329408, 1227815286672007662403600, 321120925338735501901840, 1511157274799761445355536, 1284483684466443405230096, 377789323133171244728336, 321120921116610868019216, 94447330783292827893776, 1511157274799761445093408, 1284483684466443404967968, 377789323133171244466208, 377789318629571633872928, 302231455185132287164448, 75557864851814247039008, 37778936366556789080320, 1227815285827582732534016, 94447334160992531906816, 37778932144432155197696, 1227815285827582732271888, 94447334160992531644688, 1284483683340543498387728, 1208925819896104151679248, 75557868229513951052048, 94447329657392921051408, 18889466212953574342928, 1284483683340543498125600, 1208925819896104151417120, 75557868229513950789920, 75557863725914340196640, 281474993488160]
theorem e03 : enumKeys 2119 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4206_b0, by decide, c4206_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4205_b9, by decide, c4205_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4205_b8, by decide, c4205_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4205_b7, by decide, c4205_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4205_b6, by decide, c4205_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4206_b6, by decide, c4206_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4206_b5, by decide, c4206_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4207_b1, by decide, c4207_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4207_b0, by decide, c4207_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4206_b9, by decide, c4206_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4206_b8, by decide, c4206_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4206_b7, by decide, c4206_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4208_b1, by decide, c4208_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4208_b0, by decide, c4208_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4207_b9, by decide, c4207_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4208_b2, by decide, c4208_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4208_b4, by decide, c4208_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4208_b3, by decide, c4208_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4206_b1, by decide, c4206_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4206_b4, by decide, c4206_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4206_b3, by decide, c4206_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4206_b2, by decide, c4206_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4207_b3, by decide, c4207_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4207_b2, by decide, c4207_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4207_b6, by decide, c4207_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4207_b8, by decide, c4207_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4207_b7, by decide, c4207_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4207_b4, by decide, c4207_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4207_b5, by decide, c4207_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4208_b5, by decide, c4208_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4208_b7, by decide, c4208_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4208_b6, by decide, c4208_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4208_b8, by decide, c4208_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4208_b9, by decide, c4208_ok9⟩, ?_⟩
  simp

def s04 : List Nat := [37778949877355671191552, 4854592744671470256652288, 94447347671791414018048, 37778932144432205529088, 4854592744671470256390160, 94447347671791413755920, 4911261142465905999216656, 151115745466227156582416, 94447329938867948093456, 4911261142465905998954528, 151115745466227156320288, 151115727451828713947168, 75557864007389367238688, 37778932144432138424320, 94447329938867881250816, 94447329938867880988688, 151115727451828647104528, 75557864007389300396048, 151115727451828646842400, 75557864007389300133920]
theorem e04 : enumKeys 2119 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4209_b0, by decide, c4209_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4209_b3, by decide, c4209_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4209_b2, by decide, c4209_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4209_b1, by decide, c4209_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4209_b7, by decide, c4209_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4209_b6, by decide, c4209_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4210_b0, by decide, c4210_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4209_b9, by decide, c4209_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4209_b8, by decide, c4209_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4210_b5, by decide, c4210_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4210_b4, by decide, c4210_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4210_b6, by decide, c4210_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4210_b7, by decide, c4210_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4209_b4, by decide, c4209_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4209_b5, by decide, c4209_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4210_b1, by decide, c4210_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4210_b2, by decide, c4210_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4210_b3, by decide, c4210_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4210_b8, by decide, c4210_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4210_b9, by decide, c4210_ok9⟩, ?_⟩
  simp

def s05 : List Nat := [37778932144432138682368, 37778932144432138420240, 94447329938867881246736, 94447329938867880984608, 151115727733303623811104, 151115727733303623548976]
theorem e05 : enumKeys 2119 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4211_b0, by decide, c4211_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4211_b1, by decide, c4211_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4211_b2, by decide, c4211_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4211_b3, by decide, c4211_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4211_b4, by decide, c4211_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4211_b5, by decide, c4211_ok5⟩, ?_⟩
  simp

def s06 : List Nat := [9671406558042933304557568, 5137934751376572502048768, 5137934733362174059610112, 4840425646067286317989888, 306953839400925515481088, 4840425662955784853520640, 9671406556917033397715200, 4835703296472915208372480, 4840425644941386411147520, 4722384497268221804800, 4840425646067286250885120, 306953839400925448376320, 5137934733362173992570880, 4835703279584416605736960, 302231472918055803228160, 306953821386527006003200, 4722367608769619169280, 4840425644941386344042752, 4722384497268154700032, 4835703278458516698894592, 18014398509551872, 4722366482869712326912, 306953821386526938898432, 4722367608769552064512, 302231454903657293750272, 1125899906916352, 4722366482869645222144, 73984]
theorem e06 : enumKeys 2119 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4212_b0, by decide, c4212_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4211_b9, by decide, c4211_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4211_b6, by decide, c4211_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4211_b8, by decide, c4211_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4211_b7, by decide, c4211_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4213_b2, by decide, c4213_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4213_b5, by decide, c4213_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4213_b6, by decide, c4213_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4213_b3, by decide, c4213_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4213_b4, by decide, c4213_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4212_b2, by decide, c4212_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4212_b1, by decide, c4212_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4212_b5, by decide, c4212_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4212_b7, by decide, c4212_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4212_b6, by decide, c4212_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4212_b3, by decide, c4212_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4212_b4, by decide, c4212_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4213_b7, by decide, c4213_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4213_b8, by decide, c4213_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4214_b0, by decide, c4214_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4214_b1, by decide, c4214_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4213_b9, by decide, c4213_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4212_b8, by decide, c4212_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4212_b9, by decide, c4212_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4213_b0, by decide, c4213_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4213_b1, by decide, c4213_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4214_b2, by decide, c4214_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4214_b3, by decide, c4214_ok3⟩, ?_⟩
  simp

def s07 : List Nat := [321120921961035781439488, 306953822512426845995008, 1511157275644186375487488, 604462914310914214985728, 321120921961035798151168, 1511157275644186375290896, 604462914310914214789136, 604462909807314604130320, 306953822512426862510096, 1227815286672007662469376, 321120925338735501967616, 1511157274518286468645120, 1213648187223398727024896, 306953825890126566523136, 321120920835135891308800, 23611833540248149688576, 1213648187223398726762768, 306953825890126566261008, 1511157274518286468448528, 1208925820740529081614608, 302231459407256921112848, 306953821386526955667728, 4722367608769568833808, 23611836917947853439488, 1227815285546107755627008, 18889470435078208291328, 1213648186097498820182528, 4722370986469272846848, 23611832414348242846208, 1213648186097498819920400, 4722370986469272584720, 1208925819614629174772240, 4503599627436560, 4722366482869661991440]
theorem e07 : enumKeys 2119 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4214_b8, by decide, c4214_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4214_b7, by decide, c4214_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4214_b6, by decide, c4214_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4214_b5, by decide, c4214_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4214_b4, by decide, c4214_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4216_b5, by decide, c4216_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4216_b4, by decide, c4216_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4216_b2, by decide, c4216_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4216_b3, by decide, c4216_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4215_b5, by decide, c4215_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4215_b4, by decide, c4215_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4215_b1, by decide, c4215_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4215_b3, by decide, c4215_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4215_b2, by decide, c4215_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4214_b9, by decide, c4214_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4215_b0, by decide, c4215_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4216_b7, by decide, c4216_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4216_b6, by decide, c4216_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4217_b0, by decide, c4217_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4217_b2, by decide, c4217_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4217_b1, by decide, c4217_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4216_b8, by decide, c4216_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4216_b9, by decide, c4216_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4215_b6, by decide, c4215_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4216_b0, by decide, c4216_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4216_b1, by decide, c4216_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4215_b8, by decide, c4215_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4215_b9, by decide, c4215_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4215_b7, by decide, c4215_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4217_b3, by decide, c4217_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4217_b4, by decide, c4217_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4217_b6, by decide, c4217_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4217_b7, by decide, c4217_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4217_b5, by decide, c4217_ok5⟩, ?_⟩
  simp

def s08 : List Nat := [4854592745515895186587648, 321120938849534384078848, 5137934733643648969474048, 4840425646067286251143168, 4911261143310330929348608, 306953839400925448634368, 377789336643970126839808, 321120921116610918350848, 23611833540248200019968, 94447330783292878225408, 4840425646067286250881040, 306953839400925448372240, 5137934733643648969277456, 4911261143310330929152016, 377789336643970126643216, 377789318629571684204560, 306953821668001982709776, 80280231334683942584336, 23611850428746735550720, 4854592744671470256455936, 94447347671791413821696, 4911261142184431022506240, 4840425645222861321011456, 80280248223182478377216, 94447329657392971383040, 23611832695823269888256, 4840425645222861320749328, 80280248223182478115088, 4911261142184431022309648, 4835703278739991675601168, 75557881740312832966928, 80280230208784035741968, 4722366764344689033488, 23611833540248132915200, 321120921116610851311616, 94447330783292811186176, 377789318629571617361920, 306953821668001915867136, 80280231334683875741696, 306953821668001915605008, 80280231334683875479568, 377789318629571617165328, 302231455185132270456848, 75557864851814230331408, 23611832695823202783488, 94447329657392904343808, 18889466212953557635328, 80280230208783968899328, 4722366764344622190848, 80280230208783968637200, 4722366764344621928720, 75557863725914323489040, 281474976780560]
theorem e08 : enumKeys 2119 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4218_b7, by decide, c4218_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4218_b6, by decide, c4218_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4218_b5, by decide, c4218_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4218_b4, by decide, c4218_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4218_b3, by decide, c4218_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4218_b2, by decide, c4218_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4218_b1, by decide, c4218_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4218_b0, by decide, c4218_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4217_b9, by decide, c4217_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4217_b8, by decide, c4217_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4220_b8, by decide, c4220_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4220_b7, by decide, c4220_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4221_b4, by decide, c4221_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4221_b3, by decide, c4221_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4221_b2, by decide, c4221_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4220_b9, by decide, c4220_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4221_b1, by decide, c4221_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4221_b0, by decide, c4221_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4219_b4, by decide, c4219_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4220_b1, by decide, c4220_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4220_b0, by decide, c4220_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4219_b7, by decide, c4219_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4219_b9, by decide, c4219_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4219_b8, by decide, c4219_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4219_b5, by decide, c4219_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4219_b6, by decide, c4219_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4222_b1, by decide, c4222_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4222_b0, by decide, c4222_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4222_b4, by decide, c4222_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4222_b6, by decide, c4222_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4222_b5, by decide, c4222_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4222_b2, by decide, c4222_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4222_b3, by decide, c4222_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4218_b8, by decide, c4218_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4219_b3, by decide, c4219_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4219_b2, by decide, c4219_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4218_b9, by decide, c4218_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4219_b1, by decide, c4219_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4219_b0, by decide, c4219_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4221_b6, by decide, c4221_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4221_b5, by decide, c4221_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4221_b7, by decide, c4221_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4221_b9, by decide, c4221_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4221_b8, by decide, c4221_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4220_b2, by decide, c4220_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4220_b5, by decide, c4220_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4220_b6, by decide, c4220_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4220_b3, by decide, c4220_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4220_b4, by decide, c4220_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4222_b7, by decide, c4222_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4222_b8, by decide, c4222_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4222_b9, by decide, c4222_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4223_b0, by decide, c4223_ok0⟩, ?_⟩
  simp

def s09 : List Nat := [37778932988857068617728, 321120921116610851504128, 23611833540248133173248, 94447330783292811378688, 23611833540248132911120, 321120921116610851307536, 94447330783292811182096, 306953821668001915863056, 377789318911046594068496, 80280231334683875737616, 151115728577728553943056, 306953821668001915600928, 80280231334683875475488, 377789318911046593871904, 151115728577728553746464, 37778932144432138486016, 23611832695823203041536, 94447329938867881246976, 23611832695823202779408, 94447329938867881050384, 151115727451828647100688, 80280230490258945605904, 80280230490258945343776, 151115727451828646904096, 75557864007389300195616]
theorem e09 : enumKeys 2119 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4223_b4, by decide, c4223_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4223_b3, by decide, c4223_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4223_b2, by decide, c4223_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4223_b1, by decide, c4223_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 277, c4223_b8, by decide, c4223_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4224_b4, by decide, c4224_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4224_b3, by decide, c4224_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4224_b2, by decide, c4224_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4224_b1, by decide, c4224_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4224_b0, by decide, c4224_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4223_b9, by decide, c4223_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4225_b0, by decide, c4225_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4224_b9, by decide, c4224_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4225_b2, by decide, c4225_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4225_b1, by decide, c4225_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4223_b7, by decide, c4223_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4223_b6, by decide, c4223_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4223_b5, by decide, c4223_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4224_b5, by decide, c4224_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4224_b8, by decide, c4224_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4224_b6, by decide, c4224_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4224_b7, by decide, c4224_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4225_b3, by decide, c4225_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4225_b4, by decide, c4225_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4225_b5, by decide, c4225_ok5⟩, ?_⟩
  simp

def s10 : List Nat := [5137934734488073899409408, 604462927821713096900608, 604462909807314654461952, 306953822512426912841728, 5137934733362173992567040, 4840425646067286250946816, 306953839400925448438016, 306953821386527005999360, 9444734091639264379136, 9444750980137799909888, 4840425644941386344104448, 4722384497268154761728, 9444732965739357536768, 604462909807314587422720, 306953822512426845802496, 9444734091639197274368, 306953821386526938960128, 4722367608769552126208, 9444732965739290432000, 4722366482869645283840]
theorem e10 : enumKeys 2119 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4225_b9, by decide, c4225_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4225_b8, by decide, c4225_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 342, c4225_b6, by decide, c4225_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4225_b7, by decide, c4225_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4226_b4, by decide, c4226_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4226_b6, by decide, c4226_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4226_b5, by decide, c4226_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4226_b2, by decide, c4226_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4226_b3, by decide, c4226_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4227_b0, by decide, c4227_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4227_b2, by decide, c4227_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4227_b3, by decide, c4227_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4227_b1, by decide, c4227_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4226_b0, by decide, c4226_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4226_b1, by decide, c4226_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4226_b7, by decide, c4226_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4226_b8, by decide, c4226_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4226_b9, by decide, c4226_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4227_b4, by decide, c4227_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4227_b5, by decide, c4227_ok5⟩, ?_⟩
  simp

def s11 : List Nat := [321120921961035781439488, 604462910088789564325888, 306953822512426845995008, 377789319755471524200448, 604462910088789564129296, 306953822512426845798416, 377789319755471524003856, 321120921116610851307776, 23611833540248132976896, 94447330783292811182336, 377789318629571617358080, 306953821668001915863296, 9444734091639197532416, 80280231334683875737856, 9444734091639197270288, 377789318629571617161488, 306953821668001915666704, 80280231334683875541264, 94447329657392904339968, 23611832695823202845184, 80280230208783968895488, 9444733247214267400704, 9444733247214267138576, 80280230208783968698896, 4722366764344621990416]
theorem e11 : enumKeys 2119 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 297, c4227_b9, by decide, c4227_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4227_b8, by decide, c4227_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4227_b7, by decide, c4227_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4227_b6, by decide, c4227_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4229_b3, by decide, c4229_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4229_b2, by decide, c4229_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4229_b1, by decide, c4229_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4228_b6, by decide, c4228_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4228_b5, by decide, c4228_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4228_b4, by decide, c4228_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 322, c4228_b0, by decide, c4228_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c4228_b3, by decide, c4228_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4228_b2, by decide, c4228_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c4228_b1, by decide, c4228_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4229_b4, by decide, c4229_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4229_b5, by decide, c4229_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4229_b7, by decide, c4229_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4229_b6, by decide, c4229_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4228_b9, by decide, c4228_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4229_b0, by decide, c4229_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 275, c4228_b7, by decide, c4228_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4228_b8, by decide, c4228_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4229_b8, by decide, c4229_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4229_b9, by decide, c4229_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4230_b0, by decide, c4230_ok0⟩, ?_⟩
  simp

def s12 : List Nat := [604462910933214494261248, 604462909807314587418880, 306953822512426845798656, 306953821386526938956288, 9444734091639197336064, 9444732965739290493696]
theorem e12 : enumKeys 2119 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4230_b1, by decide, c4230_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 352, c4230_b2, by decide, c4230_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4230_b3, by decide, c4230_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4230_b4, by decide, c4230_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4230_b5, by decide, c4230_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4230_b6, by decide, c4230_ok6⟩, ?_⟩
  simp

def s13 : List Nat := [9671406561420633025019905, 6044629116087544383012865, 9671406556917033414426625, 4835703296472915225083905, 6044629098073145940639745, 4835703282962116393304065, 1208925837629027751297025, 6044629098073145873534977, 4835703282962116326199297, 1208925837629027684192257, 4835703278458516715606017, 18014398526263297, 1208925819614629241819137, 4503599694483457, 1208925819614629174714369, 4503599627378689, 16785409]
theorem e13 : enumKeys 2119 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4230_b8, by decide, c4230_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c4230_b7, by decide, c4230_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4231_b2, by decide, c4231_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c4231_b3, by decide, c4231_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4230_b9, by decide, c4230_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4231_b1, by decide, c4231_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4231_b0, by decide, c4231_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4231_b4, by decide, c4231_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4231_b6, by decide, c4231_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4231_b5, by decide, c4231_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4231_b9, by decide, c4231_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c4232_b0, by decide, c4232_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4231_b7, by decide, c4231_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4231_b8, by decide, c4231_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4232_b1, by decide, c4232_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4232_b2, by decide, c4232_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4232_b3, by decide, c4232_ok3⟩, ?_⟩
  simp

def s14 : List Nat := [2417851640355158256517121, 1511157279021886096015361, 1227815286672007679180801, 321120925338735518679041, 2417851640355158256254993, 1511157279021886095753233, 1511157274518286485159953, 1208925820740529098326033, 302231459407256937824273, 1227815290049707382931713, 2417851639229258349674753, 1208925824118228802339073, 1227815285546107772338433, 18889470435078225002753, 2417851639229258349412625, 1208925824118228802076945, 1208925819614629191483665, 4503599644147985]
theorem e14 : enumKeys 2119 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c4232_b7, by decide, c4232_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4232_b6, by decide, c4232_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4232_b5, by decide, c4232_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4232_b4, by decide, c4232_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4233_b4, by decide, c4233_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4233_b3, by decide, c4233_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4233_b5, by decide, c4233_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4233_b7, by decide, c4233_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4233_b6, by decide, c4233_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4232_b8, by decide, c4232_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4233_b1, by decide, c4233_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4233_b2, by decide, c4233_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4232_b9, by decide, c4232_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4233_b0, by decide, c4233_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4233_b8, by decide, c4233_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4233_b9, by decide, c4233_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4234_b0, by decide, c4234_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4234_b1, by decide, c4234_ok1⟩, ?_⟩
  simp

def s15 : List Nat := [4854592748893594907049985, 1227815303560506265042945, 6044629098354620850503681, 4911261146688030649876481, 1284483701354942007869441, 4854592744671470273167361, 94447347671791430533121, 1227815285827582799380481, 94447334160992598753281, 6044629098354620850241553, 4911261146688030649614353, 1284483701354942007607313, 4911261142184431039021073, 4835703278739991692312593, 75557881740312849678353, 1284483683340543565234193, 1208925819896104218525713, 75557868229514017898513, 1227815285827582732275713, 94447334160992531648513, 1284483683340543498391553, 1208925819896104151683073, 75557868229513951055873, 94447329657392921055233, 18889466212953574346753, 1284483683340543498129425, 1208925819896104151420945, 75557868229513950793745, 75557863725914340200465, 281474993491985]
theorem e15 : enumKeys 2119 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4234_b3, by decide, c4234_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4234_b2, by decide, c4234_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 131, c4235_b0, by decide, c4235_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c4234_b9, by decide, c4234_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c4234_b8, by decide, c4234_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c4234_b7, by decide, c4234_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4234_b6, by decide, c4234_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4234_b5, by decide, c4234_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4234_b4, by decide, c4234_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4236_b0, by decide, c4236_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4235_b9, by decide, c4235_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 159, c4235_b8, by decide, c4235_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c4236_b4, by decide, c4236_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4236_b6, by decide, c4236_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c4236_b5, by decide, c4236_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4236_b1, by decide, c4236_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4236_b3, by decide, c4236_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4236_b2, by decide, c4236_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4235_b2, by decide, c4235_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4235_b1, by decide, c4235_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 153, c4235_b5, by decide, c4235_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 137, c4235_b7, by decide, c4235_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c4235_b6, by decide, c4235_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c4235_b3, by decide, c4235_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4235_b4, by decide, c4235_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4236_b7, by decide, c4236_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c4236_b9, by decide, c4236_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4236_b8, by decide, c4236_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4237_b0, by decide, c4237_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 152, c4237_b1, by decide, c4237_ok1⟩, ?_⟩
  simp

def s16 : List Nat := [37778936366556789080065, 94447329938867881246721, 1227815285827582732533761, 94447334160992531906561, 37778932144432155197441, 1227815285827582732271633, 94447334160992531644433, 1284483683622018475098129, 151115731955428274470929, 94447329938867897761809, 1284483683622018474836001, 151115731955428274208801, 151115727451828663615521, 75557864007389316907041]
theorem e16 : enumKeys 2119 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4237_b2, by decide, c4237_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4237_b6, by decide, c4237_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4237_b5, by decide, c4237_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4237_b4, by decide, c4237_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4237_b3, by decide, c4237_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4237_b8, by decide, c4237_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4237_b7, by decide, c4237_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c4238_b1, by decide, c4238_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4238_b0, by decide, c4238_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 163, c4237_b9, by decide, c4237_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4238_b3, by decide, c4238_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4238_b2, by decide, c4238_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4238_b4, by decide, c4238_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4238_b5, by decide, c4238_ok5⟩, ?_⟩
  simp

def s17 : List Nat := [6044629099199045780439041, 5137934737865773619937281, 1511157292532684977930241, 5137934733362174009278465, 4840425646067286267658241, 306953839400925465149441, 1511157274518286535491585, 1213648187223398793871361, 306953825890126633369601, 4840425649444985971409153, 1213648204111897329402113, 6044629098073145873596673, 4835703282962116326260993, 1208925837629027684253953, 4840425644941386360815873, 4722384497268171473153, 1213648186097498887028993, 4722370986469339693313, 1213648187223398726766593, 306953825890126566264833, 1511157274518286468452353, 1208925820740529081618433, 302231459407256921116673, 306953821386526955671553, 4722367608769568837633, 1213648186097498819924225, 4722370986469272588545, 1208925819614629174776065, 4503599627440385, 4722366482869661995265]
theorem e17 : enumKeys 2119 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 155, c4239_b4, by decide, c4239_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4239_b3, by decide, c4239_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4239_b2, by decide, c4239_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4238_b9, by decide, c4238_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4239_b1, by decide, c4239_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4239_b0, by decide, c4239_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4238_b6, by decide, c4238_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4238_b8, by decide, c4238_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4238_b7, by decide, c4238_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4240_b3, by decide, c4240_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4240_b2, by decide, c4240_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4240_b8, by decide, c4240_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4241_b0, by decide, c4241_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4240_b9, by decide, c4240_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4240_b6, by decide, c4240_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4240_b7, by decide, c4240_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4240_b4, by decide, c4240_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4240_b5, by decide, c4240_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4239_b6, by decide, c4239_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4239_b5, by decide, c4239_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4239_b9, by decide, c4239_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4240_b1, by decide, c4240_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4240_b0, by decide, c4240_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4239_b7, by decide, c4239_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4239_b8, by decide, c4239_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4241_b1, by decide, c4241_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4241_b2, by decide, c4241_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4241_b4, by decide, c4241_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4241_b5, by decide, c4241_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4241_b3, by decide, c4241_ok3⟩, ?_⟩
  simp

def s18 : List Nat := [4840425662955784853520385, 9671406557198508374425601, 4911261160198829531791361, 4911261142184431089352705, 4840425645222861387857921, 80280248223182545223681, 4840425645222861320753153, 80280248223182478118913, 4911261142184431022313473, 4835703278739991675604993, 75557881740312832970753, 80280230208784035745793, 4722366764344689037313, 80280230208783968641025, 4722366764344621932545, 75557863725914323492865, 281474976784385]
theorem e18 : enumKeys 2119 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4241_b6, by decide, c4241_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 134, c4242_b1, by decide, c4242_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 149, c4242_b0, by decide, c4242_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4241_b7, by decide, c4241_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4241_b9, by decide, c4241_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4241_b8, by decide, c4241_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 161, c4242_b3, by decide, c4242_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4242_b2, by decide, c4242_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4242_b6, by decide, c4242_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c4242_b8, by decide, c4242_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4242_b7, by decide, c4242_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4242_b4, by decide, c4242_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4242_b5, by decide, c4242_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4242_b9, by decide, c4242_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4243_b0, by decide, c4243_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4243_b1, by decide, c4243_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c4243_b2, by decide, c4243_ok2⟩, ?_⟩
  simp

def s19 : List Nat := [321120921116610851307521, 94447330783292811182081, 1227815286672007662469121, 321120925338735501967361, 306953821668001915863041, 1511157274799761445355521, 80280231334683875737601, 1213648187223398727024641, 1284483684466443405230081, 306953825890126566522881, 377789323133171244728321, 321120921116610868019201, 23611833540248149688321, 94447330783292827893761, 1213648187223398726762513, 306953825890126566260753, 1511157274799761445158929, 1284483684466443405033489, 377789323133171244531729, 377789318629571633872913, 306953821668001932378129, 80280231334683892252689, 23611836917947853439233, 1227815285827582732337409, 94447334160992531710209, 1284483683340543498387713, 1213648186378973796892929, 80280234712383596265729, 94447329657392921051393, 23611832695823219556609, 1213648186378973796630801, 80280234712383596003601, 1284483683340543498191121, 1208925819896104151482641, 75557868229513950855441, 80280230208783985410321, 4722366764344638701841]
theorem e19 : enumKeys 2119 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4244_b6, by decide, c4244_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4244_b5, by decide, c4244_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4244_b4, by decide, c4244_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4244_b3, by decide, c4244_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4244_b2, by decide, c4244_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4244_b1, by decide, c4244_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4244_b0, by decide, c4244_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4243_b9, by decide, c4243_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4243_b8, by decide, c4243_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4243_b7, by decide, c4243_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4243_b6, by decide, c4243_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4243_b5, by decide, c4243_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4243_b4, by decide, c4243_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4243_b3, by decide, c4243_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4245_b6, by decide, c4245_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4245_b5, by decide, c4245_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4246_b2, by decide, c4246_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4246_b1, by decide, c4246_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4246_b0, by decide, c4246_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4245_b7, by decide, c4245_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4245_b9, by decide, c4245_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4245_b8, by decide, c4245_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4244_b7, by decide, c4244_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4245_b4, by decide, c4245_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4245_b3, by decide, c4245_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4245_b0, by decide, c4245_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4245_b2, by decide, c4245_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4245_b1, by decide, c4245_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4244_b8, by decide, c4244_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4244_b9, by decide, c4244_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4246_b4, by decide, c4246_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4246_b3, by decide, c4246_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4246_b7, by decide, c4246_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4246_b9, by decide, c4246_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4246_b8, by decide, c4246_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4246_b5, by decide, c4246_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4246_b6, by decide, c4246_ok6⟩, ?_⟩
  simp

def s20 : List Nat := [23611850428746735550465, 4854592744671470256455681, 94447347671791413821441, 4840425645222861321011201, 4911261142465905999216641, 80280248223182478376961, 151115745466227156582401, 23611832695823269888001, 94447329938867948093441, 4840425645222861320749073, 80280248223182478114833, 4911261142465905999020049, 151115745466227156385809, 151115727451828713947153, 80280230490259012452369, 23611832695823202783233, 94447329938867881054209, 151115727451828647104513, 80280230490258945609729, 80280230490258945347601, 151115727451828646907921, 75557864007389300199441]
theorem e20 : enumKeys 2119 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4247_b0, by decide, c4247_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4247_b8, by decide, c4247_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4247_b7, by decide, c4247_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4247_b6, by decide, c4247_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4247_b5, by decide, c4247_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4247_b4, by decide, c4247_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4247_b3, by decide, c4247_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4247_b2, by decide, c4247_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4247_b1, by decide, c4247_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4248_b4, by decide, c4248_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4248_b3, by decide, c4248_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4248_b8, by decide, c4248_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4248_b7, by decide, c4248_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4248_b5, by decide, c4248_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4248_b6, by decide, c4248_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4247_b9, by decide, c4247_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4248_b2, by decide, c4248_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4248_b0, by decide, c4248_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 165, c4248_b1, by decide, c4248_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4248_b9, by decide, c4248_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4249_b0, by decide, c4249_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4249_b1, by decide, c4249_ok1⟩, ?_⟩
  simp

def s21 : List Nat := [37778932144432138485761, 23611832695823203041281, 94447329938867881246721, 23611832695823202779153, 94447329938867881050129, 80280230490258945605649, 151115727733303623811089, 80280230490258945343521, 151115727733303623614497]
theorem e21 : enumKeys 2119 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4249_b4, by decide, c4249_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4249_b3, by decide, c4249_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4249_b2, by decide, c4249_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4249_b5, by decide, c4249_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4249_b8, by decide, c4249_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4249_b7, by decide, c4249_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4249_b6, by decide, c4249_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4249_b9, by decide, c4249_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4250_b0, by decide, c4250_ok0⟩, ?_⟩
  simp

def s22 : List Nat := [306953822512426845798401, 1511157275644186375290881, 604462914310914214789121, 604462909807314604130305, 306953822512426862510081, 1511157274518286468448513, 1213648187223398726828289, 306953825890126566326529, 306953821386526955667713, 9444734091639214047489, 9444737469338917798401, 1213648186097498819985921, 4722370986469272650241, 9444732965739307205121]
theorem e22 : enumKeys 2119 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4250_b5, by decide, c4250_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4250_b4, by decide, c4250_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4250_b3, by decide, c4250_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 320, c4250_b1, by decide, c4250_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4250_b2, by decide, c4250_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4250_b8, by decide, c4250_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4251_b0, by decide, c4251_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4250_b9, by decide, c4250_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c4250_b6, by decide, c4250_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4250_b7, by decide, c4250_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4251_b1, by decide, c4251_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4251_b3, by decide, c4251_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4251_b4, by decide, c4251_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4251_b2, by decide, c4251_ok2⟩, ?_⟩
  simp

def s23 : List Nat := [5137934733643648969277441, 4840425646067286250946561, 4911261143310330929152001, 306953839400925448437761, 377789336643970126643201, 377789318629571684204545, 306953821668001982709761, 9444734091639264378881, 80280231334683942584321, 9444750980137799909633, 4911261142184431022309633, 4840425645222861320814849, 80280248223182478180609, 80280230208784035741953, 9444733247214334247169, 9444734091639197274113, 377789318629571617165313, 306953821668001915670529, 80280231334683875545089, 9444733247214267142401, 80280230208783968702721, 4722366764344621994241]
theorem e23 : enumKeys 2119 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4252_b3, by decide, c4252_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4252_b2, by decide, c4252_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4252_b1, by decide, c4252_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4252_b0, by decide, c4252_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4251_b9, by decide, c4251_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4251_b5, by decide, c4251_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4251_b8, by decide, c4251_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4251_b7, by decide, c4251_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4251_b6, by decide, c4251_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4252_b8, by decide, c4252_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4253_b1, by decide, c4253_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4253_b3, by decide, c4253_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4253_b2, by decide, c4253_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4252_b9, by decide, c4252_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4253_b0, by decide, c4253_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4252_b4, by decide, c4252_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4252_b5, by decide, c4252_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4252_b7, by decide, c4252_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4252_b6, by decide, c4252_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4253_b4, by decide, c4253_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4253_b5, by decide, c4253_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4253_b6, by decide, c4253_ok6⟩, ?_⟩
  simp

def s24 : List Nat := [321120921116610851307521, 23611833540248132976641, 94447330783292811182081, 306953821668001915863041, 377789318911046594068481, 9444734091639197532161, 80280231334683875737601, 151115728577728553943041, 9444734091639197270033, 306953821668001915666449, 377789318911046593871889, 80280231334683875541009, 151115728577728553746449, 23611832695823202844929, 94447329938867881050369, 151115727451828647100673, 9444733247214267400449, 80280230490258945605889, 9444733247214267138321, 151115727451828646904081, 80280230490258945409297]
theorem e24 : enumKeys 2119 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4254_b4, by decide, c4254_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4254_b3, by decide, c4254_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4254_b2, by decide, c4254_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c4254_b1, by decide, c4254_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4254_b0, by decide, c4254_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4253_b9, by decide, c4253_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 269, c4253_b8, by decide, c4253_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4253_b7, by decide, c4253_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4255_b0, by decide, c4255_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4255_b4, by decide, c4255_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4255_b3, by decide, c4255_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4255_b2, by decide, c4255_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4255_b1, by decide, c4255_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4254_b9, by decide, c4254_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4254_b8, by decide, c4254_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4254_b5, by decide, c4254_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4254_b7, by decide, c4254_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4254_b6, by decide, c4254_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4255_b5, by decide, c4255_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4255_b6, by decide, c4255_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4255_b7, by decide, c4255_ok7⟩, ?_⟩
  simp

def s25 : List Nat := [604462910088789564129281, 306953822512426845798401, 377789319755471524003841, 377789318629571617161473, 306953821668001915666689, 9444734091639197335809, 80280231334683875541249, 80280230208783968698881, 9444733247214267204097]
theorem e25 : enumKeys 2119 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4256_b0, by decide, c4256_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4255_b9, by decide, c4255_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4255_b8, by decide, c4255_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4256_b1, by decide, c4256_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4256_b4, by decide, c4256_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4256_b3, by decide, c4256_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4256_b2, by decide, c4256_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4256_b5, by decide, c4256_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4256_b6, by decide, c4256_ok6⟩, ?_⟩
  simp

def s26 : List Nat := [6044629102576745500901378, 2417851657243656858894338, 6044629098073145890308098, 4835703282962116342972418, 1208925837629027700965378, 2417851639229258416521218, 1208925824118228869185538, 2417851639229258349416450, 1208925824118228802080770, 1208925819614629191487490, 4503599644151810]
theorem e26 : enumKeys 2119 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 147, c4256_b8, by decide, c4256_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4256_b7, by decide, c4256_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 141, c4257_b1, by decide, c4257_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c4257_b3, by decide, c4257_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c4257_b2, by decide, c4257_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4256_b9, by decide, c4256_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4257_b0, by decide, c4257_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 148, c4257_b4, by decide, c4257_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4257_b5, by decide, c4257_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4257_b6, by decide, c4257_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4257_b7, by decide, c4257_ok7⟩, ?_⟩
  simp

def s27 : List Nat := [1227815290049707382931458, 2417851639510733326385154, 1284483687844143125757954, 1227815285827582749048834, 94447334160992548421634, 2417851639510733326123026, 1284483687844143125495826, 1284483683340543514902546, 1208925819896104168194066, 75557868229513967566866]
theorem e27 : enumKeys 2119 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4257_b8, by decide, c4257_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 130, c4258_b2, by decide, c4258_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c4258_b1, by decide, c4258_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 139, c4258_b0, by decide, c4258_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4257_b9, by decide, c4257_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 140, c4258_b4, by decide, c4258_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4258_b3, by decide, c4258_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4258_b5, by decide, c4258_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 142, c4258_b7, by decide, c4258_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4258_b6, by decide, c4258_ok6⟩, ?_⟩
  simp

def s28 : List Nat := [2417851640355158256320514, 1511157279021886095818754, 1511157274518286485159938, 1213648187223398743539714, 306953825890126583037954, 1213648190601098447290626, 2417851639229258349478146, 1208925824118228802142466, 1213648186097498836697346, 4722370986469289361666]
theorem e28 : enumKeys 2119 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4259_b2, by decide, c4259_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4259_b1, by decide, c4259_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4258_b8, by decide, c4258_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4259_b0, by decide, c4259_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4258_b9, by decide, c4258_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4259_b3, by decide, c4259_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4259_b6, by decide, c4259_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4259_b7, by decide, c4259_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4259_b4, by decide, c4259_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4259_b5, by decide, c4259_ok5⟩, ?_⟩
  simp

def s29 : List Nat := [4840425649444985971408898, 1213648204111897329401858, 6044629098354620850307074, 4911261146688030649679874, 1284483701354942007672834, 4911261142184431039021058, 4840425645222861337526274, 80280248223182494892034, 1284483683340543565234178, 1213648186378973863739394, 80280234712383663112194, 1213648186378973796634626, 80280234712383596007426, 1284483683340543498194946, 1208925819896104151486466, 75557868229513950859266, 80280230208783985414146, 4722366764344638705666]
theorem e29 : enumKeys 2119 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4259_b9, by decide, c4259_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4259_b8, by decide, c4259_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 133, c4260_b8, by decide, c4260_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4260_b7, by decide, c4260_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 145, c4260_b6, by decide, c4260_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4260_b3, by decide, c4260_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 151, c4260_b5, by decide, c4260_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4260_b4, by decide, c4260_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4260_b0, by decide, c4260_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 160, c4260_b2, by decide, c4260_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4260_b1, by decide, c4260_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 156, c4261_b0, by decide, c4261_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4260_b9, by decide, c4260_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 154, c4261_b3, by decide, c4261_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 138, c4261_b5, by decide, c4261_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4261_b4, by decide, c4261_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4261_b1, by decide, c4261_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 158, c4261_b2, by decide, c4261_ok2⟩, ?_⟩
  simp

def s30 : List Nat := [23611836917947853438978, 94447329938867881050114, 1227815285827582732337154, 94447334160992531709954, 80280230490258945605634, 1213648186378973796892674, 1284483683622018475098114, 80280234712383596265474, 151115731955428274470914, 23611832695823219556354, 94447329938867897761794, 1213648186378973796630546, 80280234712383596003346, 1284483683622018474901522, 151115731955428274274322, 151115727451828663615506, 80280230490258962120722]
theorem e30 : enumKeys 2119 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4261_b6, by decide, c4261_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4262_b6, by decide, c4262_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4262_b5, by decide, c4262_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4262_b4, by decide, c4262_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4262_b3, by decide, c4262_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4262_b2, by decide, c4262_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4262_b1, by decide, c4262_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4262_b0, by decide, c4262_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4261_b9, by decide, c4261_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4261_b8, by decide, c4261_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4261_b7, by decide, c4261_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4262_b8, by decide, c4262_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4262_b7, by decide, c4262_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 146, c4263_b2, by decide, c4263_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4263_b1, by decide, c4263_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4262_b9, by decide, c4262_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4263_b0, by decide, c4263_ok0⟩, ?_⟩
  simp

def s31 : List Nat := [306953821668001915666434, 1511157274799761445158914, 80280231334683875540994, 1213648187223398726828034, 1284483684466443405033474, 306953825890126566326274, 377789323133171244531714, 377789318629571633872898, 306953821668001932378114, 9444734091639214047234, 80280231334683892252674, 9444737469338917798146, 1284483683340543498191106, 1213648186378973796696322, 80280234712383596069122, 80280230208783985410306, 9444733247214283915522]
theorem e31 : enumKeys 2119 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4264_b3, by decide, c4264_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4264_b2, by decide, c4264_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4264_b1, by decide, c4264_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4264_b0, by decide, c4264_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4263_b9, by decide, c4263_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4263_b8, by decide, c4263_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4263_b7, by decide, c4263_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c4263_b3, by decide, c4263_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4263_b6, by decide, c4263_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4263_b5, by decide, c4263_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4263_b4, by decide, c4263_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4264_b4, by decide, c4264_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4264_b7, by decide, c4264_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4264_b9, by decide, c4264_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4264_b8, by decide, c4264_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4264_b5, by decide, c4264_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4264_b6, by decide, c4264_ok6⟩, ?_⟩
  simp

def s32 : List Nat := [9444750980137799909378, 4840425645222861320814594, 4911261142465905999020034, 80280248223182478180354, 151115745466227156385794, 151115727451828713947138, 9444733247214334246914, 80280230490259012452354, 9444733247214267142146, 151115727451828646907906, 80280230490258945413122]
theorem e32 : enumKeys 2119 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4265_b0, by decide, c4265_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4265_b7, by decide, c4265_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4265_b6, by decide, c4265_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4265_b5, by decide, c4265_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4265_b4, by decide, c4265_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4265_b1, by decide, c4265_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4265_b3, by decide, c4265_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4265_b2, by decide, c4265_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4265_b8, by decide, c4265_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4265_b9, by decide, c4265_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 162, c4266_b0, by decide, c4266_ok0⟩, ?_⟩
  simp

def s33 : List Nat := [23611832695823202844674, 94447329938867881050114, 9444733247214267400194, 80280230490258945605634, 151115727733303623811074, 9444733247214267138066, 80280230490258945409042, 151115727733303623614482]
theorem e33 : enumKeys 2119 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4266_b5, by decide, c4266_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4266_b4, by decide, c4266_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4266_b3, by decide, c4266_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4266_b2, by decide, c4266_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4266_b1, by decide, c4266_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4266_b6, by decide, c4266_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4266_b8, by decide, c4266_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4266_b7, by decide, c4266_ok7⟩, ?_⟩
  simp

def s34 : List Nat := [306953821668001915666434, 377789318911046593871874, 9444734091639197335554, 80280231334683875540994, 151115728577728553746434, 151115727451828646904066, 9444733247214267203842, 80280230490258945409282]
theorem e34 : enumKeys 2119 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4267_b3, by decide, c4267_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4267_b2, by decide, c4267_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4267_b1, by decide, c4267_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4267_b0, by decide, c4267_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4266_b9, by decide, c4266_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4267_b4, by decide, c4267_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4267_b6, by decide, c4267_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4267_b5, by decide, c4267_ok5⟩, ?_⟩
  simp

def s35 : List Nat := [2417851643732857976782851, 2417851639229258366189571, 1208925824118228818853891]
theorem e35 : enumKeys 2119 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4267_b7, by decide, c4267_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 144, c4267_b8, by decide, c4267_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4267_b9, by decide, c4267_ok9⟩, ?_⟩
  simp

def s36 : List Nat := [1213648190601098447290371, 2417851639510733326188547, 1284483687844143125561347, 1284483683340543514902531, 1213648186378973813407747, 80280234712383612780547]
theorem e36 : enumKeys 2119 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4268_b0, by decide, c4268_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 132, c4268_b5, by decide, c4268_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4268_b4, by decide, c4268_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4268_b1, by decide, c4268_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 150, c4268_b3, by decide, c4268_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4268_b2, by decide, c4268_ok2⟩, ?_⟩
  simp

def s37 : List Nat := [9444737469338917797891, 80280230490258945409027, 1213648186378973796696067, 1284483683622018474901507, 80280234712383596068867, 151115731955428274274307, 151115727451828663615491, 9444733247214283915267, 80280230490258962120707]
theorem e37 : enumKeys 2119 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4268_b6, by decide, c4268_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4269_b4, by decide, c4269_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4269_b3, by decide, c4269_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4269_b2, by decide, c4269_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4269_b1, by decide, c4269_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4269_b0, by decide, c4269_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4268_b7, by decide, c4268_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4268_b9, by decide, c4268_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4268_b8, by decide, c4268_ok8⟩, ?_⟩
  simp

def s38 : List Nat := [9444733247214267203587, 80280230490258945409027, 151115727733303623614467]
theorem e38 : enumKeys 2119 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4269_b7, by decide, c4269_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4269_b6, by decide, c4269_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4269_b5, by decide, c4269_ok5⟩, ?_⟩
  simp

/-- every enumerated key with left type `2119` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 2119 mR,
    (2119 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 2119 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K36
end Grid3.Three.Cert
