import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4269
import Grid3.Three.Cert.Data.C4270
import Grid3.Three.Cert.Data.C4271
import Grid3.Three.Cert.Data.C4272
import Grid3.Three.Cert.Data.C4273
import Grid3.Three.Cert.Data.C4274
import Grid3.Three.Cert.Data.C4275
import Grid3.Three.Cert.Data.C4276
import Grid3.Three.Cert.Data.C4277
import Grid3.Three.Cert.Data.C4278
import Grid3.Three.Cert.Data.C4279
import Grid3.Three.Cert.Data.C4280
import Grid3.Three.Cert.Data.C4281
import Grid3.Three.Cert.Data.C4282
import Grid3.Three.Cert.Data.C4283
import Grid3.Three.Cert.Data.C4284
import Grid3.Three.Cert.Data.C4285
import Grid3.Three.Cert.Data.C4286
import Grid3.Three.Cert.Data.C4287
import Grid3.Three.Cert.Data.C4288
import Grid3.Three.Cert.Data.C4289
import Grid3.Three.Cert.Data.C4290
import Grid3.Three.Cert.Data.C4291
import Grid3.Three.Cert.Data.C4292
import Grid3.Three.Cert.Data.C4293
import Grid3.Three.Cert.Data.C4294
import Grid3.Three.Cert.Data.C4295
import Grid3.Three.Cert.Data.C4296
import Grid3.Three.Cert.Data.C4297
import Grid3.Three.Cert.Data.C4298
import Grid3.Three.Cert.Data.C4299
import Grid3.Three.Cert.Data.C4300
import Grid3.Three.Cert.Data.C4301
import Grid3.Three.Cert.Data.C4302
import Grid3.Three.Cert.Data.C4303
import Grid3.Three.Cert.Data.C4304
import Grid3.Three.Cert.Data.C4305
import Grid3.Three.Cert.Data.C4306
import Grid3.Three.Cert.Data.C4307
import Grid3.Three.Cert.Data.C4308
import Grid3.Three.Cert.Data.C4309
import Grid3.Three.Cert.Data.C4310
import Grid3.Three.Cert.Data.C4311
import Grid3.Three.Cert.Data.C4312
import Grid3.Three.Cert.Data.C4313
import Grid3.Three.Cert.Data.C4314
import Grid3.Three.Cert.Data.C4315
import Grid3.Three.Cert.Data.C4316
import Grid3.Three.Cert.Data.C4317
import Grid3.Three.Cert.Data.C4318
import Grid3.Three.Cert.Data.C4319
import Grid3.Three.Cert.Data.C4320
import Grid3.Three.Cert.Data.C4321
import Grid3.Three.Cert.Data.C4322
import Grid3.Three.Cert.Data.C4323
import Grid3.Three.Cert.Data.C4324
import Grid3.Three.Cert.Data.C4325
import Grid3.Three.Cert.Data.C4326
import Grid3.Three.Cert.Data.C4327
import Grid3.Three.Cert.Data.C4328
import Grid3.Three.Cert.Data.C4329
import Grid3.Three.Cert.Data.C4330
import Grid3.Three.Cert.Data.C4331
import Grid3.Three.Cert.Data.C4332
import Grid3.Three.Cert.Data.C4333
import Grid3.Three.Cert.Data.C4334
import Grid3.Three.Cert.Data.C4335
import Grid3.Three.Cert.Data.C4336
import Grid3.Three.Cert.Data.C4337
import Grid3.Three.Cert.Data.C4338
import Grid3.Three.Cert.Data.C4339
import Grid3.Three.Cert.Data.C4340
import Grid3.Three.Cert.Data.C4341
import Grid3.Three.Cert.Data.C4342
import Grid3.Three.Cert.Data.C4343
import Grid3.Three.Cert.Data.C4344
import Grid3.Three.Cert.Data.C4345

/-! Seam keys with left type `1163` (type index 37): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K37

def s00 : List Nat := [4835703314487313717788672, 4835703296472915275415552, 36028797086072832, 4835703278458516833042432, 18014398643699712, 4835703296472915208310784, 36028797018968064, 4835703278458516765937664, 18014398576594944, 134221824, 4835703278458516698832896, 18014398509490176, 67117056, 12288]
theorem e00 : enumKeys 1163 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c4269_b8, by decide, c4269_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c4269_b9, by decide, c4269_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4270_b0, by decide, c4270_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 180, c4270_b1, by decide, c4270_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4270_b2, by decide, c4270_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 186, c4270_b3, by decide, c4270_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 190, c4270_b4, by decide, c4270_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 189, c4270_b5, by decide, c4270_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 198, c4270_b6, by decide, c4270_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 196, c4270_b7, by decide, c4270_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 188, c4270_b8, by decide, c4270_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 194, c4270_b9, by decide, c4270_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 200, c4271_b0, by decide, c4271_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 192, c4271_b1, by decide, c4271_ok1⟩, ?_⟩
  simp

def s01 : List Nat := [4835703284088016233299968, 1208925838754927591292928, 302231477421655430791168, 18889485071777013956608, 4835703279584416622706688, 302231472918055820197888, 19140298433363968, 18889471560978182176768, 1208925820740529148919808, 302231459407256988418048, 5629499601584128, 18889467057378571583488, 4835703284088016233037840, 1208925838754927591030800, 302231477421655430529040, 4835703279584416622444560, 302231472918055819935760, 19140298433101840, 1208925820740529148657680, 302231459407256988155920, 5629499601322000, 302231454903657377562640, 1125899990728720, 18889488449476717707520, 4835703282962116326457600, 1208925837629027684450560, 22517998137114880, 18889483945877107114240, 4835703278458516715864320, 18014398526521600, 18889470435078275334400, 1208925819614629242077440, 4503599694741760, 18889465931478664741120, 4835703282962116326195472, 1208925837629027684188432, 22517998136852752, 4835703278458516715602192, 18014398526259472, 1208925819614629241815312, 4503599694479632, 83886352, 18889471560978115072000, 1208925820740529081815040, 302231459407256921313280, 5629499534479360, 18889467057378504478720, 302231454903657310720000, 1125899923886080, 1208925820740529081552912, 302231459407256921051152, 5629499534217232, 302231454903657310457872, 1125899923623952, 18889470435078208229632, 1208925819614629174972672, 4503599627636992, 18889465931478597636352, 17043712, 1208925819614629174710544, 4503599627374864, 16781584]
theorem e01 : enumKeys 1163 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4271_b7, by decide, c4271_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4271_b6, by decide, c4271_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4271_b5, by decide, c4271_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4271_b3, by decide, c4271_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4272_b2, by decide, c4272_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4272_b1, by decide, c4272_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4272_b3, by decide, c4272_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4271_b2, by decide, c4271_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4271_b9, by decide, c4271_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4271_b8, by decide, c4271_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4272_b0, by decide, c4272_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4271_b4, by decide, c4271_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4274_b9, by decide, c4274_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4274_b8, by decide, c4274_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4274_b7, by decide, c4274_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4275_b4, by decide, c4275_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4275_b3, by decide, c4275_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4275_b5, by decide, c4275_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4275_b1, by decide, c4275_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4275_b0, by decide, c4275_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4275_b2, by decide, c4275_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4275_b6, by decide, c4275_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4275_b7, by decide, c4275_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4273_b1, by decide, c4273_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4273_b6, by decide, c4273_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4273_b5, by decide, c4273_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4273_b7, by decide, c4273_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4273_b3, by decide, c4273_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4274_b0, by decide, c4274_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4274_b1, by decide, c4274_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4273_b2, by decide, c4273_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4273_b8, by decide, c4273_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4273_b9, by decide, c4273_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4273_b4, by decide, c4273_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4276_b4, by decide, c4276_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4276_b3, by decide, c4276_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4276_b5, by decide, c4276_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4276_b8, by decide, c4276_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4276_b9, by decide, c4276_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4276_b6, by decide, c4276_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4276_b7, by decide, c4276_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4277_b0, by decide, c4277_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4272_b4, by decide, c4272_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4272_b7, by decide, c4272_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4272_b6, by decide, c4272_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4272_b8, by decide, c4272_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4272_b5, by decide, c4272_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4272_b9, by decide, c4272_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4273_b0, by decide, c4273_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4275_b9, by decide, c4275_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4275_b8, by decide, c4275_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4276_b0, by decide, c4276_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4276_b1, by decide, c4276_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4276_b2, by decide, c4276_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4274_b2, by decide, c4274_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4274_b4, by decide, c4274_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4274_b5, by decide, c4274_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4274_b3, by decide, c4274_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4274_b6, by decide, c4274_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4277_b1, by decide, c4277_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4277_b2, by decide, c4277_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4277_b3, by decide, c4277_ok3⟩, ?_⟩
  simp

def s02 : List Nat := [18889501960275599818752, 4835703296754390185279488, 75557899754711342645248, 18889484227352134156288, 4835703278739991742906368, 75557881740312900272128, 18295873553563648, 18889466212953691783168, 4835703296754390185017360, 75557899754711342383120, 4835703278739991742644240, 75557881740312900010000, 18295873553301520, 75557863725914457636880, 281475110928400, 18889484227352067051520, 4835703278739991675801600, 75557881740312833167360, 18295873486458880, 18889466212953624678400, 75557863725914390794240, 281475044085760, 4835703278739991675539472, 75557881740312832905232, 18295873486196752, 75557863725914390532112, 281475043823632, 18889466212953557573632, 75557863725914323689472, 281474976980992, 75557863725914323427344, 281474976718864]
theorem e02 : enumKeys 1163 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4277_b4, by decide, c4277_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4277_b8, by decide, c4277_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4277_b7, by decide, c4277_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4277_b5, by decide, c4277_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4278_b0, by decide, c4278_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4277_b9, by decide, c4277_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4278_b1, by decide, c4278_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4277_b6, by decide, c4277_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4279_b3, by decide, c4279_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4279_b2, by decide, c4279_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4279_b5, by decide, c4279_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4279_b4, by decide, c4279_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4279_b6, by decide, c4279_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4279_b7, by decide, c4279_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4279_b8, by decide, c4279_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4278_b2, by decide, c4278_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4278_b5, by decide, c4278_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4278_b4, by decide, c4278_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4278_b6, by decide, c4278_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4278_b3, by decide, c4278_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4278_b7, by decide, c4278_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4278_b8, by decide, c4278_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4280_b0, by decide, c4280_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4279_b9, by decide, c4279_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4280_b1, by decide, c4280_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4280_b2, by decide, c4280_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4280_b3, by decide, c4280_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4278_b9, by decide, c4278_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4279_b0, by decide, c4279_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4279_b1, by decide, c4279_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4280_b4, by decide, c4280_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4280_b5, by decide, c4280_ok5⟩, ?_⟩
  simp

def s03 : List Nat := [18889471560978115330048, 1208925821022004058783744, 302231459688731898281984, 75557869355413858156544, 18889467338853481447424, 18889471560978115067920, 1208925821022004058521616, 302231459688731898019856, 75557869355413857894416, 18889467338853481185296, 302231455185132287426576, 75557864851814247301136, 1407374900592656, 1208925821022004058259488, 302231459688731897757728, 75557869355413857632288, 302231455185132287164448, 75557864851814247039008, 1407374900330528, 18889470716553185198336, 1208925819896104151941376, 75557868229513951314176, 4785074604605696, 18889466212953574605056, 18889470716553184936208, 1208925819896104151679248, 75557868229513951052048, 4785074604343568, 18889466212953574342928, 75557863725914340458768, 281474993750288, 1208925819896104151417120, 75557868229513950789920, 4785074604081440, 75557863725914340196640, 281474993488160]
theorem e03 : enumKeys 1163 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4280_b6, by decide, c4280_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4281_b0, by decide, c4281_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4280_b9, by decide, c4280_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4280_b8, by decide, c4280_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4280_b7, by decide, c4280_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4281_b6, by decide, c4281_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4282_b0, by decide, c4282_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4281_b9, by decide, c4281_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4281_b8, by decide, c4281_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4281_b7, by decide, c4281_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4282_b2, by decide, c4282_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4282_b1, by decide, c4282_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4282_b3, by decide, c4282_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4283_b3, by decide, c4283_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4283_b2, by decide, c4283_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4283_b1, by decide, c4283_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4283_b5, by decide, c4283_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4283_b4, by decide, c4283_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4283_b6, by decide, c4283_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4281_b1, by decide, c4281_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4281_b4, by decide, c4281_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4281_b3, by decide, c4281_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4281_b5, by decide, c4281_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4281_b2, by decide, c4281_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4282_b4, by decide, c4282_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4282_b7, by decide, c4282_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4282_b6, by decide, c4282_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4282_b8, by decide, c4282_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4282_b5, by decide, c4282_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4282_b9, by decide, c4282_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4283_b0, by decide, c4283_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4283_b8, by decide, c4283_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4283_b7, by decide, c4283_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4283_b9, by decide, c4283_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4284_b0, by decide, c4284_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4284_b1, by decide, c4284_ok1⟩, ?_⟩
  simp

def s04 : List Nat := [18889484227352067309568, 4835703279021466652770304, 75557882021787810136064, 18889466494428601647104, 18889484227352067047440, 4835703279021466652508176, 75557882021787809873936, 18889466494428601384976, 75557864007389367500816, 562950020792336, 4835703279021466652246048, 75557882021787809611808, 75557864007389367238688, 562950020530208, 18889466494428534542336, 75557864007389300658176, 562949953949696, 18889466494428534280208, 75557864007389300396048, 562949953687568, 75557864007389300133920, 562949953425440]
theorem e04 : enumKeys 1163 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4284_b2, by decide, c4284_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4284_b5, by decide, c4284_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4284_b4, by decide, c4284_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4284_b3, by decide, c4284_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4284_b9, by decide, c4284_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4285_b2, by decide, c4285_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4285_b1, by decide, c4285_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4285_b0, by decide, c4285_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4285_b3, by decide, c4285_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4285_b4, by decide, c4285_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4285_b9, by decide, c4285_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4285_b8, by decide, c4285_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4286_b0, by decide, c4286_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4286_b1, by decide, c4286_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4284_b6, by decide, c4284_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4284_b7, by decide, c4284_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4284_b8, by decide, c4284_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4285_b5, by decide, c4285_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4285_b6, by decide, c4285_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4285_b7, by decide, c4285_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4286_b2, by decide, c4286_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4286_b3, by decide, c4286_ok3⟩, ?_⟩
  simp

def s05 : List Nat := [18889466494428534800384, 18889466494428534538256, 75557864288864277364752, 18889466494428534276128, 75557864288864277102624, 75557864288864276840496]
theorem e05 : enumKeys 1163 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4286_b4, by decide, c4286_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4286_b5, by decide, c4286_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4286_b6, by decide, c4286_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4286_b7, by decide, c4286_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4286_b8, by decide, c4286_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4286_b9, by decide, c4286_ok9⟩, ?_⟩
  simp

def s06 : List Nat := [4835703297598815115214848, 302231490932454312706048, 4722385623168128647168, 4835703279584416672841728, 302231472918055870332928, 19140298483499008, 302231454903657427894272, 4722367608769686274048, 4722402511666664177920, 4835703296472915208372480, 36028797019029760, 4722384497268221804800, 4835703278458516765999360, 18014398576656640, 4722366482869779431680, 4722385623168061542400, 4835703279584416605736960, 302231472918055803228160, 19140298416394240, 4722367608769619169280, 302231454903657360855040, 1125899974021120, 4722384497268154700032, 4835703278458516698894592, 18014398509551872, 4722366482869712326912, 67178752, 4722367608769552064512, 302231454903657293750272, 1125899906916352, 4722366482869645222144, 73984]
theorem e06 : enumKeys 1163 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4287_b4, by decide, c4287_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4287_b3, by decide, c4287_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4287_b0, by decide, c4287_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4287_b6, by decide, c4287_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4287_b5, by decide, c4287_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4287_b7, by decide, c4287_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4287_b1, by decide, c4287_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4287_b2, by decide, c4287_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4288_b8, by decide, c4288_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4289_b1, by decide, c4289_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4289_b2, by decide, c4289_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4288_b9, by decide, c4288_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4289_b3, by decide, c4289_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4289_b4, by decide, c4289_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4289_b0, by decide, c4289_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4287_b8, by decide, c4287_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4288_b1, by decide, c4288_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4288_b0, by decide, c4288_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4288_b2, by decide, c4288_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4287_b9, by decide, c4287_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4288_b3, by decide, c4288_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4288_b4, by decide, c4288_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4289_b5, by decide, c4289_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4289_b7, by decide, c4289_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4289_b8, by decide, c4289_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4289_b6, by decide, c4289_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4289_b9, by decide, c4289_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4288_b5, by decide, c4288_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4288_b6, by decide, c4288_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4288_b7, by decide, c4288_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4290_b0, by decide, c4290_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4290_b1, by decide, c4290_ok1⟩, ?_⟩
  simp

def s07 : List Nat := [1208925821866428988719104, 302231460533156828217344, 18889468183278411382784, 302231456029557217558528, 4722368734669475938304, 1208925821866428988456976, 302231460533156827955216, 4722368734669475676176, 302231456029557217361936, 2251799830528016, 18889471560978115133696, 4722372112369179689216, 1208925820740529081876736, 302231459407256921374976, 5629499534541056, 18889467057378504540416, 302231454903657310716160, 4722367608769569095936, 4722372112369179427088, 1208925820740529081614608, 302231459407256921112848, 5629499534278928, 4722367608769568833808, 302231454903657310519568, 1125899923685648, 18889470435078208291328, 4722370986469272846848, 1208925819614629175034368, 4503599627698688, 18889465931478597698048, 4722366482869662253568, 4722370986469272584720, 1208925819614629174772240, 4503599627436560, 4722366482869661991440, 16843280]
theorem e07 : enumKeys 1163 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4290_b6, by decide, c4290_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4290_b5, by decide, c4290_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4290_b4, by decide, c4290_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4290_b2, by decide, c4290_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4290_b3, by decide, c4290_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4292_b3, by decide, c4292_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4292_b2, by decide, c4292_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4292_b1, by decide, c4292_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4292_b4, by decide, c4292_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4292_b5, by decide, c4292_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4291_b0, by decide, c4291_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4290_b7, by decide, c4290_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4291_b3, by decide, c4291_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4291_b2, by decide, c4291_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4291_b4, by decide, c4291_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4291_b1, by decide, c4291_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 318, c4290_b8, by decide, c4290_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4290_b9, by decide, c4290_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c4292_b6, by decide, c4292_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4292_b9, by decide, c4292_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 277, c4292_b8, by decide, c4292_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4293_b0, by decide, c4293_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 273, c4292_b7, by decide, c4292_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4293_b1, by decide, c4293_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4293_b2, by decide, c4293_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4291_b7, by decide, c4291_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4291_b5, by decide, c4291_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4291_b9, by decide, c4291_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4292_b0, by decide, c4292_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4291_b8, by decide, c4291_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4291_b6, by decide, c4291_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 276, c4293_b3, by decide, c4293_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4293_b5, by decide, c4293_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4293_b6, by decide, c4293_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4293_b4, by decide, c4293_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4293_b7, by decide, c4293_ok7⟩, ?_⟩
  simp

def s08 : List Nat := [18889485071776997244928, 4722385623168061800448, 4835703279865891582705664, 302231473199530780196864, 75557882866212740071424, 18889467338853531582464, 302231455185132337758208, 75557864851814297632768, 4722367890244596137984, 4722385623168061538320, 4835703279865891582443536, 302231473199530779934736, 75557882866212739809296, 4722367890244595875856, 302231455185132337561616, 75557864851814297436176, 1407374950727696, 18889484227352067113216, 4722384778743131668736, 4835703278739991675863296, 75557881740312833229056, 18295873486520576, 18889466212953624740096, 75557863725914390790400, 4722366764344689295616, 4722384778743131406608, 4835703278739991675601168, 75557881740312832966928, 18295873486258448, 4722366764344689033488, 75557863725914390593808, 281475043885328, 18889467338853464477696, 4722367890244529033216, 302231455185132270718976, 75557864851814230593536, 1407374883885056, 4722367890244528771088, 302231455185132270456848, 75557864851814230331408, 1407374883622928, 18889466212953557635328, 4722366764344622190848, 75557863725914323751168, 281474977042688, 4722366764344621928720, 75557863725914323489040, 281474976780560]
theorem e08 : enumKeys 1163 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4294_b2, by decide, c4294_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4293_b8, by decide, c4293_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4294_b6, by decide, c4294_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4294_b5, by decide, c4294_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4294_b4, by decide, c4294_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4294_b3, by decide, c4294_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4294_b0, by decide, c4294_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4293_b9, by decide, c4293_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4294_b1, by decide, c4294_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 285, c4296_b4, by decide, c4296_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4296_b8, by decide, c4296_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4296_b7, by decide, c4296_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4296_b6, by decide, c4296_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4296_b5, by decide, c4296_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4297_b0, by decide, c4297_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4296_b9, by decide, c4296_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4297_b1, by decide, c4297_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4295_b5, by decide, c4295_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4295_b2, by decide, c4295_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4295_b8, by decide, c4295_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4295_b7, by decide, c4295_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4295_b9, by decide, c4295_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4295_b6, by decide, c4295_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 291, c4295_b3, by decide, c4295_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4295_b4, by decide, c4295_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4297_b6, by decide, c4297_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4297_b9, by decide, c4297_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4297_b8, by decide, c4297_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4298_b0, by decide, c4298_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4297_b7, by decide, c4297_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4298_b1, by decide, c4298_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4298_b2, by decide, c4298_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4294_b8, by decide, c4294_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4294_b7, by decide, c4294_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4295_b0, by decide, c4295_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4294_b9, by decide, c4294_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4295_b1, by decide, c4295_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4297_b2, by decide, c4297_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4297_b4, by decide, c4297_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4297_b3, by decide, c4297_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4297_b5, by decide, c4297_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4296_b1, by decide, c4296_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4296_b0, by decide, c4296_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4296_b2, by decide, c4296_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4296_b3, by decide, c4296_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4298_b3, by decide, c4298_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4298_b4, by decide, c4298_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4298_b5, by decide, c4298_ok5⟩, ?_⟩
  simp

def s09 : List Nat := [18889467338853464735744, 302231455466607247622144, 4722367890244529291264, 75557865133289207496704, 18889467338853464473616, 4722367890244529029136, 302231455466607247425552, 75557865133289207300112, 4722367890244528767008, 302231455466607247163424, 75557865133289207037984, 18889466494428534604032, 75557864007389300654336, 4722367045819599159552, 18889466494428534341904, 4722367045819598897424, 75557864007389300457744, 562949953749264, 4722367045819598635296, 75557864007389300195616, 562949953487136]
theorem e09 : enumKeys 1163 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 249, c4298_b9, by decide, c4298_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4298_b8, by decide, c4298_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4298_b7, by decide, c4298_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4298_b6, by decide, c4298_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4299_b4, by decide, c4299_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 275, c4299_b3, by decide, c4299_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4299_b6, by decide, c4299_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4299_b5, by decide, c4299_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4300_b1, by decide, c4300_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4300_b3, by decide, c4300_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4300_b2, by decide, c4300_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4299_b2, by decide, c4299_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4299_b0, by decide, c4299_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4299_b1, by decide, c4299_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4299_b8, by decide, c4299_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4299_b7, by decide, c4299_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4299_b9, by decide, c4299_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4300_b0, by decide, c4300_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4300_b4, by decide, c4300_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4300_b5, by decide, c4300_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4300_b6, by decide, c4300_ok6⟩, ?_⟩
  simp

def s10 : List Nat := [4835703280710316512641024, 302231474043955710132224, 302231456029557267693568, 4722368734669526073344, 4722385623168061604096, 4835703279584416605798656, 302231472918055803289856, 19140298416455936, 302231454903657360851200, 4722367608769619230976, 4722384497268154761728, 4835703278458516698956288, 18014398509613568, 4722366482869712388608, 4722368734669458968576, 302231456029557200654336, 2251799813820416, 4722367608769552126208, 302231454903657293811968, 1125899906978048, 4722366482869645283840, 135680]
theorem e10 : enumKeys 1163 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4301_b0, by decide, c4301_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4300_b9, by decide, c4300_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 321, c4300_b7, by decide, c4300_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 261, c4300_b8, by decide, c4300_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4301_b4, by decide, c4301_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4301_b8, by decide, c4301_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4301_b7, by decide, c4301_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4301_b9, by decide, c4301_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 333, c4301_b5, by decide, c4301_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4301_b6, by decide, c4301_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4302_b3, by decide, c4302_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4302_b5, by decide, c4302_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4302_b6, by decide, c4302_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4302_b4, by decide, c4302_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4301_b1, by decide, c4301_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4301_b2, by decide, c4301_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4301_b3, by decide, c4301_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4302_b0, by decide, c4302_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4302_b1, by decide, c4302_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4302_b2, by decide, c4302_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4302_b7, by decide, c4302_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4302_b8, by decide, c4302_ok8⟩, ?_⟩
  simp

def s11 : List Nat := [18889468183278394671104, 302231456311032177557504, 4722368734669459226624, 75557865977714137432064, 4722368734669458964496, 302231456311032177360912, 75557865977714137235472, 18889467338853464539392, 302231455185132270715136, 75557864851814230589696, 4722367890244529094912, 4722367890244528832784, 302231455185132270518544, 75557864851814230393104, 1407374883684624, 18889466212953557697024, 75557863725914323747328, 4722366764344622252544, 4722366764344621990416, 75557863725914323550736, 281474976842256]
theorem e11 : enumKeys 1163 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4303_b2, by decide, c4303_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4303_b1, by decide, c4303_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 291, c4303_b0, by decide, c4303_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4302_b9, by decide, c4302_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4304_b0, by decide, c4304_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4304_b2, by decide, c4304_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4304_b1, by decide, c4304_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4303_b6, by decide, c4303_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4303_b4, by decide, c4303_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4303_b3, by decide, c4303_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4303_b5, by decide, c4303_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4304_b3, by decide, c4304_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4304_b5, by decide, c4304_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4304_b4, by decide, c4304_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4304_b6, by decide, c4304_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4303_b9, by decide, c4303_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4303_b7, by decide, c4303_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4303_b8, by decide, c4303_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4304_b7, by decide, c4304_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4304_b8, by decide, c4304_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4304_b9, by decide, c4304_ok9⟩, ?_⟩
  simp

def s12 : List Nat := [302231457155457107492864, 302231456029557200650496, 4722368734669459030272, 302231454903657293808128, 4722367608769552187904, 4722366482869645345536]
theorem e12 : enumKeys 1163 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4305_b0, by decide, c4305_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 344, c4305_b1, by decide, c4305_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4305_b2, by decide, c4305_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 350, c4305_b3, by decide, c4305_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4305_b4, by decide, c4305_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4305_b5, by decide, c4305_ok5⟩, ?_⟩
  simp

def s13 : List Nat := [4835703300976514835677185, 1208925855643426193670145, 4835703296472915225083905, 36028797035741185, 4835703282962116393304065, 1208925837629027751297025, 22517998203961345, 4835703278458516782710785, 18014398593368065, 1208925819614629308923905, 4503599761588225, 4835703282962116326199297, 1208925837629027684192257, 22517998136856577, 4835703278458516715606017, 18014398526263297, 1208925819614629241819137, 4503599694483457, 83890177, 1208925819614629174714369, 4503599627378689, 16785409]
theorem e13 : enumKeys 1163 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4305_b7, by decide, c4305_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4305_b6, by decide, c4305_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4306_b3, by decide, c4306_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4306_b4, by decide, c4306_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4305_b9, by decide, c4305_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4305_b8, by decide, c4305_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4306_b0, by decide, c4306_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4306_b5, by decide, c4306_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4306_b6, by decide, c4306_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4306_b1, by decide, c4306_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4306_b2, by decide, c4306_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4306_b8, by decide, c4306_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4306_b7, by decide, c4306_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4306_b9, by decide, c4306_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4307_b2, by decide, c4307_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4307_b3, by decide, c4307_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4307_b0, by decide, c4307_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4307_b1, by decide, c4307_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4307_b4, by decide, c4307_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4307_b5, by decide, c4307_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4307_b6, by decide, c4307_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4307_b7, by decide, c4307_ok7⟩, ?_⟩
  simp

def s14 : List Nat := [1208925825244128709181441, 302231463910856548679681, 18889471560978131845121, 1208925820740529098588161, 302231459407256938086401, 5629499551252481, 18889467057378521251841, 1208925825244128708919313, 302231463910856548417553, 1208925820740529098326033, 302231459407256937824273, 5629499550990353, 302231454903657327230993, 1125899940397073, 18889474938677835596033, 1208925824118228802339073, 9007199255003393, 18889470435078225002753, 1208925819614629191745793, 4503599644410113, 18889465931478614409473, 1208925824118228802076945, 9007199254741265, 1208925819614629191483665, 4503599644147985, 33554705]
theorem e14 : enumKeys 1163 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4308_b1, by decide, c4308_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4308_b0, by decide, c4308_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4307_b8, by decide, c4307_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4308_b3, by decide, c4308_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4308_b2, by decide, c4308_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4308_b4, by decide, c4308_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4307_b9, by decide, c4307_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4309_b3, by decide, c4309_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4309_b2, by decide, c4309_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4309_b5, by decide, c4309_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4309_b4, by decide, c4309_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4309_b6, by decide, c4309_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4309_b7, by decide, c4309_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4309_b8, by decide, c4309_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4308_b5, by decide, c4308_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4308_b8, by decide, c4308_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4308_b9, by decide, c4308_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4308_b6, by decide, c4308_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4309_b0, by decide, c4309_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4309_b1, by decide, c4309_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4308_b7, by decide, c4308_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4309_b9, by decide, c4309_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4310_b0, by decide, c4310_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4310_b1, by decide, c4310_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4310_b2, by decide, c4310_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4310_b3, by decide, c4310_ok3⟩, ?_⟩
  simp

def s15 : List Nat := [18889488449476717707265, 4835703283243591303168001, 1208925837910502661160961, 75557886243912460533761, 18889484227352083824641, 4835703278739991692574721, 75557881740312849940481, 18295873503232001, 18889470716553252044801, 1208925819896104218787841, 75557868229514018160641, 4785074671452161, 18889466212953641451521, 4835703283243591302905873, 1208925837910502660898833, 75557886243912460271633, 4835703278739991692312593, 75557881740312849678353, 18295873502969873, 1208925819896104218525713, 75557868229514017898513, 4785074671190033, 75557863725914407305233, 281475060596753, 18889470716553184940033, 1208925819896104151683073, 75557868229513951055873, 4785074604347393, 18889466212953574346753, 75557863725914340462593, 281474993754113, 1208925819896104151420945, 75557868229513950793745, 4785074604085265, 75557863725914340200465, 281474993491985]
theorem e15 : enumKeys 1163 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4310_b4, by decide, c4310_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4311_b0, by decide, c4311_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 169, c4310_b9, by decide, c4310_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4310_b8, by decide, c4310_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4310_b6, by decide, c4310_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4311_b5, by decide, c4311_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4311_b4, by decide, c4311_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4311_b6, by decide, c4311_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4310_b5, by decide, c4310_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4311_b2, by decide, c4311_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4311_b1, by decide, c4311_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4311_b3, by decide, c4311_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4310_b7, by decide, c4310_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4312_b6, by decide, c4312_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4312_b5, by decide, c4312_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4312_b4, by decide, c4312_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4313_b1, by decide, c4313_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4313_b0, by decide, c4313_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4313_b2, by decide, c4313_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4312_b8, by decide, c4312_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4312_b7, by decide, c4312_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 205, c4312_b9, by decide, c4312_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4313_b3, by decide, c4313_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 193, c4313_b4, by decide, c4313_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4311_b7, by decide, c4311_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4312_b0, by decide, c4312_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4311_b9, by decide, c4311_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4312_b1, by decide, c4312_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4311_b8, by decide, c4311_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4312_b2, by decide, c4312_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4312_b3, by decide, c4312_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4313_b6, by decide, c4313_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4313_b5, by decide, c4313_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4313_b7, by decide, c4313_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4313_b8, by decide, c4313_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4313_b9, by decide, c4313_ok9⟩, ?_⟩
  simp

def s16 : List Nat := [18889470716553185198081, 1208925820177579128651777, 75557868510988928024577, 18889466494428551315457, 18889470716553184935953, 1208925820177579128389649, 75557868510988927762449, 18889466494428551053329, 75557864007389317169169, 562949970460689, 1208925820177579128127521, 75557868510988927500321, 75557864007389316907041, 562949970198561]
theorem e16 : enumKeys 1163 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 229, c4314_b0, by decide, c4314_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 164, c4314_b3, by decide, c4314_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4314_b2, by decide, c4314_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4314_b1, by decide, c4314_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4314_b4, by decide, c4314_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4314_b7, by decide, c4314_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4314_b6, by decide, c4314_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4314_b5, by decide, c4314_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4314_b8, by decide, c4314_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4314_b9, by decide, c4314_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4315_b1, by decide, c4315_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4315_b0, by decide, c4315_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4315_b2, by decide, c4315_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4315_b3, by decide, c4315_ok3⟩, ?_⟩
  simp

def s17 : List Nat := [4835703284088016233103361, 1208925838754927591096321, 302231477421655430594561, 4722385623168078315521, 4835703279584416622510081, 302231472918055820001281, 19140298433167361, 4722372112369246535681, 1208925820740529148723201, 302231459407256988221441, 5629499601387521, 302231454903657377562625, 4722367608769635942401, 4722389000867782066433, 4835703282962116326260993, 1208925837629027684253953, 22517998136918273, 4722384497268171473153, 4835703278458516715667713, 18014398526324993, 4722370986469339693313, 1208925819614629241880833, 4503599694545153, 4722366482869729100033, 4722372112369179430913, 1208925820740529081618433, 302231459407256921116673, 5629499534282753, 4722367608769568837633, 302231454903657310523393, 1125899923689473, 4722370986469272588545, 1208925819614629174776065, 4503599627440385, 4722366482869661995265, 16847105]
theorem e17 : enumKeys 1163 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4316_b0, by decide, c4316_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4315_b9, by decide, c4315_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4315_b8, by decide, c4315_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4315_b5, by decide, c4315_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4316_b5, by decide, c4316_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4316_b4, by decide, c4316_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4316_b6, by decide, c4316_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4315_b4, by decide, c4315_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4316_b2, by decide, c4316_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 243, c4316_b1, by decide, c4316_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4316_b3, by decide, c4316_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 293, c4315_b6, by decide, c4315_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4315_b7, by decide, c4315_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4317_b4, by decide, c4317_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4317_b9, by decide, c4317_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4317_b8, by decide, c4317_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4318_b0, by decide, c4318_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4317_b6, by decide, c4317_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4318_b3, by decide, c4318_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4318_b4, by decide, c4318_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4317_b5, by decide, c4317_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4318_b1, by decide, c4318_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4318_b2, by decide, c4318_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4317_b7, by decide, c4317_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 239, c4316_b7, by decide, c4316_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4317_b0, by decide, c4317_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 237, c4316_b9, by decide, c4316_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4317_b1, by decide, c4317_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4316_b8, by decide, c4316_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4317_b2, by decide, c4317_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4317_b3, by decide, c4317_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4318_b5, by decide, c4318_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4318_b7, by decide, c4318_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4318_b8, by decide, c4318_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4318_b6, by decide, c4318_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4318_b9, by decide, c4318_ok9⟩, ?_⟩
  simp

def s18 : List Nat := [4722402511666664177665, 4835703296754390185082881, 75557899754711342448641, 4722384778743198515201, 4835703278739991742709761, 75557881740312900075521, 18295873553367041, 75557863725914457636865, 4722366764344756142081, 4722384778743131410433, 4835703278739991675604993, 75557881740312832970753, 18295873486262273, 4722366764344689037313, 75557863725914390597633, 281475043889153, 4722366764344621932545, 75557863725914323492865, 281474976784385]
theorem e18 : enumKeys 1163 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4319_b0, by decide, c4319_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4319_b5, by decide, c4319_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4319_b4, by decide, c4319_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4319_b1, by decide, c4319_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 181, c4319_b7, by decide, c4319_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 201, c4319_b6, by decide, c4319_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4319_b8, by decide, c4319_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4319_b2, by decide, c4319_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4319_b3, by decide, c4319_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4319_b9, by decide, c4319_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4320_b2, by decide, c4320_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4320_b1, by decide, c4320_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4320_b3, by decide, c4320_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4320_b0, by decide, c4320_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4320_b4, by decide, c4320_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4320_b5, by decide, c4320_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4320_b6, by decide, c4320_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4320_b7, by decide, c4320_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4320_b8, by decide, c4320_ok8⟩, ?_⟩
  simp

def s19 : List Nat := [18889471560978115133441, 4722372112369179688961, 1208925821022004058587137, 302231459688731898085377, 75557869355413857959937, 18889467338853481250817, 302231455185132287426561, 75557864851814247301121, 4722367890244545806337, 4722372112369179426833, 1208925821022004058325009, 302231459688731897823249, 75557869355413857697809, 4722367890244545544209, 302231455185132287229969, 75557864851814247104529, 1407374900396049, 18889470716553185001729, 4722371267944249557249, 1208925819896104151744769, 75557868229513951117569, 4785074604409089, 18889466212953574408449, 75557863725914340458753, 4722366764344638963969, 4722371267944249295121, 1208925819896104151482641, 75557868229513950855441, 4785074604146961, 4722366764344638701841, 75557863725914340262161, 281474993553681]
theorem e19 : enumKeys 1163 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4321_b3, by decide, c4321_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 271, c4320_b9, by decide, c4320_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4321_b7, by decide, c4321_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4321_b6, by decide, c4321_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4321_b5, by decide, c4321_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4321_b4, by decide, c4321_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4321_b1, by decide, c4321_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4321_b0, by decide, c4321_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4321_b2, by decide, c4321_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 279, c4322_b6, by decide, c4322_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4323_b0, by decide, c4323_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4322_b9, by decide, c4322_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4322_b8, by decide, c4322_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4322_b7, by decide, c4322_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4323_b2, by decide, c4323_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4323_b1, by decide, c4323_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4323_b3, by decide, c4323_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4322_b1, by decide, c4322_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4321_b8, by decide, c4321_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4322_b4, by decide, c4322_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4322_b3, by decide, c4322_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4322_b5, by decide, c4322_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 211, c4322_b2, by decide, c4322_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 273, c4321_b9, by decide, c4321_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4322_b0, by decide, c4322_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4323_b4, by decide, c4323_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4323_b7, by decide, c4323_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4323_b6, by decide, c4323_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4323_b8, by decide, c4323_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4323_b5, by decide, c4323_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4323_b9, by decide, c4323_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4324_b0, by decide, c4324_ok0⟩, ?_⟩
  simp

def s20 : List Nat := [18889484227352067112961, 4722384778743131668481, 4835703279021466652573697, 75557882021787809939457, 18889466494428601450497, 75557864007389367500801, 4722367045819666006017, 4722384778743131406353, 4835703279021466652311569, 75557882021787809677329, 4722367045819665743889, 75557864007389367304209, 562950020595729, 18889466494428534345729, 4722367045819598901249, 75557864007389300461569, 562949953753089, 4722367045819598639121, 75557864007389300199441, 562949953490961]
theorem e20 : enumKeys 1163 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4324_b4, by decide, c4324_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4324_b1, by decide, c4324_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4324_b7, by decide, c4324_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4324_b6, by decide, c4324_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4324_b5, by decide, c4324_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 247, c4324_b2, by decide, c4324_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 197, c4324_b3, by decide, c4324_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4325_b2, by decide, c4325_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4325_b5, by decide, c4325_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4325_b4, by decide, c4325_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4325_b3, by decide, c4325_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 207, c4325_b6, by decide, c4325_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4325_b7, by decide, c4325_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4324_b9, by decide, c4324_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4324_b8, by decide, c4324_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4325_b0, by decide, c4325_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4325_b1, by decide, c4325_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4325_b8, by decide, c4325_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4325_b9, by decide, c4325_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4326_b0, by decide, c4326_ok0⟩, ?_⟩
  simp

def s21 : List Nat := [18889466494428534603777, 4722367045819599159297, 75557864288864277364737, 18889466494428534341649, 4722367045819598897169, 75557864288864277168145, 4722367045819598635041, 75557864288864276906017]
theorem e21 : enumKeys 1163 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4326_b3, by decide, c4326_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4326_b2, by decide, c4326_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4326_b1, by decide, c4326_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4326_b5, by decide, c4326_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 232, c4326_b4, by decide, c4326_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4326_b6, by decide, c4326_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4326_b7, by decide, c4326_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4326_b8, by decide, c4326_ok8⟩, ?_⟩
  simp

def s22 : List Nat := [1208925821866428988522497, 302231460533156828020737, 302231456029557217361921, 4722368734669475741697, 4722372112369179492609, 1208925820740529081680129, 302231459407256921178369, 5629499534344449, 302231454903657310519553, 4722367608769568899329, 4722370986469272650241, 1208925819614629174837761, 4503599627502081, 4722366482869662056961]
theorem e22 : enumKeys 1163 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4327_b2, by decide, c4327_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4327_b1, by decide, c4327_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 304, c4326_b9, by decide, c4326_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 248, c4327_b0, by decide, c4327_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4327_b3, by decide, c4327_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4327_b7, by decide, c4327_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4327_b6, by decide, c4327_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4327_b8, by decide, c4327_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 315, c4327_b4, by decide, c4327_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4327_b5, by decide, c4327_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4327_b9, by decide, c4327_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4328_b1, by decide, c4328_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4328_b2, by decide, c4328_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4328_b0, by decide, c4328_ok0⟩, ?_⟩
  simp

def s23 : List Nat := [4722385623168061603841, 4835703279865891582509057, 302231473199530780000257, 75557882866212739874817, 302231455185132337561601, 75557864851814297436161, 4722367890244595941377, 4722384778743131472129, 4835703278739991675666689, 75557881740312833032449, 18295873486323969, 75557863725914390593793, 4722366764344689099009, 4722367890244528836609, 302231455185132270522369, 75557864851814230396929, 1407374883688449, 4722366764344621994241, 75557863725914323554561, 281474976846081]
theorem e23 : enumKeys 1163 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4328_b3, by decide, c4328_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4328_b9, by decide, c4328_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4328_b8, by decide, c4328_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 215, c4328_b7, by decide, c4328_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c4328_b5, by decide, c4328_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 283, c4328_b4, by decide, c4328_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4328_b6, by decide, c4328_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4329_b4, by decide, c4329_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4329_b8, by decide, c4329_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4329_b7, by decide, c4329_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4329_b9, by decide, c4329_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4329_b5, by decide, c4329_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4329_b6, by decide, c4329_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4329_b0, by decide, c4329_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4329_b2, by decide, c4329_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 223, c4329_b1, by decide, c4329_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4329_b3, by decide, c4329_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 226, c4330_b0, by decide, c4330_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4330_b1, by decide, c4330_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 208, c4330_b2, by decide, c4330_ok2⟩, ?_⟩
  simp

def s24 : List Nat := [18889467338853464539137, 302231455466607247425537, 4722367890244529094657, 75557865133289207300097, 4722367890244528832529, 302231455466607247228945, 75557865133289207103505, 18889466494428534407425, 75557864007389300457729, 4722367045819598962945, 4722367045819598700817, 75557864007389300261137, 562949953552657]
theorem e24 : enumKeys 1163 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4330_b6, by decide, c4330_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4330_b5, by decide, c4330_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 255, c4330_b4, by decide, c4330_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4330_b3, by decide, c4330_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4331_b0, by decide, c4331_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4331_b2, by decide, c4331_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4331_b1, by decide, c4331_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4330_b9, by decide, c4330_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4330_b7, by decide, c4330_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4330_b8, by decide, c4330_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4331_b3, by decide, c4331_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4331_b4, by decide, c4331_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4331_b5, by decide, c4331_ok5⟩, ?_⟩
  simp

def s25 : List Nat := [302231456311032177360897, 4722368734669459030017, 75557865977714137235457, 302231455185132270518529, 75557864851814230393089, 4722367890244528898305, 75557863725914323550721, 4722366764344622055937]
theorem e25 : enumKeys 1163 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4331_b8, by decide, c4331_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4331_b7, by decide, c4331_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4331_b6, by decide, c4331_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4332_b0, by decide, c4332_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4331_b9, by decide, c4331_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4332_b1, by decide, c4332_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4332_b2, by decide, c4332_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4332_b3, by decide, c4332_ok3⟩, ?_⟩
  simp

def s26 : List Nat := [4835703287465715953565698, 1208925842132627311558658, 4835703282962116342972418, 1208925837629027700965378, 22517998153629698, 4835703278458516732379138, 18014398543036418, 1208925824118228869185538, 9007199321849858, 1208925819614629258592258, 4503599711256578, 1208925824118228802080770, 9007199254745090, 1208925819614629191487490, 4503599644151810, 33558530]
theorem e26 : enumKeys 1163 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4332_b5, by decide, c4332_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4332_b4, by decide, c4332_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4332_b9, by decide, c4332_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4332_b8, by decide, c4332_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 185, c4333_b0, by decide, c4333_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4333_b3, by decide, c4333_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4333_b4, by decide, c4333_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4332_b6, by decide, c4332_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 206, c4332_b7, by decide, c4332_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 183, c4333_b1, by decide, c4333_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4333_b2, by decide, c4333_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4333_b5, by decide, c4333_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4333_b6, by decide, c4333_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4333_b7, by decide, c4333_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4333_b8, by decide, c4333_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4333_b9, by decide, c4333_ok9⟩, ?_⟩
  simp

def s27 : List Nat := [18889474938677835595778, 1208925824399703779049474, 75557872733113578422274, 18889470716553201713154, 1208925819896104168456194, 75557868229513967828994, 4785074621120514, 18889466212953591119874, 1208925824399703778787346, 75557872733113578160146, 1208925819896104168194066, 75557868229513967566866, 4785074620858386, 75557863725914356973586, 281475010265106]
theorem e27 : enumKeys 1163 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 238, c4334_b0, by decide, c4334_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4334_b4, by decide, c4334_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4334_b3, by decide, c4334_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4334_b1, by decide, c4334_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 167, c4334_b6, by decide, c4334_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 195, c4334_b5, by decide, c4334_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 177, c4334_b7, by decide, c4334_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4334_b2, by decide, c4334_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4334_b9, by decide, c4334_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4334_b8, by decide, c4334_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4335_b1, by decide, c4335_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4335_b0, by decide, c4335_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4335_b2, by decide, c4335_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4335_b3, by decide, c4335_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4335_b4, by decide, c4335_ok4⟩, ?_⟩
  simp

def s28 : List Nat := [1208925825244128708984834, 302231463910856548483074, 4722372112369196204034, 1208925820740529098391554, 302231459407256937889794, 5629499551055874, 302231454903657327230978, 4722367608769585610754, 4722375490068899954946, 1208925824118228802142466, 9007199254806786, 4722370986469289361666, 1208925819614629191549186, 4503599644213506, 4722366482869678768386]
theorem e28 : enumKeys 1163 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4335_b9, by decide, c4335_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4335_b8, by decide, c4335_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4335_b5, by decide, c4335_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 203, c4336_b1, by decide, c4336_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 231, c4336_b0, by decide, c4336_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4336_b2, by decide, c4336_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 280, c4335_b6, by decide, c4335_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4335_b7, by decide, c4335_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4336_b3, by decide, c4336_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4336_b6, by decide, c4336_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4336_b7, by decide, c4336_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4336_b4, by decide, c4336_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4336_b8, by decide, c4336_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4336_b9, by decide, c4336_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4336_b5, by decide, c4336_ok5⟩, ?_⟩
  simp

def s29 : List Nat := [4722389000867782066178, 4835703283243591302971394, 1208925837910502660964354, 75557886243912460337154, 4722384778743148183554, 4835703278739991692378114, 75557881740312849743874, 18295873503035394, 4722371267944316403714, 1208925819896104218591234, 75557868229514017964034, 4785074671255554, 75557863725914407305218, 4722366764344705810434, 4722371267944249298946, 1208925819896104151486466, 75557868229513950859266, 4785074604150786, 4722366764344638705666, 75557863725914340265986, 281474993557506]
theorem e29 : enumKeys 1163 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4337_b0, by decide, c4337_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 179, c4337_b7, by decide, c4337_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 170, c4337_b6, by decide, c4337_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 191, c4337_b5, by decide, c4337_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4337_b2, by decide, c4337_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 173, c4338_b2, by decide, c4338_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 189, c4338_b1, by decide, c4338_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 171, c4338_b3, by decide, c4338_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 213, c4337_b1, by decide, c4337_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 182, c4337_b9, by decide, c4337_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4337_b8, by decide, c4337_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4338_b0, by decide, c4338_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 253, c4337_b3, by decide, c4337_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4337_b4, by decide, c4337_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 202, c4338_b4, by decide, c4338_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 176, c4338_b7, by decide, c4338_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 200, c4338_b6, by decide, c4338_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4338_b8, by decide, c4338_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4338_b5, by decide, c4338_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 194, c4338_b9, by decide, c4338_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 178, c4339_b0, by decide, c4339_ok0⟩, ?_⟩
  simp

def s30 : List Nat := [18889470716553185001474, 4722371267944249556994, 1208925820177579128455170, 75557868510988927827970, 18889466494428551118850, 75557864007389317169154, 4722367045819615674370, 4722371267944249294866, 1208925820177579128193042, 75557868510988927565842, 4722367045819615412242, 75557864007389316972562, 562949970264082]
theorem e30 : enumKeys 1163 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 224, c4339_b4, by decide, c4339_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 233, c4339_b1, by decide, c4339_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 166, c4339_b7, by decide, c4339_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 187, c4339_b6, by decide, c4339_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 175, c4339_b5, by decide, c4339_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4339_b2, by decide, c4339_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4339_b3, by decide, c4339_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 234, c4339_b8, by decide, c4339_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4340_b1, by decide, c4340_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4340_b0, by decide, c4340_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4339_b9, by decide, c4339_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4340_b2, by decide, c4340_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4340_b3, by decide, c4340_ok3⟩, ?_⟩
  simp

def s31 : List Nat := [4722372112369179492354, 1208925821022004058390530, 302231459688731897888770, 75557869355413857763330, 302231455185132287229954, 75557864851814247104514, 4722367890244545609730, 4722371267944249360642, 1208925819896104151548162, 75557868229513950920962, 4785074604212482, 75557863725914340262146, 4722366764344638767362]
theorem e31 : enumKeys 1163 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4340_b4, by decide, c4340_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 196, c4341_b0, by decide, c4341_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4340_b9, by decide, c4340_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4340_b8, by decide, c4340_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4340_b6, by decide, c4340_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4340_b5, by decide, c4340_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4340_b7, by decide, c4340_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4341_b1, by decide, c4341_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4341_b5, by decide, c4341_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4341_b4, by decide, c4341_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4341_b6, by decide, c4341_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4341_b2, by decide, c4341_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4341_b3, by decide, c4341_ok3⟩, ?_⟩
  simp

def s32 : List Nat := [4722384778743131471874, 4835703279021466652377090, 75557882021787809742850, 75557864007389367304194, 4722367045819665809410, 4722367045819598704642, 75557864007389300264962, 562949953556482]
theorem e32 : enumKeys 1163 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4341_b7, by decide, c4341_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4342_b1, by decide, c4342_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4342_b0, by decide, c4342_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 245, c4341_b8, by decide, c4341_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 199, c4341_b9, by decide, c4341_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 190, c4342_b2, by decide, c4342_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 188, c4342_b3, by decide, c4342_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 172, c4342_b4, by decide, c4342_ok4⟩, ?_⟩
  simp

def s33 : List Nat := [18889466494428534407170, 4722367045819598962690, 75557864288864277168130, 4722367045819598700562, 75557864288864276971538]
theorem e33 : enumKeys 1163 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4342_b7, by decide, c4342_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 219, c4342_b6, by decide, c4342_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4342_b5, by decide, c4342_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4342_b8, by decide, c4342_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 184, c4342_b9, by decide, c4342_ok9⟩, ?_⟩
  simp

def s34 : List Nat := [302231455466607247228930, 4722367890244528898050, 75557865133289207103490, 75557864007389300261122, 4722367045819598766338]
theorem e34 : enumKeys 1163 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4343_b2, by decide, c4343_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4343_b1, by decide, c4343_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4343_b0, by decide, c4343_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4343_b3, by decide, c4343_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4343_b4, by decide, c4343_ok4⟩, ?_⟩
  simp

def s35 : List Nat := [1208925828621828429447171, 1208925824118228818853891, 9007199271518211, 1208925819614629208260611, 4503599660924931]
theorem e35 : enumKeys 1163 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4343_b5, by decide, c4343_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4343_b6, by decide, c4343_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4343_b7, by decide, c4343_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4343_b8, by decide, c4343_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4343_b9, by decide, c4343_ok9⟩, ?_⟩
  simp

def s36 : List Nat := [4722375490068899954691, 1208925824399703778852867, 75557872733113578225667, 4722371267944266072067, 1208925819896104168259587, 75557868229513967632387, 4785074620923907, 75557863725914356973571, 4722366764344655478787]
theorem e36 : enumKeys 1163 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4344_b0, by decide, c4344_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4344_b5, by decide, c4344_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4344_b4, by decide, c4344_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4344_b1, by decide, c4344_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 174, c4344_b7, by decide, c4344_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 198, c4344_b6, by decide, c4344_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 180, c4344_b8, by decide, c4344_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4344_b2, by decide, c4344_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 192, c4344_b3, by decide, c4344_ok3⟩, ?_⟩
  simp

def s37 : List Nat := [4722371267944249360387, 1208925820177579128258563, 75557868510988927631363, 75557864007389316972547, 4722367045819615477763]
theorem e37 : enumKeys 1163 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4344_b9, by decide, c4344_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 168, c4345_b3, by decide, c4345_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4345_b2, by decide, c4345_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4345_b0, by decide, c4345_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 186, c4345_b1, by decide, c4345_ok1⟩, ?_⟩
  simp

def s38 : List Nat := [4722367045819598766083, 75557864288864276971523]
theorem e38 : enumKeys 1163 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4345_b5, by decide, c4345_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4345_b4, by decide, c4345_ok4⟩, ?_⟩
  simp

/-- every enumerated key with left type `1163` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 1163 mR,
    (1163 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 1163 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K37
end Grid3.Three.Cert
