import Grid3.Three.Cert.Types
import Grid3.Three.Cert.Data.C4345
import Grid3.Three.Cert.Data.C4346
import Grid3.Three.Cert.Data.C4347
import Grid3.Three.Cert.Data.C4348
import Grid3.Three.Cert.Data.C4349
import Grid3.Three.Cert.Data.C4350
import Grid3.Three.Cert.Data.C4351
import Grid3.Three.Cert.Data.C4352
import Grid3.Three.Cert.Data.C4353
import Grid3.Three.Cert.Data.C4354
import Grid3.Three.Cert.Data.C4355
import Grid3.Three.Cert.Data.C4356
import Grid3.Three.Cert.Data.C4357
import Grid3.Three.Cert.Data.C4358
import Grid3.Three.Cert.Data.C4359
import Grid3.Three.Cert.Data.C4360
import Grid3.Three.Cert.Data.C4361
import Grid3.Three.Cert.Data.C4362
import Grid3.Three.Cert.Data.C4363
import Grid3.Three.Cert.Data.C4364
import Grid3.Three.Cert.Data.C4365
import Grid3.Three.Cert.Data.C4366
import Grid3.Three.Cert.Data.C4367
import Grid3.Three.Cert.Data.C4368
import Grid3.Three.Cert.Data.C4369
import Grid3.Three.Cert.Data.C4370
import Grid3.Three.Cert.Data.C4371
import Grid3.Three.Cert.Data.C4372
import Grid3.Three.Cert.Data.C4373

/-! Seam keys with left type `207` (type index 38): the enumeration equals the stored keys, and
every stored key has a kernel-checked record. Generated by `ai_research_notes/cx/k3rev/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K38

def s00 : List Nat := [54043195528445952, 36028797086072832, 18014398643699712, 201326592, 36028797018968064, 18014398576594944, 134221824, 18014398509490176, 67117056, 12288]
theorem e00 : enumKeys 207 12288 = s00 := by decide +kernel
theorem r00 : ∀ M ∈ s00, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 12288 M ne blob = true := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c4345_b6, by decide, c4345_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4345_b7, by decide, c4345_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4345_b8, by decide, c4345_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c4345_b9, by decide, c4345_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c4346_b0, by decide, c4346_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 230, c4346_b1, by decide, c4346_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4346_b2, by decide, c4346_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 222, c4346_b3, by decide, c4346_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 228, c4346_b4, by decide, c4346_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨1, 216, c4346_b5, by decide, c4346_ok5⟩, ?_⟩
  simp

def s01 : List Nat := [23643898043957248, 19140298433363968, 5629499601584128, 1125899990990848, 23643898043695120, 19140298433101840, 5629499601322000, 1125899990728720, 22517998137114880, 18014398526521600, 4503599694741760, 84148480, 22517998136852752, 18014398526259472, 4503599694479632, 83886352, 5629499534479360, 1125899923886080, 5629499534217232, 1125899923623952, 4503599627636992, 17043712, 4503599627374864, 16781584]
theorem e01 : enumKeys 207 5392 = s01 := by decide +kernel
theorem r01 : ∀ M ∈ s01, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5392 M ne blob = true := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4346_b6, by decide, c4346_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4346_b8, by decide, c4346_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4346_b7, by decide, c4346_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4346_b9, by decide, c4346_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4347_b8, by decide, c4347_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4348_b0, by decide, c4348_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4347_b9, by decide, c4347_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4348_b1, by decide, c4348_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4347_b2, by decide, c4347_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4347_b4, by decide, c4347_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 274, c4347_b3, by decide, c4347_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4347_b5, by decide, c4347_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4348_b4, by decide, c4348_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4348_b6, by decide, c4348_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 286, c4348_b5, by decide, c4348_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 267, c4348_b7, by decide, c4348_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4347_b0, by decide, c4347_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 250, c4347_b1, by decide, c4347_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 270, c4348_b2, by decide, c4348_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4348_b3, by decide, c4348_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 265, c4347_b6, by decide, c4347_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4347_b7, by decide, c4347_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4348_b8, by decide, c4348_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4348_b9, by decide, c4348_ok9⟩, ?_⟩
  simp

def s02 : List Nat := [36310271995936768, 18295873553563648, 281475111190528, 36310271995674640, 18295873553301520, 281475110928400, 18295873486458880, 281475044085760, 18295873486196752, 281475043823632, 281474976980992, 281474976718864]
theorem e02 : enumKeys 207 8272 = s02 := by decide +kernel
theorem r02 : ∀ M ∈ s02, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8272 M ne blob = true := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4349_b0, by decide, c4349_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4349_b1, by decide, c4349_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4349_b2, by decide, c4349_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4349_b6, by decide, c4349_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4349_b7, by decide, c4349_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4349_b8, by decide, c4349_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4349_b3, by decide, c4349_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4349_b4, by decide, c4349_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4349_b9, by decide, c4349_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4350_b0, by decide, c4350_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4349_b5, by decide, c4349_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4350_b1, by decide, c4350_ok1⟩, ?_⟩
  simp

def s03 : List Nat := [5910974511448064, 1407374900854784, 5910974511185936, 1407374900592656, 5910974510923808, 1407374900330528, 4785074604605696, 281474994012416, 4785074604343568, 281474993750288, 4785074604081440, 281474993488160]
theorem e03 : enumKeys 207 1376 = s03 := by decide +kernel
theorem r03 : ∀ M ∈ s03, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1376 M ne blob = true := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4350_b2, by decide, c4350_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4350_b3, by decide, c4350_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4350_b6, by decide, c4350_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4350_b7, by decide, c4350_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4351_b0, by decide, c4351_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4351_b1, by decide, c4351_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4350_b4, by decide, c4350_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4350_b5, by decide, c4350_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4350_b8, by decide, c4350_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4350_b9, by decide, c4350_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4351_b2, by decide, c4351_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4351_b3, by decide, c4351_ok3⟩, ?_⟩
  simp

def s04 : List Nat := [18577348463427584, 562950021054464, 18577348463165456, 562950020792336, 18577348462903328, 562950020530208, 562949953949696, 562949953687568, 562949953425440]
theorem e04 : enumKeys 207 4256 = s04 := by decide +kernel
theorem r04 : ∀ M ∈ s04, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4256 M ne blob = true := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4351_b4, by decide, c4351_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4351_b5, by decide, c4351_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4351_b7, by decide, c4351_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4351_b8, by decide, c4351_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4352_b0, by decide, c4352_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4352_b1, by decide, c4352_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4351_b6, by decide, c4351_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4351_b9, by decide, c4351_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4352_b2, by decide, c4352_ok2⟩, ?_⟩
  simp

def s05 : List Nat := [844424930918400, 844424930656272, 844424930394144, 844424930132016]
theorem e05 : enumKeys 207 240 = s05 := by decide +kernel
theorem r05 : ∀ M ∈ s05, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 240 M ne blob = true := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4352_b3, by decide, c4352_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4352_b4, by decide, c4352_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4352_b5, by decide, c4352_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4352_b6, by decide, c4352_ok6⟩, ?_⟩
  simp

def s06 : List Nat := [37154696925872128, 19140298483499008, 1125900041125888, 36028797019029760, 18014398576656640, 134283520, 19140298416394240, 1125899974021120, 18014398509551872, 67178752, 1125899906916352, 73984]
theorem e06 : enumKeys 207 8452 = s06 := by decide +kernel
theorem r06 : ∀ M ∈ s06, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8452 M ne blob = true := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4352_b7, by decide, c4352_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4352_b8, by decide, c4352_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4352_b9, by decide, c4352_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4353_b3, by decide, c4353_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4353_b4, by decide, c4353_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4353_b5, by decide, c4353_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4353_b0, by decide, c4353_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 268, c4353_b1, by decide, c4353_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4353_b6, by decide, c4353_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4353_b7, by decide, c4353_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 262, c4353_b2, by decide, c4353_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4353_b8, by decide, c4353_ok8⟩, ?_⟩
  simp

def s07 : List Nat := [6755399441383424, 2251799830790144, 6755399441121296, 2251799830528016, 5629499534541056, 1125899923947776, 5629499534278928, 1125899923685648, 4503599627698688, 17105408, 4503599627436560, 16843280]
theorem e07 : enumKeys 207 1556 = s07 := by decide +kernel
theorem r07 : ∀ M ∈ s07, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1556 M ne blob = true := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4353_b9, by decide, c4353_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4354_b0, by decide, c4354_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4354_b5, by decide, c4354_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4354_b6, by decide, c4354_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4354_b1, by decide, c4354_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4354_b2, by decide, c4354_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 308, c4354_b7, by decide, c4354_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4354_b8, by decide, c4354_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 302, c4354_b3, by decide, c4354_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 282, c4354_b4, by decide, c4354_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4354_b9, by decide, c4354_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4355_b0, by decide, c4355_ok0⟩, ?_⟩
  simp

def s08 : List Nat := [19421773393362944, 1407374950989824, 19421773393100816, 1407374950727696, 18295873486520576, 281475044147456, 18295873486258448, 281475043885328, 1407374883885056, 1407374883622928, 281474977042688, 281474976780560]
theorem e08 : enumKeys 207 4436 = s08 := by decide +kernel
theorem r08 : ∀ M ∈ s08, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4436 M ne blob = true := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4355_b1, by decide, c4355_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4355_b2, by decide, c4355_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4355_b7, by decide, c4355_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4355_b8, by decide, c4355_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4355_b4, by decide, c4355_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4355_b5, by decide, c4355_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4356_b0, by decide, c4356_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4356_b1, by decide, c4356_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4355_b3, by decide, c4355_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4355_b9, by decide, c4355_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4355_b6, by decide, c4355_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4356_b2, by decide, c4356_ok2⟩, ?_⟩
  simp

def s09 : List Nat := [1688849860853760, 1688849860591632, 1688849860329504, 562949954011392, 562949953749264, 562949953487136]
theorem e09 : enumKeys 207 420 = s09 := by decide +kernel
theorem r09 : ∀ M ∈ s09, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 420 M ne blob = true := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4356_b3, by decide, c4356_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4356_b5, by decide, c4356_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4356_b7, by decide, c4356_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4356_b4, by decide, c4356_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4356_b6, by decide, c4356_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4356_b8, by decide, c4356_ok8⟩, ?_⟩
  simp

def s10 : List Nat := [20266198323298304, 2251799880925184, 19140298416455936, 1125899974082816, 18014398509613568, 67240448, 2251799813820416, 1125899906978048, 135680]
theorem e10 : enumKeys 207 4616 = s10 := by decide +kernel
theorem r10 : ∀ M ∈ s10, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4616 M ne blob = true := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4356_b9, by decide, c4356_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4357_b0, by decide, c4357_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4357_b2, by decide, c4357_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 306, c4357_b3, by decide, c4357_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4357_b5, by decide, c4357_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4357_b6, by decide, c4357_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 296, c4357_b1, by decide, c4357_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 299, c4357_b4, by decide, c4357_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4357_b7, by decide, c4357_ok7⟩, ?_⟩
  simp

def s11 : List Nat := [2533274790789120, 2533274790526992, 1407374883946752, 1407374883684624, 281474977104384, 281474976842256]
theorem e11 : enumKeys 207 600 = s11 := by decide +kernel
theorem r11 : ∀ M ∈ s11, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 600 M ne blob = true := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4357_b8, by decide, c4357_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4358_b1, by decide, c4358_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4357_b9, by decide, c4357_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4358_b2, by decide, c4358_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4358_b0, by decide, c4358_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4358_b3, by decide, c4358_ok3⟩, ?_⟩
  simp

def s12 : List Nat := [3377699720724480, 2251799813882112, 1125899907039744, 197376]
theorem e12 : enumKeys 207 780 = s12 := by decide +kernel
theorem r12 : ∀ M ∈ s12, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 780 M ne blob = true := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4358_b4, by decide, c4358_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4358_b5, by decide, c4358_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 336, c4358_b6, by decide, c4358_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 324, c4358_b7, by decide, c4358_ok7⟩, ?_⟩
  simp

def s13 : List Nat := [40532396646334465, 36028797035741185, 22517998203961345, 18014398593368065, 4503599761588225, 150994945, 22517998136856577, 18014398526263297, 4503599694483457, 83890177, 4503599627378689, 16785409]
theorem e13 : enumKeys 207 9217 = s13 := by decide +kernel
theorem r13 : ∀ M ∈ s13, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 9217 M ne blob = true := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4358_b8, by decide, c4358_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4359_b1, by decide, c4359_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4358_b9, by decide, c4358_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 220, c4359_b2, by decide, c4359_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 244, c4359_b0, by decide, c4359_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4359_b3, by decide, c4359_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 225, c4359_b4, by decide, c4359_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4359_b6, by decide, c4359_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 241, c4359_b5, by decide, c4359_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4359_b7, by decide, c4359_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4359_b8, by decide, c4359_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4359_b9, by decide, c4359_ok9⟩, ?_⟩
  simp

def s14 : List Nat := [10133099161845761, 5629499551252481, 1125899940659201, 10133099161583633, 5629499550990353, 1125899940397073, 9007199255003393, 4503599644410113, 33816833, 9007199254741265, 4503599644147985, 33554705]
theorem e14 : enumKeys 207 2321 = s14 := by decide +kernel
theorem r14 : ∀ M ∈ s14, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2321 M ne blob = true := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4360_b0, by decide, c4360_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4360_b1, by decide, c4360_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4360_b2, by decide, c4360_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4360_b6, by decide, c4360_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4360_b7, by decide, c4360_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4360_b8, by decide, c4360_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 266, c4360_b3, by decide, c4360_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 260, c4360_b4, by decide, c4360_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 240, c4360_b5, by decide, c4360_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4360_b9, by decide, c4360_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4361_b0, by decide, c4361_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4361_b1, by decide, c4361_ok1⟩, ?_⟩
  simp

def s15 : List Nat := [22799473113825281, 18295873503232001, 4785074671452161, 281475060858881, 22799473113563153, 18295873502969873, 4785074671190033, 281475060596753, 4785074604347393, 281474993754113, 4785074604085265, 281474993491985]
theorem e15 : enumKeys 207 5201 = s15 := by decide +kernel
theorem r15 : ∀ M ∈ s15, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5201 M ne blob = true := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4361_b2, by decide, c4361_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4361_b4, by decide, c4361_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4361_b3, by decide, c4361_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4361_b5, by decide, c4361_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4361_b8, by decide, c4361_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4362_b0, by decide, c4362_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4361_b9, by decide, c4361_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 230, c4362_b1, by decide, c4362_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4361_b6, by decide, c4361_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 209, c4361_b7, by decide, c4361_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4362_b2, by decide, c4362_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4362_b3, by decide, c4362_ok3⟩, ?_⟩
  simp

def s16 : List Nat := [5066549581316097, 562949970722817, 5066549581053969, 562949970460689, 5066549580791841, 562949970198561]
theorem e16 : enumKeys 207 1185 = s16 := by decide +kernel
theorem r16 : ∀ M ∈ s16, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1185 M ne blob = true := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4362_b4, by decide, c4362_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4362_b5, by decide, c4362_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4362_b6, by decide, c4362_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4362_b7, by decide, c4362_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4362_b8, by decide, c4362_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4362_b9, by decide, c4362_ok9⟩, ?_⟩
  simp

def s17 : List Nat := [23643898043760641, 19140298433167361, 5629499601387521, 1125899990794241, 22517998136918273, 18014398526324993, 4503599694545153, 83951873, 5629499534282753, 1125899923689473, 4503599627440385, 16847105]
theorem e17 : enumKeys 207 5381 = s17 := by decide +kernel
theorem r17 : ∀ M ∈ s17, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5381 M ne blob = true := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4363_b0, by decide, c4363_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 251, c4363_b2, by decide, c4363_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 272, c4363_b1, by decide, c4363_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4363_b3, by decide, c4363_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4363_b6, by decide, c4363_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 254, c4363_b8, by decide, c4363_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 278, c4363_b7, by decide, c4363_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4363_b9, by decide, c4363_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 263, c4363_b4, by decide, c4363_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 257, c4363_b5, by decide, c4363_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4364_b0, by decide, c4364_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4364_b1, by decide, c4364_ok1⟩, ?_⟩
  simp

def s18 : List Nat := [36310271995740161, 18295873553367041, 281475110993921, 18295873486262273, 281475043889153, 281474976784385]
theorem e18 : enumKeys 207 8261 = s18 := by decide +kernel
theorem r18 : ∀ M ∈ s18, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8261 M ne blob = true := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4364_b2, by decide, c4364_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4364_b3, by decide, c4364_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4364_b4, by decide, c4364_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 218, c4364_b5, by decide, c4364_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 227, c4364_b6, by decide, c4364_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4364_b7, by decide, c4364_ok7⟩, ?_⟩
  simp

def s19 : List Nat := [5910974511251457, 1407374900658177, 5910974510989329, 1407374900396049, 4785074604409089, 281474993815809, 4785074604146961, 281474993553681]
theorem e19 : enumKeys 207 1365 = s19 := by decide +kernel
theorem r19 : ∀ M ∈ s19, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1365 M ne blob = true := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4364_b8, by decide, c4364_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4364_b9, by decide, c4364_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4365_b2, by decide, c4365_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4365_b3, by decide, c4365_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4365_b0, by decide, c4365_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 246, c4365_b1, by decide, c4365_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4365_b4, by decide, c4365_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4365_b5, by decide, c4365_ok5⟩, ?_⟩
  simp

def s20 : List Nat := [18577348463230977, 562950020857857, 18577348462968849, 562950020595729, 562949953753089, 562949953490961]
theorem e20 : enumKeys 207 4245 = s20 := by decide +kernel
theorem r20 : ∀ M ∈ s20, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4245 M ne blob = true := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4365_b6, by decide, c4365_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4365_b7, by decide, c4365_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4365_b9, by decide, c4365_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4366_b0, by decide, c4366_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4365_b8, by decide, c4365_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4366_b1, by decide, c4366_ok1⟩, ?_⟩
  simp

def s21 : List Nat := [844424930721793, 844424930459665, 844424930197537]
theorem e21 : enumKeys 207 229 = s21 := by decide +kernel
theorem r21 : ∀ M ∈ s21, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 229 M ne blob = true := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4366_b2, by decide, c4366_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4366_b3, by decide, c4366_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4366_b4, by decide, c4366_ok4⟩, ?_⟩
  simp

def s22 : List Nat := [6755399441186817, 2251799830593537, 5629499534344449, 1125899923751169, 4503599627502081, 16908801]
theorem e22 : enumKeys 207 1545 = s22 := by decide +kernel
theorem r22 : ∀ M ∈ s22, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1545 M ne blob = true := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4366_b5, by decide, c4366_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4366_b6, by decide, c4366_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 301, c4366_b7, by decide, c4366_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4366_b8, by decide, c4366_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 300, c4366_b9, by decide, c4366_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4367_b0, by decide, c4367_ok0⟩, ?_⟩
  simp

def s23 : List Nat := [19421773393166337, 1407374950793217, 18295873486323969, 281475043950849, 1407374883688449, 281474976846081]
theorem e23 : enumKeys 207 4425 = s23 := by decide +kernel
theorem r23 : ∀ M ∈ s23, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4425 M ne blob = true := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4367_b1, by decide, c4367_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4367_b2, by decide, c4367_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4367_b4, by decide, c4367_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4367_b5, by decide, c4367_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 256, c4367_b3, by decide, c4367_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4367_b6, by decide, c4367_ok6⟩, ?_⟩
  simp

def s24 : List Nat := [1688849860657153, 1688849860395025, 562949953814785, 562949953552657]
theorem e24 : enumKeys 207 409 = s24 := by decide +kernel
theorem r24 : ∀ M ∈ s24, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 409 M ne blob = true := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4367_b7, by decide, c4367_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4367_b9, by decide, c4367_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4367_b8, by decide, c4367_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4368_b0, by decide, c4368_ok0⟩, ?_⟩
  simp

def s25 : List Nat := [2533274790592513, 1407374883750145, 281474976907777]
theorem e25 : enumKeys 207 589 = s25 := by decide +kernel
theorem r25 : ∀ M ∈ s25, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 589 M ne blob = true := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4368_b1, by decide, c4368_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 294, c4368_b2, by decide, c4368_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 288, c4368_b3, by decide, c4368_ok3⟩, ?_⟩
  simp

def s26 : List Nat := [27021597764222978, 22517998153629698, 18014398543036418, 9007199321849858, 4503599711256578, 100663298, 9007199254745090, 4503599644151810, 33558530]
theorem e26 : enumKeys 207 6146 = s26 := by decide +kernel
theorem r26 : ∀ M ∈ s26, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 6146 M ne blob = true := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4368_b4, by decide, c4368_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 221, c4368_b6, by decide, c4368_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 212, c4368_b8, by decide, c4368_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 242, c4368_b5, by decide, c4368_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 236, c4368_b7, by decide, c4368_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4368_b9, by decide, c4368_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4369_b0, by decide, c4369_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4369_b1, by decide, c4369_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4369_b2, by decide, c4369_ok2⟩, ?_⟩
  simp

def s27 : List Nat := [9288674231713794, 4785074621120514, 281475010527234, 9288674231451666, 4785074620858386, 281475010265106]
theorem e27 : enumKeys 207 2130 = s27 := by decide +kernel
theorem r27 : ∀ M ∈ s27, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2130 M ne blob = true := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4369_b3, by decide, c4369_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 217, c4369_b4, by decide, c4369_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 204, c4369_b5, by decide, c4369_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4369_b6, by decide, c4369_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4369_b7, by decide, c4369_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4369_b8, by decide, c4369_ok8⟩, ?_⟩
  simp

def s28 : List Nat := [10133099161649154, 5629499551055874, 1125899940462594, 9007199254806786, 4503599644213506, 33620226]
theorem e28 : enumKeys 207 2310 = s28 := by decide +kernel
theorem r28 : ∀ M ∈ s28, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2310 M ne blob = true := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4369_b9, by decide, c4369_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 259, c4370_b0, by decide, c4370_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4370_b1, by decide, c4370_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4370_b2, by decide, c4370_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 264, c4370_b3, by decide, c4370_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4370_b4, by decide, c4370_ok4⟩, ?_⟩
  simp

def s29 : List Nat := [22799473113628674, 18295873503035394, 4785074671255554, 281475060662274, 4785074604150786, 281474993557506]
theorem e29 : enumKeys 207 5190 = s29 := by decide +kernel
theorem r29 : ∀ M ∈ s29, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5190 M ne blob = true := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4370_b5, by decide, c4370_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 214, c4370_b7, by decide, c4370_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 235, c4370_b6, by decide, c4370_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4370_b8, by decide, c4370_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4370_b9, by decide, c4370_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4371_b0, by decide, c4371_ok0⟩, ?_⟩
  simp

def s30 : List Nat := [5066549581119490, 562949970526210, 5066549580857362, 562949970264082]
theorem e30 : enumKeys 207 1174 = s30 := by decide +kernel
theorem r30 : ∀ M ∈ s30, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1174 M ne blob = true := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4371_b1, by decide, c4371_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 210, c4371_b2, by decide, c4371_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4371_b3, by decide, c4371_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4371_b4, by decide, c4371_ok4⟩, ?_⟩
  simp

def s31 : List Nat := [5910974511054850, 1407374900461570, 4785074604212482, 281474993619202]
theorem e31 : enumKeys 207 1354 = s31 := by decide +kernel
theorem r31 : ∀ M ∈ s31, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1354 M ne blob = true := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4371_b5, by decide, c4371_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4371_b6, by decide, c4371_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 258, c4371_b7, by decide, c4371_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4371_b8, by decide, c4371_ok8⟩, ?_⟩
  simp

def s32 : List Nat := [18577348463034370, 562950020661250, 562949953556482]
theorem e32 : enumKeys 207 4234 = s32 := by decide +kernel
theorem r32 : ∀ M ∈ s32, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4234 M ne blob = true := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4371_b9, by decide, c4371_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4372_b0, by decide, c4372_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4372_b1, by decide, c4372_ok1⟩, ?_⟩
  simp

def s33 : List Nat := [844424930525186, 844424930263058]
theorem e33 : enumKeys 207 218 = s33 := by decide +kernel
theorem r33 : ∀ M ∈ s33, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 218 M ne blob = true := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4372_b2, by decide, c4372_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4372_b3, by decide, c4372_ok3⟩, ?_⟩
  simp

def s34 : List Nat := [1688849860460546, 562949953618178]
theorem e34 : enumKeys 207 398 = s34 := by decide +kernel
theorem r34 : ∀ M ∈ s34, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 398 M ne blob = true := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4372_b4, by decide, c4372_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 252, c4372_b5, by decide, c4372_ok5⟩, ?_⟩
  simp

def s35 : List Nat := [13510798882111491, 9007199271518211, 4503599660924931, 50331651]
theorem e35 : enumKeys 207 3075 = s35 := by decide +kernel
theorem r35 : ∀ M ∈ s35, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 3075 M ne blob = true := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4372_b6, by decide, c4372_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4372_b7, by decide, c4372_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 228, c4372_b8, by decide, c4372_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4372_b9, by decide, c4372_ok9⟩, ?_⟩
  simp

def s36 : List Nat := [9288674231517187, 4785074620923907, 281475010330627]
theorem e36 : enumKeys 207 2119 = s36 := by decide +kernel
theorem r36 : ∀ M ∈ s36, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2119 M ne blob = true := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4373_b0, by decide, c4373_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 222, c4373_b1, by decide, c4373_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4373_b2, by decide, c4373_ok2⟩, ?_⟩
  simp

def s37 : List Nat := [5066549580922883, 562949970329603]
theorem e37 : enumKeys 207 1163 = s37 := by decide +kernel
theorem r37 : ∀ M ∈ s37, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1163 M ne blob = true := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4373_b3, by decide, c4373_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4373_b4, by decide, c4373_ok4⟩, ?_⟩
  simp

def s38 : List Nat := [844424930328579]
theorem e38 : enumKeys 207 207 = s38 := by decide +kernel
theorem r38 : ∀ M ∈ s38, ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 207 M ne blob = true := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨⟨0, 216, c4373_b5, by decide, c4373_ok5⟩, ?_⟩
  simp

/-- every enumerated key with left type `207` is the symbolic `U → U` key or has a record -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 207 mR,
    (207 = UTYPE ∧ mR = UTYPE) ∨ ∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 mR M ne blob = true := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K38
end Grid3.Three.Cert
