import Grid3.Three.Cert.Mirror
import Grid3.Three.Cert.Data.C0550
import Grid3.Three.Cert.Data.C0551
import Grid3.Three.Cert.Data.C0552
import Grid3.Three.Cert.Data.C0553

/-! Seam keys with left type `207` (type index 38): the enumeration equals the stored keys, and
every stored key, or its row reflection, has a kernel-checked record. Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`. -/

set_option maxHeartbeats 0
set_option maxRecDepth 100000

namespace Grid3.Three.Cert
namespace K38

theorem tL : rtype 207 = 207 := by decide

def s00 : List Nat := [54043195528445952, 36028797086072832, 18014398643699712, 201326592, 36028797018968064, 18014398576594944, 134221824, 18014398509490176, 67117056, 12288]
theorem e00 : enumKeys 207 12288 = s00 := by decide +kernel
theorem t00 : rtype 12288 = 12288 := by decide
theorem r00 : ∀ M ∈ s00, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 12288 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 12288) (rM M) ne blob = true) := by
  unfold s00
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 216, c0550_b10, by decide, by rw [tL, t00, show rM 54043195528445952 = 12288 by decide]; exact c0550_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0550_b11, by decide, by rw [tL, t00, show rM 36028797086072832 = 67117056 by decide]; exact c0550_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 228, c0550_b12, by decide, by rw [tL, t00, show rM 18014398643699712 = 134221824 by decide]; exact c0550_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0550_b13, by decide, c0550_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨1, 222, c0550_b14, by decide, by rw [tL, t00, show rM 36028797018968064 = 18014398509490176 by decide]; exact c0550_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 230, c0550_b15, by decide, c0550_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0550_b12, by decide, c0550_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 222, c0550_b14, by decide, c0550_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 228, c0550_b11, by decide, c0550_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨1, 216, c0550_b10, by decide, c0550_ok10⟩, ?_⟩
  simp

def s01 : List Nat := [23643898043957248, 19140298433363968, 5629499601584128, 1125899990990848, 23643898043695120, 19140298433101840, 5629499601322000, 1125899990728720, 22517998137114880, 18014398526521600, 4503599694741760, 84148480, 22517998136852752, 18014398526259472, 4503599694479632, 83886352, 5629499534479360, 1125899923886080, 5629499534217232, 1125899923623952, 4503599627636992, 17043712, 4503599627374864, 16781584]
theorem e01 : enumKeys 207 5392 = s01 := by decide +kernel
theorem t01 : rtype 5392 = 5392 := by decide
theorem r01 : ∀ M ∈ s01, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5392 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 5392) (rM M) ne blob = true) := by
  unfold s01
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0550_b16, by decide, by rw [tL, t01, show rM 23643898043957248 = 16781584 by decide]; exact c0550_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 246, c0550_b17, by decide, by rw [tL, t01, show rM 19140298433363968 = 17043712 by decide]; exact c0550_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 267, c0550_b18, by decide, by rw [tL, t01, show rM 5629499601584128 = 83886352 by decide]; exact c0550_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 246, c0550_b19, by decide, by rw [tL, t01, show rM 1125899990990848 = 84148480 by decide]; exact c0550_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0550_b23, by decide, by rw [tL, t01, show rM 23643898043695120 = 4503599627374864 by decide]; exact c0550_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 265, c0550_b24, by decide, by rw [tL, t01, show rM 19140298433101840 = 4503599627636992 by decide]; exact c0550_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 286, c0550_b25, by decide, by rw [tL, t01, show rM 5629499601322000 = 4503599694479632 by decide]; exact c0550_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 274, c0550_b22, by decide, c0550_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 265, c0550_b20, by decide, by rw [tL, t01, show rM 22517998137114880 = 1125899923623952 by decide]; exact c0550_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 250, c0550_b21, by decide, by rw [tL, t01, show rM 18014398526521600 = 1125899923886080 by decide]; exact c0550_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 274, c0550_b22, by decide, by rw [tL, t01, show rM 4503599694741760 = 1125899990728720 by decide]; exact c0550_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0550_b19, by decide, c0550_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 270, c0550_b26, by decide, by rw [tL, t01, show rM 22517998136852752 = 5629499534217232 by decide]; exact c0550_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 262, c0550_b27, by decide, by rw [tL, t01, show rM 18014398526259472 = 5629499534479360 by decide]; exact c0550_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 286, c0550_b25, by decide, c0550_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 267, c0550_b18, by decide, c0550_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0550_b27, by decide, c0550_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 250, c0550_b21, by decide, c0550_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 270, c0550_b26, by decide, c0550_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0550_b20, by decide, c0550_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 265, c0550_b24, by decide, c0550_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0550_b17, by decide, c0550_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0550_b23, by decide, c0550_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0550_b16, by decide, c0550_ok16⟩, ?_⟩
  simp

def s02 : List Nat := [36310271995936768, 18295873553563648, 281475111190528, 36310271995674640, 18295873553301520, 281475110928400, 18295873486458880, 281475044085760, 18295873486196752, 281475043823632, 281474976980992, 281474976718864]
theorem e02 : enumKeys 207 8272 = s02 := by decide +kernel
theorem t02 : rtype 8272 = 9217 := by decide
theorem r02 : ∀ M ∈ s02, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8272 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 8272) (rM M) ne blob = true) := by
  unfold s02
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0550_b39, by decide, c0550_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0550_b37, by decide, c0550_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0550_b33, by decide, c0550_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0550_b38, by decide, c0550_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 241, c0550_b36, by decide, c0550_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 244, c0550_b32, by decide, c0550_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0550_b35, by decide, c0550_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 220, c0550_b31, by decide, c0550_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 225, c0550_b34, by decide, c0550_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0550_b30, by decide, c0550_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0550_b29, by decide, c0550_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0550_b28, by decide, c0550_ok28⟩, ?_⟩
  simp

def s03 : List Nat := [5910974511448064, 1407374900854784, 5910974511185936, 1407374900592656, 5910974510923808, 1407374900330528, 4785074604605696, 281474994012416, 4785074604343568, 281474993750288, 4785074604081440, 281474993488160]
theorem e03 : enumKeys 207 1376 = s03 := by decide +kernel
theorem t03 : rtype 1376 = 2321 := by decide
theorem r03 : ∀ M ∈ s03, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1376 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1376) (rM M) ne blob = true) := by
  unfold s03
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0551_b11, by decide, c0551_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0551_b5, by decide, c0551_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0551_b10, by decide, c0551_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 260, c0551_b4, by decide, c0551_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0551_b9, by decide, c0551_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0551_b3, by decide, c0551_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 260, c0551_b8, by decide, c0551_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 240, c0551_b2, by decide, c0551_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 266, c0551_b7, by decide, c0551_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 254, c0551_b1, by decide, c0551_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0551_b6, by decide, c0551_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0551_b0, by decide, c0551_ok0⟩, ?_⟩
  simp

def s04 : List Nat := [18577348463427584, 562950021054464, 18577348463165456, 562950020792336, 18577348462903328, 562950020530208, 562949953949696, 562949953687568, 562949953425440]
theorem e04 : enumKeys 207 4256 = s04 := by decide +kernel
theorem t04 : rtype 4256 = 6146 := by decide
theorem r04 : ∀ M ∈ s04, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4256 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4256) (rM M) ne blob = true) := by
  unfold s04
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0551_b20, by decide, c0551_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0551_b17, by decide, c0551_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0551_b19, by decide, c0551_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 236, c0551_b16, by decide, c0551_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0551_b18, by decide, c0551_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0551_b15, by decide, c0551_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 212, c0551_b14, by decide, c0551_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0551_b13, by decide, c0551_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0551_b12, by decide, c0551_ok12⟩, ?_⟩
  simp

def s05 : List Nat := [844424930918400, 844424930656272, 844424930394144, 844424930132016]
theorem e05 : enumKeys 207 240 = s05 := by decide +kernel
theorem t05 : rtype 240 = 3075 := by decide
theorem r05 : ∀ M ∈ s05, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 240 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 240) (rM M) ne blob = true) := by
  unfold s05
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0551_b24, by decide, c0551_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0551_b23, by decide, c0551_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0551_b22, by decide, c0551_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0551_b21, by decide, c0551_ok21⟩, ?_⟩
  simp

def s06 : List Nat := [37154696925872128, 19140298483499008, 1125900041125888, 36028797019029760, 18014398576656640, 134283520, 19140298416394240, 1125899974021120, 18014398509551872, 67178752, 1125899906916352, 73984]
theorem e06 : enumKeys 207 8452 = s06 := by decide +kernel
theorem t06 : rtype 8452 = 8452 := by decide
theorem r06 : ∀ M ∈ s06, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8452 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 8452) (rM M) ne blob = true) := by
  unfold s06
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0551_b25, by decide, by rw [tL, t06, show rM 37154696925872128 = 73984 by decide]; exact c0551_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0551_b26, by decide, by rw [tL, t06, show rM 19140298483499008 = 67178752 by decide]; exact c0551_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0551_b27, by decide, by rw [tL, t06, show rM 1125900041125888 = 134283520 by decide]; exact c0551_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 262, c0551_b28, by decide, by rw [tL, t06, show rM 36028797019029760 = 1125899906916352 by decide]; exact c0551_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 268, c0551_b29, by decide, by rw [tL, t06, show rM 18014398576656640 = 1125899974021120 by decide]; exact c0551_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0551_b27, by decide, c0551_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 259, c0551_b30, by decide, by rw [tL, t06, show rM 19140298416394240 = 18014398509551872 by decide]; exact c0551_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 268, c0551_b29, by decide, c0551_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0551_b30, by decide, c0551_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0551_b26, by decide, c0551_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 262, c0551_b28, by decide, c0551_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0551_b25, by decide, c0551_ok25⟩, ?_⟩
  simp

def s07 : List Nat := [6755399441383424, 2251799830790144, 6755399441121296, 2251799830528016, 5629499534541056, 1125899923947776, 5629499534278928, 1125899923685648, 4503599627698688, 17105408, 4503599627436560, 16843280]
theorem e07 : enumKeys 207 1556 = s07 := by decide +kernel
theorem t07 : rtype 1556 = 1556 := by decide
theorem r07 : ∀ M ∈ s07, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1556 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1556) (rM M) ne blob = true) := by
  unfold s07
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0551_b31, by decide, by rw [tL, t07, show rM 6755399441383424 = 16843280 by decide]; exact c0551_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 282, c0551_b32, by decide, by rw [tL, t07, show rM 2251799830790144 = 17105408 by decide]; exact c0551_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 300, c0551_b36, by decide, by rw [tL, t07, show rM 6755399441121296 = 4503599627436560 by decide]; exact c0551_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 302, c0551_b35, by decide, c0551_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 302, c0551_b33, by decide, by rw [tL, t07, show rM 5629499534541056 = 1125899923685648 by decide]; exact c0551_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0551_b34, by decide, c0551_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 308, c0551_b37, by decide, c0551_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 302, c0551_b33, by decide, c0551_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 302, c0551_b35, by decide, by rw [tL, t07, show rM 4503599627698688 = 2251799830528016 by decide]; exact c0551_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 282, c0551_b32, by decide, c0551_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 300, c0551_b36, by decide, c0551_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0551_b31, by decide, c0551_ok31⟩, ?_⟩
  simp

def s08 : List Nat := [19421773393362944, 1407374950989824, 19421773393100816, 1407374950727696, 18295873486520576, 281475044147456, 18295873486258448, 281475043885328, 1407374883885056, 1407374883622928, 281474977042688, 281474976780560]
theorem e08 : enumKeys 207 4436 = s08 := by decide +kernel
theorem t08 : rtype 4436 = 5381 := by decide
theorem r08 : ∀ M ∈ s08, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4436 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4436) (rM M) ne blob = true) := by
  unfold s08
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0552_b9, by decide, c0552_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0552_b5, by decide, c0552_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0552_b8, by decide, c0552_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 278, c0552_b4, by decide, c0552_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 257, c0552_b7, by decide, c0552_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0552_b1, by decide, c0552_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 263, c0552_b6, by decide, c0552_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 272, c0552_b0, by decide, c0552_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 254, c0552_b3, by decide, c0552_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 263, c0552_b2, by decide, c0552_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 251, c0551_b39, by decide, c0551_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0551_b38, by decide, c0551_ok38⟩, ?_⟩
  simp

def s09 : List Nat := [1688849860853760, 1688849860591632, 1688849860329504, 562949954011392, 562949953749264, 562949953487136]
theorem e09 : enumKeys 207 420 = s09 := by decide +kernel
theorem t09 : rtype 420 = 2310 := by decide
theorem r09 : ∀ M ∈ s09, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 420 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 420) (rM M) ne blob = true) := by
  unfold s09
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0552_b15, by decide, c0552_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0552_b14, by decide, c0552_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0552_b13, by decide, c0552_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0552_b12, by decide, c0552_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0552_b11, by decide, c0552_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0552_b10, by decide, c0552_ok10⟩, ?_⟩
  simp

def s10 : List Nat := [20266198323298304, 2251799880925184, 19140298416455936, 1125899974082816, 18014398509613568, 67240448, 2251799813820416, 1125899906978048, 135680]
theorem e10 : enumKeys 207 4616 = s10 := by decide +kernel
theorem t10 : rtype 4616 = 4616 := by decide
theorem r10 : ∀ M ∈ s10, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4616 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4616) (rM M) ne blob = true) := by
  unfold s10
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0552_b16, by decide, by rw [tL, t10, show rM 20266198323298304 = 135680 by decide]; exact c0552_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 300, c0552_b17, by decide, by rw [tL, t10, show rM 2251799880925184 = 67240448 by decide]; exact c0552_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 299, c0552_b18, by decide, by rw [tL, t10, show rM 19140298416455936 = 1125899906978048 by decide]; exact c0552_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 306, c0552_b19, by decide, c0552_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 296, c0552_b20, by decide, by rw [tL, t10, show rM 18014398509613568 = 2251799813820416 by decide]; exact c0552_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 300, c0552_b17, by decide, c0552_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 296, c0552_b20, by decide, c0552_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 299, c0552_b18, by decide, c0552_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0552_b16, by decide, c0552_ok16⟩, ?_⟩
  simp

def s11 : List Nat := [2533274790789120, 2533274790526992, 1407374883946752, 1407374883684624, 281474977104384, 281474976842256]
theorem e11 : enumKeys 207 600 = s11 := by decide +kernel
theorem t11 : rtype 600 = 1545 := by decide
theorem r11 : ∀ M ∈ s11, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 600 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 600) (rM M) ne blob = true) := by
  unfold s11
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0552_b26, by decide, c0552_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 300, c0552_b25, by decide, c0552_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0552_b24, by decide, c0552_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 301, c0552_b23, by decide, c0552_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0552_b22, by decide, c0552_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0552_b21, by decide, c0552_ok21⟩, ?_⟩
  simp

def s12 : List Nat := [3377699720724480, 2251799813882112, 1125899907039744, 197376]
theorem e12 : enumKeys 207 780 = s12 := by decide +kernel
theorem t12 : rtype 780 = 780 := by decide
theorem r12 : ∀ M ∈ s12, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 780 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 780) (rM M) ne blob = true) := by
  unfold s12
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 324, c0552_b27, by decide, by rw [tL, t12, show rM 3377699720724480 = 197376 by decide]; exact c0552_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 336, c0552_b28, by decide, by rw [tL, t12, show rM 2251799813882112 = 1125899907039744 by decide]; exact c0552_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 336, c0552_b28, by decide, c0552_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 324, c0552_b27, by decide, c0552_ok27⟩, ?_⟩
  simp

def s13 : List Nat := [40532396646334465, 36028797035741185, 22517998203961345, 18014398593368065, 4503599761588225, 150994945, 22517998136856577, 18014398526263297, 4503599694483457, 83890177, 4503599627378689, 16785409]
theorem e13 : enumKeys 207 9217 = s13 := by decide +kernel
theorem t13 : rtype 9217 = 8272 := by decide
theorem r13 : ∀ M ∈ s13, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 9217 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 9217) (rM M) ne blob = true) := by
  unfold s13
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0550_b28, by decide, by rw [tL, t13, show rM 40532396646334465 = 281474976718864 by decide]; exact c0550_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 214, c0550_b29, by decide, by rw [tL, t13, show rM 36028797035741185 = 281474976980992 by decide]; exact c0550_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 235, c0550_b30, by decide, by rw [tL, t13, show rM 22517998203961345 = 281475043823632 by decide]; exact c0550_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 220, c0550_b31, by decide, by rw [tL, t13, show rM 18014398593368065 = 281475044085760 by decide]; exact c0550_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 244, c0550_b32, by decide, by rw [tL, t13, show rM 4503599761588225 = 281475110928400 by decide]; exact c0550_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0550_b33, by decide, by rw [tL, t13, show rM 150994945 = 281475111190528 by decide]; exact c0550_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 225, c0550_b34, by decide, by rw [tL, t13, show rM 22517998136856577 = 18295873486196752 by decide]; exact c0550_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 217, c0550_b35, by decide, by rw [tL, t13, show rM 18014398526263297 = 18295873486458880 by decide]; exact c0550_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 241, c0550_b36, by decide, by rw [tL, t13, show rM 4503599694483457 = 18295873553301520 by decide]; exact c0550_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0550_b37, by decide, by rw [tL, t13, show rM 83890177 = 18295873553563648 by decide]; exact c0550_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0550_b38, by decide, by rw [tL, t13, show rM 4503599627378689 = 36310271995674640 by decide]; exact c0550_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0550_b39, by decide, by rw [tL, t13, show rM 16785409 = 36310271995936768 by decide]; exact c0550_ok39⟩, ?_⟩
  simp

def s14 : List Nat := [10133099161845761, 5629499551252481, 1125899940659201, 10133099161583633, 5629499550990353, 1125899940397073, 9007199255003393, 4503599644410113, 33816833, 9007199254741265, 4503599644147985, 33554705]
theorem e14 : enumKeys 207 2321 = s14 := by decide +kernel
theorem t14 : rtype 2321 = 1376 := by decide
theorem r14 : ∀ M ∈ s14, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2321 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 2321) (rM M) ne blob = true) := by
  unfold s14
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0551_b0, by decide, by rw [tL, t14, show rM 10133099161845761 = 281474993488160 by decide]; exact c0551_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 254, c0551_b1, by decide, by rw [tL, t14, show rM 5629499551252481 = 281474993750288 by decide]; exact c0551_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 240, c0551_b2, by decide, by rw [tL, t14, show rM 1125899940659201 = 281474994012416 by decide]; exact c0551_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0551_b6, by decide, by rw [tL, t14, show rM 10133099161583633 = 4785074604081440 by decide]; exact c0551_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0551_b7, by decide, by rw [tL, t14, show rM 5629499550990353 = 4785074604343568 by decide]; exact c0551_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 260, c0551_b8, by decide, by rw [tL, t14, show rM 1125899940397073 = 4785074604605696 by decide]; exact c0551_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 266, c0551_b3, by decide, by rw [tL, t14, show rM 9007199255003393 = 1407374900330528 by decide]; exact c0551_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 260, c0551_b4, by decide, by rw [tL, t14, show rM 4503599644410113 = 1407374900592656 by decide]; exact c0551_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 240, c0551_b5, by decide, by rw [tL, t14, show rM 33816833 = 1407374900854784 by decide]; exact c0551_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0551_b9, by decide, by rw [tL, t14, show rM 9007199254741265 = 5910974510923808 by decide]; exact c0551_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0551_b10, by decide, by rw [tL, t14, show rM 4503599644147985 = 5910974511185936 by decide]; exact c0551_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0551_b11, by decide, by rw [tL, t14, show rM 33554705 = 5910974511448064 by decide]; exact c0551_ok11⟩, ?_⟩
  simp

def s15 : List Nat := [22799473113825281, 18295873503232001, 4785074671452161, 281475060858881, 22799473113563153, 18295873502969873, 4785074671190033, 281475060596753, 4785074604347393, 281474993754113, 4785074604085265, 281474993491985]
theorem e15 : enumKeys 207 5201 = s15 := by decide +kernel
theorem t15 : rtype 5201 = 5201 := by decide
theorem r15 : ∀ M ∈ s15, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5201 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 5201) (rM M) ne blob = true) := by
  unfold s15
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0552_b29, by decide, by rw [tL, t15, show rM 22799473113825281 = 281474993491985 by decide]; exact c0552_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 209, c0552_b30, by decide, by rw [tL, t15, show rM 18295873503232001 = 281474993754113 by decide]; exact c0552_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 230, c0552_b31, by decide, by rw [tL, t15, show rM 4785074671452161 = 281475060596753 by decide]; exact c0552_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0552_b32, by decide, c0552_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0552_b33, by decide, by rw [tL, t15, show rM 22799473113563153 = 4785074604085265 by decide]; exact c0552_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 221, c0552_b34, by decide, by rw [tL, t15, show rM 18295873502969873 = 4785074604347393 by decide]; exact c0552_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 242, c0552_b35, by decide, c0552_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 230, c0552_b31, by decide, c0552_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 221, c0552_b34, by decide, c0552_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 209, c0552_b30, by decide, c0552_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0552_b33, by decide, c0552_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0552_b29, by decide, c0552_ok29⟩, ?_⟩
  simp

def s16 : List Nat := [5066549581316097, 562949970722817, 5066549581053969, 562949970460689, 5066549580791841, 562949970198561]
theorem e16 : enumKeys 207 1185 = s16 := by decide +kernel
theorem t16 : rtype 1185 = 2130 := by decide
theorem r16 : ∀ M ∈ s16, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1185 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1185) (rM M) ne blob = true) := by
  unfold s16
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b1, by decide, c0553_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 204, c0552_b38, by decide, c0552_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0553_b0, by decide, c0553_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 217, c0552_b37, by decide, c0552_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0552_b39, by decide, c0552_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0552_b36, by decide, c0552_ok36⟩, ?_⟩
  simp

def s17 : List Nat := [23643898043760641, 19140298433167361, 5629499601387521, 1125899990794241, 22517998136918273, 18014398526324993, 4503599694545153, 83951873, 5629499534282753, 1125899923689473, 4503599627440385, 16847105]
theorem e17 : enumKeys 207 5381 = s17 := by decide +kernel
theorem t17 : rtype 5381 = 4436 := by decide
theorem r17 : ∀ M ∈ s17, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5381 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 5381) (rM M) ne blob = true) := by
  unfold s17
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0551_b38, by decide, by rw [tL, t17, show rM 23643898043760641 = 281474976780560 by decide]; exact c0551_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 251, c0551_b39, by decide, by rw [tL, t17, show rM 19140298433167361 = 281474977042688 by decide]; exact c0551_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 272, c0552_b0, by decide, by rw [tL, t17, show rM 5629499601387521 = 281475043885328 by decide]; exact c0552_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0552_b1, by decide, by rw [tL, t17, show rM 1125899990794241 = 281475044147456 by decide]; exact c0552_ok1⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 263, c0552_b2, by decide, by rw [tL, t17, show rM 22517998136918273 = 1407374883622928 by decide]; exact c0552_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 254, c0552_b3, by decide, by rw [tL, t17, show rM 18014398526324993 = 1407374883885056 by decide]; exact c0552_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 278, c0552_b4, by decide, by rw [tL, t17, show rM 4503599694545153 = 1407374950727696 by decide]; exact c0552_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0552_b5, by decide, by rw [tL, t17, show rM 83951873 = 1407374950989824 by decide]; exact c0552_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 263, c0552_b6, by decide, by rw [tL, t17, show rM 5629499534282753 = 18295873486258448 by decide]; exact c0552_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 257, c0552_b7, by decide, by rw [tL, t17, show rM 1125899923689473 = 18295873486520576 by decide]; exact c0552_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0552_b8, by decide, by rw [tL, t17, show rM 4503599627440385 = 19421773393100816 by decide]; exact c0552_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0552_b9, by decide, by rw [tL, t17, show rM 16847105 = 19421773393362944 by decide]; exact c0552_ok9⟩, ?_⟩
  simp

def s18 : List Nat := [36310271995740161, 18295873553367041, 281475110993921, 18295873486262273, 281475043889153, 281474976784385]
theorem e18 : enumKeys 207 8261 = s18 := by decide +kernel
theorem t18 : rtype 8261 = 8261 := by decide
theorem r18 : ∀ M ∈ s18, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 8261 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 8261) (rM M) ne blob = true) := by
  unfold s18
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b2, by decide, by rw [tL, t18, show rM 36310271995740161 = 281474976784385 by decide]; exact c0553_ok2⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 227, c0553_b3, by decide, by rw [tL, t18, show rM 18295873553367041 = 281475043889153 by decide]; exact c0553_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0553_b4, by decide, c0553_ok4⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 218, c0553_b5, by decide, c0553_ok5⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 227, c0553_b3, by decide, c0553_ok3⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b2, by decide, c0553_ok2⟩, ?_⟩
  simp

def s19 : List Nat := [5910974511251457, 1407374900658177, 5910974510989329, 1407374900396049, 4785074604409089, 281474993815809, 4785074604146961, 281474993553681]
theorem e19 : enumKeys 207 1365 = s19 := by decide +kernel
theorem t19 : rtype 1365 = 1365 := by decide
theorem r19 : ∀ M ∈ s19, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1365 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1365) (rM M) ne blob = true) := by
  unfold s19
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b6, by decide, by rw [tL, t19, show rM 5910974511251457 = 281474993553681 by decide]; exact c0553_ok6⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 246, c0553_b7, by decide, by rw [tL, t19, show rM 1407374900658177 = 281474993815809 by decide]; exact c0553_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0553_b9, by decide, by rw [tL, t19, show rM 5910974510989329 = 4785074604146961 by decide]; exact c0553_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 259, c0553_b8, by decide, c0553_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 259, c0553_b8, by decide, by rw [tL, t19, show rM 4785074604409089 = 1407374900396049 by decide]; exact c0553_ok8⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 246, c0553_b7, by decide, c0553_ok7⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0553_b9, by decide, c0553_ok9⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b6, by decide, c0553_ok6⟩, ?_⟩
  simp

def s20 : List Nat := [18577348463230977, 562950020857857, 18577348462968849, 562950020595729, 562949953753089, 562949953490961]
theorem e20 : enumKeys 207 4245 = s20 := by decide +kernel
theorem t20 : rtype 4245 = 5190 := by decide
theorem r20 : ∀ M ∈ s20, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4245 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4245) (rM M) ne blob = true) := by
  unfold s20
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b15, by decide, c0553_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0553_b13, by decide, c0553_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0553_b14, by decide, c0553_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 235, c0553_b12, by decide, c0553_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 214, c0553_b11, by decide, c0553_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b10, by decide, c0553_ok10⟩, ?_⟩
  simp

def s21 : List Nat := [844424930721793, 844424930459665, 844424930197537]
theorem e21 : enumKeys 207 229 = s21 := by decide +kernel
theorem t21 : rtype 229 = 2119 := by decide
theorem r21 : ∀ M ∈ s21, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 229 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 229) (rM M) ne blob = true) := by
  unfold s21
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b18, by decide, c0553_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 222, c0553_b17, by decide, c0553_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b16, by decide, c0553_ok16⟩, ?_⟩
  simp

def s22 : List Nat := [6755399441186817, 2251799830593537, 5629499534344449, 1125899923751169, 4503599627502081, 16908801]
theorem e22 : enumKeys 207 1545 = s22 := by decide +kernel
theorem t22 : rtype 1545 = 600 := by decide
theorem r22 : ∀ M ∈ s22, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1545 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1545) (rM M) ne blob = true) := by
  unfold s22
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0552_b21, by decide, by rw [tL, t22, show rM 6755399441186817 = 281474976842256 by decide]; exact c0552_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0552_b22, by decide, by rw [tL, t22, show rM 2251799830593537 = 281474977104384 by decide]; exact c0552_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 301, c0552_b23, by decide, by rw [tL, t22, show rM 5629499534344449 = 1407374883684624 by decide]; exact c0552_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 294, c0552_b24, by decide, by rw [tL, t22, show rM 1125899923751169 = 1407374883946752 by decide]; exact c0552_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 300, c0552_b25, by decide, by rw [tL, t22, show rM 4503599627502081 = 2533274790526992 by decide]; exact c0552_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0552_b26, by decide, by rw [tL, t22, show rM 16908801 = 2533274790789120 by decide]; exact c0552_ok26⟩, ?_⟩
  simp

def s23 : List Nat := [19421773393166337, 1407374950793217, 18295873486323969, 281475043950849, 1407374883688449, 281474976846081]
theorem e23 : enumKeys 207 4425 = s23 := by decide +kernel
theorem t23 : rtype 4425 = 4425 := by decide
theorem r23 : ∀ M ∈ s23, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4425 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4425) (rM M) ne blob = true) := by
  unfold s23
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b19, by decide, by rw [tL, t23, show rM 19421773393166337 = 281474976846081 by decide]; exact c0553_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0553_b20, by decide, by rw [tL, t23, show rM 1407374950793217 = 281475043950849 by decide]; exact c0553_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 256, c0553_b21, by decide, by rw [tL, t23, show rM 18295873486323969 = 1407374883688449 by decide]; exact c0553_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 264, c0553_b20, by decide, c0553_ok20⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 256, c0553_b21, by decide, c0553_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b19, by decide, c0553_ok19⟩, ?_⟩
  simp

def s24 : List Nat := [1688849860657153, 1688849860395025, 562949953814785, 562949953552657]
theorem e24 : enumKeys 207 409 = s24 := by decide +kernel
theorem t24 : rtype 409 = 1354 := by decide
theorem r24 : ∀ M ∈ s24, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 409 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 409) (rM M) ne blob = true) := by
  unfold s24
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b25, by decide, c0553_ok25⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 258, c0553_b24, by decide, c0553_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b23, by decide, c0553_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b22, by decide, c0553_ok22⟩, ?_⟩
  simp

def s25 : List Nat := [2533274790592513, 1407374883750145, 281474976907777]
theorem e25 : enumKeys 207 589 = s25 := by decide +kernel
theorem t25 : rtype 589 = 589 := by decide
theorem r25 : ∀ M ∈ s25, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 589 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 589) (rM M) ne blob = true) := by
  unfold s25
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 288, c0553_b26, by decide, by rw [tL, t25, show rM 2533274790592513 = 281474976907777 by decide]; exact c0553_ok26⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 294, c0553_b27, by decide, c0553_ok27⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 288, c0553_b26, by decide, c0553_ok26⟩, ?_⟩
  simp

def s26 : List Nat := [27021597764222978, 22517998153629698, 18014398543036418, 9007199321849858, 4503599711256578, 100663298, 9007199254745090, 4503599644151810, 33558530]
theorem e26 : enumKeys 207 6146 = s26 := by decide +kernel
theorem t26 : rtype 6146 = 4256 := by decide
theorem r26 : ∀ M ∈ s26, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 6146 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 6146) (rM M) ne blob = true) := by
  unfold s26
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0551_b12, by decide, by rw [tL, t26, show rM 27021597764222978 = 562949953425440 by decide]; exact c0551_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 221, c0551_b13, by decide, by rw [tL, t26, show rM 22517998153629698 = 562949953687568 by decide]; exact c0551_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 212, c0551_b14, by decide, by rw [tL, t26, show rM 18014398543036418 = 562949953949696 by decide]; exact c0551_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 242, c0551_b15, by decide, by rw [tL, t26, show rM 9007199321849858 = 562950020530208 by decide]; exact c0551_ok15⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 236, c0551_b16, by decide, by rw [tL, t26, show rM 4503599711256578 = 562950020792336 by decide]; exact c0551_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0551_b17, by decide, by rw [tL, t26, show rM 100663298 = 562950021054464 by decide]; exact c0551_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0551_b18, by decide, by rw [tL, t26, show rM 9007199254745090 = 18577348462903328 by decide]; exact c0551_ok18⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0551_b19, by decide, by rw [tL, t26, show rM 4503599644151810 = 18577348463165456 by decide]; exact c0551_ok19⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0551_b20, by decide, by rw [tL, t26, show rM 33558530 = 18577348463427584 by decide]; exact c0551_ok20⟩, ?_⟩
  simp

def s27 : List Nat := [9288674231713794, 4785074621120514, 281475010527234, 9288674231451666, 4785074620858386, 281475010265106]
theorem e27 : enumKeys 207 2130 = s27 := by decide +kernel
theorem t27 : rtype 2130 = 1185 := by decide
theorem r27 : ∀ M ∈ s27, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2130 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 2130) (rM M) ne blob = true) := by
  unfold s27
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0552_b36, by decide, by rw [tL, t27, show rM 9288674231713794 = 562949970198561 by decide]; exact c0552_ok36⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 217, c0552_b37, by decide, by rw [tL, t27, show rM 4785074621120514 = 562949970460689 by decide]; exact c0552_ok37⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 204, c0552_b38, by decide, by rw [tL, t27, show rM 281475010527234 = 562949970722817 by decide]; exact c0552_ok38⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0552_b39, by decide, by rw [tL, t27, show rM 9288674231451666 = 5066549580791841 by decide]; exact c0552_ok39⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0553_b0, by decide, by rw [tL, t27, show rM 4785074620858386 = 5066549581053969 by decide]; exact c0553_ok0⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b1, by decide, by rw [tL, t27, show rM 281475010265106 = 5066549581316097 by decide]; exact c0553_ok1⟩, ?_⟩
  simp

def s28 : List Nat := [10133099161649154, 5629499551055874, 1125899940462594, 9007199254806786, 4503599644213506, 33620226]
theorem e28 : enumKeys 207 2310 = s28 := by decide +kernel
theorem t28 : rtype 2310 = 420 := by decide
theorem r28 : ∀ M ∈ s28, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2310 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 2310) (rM M) ne blob = true) := by
  unfold s28
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0552_b10, by decide, by rw [tL, t28, show rM 10133099161649154 = 562949953487136 by decide]; exact c0552_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 259, c0552_b11, by decide, by rw [tL, t28, show rM 5629499551055874 = 562949953749264 by decide]; exact c0552_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0552_b12, by decide, by rw [tL, t28, show rM 1125899940462594 = 562949954011392 by decide]; exact c0552_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0552_b13, by decide, by rw [tL, t28, show rM 9007199254806786 = 1688849860329504 by decide]; exact c0552_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 264, c0552_b14, by decide, by rw [tL, t28, show rM 4503599644213506 = 1688849860591632 by decide]; exact c0552_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0552_b15, by decide, by rw [tL, t28, show rM 33620226 = 1688849860853760 by decide]; exact c0552_ok15⟩, ?_⟩
  simp

def s29 : List Nat := [22799473113628674, 18295873503035394, 4785074671255554, 281475060662274, 4785074604150786, 281474993557506]
theorem e29 : enumKeys 207 5190 = s29 := by decide +kernel
theorem t29 : rtype 5190 = 4245 := by decide
theorem r29 : ∀ M ∈ s29, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 5190 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 5190) (rM M) ne blob = true) := by
  unfold s29
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b10, by decide, by rw [tL, t29, show rM 22799473113628674 = 562949953490961 by decide]; exact c0553_ok10⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 214, c0553_b11, by decide, by rw [tL, t29, show rM 18295873503035394 = 562949953753089 by decide]; exact c0553_ok11⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 235, c0553_b12, by decide, by rw [tL, t29, show rM 4785074671255554 = 562950020595729 by decide]; exact c0553_ok12⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0553_b13, by decide, by rw [tL, t29, show rM 281475060662274 = 562950020857857 by decide]; exact c0553_ok13⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0553_b14, by decide, by rw [tL, t29, show rM 4785074604150786 = 18577348462968849 by decide]; exact c0553_ok14⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b15, by decide, by rw [tL, t29, show rM 281474993557506 = 18577348463230977 by decide]; exact c0553_ok15⟩, ?_⟩
  simp

def s30 : List Nat := [5066549581119490, 562949970526210, 5066549580857362, 562949970264082]
theorem e30 : enumKeys 207 1174 = s30 := by decide +kernel
theorem t30 : rtype 1174 = 1174 := by decide
theorem r30 : ∀ M ∈ s30, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1174 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1174) (rM M) ne blob = true) := by
  unfold s30
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b28, by decide, by rw [tL, t30, show rM 5066549581119490 = 562949970264082 by decide]; exact c0553_ok28⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 210, c0553_b29, by decide, c0553_ok29⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b30, by decide, c0553_ok30⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b28, by decide, c0553_ok28⟩, ?_⟩
  simp

def s31 : List Nat := [5910974511054850, 1407374900461570, 4785074604212482, 281474993619202]
theorem e31 : enumKeys 207 1354 = s31 := by decide +kernel
theorem t31 : rtype 1354 = 409 := by decide
theorem r31 : ∀ M ∈ s31, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1354 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1354) (rM M) ne blob = true) := by
  unfold s31
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b22, by decide, by rw [tL, t31, show rM 5910974511054850 = 562949953552657 by decide]; exact c0553_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b23, by decide, by rw [tL, t31, show rM 1407374900461570 = 562949953814785 by decide]; exact c0553_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 258, c0553_b24, by decide, by rw [tL, t31, show rM 4785074604212482 = 1688849860395025 by decide]; exact c0553_ok24⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b25, by decide, by rw [tL, t31, show rM 281474993619202 = 1688849860657153 by decide]; exact c0553_ok25⟩, ?_⟩
  simp

def s32 : List Nat := [18577348463034370, 562950020661250, 562949953556482]
theorem e32 : enumKeys 207 4234 = s32 := by decide +kernel
theorem t32 : rtype 4234 = 4234 := by decide
theorem r32 : ∀ M ∈ s32, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 4234 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 4234) (rM M) ne blob = true) := by
  unfold s32
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b31, by decide, by rw [tL, t32, show rM 18577348463034370 = 562949953556482 by decide]; exact c0553_ok31⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 228, c0553_b32, by decide, c0553_ok32⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b31, by decide, c0553_ok31⟩, ?_⟩
  simp

def s33 : List Nat := [844424930525186, 844424930263058]
theorem e33 : enumKeys 207 218 = s33 := by decide +kernel
theorem t33 : rtype 218 = 1163 := by decide
theorem r33 : ∀ M ∈ s33, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 218 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 218) (rM M) ne blob = true) := by
  unfold s33
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b34, by decide, c0553_ok34⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b33, by decide, c0553_ok33⟩, ?_⟩
  simp

def s34 : List Nat := [1688849860460546, 562949953618178]
theorem e34 : enumKeys 207 398 = s34 := by decide +kernel
theorem t34 : rtype 398 = 398 := by decide
theorem r34 : ∀ M ∈ s34, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 398 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 398) (rM M) ne blob = true) := by
  unfold s34
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 252, c0553_b35, by decide, by rw [tL, t34, show rM 1688849860460546 = 562949953618178 by decide]; exact c0553_ok35⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 252, c0553_b35, by decide, c0553_ok35⟩, ?_⟩
  simp

def s35 : List Nat := [13510798882111491, 9007199271518211, 4503599660924931, 50331651]
theorem e35 : enumKeys 207 3075 = s35 := by decide +kernel
theorem t35 : rtype 3075 = 240 := by decide
theorem r35 : ∀ M ∈ s35, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 3075 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 3075) (rM M) ne blob = true) := by
  unfold s35
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0551_b21, by decide, by rw [tL, t35, show rM 13510798882111491 = 844424930132016 by decide]; exact c0551_ok21⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0551_b22, by decide, by rw [tL, t35, show rM 9007199271518211 = 844424930394144 by decide]; exact c0551_ok22⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 228, c0551_b23, by decide, by rw [tL, t35, show rM 4503599660924931 = 844424930656272 by decide]; exact c0551_ok23⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0551_b24, by decide, by rw [tL, t35, show rM 50331651 = 844424930918400 by decide]; exact c0551_ok24⟩, ?_⟩
  simp

def s36 : List Nat := [9288674231517187, 4785074620923907, 281475010330627]
theorem e36 : enumKeys 207 2119 = s36 := by decide +kernel
theorem t36 : rtype 2119 = 229 := by decide
theorem r36 : ∀ M ∈ s36, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 2119 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 2119) (rM M) ne blob = true) := by
  unfold s36
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b16, by decide, by rw [tL, t36, show rM 9288674231517187 = 844424930197537 by decide]; exact c0553_ok16⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 222, c0553_b17, by decide, by rw [tL, t36, show rM 4785074620923907 = 844424930459665 by decide]; exact c0553_ok17⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b18, by decide, by rw [tL, t36, show rM 281475010330627 = 844424930721793 by decide]; exact c0553_ok18⟩, ?_⟩
  simp

def s37 : List Nat := [5066549580922883, 562949970329603]
theorem e37 : enumKeys 207 1163 = s37 := by decide +kernel
theorem t37 : rtype 1163 = 218 := by decide
theorem r37 : ∀ M ∈ s37, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 1163 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 1163) (rM M) ne blob = true) := by
  unfold s37
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b33, by decide, by rw [tL, t37, show rM 5066549580922883 = 844424930263058 by decide]; exact c0553_ok33⟩, ?_⟩
  refine List.forall_mem_cons.2 ⟨Or.inr ⟨0, 216, c0553_b34, by decide, by rw [tL, t37, show rM 562949970329603 = 844424930525186 by decide]; exact c0553_ok34⟩, ?_⟩
  simp

def s38 : List Nat := [844424930328579]
theorem e38 : enumKeys 207 207 = s38 := by decide +kernel
theorem t38 : rtype 207 = 207 := by decide
theorem r38 : ∀ M ∈ s38, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 207 M ne blob = true)
    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype 207) (rM M) ne blob = true) := by
  unfold s38
  refine List.forall_mem_cons.2 ⟨Or.inl ⟨0, 216, c0553_b36, by decide, c0553_ok36⟩, ?_⟩
  simp

/-- every enumerated key with left type `207` is the symbolic `U → U` key, has a record, or
its row reflection has one -/
theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys 207 mR,
    (207 = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt 207 mR M ne blob = true)
      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype 207) (rtype mR) (rM M) ne blob = true) := by
  rw [validTypes_eq]
  intro mR hmR
  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR
  rcases hmR with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · intro M hM; rw [e38] at hM; exact Or.inr (r38 M hM)
  · intro M hM; rw [e33] at hM; exact Or.inr (r33 M hM)
  · intro M hM; rw [e21] at hM; exact Or.inr (r21 M hM)
  · intro M hM; rw [e05] at hM; exact Or.inr (r05 M hM)
  · intro M hM; rw [e34] at hM; exact Or.inr (r34 M hM)
  · intro M hM; rw [e24] at hM; exact Or.inr (r24 M hM)
  · intro M hM; rw [e09] at hM; exact Or.inr (r09 M hM)
  · intro M hM; rw [e25] at hM; exact Or.inr (r25 M hM)
  · intro M hM; rw [e11] at hM; exact Or.inr (r11 M hM)
  · intro M hM; rw [e12] at hM; exact Or.inr (r12 M hM)
  · intro M hM; rw [e37] at hM; exact Or.inr (r37 M hM)
  · intro M hM; rw [e30] at hM; exact Or.inr (r30 M hM)
  · intro M hM; rw [e16] at hM; exact Or.inr (r16 M hM)
  · intro M hM; rw [e31] at hM; exact Or.inr (r31 M hM)
  · intro M hM; rw [e19] at hM; exact Or.inr (r19 M hM)
  · intro M hM; rw [e03] at hM; exact Or.inr (r03 M hM)
  · intro M hM; rw [e22] at hM; exact Or.inr (r22 M hM)
  · intro M hM; rw [e07] at hM; exact Or.inr (r07 M hM)
  · intro M hM; rw [e36] at hM; exact Or.inr (r36 M hM)
  · intro M hM; rw [e27] at hM; exact Or.inr (r27 M hM)
  · intro M hM; rw [e28] at hM; exact Or.inr (r28 M hM)
  · intro M hM; rw [e14] at hM; exact Or.inr (r14 M hM)
  · intro M hM; rw [e35] at hM; exact Or.inr (r35 M hM)
  · intro M hM; rw [e32] at hM; exact Or.inr (r32 M hM)
  · intro M hM; rw [e20] at hM; exact Or.inr (r20 M hM)
  · intro M hM; rw [e04] at hM; exact Or.inr (r04 M hM)
  · intro M hM; rw [e23] at hM; exact Or.inr (r23 M hM)
  · intro M hM; rw [e08] at hM; exact Or.inr (r08 M hM)
  · intro M hM; rw [e10] at hM; exact Or.inr (r10 M hM)
  · intro M hM; rw [e29] at hM; exact Or.inr (r29 M hM)
  · intro M hM; rw [e15] at hM; exact Or.inr (r15 M hM)
  · intro M hM; rw [e17] at hM; exact Or.inr (r17 M hM)
  · intro M hM; rw [e01] at hM; exact Or.inr (r01 M hM)
  · intro M hM; rw [e26] at hM; exact Or.inr (r26 M hM)
  · intro M hM; rw [e18] at hM; exact Or.inr (r18 M hM)
  · intro M hM; rw [e02] at hM; exact Or.inr (r02 M hM)
  · intro M hM; rw [e06] at hM; exact Or.inr (r06 M hM)
  · intro M hM; rw [e13] at hM; exact Or.inr (r13 M hM)
  · intro M hM; rw [e00] at hM; exact Or.inr (r00 M hM)

end K38
end Grid3.Three.Cert
