/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Reduction

/-!
# `K₂,₂₅` at four: the certificate for hub lists sharing 0 colours

Generated by `TwoDegenerate/K2n/gen_k2n.py`; checked here by the kernel. The keys are the
four-subsets of `A ∪ B` in branching order, the rows their sixteen pair values, and the
certificate a `Cert` tree (1 nodes, 1 closed by AM–GM).
-/

namespace SimpleGraph.TwoDegenerate.K2n.K2_25

/-- The four-subsets of `A ∪ B`, as membership bits, in branching order. -/
def keys0 : List (List Bool) :=
  [[true, true, true, true, false, false, false, false],
    [true, true, true, false, true, false, false, false],
    [true, true, true, false, false, true, false, false],
    [true, true, true, false, false, false, true, false],
    [true, true, true, false, false, false, false, true],
    [true, true, false, true, true, false, false, false],
    [true, true, false, true, false, true, false, false],
    [true, true, false, true, false, false, true, false],
    [true, true, false, true, false, false, false, true],
    [true, true, false, false, true, true, false, false],
    [true, true, false, false, true, false, true, false],
    [true, true, false, false, true, false, false, true],
    [true, true, false, false, false, true, true, false],
    [true, true, false, false, false, true, false, true],
    [true, true, false, false, false, false, true, true],
    [true, false, true, true, true, false, false, false],
    [true, false, true, true, false, true, false, false],
    [true, false, true, true, false, false, true, false],
    [true, false, true, true, false, false, false, true],
    [true, false, true, false, true, true, false, false],
    [true, false, true, false, true, false, true, false],
    [true, false, true, false, true, false, false, true],
    [true, false, true, false, false, true, true, false],
    [true, false, true, false, false, true, false, true],
    [true, false, true, false, false, false, true, true],
    [true, false, false, true, true, true, false, false],
    [true, false, false, true, true, false, true, false],
    [true, false, false, true, true, false, false, true],
    [true, false, false, true, false, true, true, false],
    [true, false, false, true, false, true, false, true],
    [true, false, false, true, false, false, true, true],
    [true, false, false, false, true, true, true, false],
    [true, false, false, false, true, true, false, true],
    [true, false, false, false, true, false, true, true],
    [true, false, false, false, false, true, true, true],
    [false, true, true, true, true, false, false, false],
    [false, true, true, true, false, true, false, false],
    [false, true, true, true, false, false, true, false],
    [false, true, true, true, false, false, false, true],
    [false, true, true, false, true, true, false, false],
    [false, true, true, false, true, false, true, false],
    [false, true, true, false, true, false, false, true],
    [false, true, true, false, false, true, true, false],
    [false, true, true, false, false, true, false, true],
    [false, true, true, false, false, false, true, true],
    [false, true, false, true, true, true, false, false],
    [false, true, false, true, true, false, true, false],
    [false, true, false, true, true, false, false, true],
    [false, true, false, true, false, true, true, false],
    [false, true, false, true, false, true, false, true],
    [false, true, false, true, false, false, true, true],
    [false, true, false, false, true, true, true, false],
    [false, true, false, false, true, true, false, true],
    [false, true, false, false, true, false, true, true],
    [false, true, false, false, false, true, true, true],
    [false, false, true, true, true, true, false, false],
    [false, false, true, true, true, false, true, false],
    [false, false, true, true, true, false, false, true],
    [false, false, true, true, false, true, true, false],
    [false, false, true, true, false, true, false, true],
    [false, false, true, true, false, false, true, true],
    [false, false, true, false, true, true, true, false],
    [false, false, true, false, true, true, false, true],
    [false, false, true, false, true, false, true, true],
    [false, false, true, false, false, true, true, true],
    [false, false, false, true, true, true, true, false],
    [false, false, false, true, true, true, false, true],
    [false, false, false, true, true, false, true, true],
    [false, false, false, true, false, true, true, true],
    [false, false, false, false, true, true, true, true]]

/-- Their rows, `rowOf 0`. -/
def rows0 : List (List ℕ) :=
  [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    [2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 4, 4, 4],
    [3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 4, 3, 4, 4],
    [3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 4, 4, 3, 4],
    [3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 4, 4, 4, 3],
    [2, 3, 3, 3, 2, 3, 3, 3, 3, 4, 4, 4, 2, 3, 3, 3],
    [3, 2, 3, 3, 3, 2, 3, 3, 4, 3, 4, 4, 3, 2, 3, 3],
    [3, 3, 2, 3, 3, 3, 2, 3, 4, 4, 3, 4, 3, 3, 2, 3],
    [3, 3, 3, 2, 3, 3, 3, 2, 4, 4, 4, 3, 3, 3, 3, 2],
    [2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4, 3, 3, 4, 4],
    [2, 3, 2, 3, 2, 3, 2, 3, 3, 4, 3, 4, 3, 4, 3, 4],
    [2, 3, 3, 2, 2, 3, 3, 2, 3, 4, 4, 3, 3, 4, 4, 3],
    [3, 2, 2, 3, 3, 2, 2, 3, 4, 3, 3, 4, 4, 3, 3, 4],
    [3, 2, 3, 2, 3, 2, 3, 2, 4, 3, 4, 3, 4, 3, 4, 3],
    [3, 3, 2, 2, 3, 3, 2, 2, 4, 4, 3, 3, 4, 4, 3, 3],
    [2, 3, 3, 3, 3, 4, 4, 4, 2, 3, 3, 3, 2, 3, 3, 3],
    [3, 2, 3, 3, 4, 3, 4, 4, 3, 2, 3, 3, 3, 2, 3, 3],
    [3, 3, 2, 3, 4, 4, 3, 4, 3, 3, 2, 3, 3, 3, 2, 3],
    [3, 3, 3, 2, 4, 4, 4, 3, 3, 3, 3, 2, 3, 3, 3, 2],
    [2, 2, 3, 3, 3, 3, 4, 4, 2, 2, 3, 3, 3, 3, 4, 4],
    [2, 3, 2, 3, 3, 4, 3, 4, 2, 3, 2, 3, 3, 4, 3, 4],
    [2, 3, 3, 2, 3, 4, 4, 3, 2, 3, 3, 2, 3, 4, 4, 3],
    [3, 2, 2, 3, 4, 3, 3, 4, 3, 2, 2, 3, 4, 3, 3, 4],
    [3, 2, 3, 2, 4, 3, 4, 3, 3, 2, 3, 2, 4, 3, 4, 3],
    [3, 3, 2, 2, 4, 4, 3, 3, 3, 3, 2, 2, 4, 4, 3, 3],
    [2, 2, 3, 3, 3, 3, 4, 4, 3, 3, 4, 4, 2, 2, 3, 3],
    [2, 3, 2, 3, 3, 4, 3, 4, 3, 4, 3, 4, 2, 3, 2, 3],
    [2, 3, 3, 2, 3, 4, 4, 3, 3, 4, 4, 3, 2, 3, 3, 2],
    [3, 2, 2, 3, 4, 3, 3, 4, 4, 3, 3, 4, 3, 2, 2, 3],
    [3, 2, 3, 2, 4, 3, 4, 3, 4, 3, 4, 3, 3, 2, 3, 2],
    [3, 3, 2, 2, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 2, 2],
    [2, 2, 2, 3, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 4],
    [2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 4, 3],
    [2, 3, 2, 2, 3, 4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3],
    [3, 2, 2, 2, 4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3],
    [3, 4, 4, 4, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3],
    [4, 3, 4, 4, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3],
    [4, 4, 3, 4, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3],
    [4, 4, 4, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2],
    [3, 3, 4, 4, 2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4],
    [3, 4, 3, 4, 2, 3, 2, 3, 2, 3, 2, 3, 3, 4, 3, 4],
    [3, 4, 4, 3, 2, 3, 3, 2, 2, 3, 3, 2, 3, 4, 4, 3],
    [4, 3, 3, 4, 3, 2, 2, 3, 3, 2, 2, 3, 4, 3, 3, 4],
    [4, 3, 4, 3, 3, 2, 3, 2, 3, 2, 3, 2, 4, 3, 4, 3],
    [4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 4, 4, 3, 3],
    [3, 3, 4, 4, 2, 2, 3, 3, 3, 3, 4, 4, 2, 2, 3, 3],
    [3, 4, 3, 4, 2, 3, 2, 3, 3, 4, 3, 4, 2, 3, 2, 3],
    [3, 4, 4, 3, 2, 3, 3, 2, 3, 4, 4, 3, 2, 3, 3, 2],
    [4, 3, 3, 4, 3, 2, 2, 3, 4, 3, 3, 4, 3, 2, 2, 3],
    [4, 3, 4, 3, 3, 2, 3, 2, 4, 3, 4, 3, 3, 2, 3, 2],
    [4, 4, 3, 3, 3, 3, 2, 2, 4, 4, 3, 3, 3, 3, 2, 2],
    [3, 3, 3, 4, 2, 2, 2, 3, 3, 3, 3, 4, 3, 3, 3, 4],
    [3, 3, 4, 3, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 4, 3],
    [3, 4, 3, 3, 2, 3, 2, 2, 3, 4, 3, 3, 3, 4, 3, 3],
    [4, 3, 3, 3, 3, 2, 2, 2, 4, 3, 3, 3, 4, 3, 3, 3],
    [3, 3, 4, 4, 3, 3, 4, 4, 2, 2, 3, 3, 2, 2, 3, 3],
    [3, 4, 3, 4, 3, 4, 3, 4, 2, 3, 2, 3, 2, 3, 2, 3],
    [3, 4, 4, 3, 3, 4, 4, 3, 2, 3, 3, 2, 2, 3, 3, 2],
    [4, 3, 3, 4, 4, 3, 3, 4, 3, 2, 2, 3, 3, 2, 2, 3],
    [4, 3, 4, 3, 4, 3, 4, 3, 3, 2, 3, 2, 3, 2, 3, 2],
    [4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2],
    [3, 3, 3, 4, 3, 3, 3, 4, 2, 2, 2, 3, 3, 3, 3, 4],
    [3, 3, 4, 3, 3, 3, 4, 3, 2, 2, 3, 2, 3, 3, 4, 3],
    [3, 4, 3, 3, 3, 4, 3, 3, 2, 3, 2, 2, 3, 4, 3, 3],
    [4, 3, 3, 3, 4, 3, 3, 3, 3, 2, 2, 2, 4, 3, 3, 3],
    [3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 4, 2, 2, 2, 3],
    [3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 2, 2, 3, 2],
    [3, 4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 2, 3, 2, 2],
    [4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 2, 2, 2],
    [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]

/-- The certificate. -/
def cert0 : Cert := (.bound [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

set_option maxRecDepth 100000 in
theorem rows0_eq : rows0 = keys0.map (rowOf 0) := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodup0 : keys0.Nodup := by decide +kernel

set_option maxRecDepth 100000 in
theorem complete0 : ∀ κ ∈ allBool (8 - 0), κ.count true = 4 → κ ∈ keys0 := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem check0 : check (4 * 3 ^ 25 + 12 * 2 ^ 25) cert0 rows0 ones16 25 = true := by
  decide +kernel

theorem keyGoal0 : KeyGoal (4 * 3 ^ 25 + 12 * 2 ^ 25) 25 0 keys0 := by
  refine ⟨nodup0, complete0, ?_⟩
  rw [← rows0_eq]
  exact check_sound _ _ _ _ _ check0

end SimpleGraph.TwoDegenerate.K2n.K2_25
