/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Reduction

/-!
# `K₂,₂₅` at four: the certificate for hub lists sharing 1 colour

Generated by `TwoDegenerate/K2n/gen_k2n.py`; checked here by the kernel. The keys are the
four-subsets of `A ∪ B` in branching order, the rows their sixteen pair values, and the
certificate a `Cert` tree (1 nodes, 1 closed by AM–GM).
-/

namespace SimpleGraph.TwoDegenerate.K2n.K2_25

/-- The four-subsets of `A ∪ B`, as membership bits, in branching order. -/
def keys1 : List (List Bool) :=
  [[true, true, true, true, false, false, false],
    [true, true, true, false, true, false, false],
    [true, true, true, false, false, true, false],
    [true, true, true, false, false, false, true],
    [true, true, false, true, true, false, false],
    [true, true, false, true, false, true, false],
    [true, true, false, true, false, false, true],
    [true, true, false, false, true, true, false],
    [true, true, false, false, true, false, true],
    [true, true, false, false, false, true, true],
    [true, false, true, true, true, false, false],
    [true, false, true, true, false, true, false],
    [true, false, true, true, false, false, true],
    [true, false, true, false, true, true, false],
    [true, false, true, false, true, false, true],
    [true, false, true, false, false, true, true],
    [true, false, false, true, true, true, false],
    [true, false, false, true, true, false, true],
    [true, false, false, true, false, true, true],
    [true, false, false, false, true, true, true],
    [false, true, true, true, true, false, false],
    [false, true, true, true, false, true, false],
    [false, true, true, true, false, false, true],
    [false, true, true, false, true, true, false],
    [false, true, true, false, true, false, true],
    [false, true, true, false, false, true, true],
    [false, true, false, true, true, true, false],
    [false, true, false, true, true, false, true],
    [false, true, false, true, false, true, true],
    [false, true, false, false, true, true, true],
    [false, false, true, true, true, true, false],
    [false, false, true, true, true, false, true],
    [false, false, true, true, false, true, true],
    [false, false, true, false, true, true, true],
    [false, false, false, true, true, true, true]]

/-- Their rows, `rowOf 1`. -/
def rows1 : List (List ℕ) :=
  [[3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3],
    [3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4],
    [3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 4, 3, 4],
    [3, 3, 3, 2, 2, 3, 3, 2, 2, 3, 3, 2, 3, 4, 4, 3],
    [3, 2, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4, 2, 2, 3, 3],
    [3, 3, 2, 3, 2, 3, 2, 3, 3, 4, 3, 4, 2, 3, 2, 3],
    [3, 3, 3, 2, 2, 3, 3, 2, 3, 4, 4, 3, 2, 3, 3, 2],
    [3, 2, 2, 3, 2, 2, 2, 3, 3, 3, 3, 4, 3, 3, 3, 4],
    [3, 2, 3, 2, 2, 2, 3, 2, 3, 3, 4, 3, 3, 3, 4, 3],
    [3, 3, 2, 2, 2, 3, 2, 2, 3, 4, 3, 3, 3, 4, 3, 3],
    [3, 2, 3, 3, 3, 3, 4, 4, 2, 2, 3, 3, 2, 2, 3, 3],
    [3, 3, 2, 3, 3, 4, 3, 4, 2, 3, 2, 3, 2, 3, 2, 3],
    [3, 3, 3, 2, 3, 4, 4, 3, 2, 3, 3, 2, 2, 3, 3, 2],
    [3, 2, 2, 3, 3, 3, 3, 4, 2, 2, 2, 3, 3, 3, 3, 4],
    [3, 2, 3, 2, 3, 3, 4, 3, 2, 2, 3, 2, 3, 3, 4, 3],
    [3, 3, 2, 2, 3, 4, 3, 3, 2, 3, 2, 2, 3, 4, 3, 3],
    [3, 2, 2, 3, 3, 3, 3, 4, 3, 3, 3, 4, 2, 2, 2, 3],
    [3, 2, 3, 2, 3, 3, 4, 3, 3, 3, 4, 3, 2, 2, 3, 2],
    [3, 3, 2, 2, 3, 4, 3, 3, 3, 4, 3, 3, 2, 3, 2, 2],
    [3, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    [4, 3, 4, 4, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3],
    [4, 4, 3, 4, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 3],
    [4, 4, 4, 3, 3, 3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2],
    [4, 3, 3, 4, 3, 2, 2, 3, 3, 2, 2, 3, 4, 3, 3, 4],
    [4, 3, 4, 3, 3, 2, 3, 2, 3, 2, 3, 2, 4, 3, 4, 3],
    [4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 4, 4, 3, 3],
    [4, 3, 3, 4, 3, 2, 2, 3, 4, 3, 3, 4, 3, 2, 2, 3],
    [4, 3, 4, 3, 3, 2, 3, 2, 4, 3, 4, 3, 3, 2, 3, 2],
    [4, 4, 3, 3, 3, 3, 2, 2, 4, 4, 3, 3, 3, 3, 2, 2],
    [4, 3, 3, 3, 3, 2, 2, 2, 4, 3, 3, 3, 4, 3, 3, 3],
    [4, 3, 3, 4, 4, 3, 3, 4, 3, 2, 2, 3, 3, 2, 2, 3],
    [4, 3, 4, 3, 4, 3, 4, 3, 3, 2, 3, 2, 3, 2, 3, 2],
    [4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2],
    [4, 3, 3, 3, 4, 3, 3, 3, 3, 2, 2, 2, 4, 3, 3, 3],
    [4, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 2, 2, 2]]

/-- The certificate. -/
def cert1 : Cert := (.bound [14, 0, 0, 0, 0, 3, 4, 4, 0, 4, 4, 4, 0, 4, 3, 4])

set_option maxRecDepth 100000 in
theorem rows1_eq : rows1 = keys1.map (rowOf 1) := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodup1 : keys1.Nodup := by decide +kernel

set_option maxRecDepth 100000 in
theorem complete1 : ∀ κ ∈ allBool (8 - 1), κ.count true = 4 → κ ∈ keys1 := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem check1 : check (4 * 3 ^ 25 + 12 * 2 ^ 25) cert1 rows1 ones16 25 = true := by
  decide +kernel

theorem keyGoal1 : KeyGoal (4 * 3 ^ 25 + 12 * 2 ^ 25) 25 1 keys1 := by
  refine ⟨nodup1, complete1, ?_⟩
  rw [← rows1_eq]
  exact check_sound _ _ _ _ _ check1

end SimpleGraph.TwoDegenerate.K2n.K2_25
