/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Reduction

/-!
# `K₂,₂₅` at four: the certificate for hub lists sharing 4 colours

Generated by `TwoDegenerate/K2n/gen_k2n.py`; checked here by the kernel. The keys are the
four-subsets of `A ∪ B` in branching order, the rows their sixteen pair values, and the
certificate a `Cert` tree (1 nodes, 0 closed by AM–GM).
-/

namespace SimpleGraph.TwoDegenerate.K2n.K2_25

/-- The four-subsets of `A ∪ B`, as membership bits, in branching order. -/
def keys4 : List (List Bool) :=
  [[true, true, true, true]]

/-- Their rows, `rowOf 4`. -/
def rows4 : List (List ℕ) :=
  [[3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3]]

/-- The certificate. -/
def cert4 : Cert := .leaf

set_option maxRecDepth 100000 in
theorem rows4_eq : rows4 = keys4.map (rowOf 4) := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodup4 : keys4.Nodup := by decide +kernel

set_option maxRecDepth 100000 in
theorem complete4 : ∀ κ ∈ allBool (8 - 4), κ.count true = 4 → κ ∈ keys4 := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem check4 : check (4 * 3 ^ 25 + 12 * 2 ^ 25) cert4 rows4 ones16 25 = true := by
  decide +kernel

theorem keyGoal4 : KeyGoal (4 * 3 ^ 25 + 12 * 2 ^ 25) 25 4 keys4 := by
  refine ⟨nodup4, complete4, ?_⟩
  rw [← rows4_eq]
  exact check_sound _ _ _ _ _ check4

end SimpleGraph.TwoDegenerate.K2n.K2_25
