#!/usr/bin/env python3
"""Generate Grid3/Three/Cert/Types.lean, Keys/K{ti}.lean (one per left type) and Keys/All.lean.

For every ordered pair of valid column types the module states `enumKeys mL mR = s` with `s` the
literal list of stored record keys in the enumerator's order (checked by `decide +kernel`), and
ties every listed key to its record theorem `cNNNN_okK` from Data/ -- its own record when the key
is the canonical member of its row-reflection orbit, the record of the reflected key
`(rtype mL, rtype mR, rM M)` otherwise. `All.lean` assembles `cert_complete`: every valid maximal
key is the symbolic U -> U key, or has a passing record, or its reflection has one.
"""
import re, sys, collections
sys.set_int_max_str_digits(0)
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from enum_replica import valid_type, mult, digit, inter, rowVecs
from mirror import rtype, rM

ROOT = Path(__file__).resolve().parents[4]
DATA = ROOT / "Grid3/Three/Cert/Data"
OUT = ROOT / "Grid3/Three/Cert/Keys"
OUT.mkdir(exist_ok=True)

# --- the bit-parallel enumerator (mirrors KeysCore.lean) ---
def digitSum(r): return sum(digit(r, q) for q in range(7))
def toBase8(r): return sum(digit(r, q) * 8 ** q for q in range(7))
def colMask8(p): return sum(7 * 8 ** q for q in range(7) if inter(p, q))
G8 = sum(4 * 8 ** q for q in range(7))
TAB = {(p, cap): [(r, toBase8(r), colMask8(p) if digitSum(r) < cap else 0) for r in rowVecs[(p, cap)]]
       for p in range(7) for cap in range(4)}
def enumRows(rvs, res, dead):
    if not rvs:
        return [0] if (res & dead) == 0 else []
    out = []
    for (r, r8, m) in rvs[0]:
        if ((res + G8 - r8) & G8) == G8:
            out.extend(r + 16384 * rest for rest in enumRows(rvs[1:], res - r8, dead | m))
    return out
def enumKeys(mL, mR): return enumRows([TAB[(p, mult(mL, p))] for p in range(7)], toBase8(mR), 0)

# --- types ---
types = [m for m in range(16384) if valid_type(m)]
assert len(types) == 39
UTYPE = 12288
checker = (ROOT / "Grid3/Three/Cert/Checker.lean").read_text()
TYPETABLE = int(re.search(r"def TYPETABLE : Nat := (\d+)", checker).group(1))
def typeIndex(m): return (TYPETABLE // 100 ** m) % 100
tidx = {m: typeIndex(m) for m in types}
assert sorted(tidx.values()) == list(range(39)), sorted(tidx.values())
byidx = {tidx[m]: m for m in types}

# --- records ---
rec = {}           # (mL, mR, M) -> (fmt, ne, blobname, okname)
files = collections.defaultdict(set)   # mL -> set of module names
for path in sorted(DATA.glob("C*.lean")):
    mod = path.stem
    for fmt, ml, mr, mat, ne, blob, ok in re.findall(
            r"theorem (c\d+_ok\d+) : checkRecord (\d+) (\d+) (\d+) (\d+) (\d+) (c\d+_b\d+) = true",
            re.sub(r"theorem (c\d+_ok\d+) : checkRecord (\d+) (\d+) (\d+) (\d+) (\d+) (c\d+_b\d+) = true",
                   lambda m: f"theorem {m.group(1)} : checkRecord {m.group(2)} {m.group(3)} {m.group(4)} {m.group(5)} {m.group(6)} {m.group(7)} = true", path.read_text())):
        pass
    for ok, fmt, ml, mr, mat, ne, blob in re.findall(
            r"theorem (c\d+_ok\d+) : checkRecord (\d+) (\d+) (\d+) (\d+) (\d+) (c\d+_b\d+) = true", path.read_text()):
        key = (int(ml), int(mr), int(mat))
        assert key not in rec
        rec[key] = (int(fmt), int(ne), blob, ok)
        files[int(ml)].add(mod)
assert len(rec) == 22157, len(rec)

# --- Types.lean ---
def lst(xs): return "[" + ", ".join(str(x) for x in xs) + "]"
quarters = [[m for m in types if 4096 * k <= m < 4096 * (k + 1)] for k in range(4)]
types_lean = f'''import Grid3.Three.Cert.Keys

/-!
# The 39 valid column types as a literal list

`validTypes_eq` is `validTypes = [...]`, kernel-checked in four quarters of the type range
(each `decide +kernel` filters 4096 packed types). Generated by
`Grid3/Three/Cert/scripts/gen_keys.py`.
-/

namespace Grid3.Three.Cert

set_option maxHeartbeats 0
set_option maxRecDepth 100000

'''
for k in range(4):
    types_lean += f"theorem validTypesFrom_{k} : validTypesFrom {4096 * k} = {lst(quarters[k])} := by\n  decide +kernel\n\n"
types_lean += f'''theorem validTypes_eq : validTypes = {lst(types)} := by
  rw [validTypes_split, validTypesFrom_0, validTypesFrom_1, validTypesFrom_2, validTypesFrom_3]
  rfl

end Grid3.Three.Cert
'''
(ROOT / "Grid3/Three/Cert/Types.lean").write_text(types_lean)

# --- K modules ---
total = 0
for ti in range(39):
    mL = byidx[ti]
    mods = sorted(files[mL])
    mods = sorted(files[mL] | files[rtype(mL)])
    lines = ["import Grid3.Three.Cert.Mirror"]
    lines += [f"import Grid3.Three.Cert.Data.{m}" for m in mods]
    lines += ["", f"/-! Seam keys with left type `{mL}` (type index {ti}): the enumeration equals the stored keys, and",
              "every stored key, or its row reflection, has a kernel-checked record. Generated by",
              "`Grid3/Three/Cert/scripts/gen_keys.py`. -/",
              "", "set_option maxHeartbeats 0", "set_option maxRecDepth 100000", "",
              "namespace Grid3.Three.Cert", f"namespace K{ti:02d}", "",
              f"theorem tL : rtype {mL} = {rtype(mL)} := by decide", ""]
    for tj in range(39):
        mR = byidx[tj]
        keys = enumKeys(mL, mR)
        total += len(keys)
        lines.append(f"def s{tj:02d} : List Nat := {lst(keys)}")
        lines.append(f"theorem e{tj:02d} : enumKeys {mL} {mR} = s{tj:02d} := by decide +kernel")
        if (mL, mR) == (UTYPE, UTYPE):
            assert len(keys) == 1
            lines.append("")
            continue
        lines.append(f"theorem t{tj:02d} : rtype {mR} = {rtype(mR)} := by decide")
        lines.append(f"theorem r{tj:02d} : ∀ M ∈ s{tj:02d}, (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt {mL} {mR} M ne blob = true)")
        lines.append(f"    ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype {mL}) (rtype {mR}) (rM M) ne blob = true) := by")
        lines.append(f"  unfold s{tj:02d}")
        for M in keys:
            if (mL, mR, M) in rec:
                fmt, ne, blob, ok = rec[(mL, mR, M)]
                lines.append(f"  refine List.forall_mem_cons.2 ⟨Or.inl ⟨{fmt}, {ne}, {blob}, by decide, {ok}⟩, ?_⟩")
            else:
                Mr = rM(M)
                fmt, ne, blob, ok = rec[(rtype(mL), rtype(mR), Mr)]
                rws = ["tL"] + ([f"t{tj:02d}"] if mR != mL else []) + [f"show rM {M} = {Mr} by decide"]
                lines.append(f"  refine List.forall_mem_cons.2 ⟨Or.inr ⟨{fmt}, {ne}, {blob}, by decide, "
                             f"by rw [{', '.join(rws)}]; exact {ok}⟩, ?_⟩")
        lines.append("  simp")
        lines.append("")
    lines.append(f"/-- every enumerated key with left type `{mL}` is the symbolic `U → U` key, has a record, or")
    lines.append("its row reflection has one -/")
    lines.append(f"theorem cover : ∀ mR ∈ validTypes, ∀ M ∈ enumKeys {mL} mR,")
    lines.append(f"    ({mL} = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt {mL} mR M ne blob = true)")
    lines.append(f"      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype {mL}) (rtype mR) (rM M) ne blob = true) := by")
    lines.append("  rw [validTypes_eq]")
    lines.append("  intro mR hmR")
    lines.append("  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmR")
    lines.append("  rcases hmR with " + " | ".join(["rfl"] * 39))
    for mR in types:   # the order of `validTypes_eq` (ascending), not type-index order
        tj = tidx[mR]
        if (mL, mR) == (UTYPE, UTYPE):
            lines.append("  · exact fun M _ => Or.inl ⟨rfl, rfl⟩")
        else:
            lines.append(f"  · intro M hM; rw [e{tj:02d}] at hM; exact Or.inr (r{tj:02d} M hM)")
    lines += ["", f"end K{ti:02d}", "end Grid3.Three.Cert", ""]
    (OUT / f"K{ti:02d}.lean").write_text("\n".join(lines))
assert total == 43737, total

# --- All.lean ---
lines = [f"import Grid3.Three.Cert.Keys.K{ti:02d}" for ti in range(39)]
lines += ["", '''/-!
# Completeness of the `k = 3` seam certificate

`cert_complete`: every valid maximal seam key `(mL, mR, M)` is the symbolic `U → U` seam, or has a
record in `Data/` that passes `checkRecord` (so that `Bridge.lean` yields its seam package), or its
row reflection `(rtype mL, rtype mR, rM M)` has one (`Reflect.lean` transports that seam back).
The 39 per-type modules identify `enumKeys mL mR` with the stored keys by `decide +kernel`;
`enumKeys_complete` (`Keys.lean`) is the structural completeness of the enumeration.
Generated by `Grid3/Three/Cert/scripts/gen_keys.py`.
-/''', "", "namespace Grid3.Three.Cert", "",
          "theorem cert_complete (mL mR M : Nat) (hLb : mL < 16384) (hRb : mR < 16384)",
          "    (hL : validType mL = true) (hR : validType mR = true) (hM : M < 16384 ^ 7)",
          "    (hv : validKey mL mR M = true) (hmax : keyMax mL mR M = true) :",
          "    (mL = UTYPE ∧ mR = UTYPE) ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt mL mR M ne blob = true)",
          "      ∨ (∃ fmt ne blob, fmt < 4 ∧ checkRecord fmt (rtype mL) (rtype mR) (rM M) ne blob = true) := by",
          "  have hmL := validType_mem_validTypes mL hLb hL",
          "  have hmR := validType_mem_validTypes mR hRb hR",
          "  have hM' := enumKeys_complete mL mR M hM hv hmax",
          "  rw [validTypes_eq] at hmL",
          "  simp only [List.mem_cons, List.mem_nil_iff, or_false] at hmL",
          "  rcases hmL with " + " | ".join(["rfl"] * 39)]
for m in types:
    lines.append(f"  · exact K{tidx[m]:02d}.cover mR hmR M hM'")
lines += ["", "end Grid3.Three.Cert", ""]
(OUT / "All.lean").write_text("\n".join(lines))
print("types (index -> packed):", [byidx[i] for i in range(39)])
print("modules per type:", {ti: len(files[byidx[ti]]) for ti in range(39)})
print("generated Types.lean, Keys/K00..K38.lean, Keys/All.lean; total keys", total)
