/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Reduction

/-!
# Types for list size 3, hub lists sharing 2 colours

Generated by `TwoDegenerate/K2n/gen_k2n.py`. The 4 `3`-subsets of `A ∪ B` as membership
bits along `A ∩ B`, `A \ B`, `B \ A`, in branching order, and their rows of `9` pair values.
-/

namespace SimpleGraph.TwoDegenerate.K2n.Data

/-- The keys. -/
def keys_3_2 : List (List Bool) :=
  [[true, true, true, false],
    [true, true, false, true],
    [true, false, true, true],
    [false, true, true, true]]

/-- Their rows, `rowOf 3 2`. -/
def rows_3_2 : List (List ℕ) :=
  [[2, 1, 2, 1, 2, 2, 1, 1, 2],
    [2, 1, 1, 1, 2, 1, 2, 2, 2],
    [2, 2, 1, 2, 3, 2, 1, 2, 1],
    [3, 2, 2, 2, 2, 1, 2, 1, 1]]

set_option maxRecDepth 100000 in
theorem rows_3_2_eq : rows_3_2 = keys_3_2.map (rowOf 3 2) := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodup_3_2 : keys_3_2.Nodup := by decide +kernel

set_option maxRecDepth 100000 in
theorem complete_3_2 :
    ∀ κ ∈ allBool (2 * 3 - 2), κ.count true = 3 → κ ∈ keys_3_2 := by
  decide +kernel

end SimpleGraph.TwoDegenerate.K2n.Data
