/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Reduction

/-!
# Types for list size 4, hub lists sharing 3 colours

Generated by `TwoDegenerate/K2n/gen_k2n.py`. The 5 `4`-subsets of `A ∪ B` as membership
bits along `A ∩ B`, `A \ B`, `B \ A`, in branching order, and their rows of `16` pair values.
-/

namespace SimpleGraph.TwoDegenerate.K2n.Data

/-- The keys. -/
def keys_4_3 : List (List Bool) :=
  [[true, true, true, true, false],
    [true, true, true, false, true],
    [true, true, false, true, true],
    [true, false, true, true, true],
    [false, true, true, true, true]]

/-- Their rows, `rowOf 4 3`. -/
def rows_4_3 : List (List ℕ) :=
  [[3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3],
    [3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 3],
    [3, 2, 3, 2, 2, 3, 3, 2, 3, 3, 4, 3, 2, 2, 3, 2],
    [3, 3, 2, 2, 3, 4, 3, 3, 2, 3, 3, 2, 2, 3, 2, 2],
    [4, 3, 3, 3, 3, 3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2]]

set_option maxRecDepth 100000 in
theorem rows_4_3_eq : rows_4_3 = keys_4_3.map (rowOf 4 3) := by decide +kernel

set_option maxRecDepth 100000 in
theorem nodup_4_3 : keys_4_3.Nodup := by decide +kernel

set_option maxRecDepth 100000 in
theorem complete_4_3 :
    ∀ κ ∈ allBool (2 * 4 - 3), κ.count true = 4 → κ ∈ keys_4_3 := by
  decide +kernel

end SimpleGraph.TwoDegenerate.K2n.Data
