/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Count
import TwoDegenerate.K2n.Keys.K3R0
import TwoDegenerate.K2n.Keys.K3R1
import TwoDegenerate.K2n.Keys.K3R2
import TwoDegenerate.K2n.Keys.K3R3

/-!
# `K₂,10` is enumeratively chromatic-choosable at 3

Generated by `TwoDegenerate/K2n/gen_k2n.py`: one certificate per overlap of the hub lists.
-/

namespace SimpleGraph.TwoDegenerate.K2n.Data

/-- Overlap 0: 1 nodes, 1 AM–GM bounds. -/
def cert_3_10_0 : Cert := (.bound [2, 2, 2, 1, 2, 2, 2, 2, 1])

set_option maxRecDepth 100000 in
theorem check_3_10_0 :
    check (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) cert_3_10_0 rows_3_0 (onesK 3) 10 = true := by
  decide +kernel

theorem keyGoal_3_10_0 : KeyGoal 3 (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) 10 0 keys_3_0 := by
  refine ⟨nodup_3_0, complete_3_0, ?_⟩
  rw [← rows_3_0_eq]
  exact check_sound _ _ _ _ _ check_3_10_0

/-- Overlap 1: 1 nodes, 1 AM–GM bounds. -/
def cert_3_10_1 : Cert := (.bound [182, 6, 6, 6, 77, 76, 6, 76, 77])

set_option maxRecDepth 100000 in
theorem check_3_10_1 :
    check (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) cert_3_10_1 rows_3_1 (onesK 3) 10 = true := by
  decide +kernel

theorem keyGoal_3_10_1 : KeyGoal 3 (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) 10 1 keys_3_1 := by
  refine ⟨nodup_3_1, complete_3_1, ?_⟩
  rw [← rows_3_1_eq]
  exact check_sound _ _ _ _ _ check_3_10_1

/-- Overlap 2: 1 nodes, 1 AM–GM bounds. -/
def cert_3_10_2 : Cert := (.bound [48, 0, 1, 0, 48, 1, 1, 1, 28])

set_option maxRecDepth 100000 in
theorem check_3_10_2 :
    check (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) cert_3_10_2 rows_3_2 (onesK 3) 10 = true := by
  decide +kernel

theorem keyGoal_3_10_2 : KeyGoal 3 (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) 10 2 keys_3_2 := by
  refine ⟨nodup_3_2, complete_3_2, ?_⟩
  rw [← rows_3_2_eq]
  exact check_sound _ _ _ _ _ check_3_10_2

/-- Overlap 3: 1 nodes, 0 AM–GM bounds. -/
def cert_3_10_3 : Cert := .leaf

set_option maxRecDepth 100000 in
theorem check_3_10_3 :
    check (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) cert_3_10_3 rows_3_3 (onesK 3) 10 = true := by
  decide +kernel

theorem keyGoal_3_10_3 : KeyGoal 3 (3 * (3 - 1) ^ 10 + 3 * (3 - 1) * (3 - 2) ^ 10) 10 3 keys_3_3 := by
  refine ⟨nodup_3_3, complete_3_3, ?_⟩
  rw [← rows_3_3_eq]
  exact check_sound _ _ _ _ _ check_3_10_3

theorem eccAt_3_10 : (completeBipartiteGraph (Fin 2) (Fin 10)).ECCAt 3 := by
  intro L hL
  rw [colConst_K2n]
  refine le_col_of_keyGoals (fun r hr => ?_) L hL
  match r, hr with
  | 0, _ => exact ⟨_, keyGoal_3_10_0⟩
  | 1, _ => exact ⟨_, keyGoal_3_10_1⟩
  | 2, _ => exact ⟨_, keyGoal_3_10_2⟩
  | 3, _ => exact ⟨_, keyGoal_3_10_3⟩

end SimpleGraph.TwoDegenerate.K2n.Data
