/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Count
import TwoDegenerate.K2n.Keys.K5R0
import TwoDegenerate.K2n.Keys.K5R1
import TwoDegenerate.K2n.Keys.K5R2
import TwoDegenerate.K2n.Keys.K5R3
import TwoDegenerate.K2n.Keys.K5R4
import TwoDegenerate.K2n.Keys.K5R5

/-!
# `K₂,19` is enumeratively chromatic-choosable at 5

Generated by `TwoDegenerate/K2n/gen_k2n.py`: one certificate per overlap of the hub lists.
-/

namespace SimpleGraph.TwoDegenerate.K2n.Data

/-- Overlap 0: 1 nodes, 1 AM–GM bounds. -/
def cert_5_19_0 : Cert := (.bound [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

set_option maxRecDepth 100000 in
theorem check_5_19_0 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_0 rows_5_0 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_0 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 0 keys_5_0 := by
  refine ⟨nodup_5_0, complete_5_0, ?_⟩
  rw [← rows_5_0_eq]
  exact check_sound _ _ _ _ _ check_5_19_0

/-- Overlap 1: 1 nodes, 1 AM–GM bounds. -/
def cert_5_19_1 : Cert := (.bound [4, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1])

set_option maxRecDepth 100000 in
theorem check_5_19_1 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_1 rows_5_1 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_1 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 1 keys_5_1 := by
  refine ⟨nodup_5_1, complete_5_1, ?_⟩
  rw [← rows_5_1_eq]
  exact check_sound _ _ _ _ _ check_5_19_1

/-- Overlap 2: 1 nodes, 1 AM–GM bounds. -/
def cert_5_19_2 : Cert := (.bound [3, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1])

set_option maxRecDepth 100000 in
theorem check_5_19_2 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_2 rows_5_2 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_2 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 2 keys_5_2 := by
  refine ⟨nodup_5_2, complete_5_2, ?_⟩
  rw [← rows_5_2_eq]
  exact check_sound _ _ _ _ _ check_5_19_2

/-- Overlap 3: 1 nodes, 1 AM–GM bounds. -/
def cert_5_19_3 : Cert := (.bound [11, 0, 0, 1, 1, 0, 11, 0, 1, 1, 0, 0, 11, 1, 1, 1, 1, 1, 5, 5, 1, 1, 0, 5, 5])

set_option maxRecDepth 100000 in
theorem check_5_19_3 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_3 rows_5_3 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_3 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 3 keys_5_3 := by
  refine ⟨nodup_5_3, complete_5_3, ?_⟩
  rw [← rows_5_3_eq]
  exact check_sound _ _ _ _ _ check_5_19_3

/-- Overlap 4: 1 nodes, 1 AM–GM bounds. -/
def cert_5_19_4 : Cert := (.bound [12, 0, 0, 0, 1, 0, 12, 0, 0, 1, 0, 0, 12, 0, 1, 0, 0, 0, 12, 1, 1, 1, 1, 1, 8])

set_option maxRecDepth 100000 in
theorem check_5_19_4 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_4 rows_5_4 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_4 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 4 keys_5_4 := by
  refine ⟨nodup_5_4, complete_5_4, ?_⟩
  rw [← rows_5_4_eq]
  exact check_sound _ _ _ _ _ check_5_19_4

/-- Overlap 5: 1 nodes, 0 AM–GM bounds. -/
def cert_5_19_5 : Cert := .leaf

set_option maxRecDepth 100000 in
theorem check_5_19_5 :
    check (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) cert_5_19_5 rows_5_5 (onesK 5) 19 = true := by
  decide +kernel

theorem keyGoal_5_19_5 : KeyGoal 5 (5 * (5 - 1) ^ 19 + 5 * (5 - 1) * (5 - 2) ^ 19) 19 5 keys_5_5 := by
  refine ⟨nodup_5_5, complete_5_5, ?_⟩
  rw [← rows_5_5_eq]
  exact check_sound _ _ _ _ _ check_5_19_5

theorem eccAt_5_19 : (completeBipartiteGraph (Fin 2) (Fin 19)).ECCAt 5 := by
  intro L hL
  rw [colConst_K2n]
  refine le_col_of_keyGoals (fun r hr => ?_) L hL
  match r, hr with
  | 0, _ => exact ⟨_, keyGoal_5_19_0⟩
  | 1, _ => exact ⟨_, keyGoal_5_19_1⟩
  | 2, _ => exact ⟨_, keyGoal_5_19_2⟩
  | 3, _ => exact ⟨_, keyGoal_5_19_3⟩
  | 4, _ => exact ⟨_, keyGoal_5_19_4⟩
  | 5, _ => exact ⟨_, keyGoal_5_19_5⟩

end SimpleGraph.TwoDegenerate.K2n.Data
