/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import TwoDegenerate.K2n.Count
import TwoDegenerate.K2n.Keys.K5R0
import TwoDegenerate.K2n.Keys.K5R1
import TwoDegenerate.K2n.Keys.K5R2
import TwoDegenerate.K2n.Keys.K5R3
import TwoDegenerate.K2n.Keys.K5R4
import TwoDegenerate.K2n.Keys.K5R5

/-!
# `K₂,31` is enumeratively chromatic-choosable at 5

Generated by `TwoDegenerate/K2n/gen_k2n.py`: one certificate per overlap of the hub lists.
-/

namespace SimpleGraph.TwoDegenerate.K2n.Data

/-- Overlap 0: 1 nodes, 1 AM–GM bounds. -/
def cert_5_31_0 : Cert := (.bound [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

set_option maxRecDepth 100000 in
theorem check_5_31_0 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_0 rows_5_0 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_0 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 0 keys_5_0 := by
  refine ⟨nodup_5_0, complete_5_0, ?_⟩
  rw [← rows_5_0_eq]
  exact check_sound _ _ _ _ _ check_5_31_0

/-- Overlap 1: 1 nodes, 1 AM–GM bounds. -/
def cert_5_31_1 : Cert := (.bound [13, 0, 0, 0, 0, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 0, 3, 3, 3, 3])

set_option maxRecDepth 100000 in
theorem check_5_31_1 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_1 rows_5_1 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_1 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 1 keys_5_1 := by
  refine ⟨nodup_5_1, complete_5_1, ?_⟩
  rw [← rows_5_1_eq]
  exact check_sound _ _ _ _ _ check_5_31_1

/-- Overlap 2: 1 nodes, 1 AM–GM bounds. -/
def cert_5_31_2 : Cert := (.bound [4, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1])

set_option maxRecDepth 100000 in
theorem check_5_31_2 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_2 rows_5_2 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_2 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 2 keys_5_2 := by
  refine ⟨nodup_5_2, complete_5_2, ?_⟩
  rw [← rows_5_2_eq]
  exact check_sound _ _ _ _ _ check_5_31_2

/-- Overlap 3: 1 nodes, 1 AM–GM bounds. -/
def cert_5_31_3 : Cert := (.bound [53, 0, 0, 1, 1, 0, 53, 0, 1, 0, 0, 0, 53, 1, 0, 1, 1, 1, 22, 22, 1, 1, 0, 22, 22])

set_option maxRecDepth 100000 in
theorem check_5_31_3 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_3 rows_5_3 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_3 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 3 keys_5_3 := by
  refine ⟨nodup_5_3, complete_5_3, ?_⟩
  rw [← rows_5_3_eq]
  exact check_sound _ _ _ _ _ check_5_31_3

/-- Overlap 4: 1 nodes, 1 AM–GM bounds. -/
def cert_5_31_4 : Cert := (.bound [106, 0, 0, 0, 1, 0, 106, 0, 0, 1, 0, 0, 106, 0, 1, 0, 0, 0, 106, 1, 1, 1, 1, 1, 80])

set_option maxRecDepth 100000 in
theorem check_5_31_4 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_4 rows_5_4 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_4 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 4 keys_5_4 := by
  refine ⟨nodup_5_4, complete_5_4, ?_⟩
  rw [← rows_5_4_eq]
  exact check_sound _ _ _ _ _ check_5_31_4

/-- Overlap 5: 1 nodes, 0 AM–GM bounds. -/
def cert_5_31_5 : Cert := .leaf

set_option maxRecDepth 100000 in
theorem check_5_31_5 :
    check (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) cert_5_31_5 rows_5_5 (onesK 5) 31 = true := by
  decide +kernel

theorem keyGoal_5_31_5 : KeyGoal 5 (5 * (5 - 1) ^ 31 + 5 * (5 - 1) * (5 - 2) ^ 31) 31 5 keys_5_5 := by
  refine ⟨nodup_5_5, complete_5_5, ?_⟩
  rw [← rows_5_5_eq]
  exact check_sound _ _ _ _ _ check_5_31_5

theorem eccAt_5_31 : (completeBipartiteGraph (Fin 2) (Fin 31)).ECCAt 5 := by
  intro L hL
  rw [colConst_K2n]
  refine le_col_of_keyGoals (fun r hr => ?_) L hL
  match r, hr with
  | 0, _ => exact ⟨_, keyGoal_5_31_0⟩
  | 1, _ => exact ⟨_, keyGoal_5_31_1⟩
  | 2, _ => exact ⟨_, keyGoal_5_31_2⟩
  | 3, _ => exact ⟨_, keyGoal_5_31_3⟩
  | 4, _ => exact ⟨_, keyGoal_5_31_4⟩
  | 5, _ => exact ⟨_, keyGoal_5_31_5⟩

end SimpleGraph.TwoDegenerate.K2n.Data
